### ISSUE TITLE
Jump between date search matches

### ISSUE THREAD

**Issue by jkyeung** [halcyon-tech/vscode-ibmi#1004]
It would be really handy to be able to jump from one match to the next or previous, analogous to the usual text search or navigating side-by-side diffs.

**Comment by worksofliam** [comment]
A good idea, but I am making the decision that we will no longer improve (but will continue to support) source dates. I think adding this feature will likely take away from other big issues we must tackle. Thanks!

**Comment by jkyeung** [comment]
Can we at least close as "not planned" instead of "completed"?
