### ISSUE TITLE
Can't enter directory name when clicking add to IFS browser button

### ISSUE THREAD

**Issue by NattyNarwhal** [halcyon-tech/vscode-ibmi#1005]
**Describe the bug**

This is a known issue, but filing for easier bookkeeping.

The prompt to select a directory when adding a directory to the browser doesn't show up when using the mouse. It however, does show up when selecting the Add to IFS Browser command from the command palette.

**To Reproduce**

1. Install the extension.
2. Add a system.
3. In the IFS Browser, click the "+" to add a new directory to the browser.
4. It only adds the current working directory (usually home), no prompt.

**Expected behavior**

The prompt to select a directory should appear.

**Environment (please complete the following information):**
 - Extension version [e.g. 0.x.x] 1.6.8
 - IBM i OS version [e.g. 7.x] multiple

**Additional context**

We managed to reproduce this on a fresh install of VS Code, so user configuration shouldn't have affected this.

**Comment by worksofliam** [comment]
@NattyNarwhal Sorry for the delay on this. Been out for a while.

Fix is in and will be released after we've had a couple more PRs merged in this week.
