### ISSUE TITLE
Should alias' and more be cleaned up?

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#1007]
**Is your feature request related to a problem? Please describe.**
Looking in library ILEDITOR I have 6116 objects most consisting of ALIAS' and outfile tables for DSPFFD.  This causes the connection step of `ls -p /QSYS.lib/ILEDITOR.lib/` to take up to 15 to 20 seconds to complete.  Looking at the source in `IBMI.ts`, it looks like it looking for `GENCMDXML.PGM` only, so it lists 6116 to find one.  

**Describe the solution you'd like**
Make a connection config option to clean up alias's owned by user.
Make a connection config option to clean up DSPFFD OUTFILES owned by user.
Make a connection config option to clean up alias's.
Make a connection config option to clean up DSPFFD OUTFILES.

**Describe alternatives you've considered**
I can clean up these items as they currently are recreated each time anyway but it would be nice to not have to go to the system and remove them myself. 

**Additional context**
Ideally, the coded step would only be producing a listing for the items interested in, so `ls -p /QSYS.lib/ILEDITOR.lib/GENCMDXML.PGM` so that you dont need to code for clean up of ALIAS' that don't fit a good common name pattern.  More importantly, if I connect after another programmer has connected and that other programmer has started editing and created temp items, I don't want those cleaned up.

**Comment by worksofliam** [comment]
@m-tyler Do you have this option enabled in the connection settings?

<img width="503" alt="image" src="https://user-images.githubusercontent.com/3708366/212088551-1e876dbf-cd8f-4d6a-8370-f939975b2cbf.png">

This should cleanup temp outfiles, but there is a reason we don't tend to clean up the aliases. It's faster than recreating them.

I do recommend a nightly job as such which could simply do this cleanup for you.

**Comment by m-tyler** [comment]
I do have that set but as you noted its not cleaning up the other work files in ILEDITOR.  My concern is that the feat of looking for GENCMDXML in ILEDITOR takes some time on my system because of the generic listing of objects in ILEDITOR just to find one item.  I have nearly 7000 left over aliases and work files from the DSFFD command.   Each of the aliases are replaced if they exist so other than authorities, its like they never existed.  While DSPFFD does reuse the work files.    Each time I make a connection to the server, which is only a few times a day normally, the amount of time delays the extension start-up for the connection.

**Comment by worksofliam** [comment]
@m-tyler Please share with me what most of the work files start with? (Or if they're completely random) We ideally want to clean those up automatically. Perhaps I am missing it in one place.

The aliases will need a though from my side. For now, I won't make any drastic changes, but you are welcome to clean them up yourself of course.

**Comment by worksofliam** [comment]
@m-tyler You are very much right and I think it's an easy change to make it look for only `GENCMDXML.PGM`. Looking into it now

**Comment by worksofliam** [comment]
Also, it looks like vscode-rpgle is not cleaning up temp files. I will add the code over there to do that also.

**Comment by m-tyler** [comment]
Nice thanks.
