### ISSUE TITLE
Settings Sync btw Mac/Win with Connection Settings

### ISSUE THREAD

**Issue by ScottKlement** [halcyon-tech/vscode-ibmi#1009]
### Discussed in https://github.com/orgs/halcyon-tech/discussions/994

<div type='discussions-op-text'>

<sup>Originally posted by **ScottKlement** December 20, 2022</sup>
I love Code's "Settings Sync" because I use 4 different computers, and switch between them often.

Problem is:  Two of them are running MacOS.

Every time I switch to a different OS, it breaks my "Connection Settings" in Code for i because the path names for the SSH keys are different on Mac vs. Windows.

For example, this works fine on MacOS:
```
        {
            "name": "i.scottklement.com",
            "host": "i.scottklement.com",
            "port": 22,
            "username": "sklement",
            "privateKey": "/Users/scott/.ssh/id_rsa"
        }

```
But then when I switch to Windows, I have to change the privateKey setting to this (don't ask why my name is "micro" -- it just is.)
```
        {
            "name": "i.scottklement.com",
            "host": "i.scottklement.com",
            "port": 22,
            "username": "sklement",
            "privateKey": "C:\\Users\\micro\\.ssh\\id_rsa"
        }

```

To solve this I've added support for ${userHome} and ${pathSeparator} values in the Connections Settings.  With this change, you can now code the following:
```
        {
            "name": "i.scottklement.com",
            "host": "i.scottklement.com",
            "port": 22,
            "username": "sklement",
            "privateKey": "${userHome}${pathSeparator}.ssh${pathSeparator}id_rsa"
        }

```

This results in a privateKey that can be used on either platform.

**Comment by ScottKlement** [comment]
PR:  https://github.com/halcyon-tech/vscode-ibmi/pull/1008
Docs PR: https://github.com/halcyon-tech/docs/pull/2

**Comment by worksofliam** [comment]
Will be available in the next release (possibly tomorrow)
