### ISSUE TITLE
Check git API usage against this blog

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#1017]
https://github.com/microsoft/vscode-discussions/discussions/421

**Comment by worksofliam** [comment]
I have checked and we do not use `refs` anywhere in our code.

@sebjulliand You should be aware of this for the future, as I imagine you will continue to use the git API.

**Comment by sebjulliand** [comment]
@worksofliam: aknowledged, thanks! 🙏🏻
