### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by Shubhra1004** [halcyon-tech/vscode-ibmi#1018]
### Discussed in https://github.com/orgs/halcyon-tech/discussions/420

<div type='discussions-op-text'>

<sup>Originally posted by **cwbuck** December  3, 2021</sup>
Is there some sort of method for debugging IBM i programs and stepping through in VS Code? Thanks!</div>

**Comment by worksofliam** [comment]
Debugging is not yet available. I suspect the desire to be released within two weeks.
