### ISSUE TITLE
Handle permission denied in IFS browser

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#1023]
```
/home/liam: ls -a -p -L /home/REINHARD/
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "ls: /home/REINHARD/: Permission denied"
}
```

<img width="431" alt="image" src="https://user-images.githubusercontent.com/3708366/214609316-30995ef1-e641-4161-8f07-ce0ff6487859.png">

**Comment by sebCIL** [comment]
@worksofliam You can close this issue. It was resolved in this PR : https://github.com/halcyon-tech/vscode-ibmi/pull/1027
