### ISSUE TITLE
After recent update cannot connect to IBM I 

### ISSUE THREAD

**Issue by GordonFenske** [halcyon-tech/vscode-ibmi#1039]
After I received an update and restarted 
I cannot see the systems that I have entered on the configuration 
![image](https://user-images.githubusercontent.com/124278198/216356575-0f099d65-edbe-4c82-9f4c-90aa90108f78.png)
I click the button nothing happens

**Comment by worksofliam** [comment]
Am currently investigating this issue too! 

After you launch VS Code, go to Help->Toggle Developer Tools, can you paste the output here?

**Comment by GordonFenske** [comment]
I hope this screenshot will help. It's on my work computer.

**Comment by worksofliam** [comment]
@GordonFenske Screenshots cannot be uploaded through emails. Please upload it on the GitHub issue itself.

Thanks.

**Comment by GordonFenske** [comment]
Here is the Console screenshot.
![image](https://user-images.githubusercontent.com/124278198/216361591-38dc534c-1956-485e-924b-997ec497a9a5.png)

**Comment by GordonFenske** [comment]
Ok very good... By the way I like what you are doing...

**Comment by worksofliam** [comment]
@GordonFenske Thank you! I am re-opening this until the bug is released.

**Comment by worksofliam** [comment]
@GordonFenske 1.6.15 is out which will solve this issue!

**Comment by GordonFenske** [comment]
Works fine now.. Thanks
