### ISSUE TITLE
Compiling error not showed into problem view for sources at workspace root directory level

### ISSUE THREAD

**Issue by angelorpa** [halcyon-tech/vscode-ibmi#1052]
When compiling sources files that are at the local workspace root dir level so the resulting errors are not listed into the problem view, so errors not appear highlighted with squiggly lines in the editor and not description showed in the corresponding line.

1. Create a directory
2. Open the directory so made it a workspace
3. Create a new source file, like hello.rpgle under workspacer root directory
4. Write some basic code with errors like missing semicolons, or whatever error you want
5. Connect to a IBM i system, so it detect the workspace 
6. Compile the code

**Expected behavior**
Errors highlighted with squiggly lines and description displayed in the corresponding line inside the editor.

**Screenshots**
Compiling the source file "D:\vs code projects\helloprj\hello.rpgle" fails because it has errors but this are not displayed into the problem view, so not highlighted in the editor.

![image](https://user-images.githubusercontent.com/10833316/218155499-ca47a0d1-2c91-4a86-81c2-9ffd390babb5.png)

If you create a new folder inside the worksapce and inside this create a new source file and compile it, if errors are produced so this are showed as spected in the problem view

![image](https://user-images.githubusercontent.com/10833316/218155287-06d9755e-ccaa-4ff9-8a02-9a0a0b9d8287.png)

**Environment**
 - Extension version 1.7.0
 - IBM i OS version 7.5 (pub400.com)

**Comment by worksofliam** [comment]
> When compiling sources files that are at the local workspace root dir level so the resulting errors are not listed into the problem view

> If you create a new folder inside the worksapce and inside this create a new source file and compile it, if errors are produced so this are showed as spected in the problem view

Errors not showing when the compile is in the root! What a fun issue. I can take a look and get back to you.

Glad you have a work around. I think this was the way I implemented it, actually.
