### ISSUE TITLE
Debug start fails

### ISSUE THREAD

**Issue by chrjorgensen** [halcyon-tech/vscode-ibmi#1053]
I try to use the new debug function, but it fails with the following error:

```
EQAVS1007E dkncbm05 on port 8005 could not be connected.
Message received: self signed certificate
```

I followed the instructions in the walk-through and had no issues during setup.
The connection to the system is done by hostnane, not ip address.

To reproduce:
- Connect to the system
- Open a RPG source member
- Click the debug icon in the top menu: 
![billede](https://user-images.githubusercontent.com/13275072/218199416-254fbc01-bd2c-4ef1-8f8d-ace086cbf76e.png)

- Enter password for system
- Press Enter to accept the default debug command for SBMJOB

Now the error shows in a pop-up window:
![billede](https://user-images.githubusercontent.com/13275072/218199596-8aa72ac4-5e62-4b75-8aa8-b460e0126e1c.png)

* QCCSID: 277
* Features:
   * git: true
   * grep: true
   * tn5250: false
   * setccsid: true
   * md5sum: true
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * startDebugService.sh: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: true

Variants
```json
{
  "american": "%23@$",
  "local": "ÆØÅ"
}
```

Errors:
```json
[
  {
    "command": "system \"DLTOBJ OBJ(ILEDITOR/O_*) OBJTYPE(*FILE)\"",
    "code": 255,
    "stderr": "CPF2125: No objects deleted.",
    "cwd": "/home/zzzzzzzzz/"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPTOIMPF in library QSYS not found.",
    "cwd": "/home/zzzzzzzzz/"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found.",
    "cwd": "/home/zzzzzzzzz/"
  }
]
```

**Comment by worksofliam** [comment]
On the device where VS Code is installed, can you ensure that there is a certificate in your home directory? The cert usually starts with the hostname.

fyi: the work around is to disable secure mode in the connection settings. Off is also the default for RDi and the ACS debugger. I was trying to be smart and have it on by default, but turns out it's riddled with problems.

Thanks,
Liam

**Comment by chrjorgensen** [comment]
Yes, there is a certificate for the system in my home directory:

![billede](https://user-images.githubusercontent.com/13275072/218204808-c984c06f-4a70-43b2-a24f-bd446f8caea5.png)

I tried the workaround and disabled secure mode. But now I get the following error:

![billede](https://user-images.githubusercontent.com/13275072/218206638-45eabd9b-81ab-45e8-86bc-28719004dfaf.png)

But the debug server was indeed running - I found the job attached to port 8005.

After enabling debug trace, I get the following output in the debug console:

```text
From client: initialize({"clientID":"vscode","clientName":"VSCodium","adapterID":"IBMiDebug","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true,"supportsArgsCanBeInterpretedByShell":true,"supportsMemoryEvent":true})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsEvaluateForHovers":true,"supportsSetVariable":true,"supportsValueFormattingOptions":true,"supportsModulesRequest":true,"supportTerminateDebuggee":true,"supportsFunctionBreakpoints":true,"supportsConfigurationDoneRequest":true}}
From client: launch({"type":"IBMiDebug","request":"launch","name":"Remote debug: Launch a batch debug session","user":"ZZZZ","password":"THISWASEDITEDOUT!","host":"dkncbm05","port":"8005","secure":false,"ignoreCertificateErrors":true,"library":"ZZZZ","program":"CL_IFS","startBatchJobCommand":"SBMJOB CMD(CALL PGM(ZZZZ/CL_IFS)) INLLIBL(QTEMP QGPL ZZZZA ZZZZTESTÆ CHKIBMPTF ZZZZTESTÅ GSMTEXT NMPAPI ZZZZ) CURLIB(ZZZZ)","updateProductionFiles":false,"trace":true,"workbenchSettings":{"connection":{"connectionPort":"8005"},"updateProductionFiles":false,"enableDebugTracing":false},"__sessionId":"58379b37-5fda-403a-afbf-1c9f9ab30da9"})
To client: {"type":"event","seq":2,"event":"initialized"}
From client: setFunctionBreakpoints({"breakpoints":[]})
To client: {"type":"response","seq":0,"request_seq":3,"success":true,"command":"setFunctionBreakpoints","body":{"breakpoints":[]}}
From client: configurationDone(undefined)
To client: {"type":"response","seq":0,"request_seq":4,"success":true,"command":"configurationDone"}
From client: threads(undefined)
To client: {"type":"response","seq":0,"request_seq":5,"success":true,"command":"threads","body":{"threads":[]}}
To client: {"type":"event","seq":6,"event":"output","body":{"category":"console","output":"IBM i Debug Server has not been started yet.\nPlease run the STRDBGSVR command from a user profile with enough authority."}}
IBM i Debug Server has not been started yet.
Please run the STRDBGSVR command from a user profile with enough authority.
To client: {"type":"response","seq":0,"request_seq":2,"success":false,"command":"launch","body":{"error":{"id":"8999","format":"IBM i Debug Server has not been started yet.\nPlease run the STRDBGSVR command from a user profile with enough authority."}}}
```

**Comment by worksofliam** [comment]
> But the debug server was indeed running - I found the job attached to port 8005.

So, I need to make sure I update the docs a little. Let me explain it best I can. From VS Code, you start the Debug Service, which uses the Debug Server (as started by `STRDBGSRV`). Doing that should then allow you to debug.

> Most browsers now prohibit calling services with self-signed certificates

Yes. I am working with the debug team to see if we can change this. It's the way that RDi and other IBM i services work, so it was developed in the same manner.

**Comment by worksofliam** [comment]
@chrjorgensen FYI. I have made the decision to have 'secure mode' off by default. This may be a silly move, and perhaps, but until the debug client (also out of my control right now) comes up with a way to make using certs easier then it will be that way. 

William Xiang from the Toronto lab also made a suggestion of using SSH Tunnels to the IBM i Debug Service instead of certs.. which is kind of an awesome idea.

Also, I hope you don't mind but I used the error you provided to add a note to the Debugging docs: https://halcyon-tech.github.io/docs/#/pages/developing/debug/debug?id=strdbgsvr-requirement

**Comment by chrjorgensen** [comment]
Yeah, I had already started the debug server from VS Code - during which it found the debug server was already running and shut it down and restarted it. So it was running - and responded to the client (VS Code), if I read the trace correctly.

But then something went wrong on the debug server - after the `threads` command from the client.

Are there some special requirements regarding threads and debugging?
___

Ah, just got your latest reply and see that the client is out of your control. And I just realize that the debug extension is from IBM, not Halcyon... so would it be better if I created the issue on the debug extension repository instead?

**Comment by worksofliam** [comment]
> Are there some special requirements regarding threads and debugging?

That's odd, no there isn't. So it still didn't debug at all even though the Debug Server (via `STRDBGSVR`) was started? Note that the Debug Server (`STRDBGSVR`) and Debug Service (Started through Code for IBM i) are different 🙃 

> And I just realize that the debug extension is from IBM, not Halcyon... so would it be better if I created the issue on the debug extension repository instead?

Sadly, there is no place other than here for debug issues (also 🙃). The Merlin/debug team suggested that I use this repo to track issues, and I decided to create a special label.

**Comment by chrjorgensen** [comment]
@worksofliam Okay, now I got it - didn't notice the Debug _Service_ and Debug _Server_ and that both should be running!

It's working now! 💥

IMHO using SSH Tunnels to the IBM i Debug Service would be great! I always use SSH instead of TLS if possible, since the certificate problems is not an issue with SSH. I fully support William Xiang!

Seems like there is still some improvements needed for the IBM i debug extension: It won't show any CL variables but refers to the "Monitor" view... which I can't find anywhere... Any ideas?

**Comment by worksofliam** [comment]
> It's working now! 💥

Woop!!

> didn't notice the Debug Service and Debug Server and that both should be running!

Yes, I updated the command text to correctly reflect this, as well as the docs.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/3708366/218232339-f08b0812-6733-4be2-9050-cb4ad43f576c.png">

Yes, SSH Tunnel support would be good. It's actually going to be implemented into Code for IBM i (as in when debug starts, spin up the tunnel automatically and shut it down when it's done) so it's something I will look into this weekend.

> Seems like there is still some improvements needed for the IBM i debug extension

If you feel comfortable, I think this issue should be closed and a new issue raised with that specific issue. It will be easier to track then!

P.S. thank you for helping me solve these initial issues so late on a Friday :)

**Comment by chrjorgensen** [comment]
> Yes, SSH Tunnel support would be good. It's actually going to be implemented into Code for IBM i (as in when debug starts, spin up the tunnel automatically and shut it down when it's done) so it's something I will look into this weekend.

This is excellent, looking forward to that!

I'll close this issue - thanks for your quick replies! And remember to enjoy and relax in the weekend...! 😃
