### ISSUE TITLE
Deploy is not working ...

### ISSUE THREAD

**Issue by christianlarsen** [halcyon-tech/vscode-ibmi#1060]
I have been trying to deploy some "old" projects using pub400.com. ... but I have been receiving an error...

This is just an example:

Current library: CLV1
Library list: CLV1 QGPL GAMES400 QTEMP
Commands:
		/QOpenSys/pkgs/bin/gmake BIN_LIB=CLV1 OPT=*EVENTF

bsh: *CURLIB=CLV1: is not an identifier
bsh: {usrprf}=CLV: is not an identifier
bsh: LOCALPATH=/Users/christianlarsen/pub400/events/qrpglesrc/events01.rpgle: is not an identifier

Fetching errors from CLV1/events01.

My makefile is:

BIN_LIB=CMPSYS
LIBLIST=$(BIN_LIB) CLV1
SHELL=/QOpenSys/usr/bin/qsh

all: events01.rpgle clevents01.clp

%.rpgle:
	system -s "CHGATR OBJ('/home/CLV/events/qrpglesrc/$*.rpgle') ATR(*CCSID) VALUE(1252)"
	liblist -a $(LIBLIST);\
	system "CRTBNDRPG PGM($(BIN_LIB)/$*) SRCSTMF('/home/CLV/events/qrpglesrc/$*.rpgle') DBGVIEW(*ALL) OPTION(*EVENTF)"

%.clp:
	system -s "CHGATR OBJ('/home/CLV/events/qclsrc/$*.clp') ATR(*CCSID) VALUE(1252)"
	liblist -a $(LIBLIST);\
	system "CRTBNDCL PGM($(BIN_LIB)/$*) SRCSTMF('/home/CLV/events/qclsrc/$*.clp') DBGVIEW(*SOURCE) OPTION(*EVENTF)"

And my actions.json. is:

[
    {
      "name": "Build and deploy with make 🔨",
      "command": "/QOpenSys/pkgs/bin/gmake BIN_LIB=&CURLIB OPT=*EVENTF",
      "environment": "pase",
      "deployFirst": true,
      "extensions": [
        "GLOBAL"
      ]
    }
  ]

**Comment by worksofliam** [comment]
Think it's got something to do with your default shell.

What is your default shell?

**Comment by worksofliam** [comment]
Found a possible bug.

**Comment by worksofliam** [comment]
Yes, there are values being passed that should not be there. Working on a fix now.

**Comment by worksofliam** [comment]
@christianlarsen 1.7.2 is being released which will fix your issue.

**Comment by worksofliam** [comment]
@2Fast2Furichous Glad to hear it! I am going to update our docs with that info since it's missing, but also add something to the extension to tell the user automatically!
