### ISSUE TITLE
Only show debug button for certain sources

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#1062]
I think our `editor/title` to launch debugging needs to be more precise about when the button shows up (e.g. more on the `when` prop): https://github.com/halcyon-tech/vscode-ibmi/blob/master/package.json#L1532

I think `editorLangId` needs to be one of the following:

* `rpgle`
* `rpg`
* `cobol` (please confirm the language ID)
* `cl` 
* C/CPP (not sure of the language id)

Something like `editorLangId ~= rpgle|rpg|cobol|cl` - I haven't tested this clause

**Comment by sebCIL** [comment]
The right syntax :
`editorLangId =~ /^rpgle$|^rpg$|^cobol$|^cl$/`

I create the [PR 1126](https://github.com/halcyon-tech/vscode-ibmi/pull/1126)
