### ISSUE TITLE
Debug service

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/vscode-ibmi#1064]
Hi, 
first of all debug is wonderful. Thank you!!!

I don't know what I'm doing wrong, but when debug start, looking at joblog I see this:

<img width="2180" alt="image" src="https://user-images.githubusercontent.com/9719313/218467666-978a6bc1-1fd3-4102-b6cf-0f76cbfcd0dc.png">

But the default of my strdbg command in qsys is:

Updprod(*YES)

I try both from local and from object browser.

In local the debug service create a file launch.json:

`{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "IBMiDebug",
      "request": "launch",
      "name": "IBM i Debug: Launch a batch debug session",
      "user": "",
      "password": "",
      "host": "",
      "port": 8005,
      "library": "",
      "program": "",
      "startBatchJobCommand": "",
      "updateProductionFiles": true
    }
  ]
}`

But when my sqlrpgle make an insert the sqlstate is equal to: 55019 .

Many thanks for your help.

**Comment by worksofliam** [comment]
Do you have 'update production files' enabled in the connection settings? After you've connected to the system, those options appear at the bottom.

**Comment by pabloto** [comment]
Hi Liam, 

Thank you for your response. now it works.

Many thanks
