### ISSUE TITLE
Diagram different between Debug Service and Debug Server

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#1068]
There is some confusion.

**Comment by chrjorgensen** [comment]
Apparantly I was not the only one confused? 😆

**Comment by worksofliam** [comment]
<img width="936" alt="image" src="https://user-images.githubusercontent.com/3708366/219087875-250a7995-2ce3-421d-b5d4-74c1c2a11ccc.png">

**Comment by worksofliam** [comment]
Also in docs now.
