### ISSUE TITLE
Local Vars not show debugging CLLE

### ISSUE THREAD

**Issue by jwoehr** [halcyon-tech/vscode-ibmi#1069]
**Describe the bug**
Local vars panel during debug of CLLE program is empty.

**To Reproduce**
1. Compile CLLE
2. Run Debug
3. Local variables panel is empty
4. Watch panel does, however, work

**Expected behavior**
See locals in local variables panel

**Screenshots**
![image](https://user-images.githubusercontent.com/4604036/218827088-58b7c3f6-309a-4a89-8834-c3f26b92aa8c.png)

**Environment (please complete the following information):**
 - IBM i Debug 1.0.0
 - IBM i OS version 7.3

**Comment by mkwan01** [comment]
This is a limitation for CL. The local variables will not show up in the Variables view for CL. You can add a local variable to the Watch view to inspect its value. The CL limitation also exists in RDi.

**Comment by jwoehr** [comment]
If you can add a CL variable to a watch, why can't there be a working CL Variables view?
Not arguing, @mkwan01 , just curious what the technical point is here!

**Comment by worksofliam** [comment]
@jwoehr Do you want to close this issue? Or do you want to leave it open as a requirement?

**Comment by jwoehr** [comment]
Probably best to leave it around so people see that it's a known issue. Up to you, my question is answered.

**Comment by worksofliam** [comment]
I will add it to the docs instead. Thanks!
