### ISSUE TITLE
Not able to open member from search results view.

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#1082]
Did the search results view change to prevent opening the members listed?  It used to in the past but it has not through several recent releases.  Maybe I just missed something?    

Double click does nothing. 
No right-click on the source member name or the matching source line. 
No errors I could find.

Thanks.

**Comment by worksofliam** [comment]
Seems to work for me.

<img width="1811" alt="image" src="https://user-images.githubusercontent.com/3708366/220212435-50b3c80a-6052-4019-b86d-584748b2c0d5.png">

Open your dev tools up (Help -> Toggle Developer Tools). When you click on an item, do you get any messages in there? (I am getting vscode-db2i messages, but you can ignore them!)

**Comment by m-tyler** [comment]
I get this.

![image](https://user-images.githubusercontent.com/1353665/220212952-f17e3203-0db9-4eae-875d-479e84b0bf18.png)

Looks like the IASP isn't being prepended correctly.

**Comment by worksofliam** [comment]
Oohh!!! 

Is this an iASP you've got configured in the connection settings?

**Comment by worksofliam** [comment]
Also, it says 'streamfile' in your screenshot and member in your original issue? I assume this is happening from the Object Browser and not the IFS Browser?

**Comment by m-tyler** [comment]
When use the connection setting view, I get this now.
![image](https://user-images.githubusercontent.com/1353665/220213314-e87236ff-3670-4283-bfdd-7de34cfb544a.png)

This is what i think you are asking about.

![image](https://user-images.githubusercontent.com/1353665/220213400-f01cbf78-f935-46e9-99eb-be0c164f8432.png)


FYI, I just upgraded to V1.7.4.

**Comment by m-tyler** [comment]
The screen capture is from the dev tools you asked me to open.  When I double-click on a search reference that error appears.

**Comment by worksofliam** [comment]
@m-tyler Are you suggesting the extension no longer works at all for you?

**Comment by m-tyler** [comment]
Sorry I meant to add I double-click from within the search results.   All my code is located in the QSYS file system.

**Comment by worksofliam** [comment]
@m-tyler Do you have SQL enabled or disabled?

**Comment by m-tyler** [comment]
The extension is working just fine.  I just retried to open the setting view to capture an image for you and I received that error instead.  It appears regardless of connected to the server or not.  

I do have SQL enabled.

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the list doesn't appear.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by m-tyler** [comment]
[search_results_open_attempt_Code_for_IBM_i_Log.txt](https://github.com/halcyon-tech/vscode-ibmi/files/10788408/search_results_open_attempt_Code_for_IBM_i_Log.txt)
Here is that log but nothing appears in the log when I try to open a result from the search results.

**Comment by worksofliam** [comment]
@m-tyler Correct, but it confirms to me where the issue is.

I can see `grep` is including the iASP, but the open function is not:

```
/usr/bin/grep -inHR -F "hspecle" /WIASP/QSYS.LIB/PGMT.LIB/qrpgsrc.FILE/*.MBR
```

**Comment by worksofliam** [comment]
@m-tyler Unless you're willing to meet me tomorrow to look into this, it could be a few days before I gain access to a system with an iASP setting and is not QCCSID 65535 (so I can accurately recreate your situation).

**Comment by worksofliam** [comment]
Also, if you have SQL, try setting the custom 'Source ASP' setting to blank and let the database figure out what the ASP is. I wonder if that will do the trick in the mean time.

**Comment by worksofliam** [comment]
@m-tyler I am totally curious, but don't think it will be the case: if you downgrade to a previous version of the extension, does it work again? I am doubtful but of course love to be told otherwise! :D

**Comment by m-tyler** [comment]
Searching is working and always have (for me anyway).  

It's just the open member from search actually has not been working for a few releases for me, I just haven't needed it enough to report it.  

Today I downgraded from 1.7.4 to 1.7.3 and it still does not work.  I could downgrade until I see it working again.  I have some extra time that I don't need VS  Code for development.

In the meantime, I removed the specific IASP.
![image](https://user-images.githubusercontent.com/1353665/220378580-421de678-2a04-42b9-a0d9-0b80bd1bcd71.png)

And it still shows it's trying to open the member the same way. Debug console shows the attempt again.
![image](https://user-images.githubusercontent.com/1353665/220378683-2dbd2f23-00f4-4dd4-81cf-dfa48ac8dfde.png)
(Note: I completely restarted VS Code after changing the IASP setting)

I open VS Code over a network share folder from our dev IBM i so that I can create notes for a variety of changes I do.  I am not sure if this is an issue but any information is important until its not. 

 It's not a 65535 issue as we changed all our source files a few years ago to 37.  

Is there a cache to the product I should clear that could cause this problem?  

This is not an urgent issue for me as I have alternatives for the open member in search results.  I'll try a few other things and report back if I see anything different if you have not noticed the reason for the issue appearing now.

**Comment by m-tyler** [comment]
I found a copy of 1.6.7 (not on the version history of the marketplace).
The same results occur with the open member from search results.

Looking over the code for `IASP`,  I found this line.
![image](https://user-images.githubusercontent.com/1353665/220386634-af7f1496-bda4-4e06-ada1-142e2f43b295.png)

This expression does not match the leading IASP of the IFS QSYS path name.
/(?:\/QSYS\.LIB\/)|(?:\.LIB)|(?:\.FILE)|(?:\.MBR)/g

![image](https://user-images.githubusercontent.com/1353665/220387310-4ae81b5f-9e22-4fc5-ae8d-185150b5a0ee.png)
Note: I added the case-insensitive option for the demo.

**Comment by m-tyler** [comment]
This expression seems to capture the leading iASP.
`(?:\/\w{1,10})|(?:\/QSYS\.LIB\/)|(?:\.LIB)|(?:\.FILE)|(?:\.MBR)`

![image](https://user-images.githubusercontent.com/1353665/220389968-c2f7ca8b-93db-47cb-a879-d32634b3d34c.png)

**Comment by chrjorgensen** [comment]
@m-tyler I could recreate your issue by setting the initial ASP group in the job description of my user and search a library (and directory) residing in the ASP. So I made a fix in PR #1085, which is now being reviewed.

But for clarity, how do you specify your ASP setting? In the job description or by using the setting in the Code for IBM i connection setting? I think only few people have source code in an ASP, so the feature is not used (and verified) very much...

**Comment by m-tyler** [comment]
As a default for access to our IBM i systems, all JOBDs that need to use the IASP have it defined, that includes the one I use.

I have supplied the IASP, and not, in the configuration view but it does not seem to make a difference if a value is defined, at least not any more. 

Currently, its not populated.  
![image](https://user-images.githubusercontent.com/1353665/220663589-e020cd2d-e365-42e8-b430-9eb70488a0a6.png)

Here is 1.7.4 open attempt from the search results view, as seen in the developer tools. 
![image](https://user-images.githubusercontent.com/1353665/220664384-fd4f52cc-246e-4c53-994d-adedeb650135.png)

**Comment by chrjorgensen** [comment]
That's the same setup that I tested during development of PR #1085.
Please wait for the PR to be reviewed and included in a release - hopefully soon.
Or you can download and test the pull request on your own Code for IBM i instance...

**Comment by m-tyler** [comment]
Thanks for getting this fixed so fast!!
I am able to wait for the change to in the next release.
