### ISSUE TITLE
Code Coverage Right click run action does not work

### ISSUE THREAD

**Issue by priceaj** [halcyon-tech/vscode-ibmi#1091]
**Describe the bug**

Error produced when trying to run test.

**To Reproduce**
1. Go to Code Coverage 
2. Right Click on a test 
3. Click Run test 

Error running command code-coverage-ibmi.runCoverageTest: command 'code-coverage-ibmi.runCoverageTest' not found. This is likely caused by the extension that contributes code-coverage-ibmi.runCoverageTest.

**Expected behavior**
Test Runs (or re-runs)

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Latest version of extension
 - Not an IBMi problem

**Additional context**

Looks like runCoverageTest is in the package.json but not registered.

This can be worked around by expanding the test to run a test initially or clicking on "Re-run all open tests" to re-run a test. 

Either the run test option should be removed as it is confusing, or fixed

**Comment by priceaj** [comment]
#1047

**Comment by worksofliam** [comment]
@priceaj I am going to close this.

Code Coverage is due a large change. I actually removed it from the Marketplace, but is still open-source (if you want to build it / work on it). It will break by the  time 2.0.0 comes out.

After I've given some love to the database extension, I plan to circle around and re-write Code Coverage from the ground up!

Checkout the road map here: https://github.com/orgs/halcyon-tech/projects/2/views/1?filterQuery=task-repo%3A%22code-coverage-ibmi%22
