### ISSUE TITLE
Code Coverage Job Date issue

### ISSUE THREAD

**Issue by priceaj** [halcyon-tech/vscode-ibmi#1093]
This isn't a bug per se, but I wondered if anyone had any insight, and thought documenting it may be useful for anyone who comes across the issue.

When running Code Coverage, I noticed that the job was outputting an odd date (20221112) to a file, this didn't happen outside of the code coverage tool, but was causing the execution of my program to not be recorded correctly as some of the logic was based on the job date being the current date.  

I couldn't replicate the issue until I used SSH to remote onto the IBM i I was using and ran the `codecov` command using `qsh system` which caused it to occur again. 

If I SSH onto my IBMi and run:

`system dspjob | grep DATE`

I can see the Job Date is always picking up 12/11/2022

I have no idea where this date is coming from, the JOBD for the job has the date set to *SYSVAL, the QDATE sysval is set to todays date 

If anyone has any insight into what is causing this it would be good

**Comment by chrjorgensen** [comment]
The job date in an IBM i job is not changed when the time passes midnight - and this is also true for the SSH daemon job.
The date 12/11/2022 is from the day when the SSH daemon started. When you start a SSH session, a new job is submitted (spawned?) from the SSH daemon to handle your connection - and this job inherits the job date from the SSH daemon.

Your program should almost always use the system date - SYSVAL QDATE in CL or %date() in RPG. Unless you want the program to run using the day the job was submitted.

**Comment by priceaj** [comment]
Thanks! I'd not even considered that it was inheriting from the SSHd job itself! I'll get it restarted!
