### ISSUE TITLE
When Source dates on, SEU colors do not work

### ISSUE THREAD

**Issue by Siggy2k** [halcyon-tech/vscode-ibmi#1096]
**Describe the bug**
When enabling the Source dates in the connection settings (not show source dates but enable).
The hex color values get displayed as � and are one indented.
When these unrecognized values are saved, they also get changed. Because i tried to open a file with source dates on edited and saved it, then turned source dates off. Opened it again and i got these values  (in VS Code displayed as red box with "sub" written in it).

**To Reproduce**
1. Go to VS Code settings and enable basic SEU colors
2. Go to Connection settings and enable source dates
3. Connect to AS400 and open file with colors
4. change and try to save it
5. Disconnect from AS400
6. Turn off source dates in connection settings
7. Connect to AS400 and open same file with colors

**Expected behavior**
The � should be recognized as impulse to color the line, and not as real text to display

**Screenshots**
![2023-02-27 08_17_59-Window](https://user-images.githubusercontent.com/35961818/221499495-d92db7d7-ae7f-4706-972d-8107fa88f035.png)

![2023-02-27 08_14_00-Window](https://user-images.githubusercontent.com/35961818/221498934-78fb76b6-5c53-4bef-8d80-d3d2d94c3dca.png)

**Environment (please complete the following information):**
 - Extension version 1.7.4
 - IBM i OS version V7R5M0

**Comment by Siggy2k** [comment]
seems similiar to Issue#989.
CCSID = 273

**Comment by worksofliam** [comment]
As of right now there is no plans to support SEU colours while source dates are enabled.

**Comment by worksofliam** [comment]
The core team have been talking about how we could get this to work. We might have a solution for you in the coming weeks.

**Comment by chrjorgensen** [comment]
@Siggy2k I did a test of your problem - and I get the correct colours, with or without source dates enabled.
Have you checked your settings on the server - as per my answer in issue #989 ?

There are some CCSID conversions along the way from reading the source member to showing it on VS Code. The source file, your user profile / system values should all have a CCSID different from 65535 - and the SSH daemon should have the correct values.

My 7.5 system does not have any system environment variables set, just the following system values
```
QCCSID    277
QCNTRYID  DK
QLANGID   DAN
```
and the SSH daemon now runs with
```
PASE_LANG                   'DA_DK'
QIBM_PASE_CCSID             '1208'
```
This can be checked by finding the SSH daemon in QUSRWRK (function PGM-sshd), display the job and take option 22. `Display environment variables`.

**Comment by Siggy2k** [comment]
@chrjorgensen that's probably it, my user profile CCSID is set to 273, i think it's an ccsid with german characters like Ä. I am pretty inexperienced with the inner workings of a AS400, so i am hesistant to just change the value for the user ccsid (i don't know if i break something else). My company bought me a RDi license, so i probably will try that first (it's just easier everyone of my colleagues can help me, because they all use RDi).
Still thank you for your time. 
I will be checking this out after some time as alternative, because, lets be honest, VS code is just so much more comfortable and modern than this modded eclipse (my colleagues said to me "welcome to hell :)").
@worksofliam huge thanks to you as well and sry for the false alarm.
