### ISSUE TITLE
Initial Command to set environment i.e. library list by profile

### ISSUE THREAD

**Issue by JDubb-At-Nelnet** [halcyon-tech/vscode-ibmi#1098]
**Is your feature request related to a problem? Please describe.**
Problem - we would like to use a CL command supplied by LMi - ACMSLIB/ACMSLIBL - in order to set the library list upon successful connection.  A chglibl command would also be possible, as well as calling a CL program that sets the users library list using traditional library list cl commands.  Would like this to be tied to the profile - as in a separate command definition could be specified for each profile, so that when a profile changes the command for that profile runs.  This would allow easy rollout of library list changes to all developers using the tool.

**Describe the solution you'd like**
In the library list explorer, provide a new button (Initial Command) that pops open an initial command entry dialogue box.  The command would be saved to the current profile, and modifying the command after the fact would be possible via clicking the same 'initial command' button.  The initial command would run any time a new connection is made, or the user switches profile since the command is tied to individual profiles.  Any libraries in the library list set up in the users job description, or in the library list tool itself could potentially be overwritten by the initial command.

**Describe alternatives you've considered**
Tried setting a library list in .bashrc using 'cl: ACMSLIB/ACMSLIBL ....' but that doesn't work.

**Additional Context**
Other tools (rdi) allow this.

**Comment by worksofliam** [comment]
I have been trying things and I've come up with this conclusion:

We need to write a new program that takes in a user defined command, for example:

```
PRINTLIBL CMD(CHGLIBL LIBL(COOLLIB DEVLIB PRDLIB) CURLIB(WHATEVER))
```

This would

* run the provided command, which would change the library list of the job
* `PRINTLIBL` would then write the user portion and current library of the job to standard out
* Code for IBM i would read standard out and update to reflect the changes

It would be better if we can determine if this is possible entirely from a shell script, which would save a lot of effort. Will ponder that.

**Comment by worksofliam** [comment]
QSH `liblist` does not listen to changes after jobs are run.

**Comment by worksofliam** [comment]
Another idea, likely easier to implement:

SQL procedure that uses `QCMDEXC`(?) to call the provided change libl command and then returns the new library list as a result set.

**Comment by worksofliam** [comment]
This looks promising. Next step is to somehow integrate this with profiles.

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/3708366/224129563-a41ebfba-f981-
44d0-918f-29b13693e222.png">

**Comment by worksofliam** [comment]
Introducing.... Command Profiles

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/3708366/224169223-4854fa75-e726-47f7-9875-477485dd048c.png">

**Comment by worksofliam** [comment]
@m-tyler I am sure you asked for this kind of functionality before. Let me know what you think of the above screenshots.

**Comment by worksofliam** [comment]
@JDubb-At-Nelnet So here's the downlow:

* You can now create a `Command Profile` with a command to run (like `ACMSLIBL` that sets your library list)
* You will then see that Command Profile show up in the profiles view
* Toggle that profile on will run the command and set the library list + current library
* It will not change any of the filters or IFS shortcuts.

**Comment by m-tyler** [comment]
So the action used to set the *LIBL can be a user command.  If that is the case then I like this over saving the *LIBL to the profile.  I see it as adding a little extra time to the profile start up but worth it.   We use TAATOOL command CHGLBLJOBD for most of our environment *LIBL set up where *LIBLs can be dynamically specified.   I am looking forward to trying this feature out.  

Will the base profile *LIBL still be available? I have mine set how I want them by using the `USER LIBRARY LIST` view to `Change user library list`.   This made a huge difference for me as before I needed to direct edit the settings.JSON for any *LIBL changes.

If you wanted to build something that would assist users in this extension to set up the profiles with a *LIBL quickly using a *JOBD as the *LIBL source, then this SQL will grab that value.
```
SELECT   LIBRARY_LIST  
FROM QSYS2/JOB_DESCRIPTION_INFO 
where JOB_DESCRIPTION_LIBRARY = '[LIBRARY]' 
and JOB_DESCRIPTION ='[JOBD]'
;
```

As for getting the ACMS product environment *LIBL, I have mentioned before in other threads about having a version of BUILD (WBUILD) that my company added code to understand how to compile code using the ACMS command ACMSCREATE when asked for.   I used it all the time in VS Code for compiling SQL DDL objects.

**Comment by worksofliam** [comment]
> We use TAATOOL command CHGLBLJOBD for most of our environment *LIBL set up where *LIBLs can be dynamically specified.

Cool! That's exactly the use case here. Here's an example of how this would work from a Command Profile.

<img width="902" alt="image" src="https://user-images.githubusercontent.com/3708366/224195128-ff38444d-52fb-4e1a-99bb-dab978a2ff50.png">

> Will the base profile *LIBL still be available?

Nothing is being removed. We are just adding the additional profile type. You can also reset the library list back to the default by doing this:

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/3708366/224194738-641d8189-1155-4b45-9e55-d1c62d306455.png">

Perhaps in the future we could add a JOBD Profile which would work as you describe.
