### ISSUE TITLE
API to do member/IFS resolves

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#1106]
These will be methods in `IBMiContent` that uses either `/usr/bin/find` or `/QOpenSys/pkgs/bin/find` to find streamfiles and members. `/usr/bin` is preferred because it tends to always be there.

They will not error but they can return undefined if nothing is found. I am using `content.resolve.` here, but this is just an idea and not a requirement.

QSYS lookup:

```ts
const path: IBMiMember|undefined = await content.resolve.qsys(`mbrnam`, [
  {library: `LIBA`, file: `QRPGLEREF`},
  {library: `LIBB`, file: `QRPGLEREF`},
  {library: `LIBC`, file: `QRPGLEREF`},
]);
```

Might look something like this:

```
-bash-5.1$ /usr/bin/find /QSYS.LIB/LIAMA.LIB/QRPGLESRC.FILE/ /QSYS.LIB/LIAMA.LIB/QRPGLEREF.FILE -name 'BADEMPS.*'
/QSYS.LIB/LIAMA.LIB/QRPGLESRC.FILE/BADEMPS.MBR
```

IFS lookup:

```ts
const path: string|undefined = await content.resolve.ifs(`file.txt`, [`/path/to/dir`, `/another/path/`]);
```

**Comment by edmundreinhardt** [comment]
Looks good
I assume that in the example we mean LIBA and LIBC and LIBC

**Comment by edmundreinhardt** [comment]
The IFS resolver will need to handle multiple file extensions in the search
I.e.  .rpgle .rpgleinc .sqlrpgle .sqlrpgleinc
