### ISSUE TITLE
Project profile per workspace folder

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#1108]
Related to #1107

Settings inherited from `.env` and `iproj.json`

**Comment by ChrisHird** [comment]
Liam,  will this be the same as RDi workspaces? I am trying to get away from RDi and one of the tools I use a lot to help with product development is the use of workspaces in RDi as I can set up the development environment using library lists and compile commands specific to the product build.

**Comment by worksofliam** [comment]
> will this be the same as RDi workspaces?

I have no idea since I don't know how to compare the two anymore. I will say, for what you're trying to do is to use [Profiles](https://halcyon-tech.github.io/docs/#/pages/settings/profiles), which will allow you to setup different environment configurations (which have their own libl, curlib, etc)

**Comment by ChrisHird** [comment]
Thanks Liam I will take a look at profiles.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ChrisHird** [comment]
The Profiles option does not seem to work and no errors? I tried to add one when the popup window appeared but nothing happened and no profile list is displayed in the view?

Chris…

**Comment by pabloto** [comment]
Could I set the deploy workspace location into a profile? 

Could I bind the profile to a specific branch? so that when I switch between branch I could set a different current library and deploy workspace location?

Thank you

**Comment by worksofliam** [comment]
We won't be doing it like this anymore. Local workspaces can have two local environment variables in `.env` which can control the compiles from that workspace: `CURLIB` and `LIBL`. I will document those.
