### ISSUE TITLE
Error when attempting source search

### ISSUE THREAD

**Issue by JonFP** [halcyon-tech/vscode-ibmi#1116]
Type: <b>Bug</b>

From a filtered list of source files I request a search from the context menu.

Complete the prompt for the search string.

The "Everything is wonderful" dialog quickly pops up and is then replaced by an error dialog which states:

Error searching source members: Error: grep: 001-2113 Error found getting information for object /QSYS.LIB/PARTNER400.LIB/answersrc.FILE/.MBR. No such path or directory.

Sometimes search works - other times it doesn't. Can't see any commonality between those source files where is works and those where it doesn't.

Extension version: 1.7.4
VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id f1b2e480-027a-4ea4-83b7-42b011bbc501|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
6233i204:30672705
funwalk2cf:30676044
pythonms35cf:30676801

```

</details>

**Comment by worksofliam** [comment]
@JonFP any chance you can recreate with `QSYSINC/H`? This is usually a source file we all have, which will make it easier for us to recreate your issue.

Also, what's a typical search term like for you?

**Comment by JonFP** [comment]
The simple answer is that I have tried a couple of different source files in QSYSINC and cannot get it to fail.

Queries are nothing special.  This morning I tried to search for a subprocedure name and also the word subfile.  The subprocedure name worked on one source file but failed on two others. Right now I can get it to fail on QRPGLESRC!

**Comment by worksofliam** [comment]
@JonFP Any special characters in your search value?

**Comment by JonFP** [comment]
None, nada, rien.  

I did a quick video for you - which interestingly demonstrated that I can get more than one type of error!

You can see it here: https://www.screencast.com/t/A7f4xcPuqukt

**Comment by chrjorgensen** [comment]
Hi @JonFP and @sebjulliand 

Another valuable piece of information is the output from the Code for IBM i task, to see what's going on behind the scenes and what data is returned from the server:

![billede](https://user-images.githubusercontent.com/13275072/223709413-b17a0871-067b-43a8-935c-581bea4bec1e.png)

Go to Output and select `Code for IBM i` in the dropdown box - it is at the top of the list.
Clear the output before starting the test by clicking on the button to the right of `Code for IBM i`, run the test and send the output.

FWIW I tried to replicate the situation - same extension version 1.7.4, same sources - but I did not get the errors that @JonFP see...

**Comment by JonFP** [comment]
> Run `ls -l /QSYS.LIB/PARTNER400.LIB/answersrc.FILE > /tmp/list.txt`

total 160
-rwx---rwx 1 paris 0 15198 Jan 16  2012 BSEARCH1.MBR
-rwx---rwx 1 paris 0 14382 Nov 29  2017 BSEARCH1F.MBR
-rwx---rwx 1 paris 0   918 Dec 21 18:37 PLAY.MBR
-rwx---rwx 1 paris 0  9894 Nov  8  2017 PRINTXML.MBR
-rwx---rwx 1 paris 0  9792 Nov  8  2017 PRINTXMLF.MBR
-rwx---rwx 1 paris 0  2244 May 31  2019 TEMP.MBR

> If you can do the same with `/QSYS.LIB/HTTPAPI.LIB/QRPGLESRC.FILE`

It is LIBHTTP actually - but here it is:

total 5488
-rwx---rwx 1 qpgmr 0  75276 Jun  4  2020 CCSIDR4.MBR
-rwx---rwx 1 qpgmr 0  69360 Oct 12  2020 CHANGELOG.MBR
-rwx---rwx 1 qpgmr 0 228990 Sep  2  2020 COMMSSLR4.MBR
-rwx---rwx 1 qpgmr 0 111486 Sep  2  2020 COMMTCPR4.MBR
-rwx---rwx 1 qpgmr 0  12954 Jun  4  2020 COMM_H.MBR
-rwx---rwx 1 qpgmr 0  78540 Jun  4  2020 COMPATR4.MBR
-rwx---rwx 1 qpgmr 0  39882 Jun  4  2020 CONFIGR4.MBR
-rwx---rwx 1 qpgmr 0  12240 Mar 15  2021 CONFIG_H.MBR
-rwx---rwx 1 qpgmr 0  62934 Jun  4  2020 DECODERR4.MBR
-rwx---rwx 1 qpgmr 0 139026 Jun  4  2020 ENCODERR4.MBR
-rwx---rwx 1 qpgmr 0  59976 Jun  4  2020 ENCRYPTR4.MBR
-rwx---rwx 1 qpgmr 0  35292 Jun  4  2020 ERRNO_H.MBR
-rwx---rwx 1 qpgmr 0  10200 Jun 24  2017 EXAMPLE1.MBR
-rwx---rwx 1 qpgmr 0  13566 Nov  6  2009 EXAMPLE10.MBR
-rwx---rwx 1 qpgmr 0  19890 Nov 25  2008 EXAMPLE11.MBR
-rwx---rwx 1 qpgmr 0  12240 Jun 26  2009 EXAMPLE12.MBR
-rwx---rwx 1 qpgmr 0   8160 Jul  1  2021 EXAMPLE13.MBR
-rwx---rwx 1 qpgmr 0  25602 Nov  6  2009 EXAMPLE14.MBR
-rwx---rwx 1 qpgmr 0  13566 Feb 21  2017 EXAMPLE15.MBR
-rwx---rwx 1 qpgmr 0   7956 Mar  6  2017 EXAMPLE16.MBR
-rwx---rwx 1 qpgmr 0  29274 Nov  6  2009 EXAMPLE17.MBR
-rwx---rwx 1 qpgmr 0  13668 Mar  4  2017 EXAMPLE18.MBR
-rwx---rwx 1 qpgmr 0    306 Nov  6  2009 EXAMPLE19.MBR
-rwx---rwx 1 qpgmr 0  17442 Sep 13 19:47 EXAMPLE2.MBR
-rwx---rwx 1 qpgmr 0    204 Nov  6  2009 EXAMPLE20.MBR
-rwx---rwx 1 qpgmr 0    408 May 19  2010 EXAMPLE21.MBR
-rwx---rwx 1 qpgmr 0    204 Nov  6  2009 EXAMPLE22.MBR
-rwx---rwx 1 qpgmr 0  19992 Nov  6  2009 EXAMPLE23.MBR
-rwx---rwx 1 qpgmr 0  26112 Feb  2  2016 EXAMPLE24.MBR
-rwx---rwx 1 qpgmr 0  21012 Jan  2  2015 EXAMPLE25.MBR
-rwx---rwx 1 qpgmr 0  27744 Jan  2  2015 EXAMPLE26.MBR
-rwx---rwx 1 qpgmr 0  25194 Jan  2  2015 EXAMPLE27.MBR
-rwx---rwx 1 qpgmr 0  16218 Feb 21  2017 EXAMPLE3.MBR
-rwx---rwx 1 qpgmr 0  22134 Jan  2  2015 EXAMPLE35.MBR
-rwx---rwx 1 qpgmr 0  26418 Jan  2  2015 EXAMPLE37.MBR
-rwx---rwx 1 qpgmr 0  41820 Jan  2  2015 EXAMPLE38.MBR
-rwx---rwx 1 qpgmr 0  15402 Feb 21  2017 EXAMPLE4.MBR
-rwx---rwx 1 qpgmr 0  14280 Aug 15  2019 EXAMPLE40.MBR
-rwx---rwx 1 qpgmr 0  18768 Aug 15  2019 EXAMPLE41.MBR
-rwx---rwx 1 qpgmr 0  17034 Nov 30  2009 EXAMPLE5.MBR
-rwx---rwx 1 qpgmr 0   2040 Dec  2  2009 EXAMPLE6.MBR
-rwx---rwx 1 qpgmr 0  13260 Jul 29  2009 EXAMPLE7.MBR
-rwx---rwx 1 qpgmr 0   7446 Sep  4  2007 EXAMPLE8.MBR
-rwx---rwx 1 qpgmr 0   8772 Nov  6  2009 EXAMPLE9.MBR
-rwx---rwx 1 qpgmr 0  42432 Jan 15  2016 EXPAT_H.MBR
-rwx---rwx 1 qpgmr 0 193902 Jun  4  2020 GSKSSL_H.MBR
-rwx---rwx 1 qpgmr 0 188190 Jun  4  2020 HEADERR4.MBR
-rwx---rwx 1 qpgmr 0   1428 Jan 12  2006 HEADER_H.MBR
-rwx---rwx 1 qpgmr 0 456756 Jul 23  2020 HTTPAPIR4.MBR
-rwx---rwx 1 qpgmr 0 296106 Mar 21  2021 HTTPAPI_H.MBR
-rwx---rwx 1 qpgmr 0  63036 Jun  4  2020 HTTPCMDR4.MBR
-rwx---rwx 1 qpgmr 0   2346 Oct 14  2008 HTTPCMD_H.MBR
-rwx---rwx 1 qpgmr 0  41412 Jun  4  2020 HTTPQSHR4.MBR
-rwx---rwx 1 qpgmr 0 103938 Jun  4  2020 HTTPUTILR4.MBR
-rwx---rwx 1 qpgmr 0 218586 Jun  4  2020 HTTPXMLR4.MBR
-rwx---rwx 1 qpgmr 0  77724 Jun  4  2020 IFSIO_H.MBR
-rwx---rwx 1 qpgmr 0   4182 Jun  4  2020 INSTALLR4.MBR
-rwx---rwx 1 qpgmr 0   2346 Jun  4  2020 LICENSE.MBR
-rwx---rwx 1 qpgmr 0  81090 Jun  4  2020 MD4R4.MBR
-rwx---rwx 1 qpgmr 0  13056 Jun  4  2020 MD4_H.MBR
-rwx---rwx 1 qpgmr 0   4182 Mar  8  2017 MSTRINGR4.MBR
-rwx---rwx 1 qpgmr 0 430032 Jun  4  2020 NTLMR4.MBR
-rwx---rwx 1 qpgmr 0    918 Jun  4  2020 NTLM_C.MBR
-rwx---rwx 1 qpgmr 0  11118 Jan  2  2015 NTLM_H.MBR
-rwx---rwx 1 qpgmr 0  88128 Jun  4  2020 NTLM_P.MBR
-rwx---rwx 1 qpgmr 0  22644 Oct  9  2017 PRIVATE_H.MBR
-rwx---rwx 1 qpgmr 0  16626 Jun  4  2020 RDWR_H.MBR
-rwx---rwx 1 qpgmr 0  40086 Jun 12  2015 README.MBR
-rwx---rwx 1 qpgmr 0  17136 Jun  4  2020 SIGNAL_H.MBR
-rwx---rwx 1 qpgmr 0 112812 Jun  4  2020 SOCKET_H.MBR
-rwx---rwx 1 qpgmr 0  33558 Jan 19  2015 XMLSTUBR4.MBR

**Comment by JonFP** [comment]
This is the output from a search for "YAJL" in ANSWESRC which errors with the "No such path ..."

/home/PARIS: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"

        SELECT
          (b.avgrowsize - 12) as MBMXRL,
          a.iasp_number as MBASP,
          cast(a.system_table_name as char(10) for bit data) AS MBFILE,
          cast(b.system_table_member as char(10) for bit data) as MBNAME,
          coalesce(cast(b.source_type as varchar(10) for bit data), '') as MBSEU2,
          coalesce(b.partition_text, '') as MBMTXT
        FROM qsys2.systables AS a
          JOIN qsys2.syspartitionstat AS b
            ON b.table_schema = a.table_schema AND
              b.table_name = a.table_name
        WHERE
          cast(a.system_table_schema as char(10) for bit data) = 'PARTNER400' 
          AND cast(a.system_table_name as char(10) for bit data) = 'ANSWERSRC'
          
          
      
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n\nMBMXRL               MBASP  MBFILE     MBNAME     MBSEU2     MBMTXT                                            \n-------------------- ------ ---------- ---------- ---------- --------------------------------------------------\n                 100      0 ANSWERSRC  PRINTXML   RPGLE      Base for Ex 2 - Process XML & print results       \n                 100      0 ANSWERSRC  BSEARCH1   RPGLE                                                        \n                 100      0 ANSWERSRC  BSEARCH1F  RPGLE                                                        \n                 100      0 ANSWERSRC  PRINTXMLF  RPGLE      Base for Ex 2 - Process XML & print results       \n                 100      0 ANSWERSRC  TEMP       RPGLE      Test contant stuff                                \n                 100      0 ANSWERSRC  PLAY       RPGLE                                                        \n\n  6 RECORD(S) SELECTED.",
    "stderr": ""
}

/home/PARIS: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT IASP_NUMBER FROM TABLE(QSYS2.LIBRARY_INFO('PARTNER400'))
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\nIASP_NUMBER \n------------\n           1\n\n  1 RECORD(S) SELECTED.",
    "stderr": ""
}

/home/PARIS: /QOpenSys/usr/bin/qsh
/usr/bin/grep -inHR -F "YAJL" /QSYS.LIB/PARTNER400.LIB/answersrc.FILE/.MBR
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "grep: 001-2113 Error found getting information for object /QSYS.LIB/PARTNER400.LIB/answersrc.FILE/.MBR. No such path or directory."
}

**Comment by JonFP** [comment]
And this is from the same search against the RPG source in LIBHTTP - which errors differently:

/home/PARIS: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"

        SELECT
          (b.avgrowsize - 12) as MBMXRL,
          a.iasp_number as MBASP,
          cast(a.system_table_name as char(10) for bit data) AS MBFILE,
          cast(b.system_table_member as char(10) for bit data) as MBNAME,
          coalesce(cast(b.source_type as varchar(10) for bit data), '') as MBSEU2,
          coalesce(b.partition_text, '') as MBMTXT
        FROM qsys2.systables AS a
          JOIN qsys2.syspartitionstat AS b
            ON b.table_schema = a.table_schema AND
              b.table_name = a.table_name
        WHERE
          cast(a.system_table_schema as char(10) for bit data) = 'LIBHTTP' 
          AND cast(a.system_table_name as char(10) for bit data) = 'QRPGLESRC'
          
          
      
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n\nMBMXRL               MBASP  MBFILE     MBNAME     MBSEU2     MBMTXT                                            \n-------------------- ------ ---------- ---------- ---------- --------------------------------------------------\n                 100      0 QRPGLESRC  GSKSSL_H   RPGLE      GSKit SSL API Header member                       \n                 100      0 QRPGLESRC  SOCKET_H   RPGLE      Header File for Sockets API                       \n                 100      0 QRPGLESRC  HTTPAPI_H  RPGLE      HTTPAPI header member                             \n                 100      0 QRPGLESRC  IFSIO_H    RPGLE      Integrated File System API Header File            \n                 100      0 QRPGLESRC  HTTPAPIR4  RPGLE      HTTP-API service program                          \n                 100      0 QRPGLESRC  ERRNO_H    RPGLE      Header for Error Handling in C/UNIX APIs          \n                 100      0 QRPGLESRC  CONFIG_H   RPGLE      HTTP-API compile-time configuration               \n                 100      0 QRPGLESRC  INSTALLR4  RPGLE      (Used during install process)                     \n                 100      0 QRPGLESRC  EXAMPLE1   RPGLE      Example of getting a PDF document                 \n                 100      0 QRPGLESRC  EXAMPLE4   RPGLE      Example: Simple POST to a cgi-script              \n                 100      0 QRPGLESRC  EXAMPLE3   RPGLE      Example of using GET with SSL                     \n                 100      0 QRPGLESRC  README     TXT        *** READ ME FIRST ***                             \n                 100      0 QRPGLESRC  EXAMPLE7   RPGLE      Example of posting using multipart/form-data      \n                 100      0 QRPGLESRC  EXAMPLE6   RPGLE      Example of using POST with SSL & raw output       \n                 100      0 QRPGLESRC  LICENSE    TXT        License info                                      \n                 100      0 QRPGLESRC  EXAMPLE10  RPGLE      Example of updating Twitter status                \n                 100      0 QRPGLESRC  EXAMPLE9   RPGLE      Example of using POST with SSL & raw output       \n                 100      0 QRPGLESRC  CHANGELOG  TXT        List of changes to HTTPAPI                        \n                 100      0 QRPGLESRC  EXAMPLE5   RPGLE      Example of supplying user/pass to HTTP server     \n                 100      0 QRPGLESRC  EXAMPLE8   RPGLE      Example of showing the download status w/xproc    \n                 100      0 QRPGLESRC  EXAMPLE12  RPGLE      Example of working with cookies                   \n                 100      0 QRPGLESRC  CONFIGR4   RPGLE      Program to display license & get config info      \n                 100      0 QRPGLESRC  EXAMPLE13  SQLRPGLE   Example of Download Currency Exchange Rates (REST)\n                 100      0 QRPGLESRC  COMM_H     RPGLE      Generic Communications API                        \n                 100      0 QRPGLESRC  COMMTCPR4  RPGLE      TCP Communication Driver                          \n                 100      0 QRPGLESRC  ENCODERR4  RPGLE      Routines for encoding HTTP data                   \n                 100      0 QRPGLESRC  PRIVATE_H  RPGLE      Global/Private HTTPAPI definitions                \n                 100      0 QRPGLESRC  COMMSSLR4  RPGLE      SSL/TLS Communication Driver                      \n                 100      0 QRPGLESRC  HTTPUTILR4 RPGLE      Misc Utilities that HTTPAPI uses                  \n                 100      0 QRPGLESRC  HTTPXMLR4  RPGLE      Routines for XML parsing with EXPAT               \n                 100      0 QRPGLESRC  EXAMPLE14  RPGLE      Example of XML Parsing UPS Package Tracking       \n                 100      0 QRPGLESRC  XMLSTUBR4  RPGLE      Stub routines                                     \n                 100      0 QRPGLESRC  EXAMPLE11  RPGLE      Example of parsing an XML document with HTTPAPI   \n                 100      0 QRPGLESRC  CCSIDR4    RPGLE      Routines for ASCII/EBCDIC translation             \n                 100      0 QRPGLESRC  SIGNAL_H   RPGLE      Signal Handling Definitions                       \n                 100      0 QRPGLESRC  HEADER_H   RPGLE      Routines for working with Headers & Cookies       \n                 100      0 QRPGLESRC  EXAMPLE16  RPGLE      Example: Consume SOAP Web service                 \n                 100      0 QRPGLESRC  EXAMPLE18  RPGLE      Example: SOAP w/longer SOAPAction                 \n                 100      0 QRPGLESRC  COMPATR4   RPGLE      Deprecated Routines required for back-compat      \n                 100      0 QRPGLESRC  EXAMPLE17  RPGLE      Example: ABA Bank Routing Number                  \n                 100      0 QRPGLESRC  EXAMPLE23  RPGLE      Example: Validate SSL Certificates                \n                 100      0 QRPGLESRC  EXAMPLE24  RPGLE      Example: Using GSKit certificate validation       \n                 100      0 QRPGLESRC  HTTPQSHR4  RPGLE      QShell interface for HTTPAPI                      \n                 100      0 QRPGLESRC  HTTPCMDR4  RPGLE      Command-line interface for HTTPAPI                \n                 100      0 QRPGLESRC  HTTPCMD_H  RPGLE      Command-line interface to HTTPAPI                 \n                 100      0 QRPGLESRC  EXAMPLE15  RPGLE                                                        \n                 100      0 QRPGLESRC  EXAMPLE19  RPGLE                                                        \n                 100      0 QRPGLESRC  EXAMPLE20  RPGLE                                                        \n                 100      0 QRPGLESRC  EXAMPLE2   RPGLE      Example: Show Status, Use Proxy                   \n                 100      0 QRPGLESRC  EXAMPLE22  RPGLE                                                        \n                 100      0 QRPGLESRC  EXAMPLE21  RPGLE                                                        \n                 100      0 QRPGLESRC  HEADERR4   RPGLE      Routines for working with Headers   Cookies       \n                 100      0 QRPGLESRC  ENCRYPTR4  RPGLE      Crypto Routines                                   \n                 100      0 QRPGLESRC  MD4R4      RPGLE      RPG Version of RSA MD4 Digest                     \n                 100      0 QRPGLESRC  MD4_H      RPGLE      Prototypes for MD4 Digest                         \n                 100      0 QRPGLESRC  NTLMR4     RPGLE      Main NTLM Authority plugin code                   \n                 100      0 QRPGLESRC  NTLM_C     RPGLE      NTLM Copyright and Version                        \n                 100      0 QRPGLESRC  NTLM_H     RPGLE      NTLM Header File                                  \n                 100      0 QRPGLESRC  NTLM_P     RPGLE      NTML Private Copybook                             \n                 100      0 QRPGLESRC  EXAMPLE25  RPGLE      Example: GET from IIS using Basic, Digest, NTLM   \n                 100      0 QRPGLESRC  EXAMPLE26  RPGLE      Example: GET with auth using persistent routines  \n                 100      0 QRPGLESRC  EXAMPLE27  RPGLE      Example: GET when you know it'll be NTLM          \n                 100      0 QRPGLESRC  EXAMPLE35  RPGLE      Example: POST with NTLM, Basic or Digest          \n                 100      0 QRPGLESRC  EXAMPLE37  RPGLE      Example: POST only NTLM                           \n                 100      0 QRPGLESRC  EXAMPLE38  RPGLE      Example: POST with NTLM                           \n                 100      0 QRPGLESRC  RDWR_H     RPGLE                                                        \n                 100      0 QRPGLESRC  MSTRINGR4  RPGLE                                                        \n                 100      0 QRPGLESRC  DECODERR4  RPGLE                                                        \n                 100      0 QRPGLESRC  EXAMPLE40  RPGLE                                                        \n                 100      0 QRPGLESRC  EXAMPLE41  RPGLE                                                        \n                 100      0 QRPGLESRC  EXPAT_H    RPGLE      RPG defs for calling eXpat                        \n\n 71 RECORD(S) SELECTED.",
    "stderr": ""
}

/home/PARIS: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT IASP_NUMBER FROM TABLE(QSYS2.LIBRARY_INFO('LIBHTTP'))
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\nIASP_NUMBER \n------------\n           1\n\n  1 RECORD(S) SELECTED.",
    "stderr": ""
}

/home/PARIS: /QOpenSys/usr/bin/qsh
/usr/bin/grep -inHR -F "YAJL" /QSYS.LIB/LIBHTTP.LIB/qrpglesrc.FILE/*.MBR
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

**Comment by sebjulliand** [comment]
Ok, I think I found out.
@JonFP , could you click on "Maintain filter" on the filter used for the search, and confirm that the "Member" field is empty for you?
![image](https://user-images.githubusercontent.com/11096890/223773350-a67bb4fb-5f02-440f-b47f-4bb79b8c6f3a.png)

According to the log you sent, this must be the case and this is what causes the error. Putting a `*` in the field will fix the problem. I could reproduce the issue on my side by emptying this field.

@worksofliam : do you want me to handle this case in a PR?

**Comment by worksofliam** [comment]
@sebjulliand feel free to do a PR. I will be able to review, test and release today.

**Comment by JonFP** [comment]
Sorry to say it - but in both cases the member filter is already set to *.

**Comment by worksofliam** [comment]
@sebjulliand Based on Jon's comments, let's do a release anyway and see if it will make a fix for him.

**Comment by JonFP** [comment]
New version has no impact on errors.

**Comment by worksofliam** [comment]
@JonFP I will DM you. Perhaps you and I can meet later this week to debug together.

**Comment by chrjorgensen** [comment]
@JonFP This is very strange... 

Your error with grep reporting "No such path or directory" occurs because there is no '*' in front of '.MBR', and the star should come from the member filter.

Some conversion is done to the member filter (because of the variant characters in EBCDIC) before handing it over to `grep`, so this _could_ be the problem. However, the conversion is always the same so it should be consistent, which your problems aren't.

I would like to see your filter config in the JSON settings:
- Press F1 and run command `Preferences: Open User Settings (JSON)`
- Search for '"HTTPAPI sources"'
- Clip and upload the JSON object containing the member filter

...and do the same for the filter '"Source files"'.

I would also like to see your language setup, so can you upload the output from Code for IBM i after (re)connect - clear the window first. The output can be quite long, so please put it into a text file and upload this file.

What is the error you get when searching in the HTTPAPI sources - TypeError?

**Comment by chrjorgensen** [comment]
@worksofliam You are as always 5 minutes in front of me...! 😆

**Comment by JonFP** [comment]
OK - this gets weirder by the minute.

In the JSON the member was not * (it was just "") - but in the dialog it showed as *.  I manually edited the JSON and that filter now works ... but ... The JSON for the HTTPAPI fileter as you can see here already includes the *
```
{
                "name": "HTTPAPI Sources",
                "library": "LIBHTTP",
                "object": "*",
                "types": [
                    "*SRCPF"
                ],
                "member": "*",
                "undefined": "HTTPAPI Sources",
                "HTTPAPI Sources": "HTTPAPI Sources"
            },
```

I'll gladly do other stuff but thought you might want to muse on this first.

**Comment by JonFP** [comment]
The error I get when searching the HTTPAPI source is:

Error searching source members: TypeError: Cannot read properties of undefined (reading 'extension')

This appears after the normal progress dialogue "Searching - fetching member list" has been active for a while.

I will post the reconnect output in a few minutes.

**Comment by JonFP** [comment]
Here you go ... all double-dutch to me.
[CodeForiConnectData.txt](https://github.com/halcyon-tech/vscode-ibmi/files/10926405/CodeForiConnectData.txt)

**Comment by JonFP** [comment]
Just went through the whole JSON config file again and the only thing I noticed was that some of the filters have a member type entry and others do not. There does not however appear to be any correlation between those filters and whether searches work or fail.

**Comment by chrjorgensen** [comment]
@JonFP There is definitely something wrong with your filter - the JSON is not correct.

I created a filter like yours, and my JSON looks like this:

```
{
"name": "HTTPAPI Sources",
"library": "LIBHTTP",
"object": "*",
"types": [
   "*SRCPF"
],
"member": "*",
"memberType": "*"
},
```

Try and edit your JSON to look like this. I suspect your extra keys `"undefined"` and `"HTTPAPI Sources"` may be causing the problem. Also check other filters causing errors for similar extra JSON keys...

**Comment by JonFP** [comment]
Interesting - all of the incorrect filters had the name of the filter duplicated at the end and the memberType was missing. In some cases, there was also an additional "undefined" entry as you noted.  Since I have never edited that file it must have somehow become corrupted over time but I have no idea how.

Anyway ... I have manually added the "memberType": "*" entry to each and e3very filter and as far as I can see they now all work.

Thanks much all for the help - it was really bugging me that it seemed so inconsistent.  Will let you all know if it goes haywire again!

**Comment by worksofliam** [comment]
@chrjorgensen @JonFP I suspect the messed up config came from the old way we used to manage config internally, but has since been cleaned up by Sebastian.

Glad to hear it's working again :)

**Comment by chrjorgensen** [comment]
@JonFP Glad we got it solved and working again.
