### ISSUE TITLE
Update UI toolkit

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#1124]
We're way behind on our UI toolkit version. This isn't a problem for security, but we may be lacking in functionality due to how our current framework is changing.

In our deps:

```js
"@bendera/vscode-webview-elements": "^0.6.3",
```

But I see that this framework [just released 0.10.1](https://github.com/bendera/vscode-webview-elements/releases), and 0.8.0 was a huge, possibly breaking change.

Now that our `CustomUI` code is really cleaned up, I wonder if it's time to start making some changes:

1. Update our version of `@bendera/vscode-webview-elements`
2. Switch to Microsoft's [vscode-webview-ui-toolkit](https://github.com/microsoft/vscode-webview-ui-toolkit)

Both might have a large impact, but if we select number 2, this is what I know:

* file selects are not fully supported
* I think we should replace our `tree` field with something else, or fully remove it. It is only used in the Actions webview.

**Comment by worksofliam** [comment]
We also use vscode-webview-ui-toolkit in [our fs extension](https://github.com/halcyon-tech/vscode-ibmi-fs), so we have a good starting place on how to use it.

**Comment by sebjulliand** [comment]
I jumped from Bendera's 0.6 to 0.8 a few weeks ago without issues. According to the changelog there are no breaking changes, as far as I can tell.
But switching to [vscode-webview-ui-toolkit](https://github.com/microsoft/vscode-webview-ui-toolkit) may be the way to go, eventually, as suggested by VSCode's UX guidelines.

**Comment by chrjorgensen** [comment]
FWIW I was fiddling with the data area edit function in vscode-ibmi-fs by @sebjulliand and tried to make the data area content shown as monospace text - but this is not supported in [vscode-webview-ui-toolkit](https://github.com/microsoft/vscode-webview-ui-toolkit).

I haven't tested that in the Bendera framework, but if it works there, I would prefer to have both...

**Comment by worksofliam** [comment]
@sebjulliand I might look into upgrading this weekend and checkout out what impact it has on us.

**Comment by chrjorgensen** [comment]
> @chrjorgensen Are you suggesting we ship both frameworks to get the most functionality out of them together?

@worksofliam Well, I already found one shortcoming in the [vscode-webview-ui-toolkit](https://github.com/microsoft/vscode-webview-ui-toolkit), so it would be a shame to not have the [functionality](https://bendera.github.io/vscode-webview-elements/components/vscode-textarea/api/) if the [Bendera framework](https://bendera.github.io/) is dropped.

**Comment by worksofliam** [comment]
@chrjorgensen I agree. webview-ui-toolkit is missing a few things still, so let's just go with the update of webview-elements!

**Comment by worksofliam** [comment]
Pending #1120, I will go ahead and update to a newer version of webview-elements. It also looks some of the tags provided by the module have changed so I will do those too.

**Comment by bendera** [comment]
> FWIW I was fiddling with the data area edit function in vscode-ibmi-fs by @sebjulliand and tried to make the data area content shown as monospace text - but this is not supported in [vscode-webview-ui-toolkit](https://github.com/microsoft/vscode-webview-ui-toolkit).
> 
> I haven't tested that in the Bendera framework, but if it works there, I would prefer to have both...

You can customize mine textarea component like this, although it isn't well documented:

```css
vscode-textarea {
  --vscode-font-family: 'Comic Sans MS';
}
```

I will update the documentation with the available CSS variables.

**Comment by chrjorgensen** [comment]
@bendera Your framework does not support `rows` and `cols` attributes on the `textarea` element, so I created [PR #48](https://github.com/bendera/vscode-webview-elements/pull/48) in your project to add this. I hope you can use my PR...

**Comment by chrjorgensen** [comment]
@worksofliam My PR for `rows` and `cols` on `textarea` was accepted and merged and a new release will be published soon... 😃

**Comment by bendera** [comment]
lol, I've just realized there is a `monospace` boolean attribute that modify the textarea to use the colors and font styles of the code editor. :facepalm:
