### ISSUE TITLE
Improve code completion

### ISSUE THREAD

**Issue by ThomasBarberot** [halcyon-tech/vscode-ibmi#1132]
In RPG sources, when there are /includes or /copy, imported variables or procedures are not proposed by the code completion.
Warning: there can be /include in members that are imported (multiple levels of inclusion)

**Comment by worksofliam** [comment]
Hi @ThomasBarberot it does!

Sadly there are limitations:

* it will only go one level deep
* it doesn't search the library list, and looks for the member in the same library if not explicitly defined (this is subject to change)

**Comment by ThomasBarberot** [comment]
Hi @worksofliam.
Your answer put me on the right track:
In MYLIB library, there is the source file QRPGLESRC.
In the source file MYLIB/QRPGLESRC, there is a member MSG_H.
In the source file MYLIB/QRPGLESRC, there is a member MYPGM.
In the member MYLIB/QRPGLESRC,MYPGM, if we do :

- **/include MSG_H**, the member to be included is not found (indicated in the tooltip when you move the mouse over it)
- **/include QRPGLESRC,MSG_H**, the member to be included is found (indicated in the tooltip when you move the mouse over it), **so the code completion works**!

I think there is a bug though, because your second point seems not to work if you don't indicate the source file (when by default it should take the same one as the one we are in, as the compilator does).
