### ISSUE TITLE
DSPF Preview tool misinterprets literals with keywords on same line

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#1133]
Recently, previewing a DSPF I noticed that a couple lines rendered wrong.  Looking at the source it happens on line where there is a literal and a keyword on same line.

demo source
```
     A          R SCRN4
     A                                 18 17'Up To' COLOR(WHT)
```

RenderedPreview
![image](https://user-images.githubusercontent.com/1353665/224761098-c2458ca0-c9b5-4f2b-bd69-4ae78c547cdf.png)

For a test case create a DSPF source with the demo source as the only value.  This is all that is needed to recreate this issue.

Thanks, Matt

This is a MEDIUM priority as I don't always a change reason to check out and modify DSPFs to split the source.

**Comment by worksofliam** [comment]
@m-tyler I've got the issue fixed. I am also making some huge improvements to the display file parser in general and now even including unit tests. Hope to get the fix out today

**Comment by worksofliam** [comment]
@m-tyler 0.1.0 of vscode-displayfile is out which will fix this problem and also finally add the hover that you suggested months and months ago.
