### ISSUE TITLE
Copying filter does not copy source filter's member type to new filter

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#1138]
I did not see this as an issue already submitted.
  VS Code version: 1.76.2
  Code for IBM i version:1.7.5

When copying a filter please populate the member type input and let me alter the value. 

Source filter.
![image](https://user-images.githubusercontent.com/1353665/225659481-ac584c11-2c86-4e30-8dc1-a28d8661b879.png)

![image](https://user-images.githubusercontent.com/1353665/225659299-22bce20e-6ab9-485b-92d6-ff8057a8845f.png)

Copying filter.
![image](https://user-images.githubusercontent.com/1353665/225659358-7fc5c42a-f988-4f28-b3fc-17a4cf50dcbc.png)

Copied to filter prompt
![image](https://user-images.githubusercontent.com/1353665/225659536-4faa125e-0e38-4eb8-ba5c-4eba3013cd64.png)

**Comment by sebjulliand** [comment]
HI @m-tyler, good finding!
The following PR has been opened to fix this issue: https://github.com/halcyon-tech/vscode-ibmi/pull/1139

**Comment by chrjorgensen** [comment]
PR #1139 has been approved and merged, this case will be closed.
