### ISSUE TITLE
Issues with actions in 1.7.7

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#1164]
I updated to 1.7.7 now I have an issue with an action that uses a variable with multiple values. 
The command log
`ACMSCHKOUT OBJ((QRPGSRC (PRP02F))) IDLIB(undefined) PROJECT(PCR2030600) DVP(PGMT) SBMJOB(*IFONLINE)`
The action
```
,
    {
      "type": "member",
      "extensions": [
        "GLOBAL"
      ],
      "environment": "ile",
      "name": "🚀ACMS: 🔽Check Out - Prompt 💬",
      "command": "ACMSCHKOUT OBJ((&OPENSPF (${MBR|Check out member|&OPENMBR}))) IDLIB(${IDLIB|Identifying Relase LIbrary|&LMI_REL_IDLIBS,}) PROJECT(${PCR|Pcr Project|PCR&PCR}) DVP(${DVPR|Check out developer|&CURLIB}) SBMJOB(*IFONLINE)"
    }
```

Visual elements have changed, which don't improve the UI for actions.

1. Action maintenance used to appear in a text box, now its just a text input.  Harder to quickly maintain.  I now have to copy text into a dummy tab, edit, copy again then replace text for action. 
![image](https://user-images.githubusercontent.com/1353665/227349875-64b559fc-2136-457b-b519-000abf59f427.png)

2. Actions with multiple values (creates a drop down box), the transparency is turned on and the information blurs with the background.
![image](https://user-images.githubusercontent.com/1353665/227348577-6c2e6b9c-83ba-4eff-bd85-153b98ce5576.png)

3. If you might be in there fixing stuff any chance to get the action name value shown above the action inputs?
`Edit Action` tab.
![image](https://user-images.githubusercontent.com/1353665/227349193-e7435a3b-dce5-4b77-af01-650f6f1846fc.png)
`Run Command` Prompt tab
![image](https://user-images.githubusercontent.com/1353665/227349383-8cf253ad-1dd1-4d88-8cb8-e9b69926606f.png)

**Comment by m-tyler** [comment]
Nice!

**Comment by worksofliam** [comment]
1.7.9 will fix number 1.

**Comment by sebjulliand** [comment]
And the PR https://github.com/halcyon-tech/vscode-ibmi/pull/1169 will fix the rest 😊
@m-tyler feel free to check out the PR description to see if it fits your request!

**Comment by m-tyler** [comment]
#1169 visually looks like it resolves the items I asked for. Yeah!!!!

Thank You!

**Comment by worksofliam** [comment]
Merged so I will close :)
