### ISSUE TITLE
Actions aren't properly saving the "type" attribute

### ISSUE THREAD

**Issue by p-behr** [halcyon-tech/vscode-ibmi#1166]
Modifications to existing actions, and new actions are not properly identified as member or streamfile types, and the actions become unusable.

* QCCSID: 37
* Features:
   * git: true
   * grep: true
   * tn5250: false
   * setccsid: true
   * md5sum: true
   * bash: true
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * startDebugService.sh: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: false

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Errors:
```json
[
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPTOIMPF in library QSYS not found.",
    "cwd": "/home/BEHR605434/builds/PCR_CCN_IBMi_Objects/"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found.",
    "cwd": "/home/BEHR605434/builds/PCR_CCN_IBMi_Objects/"
  },
  {
    "command": "export BUILDLIB=\"PCR0PRD\"

**Comment by sebjulliand** [comment]
Yep, that's a bug impacting every combobox in the UI.
I'll create a PR and it will be fixed soon 😊
