### ISSUE TITLE
Iseries source code deleted when I try to save changes

### ISSUE THREAD

**Issue by robinsonmeredeth** [halcyon-tech/vscode-ibmi#1171]
Hello, I have been using VS Code to modify RPG, LE, CL, SQL source for a few months.  Today when I attempt to save my changes, I receive a message.  Can you assist?  Thanks. 

![image](https://user-images.githubusercontent.com/128847403/227624564-2ce77942-3f0d-4552-9160-54ab44b3c89e.png)

* QCCSID: 65535
* Features:
   * git: false
   * grep: false
   * tn5250: false
   * setccsid: true
   * md5sum: false
   * bash: false
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * startDebugService.sh: false
   * iconv: true
   * attr: true
* SQL enabled: false
* Source dates enabled: true

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Errors:
```json
[
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found.",
    "cwd": "/home/robinm01"
  },
  {
    "command": "ls -p /QOpenSys/pkgs/bin/",
    "code": 2,
    "stderr": "/QOpenSys/pkgs/bin/ not found",
    "cwd": "/home/robinm01"
  },
  {
    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh",
    "code": 2,
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh not found",
    "cwd": "/home/robinm01"
  }
]
```

**Comment by worksofliam** [comment]
@robinsonmeredeth How many lines of code and what record length of the file?

**Comment by robinsonmeredeth** [comment]
Hello liam. I've modified this particular member several time over the last couple of weeks.  The problem is happening with all source members, I just gave this as an example.  I can connect to the iseries and show the source.  But when I attempt to modify it and save it, I receive the error message, which I had not earlier today. It also deletes all the lines of source code in the live member.  When I try to save, it saying the path cannot be found.

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the error appears.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by robinsonmeredeth** [comment]
[Iseries source code deleted when I try to save changes 1171.txt](https://github.com/halcyon-tech/vscode-ibmi/files/11066581/Iseries.source.code.deleted.when.I.try.to.save.changes.1171.txt)

**Comment by robinsonmeredeth** [comment]
Hello I appreciate your help.  I have a hard stop in about 20min.  I can follow up with you on Monday, if not resolved in the next few minutes. Thanks.

**Comment by worksofliam** [comment]
@robinsonmeredeth can you determine that you are on the latest version of Code for IBM i? (1.7.9+)

**Comment by worksofliam** [comment]
@robinsonmeredeth please upgrade :) clicking reload required should do the trick.

**Comment by robinsonmeredeth** [comment]
Hello, I noticed that when I sent the screen print.  I did reload but still experiencing issues.  

Here is a screen print of me trying to save a source member.  Path not found.  I can bring up source but then it loses the "reference" to the source file.  This is what it looks like to me.  I can view source but when I attempt to perform an action on the iseries to the member open, the VS Code is no longer connected to the iseries source file.  

Is this a workspace problem?   

![image](https://user-images.githubusercontent.com/128847403/227964127-555c74da-7d85-4089-a05f-df3aa6fba546.png)

**Comment by worksofliam** [comment]
@robinsonmeredeth Can you let me know how many lines of code is in a member you can't save, as well as the record length of the file?

**Comment by worksofliam** [comment]
@robinsonmeredeth 1.7.11 is out with the fix. Should be available in about 15 minutes.

**Comment by robinsonmeredeth** [comment]
Okay.  It worked. I appreciate your help.

**Comment by worksofliam** [comment]
@robinsonmeredeth Glad to hear it - sorry for the trouble!
