### ISSUE TITLE
Editor in read only

### ISSUE THREAD

**Issue by carabirubi69** [halcyon-tech/vscode-ibmi#1184]
Since last update, I only can open members in read mode... anyone else?

**Comment by worksofliam** [comment]
@carabirubi69 There are two places you should check:

* Right click on your filter and select 'Maintain Filter'. Ensure 'Protected' is turned off

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/3708366/228021130-ca75a3bf-bf7a-437f-a659-10197077224a.png">

In the connection settings, under the Source Code tab, make sure 'Read only mode' is disabled

<img width="809" alt="image" src="https://user-images.githubusercontent.com/3708366/228021254-7b0a47df-9317-4aa2-81f5-4322e00272a3.png">

**Comment by carabirubi69** [comment]
No, I have all those configurations ok...

In filter maintenance:

![imagen](https://user-images.githubusercontent.com/4659967/228025254-a65230e4-dc5c-4f77-a61e-4c32e11e5d7a.png)

In connections configurations:

![imagen](https://user-images.githubusercontent.com/4659967/228025415-677114dd-3698-4b2f-9d8f-d0ed42dbda0e.png)

When I open any source:

![imagen](https://user-images.githubusercontent.com/4659967/228025534-79844c71-f498-486b-be8f-14e201c2e7b8.png)

Thanks for trying..

**Comment by worksofliam** [comment]
@carabirubi69 please share your VS Code user configuration. 

* f1 to open the command palette 
* search 'open user settings json'
* share the opened JSON here (it doesn't contain any PII)

**Comment by worksofliam** [comment]
Is this happening for every member you open?

**Comment by carabirubi69** [comment]
Ok. There goes the JSON:

{
    "workbench.colorTheme": "Visual Studio Dark",
    "code-for-ibmi.connections": [
        {
            "name": "Cquivir",
            "host": "192.168.168.12",
            "port": 22,
            "username": "SQ61",
            "privateKey": ""
        },
        {
            "name": "NDquivir",
            "host": "192.168.168.8",
            "port": 22,
            "username": "sq61",
            "privateKey": ""
        }
    ],
    "code-for-ibmi.connectionSettings": [
        {
            "name": "Cquivir",
            "host": "",
            "objectFilters": [
                {
                    "buttons": "SAVE",
                    "name": "QRPGSRCMQ",
                    "library": "GESTPRG",
                    "object": "QRPGSRCMQ",
                    "types": [
                        "*SRCPF"
                    ],
                    "member": "*",
                    "memberType": "*"
                },
                {
                    "buttons": "SAVE",
                    "name": "Distriqvr",
                    "library": "DISTRIQVR",
                    "object": "QRPG*",
                    "types": [
                        "*SRCPF"
                    ],
                    "member": "*",
                    "memberType": "*"
                },
                {
                    "buttons": "SAVE",
                    "name": "Distriqs",
                    "library": "DISTRIQS",
                    "object": "QRPG*",
                    "types": [
                        "*SRCPF"
                    ],
                    "member": "*",
                    "memberType": "*"
                },
                {
                    "buttons": "SAVE",
                    "name": "QCLSRC",
                    "library": "GESTPRG",
                    "object": "qcl*",
                    "types": [
                        "*SRCPF"
                    ],
                    "member": "*",
                    "memberType": "*"
                }
            ],
            "libraryList": [
                "QPDA",
                "LIB80323",
                "QTEMP",
                "LIB803",
                "MQSYSF",
                "MQCONTAF",
                "MQSYS",
                "CONTPRG",
                "GESTPRG",
                "MQCONTA",
                "ZFUNC",
                "ZSNTB",
                "QGPL",
                "COBROS",
                "QBIT",
                "WEBG4R0900",
                "WG4SYSFD",
                "WGFR0900D",
                "DBLNKR0900",
                "DBLFIAS",
                "DBFR0900",
                "PRTBLR0900",
                "PRTFIAS",
                "WGCONVER",
                "DISTRIQS",
                "DISTRIQVR"
            ],
            "autoClearTempData": false,
            "customVariables": [],
            "connectionProfiles": [
                {
                    "name": "Cquivir",
                    "homeDirectory": "/home/SQ61",
                    "currentLibrary": "LIB80323",
                    "libraryList": [
                        "QPDA",
                        "LIB80323",
                        "QTEMP",
                        "LIB803",
                        "MQSYSF",
                        "MQCONTAF",
                        "MQSYS",
                        "CONTPRG",
                        "GESTPRG",
                        "MQCONTA",
                        "ZFUNC",
                        "ZSNTB",
                        "QGPL",
                        "COBROS",
                        "QBIT",
                        "WEBG4R0900",
                        "WG4SYSFD",
                        "WGFR0900D",
                        "DBLNKR0900",
                        "DBLFIAS",
                        "DBFR0900",
                        "PRTBLR0900",
                        "PRTFIAS",
                        "WGCONVER",
                        "DISTRIQS",
                        "DISTRIQVR"
                    ],
                    "objectFilters": [
                        {
                            "buttons": "SAVE",
                            "name": "QRPGSRCMQ",
                            "library": "GESTPRG",
                            "object": "QRPGSRCMQ",
                            "types": [
                                "*SRCPF"
                            ],
                            "member": "*",
                            "memberType": "*"
                        },
                        {
                            "buttons": "SAVE",
                            "name": "Distriqvr",
                            "library": "DISTRIQVR",
                            "object": "QRPG*",
                            "types": [
                                "*SRCPF"
                            ],
                            "member": "*",
                            "memberType": "*"
                        },
                        {
                            "buttons": "SAVE",
                            "name": "Distriqs",
                            "library": "DISTRIQS",
                            "object": "QRPG*",
                            "types": [
                                "*SRCPF"
                            ],
                            "member": "*",
                            "memberType": "*"
                        },
                        {
                            "buttons": "SAVE",
                            "name": "QCLSRC",
                            "library": "GESTPRG",
                            "object": "qcl*",
                            "types": [
                                "*SRCPF"
                            ],
                            "member": "*",
                            "memberType": "*"
                        }
                    ],
                    "ifsShortcuts": [
                        "/home/SQ61"
                    ],
                    "customVariables": []
                }
            ],
            "ifsShortcuts": [
                "/home/SQ61"
            ],
            "autoSortIFSShortcuts": false,
            "homeDirectory": "/home/SQ61",
            "enableSQL": false,
            "tempLibrary": "ILEDITOR",
            "tempDir": "/tmp",
            "currentLibrary": "LIB80323",
            "sourceASP": "",
            "sourceFileCCSID": "*FILE",
            "autoConvertIFSccsid": false,
            "hideCompileErrors": [],
            "enableSourceDates": true,
            "sourceDateMode": "edit",
            "sourceDateGutter": true,
            "encodingFor5250": "default",
            "terminalFor5250": "default",
            "setDeviceNameFor5250": false,
            "connectringStringFor5250": "localhost",
            "autoSaveBeforeAction": false,
            "showDescInLibList": false,
            "debugPort": "8005",
            "debugIsSecure": false,
            "debugUpdateProductionFiles": false,
            "debugEnableDebugTracing": false,
            "databaseBrowserList": [
                "LIB803"
            ],
            "buttons": "save",
            "readOnlyMode": false
        },
        {
            "name": "NDquivir",
            "host": "",
            "objectFilters": [],
            "libraryList": [
                "QGPL",
                "QTEMP"
            ],
            "autoClearTempData": false,
            "customVariables": [],
            "connectionProfiles": [],
            "ifsShortcuts": [
                "/"
            ],
            "autoSortIFSShortcuts": false,
            "homeDirectory": ".",
            "enableSQL": false,
            "tempLibrary": "ILEDITOR",
            "tempDir": "/tmp",
            "currentLibrary": "QGPL",
            "sourceASP": null,
            "sourceFileCCSID": "*FILE",
            "autoConvertIFSccsid": false,
            "hideCompileErrors": [],
            "enableSourceDates": true,
            "sourceDateMode": "edit",
            "sourceDateGutter": true,
            "encodingFor5250": "default",
            "terminalFor5250": "default",
            "setDeviceNameFor5250": false,
            "connectringStringFor5250": "localhost",
            "autoSaveBeforeAction": false,
            "showDescInLibList": false,
            "debugPort": "8005",
            "debugIsSecure": false,
            "debugUpdateProductionFiles": false,
            "debugEnableDebugTracing": false,
            "buttons": "save"
        }
    ],
    "workbench.editor.enablePreview": false,
    "code-for-ibmi.actions": [
        {
            "type": "member",
            "extensions": [
                "CBLLE",
                "CBL"
            ],
            "name": "Create Bound COBOL Program (CRTBNDCBL)",
            "command": "CRTBNDCBL (&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*SOURCE) DBGVIEW(*SOURCE)"
        },
        {
            "type": "member",
            "extensions": [
                "CBLLE",
                "CBL"
            ],
            "name": "Create Module CBLLE (CRTCBLMOD)",
            "command": "CRTCBLMOD MODULE(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*SOURCE) DBGVIEW(*SOURCE)"
        },
        {
            "type": "member",
            "extensions": [
                "RPGLE",
                "RPG"
            ],
            "name": "Create Bound RPG Program (CRTBNDRPG)",
            "command": "CRTBNDRPG PGM(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT)"
        },
        {
            "type": "member",
            "extensions": [
                "GLOBAL"
            ],
            "name": "Create Service Program (CRTSRVPGM)",
            "command": "?CRTSRVPGM SRVPGM(&OPENLIB/&OPENMBR) EXPORT(*ALL) BNDSRVPGM(*NONE) BNDDIR(*NONE) ACTGRP(*CALLER) TGTRLS(*CURRENT)"
        },
        {
            "type": "member",
            "extensions": [
                "SQLRPGLE"
            ],
            "name": "Create SQL ILE RPG Program (CRTSQLRPGI)",
            "command": "?CRTSQLRPGI OBJ(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) CLOSQLCSR(*ENDMOD) OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT)"
        },
        {
            "type": "member",
            "extensions": [
                "SQLRPGLE"
            ],
            "name": "Create SQL ILE RPG Module (CRTSQLRPGI)",
            "command": "?CRTSQLRPGI OBJ(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OBJTYPE(*MODULE) CLOSQLCSR(*ENDMOD) OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT)"
        },
        {
            "type": "member",
            "extensions": [
                "RPGLE",
                "RPG"
            ],
            "name": "Create RPG Module (CRTRPGMOD)",
            "command": "?CRTRPGMOD MODULE(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT)"
        },
        {
            "type": "member",
            "extensions": [
                "CMD"
            ],
            "name": "Create Command (CRTCMD)",
            "command": "?CRTCMD CMD(&OPENLIB/&OPENMBR) PGM(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) ALLOW(*ALL) CURLIB(*NOCHG) PRDLIB(*NOCHG)"
        },
        {
            "type": "member",
            "extensions": [
                "CMD"
            ],
            "name": "Create Command (Allow Return Variables - CRTCMD)",
            "command": "?CRTCMD CMD(&OPENLIB/&OPENMBR) PGM(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) ALLOW(ALLOW(*BPGM *IPGM *BMOD *IMOD) ) CURLIB(*NOCHG) PRDLIB(*NOCHG)"
        },
        {
            "type": "member",
            "extensions": [
                "PF",
                "LF"
            ],
            "name": "Delete File (DLTF)",
            "command": "?DLTF FILE(&OPENLIB/&OPENMBR)"
        },
        {
            "type": "member",
            "extensions": [
                "DSPF"
            ],
            "name": "Create Display File (CRTDSPF)",
            "command": "?CRTDSPF FILE(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) SRCMBR(&OPENMBR) OPTION(*EVENTF) RSTDSP(*NO) REPLACE(*YES)"
        },
        {
            "type": "member",
            "extensions": [
                "PF"
            ],
            "name": "Create Physical File (CRTPF)",
            "command": "?CRTPF FILE(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) SRCMBR(&OPENMBR) OPTION(*EVENTF) SIZE(*NOMAX) MAXMBRS(1)"
        },
        {
            "type": "member",
            "extensions": [
                "LF"
            ],
            "name": "Create Logical File (CRTLF)",
            "command": "?CRTLF FILE(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*EVENTF)"
        },
        {
            "type": "member",
            "extensions": [
                "CLP",
                "CLLE"
            ],
            "name": "Create CL Program (CRTCLP)",
            "command": "?CRTCLPGM PGM(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OUTPUT(*PRINT) REPLACE(*YES)"
        },
        {
            "type": "member",
            "extensions": [
                "CLP",
                "CLLE"
            ],
            "name": "Create Bound CL Program (CRTBNDCL)",
            "command": "?CRTBNDCL PGM(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*EVENTF) DBGVIEW(*SOURCE)"
        },
        {
            "type": "member",
            "extensions": [
                "PNLGRP"
            ],
            "name": "Create Panel Group (CRTPNLGRP)",
            "command": "?CRTPNLGRP PNLGRP(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) SRCMBR(&OPENMBR) OPTION(*EVENTF)"
        },
        {
            "type": "member",
            "extensions": [
                "GLOBAL"
            ],
            "name": "Create Program (CRTPGM)",
            "command": "?CRTPGM PGM(&OPENLIB/&OPENMBR) MODULE(*PGM) ENTMOD(*FIRST) BNDSRVPGM(*NONE) BNDDIR(*NONE) ACTGRP(*ENTMOD) TGTRLS(*CURRENT)"
        },
        {
            "type": "member",
            "extensions": [
                "SQL"
            ],
            "name": "Run SQL Statements (RUNSQLSTM)",
            "command": "?RUNSQLSTM SRCFILE(&OPENLIB/&OPENSPF) SRCMBR(&OPENMBR) COMMIT(*NONE) NAMING(*SQL)"
        },
        {
            "type": "streamfile",
            "extensions": [
                "RPGLE"
            ],
            "name": "Create Bound RPG Program (CRTBNDRPG) with inputs",
            "command": "CRTBNDRPG PGM(${buildlib|Build library|&BUILDLIB}/${objectname|Object Name|&NAME}) SRCSTMF('${sourcePath|Source path|&FULLPATH}') OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT)"
        },
        {
            "type": "streamfile",
            "extensions": [
                "RPGLE",
                "RPG"
            ],
            "name": "Create Bound RPG Program (CRTBNDRPG)",
            "command": "CRTBNDRPG PGM(&BUILDLIB/&NAME) SRCSTMF('&FULLPATH') OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT)"
        },
        {
            "type": "streamfile",
            "extensions": [
                "GLOBAL"
            ],
            "name": "Create Service Program (CRTSRVPGM)",
            "command": "?CRTSRVPGM SRVPGM(&BUILDLIB/&NAME) EXPORT(*ALL) BNDSRVPGM(*NONE) BNDDIR(*NONE) ACTGRP(*CALLER) TGTRLS(*CURRENT)"
        },
        {
            "type": "streamfile",
            "extensions": [
                "SQLRPGLE"
            ],
            "name": "Create SQL ILE RPG Program (CRTSQLRPGI)",
            "command": "?CRTSQLRPGI OBJ(&BUILDLIB/&NAME) SRCSTMF('&FULLPATH') CLOSQLCSR(*ENDMOD) OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT)"
        },
        {
            "type": "streamfile",
            "extensions": [
                "SQLRPGLE"
            ],
            "name": "Create SQL ILE RPG Module (CRTSQLRPGI)",
            "command": "?CRTSQLRPGI OBJ(&BUILDLIB/&NAME) SRCSTMF('&FULLPATH') OBJTYPE(*MODULE) CLOSQLCSR(*ENDMOD) OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT)"
        },
        {
            "type": "streamfile",
            "extensions": [
                "RPGLE",
                "RPG"
            ],
            "name": "Create RPG Module (CRTRPGMOD)",
            "command": "?CRTRPGMOD MODULE(&BUILDLIB/&NAME) SRCSTMF('&FULLPATH') OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT)"
        },
        {
            "type": "streamfile",
            "extensions": [
                "CLP",
                "CLLE"
            ],
            "name": "Create Bound CL Program (CRTBNDCL)",
            "command": "?CRTBNDCL PGM(&BUILDLIB/&NAME) SRCSTMF('&FULLPATH') OPTION(*EVENTF) DBGVIEW(*SOURCE)"
        },
        {
            "type": "streamfile",
            "extensions": [
                "SQL"
            ],
            "name": "Run SQL Statements (RUNSQLSTM)",
            "command": "?RUNSQLSTM SRCSTMF('&FULLPATH') COMMIT(*NONE) NAMING(*SQL)"
        },
        {
            "type": "streamfile",
            "extensions": [
                "CMD"
            ],
            "name": "Create Command (CRTCMD)",
            "command": "?CRTCMD CMD(&BUILDLIB/&NAME) PGM(&BUILDLIB/&NAME) SRCSTMF('&FULLPATH') OPTION(*EVENTF)"
        },
        {
            "type": "streamfile",
            "extensions": [
                "CMD"
            ],
            "name": "Create Command (Allow Return Variables - CRTCMD)",
            "command": "?CRTCMD CMD(&BUILDLIB/&NAME) PGM(&BUILDLIB/&NAME) SRCSTMF('&FULLPATH') ALLOW(*BPGM *IPGM *BMOD *IMOD *BREXX *IREXX) OPTION(*EVENTF)"
        },
        {
            "type": "streamfile",
            "extensions": [
                "GLOBAL"
            ],
            "name": "Set CCSID to 1252",
            "environment": "pase",
            "command": "setccsid 1252 \"&FULLPATH\""
        },
        {
            "type": "object",
            "extensions": [
                "GLOBAL"
            ],
            "name": "Delete object",
            "command": "?DLTOBJ OBJ(&LIBRARY/&NAME) OBJTYPE(*&TYPE)"
        },
        {
            "type": "object",
            "extensions": [
                "PGM"
            ],
            "name": "Call program",
            "command": "?CALL &LIBRARY/&NAME"
        },
        {
            "type": "member",
            "extensions": [
                "RPGLE",
                "RPG",
                "SQLRPGLE",
                "CLP",
                "CLLE"
            ],
            "environment": "ile",
            "name": "Quivir Compila",
            "command": "MQSYS/QCMPSRC PGM(&OPENMBR) BIBO(&OPENLIB) ARCF(&OPENSPF) BIBF(&OPENLIB) TIPO(&EXT) CISC(R) RMV(N) DLT(N)"
        },
        {
            "type": "member",
            "extensions": [
                "RPGLE",
                "RPG",
                "SQLRPGLE",
                "DSPF"
            ],
            "environment": "ile",
            "name": "Pasa a Webgate",
            "command": "WGCVT WGPROJECT(&OPENLIB) ITEMNAME(&OPENMBR) ITEMATR(*NULL) ITEMTYPE(&EXT)"
        }
    ],
    "vscode-rpgle.showFixedFormatOutline": true,
    "vscode-db2i.validator": true
}

And yes, every member I open, it's in read only mode...

**Comment by worksofliam** [comment]
@carabirubi69 1.7.11 is going to be available in about 15 minutes. Try that version and let me know if it solves the issue. Thanks!

**Comment by BastianZwetsch** [comment]
Hello There,

please keep in mind that there are now two ways to open a member via key combination:
CRTL+O -> opens in READ ONLY mode
CRTL+P -> opens in EDIT mode

hope that helps.

**Comment by carabirubi69** [comment]
> Hello There,
> 
> please keep in mind that there are now two ways to open a member via key combination: CRTL+ALT+ O -> opens in READ ONLY mode CRTL+ALT+P -> opens in EDIT mode
> 
> hope that helps.

I think that is the problem... I always use Ctrl + Alt + O to open... I've just test with Ctrl + P and it works... 

Thank a a lot...
