### ISSUE TITLE
Disconnecting from system loses all open tabs

### ISSUE THREAD

**Issue by jkyeung** [halcyon-tech/vscode-ibmi#1192]
**Describe the bug**
Clicking the disconnect icon on the lower left not only disconnects from the system but also clears all editing tabs from VS Code. This is **ALL** tabs, not just the ones that had been open through Code for IBM i.

As you can imagine, this is potentially a big problem.

I am not sure if the problem affects open "projects" or "folders" or whatever. I just open (many) individual files, like a plain old editor.

**To Reproduce**
1. Click the disconnect icon.

**Expected behavior**
All my previously open tabs remain open.

**Screenshots**
Don't think this is necessary.

**Environment (please complete the following information):**
 - Extension version: 1.7.11
 - IBM i OS version: 7.4

**Comment by worksofliam** [comment]
I'm not classing this as a bug. That's the way I wrote it, but I think this could be a good improvement.

**Comment by jkyeung** [comment]
Not a bug? I must say, that is both surprising and disappointing to hear. Because if that's how you meant for it to work, then it is frankly a bad design.

Let me lay down my case for why this is a bug and needs to be prioritized:

1. **It didn't used to work this way.** This is a *regression* apparently introduced by the recent ["reconnect UI improvement"](#1183) (which might itself also be a bug if the zombie connection behavior is, in fact, still occurring).
2. **It breaks a fundamental VS Code feature, with no warning and no setting.** One of the best and most amazing, yet seemingly simple, things about VS Code is that it remembers and reopens all the tabs you had open, even *unsaved* ones, upon restart. I can't imagine I'm the only user who has come to depend on this.
3. As it stands, in terms of tab management, **clicking the disconnect icon is a *more disruptive* way to close a connection than either of the following:**
    * Manually closing and reopening VS Code 
    * Uninstalling and reinstalling the Code for IBM i extension
4. **It closes tabs which have nothing at all to do with the IBM i in question.** Why should disconnecting from *any* remote system close all of my local tabs, as well as any that I might have open from a different remote system? I challenge you to find anyone who thinks that is intuitive or beneficial.

**Comment by worksofliam** [comment]
@jkyeung this will be worked on today. 

There are also others that claimed the previous was of disconnecting (that refreshed the entire window) was considered a bug.

**Comment by richardschoen** [comment]
FWIW - I agree that if possible on disconnect you should only close members opened by Code for i.  But it did allow me to save changes for me open source members and local files when I tested with one of each open.

**Comment by jkyeung** [comment]
> @jkyeung this will be worked on today.

Thank you, that is welcome news.

> There are also others that claimed the previous was of disconnecting (that refreshed the entire window) was considered a bug.

I did find it a little odd and heavy-handed that the old way of disconnecting (present in v1.7.5) seemed to amount to a VS Code reload, as would be required for an update to VS Code itself or uninstalling an extension. But since VS Code seems to have mastered the art of the reload (everything comes back the way it was, at the cost of a screen blip lasting what, a second? maybe less on fast machines), it seemed like a completely reasonable solution to me.

Disconnecting faster but losing all my tabs? Not a good trade. There is no VS Code reload that could *ever* last as long or be as tedious as having to manually restore all my tabs. *It would literally be better for me to manually close and reopen VS Code than to use the v1.7.6 through v1.7.11 disconnect button.* That **cannot** be right.

**Comment by worksofliam** [comment]
@jkyeung attached PR will now only close open members and streamfiles if they are saved. The remainder will be closed.

**Comment by jkyeung** [comment]
> @jkyeung attached PR will now only close open members and streamfiles if they are saved. The remainder will be closed.

I'm very leery of this. What is included in "the remainder"? If it's any of my local files (nothing to do with Code for IBM i, nothing to do with *any* IBM i), then it's still no good to me.

**Comment by sebjulliand** [comment]
@jkyeung I think what Liam wanted to say was that when you disconnect:
- Unsaved members/stream files will remain open
- Saved members/stream files will be closed
- _Any other tab_ will remain untouched

Mind you, that's when you willingly disconnect. In case the connection drops, nothing gets closed.

**Comment by jkyeung** [comment]
@sebjulliand - Thank you, that clears things up, and that set of behaviors makes sense. I am looking forward to it!
