### ISSUE TITLE
Better information or automation relating to home directory

### ISSUE THREAD

**Issue by jkyeung** [halcyon-tech/vscode-ibmi#1205]
When the user profile used doesn't have a home directory, a notification pops up that says the extension might not work properly without a home directory. That part is fine. Then it suggests assigning a home directory with the CHGUSRPRF command. That is also fine. But if the actual directory in the IFS does not exist, the message doesn't provide an explanation or remedy. It is especially confusing if the user has already done the suggested step of issuing CHGUSRPRF.

So the minimum I'm suggesting is to also include, in the message, the command to create the home directory.

But what would be even better, if feasible, is to do those things automatically (change the user profile and/or create the home directory), after prompting the user and getting their OK. If they decline, then of course don't do those things. If they would like to have those things done automatically but don't have sufficient system privileges, then they should be informed of that, with the suggestion that they contact their administrator to do those things for them, or grant them the required authority.

* QCCSID: 65535
* Features:
   * git: true
   * grep: true
   * tn5250: true
   * setccsid: true
   * md5sum: true
   * GENCMDXML.PGM: false
   * QZDFMDB2.PGM: true
   * startDebugService.sh: false
   * iconv: true
   * attr: true
* SQL enabled: false
* Source dates enabled: false

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Errors:
```json
[
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "Could not chdir to home directory /home/JYEUNG: No such file or directory\nCPF9801: Object QCPFRMIMPF in library QSYS not found.",
    "cwd": "."
  },
  {
    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh",
    "code": 2,
    "stderr": "Could not chdir to home directory /home/JYEUNG: No such file or directory\n/QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh not found",
    "cwd": "."
  },
  {
    "command": "ls -p /QSYS.lib/ILEDITOR.lib/GENCMDXML.PGM",
    "code": 2,
    "stderr": "Could not chdir to home directory /home/JYEUNG: No such file or directory\n/QSYS.lib/ILEDITOR.lib/GENCMDXML.PGM not found",
    "cwd": "."
  }
]
```

**Comment by ThePrez** [comment]
afaict, there's no way for a user profile to NOT have a home directory (listed in the *USRPRF object) so I think some of the user experience is already a bit misleading.
