### ISSUE TITLE
New User, Cant get Object list to expand, IFS works 

### ISSUE THREAD

**Issue by jimfaulk** [halcyon-tech/vscode-ibmi#1206]
I am a New User,

Shows connected to system.  I can see the connection on the IBM i 

 Cant get Object list to expand, IFS works 

Filter is :
Library=PGMJIMF
Object = *
Type Filter = *
Member = *
Member Type = *SRCPF

* QCCSID: %3F
* Features:
   * git: false
   * grep: false
   * tn5250: false
   * setccsid: true
   * md5sum: false
   * bash: false
   * GENCMDXML.PGM: false
   * QZDFMDB2.PGM: true
   * startDebugService.sh: false
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: false

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Errors:
```json
[
  {
    "command": "ls -p /QOpenSys/pkgs/bin/",
    "code": 2,
    "stderr": "/QOpenSys/pkgs/bin/ not found",
    "cwd": "/home/FW06ET"
  },
  {
    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh",
    "code": 2,
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh not found",
    "cwd": "/home/FW06ET"
  },
  {
    "command": "ls -p /QSYS.lib/ILEDITOR.lib/GENCMDXML.PGM",
    "code": 2,
    "stderr": "/QSYS.lib/ILEDITOR.lib/GENCMDXML.PGM not found",
    "cwd": "/home/FW06ET"
  }
]
```

**Comment by worksofliam** [comment]
@jimfaulk What version of IBM i are you connected to?

**Comment by jimfaulk** [comment]
Thanks for responding ! 

 V7R3

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the list doesn't appear.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by chrjorgensen** [comment]
@jimfaulk I think you have mixed some values in your filter:

```
Object = *
Type Filter = *
Member = *
Member Type = *SRCPF
```

should be

```
Object = *
Type Filter = *SRCPF
Member = *
Member Type = *
```

Check if this helps...

**Comment by jimfaulk** [comment]
My bad on the filer contents.   It was 
Object Type Filter is *SRCPF

The last filter for below  is...   I triple checked this !
Filter Name = new filter
Library = pgmjimf
Oblect = Q*
Object Type type filter = *SRCPF
Member = *
Member Type = *
Here is the entire contents of the Output
.: pwd
{
    "code": 0,
    "signal": null,
    "stdout": "/home/FW06ET",
    "stderr": ""
}

/home/FW06ET: pwd
{
    "code": 0,
    "signal": null,
    "stdout": "/home/FW06ET",
    "stderr": ""
}

/home/FW06ET: /QOpenSys/usr/bin/qsh
liblist
{
    "code": 134,
    "signal": null,
    "stdout": "",
    "stderr": "bsh: 8968 Abort"
}

/home/FW06ET: system "CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF2111: Library ILEDITOR already exists."
}

/home/FW06ET: [ -d "/tmp" ]
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/FW06ET: system "CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF9801: Object QCPTOIMPF in library QSYS not found."
}

/home/FW06ET: system "CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found."
}

/home/FW06ET: ls -p /QOpenSys/pkgs/bin/
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "/QOpenSys/pkgs/bin/ not found"
}

/home/FW06ET: ls -p /usr/bin/
{
    "code": 0,
    "signal": null,
    "stdout": "Rfile\najar\nappletviewer\napt\narmsrv\narmsrvconv\nattr\nbasename\ncat\ncatsplf\nchgrp\nchmod\nchown\nclrtmp\ncmp\ncompress\ncp\ncut\ndataq\ndatarea\ndate\ndb2\ndb2profc\ndb2profc_trace\ndb2profp\nddns-confgen\ndelv\ndfmadmin\ndhcpd\ndhcrelay\ndig\ndirname\ndnssec-dsfromkey\ndnssec-importkey\ndnssec-keyfromlabel\ndnssec-keygen\ndnssec-revoke\ndnssec-settime\ndnssec-signzone\ndnssec-verify\ndspmsg\necho\negrep\nenv\nexpr\nextcheck\nfgrep\nfile\nfind\ngencat\ngetjobid\ngrep\nhead\nhost\nhostname\nhwkeytool\niconv\nid\nidlj\nikeyman\nipcrm\nipcs\nixlc\njar\njarsigner\njava\njavac\njavadoc\njavah\njavap\njconsole\njdb\njdmpview\njextract\nkdestroy\nkeytab\nkeytool\nkinit\nklist\nkpasswd\nksetup\nldapadd\nldapchangepwd\nldapcompare\nldapdelete\nldapdiff\nldapexop\nldapmodify\nldapmodrdn\nldapsearch\nln\nlocale\nlogger\nlogname\nls\nmkdir\nmkfifo\nmv\nnamed\nnamed-checkconf\nnamed-checkzone\nnamed-compilezone\nnamed-journalprint\nnamed-rrchecker\nnative2ascii\nnohup\nnslookup\nnsupdate\nod\norbd\npack200\npax\npolicytool\npr\nprintenv\nprofconv\nprofdb\nprofp\nps\npwd\npwdx\nqsh\nrexec\nrexx\nrm\nrmdir\nrmic\nrmid\nrmiregistry\nrndc\nrndc-confgen\nschemagen\nsed\nserialver\nservertool\nsetccsid\nsh\nsort\nsplit\nsqlj\nstrEKM\nsystem\nsysval\ntail\ntar\ntee\ntest\ntnameserv\ntouch\ntr\ntsig-keygen\nuname\nuncompress\nuniq\nunpack200\nwc\nwsgen\nwsimport\nxargs\nxjc\nzcat",
    "stderr": ""
}

/home/FW06ET: ls -p /QSYS.LIB/QZDFMDB2.PGM
{
    "code": 0,
    "signal": null,
    "stdout": "/QSYS.LIB/QZDFMDB2.PGM",
    "stderr": ""
}

/home/FW06ET: ls -p /QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh not found"
}

/home/FW06ET: ls -p /QSYS.lib/ILEDITOR.lib/GENCMDXML.PGM
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "/QSYS.lib/ILEDITOR.lib/GENCMDXML.PGM not found"
}

/home/FW06ET: ls -p /QSYS.lib/ILEDITOR.lib/GENCMDXML.PGM
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "/QSYS.lib/ILEDITOR.lib/GENCMDXML.PGM not found"
}

/home/FW06ET: ls -p /QSYS.lib/ILEDITOR.lib/GENCMDXML.PGM
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "/QSYS.lib/ILEDITOR.lib/GENCMDXML.PGM not found"
}

/home/FW06ET: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
SELECT * FROM QSYS2.ASP_INFO
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/FW06ET: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
select CHARACTER_CODE_SET_ID from table( QSYS2.QSYUSRINFO( USERNAME => upper('fw06et') ) )
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/FW06ET: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
with VARIANTS ( HASH, AT, DOLLARSIGN ) as (  values ( cast( x'7B' as varchar(1) )         , cast( x'7C' as varchar(1) )         , cast( x'5B' as varchar(1) ) ))select HASH concat AT concat DOLLARSIGN as LOCAL  from VARIANTS; 
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/FW06ET: system "DSPFD FILE(PGMJIMF/QCLSRC) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_gnlvDJR0)"
/home/FW06ET: system "DSPFD FILE(PGMJIMF/*ALL) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_gaqy1fdR)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_GNLVDJR0 created in library ILEDITOR.\nCPF9862: Member O_GNLVDJR0 added to output file O_GNLVDJR0 in library ILEDITOR.\nCPF3030: 1 records added to member O_GNLVDJR0 in file O_GNLVDJR0 in ILEDITOR.",
    "stderr": ""
}

/home/FW06ET: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT * FROM ILEDITOR.O_gnlvDJR0
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_GAQY1FDR created in library ILEDITOR.\nCPF9862: Member O_GAQY1FDR added to output file O_GAQY1FDR in library ILEDITOR.\nCPF3030: 225 records added to member O_GAQY1FDR in file O_GAQY1FDR in ILEDITOR.",
    "stderr": ""
}

/home/FW06ET: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT * FROM ILEDITOR.O_gaqy1fdR
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/FW06ET: system "DSPFD FILE(PGMJIMF/QCLSRC) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_RJkrZYON)"
/home/FW06ET: system "DSPFD FILE(PGMJIMF/*ALL) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_nf9OuwHM)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_RJKRZYON created in library ILEDITOR.\nCPF9862: Member O_RJKRZYON added to output file O_RJKRZYON in library ILEDITOR.\nCPF3030: 1 records added to member O_RJKRZYON in file O_RJKRZYON in ILEDITOR.",
    "stderr": ""
}

/home/FW06ET: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT * FROM ILEDITOR.O_RJkrZYON
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_NF9OUWHM created in library ILEDITOR.\nCPF9862: Member O_NF9OUWHM added to output file O_NF9OUWHM in library ILEDITOR.\nCPF3030: 225 records added to member O_NF9OUWHM in file O_NF9OUWHM in ILEDITOR.",
    "stderr": ""
}

/home/FW06ET: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT * FROM ILEDITOR.O_nf9OuwHM
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/FW06ET: system "DSPFD FILE(PGMJIMF/Q*) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_P5SdJN5b)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_P5SDJN5B created in library ILEDITOR.\nCPF9862: Member O_P5SDJN5B added to output file O_P5SDJN5B in library ILEDITOR.\nCPF3030: 29 records added to member O_P5SDJN5B in file O_P5SDJN5B in ILEDITOR.",
    "stderr": ""
}

/home/FW06ET: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT * FROM ILEDITOR.O_P5SdJN5b
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

**Comment by jimfaulk** [comment]
Maybe this is a little more relevant:

/home/fw06et: system "DSPFD FILE(PGMJIMF/Q*) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_KoDSLqPc)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_KODSLQPC created in library ILEDITOR.\nCPF9862: Member O_KODSLQPC added to output file O_KODSLQPC in library ILEDITOR.\nCPF3030: 13 records added to member O_KODSLQPC in file O_KODSLQPC in ILEDITOR.",
    "stderr": ""
}

/home/fw06et: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT * FROM ILEDITOR.O_KoDSLqPc
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/fw06et: system "DSPFD FILE(FDWPGM/QCLSRC) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_4sIqpwLt)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_4SIQPWLT created in library ILEDITOR.\nCPF9862: Member O_4SIQPWLT added to output file O_4SIQPWLT in library ILEDITOR.\nCPF3030: 1 records added to member O_4SIQPWLT in file O_4SIQPWLT in ILEDITOR.",
    "stderr": ""
}

/home/fw06et: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT * FROM ILEDITOR.O_4sIqpwLt
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

**### I ran the SELECT * FROM ILEDITOR.O_4sIqpwLt SQL on the IBM i and it returned one record as expected.  I set the shell to use bash and got the following:**

.: pwd
{
    "code": 0,
    "signal": null,
    "stdout": "/home/fw06et",
    "stderr": ""
}

/home/fw06et: pwd
{
    "code": 0,
    "signal": null,
    "stdout": "/home/fw06et",
    "stderr": ""
}

/home/fw06et: /QOpenSys/usr/bin/qsh
liblist
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/fw06et: system "CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF2111: Library ILEDITOR already exists."
}

/home/fw06et: [ -d "/tmp" ]
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/fw06et: system "CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF9801: Object QCPTOIMPF in library QSYS not found."
}

/home/fw06et: system "CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found."
}

/home/fw06et: ls -p /QOpenSys/pkgs/bin/
{
    "code": 0,
    "signal": null,
    "stdout": "2to3\n2to3-3.6\n[\n__pycache__/\naclocal\naclocal-1.15\naddbuiltin\nalternatives\natob\nautoconf\nautoheader\nautom4te\nautomake\nautomake-1.15\nautoreconf\nautoscan\nautoupdate\nawk\nbaddbdir\nbase32\nbase64\nbasename\nbash\nbashbug\nbison\nbltest\nbottle.py\nbtoa\nc++\nc++.bin\nc2ph\ncat\ncc\nccmake\ncertcgi\ncertutil\nchcon\nchgrp\nchktest\nchmod\nchown\nchroot\nchsh\ncksum\ncmake\ncmsutil\ncomm\nconflict\ncorelist\ncp\ncpack\ncpan\ncpp\ncpp.bin\ncrlutil\ncrmftest\ncsplit\nctest\ncut\ncygdb\ncython\ncythonize\ndate\ndbtest\ndd\ndebuginfo-install\nderdump\ndertimetest\ndf\ndigest\ndir\ndircolors\ndirname\ndjango-admin\ndjango-admin.py\ndu\neasy_install-3.6\necho\necperf\negrep\nenc2xs\nencguess\nencodeinttest\nenv\nexample\nexpand\nexpr\nf2py3.6\nfactor\nfalse\nfbectest\nfgrep\nfind-repos-of-install\nfipstest\nflask\nflex\nflex++\nfmt\nfold\nfuturize\ng++\ng++.bin\ngawk\ngcc\ngcc-ar\ngcc-ar.bin\ngcc-nm\ngcc-nm.bin\ngcc-ranlib\ngcc-ranlib.bin\ngcc.bin\ngcov\ngendiff\ngit\ngit-cvsserver\ngit-receive-pack\ngit-shell\ngit-upload-archive\ngit-upload-pack\ngmake\ngrep\ngroups\ngsed\nh2ph\nh2xs\nhead\nhostid\nhttpserv\nid\nidle3\nidle3.6\nifnames\nigawk\ninstall\ninstmodsh\njoin\njson_pp\nkill\nlibnetcfg\nlibtool\nlibtoolize\nlink\nlistsuites\nln\nlogname\nls\nm4\nmake\nmakepqg\nmangle\nmd5sum\nminigzip\nmkdir\nmkfifo\nmknod\nmktemp\nmodutil\nmultinit\nmv\nneeds-restarting\nnice\nnl\nnohup\nnonspr10\nnproc\nnumfmt\nocspclnt\nocspresp\nod\noidcalc\np7content\np7env\np7sign\np7verify\npackage-cleanup\npaste\npasteurize\npatch\npathchk\nperl\nperl5.24.1\nperlbug\nperldoc\nperlivp\nperlthanks\npiconv\npinky\npip3\npip3.6\npk11ectest\npk11gcmtest\npk11mode\npk12util\npk1sign\npkg-config\npkix-errcodes\npl2pm\npod2html\npod2man\npod2text\npod2usage\npodchecker\npodselect\npowerpc-ibm-os400-pkg-config\npp\npr\nprintenv\nprintf\nprove\npstruct\nptar\nptardiff\nptargrep\nptx\npwd\npwdecrypt\npydoc\npydoc3\npydoc3.6\npython\npython2\npython2.7\npython3\npython3-config\npython3.6\npython3.6-config\npython3.6m\npython3.6m-config\npyvenv\npyvenv-3.6\nreadlink\nrealpath\nremtest\nrepo-graph\nrepo-rss\nrepoclosure\nrepodiff\nrepomanage\nrepoquery\nreposync\nrepotrack\nrm\nrmdir\nrpm\nrpm2archive\nrpm2cpio\nrpmbuild\nrpmdb\nrpmgraph\nrpmkeys\nrpmquery\nrpmsign\nrpmspec\nrpmverify\nrsaperf\nruncon\nsdrtest\nsecmodtest\nsed\nselfserv\nseq\nsha1sum\nsha224sum\nsha256sum\nsha384sum\nsha512sum\nshasum\nshlibsign\nshow-changed-rco\nshow-installed\nshred\nshuf\nsigntool\nsignver\nsleep\nsmtpd.py\nsort\nsplain\nsplit\nsqlformat\nssltap\nstat\nstdbuf\nstrsclnt\nstty\nsum\nsymkeyutil\nsync\ntac\ntail\ntee\ntest\ntimeout\ntouch\ntr\ntrue\ntruncate\ntrust\ntsort\ntstclnt\ntty\nuname\nunexpand\nuniq\nunlink\nupdate-alternatives\nupdate-ca-certificates\nuptime\nurlgrabber\nusers\nvdir\nverifytree\nvfychain\nvfyserv\nwc\nwheel\nwho\nwhoami\nxslt-config\nxsltproc\nxsubpp\nyacc\nyes\nyum\nyum-builddep\nyum-config-manager\nyum-debug-dump\nyum-debug-restore\nyum-groups-manager\nyumdownloader\nzipdetails",
    "stderr": ""
}

/home/fw06et: ls -p /usr/bin/
{
    "code": 0,
    "signal": null,
    "stdout": "Rfile\najar\nappletviewer\napt\narmsrv\narmsrvconv\nattr\nbasename\nbash\ncat\ncatsplf\nchgrp\nchmod\nchown\nclrtmp\ncmp\ncompress\ncp\ncut\ndataq\ndatarea\ndate\ndb2\ndb2profc\ndb2profc_trace\ndb2profp\nddns-confgen\ndelv\ndfmadmin\ndhcpd\ndhcrelay\ndig\ndirname\ndnssec-dsfromkey\ndnssec-importkey\ndnssec-keyfromlabel\ndnssec-keygen\ndnssec-revoke\ndnssec-settime\ndnssec-signzone\ndnssec-verify\ndspmsg\necho\negrep\nenv\nexpr\nextcheck\nfgrep\nfile\nfind\ngencat\ngetjobid\ngrep\nhead\nhost\nhostname\nhwkeytool\niconv\nid\nidlj\nikeyman\nipcrm\nipcs\njar\njarsigner\njava\njavac\njavadoc\njavah\njavap\njconsole\njdb\njdmpview\njextract\nkdestroy\nkeytab\nkeytool\nkinit\nklist\nkpasswd\nksetup\nldapadd\nldapchangepwd\nldapcompare\nldapdelete\nldapdiff\nldapexop\nldapmodify\nldapmodrdn\nldapsearch\nln\nlocale\nlogger\nlogname\nls\nmkdir\nmkfifo\nmv\nnamed\nnamed-checkconf\nnamed-checkzone\nnamed-compilezone\nnamed-journalprint\nnamed-rrchecker\nnative2ascii\nnohup\nnslookup\nnsupdate\nod\norbd\npack200\npax\npolicytool\npr\nprintenv\nprofconv\nprofdb\nprofp\nps\npwd\npwdx\nqsh\nrexec\nrexx\nrm\nrmdir\nrmic\nrmid\nrmiregistry\nrndc\nrndc-confgen\nschemagen\nsed\nserialver\nservertool\nsetccsid\nsh\nsort\nsplit\nsqlj\nstrEKM\nsystem\nsysval\ntail\ntar\ntee\ntest\ntnameserv\ntouch\ntr\ntsig-keygen\nuname\nuncompress\nuniq\nunpack200\nwc\nwsgen\nwsimport\nxargs\nxjc\nzcat",
    "stderr": ""
}

/home/fw06et: ls -p /QSYS.LIB/QZDFMDB2.PGM
{
    "code": 0,
    "signal": null,
    "stdout": "/QSYS.LIB/QZDFMDB2.PGM",
    "stderr": ""
}

/home/fw06et: ls -p /QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh not found"
}

/home/fw06et: ls -p /QSYS.lib/ILEDITOR.lib/GENCMDXML.PGM
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "/QSYS.lib/ILEDITOR.lib/GENCMDXML.PGM not found"
}

/home/fw06et: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
SELECT * FROM QSYS2.ASP_INFO
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/fw06et: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
select CHARACTER_CODE_SET_ID from table( QSYS2.QSYUSRINFO( USERNAME => upper('fw06et') ) )
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/fw06et: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
with VARIANTS ( HASH, AT, DOLLARSIGN ) as (  values ( cast( x'7B' as varchar(1) )         , cast( x'7C' as varchar(1) )         , cast( x'5B' as varchar(1) ) ))select HASH concat AT concat DOLLARSIGN as LOCAL  from VARIANTS; 
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/fw06et: echo $SHELL
{
    "code": 0,
    "signal": null,
    "stdout": "/QOpenSys/pkgs/bin/bash",
    "stderr": ""
}

/home/fw06et: system "DSPFD FILE(PGMJIMF/Q*) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_sIyv5o1N)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_SIYV5O1N created in library ILEDITOR.\nCPF9862: Member O_SIYV5O1N added to output file O_SIYV5O1N in library ILEDITOR.\nCPF3030: 13 records added to member O_SIYV5O1N in file O_SIYV5O1N in ILEDITOR.",
    "stderr": ""
}

/home/fw06et: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT * FROM ILEDITOR.O_sIyv5o1N
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/fw06et: system "DSPFD FILE(FDWPGM/QCLSRC) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_MbCo4dZb)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_MBCO4DZB created in library ILEDITOR.\nCPF9862: Member O_MBCO4DZB added to output file O_MBCO4DZB in library ILEDITOR.\nCPF3030: 1 records added to member O_MBCO4DZB in file O_MBCO4DZB in ILEDITOR.",
    "stderr": ""
}

/home/fw06et: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT * FROM ILEDITOR.O_MbCo4dZb
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/fw06et: system "DSPOBJD OBJ(JRFTEMPXX/*ALL) OBJTYPE(*ALL) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_7CF0Bqz6)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_7CF0BQZ6 created in library ILEDITOR.\nCPF9862: Member O_7CF0BQZ6 added to output file O_7CF0BQZ6 in library ILEDITOR.",
    "stderr": ""
}

/home/fw06et: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT * FROM ILEDITOR.O_7CF0Bqz6
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

**Comment by jimfaulk** [comment]
oops, still not resolved

**Comment by worksofliam** [comment]
@jimfaulk I think this might solve your issue: https://halcyon-tech.github.io/docs/#/pages/tips/setup?id=no-results-from-sql-execution

**Comment by jimfaulk** [comment]
Thank you so much for the post worksofliam !   That resolved the issue for me on Friday.   Is this not a persistent setting ?    I had the same issue this morning (Monday) and had to repeat the procedure and it again corrected the issue.

**Comment by worksofliam** [comment]
@jimfaulk It should be persistent, but I guess it has to do with how the SSH Daemon is started it.

Perhaps @chrjorgensen will have a better answer for you.

Glad you were able to solve it!

**Comment by chrjorgensen** [comment]
@jimfaulk I've never experienced this issue but I would check how the SSH server is started after IPL - perhaps in the start program defined in system value `QSTRUPPGM`. Also check the link in `/QOpenSys/usr/sbin` - it should look like this:

![billede](https://user-images.githubusercontent.com/13275072/229611375-edea6c99-f13d-4d41-8d03-9a2f2dc59748.png)

Maybe someone installed the open source RPM ssh server `openssh-server` and has set this up as the default ssh server program?
It is possible to have both installed, but this extension is built to use the IBM i SSH daemon from 5733-SC1, which integrates with IBM i and `openssh-server` does not. 5733-SC1 is free and contained on the IBM i media.

**Comment by jimfaulk** [comment]
Thanks @chrjorgensen !  
The Startup program starts it with STRHOSTSVR SERVER(*ALL) RQDPCL(*TCP) 

When I check the link , it looks like: 
 > ls -la /QOpenSys/usr/sbin/ssh*                                               
   lrwxrwxrwx    1 qsys     0                82 Jan 19 2018  /QOpenSys/usr/sbin/
   sshd -> ../../QIBM/ProdData/SC1/OpenSSH/sbin/sshd                

Is there a way to revert it back ?

**Comment by chrjorgensen** [comment]
@jimfaulk SSH is not started by STRHOSTSVR - it is started by STRTCPSVR (*SSHD, *AUTOSTART or **ALL).

Your link seems correct to me... just another date because the installation were done at a different time.

Are you by any chance using [Service Commander](https://github.com/ThePrez/ServiceCommander-IBMi) and starting the open source SSH daemon using ´SC´? This may prevent the integrated SSH daemon from starting, since port 22 will already be taken...
