### ISSUE TITLE
Did VS Code version 1.77 break Code for IBM i 1.7.11??

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#1207]
My Vs Code auto updates itself, after 1.77 updated and VS Code was restarted (because I just opened it). I don't see my connections.  They are present in the settings.json file.  I see this in the output. 

![image](https://user-images.githubusercontent.com/1353665/228964410-6d870a86-e358-4a5e-90c9-867fdd3ec57b.png)

I have gone into the backup history for settings.json and pulled one out that was working yesterday, with no luck.

**Comment by worksofliam** [comment]
@m-tyler gonna look into this update later. Thanks for reporting.

**Comment by devinhh** [comment]
Yes it is definitely related to 1.77.  I downgraded back to 1.67.2.  And the connections are there again.

**Comment by m-tyler** [comment]
Yes, I can confirm downgrading works.  I went back to 1.76.2.  Ugg.  I turned off auto updates of VS Code.  But good to know you can go to https://code.visualstudio.com/updates/ and pick the prior version you want to get back to work.

**Comment by worksofliam** [comment]
@m-tyler @devinhh Fix incoming.

Very sorry. The new 1.77 changelog did not list any breaking changes, yet something did change in VS Code and it affected us.

Will be out tonight.

**Comment by m-tyler** [comment]
No apology is needed.   The switchback was Easy-peasy.  

Thanks for finding out the reason and getting a fix.  Too bad it was needed and took time away from other stuff.

**Comment by worksofliam** [comment]
1.7.12 is out which will solve the issue.
