### ISSUE TITLE
Unable to Open/Create New IBMi Connection

### ISSUE THREAD

**Issue by thomprl** [halcyon-tech/vscode-ibmi#1208]
So everything was working fine.  I try to open VSCode and get the below message.  I assume something in my config got corrupted but I don't know what might have happened and now I can't create a new IBMi connection either.  

![image](https://user-images.githubusercontent.com/17936568/228966202-d988ac07-c188-461b-aa30-f864bcc94a8c.png)

**Comment by devinhh** [comment]
Related to 1.77. I downgraded back to 1.67.2. And the connections are there again. And did not receive this message anymore

**Comment by thomprl** [comment]
Thanks you.. I turned auto updates off as well.  1.75.1 seems to work for me.

**Comment by worksofliam** [comment]
1.8.12 is out which will solve the issue.
