### ISSUE TITLE
Special character "¬" not recognized by VS Code

### ISSUE THREAD

**Issue by robinsonmeredeth** [halcyon-tech/vscode-ibmi#1216]
The special character "¬" is not recognized in VS Code.  This character is used to interface with our document software.  The character shows as a  "?" inside the editor then after the source is saved it is either converted to blanks or "\Z".  I then need to go into SEU to copy the source line back that includes "¬".   Is there something that you can do?  Being that I have a workaround for this, this is not a high priority issue.  Any assistance on this is appreciated.  Thanks.  

* QCCSID: 65535
* Features:
   * git: false
   * grep: false
   * tn5250: false
   * setccsid: true
   * md5sum: false
   * bash: false
   * chsh: false
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * startDebugService.sh: false
   * iconv: true
   * attr: true
* SQL enabled: false
* Source dates enabled: true

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Errors:
```json
[
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found.",
    "cwd": "/home/robinm01"
  },
  {
    "command": "ls -p /QOpenSys/pkgs/bin/",
    "code": 2,
    "stderr": "/QOpenSys/pkgs/bin/ not found",
    "cwd": "/home/robinm01"
  },
  {
    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh",
    "code": 2,
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh not found",
    "cwd": "/home/robinm01"
  }
]
```

**Comment by chrjorgensen** [comment]
@robinsonmeredeth I have no problems seeing the "¬" character and edit and save lines containing this.

You have enabled source dates, so SQL is used to read and write the members and thus the user CCSID and SSH daemon language settings are in effect. Please follow the tips for correct language setup: https://halcyon-tech.github.io/docs/#/pages/tips/ccsid

**Comment by worksofliam** [comment]
@chrjorgensen You beat me to it! 

I am sure we had something come up specifically about `¬` before but I will have to dig through our issues, but I think the usual fix will solve it.

**Comment by robinsonmeredeth** [comment]
Hello, I am still having problems with special characters.  I changed my character set to CCSID 37, but I still get the below message when I start the application.  When the conversions are not done, I need to use PDM on the iSeries to copy and paste the characters from the original code.  I cannot find the Source Date settings.  
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/128847403/6e639ade-46ed-4983-9442-4ef215f7364e)

**Comment by chrjorgensen** [comment]
@robinsonmeredeth You have to right-click the connection and select `Connect and Reload Server Settings` to have Code for IBM i recognize your new CCSID. Then it should be fine...

**Comment by robinsonmeredeth** [comment]
I cannot locate the Connect and Reload Server Settings.  Also, how do i get out of Full Screen view?

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/128847403/4fdd7a02-d788-4477-865d-98aab54b4e6e)

**Comment by chrjorgensen** [comment]
Disconnect and right-click the connection in the `SERVERS` list.

F11 will take you out of full screen - like in your browser.

**Comment by robinsonmeredeth** [comment]
Great.  I didn't know about F11.  Thanks for your help.  

At one time I had to connect to the Server, now it comes up automatically.  I don't know how to disconnect, IBM I appears at the top.  How to I disconnect?  I assume once I disconnect then I will be able to manually connect like I use to.

**Comment by chrjorgensen** [comment]
`F1` and select `IBM i: Disconnect From Current Connection`:

![billede](https://github.com/halcyon-tech/vscode-ibmi/assets/13275072/3c172341-143b-480c-b069-8561b8714aed)

or click the disconnect button in the bottom bar:

![billede](https://github.com/halcyon-tech/vscode-ibmi/assets/13275072/6d3b07e8-04d0-431e-8c10-fd527efb1206)

**Comment by robinsonmeredeth** [comment]
I've learned a lot today.  Thanks again for your patience.  Wow!  

Now I no longer have the message for the CCSID.  I assume it now recognizes the CCSID = 37.  However, the special chars are still not recognized.  Below are comparisons of PDM to VSCode.  What else am I missing?


![image](https://github.com/halcyon-tech/vscode-ibmi/assets/128847403/65494269-5403-4ba0-b5ac-58be70cc1aa4)

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/128847403/90f39615-d8fc-4e83-8c25-adf0219a885d)

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/128847403/e8c8438b-1eeb-4c61-92cf-2fae82fdd24c)

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/128847403/0f30555f-6021-4d79-9c61-019f1a11184d)

**Comment by chrjorgensen** [comment]
@robinsonmeredeth Please check and report the CCSID of the source file.

Also check that you use `*FILE' in the connection settings:

![billede](https://github.com/halcyon-tech/vscode-ibmi/assets/13275072/ce362d19-ea57-4f6d-99c9-fc1ed780e166)

**Comment by robinsonmeredeth** [comment]
Hello, yes CCSID is *FILE already.

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/128847403/cdb0aca4-a550-4e0d-8ed0-c8f32d8e32e6)
