### ISSUE TITLE
Object Browser: Member appear only after Refresh

### ISSUE THREAD

**Issue by basim1971** [halcyon-tech/vscode-ibmi#1221]
[vcode2.docx](https://github.com/halcyon-tech/vscode-ibmi/files/11170203/vcode2.docx)
Dear all,
Can you check the following behavior.
After connecting i can see the list of filter and i try to open it no member appear (1 screenshot). I need to clik on the refresh object in order to update the member.
Thanks
Basilio

**Comment by worksofliam** [comment]
@basim1971 Please paste screenshots into the issue as many of us cannot open docx files from public sources.

**Comment by chrjorgensen** [comment]
I see the same issue - after starting the extension and connecting to a system, when opening the filter in Object Browser, the filter is not opened although the arrow changes from `>` to `v`. And no command is run on the server, the output from Code for IBM i only contains the connection log:

![billede](https://user-images.githubusercontent.com/13275072/230715941-d2b60944-9d5c-41de-9118-a1e08b0040ea.png)

Only after refresh is the filter read on server:

![billede](https://user-images.githubusercontent.com/13275072/230716061-cd71aeae-805b-4c2a-a2e8-eb98552ae394.png)

Seems like some initialization is missing on startup...?

**Comment by Teqed** [comment]
I've been trying to reproduce this issue but haven't had any luck.
Code for IBM i v1.7.12
VSCode 1.77.3 & 1.73.0
IBM i V7R5 & V7R4
Windows 10 Enterprise & 11 Enterprise

I've tried launching from a fresh VSCode window; disconnecting and reconnecting; connecting to one system and then another.

![image](https://user-images.githubusercontent.com/5181964/231554965-54a81aee-d0cb-41f2-8736-88cf44e869ba.png)

Some additional information might be needed to reproduce.
- Does every filter behave this way, or only certain ones?
- Does it happen on every fresh connection, or only sometimes?
- Do you also see this behavior on pub400?

**Comment by basim1971** [comment]
Hi @Teqed ,
Below my answer
    Does every filter behave this way, or only certain ones? 
              All the filter are impacted
    Does it happen on every fresh connection, or only sometimes?
              Every connection if i disconnect and connect again it's happne
    Do you also see this behavior on pub400?
              I don't have any account on pub400
Thanks
