### ISSUE TITLE
Object Browser Filter Not Working

### ISSUE THREAD

**Issue by sldeshpande08** [halcyon-tech/vscode-ibmi#1222]
Hello Team,
I am new to vscode.
This may be question already answered but when I am creating filter for one of our systems it is not working and not bringing up source files in vscode. In output logs I see it is generated temp file in ILEDITOR and able to fetch data but not able to write in vscode. There may be some copy command missing.

Any idea how to fix this? This is working for me on another IBM i system. Below are logs -
Anything missing on user profile level?

 "DSPFD FILE(PGMSLD/*ALL) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_C286XigC)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_C286XIGC created in library ILEDITOR.\nCPF9862: Member O_C286XIGC added to output file O_C286XIGC in library ILEDITOR.\nCPF3030: 3 records added to member O_C286XIGC in file O_C286XIGC in ILEDITOR.",
    "stderr": ""
}

LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT * FROM ILEDITOR.O_C286XigC
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

**Comment by worksofliam** [comment]
Hi @sldeshpande08!

See the '[No results from SQL execution](https://halcyon-tech.github.io/docs/#/pages/tips/setup?id=no-results-from-sql-execution)' section on this page: https://halcyon-tech.github.io/docs/#/pages/tips/setup?id=no-results-from-sql-execution

That should solve your problem.

**Comment by sldeshpande08** [comment]
@worksofliam It worked :) Thank you so much.

**Comment by bigsdavid** [comment]
From the response:

**Comment by bigsdavid** [comment]
From the response: See the '[No results from SQL execution](https://halcyon-tech.github.io/docs/#/pages/tips/setup?id=no-results-from-sql-execution)' section on this page: https://halcyon-tech.github.io/docs/#/pages/tips/setup?id=no-results-from-sql-execution   ===  the link no longer works. Does anyone have access to the answer that was provided at this link?

**Comment by chrjorgensen** [comment]
@bigsdavid `halcyon-tech` has been renamed to `codefori`, so your link should be [https://codefori.github.io/docs/#/pages/tips/setup?id=no-results-from-sql-execution](https://codefori.github.io/docs/#/pages/tips/setup?id=no-results-from-sql-execution)

The documentation link in the extension has been changed to the new URL. and so has the link in the About section of the [repository frontpage](https://github.com/codefori/vscode-ibmi).

Hope this helps! :smiley:
