### ISSUE TITLE
Command Profiles not refreshing

### ISSUE THREAD

**Issue by JDubbTX** [halcyon-tech/vscode-ibmi#1239]
When saving a new command profile, it doesn't show up in PROFILEs view.

Enter in information for a command to run with the command profile.  2 connection profiles already exist:
![image](https://user-images.githubusercontent.com/56802156/231826061-3a8ff0b7-7d39-4838-b4a9-a1e533973273.png)

New command profile is not added to the PROFILES view:
![image](https://user-images.githubusercontent.com/56802156/231826209-c647d0b5-8f3c-4a69-a78c-89bc1b7e4741.png)

* QCCSID: 65535
* Features:
   * git: true
   * grep: true
   * tn5250: false
   * setccsid: true
   * md5sum: true
   * bash: true
   * chsh: true
   * GENCMDXML.PGM: true
   * GETNEWLIBL.PGM: true
   * QZDFMDB2.PGM: true
   * startDebugService.sh: true
   * attr: true
   * iconv: true
* SQL enabled: false
* Source dates enabled: true

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Errors:
```json
[
  {
    "command": "system \"CRTLIB LIB(RDGJWEIRIC) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPD0032: Not authorized to command CRTLIB in library *LIBL.\nCPF0006: Errors occurred in command.",
    "cwd": "/home/JWEIRIC9"
  },
  {
    "command": "system \"DLTOBJ OBJ(RDGJWEIRIC/O_*) OBJTYPE(*FILE)\"",
    "code": 255,
    "stderr": "CPF2125: No objects deleted.",
    "cwd": "/home/JWEIRIC9"
  }
]
```

**Comment by worksofliam** [comment]
@JDubbTX 

I have attempted to recreate with no luck. If you reload or disconnect+reconnect, does it appear?

When you save, are you getting any notification appear in the bottom right?
