### ISSUE TITLE
I can't update a member text

### ISSUE THREAD

**Issue by ThomasBarberot** [halcyon-tech/vscode-ibmi#1245]
Type: <b>Bug</b>

Hello, this is low priority error. Here are the steps:

I can't change the member text by right-clicking / update member text. I enter a text of less than 50 characters and press ENTER --> The message CPF3288 appears : Member UNDEFINED file QRPGLESRC in MYLIB not changed.
![Error message](https://user-images.githubusercontent.com/123751292/233012247-5016e20b-33cf-46d9-b2f4-e61a8c336bc1.png)

Even after relaunching VSC, I can't execute the update.

**Environment:**
 - Extension version 1.8.0
 - IBM i OS version V7R4
 - QCCSID : 65535
 -  Source file CCSID : 1147
 
 

Extension version: 1.8.0
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.76GB (16.42GB free)|
|Process Argv|--crash-reporter-id ce1adbe5-33ca-4b60-9185-be47017be40e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsccsb:30705552
vscodeenable:30660116
defaultazurewalk:30687958
pythonms35:30701012
pythonfmttext:30716742
pythonclientmv:30713943

```

</details>

**Comment by worksofliam** [comment]
#1236 will fix the ability to delete a member. I will add to this PR so it will also include the update member text fix.
