### ISSUE TITLE
Content Assist Issues

### ISSUE THREAD

**Issue by edshaw42** [halcyon-tech/vscode-ibmi#1251]
I am not seeing content assist anywhere. I have watched the tutorial and read the docs and it's not in my settings page. Maybe I am missing a piece somewhere?

**Comment by worksofliam** [comment]
@edshaw42 

You've not really provided any context here. Content assist for what language?

**Comment by edshaw42** [comment]
My apologies. 

I was watching your video on IBMi Notebooks. You referred to the content assist for CLP in that video and actually have a whole independent video over content assist. 

But, when I go to the settings page, I do not see content assist anywhere. Possibly has been moved through an upgrade over time, or I am missing a piece to the puzzle. I would love to have the content assist for RPG, CLP, and SQL if available. 

Attaching a screenshot of my settings page current view. 

![image](https://user-images.githubusercontent.com/85707702/233736513-c4a7e811-0466-4be3-9bfe-c8433f2f21b4.png)

**Comment by worksofliam** [comment]
You likely want these two 😄 

* RPGLE: https://marketplace.visualstudio.com/items?itemName=HalcyonTechLtd.vscode-rpgle
* CL: https://marketplace.visualstudio.com/items?itemName=IBM.vscode-clle
