### ISSUE TITLE
CCSID 273 encoding not recognised

### ISSUE THREAD

**Issue by mechefan** [halcyon-tech/vscode-ibmi#1254]
I am using VS Code to connect to an IBM i server. The encoding associated with my user profile in the server is CCSID 273, which is not included in the VS Code list, so I'm not able to open files using this encoding, and some characters are misunderstood by the VS Code editor.

I am connecting to the IBM i server using the Code for IBM i VS Code extension. I've tried to adjust the extension settings in different ways so the CCSID is recognised, but I never get the correct result.

I've also tried to open the files in VS Code using different encodings but none of the included in the VS Code list are able to recognise correctly the complete set of characters.

Is there any way to get the CCSID 273 encoding recognised by VS Code?

* QCCSID: 273
* Features:
   * git: true
   * grep: true
   * tn5250: true
   * setccsid: true
   * md5sum: true
   * bash: true
   * chsh: true
   * GENCMDXML.PGM: false
   * GETNEWLIBL.PGM: false
   * QZDFMDB2.PGM: true
   * startDebugService.sh: true
   * attr: true
   * iconv: true
* SQL enabled: true
* Source dates enabled: true

**Comment by worksofliam** [comment]
@mechefan I recommend you check out this page to ensure your environment is setup correctly. Thanks! 

https://halcyon-tech.github.io/docs/#/pages/tips/ccsid
