### ISSUE TITLE
Not able to Start debug service

### ISSUE THREAD

**Issue by mrbenp** [halcyon-tech/vscode-ibmi#1258]
Save us time! Click 'Report an Issue' from the Help and Support panel inside of VS Code after you have connected to a system.

When I try to start the debug service from VScode, the startup fails:

Failed to end existing debug service (EQARD1028E The request to stop the Remote Debug Service daemon failed because port 8001 was invalid or the daemon was not running.)

![VScode](https://user-images.githubusercontent.com/10214830/234616894-f64c2688-013a-4fce-9dd4-19c1e7619055.PNG)

I did open a ticket with IBM, but was told to open the issue  in this forum.

**Comment by worksofliam** [comment]
@mrbenp Please describe in detail how you end up with this error message - a video is fine too. Thanks!

**Comment by mrbenp** [comment]
https://user-images.githubusercontent.com/10214830/235328341-d8953874-64a1-49ec-8a35-a26ddd15f968.mp4

Hi Liam, please see video attached.. thank you
