### ISSUE TITLE
Unable to retry source from my lib, IBM iSeries source code

### ISSUE THREAD

**Issue by guatememe** [halcyon-tech/vscode-ibmi#1259]
I'm using a VSCode to connect into Pub400 services, works fine the login, but when I try to retrieve some objects from my library, it show me this message 

![image](https://user-images.githubusercontent.com/58608775/235059368-fdb45a0c-d6be-4a8a-a85f-78a332540acf.png)

Error message
![image](https://user-images.githubusercontent.com/58608775/235059458-d75954b3-2b79-4d92-9567-bf6460a6e631.png)

**Comment by worksofliam** [comment]
In the filter, you need to use the `*SRCPF` type in order to browse source code.

Thanks!
