### ISSUE TITLE
`postDownload` not downloading/creating directories

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#1261]
**Is your feature request related to a problem? Please describe.**
Slight convenience feature.

**Describe the solution you'd like**
When running "`Launch Actions Setup`" and checking "`ibmi-bob`", shouldn't it create a `.logs` directory if one doesn't exist?

**Describe alternatives you've considered**
I can easily create it manually 

![image](https://user-images.githubusercontent.com/67484051/235255743-10f29c4b-f63f-49ae-adee-88f8e76c6be5.png)

**Comment by edmundreinhardt** [comment]
The .logs directory is created by the BOB tooling and vscode-ibmi download.  There is no need to manually create it.

**Comment by SJLennon** [comment]
@worksofliam 
@edmundreinhardt 

What am I doing wrong?  Here's the scenario:

Cloned the https://github.com/IBM/bob-recursive-example project from Github to a local directory on my PC.
Created Launch Actions Setup and selected ibmi-bob.
Did a build all, which deploys then fails because I forgot to change &lib1 to &LIB1 in iproj.json.
Fixed iproj.json.
Did build all again.
The build completes, but I get this failure:
![image](https://user-images.githubusercontent.com/67484051/235324859-37cc1bd4-b431-486d-9fee-86a07ac39f0a.png)
The .logs directory does not exist on my PC.
The .logs directory is created on PUB400.
![image](https://user-images.githubusercontent.com/67484051/235324963-0545389c-3a76-4ddb-a6f6-0590d3bd9eae.png)

**Comment by worksofliam** [comment]
@SJLennon do you still get this error if you create the directory manually? Perhaps something is happening with the directory creation.

**Comment by SJLennon** [comment]
@worksofliam If I create it manually in File Explorer the download works.

![image](https://user-images.githubusercontent.com/67484051/235325572-2530855f-c707-4c79-b24a-6ce54d8c92b6.png)


![image](https://user-images.githubusercontent.com/67484051/235325551-14006ac4-519f-4d0c-8dbd-c440049daab2.png)

**Comment by worksofliam** [comment]
What action are you running to run Bob? Please share the json, thanks!

**Comment by SJLennon** [comment]
```
[
  {
    "extensions": [
      "GLOBAL"
    ],
    "name": "Build all",
    "command": "OPT=*EVENTF BUILDLIB=&CURLIB /QOpenSys/pkgs/bin/makei build",
    "environment": "pase",
    "deployFirst": true,
    "postDownload": [
      ".logs/"
    ]
  },
  {
    "extensions": [
      "GLOBAL"
    ],
    "name": "Build current",
    "command": "OPT=*EVENTF BUILDLIB=&CURLIB /QOpenSys/pkgs/bin/makei compile -f &BASENAME",
    "environment": "pase",
    "deployFirst": true,
    "postDownload": [
      ".logs/"
    ]
  }
]
```
Built with:
![image](https://user-images.githubusercontent.com/67484051/235325758-ccbd0036-92c1-4f15-aecf-8bd679355da6.png)

**Comment by worksofliam** [comment]
@sebjulliand Edmund is out and I don't really use ibmi-bob. Is the `.logs` directory something you're familiar with? Are you interested in getting together Monday to debug together?

**Comment by sebjulliand** [comment]
@worksofliam indeed I am; I do the same in Elias actually.
I tried @SJLennon use case and had the same issue. After a bit of debugging, it turns out this error shows when trying to create the folder locally:
```
Error (FileSystemError): Unable to resolve filesystem provider with relative file path 'c:\Temp\bob-recursive-example\.logs'
```
It seems that vscode.workspace.fs.createDirectory (at least on Windows) is not happy with what it's being given. I'll create a PR to fix that 😉
