### ISSUE TITLE
Deploy changed files breaks when multiple deploy sources in workspace

### ISSUE THREAD

**Issue by edmundreinhardt** [halcyon-tech/vscode-ibmi#1262]
Save us time! Click 'Report an Issue' from the Help and Support panel inside of VS Code after you have connected to a system.

**Describe the bug**
(A clear and concise description of what the bug is. We will not accept your bug and close it if this is not filled out correctly.)
I have 2 projects in my workspace (ibmi-bob and bob-recursive-example) 
they have separate corresponding target IFS directories for deployment
If I make a change in 1 project (bob-recursive-example)
But deploy the other (ibmi-bob)
Deployment fails with `Deployment failed: RangeError: path should be a `path.relative()`d string, but got "../bob-recursive-example/prepost/Rules.mk"`
(it seems that it is confused by a changed file that it outside of the root of the deployed project
If I deploy all the files in the project, the problem goes away.

Los problemas en espanol estan bien.

**To Reproduce**
- see above

**Expected behavior**
- successful deployment of all and only the changed files of the selected workspace root

**Screenshots**
![image](https://user-images.githubusercontent.com/11184579/235282328-bc4ccd03-3974-442f-88ff-7e629c3ed4e2.png)

**Environment (please complete the following information):**
 - Extension version [e.g. 0.x.x] 1.8.0
 - IBM i OS version [e.g. 7.x] 7.4

**Additional context**

**Comment by sebjulliand** [comment]
I'll look into it 😉

**Comment by sebjulliand** [comment]
I see the problem, I'll fix it quickly. You should have mentioned you used the `Changes` deployment method though. 😅
`Compare` and the others are not affected.
