### ISSUE TITLE
After upgrading Db2 for IBMi v0.2.10 getting message   "Cannot read properties of undefined (reading 'isBasicStatement')"

### ISSUE THREAD

**Issue by devinhh** [halcyon-tech/vscode-ibmi#1279]
After upgrading Db2 for IBMi v0.2.10 getting message   "Cannot read properties of undefined (reading 'isBasicStatement')" in the "IBM I:RESULTS"

* QCCSID: 37
* Features:
   * git: true
   * grep: true
   * tn5250: true
   * setccsid: true
   * md5sum: true
   * bash: true
   * chsh: true
   * GENCMDXML.PGM: true
   * GETNEWLIBL.PGM: true
   * QZDFMDB2.PGM: true
   * startDebugService.sh: true
   * attr: true
   * iconv: true
* SQL enabled: true
* Source dates enabled: false

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Errors:
```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2158: Library ILEDITOR exists in ASP device *SYSBAS.\nCPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/dtdevin/builds/NEWVID"
  },
  {
    "command": "system \"DLTOBJ OBJ(ILEDITOR/O_*) OBJTYPE(*FILE)\"",
    "code": 255,
    "stderr": "CPF2125: No objects deleted.",
    "cwd": "/home/dtdevin/builds/NEWVID"
  }
]
```

**Comment by worksofliam** [comment]
@devinhh by any chance do you know what version it worked on? Also had the same issue but need time to fix it.

**Comment by devinhh** [comment]
If I go back to 0.2.9 it works

**Comment by worksofliam** [comment]
I've found the issue. Will release the fix sometime this week

**Comment by devinhh** [comment]
Thanks

**Comment by worksofliam** [comment]
@devinhh 0.2.11 will solve this. Thanks!

**Comment by devinhh** [comment]
Looks good. Thanks
