### ISSUE TITLE
DB2 for IBM i: + More... Question

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#1282]
(Don't see how to ask questions or add an issue on the project page, so I guess this is the place.)

Version 0.2.11 - First time experimenting with it.  Impressive so far.

A question: Why does `" + More..."` appear when there is no more?  If you click it, then it tells you that there really isn't anything to load.  Definitely not a game stopper, just a minor quibble.  Perhaps it is a VS Code limitation.
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/67484051/8f79ed88-a431-4ea4-b815-8a8ba9e5c8e7)

**Comment by worksofliam** [comment]
It's just the way I implemented it. It'd be cool if that button went away if no more items were available.
