### ISSUE TITLE
Set Line Endings to LF on Deploy for BOB

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#1283]
**Is your feature request related to a problem? Please describe.**
Cloned IBM / ibm i-bob to my Window 10 PC and has issues with the build.  See https://github.com/IBM/ibmi-bob/issues/224.
Issue was resolved by changing my global git config to `git config --global core.autocrlf input` and re-cloning the project.

**Describe the solution you'd like**
@edmundreinhardt said "The long term solution is for Code for IBM i deploy to change line endings. Opening an issue on vscode-ibmi would help make this happen."

**Describe alternatives you've considered**
Changing my Git config  away from the default is a solution.

**Comment by worksofliam** [comment]
Nothing that we should do for this I think. Like endings can be changed by the user manually and I don't know if changing them automatically is a good idea.

@chrjorgensen @sebjulliand thoughts?

**Comment by chrjorgensen** [comment]
@worksofliam I don't think we should mess around changing line endings... git has a fix for this problem with the AUTOCRLF config setting, so it must be up to the user to ensure correct line endings. Windows is a P.i.t.A in this respect, as usual having its own "standard"...

I would always advice to use only LF as line ending, also on Windows. This will ensure such problems does not occur.
