### ISSUE TITLE
Enable CL Content Assist

### ISSUE THREAD

**Issue by GreggWillow** [halcyon-tech/vscode-ibmi#1284]
I have recently installed Code for i and I am trying to get the CL Content Assist activated. I watched your YouTube video on how to do this but it is unavailable in my Settings. I seen in a previous post here with the same issue and it was suggested that the poster needed...

RPGLE: https://marketplace.visualstudio.com/items?itemName=HalcyonTechLtd.vscode-rpgle
CL: https://marketplace.visualstudio.com/items?itemName=IBM.vscode-clle

These extensions have already been installed but like I noted, in Settings there is no selection for CL Content Assist. Any help would be appreciated.

**Comment by worksofliam** [comment]
Hey there.

Do you get a message that asks if you want to install the CL tools? There is no longer a configuration setting for it.

**Comment by GreggWillow** [comment]
I uninstalled CL and reinstalled and I did get the message. I answered it to update and it and now CL Assist works. It does not display very long, I remember that from the first install. Nice IDE, I use rdi but wanted to check this out. Very fast! I think I will bounce between them for awhile. Thanks for the reply.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
