### ISSUE TITLE
Source member not showing

### ISSUE THREAD

**Issue by Nithy29** [halcyon-tech/vscode-ibmi#1286]
I created a filter 1, to display all objects in my library.  It returned a list with "undefined"
I created another filter - filter 2, to display source members.  The filter is returning empty list

Both filter should objects that I can work with.  

OS Version is 7.3
VS Code is 
  Version: 1.78.1 (user setup)
  Commit: 6a995c4f4cc2ced6e3237749973982e751cb0bf9
  Date: 2023-05-04T09:48:08.683Z
  Electron: 22.5.1
  Chromium: 108.0.5359.215
  Node.js: 16.17.1
  V8: 10.8.168.25-electron.0
  OS: Windows_NT x64 10.0.19044
  Sandboxed: Yes

plugin -  Code for IBM i,  Version is 1.8.0

I have attached some screen shots

![Filter2](https://github.com/halcyon-tech/vscode-ibmi/assets/98414364/5166d2f1-2fe6-4e42-9aa7-c82f865f83f0)
![Filter1](https://github.com/halcyon-tech/vscode-ibmi/assets/98414364/13c8ef6b-c0a9-4a72-b0c9-7f99e910a77b)
![Screenshot 2](https://github.com/halcyon-tech/vscode-ibmi/assets/98414364/6032511e-3817-4a62-8059-405a462d26c0)
![Screenshot 1](https://github.com/halcyon-tech/vscode-ibmi/assets/98414364/e75dff0c-0d60-4297-980e-60a8a3389db7)

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the list appears.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by Nithy29** [comment]
Hi Barry

I reply to the email.  I was not sure if I got all the attachments. 

Here is the output you requested.  I have also attached the output from
those command

I also attached the IFS list and its output as well

Thanks

![Output of IFS](https://github.com/halcyon-tech/vscode-ibmi/assets/98414364/d3618da6-b400-4eb0-b050-a24e339a0c9b)
![Output of file O_qRC97nz8](https://github.com/halcyon-tech/vscode-ibmi/assets/98414364/5cc327ab-ca65-48b8-a072-2243bbdf195f)
![IFS Broswer output](https://github.com/halcyon-tech/vscode-ibmi/assets/98414364/cdc2d277-7825-4140-b2ae-1cab82f11277)
![IBM i Code output](https://github.com/halcyon-tech/vscode-ibmi/assets/98414364/f3e7c2f2-4efb-4f15-aee7-006078545a96)

**Comment by worksofliam** [comment]
@Nithy29 you're almost there. I really just need you to copy and paste the output into this issue. Thanks!

**Comment by Nithy29** [comment]
.: pwd

{

    "code": 0,

    "signal": null,

    "stdout": "/home/VA967",

    "stderr": ""

}

 

/home/VA967: pwd

{

    "code": 0,

    "signal": null,

    "stdout": "/home/VA967",

    "stderr": ""

}

 

/home/VA967: /QOpenSys/usr/bin/qsh

liblist

{

    "code": 0,

    "signal": null,

    "stdout": "RISCSYSLIB  SYS\nQSYS        SYS\nQSYS2       SYS\nQHLPSYS     SYS\nQUSRSYS     SYS\nQFNTCPL     SYS\nBNSOPR      SYS\nQSHELL      PRD\nBNSOPR3     USR\nUGLOBAL     USR\nFTP         USR\nQGPL        USR\nQTEMP       USR",

    "stderr": ""

}

 

/home/VA967: system "CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')"

{

    "code": 255,

    "signal": null,

    "stdout": "",

    "stderr": "CPF2111: Library ILEDITOR already exists."

}

 

/home/VA967: [ -d "/tmp" ]

{

    "code": 0,

    "signal": null,

    "stdout": "",

    "stderr": ""

}

 

/home/VA967: ls -p /QOpenSys/pkgs/bin/

{

    "code": 0,

    "signal": null,

    "stdout": "[\nalternatives\natob\nbase32\nbase64\nbasename\nbash\nbashbug\nbtoa\nc2ph\ncat\ncertutil\nchcon\nchgrp\nchmod\nchown\nchroot\nchsh\ncksum\ncmsutil\ncomm\ncorelist\ncp\ncpan\ncrlutil\ncsplit\ncurl\ncut\ndate\ndd\ndebuginfo-install\nderdump\ndf\ndir\ndircolors\ndirname\ndu\necho\nenc2xs\nencguess\nenv\nexpand\nexpr\nfactor\nfalse\nfind-repos-of-install\nfmt\nfold\ngroups\nh2ph\nh2xs\nhead\nhostid\nid\ninstall\ninstmodsh\njoin\njson_pp\nkill\nlibnetcfg\nlink\nlistsuites\nln\nlogname\nls\nmd5sum\nmkdir\nmkfifo\nmknod\nmktemp\nmodutil\nmv\nneeds-restarting\nnice\nnl\nnohup\nnproc\nnss-policy-check\nnumfmt\nocspclnt\nod\npackage-cleanup\npaste\npathchk\nperl\nperl5.24.1\nperlbug\nperldoc\nperlivp\nperlthanks\npiconv\npinky\npk12util\npl2pm\npod2html\npod2man\npod2text\npod2usage\npodchecker\npodselect\npp\npr\nprintenv\nprintf\nprove\npstruct\nptar\nptardiff\nptargrep\nptx\npwd\npydoc\npython\npython2\npython2.7\nreadlink\nrealpath\nrepo-graph\nrepo-rss\nrepoclosure\nrepodiff\nrepomanage\nrepoquery\nreposync\nrepotrack\nrm\nrmdir\nrpm\nrpm2archive\nrpm2cpio\nrpmdb\nrpmgraph\nrpmkeys\nrpmquery\nrpmsign\nrpmverify\nruncon\nselfserv\nseq\nsha1sum\nsha224sum\nsha256sum\nsha384sum\nsha512sum\nshasum\nshow-changed-rco\nshow-installed\nshred\nshuf\nsigntool\nsignver\nsleep\nsmtpd.py\nsort\nsplain\nsplit\nssltap\nstat\nstdbuf\nstrsclnt\nstty\nsum\nsymkeyutil\nsync\ntac\ntail\ntee\ntest\ntimeout\ntouch\ntr\ntrue\ntruncate\ntrust\ntsort\ntstclnt\ntty\nuname\nunexpand\nuniq\nunlink\nupdate-alternatives\nupdate-ca-certificates\nuptime\nurlgrabber\nusers\nvdir\nverifytree\nvfychain\nvfyserv\nwc\nwho\nwhoami\nxsubpp\nyes\nyum\nyum-builddep\nyum-complete-transaction\nyum-config-manager\nyum-debug-dump\nyum-debug-restore\nyum-groups-manager\nyumdb\nyumdownloader\nzipdetails",

    "stderr": ""

}

 

/home/VA967: ls -p /usr/bin/

{

    "code": 0,

    "signal": null,

    "stdout": "ARS3WAPI64\nARS3WCGI\nARS400IDX\nARSADM\nARSADMIN\nARSDATE\nARSDB\nARSDOC\nARSEXPRT\nARSFTERM\nARSLOAD\nARSLOG\nARSLSYNC\nARSMAINT\nARSODF\nARSPRT400\nARSRPT\nARSSLU\nARSSMTSM\nARSSTASH\nARSSYSCR\nARSTBLSP\nARSTFMT\nARSUSEC\nARSWWW\nARSWWWSL32\nARSXAPI\nARSXML\nRfile\najar\nappletviewer\napt\narmsrv\narmsrvconv\narspdoci\narspdump\narsxafp\narsxline\nattr\nbasename\nbash\nbison\ncat\ncatsplf\nchgrp\nchmod\nchown\nclrtmp\ncmp\ncompress\ncp\ncpio\ncut\ndataq\ndatarea\ndate\ndb2\ndb2profc\ndb2profc_trace\ndb2profp\nddns-confgen\ndel\ndelv\ndfmadmin\ndhcpd\ndhcrelay\ndig\ndirname\ndnssec-dsfromkey\ndnssec-importkey\ndnssec-keyfromlabel\ndnssec-keygen\ndnssec-revoke\ndnssec-settime\ndnssec-signzone\ndnssec-verify\ndspmsg\necho\negrep\nenv\nexpr\nextcheck\nfgrep\nfile\nfind\nflex\ngawk\ngencat\ngetjobid\ngmake\ngrep\ngunzip\ngzip\nhead\nhost\nhostname\nhttpapi\nhwkeytool\nicc\niconv\nid\nidlj\nikeyman\nipcrm\nipcs\nixlc\njar\njarsigner\njava\njavac\njavadoc\njavah\njavap\njconsole\njdb\njdmpview\njextract\njpzip/\nkdestroy\nkeytab\nkeytool\nkinit\nklist\nkpasswd\nksetup\nld\nldapadd\nldapchangepwd\nldapcompare\nldapdelete\nldapdiff\nldapexop\nldapmodify\nldapmodrdn\nldapsearch\nln\nlocale\nlogger\nlogname\nls\nmkdir\nmkfifo\nmv\nnamed\nnamed-checkconf\nnamed-checkzone\nnamed-compilezone\nnamed-journalprint\nnamed-rrchecker\nnative2ascii\nnohup\nnslookup\nnsupdate\nod\norbd\npack200\npax\nperl\npolicytool\npr\nprintenv\nprofconv\nprofdb\nprofp\nps\npwd\npwdx\nqar\nqsh\nrexec\nrexx\nrm\nrmdir\nrmic\nrmid\nrmiregistry\nrndc\nrndc-confgen\nschemagen\nsed\nserialver\nservertool\nsetccsid\nsh\nsort\nsplit\nsqlj\nstrEKM\nsystem\nsysval\ntail\ntar\ntee\ntest\ntnameserv\ntouch\ntr\ntsig-keygen\nuname\nuncompress\nuniq\nunpack200\nunzip\nwc\nwsgen\nwsimport\nxargs\nxjc\nzcat\nzip",

    "stderr": ""

}

 

/home/VA967: ls -p /QSYS.LIB/QZDFMDB2.PGM

{

    "code": 0,

    "signal": null,

    "stdout": "/QSYS.LIB/QZDFMDB2.PGM",

    "stderr": ""

}

 

/home/VA967: ls -p /QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh

{

    "code": 2,

    "signal": null,

    "stdout": "",

    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh not found"

}

 

/home/VA967: ls -p /QSYS.lib/ILEDITOR.lib/GE*.PGM

{

    "code": 0,

    "signal": null,

    "stdout": "/QSYS.lib/ILEDITOR.lib/GENCMDXML.PGM\n/QSYS.lib/ILEDITOR.lib/GETNEWLIBL.PGM",

    "stderr": ""

}

 

/home/VA967: echo $SHELL

{

    "code": 0,

    "signal": null,

    "stdout": "/QOpenSys/pkgs/bin/bash",

    "stderr": ""

}

 

/home/VA967: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"

select OS_VERSION || '.' || OS_RELEASE as VERSION from sysibmadm.env_sys_info

/home/VA967: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"

select max(ptf_group_level) as HIGHEST_DB2_PTF_GROUP_LEVEL from qsys2.group_ptf_info where PTF_GROUP_DESCRIPTION like 'DB2 FOR IBM I%' and ptf_group_status = 'INSTALLED';

{

    "code": 0,

    "signal": null,

    "stdout": "DB2>\n  ?>\n\nVERSION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \n---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n7.3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \n\n  1 RECORD(S) SELECTED.",

    "stderr": ""

}

 

{

    "code": 0,

    "signal": null,

    "stdout": "DB2>\n\nHIGHEST_DB2_PTF_GROUP_LEVEL \n----------------------------\n                          27\n\n  1 RECORD(S) SELECTED.\n\nDB2>",

    "stderr": ""

}

 

/home/VA967: system "DSPFD FILE(VA967/*ALL) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_ykeme4db)"

{

    "code": 0,

    "signal": null,

    "stdout": "CPF9861: Output file O_YKEME4DB created in library ILEDITOR.\nCPF9862: Member O_YKEME4DB added to output file O_YKEME4DB in library ILEDITOR.\nCPF3030: 47 records added to member O_YKEME4DB in file O_YKEME4DB in ILEDITOR.",

    "stderr": ""

}

 

/home/VA967: system "QSYS/CPYTOIMPF FROMFILE(ILEDITOR/O_ykeme4db O_ykeme4db) TOSTMF('/tmp/vscodetemp-O_ChlndMOb') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"

{

    "code": 0,

    "signal": null,

    "stdout": "",

    "stderr": ""

}

**Comment by worksofliam** [comment]
It looks like from your first screenshot that the column names are missing. Can you run this and share the resulting streamfile (`/tmp/issue1286`)?

1. `DSPFD FILE(VA967/*ALL) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(QTEMP/ABCD)`
2. `QSYS/CPYTOIMPF FROMFILE(QTEMP/ABCD ABCD) TOSTMF('/tmp/issue1286') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)`

**Comment by Nithy29** [comment]
Hi Allan, 

sorry for taking long. I have to extract data from my work laptop and then email to my personal to upload to git.  My organization does not allow me to upload to git

Thanks
[issue1286.txt](https://github.com/halcyon-tech/vscode-ibmi/files/11489066/issue1286.txt)

**Comment by Nithy29** [comment]
yes...

**Comment by Nithy29** [comment]
I am using the ADDCOLNAM(*SQL).  I also tried *SYS.  Both did not include the column names

**Comment by chrjorgensen** [comment]
@Nithy29 Just some follow-up questions:

1. Do you have SQL enabled on the connection?
2. Did you at any time see this error message: `The data area QSYS/QCPTOIMPF exists on this system and may impact Code for IBM i functionality.`?
3. If you right-click the connection and select `Connect and Reload Server Settings`, do you get the error mentioned above?

Just to ensure that our check for the data actually works - it should have caught this error!

**Comment by Nithy29** [comment]
Hi Christian 

Yes I have the SQL enabled.  

There were no errors regarding the data area  QCPTOIMPF or any sort.  Barry mention that the IFS file created by CPYTOIMPF did not include the heading names.  So I search for errors related to this. I found a post that was dealing with column name not included when using the CPYTOIMPF.  

Here is the link 

https://archive.midrange.com/midrange-l/201903/msg00678.html

This article is from midrange community

Hope this helps

**Comment by Nithy29** [comment]
Sorry I gave the wrong thread of the post

https://archive.midrange.com/midrange-l/201903/msg00679.html

**Comment by Nithy29** [comment]
Hi Christian

I don't think its anything related to Code for IBM i.   I believe the data area is part of OS to control the backward compatibility.   But may be you can mention this in the documentation as a check point

Thanks

**Comment by Nithy29** [comment]
Hi

I did what you told me and I received the warning message. Ir also gave me
an option to delete.

But I did not receive this error when I created the connection.

Hope this helps

Thanks

**Comment by chrjorgensen** [comment]
@Nithy29 Thanks for verifying the check is still working as expected. We (the support team) must have this reload option in mind, when issues like this are reported.

Thanks again!
