### ISSUE TITLE
Compile with multiple actions

### ISSUE THREAD

**Issue by jkdavew** [halcyon-tech/vscode-ibmi#1290]
Type: <b>Bug</b>

Line 1 of action has a prompted command (with leading ? symbol)
Line 2 can be any other statemnt

Compile a program and the prompted command will show all lines but should only be prompting the line for which the ? was on.

Extension version: 1.8.0
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by jkdavew** [comment]
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/15818305/261f92f9-0a03-4727-8670-441379988358)

**Comment by jkdavew** [comment]
@worksofliam thx for having a look at this!

**Comment by sebjulliand** [comment]
This will be fixed with the next release.
