### ISSUE TITLE
Cant connect to ASP

### ISSUE THREAD

**Issue by vaisoliviu** [halcyon-tech/vscode-ibmi#1300]
Hello.

Although i have inputted the ASP in the setting, it does not connect to it. Do u have any ideas?

* QCCSID: 65535
* Features:
   * git: false
   * grep: false
   * tn5250: false
   * setccsid: true
   * md5sum: false
   * bash: false
   * chsh: false
   * GENCMDXML.PGM: false
   * GETNEWLIBL.PGM: true
   * QZDFMDB2.PGM: true
   * startDebugService.sh: false
   * attr: true
   * iconv: true
* SQL enabled: false
* Source dates enabled: true

Variants
```json
{
  "american": "%23@$",
  "local": "��$"
}
```

Errors:
```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF3012:  Fichier GERECD non trouv� dans biblioth�que *LIBL.\nCPC2206:  Propri�t� de l'objet QZSHSYSTEM de QTEMP, type *USRSPC modifi�e.",
    "cwd": "/home/INFOVA"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF3012:  Fichier XPLIVDREF non trouv� dans biblioth�que *LIBL.\nCPC2206:  Propri�t� de l'objet QZSHSYSTEM de QTEMP, type *USRSPC modifi�e.",
    "cwd": "/home/INFOVA"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF3012:  Fichier FAGRASSIGN non trouv� dans biblioth�que *LIBL.\nCPC2206:  Propri�t� de l'objet QZSHSYSTEM de QTEMP, type *USRSPC modifi�e.",
    "cwd": "/home/INFOVA"
  }
]
```

**Comment by worksofliam** [comment]
More detail is needed in your issue.

Also, it looks like you'e having some encoding issues. I recommend you check out this page: https://halcyon-tech.github.io/docs/#/pages/tips/ccsid

**Comment by vaisoliviu** [comment]
I changed the SSCID on the user level and system level to 297.
Also created the PASE_LANG and QIBM_PASE_CCSID, and restarted the SSH server.
Yet, when connecting VS Code, i get this message:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/51542033/7a3d2079-84f3-46ef-b8d0-a00ad9728075)

**Comment by vaisoliviu** [comment]
> More detail is needed in your issue.
> 
> Also, it looks like you'e having some encoding issues. I recommend you check out this page: https://halcyon-tech.github.io/docs/#/pages/tips/ccsid
 
What details are needed?

**Comment by chrjorgensen** [comment]
@vaisoliviu You should also update the server settings by right-click the connection and select `Connect and Reload Server Settings`. This will refresh the server settings seen by Code for IBM i and may help resolve your issue.

**Comment by vaisoliviu** [comment]
<hr />

|Context|Version|
|-|-|
|Code for IBM i version|1.9.0|
|Visual Studio Code version|1.78.2|
|Operating System|win32_x64|


<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 9.5.6
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.2.11
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.11.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.5
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>


<hr />


<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R3M0|
|Tech Refresh|13|
|QCCSID|297|
|SQL|Enabled
|Source dates|Disabled

* Enabled features:
  * GENCMDXML.PGM
  * GETNEWLIBL.PGM
  * QZDFMDB2.PGM
  * attr
  * iconv
  * ls
  * setccsid
  * tar
</details>



<details>
<summary>Shell env</summary>

```bash
```
</details>



<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "£à$"
}
```
</details>



<details>
<summary>Errors</summary>

```json
[
  {
    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh",
    "code": 2,
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh not found",
    "cwd": "/home/INFOVA"
  },
  {
    "command": "system \"DSPOBJD OBJ(FOURNIER/*ALL) OBJTYPE(*ALL) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_Y82d3VHU)\"",
    "code": 255,
    "stderr": "CPF2110: Bibliothèque FOURNIER non trouvée.",
    "cwd": "/home/INFOVA"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"INFOVA\" && export HOME=\"/home/INFOVA\" && export LIBLS=\"FACDUPNEW FAXN2OBJ IAFTP QTEMP QGPL\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/INFOVA"
  }
]
```
</details>

I updated to 1.9.0, and it still does not connect to the IASP.
