### ISSUE TITLE
Update Production Files setting not working

### ISSUE THREAD

**Issue by cwbuck** [halcyon-tech/vscode-ibmi#1307]
When starting up debug for a program that opens a file in a production library, my job goes to MSGW with an error on file open:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/68613130/d16f2955-799c-4936-98b6-3b6123ecd036)

I have confirmed that my extension setting 'update production files' is checked
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/68613130/a467ac5c-dd3d-4594-b615-4d1ed5ddf350)

And I have even regenerated certs and restarted the debug service since applying this change to no avail.

* QCCSID: 65535
* Features:
   * git: true
   * grep: true
   * tn5250: false
   * setccsid: true
   * md5sum: true
   * bash: true
   * chsh: false
   * GENCMDXML.PGM: true
   * GETNEWLIBL.PGM: true
   * QZDFMDB2.PGM: true
   * startDebugService.sh: true
   * attr: true
   * iconv: true
* SQL enabled: false
* Source dates enabled: true

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Errors:
```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/CBUCK"
  },
  {
    "command": "MY_JAVA_HOME=\"/QOpenSys/QIBM/ProdData/JavaVM/jdk80/64bit\" DEBUG_SERVICE_KEYSTORE_PASSWORD=\"sZt4qB9hBkqhYR7mu7TpVFiDMRQx9ZR4VWGX/G8lZ6k=\" DEBUG_SERVICE_KEYSTORE_FILE=\"/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx\" /QOpenSys/usr/bin/nohup \"/QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh\"",
    "code": 255,
    "stderr": "java version \"1.8.0_331\"\nJava(TM) SE Runtime Environment (build 8.0.7.10 - pap6480sr7fp10-20220505_01(SR7 FP10))\nIBM J9 VM (build 2.9, JRE 1.8.0 OS/400 ppc64-64-Bit Compressed References 20220401_26248 (JIT enabled, AOT enabled)\nOpenJ9   - 255b7d9\nOMR      - 3671a9f\nIBM      - 1b0232b)\nJCL - 20220504_01 based on Oracle jdk8u331-b09",
    "cwd": "/home/CBUCK"
  }
]
```

**Comment by mkwan01** [comment]
If you also have RDi, please use RDi to debug the same program by checking the "Update production files" setting in the launch configuration dialog. Let us know whether you would see the same error in RDi.

**Comment by cwbuck** [comment]
@mkwan01 For sure. I just debugged in RDi -- no errors.

**Comment by cwbuck** [comment]
@mkwan01 @worksofliam 
WAIT -- I figured it out. The primary 'Update Productions File' setting for the Extension in Preferences > Settings > Extensions > IBM i Debug doesn't seem to handle this. It appears it has to be specifically set for the connection configuration you are using. 

**However**, when setting up a new connection config or even updating an old connection config from the main IBM I: SERVERS section, you will not see the new 'Debugger' section in the Settings view for the connection. So it's difficult to find this setting:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/68613130/360ab661-77f4-481d-a9f6-df9b2055fe08)
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/68613130/b79deefb-c2d0-4f42-b3b6-a32bebdea907)

I finally found it by selecting the 'Settings: ${server}' in the Status Bar after establishing a connection for one of my profiles.
Opening the Settings from here appears to have the new 'Debugger' tab, at which point I realized I did not have the setting selected here yet:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/68613130/bdeba484-2123-4600-945f-b3db96506632)
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/68613130/0920a960-8409-4d45-b16f-e9d24975ec3d)

So not quite as big of an issue, but still a little confusing to figure out. I'm not sure what the main extension setting really controls if it ultimately needs to be set at the connection level.

**Comment by cwbuck** [comment]
Makes sense, just a little confusing to figure out. Once I set up a connection config, I wouldn't have necessarily guessed that display would have had additional settings available after connecting. And also, I would generally have just edited from the main list (after disconnecting). I didn't think to get there from the status bar until this morning. Not sure how you would overcome that though--as I see what you're saying about having to determine if debugger is actually installed or not. Plus, it's entirely possible I'm the only one that struggled to figure it out lol.

**Comment by worksofliam** [comment]
@cwbuck I will think of ways to make it clearer.

Sorry for the confusion.

**Comment by cwbuck** [comment]
No problem! Once configured correctly, debugger experience is great!
