### ISSUE TITLE
Connessione IBM i 

### ISSUE THREAD

**Issue by bormax61** [halcyon-tech/vscode-ibmi#1322]
Type: <b>Bug</b>

Not connected to server IBM i . Shell config error. 

Extension version: 1.9.0
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (2.98GB free)|
|Process Argv|--crash-reporter-id 3dfd6922-7476-4ea6-94fb-b38fe21d8e4b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
7ij38806:30736111
pythonfmttext:30731395
pythoncmv:30739700
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpathcf:30739705

```

</details>

**Comment by sebjulliand** [comment]
Hi,
please share any Output, console error and error notification encountered while trying to connect?

Also:
- Is bash your default shell when connecting to IBM i?
- Can you connect to IBM i using an external client? (i.e. the `ssh` command in a terminal or using `Putty` on Windows)

You can get more information about connecting through SSH here: https://ibmi-oss-docs.readthedocs.io/en/latest/user_setup/README.html

**Comment by bormax61** [comment]
![immagine01](https://github.com/halcyon-tech/vscode-ibmi/assets/135013605/046ed459-392f-4fdb-9824-24c30cdbbc0e)

**Comment by sebjulliand** [comment]
Please refer to this section of the documentation: https://halcyon-tech.github.io/docs/#/pages/tips/setup?id=unexpected-packet-before-version

You most likely have something in your `.bashrc` file (or another initialization file) that writes something to the standard output when the SSH connection is opened. The connection cannot be established when it's the case.

One way to fix this is to remove these commands from `.bashrc` if possible, or move them to a `.profile` file (see the link above for the details).
