### ISSUE TITLE
IFS Shortcut to non-existant path still shows objects

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#1325]
To re-create
Create an IFS shortcut to a directory that doesn't exist:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/67484051/9308d895-22c6-46f7-a4b0-97a5c17e9d74)

Shortcut is created:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/67484051/31c95006-8b4f-448d-a6e0-ce81f59a7e15)

Expand the shortcut and see directories and files that don't exist
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/67484051/39bf3e51-ad15-4a1e-b386-b3178bbd43f4)

Keep expanding and you can do so (seemingly) indefinitely.
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/67484051/fc09de59-5078-4e27-bbea-9cf6b51d2ebd)

The files that turn up appear to be those in my home directory:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/67484051/d3cba381-f571-4e78-9b03-4114ab15a394)

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|1.9.0|
|Visual Studio Code version|1.78.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.2.11
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.11.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitLens — Git supercharged (gitlens): 13.6.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.5
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|1|
|QCCSID|37|
|SQL|Enabled
|Source dates|Disabled

* Enabled features:
  * GENCMDXML.PGM
  * GETNEWLIBL.PGM
  * QZDFMDB2.PGM
  * attr
  * bash
  * chsh
  * git
  * grep
  * iconv
  * ls
  * md5sum
  * setccsid
  * sort
  * startDebugService.sh
  * stat
  * tar
  * tn5250
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=LENNONSB
CURLIB=LENNONSB
HOME=/home/LENNONS
LIB1=LENNONSB
LIBLS=LENNONSB QGPL QTEMP QIWS
LOGIN=lennons
LOGNAME=lennons
MAIL=/var/spool/mail/lennons
OLDPWD=/home/LENNONS
PASE_USRGRP_LIMITED=N
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/LENNONS
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=108.4.52.93 50655 2222
SSH_CONNECTION=108.4.52.93 50655 185.113.5.134 2222
TZ=<UTC>0
USER=lennons
USERNAME=lennons
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "echo \"\" > /home/lennons/builds/fred",
    "code": 1,
    "stderr": "bash: line 1: /home/lennons/builds/fred: No such file or directory",
    "cwd": "/home/LENNONS"
  },
  {
    "command": "/QOpenSys/pkgs/bin/stat --dereference --printf=\"%A\t%h\t%U\t%G\t%s\t%Y\t%n\n\" * .*  ",
    "code": 1,
    "stderr": "/QOpenSys/pkgs/bin/stat: cannot stat '*': No such file or directory",
    "cwd": "/home/LENNONS/hello-world.git/Images"
  },
  {
    "command": "/QOpenSys/pkgs/bin/stat --dereference --printf=\"%A\t%h\t%U\t%G\t%s\t%Y\t%n\n\" * .*  ",
    "code": 1,
    "stderr": "/QOpenSys/pkgs/bin/stat: cannot stat '*': No such file or directory",
    "cwd": "/home/LENNONS/my_Git"
  }
]
```
</details>

**Comment by worksofliam** [comment]
I wonder if this is regarding how we have started capturing errors?

@chrjorgensen @sebjulliand

**Comment by chrjorgensen** [comment]
@worksofliam Yeah, the error capturing was part of the problem: The `cd` command failed but `stat` was executed anyway, so `code` was 1, `stderr` contained the `cd` error - and `stdout` contained the `stat` output...

I did some tidying up in PR #1327...
