### ISSUE TITLE
Program extension is not getting updated when using the "Upload and Replace" from the Object Browser

### ISSUE THREAD

**Issue by devinhh** [halcyon-tech/vscode-ibmi#1332]
I have a program that has changed from pgm.rpgle to pgm.sqlrpgle.  When I use the "Upload and Replace" from the Object Browser to get the new version from the Git directory on my PC, the contents of the program is replaced but the .rpgle is not changed to the new .sqlrpgle.

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|1.9.1|
|Visual Studio Code version|1.78.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
ARCAD-CodeChecker (arcad-codechecker): 1.0.0
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.2.11
ESLint (vscode-eslint): 2.4.1
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.11.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
Git Graph (git-graph): 1.30.0
Git Tags (vscode-git-tags): 1.4.4
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitHub Pull Requests and Issues (vscode-pull-request-github): 0.64.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.5
JSON Language Features (json-language-features): 1.0.0
Live Share (vsliveshare): 1.0.5864
Material Icon Theme (material-icon-theme): 4.28.0
Material Theme (vsc-material-theme): 33.8.0
Material Theme Icons (vsc-material-theme-icons): 2.7.5
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
Power Mode (vscode-power-mode): 3.0.2
Prettier - Code formatter (prettier-vscode): 9.13.0
RPGLE (vscode-rpgle): 0.19.2
RPGLE Free (vscode-rpgfree): 0.0.25
Simple CSV editor (csv-editor): 0.2.2
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
vscode-icons (vscode-icons): 12.4.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|7|
|CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

**Comment by worksofliam** [comment]
Upload does not change file names. As you discovered, it only changes the content of the file. That is normal behaviour.
