### ISSUE TITLE
Max identification string size error

### ISSUE THREAD

**Issue by Alfmesiter** [halcyon-tech/vscode-ibmi#1342]
What must one do to correct the Max identification string size exceeded error?

**Comment by worksofliam** [comment]
@Alfmesiter Are you able to connect with standard SSH? Previous times we've seen this it's because the SSH port has been incorrect

**Comment by Alfmesiter** [comment]
My apologies, I'm not familiar with "connect with standard SSH". The TCP server has been started on the IBMi and the QSSHD profile is enabled. The connection was configured with the IP and port used for Access Client Solutions, so I know they are active.

Thanks,
Bryan

**Comment by worksofliam** [comment]
Code for IBM i uses SSH to connect to IBM i. You can learn about using SSH here: https://ibmi-oss-docs.readthedocs.io/en/latest/user_setup/README.html
