### ISSUE TITLE
IFS Browser - unable to browse a folder containing a space

### ISSUE THREAD

**Issue by jkdavew** [halcyon-tech/vscode-ibmi#1348]
While using the IFS Browser and navigating to a folder containing a space, VSCode shows a couple of errors and the contents of the folder are not shown.

Error
1 error occurred while listing files.
Source: Code for IBM i (Extension).

Error
bsh: cd: too many arguments
Source: Code for IBM i (Extension).

Side note: displaying a file which has a space in the name works.

**Comment by chrjorgensen** [comment]
@jkdavew Please update to the latest version if not already there, and then open the Help view and click `Report an issue` and copy-paste the issue content here...

**Comment by sebjulliand** [comment]
I think that should take care of it: https://github.com/halcyon-tech/vscode-ibmi/pull/1350

**Comment by jkdavew** [comment]
Thank you for the fix!  Now that the repo is updated, what is the deploy schedule to update the plugin in the VSCode Marketplace?  Thx

**Comment by sebjulliand** [comment]
> Thank you for the fix! Now that the repo is updated, what is the deploy schedule to update the plugin in the VSCode Marketplace? Thx

It's being published at this very moment. It should be available in a few minutes.
This is @chrjorgensen first release, too 😎

**Comment by chrjorgensen** [comment]
> This is @chrjorgensen first release, too 😎

Shhhh! Don't tell!! 😉

**Comment by sebjulliand** [comment]
> > This is @chrjorgensen first release, too 😎
> 
> Shhhh! Don't tell!! 😉

This calls for a celebration!

**Comment by jkdavew** [comment]
Amazing first release - worked like a charm!!  Thx team!
