### ISSUE TITLE
RPGLE outline view "No symbols found" error

### ISSUE THREAD

**Issue by pdow** [halcyon-tech/vscode-ibmi#1355]
Type: <b>Bug</b>

Install extensions "Code for IBM i", "IBM i Languages", "RPGLE Free", and "RPG" extensions.

Open HelloWorld.pgm.rpgle.

Outline view says "No symbols found in document 'helloWorld.pgm.rpgle'"

Disable "RPG" extension.

Outline view now shows
  printf
  mytext

Extension version: 1.9.3
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:26:35.552Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (8.00GB free)|
|Process Argv|--crash-reporter-id 658e1802-a115-4cce-b7a4-57787c5fa440|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
hidesbindicator:30760978
pythongtdpathcf:30739705
dh2dc718:30763024

```

</details>

**Comment by worksofliam** [comment]
Doesn't seem like a bug. You had colliding extensions.

**Comment by pdow** [comment]
Then I guess it would help if there were a check for colliding extensions.

I just checked, and realized that in the lower right corner it appears 
to say what source type it thinks it is working with.  The HelloWorld 
source is **FREE, and the filename extension is .rpgle, but when both 
the RPG and RPGLE extensions are enabled, it chose RPG.  How does it decide?
