### ISSUE TITLE
Filter not showing results

### ISSUE THREAD

**Issue by mascarenhasl** [halcyon-tech/vscode-ibmi#1363]
I am new to Code for IBMi using version v1.9.4

Issue - I have created a filter to list Source PF from a Library.  the filter i not returning file names, no sure what is the issue. 

In the output related to "Code for IBMi" is listed below.  I see data in file REQLM04.O_2PAzacVx on iSeries server. 

/home/MASCARENHL/java: system "DSPFD FILE(LEOM1/*ALL) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(REQLM04/O_2PAzacVx)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_2PAZACVX created in library REQLM04.\nCPF9862: Member O_2PAZACVX added to output file O_2PAZACVX in library REQLM04.\nCPF3030: 1090 records added to member O_2PAZACVX in file O_2PAZACVX in REQLM04.",
    "stderr": ""
}

/home/MASCARENHL/java: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT * FROM REQLM04.O_2PAzacVx
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n                                                   Output Originated on Dev",
    "stderr": ""
}

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|1.9.4|
|Visual Studio Code version|1.79.0|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|?|
|Tech Refresh|?|
|CCSID|?|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/usr/bin|/QSYS.lib/REQLM04.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|
|attr|GETNEWLIBL.PGM|QZDFMDB2.PGM|startDebugService.sh|
|iconv||||
|ls||||
|setccsid||||
|tar||||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx",
    "code": 2,
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx not found",
    "cwd": "/home/MASCARENHL/java"
  },
  {
    "command": "export BUILDLIB=\"\" && export CURLIB=\"\" && export USERNAME=\"powerlm\" && export HOME=\"/home/MASCARENHL/java\" && export LIBLS=\"REQLM04 LEOM1\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=: is not an identifier",
    "cwd": "/home/MASCARENHL/java"
  },
  {
    "command": "export BUILDLIB=\"\" && export CURLIB=\"\" && export USERNAME=\"powerlm\" && export HOME=\"/home/MASCARENHL/java\" && export LIBLS=\"REQLM04 LEOM1\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=: is not an identifier",
    "cwd": "/home/MASCARENHL/java"
  }
]
```
</details>

Json setting
"code-for-ibmi.connectionSettings": [
        
        {
            "name": "iseriesDevelopment",
            "host": "",
            "objectFilters": [
                {
                    "name": "LEOM1-FULL",
                    "library": "LEOM1",
                    "object": "*",
                    "types": [
                        "*SRCPF"
                    ],
                    "member": "*",
                    "memberType": "*",
                    "protected": false,
                    "buttons": "SAVE"
                }
            ],
            "libraryList": [
                "LEOM1",
                "REQLM04"
            ],
            "autoClearTempData": false,
            "customVariables": [],
            "connectionProfiles": [],
            "commandProfiles": [],
            "ifsShortcuts": [
                "/home/MASCARENHL/java",
                "/home/leom",
                "/home/iseriesdata/ibmi/d365"
            ],
            "autoSortIFSShortcuts": false,
            "homeDirectory": "/home/MASCARENHL/java",
            "enableSQL": true,
            "tempLibrary": "REQLM04",
            "tempDir": "/tmp",
            "currentLibrary": "",
            "sourceASP": "",
            "sourceFileCCSID": "*FILE",
            "autoConvertIFSccsid": false,
            "hideCompileErrors": [],
            "enableSourceDates": false,
            "sourceDateMode": "edit",
            "sourceDateGutter": false,
            "encodingFor5250": "default",
            "terminalFor5250": "default",
            "setDeviceNameFor5250": false,
            "connectringStringFor5250": "localhost",
            "autoSaveBeforeAction": false,
            "showDescInLibList": false,
            "debugPort": "8005",
            "debugIsSecure": false,
            "debugUpdateProductionFiles": false,
            "debugEnableDebugTracing": false,
            "readOnlyMode": false,
            "quickConnect": true
        },

**Comment by chrjorgensen** [comment]
@mascarenhasl Welcome to the Code for IBM i extension. 😃 

Sorry to hear about your problems... it's probably your server language settings, that is the problem. Please check your setup against the documentation here:
https://halcyon-tech.github.io/docs/#/pages/tips/ccsid
