### ISSUE TITLE
'Report an Issue' not working

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#1364]
Save us time! Click 'Report an Issue' from the Help and Support panel inside of VS Code after you have connected to a system.

I tried this and it flashes "Gathering issue details..." and then nothing.   I'm pretty sure I did this in the last couple of weeks and it opened up Firefox and copied in all the useful info you need into a new issue.  I'm on 1.9.4 running on Windows 10. connected to PUB400.COM. 

I've exited VSCode and reconnected and the problem still exists. Hope I'm not overlooking something or doing something stupid.

**Describe the bug**
(A clear and concise description of what the bug is. We will not accept your bug and close it if this is not filled out correctly.)

Los problemas en espanol estan bien.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Extension version [e.g. 0.x.x]
 - IBM i OS version [e.g. 7.x]

**Additional context**

**Comment by sebjulliand** [comment]
Good catch!
Turns out some of the information we get from the system are not accessible to everybody (OS version and TR level).
This PR will fix this: https://github.com/halcyon-tech/vscode-ibmi/pull/1365
