### ISSUE TITLE
All source files giving the 'Failed to save file xxxxx  unable to write file' message  

### ISSUE THREAD

**Issue by AndyGildroy** [halcyon-tech/vscode-ibmi#1375]
Hi,   very new user to VS Code but this seems to happen for any source file I try to save ...not sure what I have done wrong - the profile I've used to connect should have all permissions needed - it's the same one I use on green screen SEU.   A 'side issue' is that it seems to be obliterating the the source on the IBMi before trying/failing to save.   Hope someone can help  

Thanks In advance 
Andy

**Comment by AndyGildroy** [comment]
Thanks such a prompt reply ...the output in the output tab doesn't seem to be changing updating when I try to save

**Comment by ffleer** [comment]
I have the same problem but only if the file size exceeds 100 KB ?!!

**Comment by ffleer** [comment]
And what’s worse it also clears the source physical file member.

**Comment by AndyGildroy** [comment]
Yes that's happening here too

**Comment by worksofliam** [comment]
Folks, we really need the Code for IBM i output channel content (found in the drop-down on the Output tab) in order to debug these issues.

Thanks!

**Comment by RolandStrauss** [comment]
Hi Liam, I believe the issue #1329 (I logged), could be the same as described here. I have attached various logs to #1329 and output as requested. Maybe my logs there could assist

**Comment by ffleer** [comment]
> Folks, we really need the Code for IBM i output channel content (found in the drop-down on the Output tab) in order to debug these issues.
> 
> Thanks!



Current library: W_FF00150
Library list: QTEMP OPSSLIBW OPSSLIBQ OPSSLIBP OPSOLIBW OPSOLIBQ JD_SECFQ7 W_FF00150 QGPL JD_CBNFQ7
Commands:
		DSPFFD FILE(*LIBL/FI4101) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RFI4487580)



Current library: W_FF00150
Library list: QTEMP OPSSLIBW OPSSLIBQ OPSSLIBP OPSOLIBW OPSOLIBQ JD_SECFQ7 W_FF00150 QGPL JD_CBNFQ7
Commands:
		DSPFFD FILE(*LIBL/F4101LA) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RF41487583)

CPF3012:  FILE FI4101 IN LIBRARY *LIBL NOT FOUND.
CPC2206:  OWNERSHIP OF OBJECT QZSHSYSTEM IN QTEMP TYPE *USRSPC CHANGED.
CPF3012:  FILE F4101LA IN LIBRARY *LIBL NOT FOUND.
CPC2206:  OWNERSHIP OF OBJECT QZSHSYSTEM IN QTEMP TYPE *USRSPC CHANGED.


Current library: W_FF00150
Library list: QTEMP OPSSLIBW OPSSLIBQ OPSSLIBP OPSOLIBW OPSOLIBQ JD_SECFQ7 W_FF00150 QGPL JD_CBNFQ7
Commands:
		DSPFFD FILE(*LIBL/F4101LB) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RF41487881)



Current library: W_FF00150
Library list: QTEMP OPSSLIBW OPSSLIBQ OPSSLIBP OPSOLIBW OPSOLIBQ JD_SECFQ7 W_FF00150 QGPL JD_CBNFQ7
Commands:
		DSPFFD FILE(*LIBL/F4101LC) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RF41487883)

CPF3012:  FILE F4101LB IN LIBRARY *LIBL NOT FOUND.
CPC2206:  OWNERSHIP OF OBJECT QZSHSYSTEM IN QTEMP TYPE *USRSPC CHANGED.


Current library: W_FF00150
Library list: QTEMP OPSSLIBW OPSSLIBQ OPSSLIBP OPSOLIBW OPSOLIBQ JD_SECFQ7 W_FF00150 QGPL JD_CBNFQ7
Commands:
		DSPFFD FILE(*LIBL/FHCP9201) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RFHC488144)

CPF3012:  FILE F4101LC IN LIBRARY *LIBL NOT FOUND.
CPC2206:  OWNERSHIP OF OBJECT QZSHSYSTEM IN QTEMP TYPE *USRSPC CHANGED.


Current library: W_FF00150
Library list: QTEMP OPSSLIBW OPSSLIBQ OPSSLIBP OPSOLIBW OPSOLIBQ JD_SECFQ7 W_FF00150 QGPL JD_CBNFQ7
Commands:
		DSPFFD FILE(*LIBL/F9201) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RF92488209)

CPF3012:  FILE FHCP9201 IN LIBRARY *LIBL NOT FOUND.
CPC2206:  OWNERSHIP OF OBJECT QZSHSYSTEM IN QTEMP TYPE *USRSPC CHANGED.


Current library: W_FF00150
Library list: QTEMP OPSSLIBW OPSSLIBQ OPSSLIBP OPSOLIBW OPSOLIBQ JD_SECFQ7 W_FF00150 QGPL JD_CBNFQ7
Commands:
		DSPFFD FILE(*LIBL/FHCP1000) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RFHC488415)

CPF3012:  FILE F9201 IN LIBRARY *LIBL NOT FOUND.
CPC2206:  OWNERSHIP OF OBJECT QZSHSYSTEM IN QTEMP TYPE *USRSPC CHANGED.


Current library: W_FF00150
Library list: QTEMP OPSSLIBW OPSSLIBQ OPSSLIBP OPSOLIBW OPSOLIBQ JD_SECFQ7 W_FF00150 QGPL JD_CBNFQ7
Commands:
		DSPFFD FILE(*LIBL/FHCP1000LA) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RFHC488471)

CPF3012:  FILE FHCP1000 IN LIBRARY *LIBL NOT FOUND.
CPC2206:  OWNERSHIP OF OBJECT QZSHSYSTEM IN QTEMP TYPE *USRSPC CHANGED.


Current library: W_FF00150
Library list: QTEMP OPSSLIBW OPSSLIBQ OPSSLIBP OPSOLIBW OPSOLIBQ JD_SECFQ7 W_FF00150 QGPL JD_CBNFQ7
Commands:
		DSPFFD FILE(*LIBL/FHCP1001) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RFHC488692)

CPF3012:  FILE FHCP1000LA IN LIBRARY *LIBL NOT FOUND.
CPC2206:  OWNERSHIP OF OBJECT QZSHSYSTEM IN QTEMP TYPE *USRSPC CHANGED.


Current library: W_FF00150
Library list: QTEMP OPSSLIBW OPSSLIBQ OPSSLIBP OPSOLIBW OPSOLIBQ JD_SECFQ7 W_FF00150 QGPL JD_CBNFQ7
Commands:
		DSPFFD FILE(*LIBL/FHCP1001LB) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RFHC488750)

CPF3012:  FILE FHCP1001 IN LIBRARY *LIBL NOT FOUND.
CPC2206:  OWNERSHIP OF OBJECT QZSHSYSTEM IN QTEMP TYPE *USRSPC CHANGED.


Current library: W_FF00150
Library list: QTEMP OPSSLIBW OPSSLIBQ OPSSLIBP OPSOLIBW OPSOLIBQ JD_SECFQ7 W_FF00150 QGPL JD_CBNFQ7
Commands:
		DSPFFD FILE(*LIBL/F0101) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RF01488935)

CPF3012:  FILE FHCP1001LB IN LIBRARY *LIBL NOT FOUND.
CPC2206:  OWNERSHIP OF OBJECT QZSHSYSTEM IN QTEMP TYPE *USRSPC CHANGED.


Current library: W_FF00150
Library list: QTEMP OPSSLIBW OPSSLIBQ OPSSLIBP OPSOLIBW OPSOLIBQ JD_SECFQ7 W_FF00150 QGPL JD_CBNFQ7
Commands:
		DSPFFD FILE(*LIBL/FHCP1005) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RFHC488998)

CPF3012:  FILE FHCP1005 IN LIBRARY *LIBL NOT FOUND.
CPC2206:  OWNERSHIP OF OBJECT QZSHSYSTEM IN QTEMP TYPE *USRSPC CHANGED.
CPF9861:  OUTPUT FILE RF01488935 CREATED IN LIBRARY ILEDITOR.
CPF9862:  MEMBER RF01488935 ADDED TO OUTPUT FILE RF01488935 IN LIBRARY ILEDITOR.
CPF427D:  SUBSTITUTION CHARACTERS MAY BE USED IN DATA CONVERSION.
CPF427D:  SUBSTITUTION CHARACTERS MAY BE USED IN DATA CONVERSION.
CPF3030:  76 RECORDS ADDED TO MEMBER RF01488935 IN FILE RF01488935 IN ILEDITOR.
CPC2206:  OWNERSHIP OF OBJECT QZSHSYSTEM IN QTEMP TYPE *USRSPC CHANGED.


Current library: W_FF00150
Library list: QTEMP OPSSLIBW OPSSLIBQ OPSSLIBP OPSOLIBW OPSOLIBQ JD_SECFQ7 W_FF00150 QGPL JD_CBNFQ7
Commands:
		DSPFFD FILE(*LIBL/RHCP1000) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RRHC489315)



Current library: W_FF00150
Library list: QTEMP OPSSLIBW OPSSLIBQ OPSSLIBP OPSOLIBW OPSOLIBQ JD_SECFQ7 W_FF00150 QGPL JD_CBNFQ7
Commands:
		DSPFFD FILE(*LIBL/F0005) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RF00489795)

CPF3012:  FILE RHCP1000 IN LIBRARY *LIBL NOT FOUND.
CPC2206:  OWNERSHIP OF OBJECT QZSHSYSTEM IN QTEMP TYPE *USRSPC CHANGED.
CPF3012:  FILE F0005 IN LIBRARY *LIBL NOT FOUND.
CPC2206:  OWNERSHIP OF OBJECT QZSHSYSTEM IN QTEMP TYPE *USRSPC CHANGED.


Current library: W_FF00150
Library list: QTEMP OPSSLIBW OPSSLIBQ OPSSLIBP OPSOLIBW OPSOLIBQ JD_SECFQ7 W_FF00150 QGPL JD_CBNFQ7
Commands:
		CHKOBJ OBJ(JDPLIBSW7/JDELESRC) OBJTYPE(*FILE) AUT(*UPD)

CPC2206:  OWNERSHIP OF OBJECT QZSHSYSTEM IN QTEMP TYPE *USRSPC CHANGED.

**Comment by ffleer** [comment]
Changing the library list to fix the "File not found" errors does not make a difference. 
I no longer get any messages in the "Output" tab.

**Comment by ffleer** [comment]
yes "Enable Source Dates" and "Enable SQL" are both enabled.

**Comment by ffleer** [comment]
Disabling SQL did not make a difference BUT disabling Source Dates DOES !

**Comment by AndyGildroy** [comment]
Hi
**_Folks, we really need the Code for IBM i output channel content (found in the drop-down on the Output tab) in order to debug these issues.

Thanks!_**

Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/PCMACHPF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RPCM858967)

CPF3012:  File PCMACHPF in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/PCORDL0) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RPCO859998)

CPF3012:  File PCORDL0 in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/PCSCHPF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RPCS860354)

CPF3012:  File PCSCHPF in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/PCCRITPF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RPCC860679)

CPF3012:  File PCCRITPF in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/HRJCIML1) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RHRJ861035)

CPF3012:  File HRJCIML1 in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/PCHAZPF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RPCH861361)

CPF3012:  File PCHAZPF in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/HRJNFCPF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RHRJ861687)

CPF3012:  File HRJNFCPF in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/HRJNFCL2) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RHRJ861954)

CPF3012:  File HRJNFCL2 in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/COSIZEL1) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RCOS862253)

CPF3012:  File COSIZEL1 in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/HRJBOML1) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RHRJ862556)

CPF3012:  File HRJBOML1 in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/PCLEADPF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RPCL862832)

CPF3012:  File PCLEADPF in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/PCFNWDPF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RPCF863115)

CPF3012:  File PCFNWDPF in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/HRJFITPF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RHRJ863386)

CPF3012:  File HRJFITPF in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/HRJGPRL1) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RHRJ863678)

CPF3012:  File HRJGPRL1 in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/HRJGPCL3) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RHRJ863961)

CPF3012:  File HRJGPCL3 in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/HRJFACPF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RHRJ864247)

CPF3012:  File HRJFACPF in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/HRJGCHL1) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RHRJ864528)

CPF3012:  File HRJGCHL1 in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/DCSCIU) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RDCS864784)

CPF3012:  File DCSCIU in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/IC198XPF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RIC1865045)

CPF3012:  File IC198XPF in library *LIBL not found.


Current library: QGPL
Library list: QTEMP QGPL ORDLIB WRKSPLFRPG ADTSLAB RUPERT
Commands:
		DSPFFD FILE(*LIBL/IC198XDWW) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RIC1865321)

CPF3012:  File IC198XDWW in library *LIBL not found.



SQL is enabled...     tried disabling Source Dates ...unfortunately didn't solve the problem for me...

**Comment by ffleer** [comment]
If I  disable "Source Dates" I can save my source code without any errors. The output tab is then empty.

**Comment by AndyGildroy** [comment]
thanks for the suggestion ffleer ...still not working for me with any combination of SQL and source dates enabled or disabled  ....am getting the message:  Failed to save 'nw040xr.rpgle': Unable to write file 'member:/WOWILLIAM/qrpglesrc/nw040xr.rpgle' (CPDA08C: Database file CCSID is 65535.
CPFA095: Stream file not copied.) though   ...I think this is slightly more information than before....

**Comment by ffleer** [comment]
> thanks for the suggestion ffleer ...still not working for me with any combination of SQL and source dates enabled or disabled ....am getting the message: Failed to save 'nw040xr.rpgle': Unable to write file 'member:/WOWILLIAM/qrpglesrc/nw040xr.rpgle' (CPDA08C: Database file CCSID is 65535. CPFA095: Stream file not copied.) though ...I think this is slightly more information than before....

And you did not forget to save your settings and restart VS ?  Sorry had to ask :-) 
I have both sql and source date unticked and I can now save sources > 100 KB.

**Comment by AndyGildroy** [comment]
_**And you did not forget to save your settings and restart VS ? Sorry had to ask :-)
I have both sql and source date unticked and I can now save sources > 100 KB.**_

Yep have saved (both unticked) and restarted VS but still getting the same message :(

**Comment by worksofliam** [comment]
@AndyGildroy your issue is different from some of the other users here.

> Database file CCSID is 65535.
CPFA095

This means your source file is 65535 (that's not good, btw)

You can override this by setting the default source file CCSID in the settings.

**Comment by AndyGildroy** [comment]
Would the recommended CCSID be 00285 for UK source physical members?

**Comment by ffleer** [comment]
yes.

Mvg, Frank Fleer.

On 19 Jun 2023, at 17:43, AndyGildroy ***@***.***> wrote:

﻿

Would the recommended CCSID be 00285 for UK source physical members?

**Comment by AndyGildroy** [comment]
OK big thanks again Frank (and Liam too) ...I'd better look into that

**Comment by chrjorgensen** [comment]
@ffleer Are you on the latest release 2.0.0 of Code for IBM i? It has a [change](https://github.com/halcyon-tech/vscode-ibmi/pull/1403) to the save operation when using source dates (to avoid clearing the member when error occurs).

Scanning your output log, I think you may have some CCSID issues (because of the error `CPF427D: SUBSTITUTION CHARACTERS MAY BE USED IN DATA CONVERSION.`). Have you checked your CCSID settings for your user and PASE and the source file?

We have also seen issues with members having SEU colour codes - do you have any of these?

**Comment by ffleer** [comment]
Hi Christian,

Thanks for your feedback, I’m on:

Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

After update I’m on:

Version: 1.80.0 (user setup)
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T15:06:02.407Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

So this is not version 2.0.0. I will do some testing and let you know the outcome.

**Comment by ffleer** [comment]
Ah yes version 2.0.0 is what I have for Code for IBM i. 
Well if I switch on source dates again I get the "Failed to save xxxx.rplge: Unable to write file" again.

**Comment by ffleer** [comment]
There is one change - The source member is no longer cleared. So that is good.

**Comment by worksofliam** [comment]
> So just to be clear we can use VS Code but we can't have the source line dates. That makes VS Code unusable for our production environment.

@ffleer with the new 2.0.0 update, please share the contents of your Code for IBM i output channel after the member doesn't save.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by ffleer** [comment]
This is in OUTPUT

Current library: W_FF00150
Library list: QTEMP OPSSLIBW OPSSLIBQ OPSSLIBP OPSOLIBW OPSOLIBQ JD_SECFQ7 W_FF00150 JD_CBNFQ7 CDPL150FQ7 JDPLIBOP7 JD_LSCFQ7 JDPSHARE JD_COMFX7 QGPL
Commands:
		CHKOBJ OBJ(W_FF00150/QRPGLESRC) OBJTYPE(*FILE) AUT(*UPD)

CPC2206:  OWNERSHIP OF OBJECT QZSHSYSTEM IN QTEMP TYPE *USRSPC CHANGED.


Current library: W_FF00150
Library list: QTEMP OPSSLIBW OPSSLIBQ OPSSLIBP OPSOLIBW OPSOLIBQ JD_SECFQ7 W_FF00150 JD_CBNFQ7 CDPL150FQ7 JDPLIBOP7 JD_LSCFQ7 JDPSHARE JD_COMFX7 QGPL
Commands:
		DSPFFD FILE(QTEMP/FHEIM) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/RQTE508610)

CPF3012:  FILE FHEIM IN LIBRARY QTEMP NOT FOUND.
CPC2206:  OWNERSHIP OF OBJECT QZSHSYSTEM IN QTEMP TYPE *USRSPC CHANGED.

**Comment by ffleer** [comment]
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/136909783/8f4bf338-5c3a-4d1c-b141-ecad1ab65f7b)

**Comment by chrjorgensen** [comment]
@ffleer What's the character in the source member in the comment lines `//(?)------`?
It's a character, that could not be converted to UTF-8 (required for VS Code).

If it's a SEU colour code (hex values x'21' etc), you have two choices:

1. Remove the code
2. Activate `Show Seu Colors` in Code for IBM i settings:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/13275072/c6dffbde-7d33-4f12-838f-b089aa6877f2)

I would strongly advice option 1 - to remove these characters! They are only useful in SEU and SEU is not useful!! 😜 
After this, try your open again...

**Comment by chrjorgensen** [comment]
Please clear the Code for IBM i output, try your save operation and provide the OUTPUT here after getting the error.

**Comment by ffleer** [comment]
When I removed **ALL** X'22' from the source code the save works !!!

**Comment by chrjorgensen** [comment]
Great to hear! Hope you find Code for IBM i more useful and more compatible to all your environments.

**Comment by chrjorgensen** [comment]
Go ahead and use Code for IBM i to full extent - and then show your colleagues just how much better experience it is then clinging on to SEU:

No color codes are necessary, VS Code will show the source in color by itself. 😍

**Comment by ffleer** [comment]
It would be very nice if Code for IBM i replaces X'22' (and other color attributes) with X'40' (space). This would make life much easier. This could be a config setting.

**Comment by chrjorgensen** [comment]
You can replace the colour codes for spaces using SQL on the server.

Here is a SQL procedure, that will do what you want:

```SQL
create or replace procedure QGPL.Remove_SEU_colour_codes( 
  Lib varchar( 10 )
, Fil varchar( 10 )
, Mbr varchar( 10 )
)

begin
  execute immediate 'create or replace alias QTEMP.MEMBER for ' concat Lib concat '/' concat Fil concat '(' concat Mbr concat ')';

  update QTEMP.MEMBER
     set SRCDTA = translate( SRCDTA, ' ', x'2021222324252628292C2D3031323334353638393A3B3C3D3E' );

  drop alias QTEMP.MEMBER;

  call SYSTOOLS.LPRINTF( 'Source member ' concat Mbr concat ' in ' concat Lib concat '/' concat Fil concat ' has been cleaned for SEU colour codes.' );
end  
```

You call it like this:

```SQL
call QGPL.Remove_SEU_colour_codes( LIB => '<library>', FIL => '<sourcefile>', MBR => '<member>' )
```

This can be expanded with a SQL procedure to loop through all members in a source file and call `Remove_SEU_colour_codes` for each member - or whatever you can think of...

**Comment by ffleer** [comment]
Yes that is exactly what I do but it is a bit of a pain because we can not change production source code. Only when the program is checked out to development we can change it. Each time we then need to run a SQL command (or call a procedure). Thanks for your help anyway.

**Comment by chrjorgensen** [comment]
I don't think Code for IBM i should change the source "behind the scenes"... maybe you could make the source cleanup part of your source checkout to development, so you don't have to run it manually...

**Comment by worksofliam** [comment]
What is the status here? 

cc @chrjorgensen: I reckon we should close this.

**Comment by AndyGildroy** [comment]
OK with me all my questions well answered :)
