### ISSUE TITLE
Deploying from local PC to IFS creates objects with qsecofr owner

### ISSUE THREAD

**Issue by rogersonra** [halcyon-tech/vscode-ibmi#1405]
👉🏻 Working with @edmundreinhardt and @worksofliam  we git cloned ibmi-bob to my local pc.  We then deployed ALL to the ifs.  
rrogerson@KT24002C:~$ cd ibmi-bob
rrogerson@KT24002C:~/ibmi-bob$ ls -l
total 136
-rw-rw-rw-  1 qsecofr 0   140 Jun 30 13:41 AUTHORS.md
-rw-rw-rw-  1 qsecofr 0  6949 Jun 30 13:41 CHANGELOG
-rw-rw-rw-  1 qsecofr 0 11560 Jun 30 13:41 LICENSE
-rw-rw-rw-  1 qsecofr 0  2631 Jun 30 13:41 README.md
drwxr-sr-x  2 qsecofr 0  8192 Jun 30 16:11 bin
drwxr-sr-x 12 qsecofr 0 24576 Jun 30 16:11 docs
-rw-rw-rw-  1 qsecofr 0  5531 Jun 30 13:41 noxfile.py
-rw-rw-rw-  1 qsecofr 0    28 Jun 30 13:41 pytest.ini
-rw-rw-rw-  1 qsecofr 0   552 Jun 30 13:41 setup.cfg
drwxr-sr-x  5 qsecofr 0  8192 Jun 30 16:11 src
drwxr-sr-x  5 qsecofr 0  8192 Jun 30 16:11 tests
drwxr-sr-x  3 qsecofr 0  8192 Jun 30 16:11 tools

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|1.9.4|
|Visual Studio Code version|1.79.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Black Formatter (black-formatter): 2023.2.0
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.2.11
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.11.1
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.5
JSON Language Features (json-language-features): 1.0.0
Jupyter (jupyter): 2023.5.1101742258
Jupyter Notebook Renderers (jupyter-renderers): 1.0.15
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Pylance (vscode-pylance): 2023.6.40
Python (python): 2023.10.1
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
isort (isort): 2022.8.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|2|
|CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|
|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|
|chsh|iconv|GETNEWLIBL.PGM||
|git|setccsid|||
|grep|tar|||
|ls||||
|md5sum||||
|sort||||
|stat||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=DTCOBJ
CURLIB=DTCOBJ
HOME=/home/RROGERSON/ibmi-bob
LC_ALL=EN_US.UTF-8
LIBLS=RROGERSON QGPL DTCDTA DTCOBJ QTEMP DTCSRC
LOGIN=rrogerson
LOGNAME=rrogerson
MAIL=/var/spool/mail/rrogerson
OBJECT_MODE=64
OLDPWD=/home/rrogerson
PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PS1=\u@\h:\w\$
PWD=/home/RROGERSON/ibmi-bob
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=10.200.3.156 53935 22
SSH_CONNECTION=10.200.3.156 53935 172.20.70.130 22
TERM=xterm
TZ=<EST>5<EDT>,M3.2.0,M11.1.0
USER=rrogerson
USERNAME=rrogerson
_=/QOpenSys/usr/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/RROGERSON/ibmi-bob"
  },
  {
    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh",
    "code": 2,
    "stderr": "ls: 0653-341 The file /QIBM/ProdData/IBMiDebugService/bin/startDebugService.sh does not exist.",
    "cwd": "/home/RROGERSON/ibmi-bob"
  }
]
```
</details>

**Comment by sebjulliand** [comment]
Good catch! A PR has been opened to address this problem: https://github.com/halcyon-tech/vscode-ibmi/pull/1408
