### ISSUE TITLE
Getting Not connected to 192.168.4.4! connect ECONNREFUSED  message

### ISSUE THREAD

**Issue by AndyGildroy** [halcyon-tech/vscode-ibmi#1407]
👉🏻 Hi I'm getting a 'Not connected to 192.168.4.4! connect ECONNREFUSED  IPaddress:port'  message whenever I try to connect to the IBMi  ...It has always worked previously but I'm just coming back to VS Code as I had been diverted to project work for a few weeks.... 
<hr />

|Context|Version|
|-|-|
|Code for IBM i version|1.9.4|
|Visual Studio Code version|1.79.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 9.7.1
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.2.11
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.11.1
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.5
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL (remote-wsl): 0.79.5
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

**_Not connected_** 🔌

**Comment by chrjorgensen** [comment]
@AndyGildroy This is not a Code for IBM i issue... please check your user and password on the server, VS Code can't connect.

**Comment by AndyGildroy** [comment]
Thanks for the reply ...user and password are fine VS Code still not connecting though -  am using them on ACS with no problem and the same credentials work with VS Code for IBMi before...   ...is there any way of getting VS Code for IBMi to say/show what it doesn't like about the connection?

________________________________

**Comment by sebjulliand** [comment]
Hi!
At the point in connection process, that's the ssh connection process who
throws this error. You most likely have an SSH problem.
Is the ssh server up and running on your IBM i? If yes, can you connect to
it using a tool like putty or the ssh terminal from ACS?


Le lun. 3 juil. 2023, 12:51, AndyGildroy ***@***.***> a
écrit :

**Comment by AndyGildroy** [comment]
sebjulliand  ...thanks I'll look into that ...I think it's likely that the SSH server has been killed by a recent IPL

**Comment by sebjulliand** [comment]
That sounds like the most sensible cause for this kind of issue 😄

**Comment by AndyGildroy** [comment]
That worked by the way - thanks loads  ...sometimes the simple answers are the easiest to overlook

**Comment by sebjulliand** [comment]
Anytime! Glad it works now!
