### ISSUE TITLE
Unable to open source member

### ISSUE THREAD

**Issue by rogerrettig** [halcyon-tech/vscode-ibmi#1419]
Type: <b>Bug</b>

This error is displayed when opening any IBM i  source member :

The editor could not be opened due to an unexpected error: Token 1 was not valid. Valid tokens: FOR USE SKIP WAIT WITH FETCH ORDER UNION EXCEPT OPTIMIZE. (42601)

Extension version: 1.9.4
VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19042
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (6.84GB free)|
|Process Argv|--crash-reporter-id 02d39954-1b7d-467d-854a-bc49cd3c8318|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30766889
pythongtdpath:30769146
bgfeh915:30780428
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnoceb:30776495
h7j2d465:30772216
cmakesidepanelv2:30779593

```

</details>

**Comment by rogerrettig** [comment]
V1.94

This is the only lines in the IBM i output:
Current library: QGPL
Library list: QTEMP STSDAT10 CISTSOBJ10 AASTSOBJ10 CIOBJ10 AAMOD10 AAOBJ10 CISTSSRC10 AASTSSRC10 CIPRDSRC10 AAMODSRC10 AASRC10 SEQUEL SV5TEST ILEPGMLIB SQLVIEWS RMRTEST PRDDAT10 OTTOSYS OTTOSRC IFSTOOL ABSTRACT DBU10 QGPL AVATAX
Commands:
		CHKOBJ OBJ(EPICOR/QRPGLESRC) OBJTYPE(*FILE) AUT(*UPD)

**Comment by worksofliam** [comment]
@rogerrettig Sorry, what version of IBM i are you using - not what version of the extension. Also, that output comes from the 'IBM i Output' channel, not the 'Code for IBM i' output channel.

**Comment by worksofliam** [comment]
I have a theory that it's because `SELECT LENGTH(srcdta) as LENGTH FROM ILEDITOR.EPICOR_QRPGLESRC_VENDMASTR limit 1` doesn't work on 7.1. We also don't support 7.1. Sorry about that.

**Comment by rogerrettig** [comment]
Ok, thanks for looking into this.
