### ISSUE TITLE
Special characters conversion

### ISSUE THREAD

**Issue by alfax218** [halcyon-tech/vscode-ibmi#1432]
In the last couple weeks i found out that some special characters (like §, ò, à, è, etc...) are not shown correctly.

When i open a source member i see this:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/107923967/6a0d2c06-4ace-4a2e-acdc-a1f72282a29c)
instead of §FTAZ0.

Also, object filters with special characters in the member name input will show no results, probably due to incorrect conversion.

Thank you!

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.0.0|
|Visual Studio Code version|1.80.0|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Account Microsoft (microsoft-authentication): 0.0.1
Autenticazione GitHub (github-authentication): 0.0.2
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Collegamento automatico per debug di Node (debug-auto-launch): 1.0.0
Creazione estensione (extension-editing): 1.0.0
Db2 for IBM i (vscode-db2i): 0.2.11
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.11.1
Esegui merge del conflitto (merge-conflict): 1.0.0
Excel Viewer (gc-excelviewer): 4.2.57
Funzionalità dei linguaggi TypeScript e JavaScript (typescript-language-features): 1.0.0
Funzionalità del linguaggio JSON (json-language-features): 1.0.0
GIT (git): 1.0.0
Git Base (git-base): 1.0.0
Git Graph (git-graph): 1.30.0
GitHub (github): 0.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.5
Material Icon Theme (material-icon-theme): 4.28.0
Monokai Pro (theme-monokai-pro-vscode): 1.2.1
Overtype (overtype): 0.5.0
Path Intellisense (path-intellisense): 2.8.4
Prettier - Code formatter (prettier-vscode): 9.19.0
RPGLE (vscode-rpgle): 0.19.3
Supporto di npm per VS Code (npm): 1.0.1
TODO Highlight (vscode-todo-highlight): 1.0.5
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|2|
|CCSID|1144|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|git|setccsid||||
|ls|tar||||
|md5sum|||||
|sort|||||
|stat|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=QGPL
CURLIB=QGPL
PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
TZ=<CET>-1<CEST>,M3.5.0,M10.5.0
_=/QOpenSys/usr/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "��$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: La libreria ILEDITOR esiste gi�."
  },
  {
    "command": "system \"DLTOBJ OBJ(ILEDITOR/O_*) OBJTYPE(*FILE)\"",
    "code": 255,
    "stderr": "CPF2125: Non � stato cancellato alcun oggetto."
  }
]
```
</details>

**Comment by worksofliam** [comment]
Have you checked out our CCSID docs? https://halcyon-tech.github.io/docs/#/pages/tips/ccsid

**Comment by alfax218** [comment]
I've checked the CCSID section. The system CCSID is 1144 and the profile CCSID is *SYSVAL.

Maybe it has something to do with the upgrade from 7.4 to 7.5.

One of our partitions has 7.4 and the special characters are shown correctly, unlike the one with the version 7.5.

The QCCSID and the user profiles are the same in the partitions.

**Comment by vsafanda** [comment]
Hi, similar issue for me.

If I open source member containing Czech national characters (ě, š, č, ř, ...), these characters are wrongly displayed (as shown above). Saving such member leads to an error "Unable to write file ...", and member content is cleared.

If I overwrite these characters back to original Czech national characters, save operation will succeed and member content is OK. But only until next member open. 

Environment:
System QCCSID 65535, profile CCSID 870 (Czech), environment variables PASE_LANG = 'CS_CZ', QIBM_PASE_CCSID = 1208 on *SYS level. Source file CCSID = 870, CCSID in extension settings set to *FILE.

Thank you.

**Comment by vsafanda** [comment]
Yes, 
I have set all environment variables/ccsid values for profile/job/etc. that I'm able to change - according to documentation. 
That includes env vars PASE_LANG, QIBM_PASE_CCSID and my user profile CCSID.
The only value that I cannot change, is QCCSID system value.

Maybe I missed something, as I am not an ibm i admin ...

**Comment by alfax218** [comment]
@vsafanda do you have 7.5 on your IBM i?

**Comment by vsafanda** [comment]
@alfax218 No, currently 7.4

**Comment by L-Escri** [comment]
Hi @worksofliam,

same issue here, i have checked the CCSID and the docs, nothing change. I'm in the 7.5 on IBM i. 
The problem is on reading variant characters, not writing. 

The job running has CCSID 1208 in the environment variable named QIBM_PASE_CCSID.

**Comment by worksofliam** [comment]
@alfax218 looks like your issue could be regarding no results sets with SQL. See here: https://halcyon-tech.github.io/docs/#/pages/tips/setup?id=no-results-from-sql-execution

**Comment by alfax218** [comment]
@worksofliam that issue is because of variant character bad conversion.

I've tried to run a PASE terminal on VS and execute the following command.
```
LC_CTYPE=EN_US.UTF-8 system -i "call QSYS/QZDFMDB2 PARM('SELECT b.avgrowsize as MBMXRL, a.iasp_number as MBASP, cast(a.system_table_name as char(10) for bit data) AS MBFILE, cast(b.system_table_member as char(10) for bit data) as MBNAME, coalesce(cast(b.source_type as varchar(10) for bit data), '''') as MBSEU2, coalesce(b.partition_text, '''') as MBMTXT, b.NUMBER_ROWS as MBNRCD, extract(epoch from (b.CREATE_TIMESTAMP))*1000 as CREATED, extract(epoch from (b.LAST_SOURCE_UPDATE_TIMESTAMP))*1000 as CHANGED FROM qsys2.systables AS a JOIN qsys2.syspartitionstat AS b ON b.table_schema = a.table_schema AND b.table_name = a.table_name WHERE cast(a.system_table_schema as char(10) for bit data) = ''MYLIB'' AND cast(a.system_table_name as char(10) for bit data) = ''QSRC'' AND rtrim(cast(b.system_table_member as char(10) for bit data)) like ''§TEST%''')"
```
The first time it fails (no results, just like when I try to expand the members filter), the second time it returns all the expected members and variant characters are shown correctly.

**Comment by alfax218** [comment]
We've submitted a case to IBM. Apparently it's a bug of OpenSSH that's been updated in IBM i 7.5 (and cannot be downgraded), we recreated the same issue on Putty, XShell and the Windows prompt.
Last weekend we've upgraded another partition to 7.5, it was fine until the update, now all variant characters are broken.

**Comment by chrjorgensen** [comment]
@alfax218 Interesting! Do you know which PTF causes this OpenSSH problem?

Keep us posted when a fix is found. Thanks!

**Comment by alfax218** [comment]
@chrjorgensen On 7.4 we had OpenSSL 1.1.1p, now we have OpenSSL 1.1.1t. Honestly I don't know if there's a PTF that updates OpenSSH or if it's only on 7.5.

**Comment by alfax218** [comment]
@worksofliam @chrjorgensen 
IBM has released PTF SI84164, we've installed it and it fixed the problem
