### ISSUE TITLE
TN5250 terminal is not opening

### ISSUE THREAD

**Issue by ravisankar-PIO** [halcyon-tech/vscode-ibmi#1434]
**Issue: TN5250 terminal is not opening**
I have installed TN5250 via yum on my machine and yet I am not able to spawn a TN5250 terminal inside VS Code. 

**Update:** In the "Enabled Features" table below, I don't see tn5250 under /QOpenSys/pkgs/bin. Do I need to enable it inside VS Code? However, I am able to "which" them in the PASE editor.

below is the output of ```which``` command from PASE.

```
-bash-5.1$ which yum curl tn5250
/QOpenSys/pkgs/bin/yum
/QOpenSys/pkgs/bin/curl
/QOpenSys/pkgs/bin/tn5250
-bash-5.1$ 
```

This meansTN5250 is already installed in my IBMi machine and the $PATH variable is also set correctly. 

I am also able to spawn the TN5250 manually from within PASE - which is kind of ugly looking and the F keys aren't working. Otherwise, I would be happily invoking a new session inside of PASE. 

FYI, I tried the steps exactly as per
https://halcyon-tech.github.io/docs/#/pages/tips/terminals and
https://www.seidengroup.com/php-documentation/how-to-set-up-the-ibm-i-open-source-environment/

**To Reproduce**
1. Once connected to the IBMi system, click on the "Terminals" at the bottom of the VSCODE. 
2. Select the terminal type 5250.
3. See below error
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/139198015/8118fda1-532d-4f83-a281-dd7ab05bc32b)

**Expected behavior**
TN5250 terminal should spawn.
<hr />

# Environment details

|Context|Version|
|-|-|
|Code for IBM i version|2.0.0|
|Visual Studio Code version|1.80.0|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 9.7.10
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.2.11
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.11.1
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.5
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.19.3
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|8|
|CCSID|65535|
|SQL|Disabled
|Source dates|Disabled

#### (I don't see the TN5250 enabled in the /QOpenSys/pkgs/bin)

|/usr/bin|/QOpenSys/pkgs/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|attr|bash|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|iconv|chsh|GETNEWLIBL.PGM|||
|setccsid|ls||||
|tar|md5sum||||
||sort||||
||stat||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=RAVISANKAR
CURLIB=RAVISANKAR
HOME=/home/ravisankar
LIBLS=QTEMP QGPL RAVISANKAR
LOGIN=ravisankar
LOGNAME=ravisankar
MAIL=/var/spool/mail/ravisankar
OLDPWD=/home/ravisankar
PASE_USRGRP_LIMITED=N
PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/ravisankar
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=198.18.0.247 64228 22
SSH_CONNECTION=198.18.0.247 64228 129.40.98.153 22
TZ=<EST>5<EDT>,M3.2.0,M11.1.0
USER=ravisankar
USERNAME=ravisankar
_=/QOpenSys/usr/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/ravisankar"
  },
  {
    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx",
    "code": 2,
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx not found",
    "cwd": "/home/ravisankar"
  }
]
```
</details>

**Comment by ravisankar-PIO** [comment]
**Hello... Gentle reminder... I know this isn't a support thread, but I shall ask nowhere else!** 

I tried everything as per the document. One thing I did notice is that my CCSID is set to 65535 and I got a notification for the same. Do I need to change it to 37 in order to TN5250 to work? I don't have authority to change my default user profile entries. 

Any help is appreciated!

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after connecting to your system.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by ravisankar-PIO** [comment]
Hi Liam,
    Sorry, it took me a while to reply. I actually lost access to the IBMi server (v7r4) using which I was originally trying to open TN5250 inside VSC. However, I replicated the same steps on a new server (v7r3) and here's the output of the console. Currently I have access only to this new (v7r3) server. Below is the output of "Code for IBM i" channel after connecting to my IBMi box. 

```
/home/CECUSER: echo "This should be the only text!"
{
    "code": 0,
    "signal": null,
    "stdout": "This should be the only text!",
    "stderr": ""
}

.: pwd
{
    "code": 0,
    "signal": null,
    "stdout": "/home/CECUSER",
    "stderr": ""
}

/home/CECUSER: pwd
{
    "code": 0,
    "signal": null,
    "stdout": "/home/CECUSER",
    "stderr": ""
}

/home/CECUSER: /QOpenSys/usr/bin/qsh
liblist
{
    "code": 0,
    "signal": null,
    "stdout": "QSYS        SYS\nQSYS2       SYS\nQHLPSYS     SYS\nQUSRSYS     SYS\nQSHELL      PRD\nQGPL        USR\nQTEMP       USR",
    "stderr": ""
}

/home/CECUSER: system "CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF2111: Library ILEDITOR already exists."
}

/home/CECUSER: [ -d "/tmp" ]
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/CECUSER: echo $SHELL
{
    "code": 0,
    "signal": null,
    "stdout": "/QOpenSys/pkgs/bin/bash",
    "stderr": ""
}

/home/CECUSER: ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx
/home/CECUSER: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select OS_VERSION || '.' || OS_RELEASE as VERSION from sysibmadm.env_sys_info
/home/CECUSER: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select max(ptf_group_level) as HIGHEST_DB2_PTF_GROUP_LEVEL from qsys2.group_ptf_info where PTF_GROUP_DESCRIPTION like 'DB2 FOR IBM I%' and ptf_group_status = 'INSTALLED';
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx not found"
}

/home/CECUSER: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select job_name, authorization_name from qsys2.netstat_job_info j where local_port = 8005 group by job_name, authorization_name
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\nVERSION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \n---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n7.3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \n\n  1 RECORD(S) SELECTED.",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n\nHIGHEST_DB2_PTF_GROUP_LEVEL \n----------------------------\n                          32\n\n  1 RECORD(S) SELECTED.\n\nDB2>",
    "stderr": ""
}

{
    "code": 1,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\nJOB_NAME                     AUTHORIZATION_NAME \n---------------------------- -------------------\n\n  0 RECORD(S) SELECTED.",
    "stderr": ""
}

/: system "RUNSQLSTM SRCSTMF('/tmp/vscodetemp-O_OawWSnUh') COMMIT(*NONE) NAMING(*SQL)"
{
    "code": 0,
    "signal": null,
    "stdout": "5770SS1 V7R3M0 160422               Run SQL Statements             VSCODETEMP                         07/19/23 05:38:59   PAGE   1\nSource stream file......../tmp/vscodetemp-O_OawWSnUh\nTarget release............V7R3M0\nCommit....................*NONE\nNaming....................*SQL\nGeneration level..........10\nDate format...............*JOB\nDate separator............*JOB\nTime format...............*HMS\nTime separator ...........*JOB\nRight margin..............80\nDefault collection........*NONE\nIBM SQL flagging..........*NOFLAG\nANS flagging..............*NONE\nDecimal point.............*JOB\nSort sequence.............*JOB\nLanguage ID...............*JOB\nPrinter file..............*LIBL/QSYSPRT\nSource file CCSID.........1208\nJob CCSID.................37\nStatement processing......*RUN\nAllow copy of data........*OPTIMIZE\nAllow blocking............*ALLREAD\nSQL rules.................*DB2\nDecimal result options:\n  Maximum precision.......31\n  Maximum scale...........31\n  Minimum divide scale....0\nConcurrent access\n  resolution..............*DFT\nSystem time sensitive.....*YES\nSource member changed on 07/19/23  05:38:57\n5770SS1 V7R3M0 160422               Run SQL Statements             VSCODETEMP                         07/19/23 05:38:59   PAGE     2\nRecord  *...+... 1 ...+... 2 ...+... 3 ...+... 4 ...+... 5 ...+... 6 ...+... 7 ...+... 8   SEQNBR  Last change\n      1 CREATE OR REPLACE PROCEDURE ILEDITOR.GETNEWLIBL(IN COMMAND VARCHAR(2000))\n      2 DYNAMIC RESULT SETS 1\n      3 BEGIN\n      4   DECLARE clibl CURSOR FOR\n      5     SELECT ORDINAL_POSITION, TYPE as PORTION, SYSTEM_SCHEMA_NAME\n      6     FROM QSYS2.LIBRARY_LIST_INFO;\n      7   CALL QSYS2.QCMDEXC(COMMAND);\n      8   OPEN clibl;\n      9 END;\n                                 * * * * *  E N D  O F  S O U R C E  * * * * *\n5770SS1 V7R3M0 160422               Run SQL Statements             VSCODETEMP                         07/19/23 05:38:59   PAGE     3\nRecord  *...+... 1 ...+... 2 ...+... 3 ...+... 4 ...+... 5 ...+... 6 ...+... 7 ...+... 8   SEQNBR  Last change\nMSG ID  SEV  RECORD  TEXT\nSQL7989   0       1  Position 1 Procedure GETNEWLIBL was created in ILEDITOR.\n                    Message Summary\n  Total     Info   Warning      Error   Severe  Terminal\n      1        1         0          0        0         0\n00 level severity errors found in source\n                                * * * * *  E N D  O F  L I S T I N G  * * * * *",
    "stderr": ""
}


```

**Comment by worksofliam** [comment]
@ravisankar-PIO before connecting to your server, use the right click option on the server and ‘reload and connect’.

**Comment by ravisankar-PIO** [comment]
Phew, that solved it! Thank you so much Liam. I really appreciate your good work on IBMi and Open Source. 

That being said, do we need to include this step in the documentation?

**Comment by ravisankar-PIO** [comment]
Also, do I need to fiddle with CCSID for the correct rendering of these junk characters? Below is the 5250 inside vsc.

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/139198015/fa5cd402-e7a4-4d01-b7a9-14563401124c)

This is the actual emulator from ACS.
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/139198015/b34125a1-42e6-4a68-bd30-1f79b9598499)

**Comment by alanseiden** [comment]
> That being said, do we need to include this step in the documentation?

@ravisankar-PIO Good idea. I have submitted a pull request to document the “Connect and Reload Server Settings" tip: https://github.com/codefori/docs/pull/18

**Comment by GalonMitsunari** [comment]
Hi, I installed tn5250 via ACS to be able to use it on VSCODE and it doesn't work and when I do the "which yum curl tn5250" command
it returns 
"no yum in /QOpenSys/usr/bin /usr/ccs/bin /QOpenSys/usr/bin/X11 /usr/sbin . /usr/bin
no curl in /QOpenSys/usr/bin /usr/ccs/bin /QOpenSys/usr/bin/X11 /usr/sbin . /usr/bin
no tn5250 in /QOpenSys/usr/bin /usr/ccs/bin /QOpenSys/usr/bin/X11 /usr/sbin . /usr/bin"

while the module is installed.

**Comment by chrjorgensen** [comment]
@GalonMitsunari 

> I installed tn5250 via ACS to be able to use it on VSCODE

If you have ACS installed, I would strongly recommend using the 5250 emulator in ACS instead of tn5250 - the latter has some caveats including keyboard mappings... see more in this discussion #1675 or search the issues section for `tn5250`...

**Comment by sboisier** [comment]
Hi all,

Hope I'm on the right place for my problem.

Using TN5250 in Visual Studio to connect to my Host IBM i.

I'm able to connect and start a TN5250 session in VS but got some troubles for setting right CCSID session.

My iSeries CCSID is 65535, my iSeries language is 1147 (French Euro).

When I'm starting TN5250 got this type of screen 

![Capture d’écran 2024-06-26 100106](https://github.com/codefori/vscode-ibmi/assets/32508542/99764f72-43c3-4a83-a3e8-32763744268a)

Saw tyhat I can put some options but don't know where to put these. Guess there's an ini file somewhere I can modify

Thanks for your feedbacks

Regards

Sylvain

**Comment by chrjorgensen** [comment]
@sboisier Did you set the 5250 encoding to '297' (French) in the `Terminal` tab in the `Settings`?

![image](https://github.com/codefori/vscode-ibmi/assets/13275072/c506a156-0510-4013-8a22-e1c0a6164cff)

You can see all options for `tn5250` by opening a PASE terminal and type `man tn5250`.
Then you can add any additional options to the connection string in the `Terminal` settings.

**Comment by fredericpetit** [comment]
Hello, I have the same problem with accents, do you have solve it ? Thanks a lot

**Comment by sboisier** [comment]
Hi,

Not yet as nobody's give me advices
________________________________

**Comment by sebjulliand** [comment]
As far as I can tell, running tn5250 outside of VS Code, from an SSH terminal like putty gives the same result (characters are scrambled with CCSID 297).
