### ISSUE TITLE
Ibm-i Notebook not working

### ISSUE THREAD

**Issue by HenryMiller** [halcyon-tech/vscode-ibmi#1438]
Hello,
It looks like IBM I Notebook is not working anymore on my PC.
I always get "command 'code-for-ibmi.runQuery' not found" even if all extensions look properly installed, including IBM I Notebooks, DB2 for I .

<img width="320" alt="image" src="https://github.com/halcyon-tech/vscode-ibmi/assets/1829995/7ab2dd15-1f71-4e70-90c4-2798ff18cfa8">

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.0.0|
|Visual Studio Code version|1.80.1|
|Operating System|darwin_arm64|

<details>
<summary>Active extensions</summary>

```
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.2.11
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitLens — Git supercharged (gitlens): 14.1.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.5
JSON Language Features (json-language-features): 1.0.0
Jira and Bitbucket (Atlassian Labs) (atlascode): 3.0.3
Live Server (LiveServer): 5.7.9
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
RPGLE (vscode-rpgle): 0.19.3
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
YAML (vscode-yaml): 1.13.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|4|
|CCSID|1144|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|
|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|
|chsh|iconv|GETNEWLIBL.PGM||
|git|setccsid|||
|grep||||
|ls||||
|md5sum||||
|sort||||
|stat||||
|tar||||
|tn5250||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=XXX_OBP
CURLIB=XXXX_OBP
HOME=/xxxxxx/m11/
LIBLS=XXXX_OBP XXX_SRC XXX_OBJ QGPL QTEMP XXXX_DAT
LOGIN=hm
LOGNAME=hm
MAIL=/var/spool/mail/hm
OLDPWD=/home/hm
PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/ospreys/m11
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=192.168.1.78 53113 22
SSH_CONNECTION=192.168.1.78 53113 192.168.0.100 22
TZ=<UTC>0
USER=xx
USERNAME=xx
_=/QOpenSys/usr/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "£§$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: La libreria ILEDITOR esiste già.",
    "cwd": "/ospreys/m11/"
  }
]
```
</details>

**Comment by worksofliam** [comment]
@HenryMiller new version of Notebooks will be released soon!

We had an API change and Notebooks was affected.

**Comment by HenryMiller** [comment]
Thank you!

**Comment by worksofliam** [comment]
0.0.6 is being released as I write this which will solve the issue. Thanks!
