### ISSUE TITLE
Support for uniqe object names through user-supplied variable values

### ISSUE THREAD

**Issue by v-p-b** [halcyon-tech/vscode-ibmi#1440]
**Is your feature request related to a problem? Please describe.**

I'm creating save files from multiple versions of objects. I can use variables like`&NAME` when naming the save files, however this will result in a conflict when saving a different version of the same object (that has the same name, library, etc.). Unfortunately CRTSAVF doesn't have REPLACE parameter...

**Describe the solution you'd like**

It'd be convenient to have a variable that would prompt the user for its value, so I could use it like:

```
CRTSAVF (&OPENLIB/&USERVAL)
SAVOBJ SAVF(&OPENLIB/&USERVAL) ...
```

When this action runs the user would be prompted for a value by VSCode, and the supplied value would be inserten in place of `&USERVAL`.

**Describe alternatives you've considered**

I was thinking about having a variable with a value increasing with every action call, but I think this would quickly result in too long names.

A workaround could be to have a prompted CL command that stores some value for later calls, but I'm not that familiar with CL programming TBH.

**Comment by worksofliam** [comment]
Have you checked out our prompting capabilities for actions?

https://halcyon-tech.github.io/docs/#/pages/developing/actions/execution?id=prompted

**Comment by v-p-b** [comment]
This seems just perfect, thank you!

**Comment by v-p-b** [comment]
One more question though: is there a way to reference  a previously prompted value so I don't have to provide the same value twice?

Thanks!
