### ISSUE TITLE
Actions and Terminal status bar buttons are gone

### ISSUE THREAD

**Issue by p-behr** [halcyon-tech/vscode-ibmi#1447]
The Terminal and Actions status bar buttons are gone.
Same issue for 2.0.1 and 2.0.2.

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/17951550/094d6449-8937-4763-b431-0c50f7b1aa15)

They're there in V2.0.0

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/17951550/51f14faa-3ff3-4781-8345-226a3c63d8a1)

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.0.1|
|Visual Studio Code version|1.80.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.2.11
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.12.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
PHP Intelephense (vscode-intelephense-client): 1.9.5
PHP Language Features (php-language-features): 1.0.0
Path Intellisense (path-intellisense): 2.8.4
TODO Highlight (vscode-todo-highlight): 1.0.5
Toggle Excluded Files (toggle-excluded-files): 2.0.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL (remote-wsl): 0.80.2
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|7|
|CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|ILEDITOR.GETNEWLIBL|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv||||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=PBEHR
CURLIB=PBEHR
HOME=/home/PATRICK/builds/telesure
LIBLS=YAJL72 QGPL PATRICK QTEMP PBEHR
LOGIN=patrick
LOGNAME=patrick
MAIL=/var/spool/mail/patrick
OLDPWD=/home/PATRICK
PASE_USRGRP_LIMITED=N
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/PATRICK/builds/telesure
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=76.105.160.122 63828 8222
SSH_CONNECTION=76.105.160.122 63828 172.20.30.10 8222
TZ=<EST>5<EDT>,M3.2.0,M11.1.0
USER=patrick
USERNAME=patrick
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/PATRICK/builds/telesure"
  }
]
```
</details>

**Comment by Wright4i** [comment]
@p-behr the status bar clutter was tidied up in #1441. You should be able to find those under the settings bar item.

**Comment by p-behr** [comment]
My bad  LOL  Thanks for pointing that out!!
Closing the issue
