### ISSUE TITLE
Prompt for CL programs

### ISSUE THREAD

**Issue by AMetnik** [halcyon-tech/vscode-ibmi#1448]
Hello
As a new ibmi programmer, I really like the VScode environment to do my stuff in.
But I seem to make very many mistakes when doing CLLE programs, because I can't prompt for a command, and get it to format it correctly.
Am I missing a plugin or how to prompt?

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.0.0|
|Visual Studio Code version|1.80.0|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
CL (vscode-clle): 1.1.0
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.2.11
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
Git Blame (gitblame): 10.4.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitLens — Git supercharged (gitlens): 14.1.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Peacock (vscode-peacock): 4.2.2
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|8|
|CCSID|277|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|git|setccsid||||
|grep|tar||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=ANLIB
CURLIB=ANLIB
HOME=/home/ANMET
LIBLS=ICEBREAK SYSAFD UNO700CFUT SMSDB NHO NHOPRG YXDB NHODATA YXDTA24 QGPL QTEMP ANLIB
LOGIN=anmet
LOGNAME=anmet
MAIL=/var/spool/mail/anmet
OLDPWD=/home/ANMET
PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/ANMET
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=10.45.11.51 57263 22
SSH_CONNECTION=10.45.11.51 57263 10.45.18.44 22
TZ=<CET>-1<CEST>,M3.5.0,M10.5.0/03:00:00
USER=anmet
USERNAME=anmet
_=/QOpenSys/usr/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "ÆØÅ"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/ANMET"
  },
  {
    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx",
    "code": 2,
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx not found",
    "cwd": "/home/ANMET"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF5D02:  No modules found for the specified value of EAS228CL in library ANLIB.\nCPF5D05:  Service program EAS228CL not created.\nCPC2206:  Ejerskab til objekt QZSHSYSTEM i QTEMP type *USRSPC revideret.",
    "cwd": "/home/ANMET"
  }
]
```
</details>

**Comment by chrjorgensen** [comment]
CL prompting is in the works, but not ready yet.

A workaround - and the way I do it - is to prompt the command in 5250 (F4) and fill in the parameters, and finally press F14 to show the complete command string and copy-paste to VS Code.

Code for IBM i can run 5250 sessions, so no need for additional software.

**Comment by AMetnik** [comment]
Thanks for the workaround.
Looking forward to it being done 👍
