### ISSUE TITLE
Colored comments get broken

### ISSUE THREAD

**Issue by ThomasMcA** [halcyon-tech/vscode-ibmi#1452]
I searched, but can't find a workaround for my issue.

**Describe the bug**
Saving any source member breaks ALL colored comments within that source member. This is a show-stopper for my team - we cannot use VS Code for IBM i while it has this bug.

**To Reproduce**
Save any source member that has colored comments.

**Expected behavior**
Don't break anything!

**Screenshots**
Sample:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/1448396/e567dbe6-c378-4bf2-9f53-c272b06f852f)

Inside VSCode, the hex attribute that creates the colors in SEU are shown as a question mark:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/1448396/4f321043-ad41-43c2-9610-be4fa11c580d)

After saving in VSCode, the hex attribute gets replaced by an actual question mark, and the colors are lost.
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/1448396/eab44acc-293a-46da-9e8d-ab91bd20a1fd)

**Environment (please complete the following information):**
 - Extension version: 2.0.2
 - IBM i OS version: 7.3

**Comment by chrjorgensen** [comment]
@ThomasMcA Have you enabled SEU color support in the Code for IBM i settings?

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/13275072/e704f223-1ea1-4bb6-80a6-98d1b666751a)

Press `Ctrl-,` and type `code seu` in the search bar to get to this settings...

TBH, I don't think SEU color codes should be used anymore - these are hex values that only work in 5250 sessions, not in modern source editors.

**Comment by ThomasMcA** [comment]
Once I enable that setting, I can no longer save anything, even after restarting VSCode. Every save generates this error:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/1448396/349f67f8-7728-4c6a-aa81-5a3ee9c5d449)
There are no locks on the file or member.

After I disable that setting, I can save the file (even without restarting VSCode).

**Comment by ThomasMcA** [comment]
Weird, after re-enabling that setting, and another restart of VSCode, it lets me save the source members, but it still breaks the colors. I now get this:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/1448396/a011475e-32d1-4f59-b386-848da45a8686)

Which gets saved into this:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/1448396/65caa33e-4d70-40d0-b670-a6fa96be6b52)

**Comment by worksofliam** [comment]
Please use the raise an issue button from the help and support view. This will tell some of your system configuration and enable us to help determine where the issue may be on your side.

**Comment by ffleer** [comment]
If I copy/paste the following comment line from the internet into a source physical file member I can not save the member"

// Lines 33 – 41

It is the weird dash character that screws up the save. Can not be converted to a ccsid 37 equivalent?

//Lines 33 - 44

This works fine and can  be saved. Why do we have these annoying issues?

**Comment by chrjorgensen** [comment]
The internet is mostly in UTF-8, which has many more characters than ASCII and EBCDIC.

So you will often find these problems, when you copy and paste from the internet. Your dash character is not the normal dash, but a variant which is longer and does not convert into EBCDIC.

Nothing to do with Code for IBM i...

**Comment by ffleer** [comment]
Yes understood but there is no clear error message why the file can not be saved.

I think it would be very nice to have a (generic) option that can be switched ON/OFF that says:

“Do you want to convert non EBCDIC characters to a space   Y/N?”

This could include color attributes too.

Best regards,
Frank Fleer
Technical Specialist Lead, Computer Operations (Power Systems)

Mobile: +31 (0) 653218078 | Email: ***@***.******@***.***>
Parker Hannifin B.V. | Edisonstraat 1 | 7575 AT | Oldenzaal | Netherlands

From: Christian Jorgensen ***@***.***>
Sent: maandag 24 juli 2023 16:12
To: halcyon-tech/vscode-ibmi ***@***.***>
Cc: Frank Fleer ***@***.***>; Comment ***@***.***>
Subject: [EXT] Re: [halcyon-tech/vscode-ibmi] Colored comments get broken (Issue #1452)


The internet is mostly in UTF-8, which has many more characters than ASCII and EBCDIC.

So you will often find these problems, when you copy and paste from the internet. Your dash character is not the normal dash, but a variant which is longer and does not convert into EBCDIC.

Nothing to do with Code for IBM i...

**Comment by ffleer** [comment]
Yes I understand but there is no clear error message why the file can not be saved. This can be pretty frustrating.

I think it would be very nice to have a (generic) option that can be switched ON/OFF that says:

“Do you want to convert non EBCDIC characters to a space   Y/N?”

This could include color attributes too.

**Comment by chrjorgensen** [comment]
@ffleer I will strongly advice you to store your source code as IFS stream file in CCSID 1208, which is UTF-8. This way you don't convert anything, and all compilers support IFS source.

I've been doing this for years and have had zero problems.

As a bonus you will also be able to use git on your source code, if you store them in IFS!

**Comment by Wright4i** [comment]
@ThomasMcA I'd recommend reading https://halcyon-tech.github.io/docs/#/pages/tips/ccsid and making sure everything is followed. Lots of good tips there (and the rest of the manual ain't half bad either) that will ensure you have the proper setup.

Color codes do work on my system when everything is properly configured. I do not believe this is a bug with the extension. See below some unfortunately real examples from my system back when we were still coloring our source.

With `Show SEU Colors` disabled:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/93156666/a446d0f5-9f66-4b9f-bbf3-ee9d1356366f)

With `Show SEU Colors` enabled:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/93156666/9595f953-35cf-437e-bfcf-d70fe2f98383)

When displayed in SEU:
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/93156666/8e9b470e-0a53-4eef-b4db-b24cfdd93c02)

I usually run with Show SEU Colors disabled. You can see there is room for improvement on the extension's handling of multiple color codes in a single line, but I think the support we've got is plenty and I wouldn't want to see anyone waste their free time trying to improve it further when we, as a community, should be moving away from color codes.

**Comment by chrjorgensen** [comment]
@ThomasMcA You can also search the closed issues for 'SEU' and see how others fixed their systems and got SEU colour code working.

**Comment by ffleer** [comment]
@ThomasMcA and @chrjorgensen thanks for your feedback.

**Comment by ThomasMcA** [comment]
Thanks, changing the environment variables for SSH fixed the issue for me.
