### ISSUE TITLE
Request getFileDefinition failed with message: command 'code-for-ibmi.runCommand' not found

### ISSUE THREAD

**Issue by MarcoDeSenas** [halcyon-tech/vscode-ibmi#1454]
Hello
I get this error message in output panel every time I hit any keyboard key in CLLE type source file.

[Error - 21:02:41] Request textDocument/documentSymbol failed.
  Message: Request getFileDefinition failed with message: command 'code-for-ibmi.runCommand' not found
  Code: -32603 
[Error - 21:02:47] Request textDocument/documentSymbol failed.
  Message: Request getFileDefinition failed with message: command 'code-for-ibmi.runCommand' not found
  Code: -32603 

These messages do not seem to have any consequence. I can write code, run actions, look at problems panel if compile fail...

I don't receive this message for other source files types such as RPGLE, CMD.
I am using IFS files a source files. 

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.0.2|
|Visual Studio Code version|1.80.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Attachement automatique du débogage de nœud (debug-auto-launch): 1.0.0
Authentification GitHub (github-authentication): 0.0.2
CL (vscode-clle): 1.1.0
COBOL (cobol): 9.7.23
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Compte Microsoft (microsoft-authentication): 0.0.1
Conflit de fusion (merge-conflict): 1.0.0
Db2 for IBM i (vscode-db2i): 0.3.3
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.12.0
Fonctionnalités de langage JSON (json-language-features): 1.0.0
Fonctionnalités de langage TypeScript et JavaScript (typescript-language-features): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
Overtype (overtype): 0.5.0
TODO Highlight (vscode-todo-highlight): 1.0.5
WSL : Recommandeur (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|n/a|
|CCSID|297|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/DIMARCOB.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=DIMARCO1
CURLIB=DIMARCO1
HOME=/home/DIMARCO
LIBLS=DIMARCOB GAMES400 DIMARCO2 QTEMP QGPL
LOGIN=dimarco
LOGNAME=dimarco
MAIL=/var/spool/mail/dimarco
OLDPWD=/home/DIMARCO
PASE_USRGRP_LIMITED=N
PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/DIMARCO
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=88.170.41.66 39842 2222
SSH_CONNECTION=88.170.41.66 39842 185.113.5.134 2222
TZ=<UTC>0
USER=dimarco
USERNAME=DIMARCO
_=/QOpenSys/usr/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "£à$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(DIMARCOB) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPD0032: Not authorized to command CRTLIB in library *LIBL.\nCPF0006: Errors occurred in command.",
    "cwd": "/home/DIMARCO"
  },
  {
    "command": "system \"DLTOBJ OBJ(DIMARCOB/O_*) OBJTYPE(*FILE)\"",
    "code": 255,
    "stderr": "CPF2125: No objects deleted.",
    "cwd": "/home/DIMARCO"
  },
  {
    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx",
    "code": 2,
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx not found",
    "cwd": "/home/DIMARCO"
  }
]
```
</details>

**Comment by worksofliam** [comment]
Thanks! Looking into this.

**Comment by worksofliam** [comment]
Here's the line of code it's happening on: https://github.com/IBM/vscode-clle/blob/main/client/src/external/handlers/vscodeIbmi.ts#L50

Basically, we removed those vscode commands ages ago, but were replaced with export APIs (`instance.getConnection().sendCommand()` I think)

I've asked someone to lend a hand for fixing this, otherwise it will be done on Monday.

**Comment by MarcoDeSenas** [comment]
ok, thanks.
