### ISSUE TITLE
$(userHome) no longer works starting at version 2

### ISSUE THREAD

**Issue by icecreamville** [halcyon-tech/vscode-ibmi#1465]
I have home computers that are "local" & a work machine that is on a corporate domain.  The "user" login for each is different (ie. jsmith on home, joesmith on corporate).  All machines on Windows 10 Pro.

When syncing the extension settings between the machines, each time I used the one on the domain, it couldn't find the key, because the extension setting were synced from my personal machines - once I adjusted the private key path on the corporate machine,  I would have issues with the personal ones.

I got around this by setting the private key path (in "Login settings") to ${userHome}\.ssh\private_key.ppk - and it seemed to work perfectly.

The  "privateKey" definition within "code-for-ibmi.connections":  when looking at the JSON is

"privateKey": "${userHome}\\.ssh\\private_key.ppk"

After upgrading to 2.0 & higher, I can no longer connect to my system using this value - I receive the following error when attempting to connect to my system (replace <ip address> with actual IP address)

Not connected to <ip address>! ENOENT: no such file or directory, open '${userHome}\.ssh\private_key.ppk'

Have installed 2.0.0, 2.0.1 & 2.0.2 and the issue appears in all 3 versions.

Reverting back to 1.9.4 works as expected.

Thank you

**Comment by sebjulliand** [comment]
Good finding; this PR will fix the problem: https://github.com/halcyon-tech/vscode-ibmi/pull/1466
It appears the variable replacement occurs after the private key is being read, hence the issue 😉

**Comment by icecreamville** [comment]
Thank you - will verify this is fixed once it has been merged to main
