### ISSUE TITLE
How to modify the Deploy Script?

### ISSUE THREAD

**Issue by ravisankar-PIO** [halcyon-tech/vscode-ibmi#1468]
Ok. This is actually two questions.

1) I want to run a custom shell script after I deploy my sources to the IFS folder. Where can I append/modify my shell script? 

2) I also want to run a custom shell script after I made a successful connection to an IBMi server. (such as changing library list, setting up current library, changing CCSID and changing authority of users etc.,). 

Needless to say, I would be using `system` command in Bash/QShell to execute the CL commands in both the cases above.

**Comment by worksofliam** [comment]
1. Create an action (in the actions.json file) that runs a specific command: https://halcyon-tech.github.io/docs/#/pages/developing/local/getting-started?id=_4-workspace-actions-deploy-amp-build

2. Sadly you can’t do that and altering the library list and such won’t affect the connection as we run most commands in a stateless manner. You likely want to check out profiles: https://halcyon-tech.github.io/docs/#/pages/settings/profiles
