### ISSUE TITLE
Trigger the IBM Debug initial setup script

### ISSUE THREAD

**Issue by DLCentral** [halcyon-tech/vscode-ibmi#1472]
The issue I'm ultimately dealing with is getting Debugging working. It worked out of the box after following the initial setup wizard, but after a few weeks of not having to use it, I came back and it stopped working. I suspect it's nothing more than my borking something in my config. But I figured my best best would be to reset and go through the initial setup wizard again.

Is there a way to walkthrough the initial IBM Debug setup script after going through it once already? Or is the only option to uninstall and reinstall the entire Code for IBMi extension? If it is, no worries, I was just hoping to avoid it.

What I've tried so far:

In the documentation it says:
"After connecting to a system in Code for IBM i, if the PTFs are installed but the service is not configured (i.e. the certificates don’t exist) you will see a notice asking if you’d like to open the Walkthrough to configure the Debug Service. Clicking the button will open the Walkthrough."

So I tried renaming the directory /QIBM/ProdData/IBMiDebugService/bin/certs to something else. Additionally I renamed the local certificate located here as well: C:\Users\<user>\<server_name>_debug_service.crt. I then ended the debug service via ([iNavigator](https://www.ibm.com/support/pages/debug-service)) and then disconnected and reconnected to the server within VSCode, but it didn't seem to do the trick.

Note: we are on V7.4 and I have confirmed both SI80364 and SI81031 are permanently applied with:
```
SELECT PTF_IDENTIFIER, PTF_LOADED_STATUS 
FROM QSYS2.PTF_INFO 
WHERE PTF_IDENTIFIER IN ('SI81031', 'SI80364');
```

Also, I'm not testing with interactive scripts. I know that's not supported yet.

**Comment by worksofliam** [comment]
You should simply be able to launch the Walkthrough again to go through the debug setup.

1. Open the Command Palette
2. Search for 'Open Walkthrough...'
3. Look for one related to Code for IBM i and debugging

That is the initial stuff you see when you setup the debugger.

**Comment by DLCentral** [comment]
Ah wonderful. I didn't even realize the "open walkthrough" was a universal VS Code feature. It looks a bunch of extension support the same.  Thank you for the quick reply. I have some tinkering to do!
