### ISSUE TITLE
Formatting free RPGLE sources

### ISSUE THREAD

**Issue by alfax218** [halcyon-tech/vscode-ibmi#1473]
Hi everyone,
is it possible to format RPGLE sources to align lines to the right columns? Something similiar to what RDI does for RPGLE or extensions like Prettier does for other languages.

If not currently possible, could it become a new feature?

Thanks

**Comment by worksofliam** [comment]
Check out our docs: https://halcyon-tech.github.io/docs/#/pages/extensions/rpgle/linter
