### ISSUE TITLE
2.1.0 Update validation of library list does not use user IASP

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#1497]
I get this warning now.
```
The following libraries does not exist: WFICPYSRC,WFIDBDEFNS,WFIMODULES,WIASPUSR,DTSUSER,DTSCNTRL,DTSDCDTA,WFIDTA,WFINEP,WFIHST,WFIOBJ,PROFOUNDUI,PROFOUNDJS,SPLTOOL,AFPTOOL,WFISRC. Remove them from the library list?
```

I see this in the log.  We use an IASP on our system
```
/home/PGMT: for lib in WFICPYSRC WFIDBDEFNS WFIMODULES WIASPUSR WSBUSR WSBDTA WSBOBJ WSBSRC DTSUSER DTSCNTRL DTSDCDTA WFIDTA WFINEP WFIHST WFIOBJ PROFOUNDUI PROFOUNDJS TAATOOL SPLTOOL AFPTOOL WFISRC QGPL QTEMP; do if [ -d /QSYS.LIB/$lib.LIB ]; then echo $lib; fi; done
{
    "code": 0,
    "signal": null,
    "stdout": "WSBUSR\nWSBDTA\nWSBOBJ\nWSBSRC\nTAATOOL\nQGPL\nQTEMP",
    "stderr": ""
}
```
This process takes far too long to complete as well.   I am not completely certain of the purpose of this action but if its to see if the library on the list if a valid libary on the system, maybe running `DSPOBJD QSYS/*ALL *LIB` to outfile would be faster.   Its seems that the process takes longer when the library is a one with a lot of objects. 
<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.1.0|
|Visual Studio Code version|1.78.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code Spell Checker (code-spell-checker): 2.20.5
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.4.0
ESLint (vscode-eslint): 2.4.2
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.13.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
Git Graph (git-graph): 1.30.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
Partial Diff (partial-diff): 1.4.3
Project Dashboard (vscode-dashboard): 2.6.0
SQL Formatter VSCode (sql-formatter-vsc): 2.1.0
Text Marker (Highlighter) (text-marker): 1.11.0
Todo Tree (todo-tree): 0.0.226
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
classdiagram-ts (classdiagram-ts): 0.1.67
undefined (indent-rainbow): 8.3.1
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R3M0|
|Tech Refresh|13|
|CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|QZDFMDB2.PGM|startDebugService.sh|
|git|iconv||||
|grep|setccsid||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx",
    "code": 2,
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx not found",
    "cwd": "/home/PGMT"
  },
  {
    "command": "ls undefined",
    "code": 2,
    "stderr": "undefined not found",
    "cwd": "/home/PGMT"
  },
  {
    "command": "export BUILDLIB=\"QGPL\" && export CURLIB=\"QGPL\" && export USERNAME=\"PGMT\" && export HOME=\"/home/PGMT\" && export LIBLS=\"QTEMP QGPL WFISRC AFPTOOL SPLTOOL TAATOOL PROFOUNDJS PROFOUNDUI WFIOBJ WFIHST WFINEP WFIDTA DTSDCDTA DTSCNTRL DTSUSER WSBSRC WSBOBJ WSBDTA WSBUSR WIASPUSR WFIMODULES WFIDBDEFNS WFICPYSRC\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=QGPL: is not an identifier",
    "cwd": "/home/PGMT"
  }
]
```
</details>

**Comment by worksofliam** [comment]
@m-tyler Do you have this ASP configured on your user profile or just in the Connection Settings?

**Comment by m-tyler** [comment]
I have a IASP specified on user profile and not in connection settings.  I have been relying on the use of the SQL view to obtain the IASP for the working value. 

It also seems that this only appears when the quick connection feature is not  present for the workspace.

**Comment by worksofliam** [comment]
cc @chrjorgensen

**Comment by m-tyler** [comment]
You can ignore the time length portion as it seemed to be a problem with the server I was connecting to.

**Comment by m-tyler** [comment]
If the user dismisses the notifications while connecting, this process never completes and you never finish connecting.  You must return to the notifications and answer the warning message.

**Comment by chrjorgensen** [comment]
@worksofliam Agree... closed... 😄
