### ISSUE TITLE
Request creating spool file for compiled member

### ISSUE THREAD

**Issue by danielwexstaff** [halcyon-tech/vscode-ibmi#1516]
Request creating a spool file for member that is compiled. 

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.1.1|
|Visual Studio Code version|1.81.1|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 9.8.31
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.4.1
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.13.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
HTML CSS Support (vscode-html-css): 1.13.1
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|5|
|CCSID|65535|
|SQL|Disabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|grep|setccsid||||
|ls|tar||||
|md5sum|||||
|sort|||||
|stat|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=ELWORKR
CURLIB=ELWORKR
HOME=/home/DANIELW
LIBLS=ELOE EL.DANIELW ELPO ELICAR ELCON QTEMP QGPL ELBID ELQUE TLBOX ELWORKR
LOGIN=danielw
LOGNAME=danielw
MAIL=/var/spool/mail/danielw
OLDPWD=/home/DANIELW
PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/DANIELW
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=192.168.1.68 63218 22
SSH_CONNECTION=192.168.1.68 63218 192.168.1.19 22
TZ=<EST>5<EDT>,M3.2.0,M11.1.0
USER=danielw
USERNAME=danielw
_=/QOpenSys/usr/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/DANIELW"
  }
]
```
</details>

**Comment by chrjorgensen** [comment]
@danielwexstaff 

> Request creating a spool file for member that is compiled.

Please state the reasoning behind this request - no other Code for IBM i user has requested this.

**Comment by SJLennon** [comment]
@danielwexstaff 
Might View/Open View/Output then choose IBM i Output give you what you want?
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/67484051/cab23734-8988-4be0-beb4-27ec93713d49)

**Comment by SJLennon** [comment]
@danielwexstaff 
You will find this under the Task view as v2.2.0, as I have just discovered.

**Comment by danielwexstaff** [comment]
Thank you @SJLennon. I did see that I can get the spool file output from the Output tab, but what I am asking for is a spool file to be generated on the IBM i system that I am working on, as well as in VS Code. This is nice but when I am working on different projects, I leave my spool files out there until I am finished or have completed the project. This 1) gives me and anyone else working on the same set of code visibility to what I am working on or what others have worked on, and 2) it allows me to have a set place I can see what has been compiled and then in turn I can write my TODONE, i.e. the changes that I have made to a change log that is standard at my company.

**Comment by chrjorgensen** [comment]
@danielwexstaff IMHO it seems to me you are using the spooled files as a log - correct me if I'm wrong.

You could create a DB2 table to contain your compile info and write your TODONE from this.

```sql
create table MyLib.Code4iLog (
  LOG_TIME timestamp(0) default current_timestamp,
  LOG_PROJECT varchar(128),
  LOG_TEXT varchar(32000)
)
```

On the actions needed to be logged, you would add the following command to the action:

```
runsql 'insert into MyLib.Code4iLog ( LOG_PROJECT, LOG_TEXT ) values ( ''&MYPROJ'', ''CRTBNDRPG PGM(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF)'' )' commit(*none)
```

This will add an entry in your logfile for each run of the action.

Notes:
- You can have more than one command in an action, so you would add the `RUNSQL` command above on a new line after the CL command currently in the action.
- All quotes inside the `insert into` SQL statements has to be doubled, as usual in CL command parameters allowing text.
- the &MYPROJ could be a [custom variable](https://halcyon-tech.github.io/docs/#/pages/developing/actions/custom-vars), that you define i Code for IBM i, to hold your project code. This could be dependent on a [profile](https://halcyon-tech.github.io/docs/#/pages/settings/profiles) in the library list view. Or it could just be a constant in the `RUNSQL` command.
- You can use all the built-in variables as well as custom variables in the text.
- The example above is for the CRTBNDRPG command on members. The command text to be logged will obviously be different on other actions.

Hope this will help you creating a log over actions run from Code for IBM i?

**Comment by SJLennon** [comment]
@chrjorgensen 
You said "_You can have more than one command in an action, so you would add the RUNSQL command above on a new line after the CL command currently in the action._"

Can you give me an example  of how to enter more than one command in an action?

I can't find anything in the documentation.  Trying something like this to create a DSPF from a local repository, but not having much success:
```
  {"extensions": [
    "dspf",
    "DSPF"
  ],"name": "Create Display File",
  "command":   " CRTSRCPF FILE(QTEMP/Z) RCDLEN(198) QSYS/CPYFRMSTMF FROMSTMF('/home/LENNONS/IBMi_IFS_Dev/5250_Subfile/PMTCUSTD.DSPF') TOMBR('/qsys.lib/qtemp.lib/z.file/pmtcustd.mbr') MBROPT(*REPLACE) CRTDSPF FILE(&CURLIB/&NAME) SRCFILE(&OPENLIB/&OPENSPF) SRCMBR(&OPENMBR) RSTDSP(*NO) REPLACE(*YES) OPTION(*EVENTF)",
  "deployFirst": true,
  "environment": "ile"
  },
```
And is there a list of variable that can be substituted?  For example, above I eventually want to extract PMTCUSTD out of the file name PMYCUSTD.DSPF.

If this is feasible and I can figure it out I will update the documentation.

Thanks

**Comment by SJLennon** [comment]
@chrjorgensen 
Ah, looks like \n separate commands. Right?
Still would like a list of variable that can be substituted.

Thanks

**Comment by chrjorgensen** [comment]
@SJLennon Check the list of variables below the command input area - there are separate variables for members, stream files and objects, though some are common.

**Comment by sebjulliand** [comment]
I think everything is documented in the action editor, below each field.

**Comment by SJLennon** [comment]
@chrjorgensen @sebjulliand 
Thank you gentlemen. I had trouble finding the actions editor since Actions has moved since the last time I used it..  And I was editing actions.json directly this time.

In an action with multiple commands, are all the commands executed in the same connection, so that  QTEMP can be used? 

I thought I'd read that somewhere. So I tried a CRTSRCPF in QTEMP, a CPYFRMSTMF to the QTEMP file, but it failed because I couldn't find the QTEMP file.

Using a permanent library does work., as below, but a second execution of the CRTSRCPF fails because the file exists.
```
  {"extensions": [
    "dspf", 
    "DSPF"
  ],"name": "Create Display File",
  "command": " CRTSRCPF FILE(LENNONSB/Z) RCDLEN(198)\n QSYS/CPYFRMSTMF FROMSTMF('&RELATIVEPATH') TOMBR('/qsys.lib/LENNONSB.lib/z.file/&NAME.mbr') MBROPT(*REPLACE)\nCRTDSPF FILE(&CURLIB/&NAME) SRCFILE(LENNONSB/Z) SRCMBR(*FILE) RSTDSP(*YES) REPLACE(*YES) OPTION(*EVENTF)",
  "deployFirst": true,
  "environment": "ile"
  },
```

**Comment by chrjorgensen** [comment]
@SJLennon IIRC each command runs in a separate job, so no sharing of QTEMP is possible.

Suggestion for your code example: Why not use the excellent command [CRTFRMSTMF by Brian Garland](https://github.com/BrianGarland/CRTFRMSTMF), which does exactly what you're trying to do: Creates an object from source in the IFS, where the create command does not support streamfiles.
I've used this since many years, and it just works!

**Comment by SJLennon** [comment]
@chrjorgensen 
Yes, i looked at that, but I was trying to do it without installing anything on the IBM i.
