### ISSUE TITLE
Implementation of a server manager

### ISSUE THREAD

**Issue by szsascha** [halcyon-tech/vscode-ibmi#152]
**Is your feature request related to a problem? Please describe.**
At the moment you're only able to connect with your previous IBM i session. But there are environments where you need to switch between multiple IBM i servers.

**Describe the solution you'd like**
I think a simple server manager like the one from the software called "FileZilla" (but far more simple) should be easy to implement. I would even say that this is maybe a good first contribution for someone who is new to this project.

**Describe alternatives you've considered**
One alternative is to leave it as it is. You're welcome to give me some feedback on this. Maybe you have more ideas?

**Comment by worksofliam** [comment]
This is a good idea!

Right now the only way to edit an existing connection is to edit the JSON manually, but this something that our CustomUI could do nicely.

Maybe I will even take a stab at it.

**Comment by szsascha** [comment]
Just an idea: Maybe it would be nice to be able define some more custom settings in the servermanager (i.e. library list, default ifs directory, etc.)

**Comment by worksofliam** [comment]
@szsascha I'd like to work on this soon.

Any chance you can provide as much detail as possible for what you would like to see?

**Comment by worksofliam** [comment]
Hey @szsascha 

Not only do we have the Server Browser now - we also have a way to edit the connection without being connected now!

Out very soon.

![image](https://user-images.githubusercontent.com/3708366/132928739-64c34d80-a65b-4bca-bdae-a9a14b682b67.png)

**Comment by szsascha** [comment]
@worksofliam 

Thank you very much! Sorry for not answering your question. I just haven't seen it.
