### ISSUE TITLE
vscode-ibmi needs to implement new callback signature

### ISSUE THREAD

**Issue by edmundreinhardt** [halcyon-tech/vscode-ibmi#1523]
Save us time! Click 'Report an Issue' from the Help and Support panel inside of VS Code after you have connected to a system.

**Describe the bug**
Seb made the callback method more type specific, I believe that is why the project-explorer extension is not loading successfully
The offending PR is: https://github.com/IBM/vscode-ibmi-projectexplorer/pull/201
Basically he is guaranteeing that an iProject is passed in

<img width="914" alt="image" src="https://github.com/halcyon-tech/vscode-ibmi/assets/11184579/5c573f08-915b-4e4b-8081-f3100b7beb02">

**To Reproduce**
1. git clone main branch of 
2. Load Code for IBM i v 2.2.0
3. The output for Extension Host shows an error

**Expected behavior**
The extension should load without error

**Screenshots**
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/11184579/d729b3b6-108d-4ee9-b749-0d37774ce52d)

**Environment (please complete the following information):**
 - Extension version [2.2.0]
 - IBM i OS version [N/A]

**Additional context**

**Comment by edmundreinhardt** [comment]
It would make sense for @sebjulliand to look at this

**Comment by sebjulliand** [comment]
@edmundreinhardt I don't have that crash here using Code for IBM i 2.2.0 and running the head of the explorer's main branch.
I'd be very surprised that the change from https://github.com/IBM/vscode-ibmi-projectexplorer/pull/201 is at fault here. That may be related to something else...

Besides, Code for IBM i does not import or implement or call anything from Project Explorer (that would create a dependency cycle 😅).

**Comment by worksofliam** [comment]
That 'name' error has been happening for months (no kidding) but does not pose an immediate issue.

**Comment by edmundreinhardt** [comment]
The problem is no longer reproducible.  I am closing.  (It could be that Project Explorer was depending on old types)
