### ISSUE TITLE
In "Selet a Language", COBOL is not in the list (Select Language Mode) 

### ISSUE THREAD

**Issue by OkoyDev** [halcyon-tech/vscode-ibmi#1524]
Save us time! Click 'Report an Issue' from the Help and Support panel inside of VS Code after you have connected to a system.

**Describe the bug**
After installing Code for IBM i, only RPGLE, CL, C/CPP are present in the "Select Language Mode", COBOL is NOT there.

**To Reproduce**

**Expected behavior**
COBOL should be in the list in "Select Language Mode"

**Screenshots**
Screenshot attached.
![VSCode No Cobol in the List](https://github.com/halcyon-tech/vscode-ibmi/assets/144329273/7b946e10-1622-4c09-9656-a081990a5477)

**Environment (please complete the following information):**
 - Extension version v2.2.0
 - IBM i OS version [e.g. 7.x]

**Additional context**

**Comment by sebjulliand** [comment]
Hi, Cobol language support is not provided by Code for IBM i; it is usually provided by this extension: [COBOL](https://marketplace.visualstudio.com/items?itemName=bitlang.cobol)
You can also consider installing the [IBM i Development Extension Pack](https://marketplace.visualstudio.com/items?itemName=HalcyonTechLtd.ibm-i-development-pack) to get everything you need.

**Comment by OkoyDev** [comment]
Thanks

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 7, 2023 at 5:33 PM, Sébastien ***@***.***> wrote:   


Closed #1524 as completed.
