### ISSUE TITLE
Recent update to v2.2.0 compile output to terminal window truncates compile listing

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#1526]
Recent update to v2.2.0 compile output to terminal window truncates compile listing.   You will need a program that produces more than 1000 lines of output.   A program I noticed this on is raw source of 1432 lines and is an SQLRPGLE.  This kind of defeats the purpose of producing the compile listing if the new target output view truncates the lines shown. 

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/1353665/131291d3-08e5-40e0-b252-af4a9b6f8675)

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.2.0|
|Visual Studio Code version|1.78.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code Spell Checker (code-spell-checker): 2.20.5
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Data Preview (vscode-data-preview): 2.3.0
Db2 for IBM i (vscode-db2i): 0.4.1
ESLint (vscode-eslint): 2.4.2
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.13.0
Excel Viewer (gc-excelviewer): 4.2.58
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
Git Graph (git-graph): 1.30.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
Partial Diff (partial-diff): 1.4.3
RPGLE (vscode-rpgle): 0.21.4
Rainbow CSV (rainbow-csv): 3.7.0
SQL Formatter VSCode (sql-formatter-vsc): 2.1.1
Text Marker (Highlighter) (text-marker): 1.11.0
Todo Tree (todo-tree): 0.0.226
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
Version Lens (vscode-versionlens): 1.5.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
classdiagram-ts (classdiagram-ts): 0.1.67
undefined (indent-rainbow): 8.3.1
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|2|
|CCSID|37|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|git|iconv|GETNEWLIBL.PGM|||
|grep|setccsid||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=PGXX
CURLIB=PGXX
HOME=/home/PGXX
HOST=my.dev.system
LIBLS=QTEMP QGPL HAWKEYE WFISRC WAEOBJ WAEDTA ACMSLIB AFPTOOL SPLTOOL TAATOOL WFIOBJ WFIHST WFINEP WFIDTA WFIQUAL WFIINTG DTSDCDTA DTSCNTRL DTSUSER DTSQUAL DTSQUAL92 DTSINTG DTSINTG92 DEVOBJ DEVDTA DEVSRC DEVQUAL WSBSRC WSBOBJ WSBDTA WSBQUAL WSBINTG WSBUSR WIASPUSR PGXX
LMI_REL_IDLIB=WFIOBJ
LMI_REL_IDLIBS=WFIOBJ,WFICVT
LOGIN=PGXX
LOGNAME=PGXX
MAIL=/var/spool/mail/PGXX
NUMPCR=2066900
OLDPWD=/home/PGXX
PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PCR=PCR2066900
PROFILENAME=BASE: PGXX
PWD=/home/PGXX
REL=BASE
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=10.10.0.135 52831 22
SSH_CONNECTION=10.10.0.135 52831 10.0.4.31 22
TZ=<MST>7<MDT>,M3.2.0,M11.1.0
USER=PGXX
USERNAME=PGXX
_=/QOpenSys/usr/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF3012:  File PRP48VCSV in library *LIBL not found.",
    "cwd": "/home/PGXX"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPC7301:  File QSQLPRE created in library QTEMP.\nCPC7305:  Member UTL96BRG added to file QSQLPRE in QTEMP.\nCPC3201:  Member UTL96BRG file QSQLPRE in QTEMP changed.\nRNS9307:  Diagnostic check of source is complete. Highest severity is 00.\nCPC0904:  Data area RETURNCODE created in library QTEMP.\nCPF4011:  Buffer length longer than record for member UTL96BRG.\nCPC7305:  Member UTL96BRG added to file QSQLTEMP1 in PGXX.\nRNS9308:  Compilation stopped. Severity 20 errors found in program.\nRNS9310:  Compilation failed. Program UTL96BRG not created in library PGXX.",
    "cwd": "/home/PGXX"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPC7301:  File QSQLPRE created in library QTEMP.\nCPC7305:  Member UTL96BRG added to file QSQLPRE in QTEMP.\nCPC3201:  Member UTL96BRG file QSQLPRE in QTEMP changed.\nRNS9307:  Diagnostic check of source is complete. Highest severity is 00.\nCPC0904:  Data area RETURNCODE created in library QTEMP.\nCPF4011:  Buffer length longer than record for member UTL96BRG.\nCPC7305:  Member UTL96BRG added to file QSQLTEMP1 in PGXX.\nRNS9308:  Compilation stopped. Severity 20 errors found in program.\nRNS9310:  Compilation failed. Program UTL96BRG not created in library PGXX.",
    "cwd": "/home/PGXX"
  }
]
```
</details>

**Comment by sebjulliand** [comment]
@m-tyler can you try to increment this value in the settings and see if it helps?
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/11096890/3babe120-0722-4b68-ad45-4bc9079fd8dd)

**Comment by m-tyler** [comment]
Yes, that setting works(ish) although its not a value that I can know for all source, us legacy system folks tend to have very large source. 

I set it to 10000 and recompiled.

The source I found this with the compile listing is 6525 lines (with CPYSPLF to DB) but for some reason it producing over 10000 lines in the output.    I think this control is good enough for most it just took me by surprise because I am still in the habit of going to the compile output to see compile errors as I had trouble getting the errors loaded into the source view.   The errors are loading into the source view with recent changes so I guess i just need to go back to relying on that feature.

**Comment by worksofliam** [comment]
Hmm, this is potentially bad. @sebjulliand I am thinking we might need to set a default for this setting like we do here for `enablePreview`?

https://github.com/halcyon-tech/vscode-ibmi/blob/33da7a891d61bd5dab68e6d98b68f13e754b918e/src/api/IBMi.ts#L822

**Comment by m-tyler** [comment]
Since this is re-open, I am now seeing a message for me to save all other unsaved tabs before proceeding with an action like compile. 
Before choosing an action.
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/1353665/14ae4331-1675-4fa0-83a0-3fee7a97836c)
Action list
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/1353665/bdecfb91-5f80-46b8-920d-02ff3cd6025c)
After choosing to run CRTSQLRPGI
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/1353665/6b64d03f-3f48-46d4-9ec3-eb540d022f6c)

I can select don't save but at first it's a little alarming and I don't always want to wait for the process of saving just to compile a member.  The pop-up appears even if the member I choose Ctrl+E on is already saved.

If this cannot be worked around, then I think it needs to be pointed out in the documentation.   I get around the pop-up by just pressing ESC and it goes away then the action command input appears (if I choose a command that prompts).

**Comment by worksofliam** [comment]
Likely going back to the Output View.

**Comment by m-tyler** [comment]
I think this is the best approach for now.  I was going to add an issue about having issues getting the object browsers to refresh after using an action and dismissing the output channel without clearing it.  

It happens for me as I use actions linked to commands for my companies CMS product (Rocket Aldon).  I can open a member in production location, run an action to check out that member to a project I am working on, then I usually refresh the object browser filter to have the member appear in the list but if I dismiss the new output channel the object browser does not seem to want to refresh.  

I don't know if these two are related.
