### ISSUE TITLE
apex into a comment problem

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/vscode-ibmi#1541]
Hi, there's a problem probably in lint?

I have an apex into a comment, and starting from this it put me all my program (really until it find another apex) like a constant.

<img width="676" alt="image" src="https://github.com/halcyon-tech/vscode-ibmi/assets/9719313/7dd2eff2-5375-4aa9-84a7-fef569ed57ac">

Could you check?

Thank you

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.2.1|
|Visual Studio Code version|1.82.2|
|Operating System|darwin_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 9.8.31
Code Coverage for IBM i (code-coverage-ibmi): 0.1.7
Code Spell Checker (code-spell-checker): 3.0.1
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.4.1
Dev Containers (remote-containers): 0.309.0
ESLint (vscode-eslint): 2.4.2
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.13.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
Git Graph (git-graph): 1.30.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitHub Pull Requests and Issues (vscode-pull-request-github): 0.72.0
GitLab Workflow (gitlab-workflow): 3.77.1
GitLens — Git supercharged (gitlens): 14.3.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
IBM i Project Explorer (vscode-ibmi-projectexplorer): 1.2.2
JSON Language Features (json-language-features): 1.0.0
Live Share (vsliveshare): 1.0.5883
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Postman (postman-for-vscode): 0.8.0
RPGLE (vscode-rpgle): 0.21.4
Rainbow CSV (rainbow-csv): 3.7.0
Remote - Tunnels (remote-server): 1.4.3
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL (remote-wsl): 0.81.3
vscode-icons (vscode-icons): 12.5.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|8|
|CCSID|280|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|vscode.GETNEWLIBL|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv||||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=JDET
CURLIB=JDET
HOME=/home/myuser
HOST=directa1
LANG=IT_IT.UTF-8
LIBLS=QTEMP 
LOGIN=myuser
LOGNAME=myuser
LS_COLORS=
MAIL=/var/spool/mail/myuser
OLDPWD=/DIRECTA1/home/myuser
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PS1=\u@\h@\W$
PWD=/home/myuser
QIBM_PASE_CCSID=1208
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=192.168.0.141 56865 22
SSH_CONNECTION=192.168.0.141 56865 192.168.0.11 22
SSL_CERT_FILE=/home/cacert.pem
TZ=<CET>-1<CEST>,M3.5.0,M10.5.0
USER=myuser
USERNAME=myuser
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "£§$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF3012:  File CMELTRWW non trovato nella libreria *LIBL.\nCPC2206:  È stata modificata la proprietà dell'oggetto QZSHSYSTEM in QTEMP di tipo *USRSPC.",
    "cwd": "/home/myuser"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF3012:  File CMELTRC3SS non trovato nella libreria *LIBL.\nCPC2206:  È stata modificata la proprietà dell'oggetto QZSHSYSTEM in QTEMP di tipo *USRSPC.",
    "cwd": "/home/myuser"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPF3012:  File EMIRATECOW non trovato nella libreria *LIBL.\nCPC2206:  È stata modificata la proprietà dell'oggetto QZSHSYSTEM in QTEMP di tipo *USRSPC.",
    "cwd": "/home/v"
  }
]
```
</details>

**Comment by chrjorgensen** [comment]
@pabloto Is your problem in the syntax colouring? You do not have the [IBM i Languages](https://marketplace.visualstudio.com/items?itemName=barrettotte.ibmi-languages) extension installed, which will provide the correct syntax colour for RPGLE, CL etc.

The extension will be installed automatically, if you install the [IBM i Development Pack](https://marketplace.visualstudio.com/items?itemName=HalcyonTechLtd.ibm-i-development-pack) extension.

**Comment by pabloto** [comment]
I have ibm development pack installed

**Comment by worksofliam** [comment]
@pabloto what is the language selected when you have the file open with the messed up comment? You can see it in the bottom right.

**Comment by pabloto** [comment]
I don't understand why but now I don't have the problem. I'll close the issue if it comes again I'll reopen it.
Many thanks.
