### ISSUE TITLE
Reconnecting with private key fails with ENAMETOOLONG

### ISSUE THREAD

**Issue by edmundreinhardt** [halcyon-tech/vscode-ibmi#1542]
After a timeout disconnect, Code for IBM i prompts correctly to reconnect.
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/11184579/3d5194d1-1e55-452d-ba57-6e53f957f709)

But when attempting to do so, the connection attempt fails with
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/11184579/29a6e57c-f7c3-4d06-bad9-d5dc17edb1bc)
...
<img width="528" alt="image" src="https://github.com/halcyon-tech/vscode-ibmi/assets/11184579/23d8ef3e-a0af-4bfb-b711-6b9ab1bcddbe">

Pressing Yes to reconnect simply causes the same  error to reappear 

However when I Cancel and reconnect it succeeds
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/11184579/d4175667-ed6c-4ce5-a28e-6a0ad97dfc59)

Note the Login Settings specify the Private Key
<img width="853" alt="image" src="https://github.com/halcyon-tech/vscode-ibmi/assets/11184579/a7078476-bd7e-4fb7-abc2-79c9a67ef315">

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.2.0|
|Visual Studio Code version|1.82.0|
|Operating System|darwin_arm64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.4.1
ESLint (vscode-eslint): 2.4.2
Emmet (emmet): 1.0.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitLens — Git supercharged (gitlens): 14.3.0
IBM i Project Explorer (vscode-ibmi-projectexplorer): 1.2.2
JSON Language Features (json-language-features): 1.0.0
Live Share (vsliveshare): 1.0.5883
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.21.4
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|n/a|
|Tech Refresh|n/a|
|CCSID|65535|
|SQL|Disabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=BOBTEST
CURLIB=BOBTEST
HOME=/home/REINHARD
HOST=p8adt05.rch.stglabs.ibm.com
LIBLS=PAYROLLORG QTEMP RPGUNIT TDD_ER
LOGIN=reinhard
LOGNAME=reinhard
MAIL=/var/spool/mail/reinhard
OLDPWD=/home/REINHARD
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/REINHARD
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=9.67.16.205 62184 22
SSH_CONNECTION=9.67.16.205 62184 9.5.12.241 22
TZ=<UTC>0
USER=reinhard
USERNAME=reinhard
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/REINHARD"
  }
]
```
</details>

**Comment by sebjulliand** [comment]
@edmundreinhardt I see what the problem is. I'll fix it.

**Comment by edmundreinhardt** [comment]
Thanks Seb,
I am trying with your branch and my workspace and I am seeing the same behaviour.

did 
```
%
git fetch --all
Fetching upstream
Fetching origin
 %
git branch fix/privateKeyReconnect
%
npm install

up to date, audited 312 packages in 718ms
%
code .
```
In Code I did `Run Extension`
Connected to an internal IBM i
Disconnect VPN
Expand Library list to invoke IBM
Get `Connection Lost` dialog 
Reconnect VPN
> press Yes to reconnect
Still get 
<img width="554" alt="image" src="https://github.com/halcyon-tech/vscode-ibmi/assets/11184579/686f4f8d-2e4e-4eb6-bb1e-e79fa0f16da1">

**Comment by edmundreinhardt** [comment]
Am I doing something wrong?

**Comment by edmundreinhardt** [comment]
git status
On branch fix/privateKeyReconnect
nothing to commit, working tree clean

**Comment by edmundreinhardt** [comment]
sadly same behaviour

**Comment by edmundreinhardt** [comment]
Works great!
