### ISSUE TITLE
Create Source File - only creates PF not SRC-PF

### ISSUE THREAD

**Issue by edmundreinhardt** [halcyon-tech/vscode-ibmi#1543]
RIght click on a filter of LIBRARY/*ALL/*.* (*ALL)
Select `Create Source File` from the context menu
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/11184579/a97c95de-07e7-41b7-89cd-c56cebfdb51d)
Specify a name for the SRC-PF
<img width="633" alt="image" src="https://github.com/halcyon-tech/vscode-ibmi/assets/11184579/7b2b91d0-383e-48a4-93db-2a0455c28ba5">
The resultant object is just  PF, and doesn't let us create members
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/11184579/cdf904f3-b8f7-400b-84f4-af2f69c9d05b)

|Context|Version|
|-|-|
|Code for IBM i version|2.2.0|
|Visual Studio Code version|1.82.0|
|Operating System|darwin_arm64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.1
Db2 for IBM i (vscode-db2i): 0.4.1
ESLint (vscode-eslint): 2.4.2
Emmet (emmet): 1.0.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitLens — Git supercharged (gitlens): 14.3.0
IBM i Project Explorer (vscode-ibmi-projectexplorer): 1.2.2
JSON Language Features (json-language-features): 1.0.0
Live Share (vsliveshare): 1.0.5883
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.21.4
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|n/a|
|Tech Refresh|n/a|
|CCSID|65535|
|SQL|Disabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=BOBTEST
CURLIB=BOBTEST
HOME=/home/REINHARD
HOST=p8adt05.rch.stglabs.ibm.com
LIBLS=PAYROLLORG QTEMP RPGUNIT TDD_ER
LOGIN=reinhard
LOGNAME=reinhard
MAIL=/var/spool/mail/reinhard
OLDPWD=/home/REINHARD
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/REINHARD
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=9.67.9.21 63056 22
SSH_CONNECTION=9.67.9.21 63056 9.5.12.241 22
TZ=<UTC>0
USER=reinhard
USERNAME=reinhard
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/REINHARD"
  },
  {
    "command": "system \"DSPOBJD OBJ(PAYROLLORG/*ALL) OBJTYPE(*ALL) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_h5qL8NEe)\"",
    "code": 255,
    "stderr": "CPF2123: No objects of specified name or type exist in library PAYROLLORG.",
    "cwd": "/home/REINHARD"
  }
]
```
</details>

**Comment by worksofliam** [comment]
Your filter is using `*ALL`, when it needs to use `*SRCPF`
