### ISSUE TITLE
Error saving, yields empty source file.

### ISSUE THREAD

**Issue by AMetnik** [halcyon-tech/vscode-ibmi#1549]
Hello
Today I had an issue, where VScode said that I could not save my RPG program.
I then closed the program and tried to open it again, and now it was all gone.

Is there any dumps or temporares I can recreate it from ?

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/2640098/25158391-8660-494f-898f-e54fb0f623f9)

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.2.1|
|Visual Studio Code version|1.82.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.2
Db2 for IBM i (vscode-db2i): 0.4.1
Emmet (emmet): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
Git Blame (gitblame): 10.5.1
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitHub Copilot Chat (copilot-chat): 0.7.1
GitLens — Git supercharged (gitlens): 14.3.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Peacock (vscode-peacock): 4.2.2
RPGLE (vscode-rpgle): 0.21.4
RPGLE Free (vscode-rpgfree): 0.0.26
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R4M0|
|Tech Refresh|8|
|CCSID|277|
|SQL|Enabled
|Source dates|Enabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|git|setccsid||||
|grep|tar||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=ANLIB
CURLIB=ANLIB
HOME=/home/ANMET
HOST=mensa
LIBLS=ICEBREAK SYSAFD UNO700CFUT SMSDB NHO NHOPRG YXDB NHODATA YXDTA24 QGPL QTEMP ANLIB
LOGIN=anmet
LOGNAME=anmet
MAIL=/var/spool/mail/anmet
OLDPWD=/home/ANMET
PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/ANMET
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=10.45.11.51 56390 22
SSH_CONNECTION=10.45.11.51 56390 10.45.18.44 22
TZ=<CET>-1<CEST>,M3.5.0,M10.5.0/03:00:00
USER=anmet
USERNAME=anmet
_=/QOpenSys/usr/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "ÆØÅ"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/ANMET"
  },
  {
    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx",
    "code": 2,
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx not found",
    "cwd": "/home/ANMET"
  }
]
```
</details>

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after you see the error.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by AMetnik** [comment]
Suggestion is to include that in the "report an issue" if possible of cause.
I no longer have this, since I reconnected to the session to try and fix the "error saving".
If it happens again, I'll include it :-)
