### ISSUE TITLE
New connection ==> config.privateKeyPath doesn't exist !

### ISSUE THREAD

**Issue by novy400** [halcyon-tech/vscode-ibmi#1550]
👉🏻 When I attempt to add a new connection using a login and user password (instead of SSH keys)
💣 I encounter an issue. 
![image](https://github.com/halcyon-tech/vscode-ibmi/assets/1349871/fb1ae9b6-5f0b-4125-85fd-0569af82ed93)

👁‍🗨 Upon inspecting the settings.json file, I noticed the property privateKeyPath: "" following the userName property.
 ✔The issue is resolved when I remove this line from the settings.json file.
😥🙏 Unfortunately, I don't have the time to debug this issue right now.
Thanks for all
Yvon

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.3.0|
|Visual Studio Code version|1.82.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Bookmarks (Bookmarks): 13.4.1
COBOL (cobol): 9.9.21
Code GPT: Chat & AI Agents (dscodegpt): 2.1.21
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.2
Db2 for IBM i (vscode-db2i): 0.4.1
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.14.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
IBM i Project Explorer (vscode-ibmi-projectexplorer): 1.2.2
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.21.4
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|n/a|
|CCSID|273|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/NOVY4002.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GETNEWLIBL.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv||||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=NOVY4001
CURLIB=NOVY4001
HOME=/home/NOVY400
HOST=pub400.com
LIBLS=GAMES400 QTEMP QGPL
LOGIN=novy400
LOGNAME=novy400
MAIL=/var/spool/mail/novy400
OLDPWD=/home/NOVY400
PASE_USRGRP_LIMITED=N
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/NOVY400
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=130.180.215.74 55239 2222
SSH_CONNECTION=130.180.215.74 55239 185.113.5.134 2222
TZ=<UTC>0
USER=novy400
USERNAME=novy400
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#§$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(novy4002) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPD0032: Not authorized to command CRTLIB in library *LIBL.\nCPF0006: Errors occurred in command.",
    "cwd": "/home/NOVY400"
  },
  {
    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx",
    "code": 2,
    "stderr": "ls: cannot access '/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx': No such file or directory",
    "cwd": "/home/NOVY400"
  }
]
```
</details>

**Comment by sebjulliand** [comment]
Good catch @novy400 . That must be related to a recent change in the way private keys are handled.
For some reason, `privateKeyPath: ""` was written in your settings file.

I'll make sure this doesn't happen and fix the existing settings as well.

**Comment by novy400** [comment]
@worksofliam  and  @sebjulliand  hello I've tested my old connections ,I think It's ok with the old one.

**Comment by sebjulliand** [comment]
@worksofliam you're right!
Well, I updated the settings fix method on startup and I'll fix the underlying cause while I'm at it 😁

**Comment by sebjulliand** [comment]
PR https://github.com/halcyon-tech/vscode-ibmi/pull/1551 is out and it hopefully fixes it all 😁

**Comment by novy400** [comment]
@sebjulliand  thanks !
