### ISSUE TITLE
Source file members read only

### ISSUE THREAD

**Issue by BlancoConsulting** [halcyon-tech/vscode-ibmi#1553]
Source members are locked, or ready only.

Filter "Protected" not checked.
Settings "Read only mode" not checked.

👉🏻 Issue text goes here.

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.3.0|
|Visual Studio Code version|1.82.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Beautify (beautify): 1.5.0
CL (vscode-clle): 1.1.2
COBOL (cobol): 9.9.21
Code Spell Checker (code-spell-checker): 3.0.1
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.2
Comment Anchors (comment-anchors): 1.10.3
Db2 for IBM i (vscode-db2i): 0.4.1
Dev Containers (remote-containers): 0.309.0
ESLint (vscode-eslint): 2.4.2
Emmet (emmet): 1.0.0
Eradani Extension (ec-generators): 0.9.11
Error Lens (errorlens): 3.14.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
Git Graph (git-graph): 1.30.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitHub Copilot (copilot): 1.116.440
GitHub Copilot Chat (copilot-chat): 0.7.1
GitLens — Git supercharged (gitlens): 14.3.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Live Server (LiveServer): 5.7.9
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Remote - Tunnels (remote-server): 1.4.3
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL (remote-wsl): 0.81.4
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|n/a|
|Tech Refresh|n/a|
|CCSID|?|
|SQL|Disabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|
|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|
|git|iconv|GETNEWLIBL.PGM||
|grep|setccsid|||
|ls||||
|md5sum||||
|sort||||
|stat||||
|tar||||
</details>

<details>
<summary>Shell env</summary>

```bash
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/JOHN"
  },
  {
    "command": "ls undefined",
    "code": 2,
    "stderr": "undefined not found",
    "cwd": "/home/JOHN"
  },
  {
    "command": "export BUILDLIB=\"JOHN\" && export CURLIB=\"JOHN\" && export USERNAME=\"john\" && export HOST=\"IBM\" && export HOME=\"/home/JOHN\" && export LIBLS=\"\" && env",
    "code": 1,
    "stderr": "bsh: BUILDLIB=JOHN: is not an identifier",
    "cwd": "/home/JOHN"
  }
]
```
</details>

**Comment by BlancoConsulting** [comment]
When "Enable SQL" checked the library description says "*** NOT FOUND ***", and source files are missing from the object browser filter.  On the other hand, when unchecked the library description appears, and source files also appear with the lock/protected members.


![image](https://github.com/halcyon-tech/vscode-ibmi/assets/77461463/b4b47580-9ec0-4003-a950-0b712151deba)

**Comment by BlancoConsulting** [comment]
DB2 for i Server Component is producing the following error.  Could this be related to the other problems in this issue?

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/77461463/28bc18a7-d464-4d70-8571-fcac06b50db1)

**Comment by worksofliam** [comment]
Please share the contents of your Code for IBM i output channel after the list appears locked. Usually this means a `CHKOBJ` returned something that indicates you don't have access.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by worksofliam** [comment]
Also, what version of IBM i is this?

**Comment by BlancoConsulting** [comment]
Hi Barry, the IBM i version is V7R3M0

Code for IBM i output:

/home/RAMIRO: /QOpenSys/usr/bin/qsh
liblist -d  && liblist -c RAMIRO && liblist -a  && system  "CHKOBJ OBJ(RAMIRO/QCLSRC) OBJTYPE(*FILE) AUT(*UPD)"; if [[ $? -ne 0 ]]; then exit 1; fi
{
    "code": 9,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/RAMIRO: system "DSPFD FILE(RAMIRO/QCLSRC) TYPE(*MBR) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_Bd6IOU9E)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_BD6IOU9E created in library ILEDITOR.\nCPF9862: Member O_BD6IOU9E added to output file O_BD6IOU9E in library ILEDITOR.\nCPF3030: 1 records added to member O_BD6IOU9E in file O_BD6IOU9E in ILEDITOR.",
    "stderr": ""
}

/home/RAMIRO: system "QSYS/CPYTOIMPF FROMFILE(ILEDITOR/O_Bd6IOU9E O_Bd6IOU9E) TOSTMF('/tmp/vscodetemp-O_VoUrYW0w') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPC2958: All records copied from file O_BD6IOU9E in ILEDITOR.",
    "stderr": ""
}

.: system "CPYTOSTMF FROMMBR('/QSYS.lib/RAMIRO.lib/QCLSRC.file/DSORDQT#.mbr') TOSTMF('/tmp/vscodetemp-O_ZyTnC8A5') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPCA082: Object copied.",
    "stderr": ""
}

**Comment by worksofliam** [comment]
@BlancoConsulting Surely there is more than that. You'll need to copy everything in that window, and if it's too big for the issue, stick it into a gist (gist.github.com)

**Comment by BlancoConsulting** [comment]
I reconnected and opened a locked source member.  Here is the Code for IBM i output.

.: echo "This should be the only text!"
{
    "code": 0,
    "signal": null,
    "stdout": "This should be the only text!",
    "stderr": ""
}

.: echo $HOME && cd && test -w $HOME
{
    "code": 0,
    "signal": null,
    "stdout": "/home/RAMIRO",
    "stderr": ""
}

/home/RAMIRO: /QOpenSys/usr/bin/qsh
liblist
{
    "code": 9,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/RAMIRO: system "CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF2111: Library ILEDITOR already exists."
}

/home/RAMIRO: [ -d "/tmp" ]
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/RAMIRO: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
select CHARACTER_CODE_SET_ID from table( QSYS2.QSYUSRINFO( USERNAME => upper('ramiro') ) )
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n                                                   **** Generated from Blue *****",
    "stderr": ""
}

/home/RAMIRO: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
with VARIANTS ( HASH, AT, DOLLARSIGN ) as (  values ( cast( x'7B' as varchar(1) )         , cast( x'7C' as varchar(1) )         , cast( x'5B' as varchar(1) ) ))select HASH concat AT concat DOLLARSIGN as LOCAL  from VARIANTS; 
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n                                                   **** Generated from Blue *****",
    "stderr": ""
}

/home/RAMIRO: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select OS_VERSION || '.' || OS_RELEASE as VERSION from sysibmadm.env_sys_info
/home/RAMIRO: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select max(ptf_group_level) as HIGHEST_DB2_PTF_GROUP_LEVEL from qsys2.group_ptf_info where PTF_GROUP_DESCRIPTION like 'DB2 FOR IBM I%' and ptf_group_status = 'INSTALLED';
/home/RAMIRO: ls undefined
/home/RAMIRO: system "DSPOBJD OBJ(QSYS/*ALL) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_w0pHn75S)"
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "undefined not found"
}

{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n                                                   **** Generated from Blue *****",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n                                                   **** Generated from Blue *****",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_W0PHN75S created in library ILEDITOR.\nCPF9862: Member O_W0PHN75S added to output file O_W0PHN75S in library ILEDITOR.",
    "stderr": ""
}

/home/RAMIRO: system "QSYS/CPYTOIMPF FROMFILE(ILEDITOR/O_w0pHn75S O_w0pHn75S) TOSTMF('/tmp/vscodetemp-O_dN2BQIWI') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPC2958: All records copied from file O_W0PHN75S in ILEDITOR.",
    "stderr": ""
}

/home/RAMIRO: system "DSPOBJD OBJ(QSYS/*ALL) OBJTYPE(*LIB) DETAIL(*TEXTATR) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_VPOUGcQi)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_VPOUGCQI created in library ILEDITOR.\nCPF9862: Member O_VPOUGCQI added to output file O_VPOUGCQI in library ILEDITOR.",
    "stderr": ""
}

/home/RAMIRO: system "QSYS/CPYTOIMPF FROMFILE(ILEDITOR/O_VPOUGcQi O_VPOUGcQi) TOSTMF('/tmp/vscodetemp-O_dr2da29z') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPC2958: All records copied from file O_VPOUGCQI in ILEDITOR.",
    "stderr": ""
}

/home/RAMIRO: system "DSPFD FILE(RAMIRO/Q*) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_jkZ3J1In)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_JKZ3J1IN created in library ILEDITOR.\nCPF9862: Member O_JKZ3J1IN added to output file O_JKZ3J1IN in library ILEDITOR.\nCPF3030: 7 records added to member O_JKZ3J1IN in file O_JKZ3J1IN in ILEDITOR.",
    "stderr": ""
}

/home/RAMIRO: system "QSYS/CPYTOIMPF FROMFILE(ILEDITOR/O_jkZ3J1In O_jkZ3J1In) TOSTMF('/tmp/vscodetemp-O_ZFmxDYnh') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPC2958: All records copied from file O_JKZ3J1IN in ILEDITOR.",
    "stderr": ""
}

/home/RAMIRO: /QOpenSys/usr/bin/qsh
liblist -d  && liblist -c RAMIRO && liblist -a  && system  "CHKOBJ OBJ(RAMIRO/QCLSRC) OBJTYPE(*FILE) AUT(*UPD)"; if [[ $? -ne 0 ]]; then exit 1; fi
{
    "code": 9,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/RAMIRO: system "DSPFD FILE(RAMIRO/QCLSRC) TYPE(*MBR) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_PZPNtUJg)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_PZPNTUJG created in library ILEDITOR.\nCPF9862: Member O_PZPNTUJG added to output file O_PZPNTUJG in library ILEDITOR.\nCPF3030: 1 records added to member O_PZPNTUJG in file O_PZPNTUJG in ILEDITOR.",
    "stderr": ""
}

/home/RAMIRO: system "QSYS/CPYTOIMPF FROMFILE(ILEDITOR/O_PZPNtUJg O_PZPNtUJg) TOSTMF('/tmp/vscodetemp-O_dshGUIK4') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPC2958: All records copied from file O_PZPNTUJG in ILEDITOR.",
    "stderr": ""
}

.: system "CPYTOSTMF FROMMBR('/QSYS.lib/RAMIRO.lib/QCLSRC.file/DSORDQT#.mbr') TOSTMF('/tmp/vscodetemp-O_lNcTuBbi') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPCA082: Object copied.",
    "stderr": ""
}

**Comment by worksofliam** [comment]
@BlancoConsulting i can see a magnitude of issues here, and this is where it's going wrong and explains why it is locked.

```
/home/RAMIRO: /QOpenSys/usr/bin/qsh
liblist -d && liblist -c RAMIRO && liblist -a && system "CHKOBJ OBJ(RAMIRO/QCLSRC) OBJTYPE(*FILE) AUT(*UPD)"; if [[ $? -ne 0 ]]; then exit 1; fi
{
"code": 9,
"signal": null,
"stdout": "",
"stderr": ""
}

```

Can you also share your .profile/.bash_profile here?

Cc @chrjorgensen

**Comment by BlancoConsulting** [comment]
Here is the .profile (don't see .bash_profile):

PATH=/QOpenSys/pkgs/bin:$PATH
export PATH

LIB=RAMIRO
export LIB

if [ -z "$QIBM_USE_DESCRIPTOR_STDIO" ]; then
    # If we're in an SSH session, use bash
    bash
    exit
else
    # If we're in QP2TERM or QSH, no colors + no bash
    PS1="eradani-connect [$(id -un)]> "
fi

**Comment by BlancoConsulting** [comment]
I noticed that "/QOpenSys/usr/bin/qsh" is missing.

**Comment by BlancoConsulting** [comment]
/QOpenSys/usr/bin/qsh does exist.

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/77461463/38165ad5-2115-404d-9534-ae192c0df1b1)

**Comment by BlancoConsulting** [comment]
Is the .profile causing the "/home/RAMIRO: /QOpenSys/usr/bin/qsh" not to work?

**Comment by chrjorgensen** [comment]
Seems like there is a problem with the library list? Empty liblist -d and liblist -a...??

**Comment by BlancoConsulting** [comment]
Why the following command not working?

/home/RAMIRO: /QOpenSys/usr/bin/qsh
liblist
{
"code": 9,
"signal": null,
"stdout": "",
"stderr": ""
}

This is the same command on a different machine.

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/77461463/2faa74b9-dbe7-44af-927f-5057eeeaec1f)

**Comment by BlancoConsulting** [comment]
This solved the problem with locked source members.

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/77461463/c42b52ae-d071-4eb0-a8c8-e1c5726d688c)
