### ISSUE TITLE
Copy library fails trying to use CPYOBJ command

### ISSUE THREAD

**Issue by edmundreinhardt** [halcyon-tech/vscode-ibmi#1565]
It appears that the action for copying a library is using CPYOBJ which is failing as *LIB is not vaid for parameter OBJTYPE
The message CPD0084 is shown.
We probably need a unique action for copying a library when showing libraries in the QSYS Object Browser

![image](https://github.com/halcyon-tech/vscode-ibmi/assets/11184579/2dbb72b9-0833-42a9-b51f-aa3f3cae3f26)

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.3.1|
|Visual Studio Code version|1.82.2|
|Operating System|darwin_arm64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.2
Db2 for IBM i (vscode-db2i): 0.5.0
ESLint (vscode-eslint): 2.4.2
Emmet (emmet): 1.0.0
Extension Authoring (extension-editing): 1.0.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitLens — Git supercharged (gitlens): 14.3.0
IBM i Project Explorer (vscode-ibmi-projectexplorer): 1.2.2
JSON Language Features (json-language-features): 1.0.0
Live Share (vsliveshare): 1.0.5883
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.21.4
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
undefined (vscode-sourceorbit): 1.1.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|n/a|
|Tech Refresh|n/a|
|CCSID|65535|
|SQL|Disabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/ILEDITOR.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=BOBTEST
CURLIB=BOBTEST
HOME=/home/REINHARD
HOST=p8adt05.rch.stglabs.ibm.com
LIBLS=PAY_BR_FIX PAYROLLORG QTEMP RPGUNIT TDD_ER
LOGIN=reinhard
LOGNAME=reinhard
MAIL=/var/spool/mail/reinhard
OLDPWD=/home/REINHARD
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/REINHARD
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=9.108.126.57 62336 22
SSH_CONNECTION=9.108.126.57 62336 9.5.12.241 22
TZ=<UTC>0
USER=reinhard
USERNAME=reinhard
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/REINHARD"
  }
]
```
</details>

**Comment by edmundreinhardt** [comment]
Important detail, this was a filter on QSYS and shows libraries

**Comment by sebjulliand** [comment]
I'll port back what I did for Project Explorer.

**Comment by sebjulliand** [comment]
Nevermind, this is a simple bug. The command already handles the case where a library is copied. But the test on the object type doesn't work anymore, probably because of some changes made during the browser's TS conversion.
