### ISSUE TITLE
"Get started" link no longer works

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#1575]
Under "HELP AND SUPPORT" clicking "Get stated" give a 404.
It tried to link to https://halcyon-tech.github.io/docs/#/
Presumably since repository is now owned by "codefori" the link just needs to be changed.

<hr />

⚠️ **REMOVE THIS LINE AND ANY SENSITIVE INFORMATION BELOW!** ⚠️

|Context|Version|
|-|-|
|Code for IBM i version|2.3.1|
|Visual Studio Code version|1.82.2|
|Operating System|win32_x64|

<details>
<summary>Active extensions</summary>

```
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.3.2
Db2 for IBM i (vscode-db2i): 0.5.0
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.14.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitLens — Git supercharged (gitlens): 14.3.0
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
Microsoft Account (microsoft-authentication): 0.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
Overtype (overtype): 0.5.0
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
WSL: Recommender (remote-wsl-recommender): 0.0.19
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|n/a|
|CCSID|37|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin|/QSYS.lib/LENNONS2.lib|/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|GENCMDXML.PGM|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv|GETNEWLIBL.PGM|||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=LENNONSB
CURLIB=LENNONSB
HOME=/home/LENNONS
HOST=pub400.com
IFS_LIB=LENNONSB
IFS_SRCPF=VSCODE
LIB1=LENNONSB
LIBLS=LENNONS1 LENNONSB QGPL QTEMP QIWS
LOGIN=lennons
LOGNAME=lennons
MAIL=/var/spool/mail/lennons
OLDPWD=/home/LENNONS
PASE_USRGRP_LIMITED=N
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/LENNONS
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
SSH_CLIENT=71.63.120.199 58540 2222
SSH_CONNECTION=71.63.120.199 58540 185.113.5.134 2222
TZ=<UTC>0
USER=lennons
USERNAME=lennons
_=/QOpenSys/pkgs/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#§$"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "system \"CRTLIB LIB(LENNONS2) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPD0032: Not authorized to command CRTLIB in library *LIBL.\nCPF0006: Errors occurred in command.",
    "cwd": "/home/LENNONS"
  },
  {
    "command": "system \"DLTOBJ OBJ(LENNONS2/O_*) OBJTYPE(*FILE)\"",
    "code": 255,
    "stderr": "CPF2125: No objects deleted.",
    "cwd": "/home/LENNONS"
  }
]
```
</details>

**Comment by sebjulliand** [comment]
Yep!
This will be fixed by this PR: https://github.com/codefori/vscode-ibmi/pull/1571
