### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by eduardomarco** [halcyon-tech/vscode-ibmi#164]
**Describe the bug**
I can´t connect to IBM I, i don´t have any problem with ACS connections
**To Reproduce**
1. Go to 'Connect to an IBM i'
2. Fill the fields.
2. Click on 'Connect'
Not connected to 10.213.5.5  Max identification string size exceed
**Expected behavior**
Connect to an IBM I

**Screenshots**

**Environment (please complete the following information):**
 - Extension version [V0.5.3)
 - IBM i OS version [e.g. 7.x2

**Additional context**
![WhatsApp Image 2021-06-08 at 10 48 58](https://user-images.githubusercontent.com/26776921/121353020-cc069380-c903-11eb-9d9e-ddfaffa32ec3.jpeg)

**Comment by worksofliam** [comment]
@eduardomarco Please fill out the issue correctly, especially the steps to reproduce. Thanks.

**Comment by worksofliam** [comment]
@eduardomarco Were you able to connect to the system previously? Or has it just never worked.

I have never seen this error before.

**Comment by eduardomarco** [comment]
> @eduardomarco Were you able to connect to the system previously? Or has it just never worked?
> 
> I have never seen this error before.

With VS code never connect. I am connecting with ACS without problems

**Comment by worksofliam** [comment]
@eduardomarco is the SSH daemon running? Are you able to connect with ssh?

**Comment by eduardomarco** [comment]
> @eduardomarco is the SSH daemon running? Are you able to connect with ssh?

I can´t connect.

**Comment by prachaya2639** [comment]
I have the same problem.

![image](https://user-images.githubusercontent.com/61548379/124085804-9d9b5480-da7a-11eb-8ba5-87f036a16a53.png)
