### ISSUE TITLE
Update searches to support standard strings

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#165]

**Comment by SJLennon** [comment]
I've been experimenting with the search feature.
I wanted to find RPG source with **free.  Searching in the Member Browser.
![image](https://user-images.githubusercontent.com/67484051/121382706-ded59400-c914-11eb-8484-eb9333e7c194.png)
Results looked like this, with a lot of hits that were not **free:
![image](https://user-images.githubusercontent.com/67484051/121382939-13e1e680-c915-11eb-8381-6260293d11c1.png)
I saw from the issues that you were using grep, so I tried escaping the *:
![image](https://user-images.githubusercontent.com/67484051/121383299-57d4eb80-c915-11eb-803d-b6448ad98978.png)
But I still get the same results--"10 results - 3 files".

I tried searching in the IFS Browser.  _There using \\*\\*free works as expected._ and I don't get spurious hits.

Not an expert on regular expressions, so not sure what the issue is in the source file search.

I think search needs more documentation.  Be happy to update the documentation when search is stable. 
@worksofliam

**Comment by worksofliam** [comment]
That is totally weird.

![image](https://user-images.githubusercontent.com/3708366/121387908-0a5a7d80-c919-11eb-860b-8e87b3047d3d.png)

![image](https://user-images.githubusercontent.com/3708366/121387927-0f1f3180-c919-11eb-895e-b4ecc8257849.png)

**Comment by worksofliam** [comment]
it seems like the asterisks are ignored.

![image](https://user-images.githubusercontent.com/3708366/121388423-7c32c700-c919-11eb-8d31-66d7e801f374.png)

![image](https://user-images.githubusercontent.com/3708366/121388479-85239880-c919-11eb-894b-94d2a7058f7d.png)

Unless I specify `\\*\\*FREE`:

![image](https://user-images.githubusercontent.com/3708366/121388627-a1273a00-c919-11eb-9d4d-438fcc6bfd44.png)

**Comment by worksofliam** [comment]
I am going to use this issue as a to-do item from now. Thanks for this info @SJLennon!

* [ ] Update docs to tell users that regex can be provided in the search
* [ ] Automatically apply a second backtick so users don't have to that (like standard regex). E.g. `\*\*free` (correct) vs `\\*\\*free` (not correct)

**Comment by SJLennon** [comment]
I tried \\\\*\\\\*FREE and I still get the spurious hits.  On pub400, of course.
![image](https://user-images.githubusercontent.com/67484051/121389658-a769e600-c91a-11eb-9434-132e06ab64b5.png)
Result:
![image](https://user-images.githubusercontent.com/67484051/121389827-c9636880-c91a-11eb-8b60-3a5942e3ddac.png)
@worksofliam

**Comment by SJLennon** [comment]
Another curiosity when searching a source file.
If I have code like this:
```
          exec sql fetch DataCur into
                             :FetchData.STATE,
                             :FetchData.NAME
           ;
```
and I want to search for `.STATE`.  According to my Unix book, there are a number characters which have special significance to grep, including the period.  So searching for .STATE gives a lot of spurious hits.

However, if I search for `\.state` then I get an error:
![image](https://user-images.githubusercontent.com/67484051/121394710-9c658480-c91f-11eb-9616-364e4cacc7e6.png)
This is what I see in the Output tab:
![image](https://user-images.githubusercontent.com/67484051/121395010-f36b5980-c91f-11eb-8ded-b249a0ba45e5.png)

Same error if I search for `data\.`

@worksofliam

**Comment by worksofliam** [comment]
But what about if you use `\\.state` and `data\\.`?

**Comment by SJLennon** [comment]
No luck.  Still get the error.
![image](https://user-images.githubusercontent.com/67484051/121397268-2ca4c900-c922-11eb-87a5-8b2e667dedb6.png)
@worksofliam

**Comment by worksofliam** [comment]
Weird how we get different results on the same utility.

**Comment by SJLennon** [comment]
Again, maybe something quirky on pub400.  Or maybe it's me doing something wrong.  I'll try again tomorrow.

I have a cloned copy of the repository.  Should that make any difference?
@worksofliam

**Comment by worksofliam** [comment]
No difference to my knowledge!

**Comment by SJLennon** [comment]
This issue is closed, but I'm not clear if I can now search for  `**free`.  Or if I need to instead search for `\*\*free`.  Or maybe for` \\*\\*free`.  Or if this is an enhancement deferred to a subsequent release.

I ask because on 0.5.7 I still seem to be having issues.

Again, it's not impeding anything that I'm doing--just looking for clarity.
@worksofliam

**Comment by SJLennon** [comment]
@worksofliam On 0.5.8 still having issues with search.
Given a test source member like this:
```
**free
      // this code is is not **free: xxx
      /free
       WS_DspSfl = *off;
       write TEST1C1;
      /end-free
      // might it be just *free
      // free* is just another word
      // calc discount as free*custpct
```
Search the source file for `-free`
I get this:
![image](https://user-images.githubusercontent.com/67484051/122680021-516b2d00-d1bb-11eb-999a-fc11ec2f2bc5.png)
Code for IBM i output show this:
```
/home/lennons/: echo "/usr/bin/grep -in '-free' /QSYS.LIB/LENNONS1.LIB/XPR_2.FILE/*" | /QOpenSys/usr/bin/qsh
{
    "code": 2,
    "signal": null,
    "stdout": "",
    "stderr": "grep: 001-2103 Error found getting information for file or directory ree. No such path or directory.\ngrep: 001-2107 Error found processing pattern file ree."
}
```
Possibly any search starting with `-` is problematic.

Searching for `\-free` also fails:
![image](https://user-images.githubusercontent.com/67484051/122680247-449b0900-d1bc-11eb-9974-380f68227975.png)
But with a different error in Code for IBM i:
```
/home/lennons/: echo "/usr/bin/grep -in '\\\"-free' /QSYS.LIB/LENNONS1.LIB/XPR_2.FILE/*" | /QOpenSys/usr/bin/qsh
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": ""
}
```
And searching for `**free` still gives spurious hits.
![image](https://user-images.githubusercontent.com/67484051/122680437-1f5aca80-d1bd-11eb-832b-c429a5ce829f.png)

So does searching for `free*`.

Again, not urgent for me, just providing feedback.

**Comment by worksofliam** [comment]
@SJLennon Hey - do you by any chance remember what the fix is here? I wonder if you would know what I would need to change in the code?

https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/api/Search.js#L17

https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/api/Search.js#L105

**Comment by SJLennon** [comment]
@worksofliam Regex, to me, is a bit like APL - a write only language.  
Shell programming isn't something I have a lot of experience with.
So I may not be much of a help.
I don't recall that we ever came up with a solution. I've done a little experimenting with grep searching for **free, this seems to give the correct results:
`/usr/bin/grep -in '\*\*free' /QSYS.LIB/LENNONS1.LIB/DATE_UDF.FILE/*`
Haven't come up with anything for .state.

**Comment by SJLennon** [comment]
@worksofliam Don't know if this helps, but to find .state, this grep works:
`/usr/bin/grep -in '\.state' /QSYS.LIB/LENNONS1.LIB/I5250_SUBF.FILE/*`

**Comment by worksofliam** [comment]
@SJLennon Okay, so the fix is to not search as regex for now and search as a plain string. I will do that

**Comment by SJLennon** [comment]
@worksofliam I think that would be a good idea..  I think you have to quote all these characters to keep grep happy, if I read my O'Reilly Unix book correctly:
```
.   *  -   $  [  ]    {  }  \
 ```

Then later add regex as an option if there is a request for it.  Like VS Code search does, allowing match case, whole word and regex. Though that might be be a lot of work...  Don't suppose there is a VS Code api you can plug into?  Or maybe SQL could do it.

**Comment by worksofliam** [comment]
@SJLennon Great! That will come out in 1.0.0.

Regex support can easily come later. About the API: sadly not. I would have used it if possible, but it's not yet :( 

https://github.com/microsoft/vscode/issues/59921

**Comment by SJLennon** [comment]
@worksofliam FWIW:  I found a -F grep option, which doesn't do any regex interpretation of the string.  Might be a simpler approach.
https://stackoverflow.com/questions/37100931/what-is-the-meaning-of-the-f-option-in-grep-manual
Seems to work in QSH.  Example searching for .state, first without -F, second with it:
```
> /usr/bin/grep -in '.state' /QSYS.LIB/LENNONS1.LIB/A_CONV.FILE/*                                    
  /QSYS.LIB/LENNONS1.LIB/A_CONV.FILE/FAILS_BAS.MBR:25:      *=== SQL State Constants ================
  /QSYS.LIB/LENNONS1.LIB/A_CONV.FILE/FAILS_C.MBR:29:        //=== SQL State Constants ===============
  /QSYS.LIB/LENNONS1.LIB/A_CONV.FILE/IPR821R1.MBR:157:      *=== SQL State Constants ================
  /QSYS.LIB/LENNONS1.LIB/A_CONV.FILE/IPR821R1.MBR:1186:      *       Thus there are 4 SQL statements,
  /QSYS.LIB/LENNONS1.LIB/A_CONV.FILE/METACHAR.MBR:16:.state                                          

  (/home/LENNONS)->                                                                                  
> /usr/bin/grep -inF '.state' /QSYS.LIB/LENNONS1.LIB/A_CONV.FILE/*                                   
  /QSYS.LIB/LENNONS1.LIB/A_CONV.FILE/METACHAR.MBR:16:.state                                          
  (/home/LENNONS)->           
```

**Comment by SJLennon** [comment]
@worksofliam I've just started with v1.0.0.  Nice touch with the new Help and Support feature! 

Unfortunately,  I'm still confused about the search.  Works for simple text and opens nicely in the new approach.  
But it still seems to get confused with special characters.
If I search simply for . then \\ is found.
If I search for .. it finds nothing.
Curiously, if I search for \\\\. then  \\\\ is found.
Searching for * gives false hits
![image](https://user-images.githubusercontent.com/67484051/155173565-b8dfc1ea-9db9-41e6-9eca-d4ba267b056a.png)
searching for - or for -- finds nothing
searching for ( or  for ) finds nothing.
There are other oddities.

May I suggest that you have three search options:
1) Search.
2) Search, case sensitive.
3) Search with Regex.

For 1) it would be grep -inF
For 2) it would be grep -nF
For 3) it would be deferred since it seems like it needs some work and or experimentation.

I have this test member that I created recently to experiment with grep, just in case it is of use.
```
period      .                one
period      ..               two
asterisk    *                one
asterisk    **               two
dash        -                one
dash        --               two
dollar      $                one
dollar      $$               two
back slash  \                one
back slash  \\               two
set begin   [                one
set begin   [[               two
set end     ]                one
set end     ]]               two
.state
$dollar$
[array]
array
{object}
object
{{
}}
{}
(thingy)        with
thingy          without
-- SQL comment

```

**Comment by worksofliam** [comment]
@SJLennon Just shipped 1.2.0, which will use -F to search with plaintext and not regex.

**Comment by SJLennon** [comment]
@worksofliam 

Regrettably, -F still seems to have some inconsistencies.  (Testing on PUB400.)

Search for ]]
Returns both ]] and }}
![image](https://user-images.githubusercontent.com/67484051/156798060-83ff128e-e3c4-4f95-8ef7-3abb7ff27c1c.png)

But run the same command in QSH it returns only ]], though it shows as ||.
![image](https://user-images.githubusercontent.com/67484051/156797941-296b5a42-543b-43ea-a950-3f58c123ba45.png)

Searching for $dollar$ returns no results;
![image](https://user-images.githubusercontent.com/67484051/156800379-a2ef21db-160b-4004-9deb-fbb6bbce02f3.png)

Running the same command in QSH yields three results, but should be only one:
![image](https://user-images.githubusercontent.com/67484051/156800717-92951dbf-d297-4729-888b-0a4a9114997a.png)

Searching for a string with a blank in it gives an error:
![image](https://user-images.githubusercontent.com/67484051/156805900-9cb59c8b-1e9e-4543-8e41-885f565accfb.png)

But running the same search in QSH yields a result:
![image](https://user-images.githubusercontent.com/67484051/156806094-b4c721d4-b13a-4a27-9fdc-0172b796cc15.png)

I ran all the QSH commands above from a job that had CCSID 37. PUB400 is CCSID 273.  
If I run QSH in a CCSID 273 job, results can be different.  For example, if I search for ]] I get no results:
![image](https://user-images.githubusercontent.com/67484051/156809904-557d0fda-4dc2-4dc6-b9ec-eefc4a9e855b.png)

Looks like searching is becoming extremely tricky.  Don't know how QSH handles CCSID.  You are using QSH to run the searches?  I got no good results trying to duplicate them in QP2TERM.

Taking a break for lunch...

**Comment by worksofliam** [comment]
@SJLennon Ok! Next thing to try is passing the user string in as standard in, which might solve the issues with those special characters.

**Comment by worksofliam** [comment]
@SJLennon There must be some weird setup. Looks good to me.. but I will continue to search.

![image](https://user-images.githubusercontent.com/3708366/156825776-c91b159c-a431-4fcf-819a-292cedc3e6dd.png)

With a space:

![image](https://user-images.githubusercontent.com/3708366/156825868-5461a18e-c9bd-4f0a-aa8a-4d66f8600ddb.png)

**Comment by SJLennon** [comment]
@worksofliam 
Definitely odd, because I just restarted VS Code and tried searching for ccc ddd  again, and it worked this time. Is it possible there is a memory leak or corruption in VS Code or the extension?  Seems like recently I've seen "oddities" that I can't replicate but unfortunately cannot remember.

And what do you make of this QSH search & failure looking for "-- " (two dashes and a blank0
![image](https://user-images.githubusercontent.com/67484051/156830779-1a52a2ad-513d-4fed-876b-1ba3adb31e1e.png)

And it seem to me that somewhere this morning I managed to consistently make QSH go away and never return, but I can't replicate that again now.  Maybe it's PUB400s proclivity to constantly adjust job priorities.

**Comment by worksofliam** [comment]
@SJLennon If it worked after restarting VS Code, likely just needed a reload to get the latest version?

Not sure about `--`, but I can look into that also.

**Comment by SJLennon** [comment]
@worksofliam I don't think so, because I loaded VS Code and looked at extension and saw "reload required" and clicked it. Check extensions again an no reloads were required.  But I'm seeing the -F option in use, so wouldn't confirm I had the latest version?

**Comment by worksofliam** [comment]
Odd. Definitely sounds like some shell oddities.

**Comment by SJLennon** [comment]
@worksofliam Additional info in QSH on PUB400, in case it is useful:
If I search for ** in a CCSID 273 job it finds all lines:
![image](https://user-images.githubusercontent.com/67484051/156834567-06f04d0e-8a12-4e37-a24e-aa65d79c9fee.png)
If I do the same seach in a CCSID 37 job, it works as expected:
![image](https://user-images.githubusercontent.com/67484051/156834737-b06f5f57-7899-433d-8b1d-7f680ea23d60.png)

In a CCSID 273 job,  seemingly searching for any number of *, returns all lines.  Looks like the * is just ignored and gives the same result as no pattern.

Very strange...

Again, this is not holding me up.  It just started when I originally tried to search for **free.  Which, incidentally, still produces spurious hits in the extension, though it does work correctly in QSH in a CCSID 37 job, but gives spurious hits in a CCSID 273 job.

**Comment by SJLennon** [comment]
QSH links for reference
Qshell command language features: https://www.ibm.com/docs/en/i/7.3?topic=tutorial-qshell-command-language-features
Patterns: https://www.ibm.com/docs/en/i/7.3?topic=expansions-patterns
Programming Qshell (PDF); https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwingd6TrbT2AhWioXIEHUfNDFcQFnoECAIQAQ&url=https%3A%2F%2Fwww.ibm.com%2Fdocs%2Fssw_ibm_i_73%2Frzahz%2Frzahzpdf.pdf&usg=AOvVaw38PKiCcc_X3x6f6f0ZlCzP

From what I can determine, the meta characters `!, *, ?, and [` are found if you use the -F option .
Testing in QSH _on the green screen_ confirms this, e.g.,
this works:
`> /usr/bin/grep -in -F '[' /QSYS.LIB/LENNONS1.LIB/SEARCH.FILE/*`
but this fails:
`> /usr/bin/grep -in  '[' /QSYS.LIB/LENNONS1.LIB/SEARCH.FILE/*`

One other quirk I noticed on back slash on the green screen.
This works with single quotes:
`> /usr/bin/grep -in -F '\' /QSYS.LIB/LENNONS1.LIB/SEARCH.FILE/*`
But doesn't find anything with double quotes:
`> /usr/bin/grep -in -F "\" /QSYS.LIB/LENNONS1.LIB/SEARCH.FILE/*`
@worksofliam
