### ISSUE TITLE
Open search results in readonly document

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#166]
Further experiments.
1) Search results are show in a tab.  When you close it you get a save dialog:
![image](https://user-images.githubusercontent.com/67484051/121387158-77b9de80-c918-11eb-81be-ba5907b8768a.png)
Not a show stopper, but would be nice if it could be avoided.

2) Subsequent searches add to the open Results tab.  I kind of expected them to be in a separate tab.
![image](https://user-images.githubusercontent.com/67484051/121387708-e4cd7400-c918-11eb-8e9d-afb67863e65e.png)
@worksofliam

**Comment by worksofliam** [comment]
Please keep all your findings in a single issue, thanks!

**Comment by worksofliam** [comment]
Yes, for now, it will continue to open in its own unsaved text document. I could implement a textDocumentProvider but that does add a tad bit of complexity. I don't have a ton of time to work on this right now, but I am going to fix up the issue title to match the enhancement.

**Comment by SJLennon** [comment]
"Please keep all your findings in a single issue, thanks!"

Sorry.  I thought that one issue would be too large.

"edit: i would recommend updating the topmost comment with all this info"

Not sure that this means.

You back in the UK or still in NC?

Sam


________________________________

**Comment by worksofliam** [comment]
I've wanted this for a while, but there is a blocker.

https://github.com/microsoft/vscode/issues/4873

**Comment by worksofliam** [comment]
@SJLennon The attached PR will solve this issue. Check out the PR for a screenshot.

**Comment by worksofliam** [comment]
We no longer use documents for the results.
