### ISSUE TITLE
Use decoration commands instead of classic links in search results

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#167]
I wanted to open the source from the search. Initially it didn't seem obvious.  But I can follow the link and it opens the file! Great feature 😃 .  
Might not be intuitive to those new to VS Code.
![image](https://user-images.githubusercontent.com/67484051/121388385-73da8c00-c919-11eb-9f8c-a7b732e93079.png)
I don't have huge source files, but search seems pretty responsive.  Neat!
@worksofliam

**Comment by worksofliam** [comment]
Right now, this is the only way we can open-source members and stream files from TextDocuments without writing a ton of code to make them use VS Code decorations instead. I do not plan on doing this right now.

**Comment by SJLennon** [comment]
I think the current approach ctrl-click to follow the link is quite functional, once you know about it.  Definitely works for me.
@worksofliam
