### ISSUE TITLE
Unable to open files with a '#' in the name

### ISSUE THREAD

**Issue by onewheelonly** [halcyon-tech/vscode-ibmi#169]
**Describe the bug**
The extension appears unable to open files that contain a '#' in the name. From some experimenting, this seems to include:

- A '#' in the containing library, file or member name
- A '#' in the path of a stream file, (both file and directory names)

Trying to open such a file doesn't result in any error messages. The editor just doesn't load.

**To Reproduce**
Find (or create if necessary) a source file with a '#' in the name and attempt to open it.

**Expected behavior**
The file is loaded into the editor.

**Environment (please complete the following information):**
 - Extension version 0.5.3
 - IBM i OS version 7.4

**Additional context**
I've had a little look at the code but couldn't see any obvious reason. This looked like it might be the relevant bit?

https://github.com/halcyon-tech/vscode-ibmi/blob/67cb13add499c5d1cdbea9f74df827b4ad43375f/src/Instance.js#L241

My expectation is it is probably not being escaped somewhere and being treated as a comment in a shell command. Hopefully that's not in the VS Code internals!

Our change management solution uses '#' in the library names, so a solution would very useful 🙂

**Comment by worksofliam** [comment]
I believe this is a bug related to running SSH commands. I also think I know the fix. Will keep you posted!

**Comment by worksofliam** [comment]
The issue was actually with the VS Code API and how it treats paths with the pound sign / hashtag.

See the fragment property here: https://code.visualstudio.com/api/references/vscode-api#Uri

A fix is coming.

**Comment by worksofliam** [comment]
Will be available in 0.5.5 
![image](https://user-images.githubusercontent.com/3708366/121603243-740c8180-ca16-11eb-90ed-46bea0658ea6.png)
