### ISSUE TITLE
More compile defaults

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#17]
We're looking for some more compile defaults. Right now we only have RPGLE.

We're looking for defaults for the following extensions:

* [x] RPGLE, SQLRPGLE
* [x] CLLE, CL, CLP
* [ ] CBBLE, COBOL, CBL
* [ ] C
* [ ] CPP

See this link for an example, and also where to add more defaults: https://github.com/halcyon-tech/code-for-ibmi/blob/master/package.json#L126

**Comment by thebeardedgeek** [comment]
I added CLLE and CLP, which we just committed in version 0.0.7. Thanks @worksofliam

**Comment by worksofliam** [comment]
@thebeardedgeek I ticked it off. Thanks!

**Comment by adeanbd** [comment]
Hi, Georges Kopp here. 
The COBOL compile default needs a step before the creation of the PGM already existing.
My suggestion is to add in setting.json section "code-for-ibmi.actions":   
         {
            "type": "member",
            "extensions": [
                "CBLLE",
                "CBL"
            ],
            "name": "Create Module CBLLE (CRTCBLMOD)",
            "command": "CRTCBLMOD MODULE(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*SOURCE) DBGVIEW(*SOURCE)"
        },

**Comment by adeanbd** [comment]
Hi, Georges Kopp from here.
The COBOL SQL compile default needs to prepare a definition too. I'm on it.

**Comment by adeanbd** [comment]
Hi, Georges Kopp from Adean here.
The COBOL compile default may need a direct step as suggested below.
My suggestion is to add in setting.json section "code-for-ibmi.actions":
{
"type": "member",
"extensions": [
"CBLLE",
"CBL"
],
"name": "Create PGM 'All-in-One' CBLLE (CRTBNDCBL)",
"command": "CRTBNDCBL (&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*SOURCE) DBGVIEW(*SOURCE)"
},

**Comment by worksofliam** [comment]
Hi @adeanbd!

Thanks for your comment. Might I suggest you create a PR to add the new default? It can be added in the `package.json` file.

**Comment by adeanbd** [comment]
Hi @worksofliam, thank you for your consideration but honestly I have no idea how to do it!
May I ask for your help on this?

**Comment by adeanbd** [comment]
Hi @worksofliam,
Pull request done!
May I ask which is the next step?
Thank you!

**Comment by worksofliam** [comment]
This has gone stale so I will close it.
