### ISSUE TITLE
Is there a way to open a Source Member directly without navigating through the Member Browser?

### ISSUE THREAD

**Issue by mahoneyl** [halcyon-tech/vscode-ibmi#170]
Hi guys,

I'm looking for a way to directly open a source member without needing to scroll through the member browser and click on one. 

In RDi this can be achieved with the hotkey ctrl+alt+q which pulls up a window like this
![image](https://user-images.githubusercontent.com/35392006/121551047-e9576280-c9d4-11eb-902f-63784267ede4.png)

Does there currently exist a way to do this with CODE for IBM i? If not could it be considered for a feature addition? Sometimes a Source File can contain a ton of members and it can take some time to scroll through and pinpoint the one I need to open.

Thanks for your help, this extension is awesome!

**Comment by worksofliam** [comment]
We can absolutely add this. Thanks!

**Comment by worksofliam** [comment]
@mahoneyl This is being worked on. It will be out sometime in the next few days.

**Comment by mahoneyl** [comment]
You just rocked my socks off. Thanks for your help!

**Comment by SJLennon** [comment]
FWIW: You can search in the member browser simply by clicking and typing.  That might work for you for now.
Example:
I clicked on the scroll bar and that highlights the browser in blue:
![image](https://user-images.githubusercontent.com/67484051/121702490-ed9c8200-ca9f-11eb-9b5e-b6a8d3a769d7.png)
I have a member named usphdr.rpgle, which is further down the browser.  It I start typing and enter usp it highlights and positions, thus:
![image](https://user-images.githubusercontent.com/67484051/121701753-399af700-ca9f-11eb-841f-d69ab115f8dc.png)
You get rid of the filter by hovering and clicking the X:
![image](https://user-images.githubusercontent.com/67484051/121702801-318f8700-caa0-11eb-8423-60d56ec2c09c.png)
@mahoneyl

**Comment by mahoneyl** [comment]
> FWIW: You can search in the member browser simply by clicking and typing. That might work for you for now.
> Example:
> I clicked on the scroll bar and that highlights the browser in blue:
> ![image](https://user-images.githubusercontent.com/67484051/121702490-ed9c8200-ca9f-11eb-9b5e-b6a8d3a769d7.png)
> I have a member named usphdr.rpgle, which is further down the browser. It I start typing and enter usp it highlights and positions, thus:
> ![image](https://user-images.githubusercontent.com/67484051/121701753-399af700-ca9f-11eb-841f-d69ab115f8dc.png)
> You get rid of the filter by hovering and clicking the X:
> ![image](https://user-images.githubusercontent.com/67484051/121702801-318f8700-caa0-11eb-8423-60d56ec2c09c.png)
> @mahoneyl

Thanks! That definitely helps

**Comment by mahoneyl** [comment]
@worksofliam Thank you for adding this! This feature really helps a bunch. I really like the LIB/SOURCEPF/MEMBER notation to quickly navigate and open the files I need.

**Comment by mlstoppa** [comment]
@mahoneyl I tried your suggestion but when I click on the scroll bar the member browser pane doesn't get surrounded by the blue border and so I can't simply start typing to have the names filtered.

@worksofliam 
Hi Liam, I was looking for the very same feature, but I don't see any LIB/SOURCEPF/MEMBER notation to use for the scope.

Am I doing something wrong? I am running v0.6.3 version.

Thank you
