### ISSUE TITLE
Library list being set in reverse order when compiling

### ISSUE THREAD

**Issue by richardm90** [halcyon-tech/vscode-ibmi#1875]
This took me a while to work out what was going on but when checking the Code for IBM i: connection output it dawned on me what the problem was. I'm guessing this is a a new problem as I'm sure it would have come to light before now.

I created a simple example, this is my connection library list.

![image](https://github.com/codefori/vscode-ibmi/assets/7809440/a51ac495-6933-40a8-a58f-a24ebe379d43)

When I compile my source member this is the command from the output panel.

`liblist -d QGPL QTEMP && liblist -c QGPL && liblist -a RMTEMP QGPL QTEMP && system  "CRTBNDRPG PGM(RMTEMP/TEST01) SRCFILE(RMTEMP/QRPGLESRC) OPTION(*EVENTF) REPLACE(*YES)"`

I think the `liblist -a RMTEMP QGPL QTEMP` is the problem.

If I run the command manually from a command line this is what I get.

```shell
$ liblist
QSYS        SYS  
QSYS2       SYS  
QHLPSYS     SYS  
QUSRSYS     SYS  
QSHELL      PRD  
$ liblist -a RMTEMP QGPL QTEMP
CPC2196: Library RMTEMP added to library list.
CPC2196: Library QGPL added to library list.
CPC2196: Library QTEMP added to library list.
$ liblist
QSYS        SYS  
QSYS2       SYS  
QHLPSYS     SYS  
QUSRSYS     SYS  
QSHELL      PRD  
QTEMP       USR  
QGPL        USR  
RMTEMP      USR  
$ 
```
As you can see library RMTEMP is added to the end of the library list.

I don't think it would be a factor but I am deliberately slightly behind the current version of the RPGLE (vscode-rpgle) extension.

<hr />

|Context|Version|
|-|-|
|Code for IBM i version|2.7.0|
|Visual Studio Code version|1.86.2|
|Operating System|linux_x64|

<details>
<summary>Active extensions</summary>

```
COBOL (cobol): 10.2.21
Code for IBM i Walkthroughs (vscode-ibmi-walkthroughs): 0.4.0
Db2 for IBM i (vscode-db2i): 0.7.0
ESLint (vscode-eslint): 2.4.4
Emmet (emmet): 1.0.0
Error Lens (errorlens): 3.16.0
Git (git): 1.0.0
Git Base (git-base): 1.0.0
GitHub (github): 0.0.1
GitHub Authentication (github-authentication): 0.0.2
GitLens — Git supercharged (gitlens): 14.8.2
IBM i Notebooks (vscode-ibmi-notebooks): 0.0.6
IBM i Project Explorer (vscode-ibmi-projectexplorer): 2.6.4
IntelliCode (vscodeintellicode): 1.2.30
IntelliCode API Usage Examples (intellicode-api-usage-examples): 0.2.8
JSON Language Features (json-language-features): 1.0.0
Merge Conflict (merge-conflict): 1.0.0
NPM support for VS Code (npm): 1.0.1
Node Debug Auto-attach (debug-auto-launch): 1.0.0
RPGLE (vscode-rpgle): 0.26.0
TODO Highlight (vscode-todo-highlight): 1.0.5
TypeScript and JavaScript Language Features (typescript-language-features): 1.0.0
```
</details>

<hr />

<details>
<summary>Remote system</summary>

|Setting|Value|
|-|-|
|IBM i OS|V7R5M0|
|Tech Refresh|3|
|CCSID|1146|
|Default CCSID|1146|
|SQL|Enabled
|Source dates|Disabled

### Enabled features

|/QOpenSys/pkgs/bin|/usr/bin||/QSYS.LIB|/QIBM/ProdData/IBMiDebugService/bin|
|-|-|-|-|-|
|bash|attr|ILEDITOR.GETNEWLIBL|QZDFMDB2.PGM|startDebugService.sh|
|chsh|iconv||||
|git|setccsid||||
|grep|||||
|ls|||||
|md5sum|||||
|sort|||||
|stat|||||
|tar|||||
|tn5250|||||
</details>

<details>
<summary>Shell env</summary>

```bash
BUILDLIB=QGPL
CURLIB=QGPL
HOME=/home/RICHARD
HOST=myibmi.com
LC_ALL=EN_GB.UTF-8
LIBLS=QTEMP QGPL RMTEMP
LOGIN=richard
LOGNAME=richard
MAIL=/var/spool/mail/richard
OLDPWD=/home/richard
PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PWD=/home/RICHARD
SHELL=/QOpenSys/pkgs/bin/bash
SHLVL=1
TZ=<GMT>0<BST>,M3.5.0,M10.5.0
USER=richard
USERNAME=richard
WORKDIR=/home/RICHARD
_=/QOpenSys/usr/bin/env
```
</details>

<details>
<summary>Variants</summary>

```json
{
  "american": "#@$",
  "local": "#@£"
}
```
</details>

<details>
<summary>Errors</summary>

```json
[
  {
    "command": "ls -p /QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx",
    "code": 2,
    "stderr": "/QIBM/ProdData/IBMiDebugService/bin/certs/debug_service.pfx not found",
    "cwd": "/home/RICHARD"
  },
  {
    "command": "ls undefined",
    "code": 2,
    "stderr": "undefined not found",
    "cwd": "/home/RICHARD"
  },
  {
    "command": "/QOpenSys/usr/bin/qsh",
    "code": 1,
    "stderr": "CPFA0A9:  Object not found.  Object is /QSYS.LIB/RMTEMP.LIB/VSCODE.FILE/RPGLINT.MBR.\nCPFA097:  Object not copied.  Object is /QSYS.LIB/RMTEMP.LIB/VSCODE.FILE/RPGLINT.MBR.\nCPC2206:  Ownership of object QZSHSYSTEM in QTEMP type *USRSPC changed.",
    "cwd": "/home/RICHARD"
  }
]
```
</details>

**Comment by m-tyler** [comment]
I am adding a second to this issue.  

-Matt

**Comment by worksofliam** [comment]
<img width="1339" alt="image" src="https://github.com/codefori/vscode-ibmi/assets/3708366/974db0f5-c441-4a16-84c3-fc5d82477d05">

**Comment by richardm90** [comment]
@worksofliam - a much quicker way of illustrating the problem!

**Comment by richardm90** [comment]
@worksofliam , yes, no problem.

**Comment by m-tyler** [comment]
I did and the fix works for me.

![image](https://github.com/codefori/vscode-ibmi/assets/1353665/ea2f985c-850e-4461-b519-7cbd16096f40)

**Comment by richardm90** [comment]
@worksofliam , same results here, works well.

**Comment by worksofliam** [comment]
The next release, 2.8.0 should be out in a day or two with this fix. But, we are making a prerelease that you can switch to in VS Code to get it early.

**Comment by richardm90** [comment]
Just to add that I've been using the fix heavily over the last few days and it's still working well.

**Comment by chrjorgensen** [comment]
Release 2.8.0 was published yesterday and included the fix. So no users should be hit by this bug anymore.
