### ISSUE TITLE
Curious activity in Code for IBM i Output

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#190]
**Describe the bug**
In the Output tab I see CPYTOSTMF activity each time VS Code regains the focus.

**To Reproduce**
Running on WIN 10 Pro.
1. Open a member, but make no changes.
2. Open the OUTPUT tab.  Select CODE for IBM i in the drop down.
3. Clear the OUTPUT tab.
4. Switch focus to another window.
5. Alt-Tab back to VS Code.  A CPYTOSTMF activity appears in the OUTPUT tab.
6. Repeat ALT-TAB, ALT_TAB.  Each time VS Code gets the focus the CPYTOSTMF activity appears.

If the open member has changes, then nothing appears in the OUTPUT tab.

This may be expected behavior,  but I'm reporting it just in case.  

**Environment (please complete the following information):**
 - Extension version [e.g. 0.5.7]
 - IBM i OS version [e.g. 7.4]

**Comment by worksofliam** [comment]
This is standard VS Code behavior.

When a file is not dirty (edited), VS Code continues to fetch the contents of the file in case of any changes.
