### ISSUE TITLE
Source Search Result Error

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#191]
**Describe the bug**
A colon (:) in the found line truncates the line in the result.

**To Reproduce**
1. Create a source file with this line:   `// This is a sample comment:xxx precedes this.`

2. Search for xxx.
3. Text after the colon is missing in the Result tab.

**Expected behavior**
Should show the entire line
**Screenshots**
Here's my result:
![image](https://user-images.githubusercontent.com/67484051/121920978-90eed080-cd06-11eb-8a19-30b23dc1be81.png)
Here's the input file:
![image](https://user-images.githubusercontent.com/67484051/121921061-a663fa80-cd06-11eb-9d45-5ef7bafe4ea4.png)

**Environment (please complete the following information):**
 - Extension version [e.g. 0.5.7x]
 - IBM i OS version [e.g. 7.4]

**Comment by worksofliam** [comment]
This is a great bug find. Thank you @SJLennon!

![image](https://user-images.githubusercontent.com/3708366/121963392-0d4dd780-cd38-11eb-9a54-1befd546586d.png)

![image](https://user-images.githubusercontent.com/3708366/121963458-22c30180-cd38-11eb-9844-df0bb678b587.png)
