### ISSUE TITLE
Error Deleteing IFS file.

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#192]
**Describe the bug**
Get "Cannot delete streamfile while it is open" even though the file is not open.

**To Reproduce**
1.Open a stream file in the IFS browser.
2. Close the stream file.
3. Right click and choose Delete Object.
4. See the error message.

**Expected behavior**
Should get the "Are you sure ..." prompt.

If you keep trying to delete, eventually after a minute or two you will get the "Are you sure ..."  prompt.  I'd guess something timed out.

**Comment by worksofliam** [comment]
This is an issue for both IFS and members.

Also applied to deleting, renaming, moving, etc.

Working on it.

**Comment by worksofliam** [comment]
Turns out my current implementation was not that good.

There really isn't an API to determine a list of open tabs, so I may just remove this entirely.

https://github.com/microsoft/vscode/issues/15178

**Comment by worksofliam** [comment]
Due release.
