### ISSUE TITLE
Ability to create library from object view

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#194]

**Comment by szsascha** [comment]
@worksofliam You're assigned to this issue. Are you working currently on this?
I've a bit of free time at the moment and planning to work on vscode for ibmi again. This seems a good issue to me. Maybe I want to implement this. But I'm not sure.

**Comment by worksofliam** [comment]
@szsascha feel free to take it on! I'd say this is a nice easy thing to work on.
