### ISSUE TITLE
Source Dates Not Working

### ISSUE THREAD

**Issue by danlong005** [halcyon-tech/vscode-ibmi#196]
**Describe the bug**
I have purchased the license and have applied the license. Also, I have installed the SourceDates vsix. Then restarted VSCode. I get the following message each time I connect.

![image](https://user-images.githubusercontent.com/7793404/122275940-e1eafa00-cea9-11eb-9753-abd1a3d5dcc8.png)

Yet when I connect via ssh to the IBMi I can run the db2util command.
![image](https://user-images.githubusercontent.com/7793404/122276097-0e9f1180-ceaa-11eb-8b03-9a63138d5133.png)

**Environment (please complete the following information):**
 - Extension version - v0.0.2
 - IBM i OS version - 7.3

**Comment by worksofliam** [comment]
Hey Dan. Please reach out to our support team.

support[at]ileditor[dot]dev

We may setup a little call to look at this together!
