### ISSUE TITLE
I can't open a source member with '£' in the member's name

### ISSUE THREAD

**Issue by benetti-smeup** [halcyon-tech/vscode-ibmi#198]
**Describe the bug**
Describe your issue:
A lot of my source members' names contains '£' . 
I see the right member name in the member browser.
When I try to open it, I get this message:
"CPFA0A9: L'oggetto non � stato trovato. L'oggetto � /QSYS.lib/SMEUP_TST.lib/JASRC.file/A£MOPE_02.mbr. CPFA097: Oggetto non copiato. L'oggetto � /QSYS.lib/SMEUP_TST.lib/JASRC.file/A£MOPE_02.mbr."

The source file ccsid is 280.

I tried with both sourceFileCCSID="*FILE" and sourceFileCCSID="280" 

**To Reproduce**
1. Go to Member browser
2. Click on a member with a name that contains '£'
3. See error
"CPFA0A9: L'oggetto non � stato trovato. L'oggetto � /QSYS.lib/SMEUP_TST.lib/JASRC.file/A£MOPE_02.mbr. CPFA097: Oggetto non copiato. L'oggetto � /QSYS.lib/SMEUP_TST.lib/JASRC.file/A£MOPE_02.mbr."

**Expected behavior**
See my source member in the editor

**Screenshots**
![Liam](https://user-images.githubusercontent.com/33417433/123094773-972f2c00-d42d-11eb-8a73-25700d19d033.png)

**Environment (please complete the following information):**
 - Extension version 0.5.8
 - IBM i OS version 7.2

**Additional context**
db2util 1.0.11-1

usrprf
LANGID *SYSVAL
CNTRYID *SYSVAL
CCSID *SYSVAL

wrksysval
QCCSID 65535
QCNTRYID IT
QLANGID ITA
QCHRID 697-280

**Comment by worksofliam** [comment]
Can you run `ls /QSYS.lib/SMEUP_TST.lib/JASRC.file/` in a pase shell and paste the result here?

**Comment by benetti-smeup** [comment]
I get a list with # instead of £ in the members' names.

A#_053_02.MBR   B#_089_01.MBR   B#SER_10.MBR    C#_100_04.MBR   D5_139_01O.MBR  LOA10_SE.MBR    LOA42_OG3.MBR   WFSER_02.MBR  
A#_053_02O.MBR  B#_089_01O.MBR  B#SER_39.MBR    C#_101_01.MBR   GM_036_01.MBR   LOA10_SU.MBR    LOA42_RND1.MBR  WFSER_03.MBR  
A#_094_06.MBR   B#_089_02.MBR   B#SER_44.MBR    C#_125_00.MBR   GM_036_02.MBR   LOA12_10.MBR    LOCSPL_01.MBR   WFSER_07.MBR  
A#_136_01.MBR   B#_089_02O.MBR  B#SER_46.MBR    C#_125_01.MBR   JACFG1.MBR      LOA12_A1.MBR    LOCTED_01.MBR   WFSER_11.MBR  
A#_136_02.MBR   B#_089_03.MBR   B#SER_49.MBR    C#_125_02.MBR   JACFG2.MBR      LOA12_A2.MBR    LOFUNC_SE1.MBR  WFSER_15.MBR  
A#_136_03.MBR   B#_092_01.MBR   B#SER_56.MBR    C#_125_03.MBR   JAJ11G.MBR      LOA12_SE.MBR    LOFUNC_SE.MBR   WFSER_16.MBR  
A#_136_04.MBR   B#_105_01.MBR   B#SER_59.MBR    C#_125_04.MBR   JAJ11G_T.MBR    LOA15_001.MBR   LOFUNC_SEN.MBR  WFSER_16_O.MBR
A#_136_04O.MBR  B#_105_02.MBR   B#SER_59_O.MBR  C#_125_05.MBR   JAJ180.MBR      LOA15_A5.MBR    LOFUNC_SEO.MBR  WFSER_17.MBR  
A#_136_05.MBR   B#_105_03.MBR   B#SER_62.MBR    C#_125_08.MBR   JAJAC0_SM.MBR   LOA15_GF.MBR    LOIP_01V.MBR    WFSER_18.MBR  
A#_136_06.MBR   B#_120_01.MBR   B#SER_63_1.MBR  C#_125_09.MBR   JAJAS1.MBR      LOA20_DE.MBR    LOSER_04.MBR    WFSER_19.MBR  
A#MOPE_02.MBR   B#BASE_05.MBR   B#SER_63.MBR    C5_093D_01.MBR  JASER_02.MBR    LOA20_SE_1.MBR  LOSER_09.MBR    WFSER_20.MBR  
B#_006_01.MBR   B#BASE_07B.MBR  B#SER_63_O.MBR  CQ_007_01.MBR   JASER_13.MBR    LOA20_SE.MBR    LOSER_10.MBR    WS_129_01.MBR 
B#_032_01.MBR   B#BASE_07.MBR   B#SER_76.MBR    C#SMA_100.MBR   JATRE_01C.MBR   LOA20_SE_O.MBR  LOSER_10_O.MBR  WS_130_01.MBR 
B#_054_01.MBR   B#BASE_07O.MBR  B#SER_88.MBR    C#SUP_04.MBR    JATRE_13C.MBR   LOA20_SEV.MBR   LOSER_25.MBR    WS_130_02.MBR 
B#_055_01.MBR   B#DOCU_01.MBR   B#SER_90.MBR    D5_084_01.MBR   JATRE_18C.MBR   LOA36_SI.MBR    LOSER_36_O.MBR                
B#_063_01.MBR   B#DOCU_02.MBR   B#SER_95.MBR    D5_091_01.MBR   JATRE_29C.MBR   LOA36_SM_O.MBR  LOSER_37.MBR                  

![liam2](https://user-images.githubusercontent.com/33417433/123099278-55ed4b00-d432-11eb-893d-f703c3fd0d40.png)

**Comment by worksofliam** [comment]
That is likely the issue here. Probably something to do with encoding. I will ask around to see if anyone knows why this might be.

Also, can you try it from an ssh session?

**Comment by benetti-smeup** [comment]
I think the problem is that in ccsid 280 '£' has the same hex as '#' in ccsid 37. The member browser lists the members' names in ccsid 280 (rightly), but I don't know if the pase environment support different ccsid.

In a ssh sessions I see names with # insteand of £.

![liam3](https://user-images.githubusercontent.com/33417433/123101601-8635e900-d434-11eb-8a9f-4c393d17a70e.png)

**Comment by onewheelonly** [comment]
'£' isn't valid in an IBM i "name". So I think you're a victim of QCCSID= 65535.

In an interactive job, could you check your job CCSID (DSPJOB, option 2, page down three times, find "Coded character set identifier")? And can you advise what encoding your emulator software is set to use?

**Comment by benetti-smeup** [comment]
Identificativo lingua . . . . . . . . . . . . . . :   ITA  
Identificativo paese o regione  . . . . . . . . . :   IT   
Identificativo serie caratteri codificati . . . . :   65535
CCSID predefinito . . . . . . . . . . . . . . . . :   280  

my ACS session use ccsid 280

**Comment by benetti-smeup** [comment]
I have the same problem using a user with ccsid set to 280, too.

**Comment by onewheelonly** [comment]
That setup does sound like it should be okay 🤔

**Comment by benetti-smeup** [comment]
I thought so too, but it does not work.

**Comment by benetti-smeup** [comment]
I tried on a 7.3 IBM i machine with QCCSID = 280  and db2util 1.0.11-1 and I have the same problem. So it's not QCCSID = 65535 the issue.

**Comment by SJLennon** [comment]
@benetti-smeup FWIW:  Until a solution if found, you can try disabling db2Util, by un-checking the "Enable SQL" option.  That will mean the Member Browser should work but you will lose the Database browser.  If the Member Browser still fails, then it probably isn't db2Util.

You need to **save the settings**, then **reconnect** to make it take effect.
![image](https://user-images.githubusercontent.com/67484051/123278228-c51b7b80-d4d4-11eb-80fb-eb85075ff6ba.png)

**Comment by benetti-smeup** [comment]
I confirm that I have the same problem with db2utils disabled.
![liam4](https://user-images.githubusercontent.com/33417433/123281727-36c1ec80-d50a-11eb-8b7e-a8da48bd0e55.png)

**Comment by worksofliam** [comment]
Likely something to do with the shell encoding vs encoding of the members.

I am not sure personally, and this isn't a direct issue with this extension if `ls` is returning names with the pound sign (`#`) in. I will leave it open and hopefully someone who knows more about it might be able to chime in.

**Comment by benetti-smeup** [comment]
I have some update about this issue.
Setting these env variables seems to work.
PASE_LANG                   'IT_IT'
QIBM_PASE_CCSID             '1208' 

I tried also 
PASE_LANG                   'it_IT'
QIBM_PASE_CCSID             '1252'

and it seems to work, too.

The original setting was

QIBM_PASE_CCSID             '819'  
and no PASE_LANG

I had to set these variables with 
WRKENVVAR LEVEL(*SYS)
and restart my IBM i.

I'm trying to understand if is better to use 
QIBM_PASE_CCSID             '1208' 
or
QIBM_PASE_CCSID             '1252'

I'll keep you posted!

**Comment by onewheelonly** [comment]
1208 may be preferable. It sounds like it is the default from 7.4:

https://www.ibm.com/docs/en/i/7.4?topic=system-default-pase-ccsid-locale-changed-utf-8

Though that page only talks about PASE commands invoked from QShell, to me it suggests a move towards using utf-8. It would be interesting to see if you still need those variables after you upgrade.

**Comment by worksofliam** [comment]
@benetti-smeup what's the status here? 

Is there something I need to do or shall we close this?

**Comment by benetti-smeup** [comment]
Hi @worksofliam .
Setting these env variables seems to work. 
PASE_LANG 'IT_IT'
QIBM_PASE_CCSID '1208'

I've been trying for several days.

I tried also on a 7.4 (default QIBM_PASE_CCSID '1208' as @onewheelonly said) and it seems to work out of the box.

I think we can close the issue.
Thank you.

**Comment by worksofliam** [comment]
@benetti-smeup Sorry to bother you. Do you think it's worth us adding in a notice to the extension that when the user connects and they don't have a `PASE_LANG` set, we should notify them to set one based on their CCSID? Same for QIBM_PASE_CCSID?

**Comment by benetti-smeup** [comment]
@worksofliam yes, I think it could be useful. Something like "If you have problem with variant characters in members name you should set PASE_LANG based on your CCSID". Based on my tests, I think that set QIBM_PASE_CCSID to 1208 is useful but maybe not necessary.

**Comment by worksofliam** [comment]
@benetti-smeup 

Good idea. Do you know where the docs are for `PASE_LANG`? I can't seem to find any.

After some further discussion with others, the plan is to add a new configuration variable for setting `LC_ALL` in the connection settings. It will default to `none` but there will be options to select a UTF8 locale for their language.

When the user first connects, it will check if there is a `LC_ALL` env var. If there is, the config will change to `default` (as it's already set). If it's not, it will prompt the user to warn them and ask if they:

1. want to set it up, which will open the connection settings.
2. ignore it, which will change the config to `default`

The connection settings will have a new select box with the available options, which will all be UTF8/1208 encodings.

* Locales: https://www.ibm.com/docs/en/i/7.4?topic=ssw_ibm_i_74/apis/pase_locales.htm
* https://www.ibm.com/docs/en/aix/7.1?topic=locales-understanding-locale-environment-variables

**Comment by benetti-smeup** [comment]
@worksofliam 
I found some reference to PASE_LANG in forums but I'm not sure about official IBM docs.
In the official documentation I found PASE_LANG here:
https://www.ibm.com/docs/en/i/7.4?topic=programming-running-cgi-programs-in-pase
https://www.ibm.com/docs/en/i/7.4?topic=i-database

Good idea a new configuration variable for setting the utf8 locale. 
If the available options will all be UTF8 locales, I think you should also set QIBM_PASE_CCSID to 1208.
