### ISSUE TITLE
CPDA08C: Database File CCSID is 65535

### ISSUE THREAD

**Issue by cwakelee** [halcyon-tech/vscode-ibmi#199]
**Describe the bug**
Clients keeps box at CCSID 66535 can not open member
CPDA08C: Database File CCSID is 65535

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Extension version [e.g. 0.x.x]
 - IBM i OS version [e.g. 7.x]

**Additional context**

**Comment by worksofliam** [comment]
That's because the source file was likely created as 65535. Please set the 'Source file CCSID' in the settings.

![image](https://user-images.githubusercontent.com/3708366/123128707-5decc100-d419-11eb-9e8b-5469e26dbb97.png)

**Comment by cwakelee** [comment]
Now do you get the addtional settings

**Comment by worksofliam** [comment]
There is a label in the bottom right that says the word 'Settings' followed by the host name.

**Comment by cwakelee** [comment]
CPD0085: Range of parameter DBFCCSID does not include 65535. CPF0006: Errors occurred in command.

**Comment by worksofliam** [comment]
You cannot put 65535 in there. You need to specify what CCSID you expect it to be.

**Comment by SJLennon** [comment]
@cwakelee  FWIW:  65535 means hex, or no translation takes place when the data is retrieved. Having data as 65535 is not a good practice. 
For Source file CCSID you _probably_ want 37 if you are in the USA.  If you are somewhere else this page may help: https://www.ibm.com/docs/en/i/7.2?topic=information-ccsid-values-defined-i

**Comment by worksofliam** [comment]
Thanks for your help here @SJLennon!
