### ISSUE TITLE
buildLibrary property not accepted when compiling IFS source

### ISSUE THREAD

**Issue by richardm90** [halcyon-tech/vscode-ibmi#202]
**Describe the bug**
When compiling IFS source I was unable to get the build library to default, it always defaulted the value `undefined`.

My connectionSettings config included a value for `buildLibrary`, as per the docs, and the library existed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clear "IBM i output" output in the Output tab
2. Open an IFS rpgle source
3. Compile using the CRTBNDRPG command
4. Review "IBM i output" in the Output tab
5. Find the CRTBNDRPG command, the object library is shown as undefined

**Expected behavior**
When compiling a source from the IFS I expected the `buildLibrary` setting to be picked up and used as the compiled object library.

After some trial and error I found that adding a property of `currentLibrary` with a value worked as expected.

It maybe that its simply a case of updating the docs.

Is there a potential for confusion with the `currentLibrary` property and the IBM i current library? does the `currentLibrary` property set the IBM i current library?

**Environment (please complete the following information):**
 - Extension version 0.5.8
 - IBM i OS version 7.4
 - db2util version 1.0.11-1

**Additional context**
Running VS Code on Linux.
I was using the the CRTBNDRPG command to perform the compile - the only adjustment I made to the command was the addition of `TGTCCSID(*JOB)`.

**Comment by worksofliam** [comment]
> After some trial and error I found that adding a property of currentLibrary with a value worked as expected.

Yup, glad you figured it out. We switched it over to avoid confusion in the future.

> It maybe that its simply a case of updating the docs.

Here are the references to 'current library' - maybe we do need to add more?

1. https://halcyon-tech.github.io/vscode-ibmi/#/?id=current-library
2. https://halcyon-tech.github.io/vscode-ibmi/#/?id=command-variables-and-fields (see `&CURLIB`)

> Is there a potential for confusion with the currentLibrary property and the IBM i current library? does the currentLibrary property set the IBM i current library?

Yes, it does correct set your setting `currentLibrary` to the current library when running actions. The reason we renamed it was to add this functionality 😄 

Please see #146 and #149
