### ISSUE TITLE
Rpgle Indentation Enabled: End-PR

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#203]
**Describe the bug**
End-PR is flagged as an indentation issue.  End-PR is expected to be indented and (IMHO) it should not.  End-PI and End-DS don't require indentation.

**Screenshots**
Here's and example:
![image](https://user-images.githubusercontent.com/67484051/123817767-6f751380-d8c6-11eb-976f-df1529693be7.png)

 **To Reproduce**
I have struggled with this.  The above screen shot is of some old source that I converted with your **`rpgfreeweb`** tool but it's fairly long and complex.  So I keyed in some simple code, but could not cause the error.  Finally, I discovered that it seems to relate to the commend on the prior line.  Here's the simplified code with the error:
![image](https://user-images.githubusercontent.com/67484051/123830845-b1578700-d8d1-11eb-89b7-7b7ed46a23ad.png)
But if I remove the two slashes, bingo, no errors:
![image](https://user-images.githubusercontent.com/67484051/123830985-d815bd80-d8d1-11eb-8b24-721b7aea5236.png)

**Environment (please complete the following information):**
 - Extension version [e.g. 0.5.8]
 - IBM i OS version [e.g. 7.4]

(England vs Germany calls...)

**Comment by worksofliam** [comment]
@SJLennon Can you please paste the code here that is causing this so I can just copy and paste it into my editor?

Thanks

**Comment by SJLennon** [comment]
Sure...

```
**FREE
Dcl-PR p_getobjur  extpgm('GETOBJUR');
    *n             char(4); 
End-Pr; //
```

![image](https://user-images.githubusercontent.com/67484051/123845731-875a9080-d8e2-11eb-9e1c-b47e9a13748a.png)

Delete the `// `and the problem goes away.
@worksofliam

**Comment by worksofliam** [comment]
Thanks. I will work on this tonight.

**Comment by SJLennon** [comment]
No rush on my part.  If case it helps, here is slightly larger code with errors **also** on the `End-pi,` and the comments in a slightly different place.
```
**FREE
Dcl-PR p_getobjur  extpgm('GETOBJUR');
    *n             char(4);
    *n int(10); // xxx.
End-Pr; 
Dcl-PI p_getobjur;
    pFileYN        Char(4); // yyy
End-PI;
```
![image](https://user-images.githubusercontent.com/67484051/123852212-1028fa80-d8ea-11eb-87fd-a728a35285be.png)
Removing the comment resolves the problem.

![image](https://user-images.githubusercontent.com/67484051/123852474-5716f000-d8ea-11eb-8fb7-7940e08622e2.png)
@worksofliam

**Comment by worksofliam** [comment]
Made a fix. Will be out in 0.6.0

**Comment by worksofliam** [comment]
@SJLennon This issue has been fixed and will be available in 0.5.9, which has just come out.

Please have a go and let me know.

**Comment by SJLennon** [comment]
@worksofliam 
0.5.9 Fixed the above problem.  
However,I have a question:  **What invokes the feature?**  
I have two members open.  TESTIN2 is reporting indentation problems (line 8) as I expect.
![image](https://user-images.githubusercontent.com/67484051/124142863-9cf1c680-da58-11eb-950b-c18f23f3d57f.png)

But I cannot get TESTIN to report any indentation errors.  Line  8 in this one is clearly in error. No matter how many lines I incorrectly indent, nothing is flagged.
![image](https://user-images.githubusercontent.com/67484051/124143344-0d004c80-da59-11eb-911f-a7f848e2a6f5.png)
This is non functional test code, but both members compile, so they are syntactically correct.
I think this is a nice feature for maintaining code readability.

```
**FREE
Dcl-PR p_getobjur  extpgm('GETOBJUR');
    *n             char(4);
    *n int(10); // xxx.
End-Pr;
Dcl-PI p_ZZZZbjur extpgm('GETOBJUR');
    pFileYN        Char(4);
      pThing          char(10);
End-PI;
*inlr = *on;
```


```
**free
Dcl-PR p_qwclobjl  extpgm('QWCLOBJL');
    *N             Char(272); //APIError
     S#Keys       Packed(3:0);
End-PR;
dcl-pr Ziggy extpgm('QZONKER');
    *n             char(10);
      *n              char(20);
 end-pr;
//------------------------------------------------------
Dcl-PR p_XXXlobjl  extpgm('QWCLOBJL');
    *N             Char(272); //APIError
End-PR;
//------------------------------------------------------
Dcl-PI p_getobjur extpgm('QWCLOBJL');
    pObject        Char(20);
    pObjType       Char(10);
    pObjMem        Char(10);
    pMsgYN         Char(4);
    pMsgFld        Char(200);
    pFileYN        Char(4);
End-PI;
*inlr = *on;

```

**Comment by SJLennon** [comment]
OK, figured it out.  **FREE is what turns it on.  **free does not, even though it is syntactically correct.
@worksofliam
