### ISSUE TITLE
Allow saving of a library list and swapping between saved lists

### ISSUE THREAD

**Issue by BrianGarland** [halcyon-tech/vscode-ibmi#204]
It is common to work in multiple applications (or multiple versions of the same application) which have different library lists.  

It would be great to have a way to set a library list, then save it for later use so that you can easily switch between them.

**Comment by worksofliam** [comment]
This is an awesome feature. The code has been written and I'm to open the PR. Before it can get released, I need to work on the documentation and then it should be out in 0.6.0.

**Comment by BrianGarland** [comment]
@worksofliam This is amazing!  It was cool to watch you think through this and code it within hours of me creating the issue.
