### ISSUE TITLE
how to get Private Key

### ISSUE THREAD

**Issue by prachaya2639** [halcyon-tech/vscode-ibmi#209]
I don't know to get a Private Key path

Thank you.

**Comment by prachaya2639** [comment]
I have a problem.
![image](https://user-images.githubusercontent.com/61548379/124066816-8c931900-da63-11eb-8116-e56751c6f5be.jpeg)

**Comment by eduardomarco** [comment]
I have the same problem

**Comment by worksofliam** [comment]
I will have to look into getting this setup myself.

**Comment by SJLennon** [comment]
Didn't @onewheelonly add the support for SSH private keys?  Perhaps he could weigh in on this one.

**Comment by onewheelonly** [comment]
I did indeed. I've never seen this message before though. I assume it comes from the ssh2 library that we use, but a quick Google for that text didn't turn up any results.

@prachaya2639 and/or @eduardomaro - Can you please tell me a little about your private keys? What algorithm/key size do you use? And when you look at the text within the private key file, can you tell me what the first line looks like please?

**Comment by priceaj** [comment]
FWIW The code that is producing this error is here: https://github.com/mscdex/ssh2-streams/blob/8de25ea69a76dbf1c34e578e42571e97de926ac0/lib/ssh.js 

It occurs when the SSH protocol identification is too long (> 255 characters)

The identification string should look something like "SSH-<protocolmajor>.<protocolminor>-<version>\n"

I would suggest trying to connect to the same box using an SSH client like PuTTY or KiTTY and if you can connect you will see a line in the event log something like:

We Claim version: SSH-2.0-PuTTY-KiTTY
Server version: SSH-2.0-OpenSSH_8.0

You could also try connecting directly using the SSH2 module and seeing if that works:

https://github.com/halcyon-tech/vscode-ibmi/issues/125#issuecomment-817214784

You should see domething like:

Local ident: 'SSH-2.0-ssh2js1.4.0'
Socket connected
Remote ident: 'SSH-2.0-OpenSSH_8.0'

Let us know if either of these methods work and what both of the identification strings look like
