### ISSUE TITLE
Library list seems reversed

### ISSUE THREAD

**Issue by benetti-smeup** [halcyon-tech/vscode-ibmi#213]
**Describe the bug**
Checking the library list of QP0ZSPWP job I see the library list reversed.
This is the library list I set 

            "libraryList": [
                "QTEMP",
                "SMEUP_DAT",
                "SMETAB",
                "PER_SRVL",
                "SMEUP_SVI",
                "SMEUP_TST",
                "SMEDEV",
                "SMEUP_OBJ",
                "SMESRC",
                "SMESTD",
                "QGPL"
            ],

and this is the library list of my QP0ZSPWP job

Lib.        Tipo
QSYS        SYS 
QSYS2       SYS 
QHLPSYS     SYS 
QUSRSYS     SYS 
SMESYS_SML  SYS 
SMESYS_SM   SYS 
QSHELL      PRD 
QGPL        USR 
SMESTD      USR 
SMESRC      USR 
SMEUP_OBJ   USR 
SMEDEV      USR 
SMEUP_TST   USR
SMEUP_SVI   USR
PER_SRVL    USR
SMETAB      USR
SMEUP_DAT   USR
QTEMP       USR

as you can see the order seems reversed.
I noticed this because a program in the wrong library was called with a custom action.

**Environment (please complete the following information):**
 - Extension version 0.6.1
 - IBM i OS version 7.2

**Comment by worksofliam** [comment]
The job for the SSH connection is not the job that runs the compiles (which will have that library list).

**Comment by benetti-smeup** [comment]
Sorry Liam, maybe I wasn't clear.

I have the same program in 4 different libraries (SMEUP_SVI, SMEUP_TST, SMEDEV and SMEUP_OBJ).

My library list was this:

        "libraryList": [
            "QTEMP",
            "SMEUP_DAT",
            "SMETAB",
            "PER_SRVL",
            "SMEUP_SVI",
            "SMEUP_TST",
            "SMEDEV",
            "SMEUP_OBJ",
            "SMESRC",
            "SMESTD",
            "QGPL"
        ],

but the program called using a custom action was in SMEUP_OBJ, not in SMEUP_SVI.

I tried reversing the settings of my library list to
            "libraryList": [
                "QGPL",
                "SMESRC",
                "SMESTD",
                "SMEUP_OBJ",
                "SMEDEV",
                "SMEUP_TST",
                "SMEUP_SVI",
                "PER_SRVL",
                "SMETAB",
                "SMEUP_DAT",
                "QTEMP"
            ],

and the program in SMEUP_SVI was called.

**Comment by worksofliam** [comment]
Interesting.

I will open it back up, but I'm on vacation until the 19th.

Please feel free to do some debugging to find the source of the issue.

**Comment by SJLennon** [comment]
FWIW:  I can confirm this is happening in the OBJECT BROWSER.  I wrote a 3 line CLP that did
DSPLIBL    OUTPUT(*PRINT), then ran the Call action in the OBJECT BROWSER.  Screen shot shows the reversed library list.
![image](https://user-images.githubusercontent.com/67484051/125202999-65e39800-e244-11eb-9568-f54f5dff1457.png)

**Comment by worksofliam** [comment]
Ha.

I will look into getting this fixed this weekend.

**Comment by worksofliam** [comment]
Good morning. I have recreated this issue.

![image](https://user-images.githubusercontent.com/3708366/126040355-a26d239e-037b-4bf1-9f87-30cf10a0afac.png)

**Comment by worksofliam** [comment]
This is where the issue starts: https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/api/CompileTools.js#L258

The first reverse is correct, but the second on 270 is where it is breaking. `.reverse` is not creating a new instance of the array, it is mutating the base one, which is why it is coming backward.

I have resolved it and there will be a fix out very soon.

**Comment by worksofliam** [comment]
I'm about to release 0.6.2 which should solve this issue.

**Comment by worksofliam** [comment]
@benetti-smeup @SJLennon have either of you had a look at testing my fix at all? No rush, just curious.

**Comment by SJLennon** [comment]
@worksofliam I checked it out calling my test program, which was, I think, identical to yours.  Hopefully, that covers the situation of @benetti-smeup as well.

**Comment by worksofliam** [comment]
@SJLennon that is great.

Hopefully Marco can get back here sooner so we can close this issue 🙌

**Comment by benetti-smeup** [comment]
@worksofliam It works!
thank you!
