### ISSUE TITLE
Cannot cannect on IBMi

### ISSUE THREAD

**Issue by andymalo43** [halcyon-tech/vscode-ibmi#215]
**Describe the bug**
When I am trying to connect to my IBMi, After initialising library, It sends me a message 'Not connected to xxx.xxx.xxx.xxx!'

**To Reproduce**
1. Click on the Icon
2. Configure connection (Name, Host , User, Password, OK
3. Notification 'Not connected'

**Screenshots**
![image](https://user-images.githubusercontent.com/87163807/125358383-8c284580-e3b4-11eb-9309-abfcb1d27d55.png)

**Environment :**
 - Extension version 0.6.1
 - IBM i OS version 7R3
 - SSH Daemon launched on the host

**Comment by SJLennon** [comment]
@andymalo43 
I doubt there is enough provided to isolate the problem...
Suggestions:
1) Post your settings.json file.
2) Take a look at #214. It might help clarify what is wrong.
3) Ensure you have SSH Daemon must be started on IBM i.

**Comment by andymalo43** [comment]
Hi,
Sorry for the missing informations... and thank you for your time answering.

It stopped here : 

![image](https://user-images.githubusercontent.com/87163807/125388488-4c308500-e3eb-11eb-9150-54c5324d45af.png)

Here are my settings.json concerning code for ibmi

`"code-for-ibmi.connectionSettings": [
        {
            "name": "IBMi",
            "sourceFileList": [
                "QSYSINC/H"
            ],
            "objectBrowserList": [],
            "databaseBrowserList": [],
            "libraryList": ["MALOA","QTEMP","QGPL"],
            "libraryListProfiles": [],
            "homeDirectory": "/home/MALOA",
            "tempLibrary": "MALOA",
            "currentLibrary": "MALOA",
            "sourceFileCCSID": "*FILE",
            "enableSQL": false,
            "hideCompileErrors": []
        }
    ],
    "code-for-ibmi.connections": [
    

        {
            "name": "IBMi",
            "host": "xxx",
            "port": 22,
            "username": "MALOA",
            "password":"xxx",
            "privateKey": null
          }
    ],`

2. i looked the post and I cannot see what's going wrong :/
3. the SSH is started on the IBM i

**Comment by SJLennon** [comment]
@andymalo43  Ummm. Not sure what is going on. 
Suggestions:
1) In your settings.json you have` "password":"xxx",`.  I do not have a password in mine and get prompted for it each time.
2) Can you get a SSH connection to your IBM i using another client, e.g. PuTTY, or Windows SSH client?
3) The extension write some debugging info the OUTPUT tab.  Select Code for IBM i in the drop down on the right. You may have to try connecting a second time before you see Code for IBM i or output.  And there appears to be a bug in that the Code for IBM i may appears more than once in the drop down.  I picked the last one.
You might find something useful here:
![image](https://user-images.githubusercontent.com/67484051/125475584-7f828d7c-0a22-4c28-b5c1-5b7f53ad9c7d.png)

**Comment by andymalo43** [comment]
Hello,

1. 'xxx' was just to mask my password 
2. Yep, i use Putty, ssh connexion from my linux computer
3. Thank you, here is the OUTPUT TAB :
![image](https://user-images.githubusercontent.com/87163807/125701774-31bb279d-5a8a-438f-9ede-98e78fc14fca.png)
I tried the command via ssh on  my server and nothing happened :/

**Comment by SJLennon** [comment]
@andymalo43  Take the password line our of your settings.json, save it, and try to reconnect.

**Comment by SJLennon** [comment]
@andymalo43 When you try to connect do you get a password prompt?  Like this:
![image](https://user-images.githubusercontent.com/67484051/125706905-62782d8d-8971-4c22-ad22-0559f9d3d7a2.png)
I ask because I just added a password line to my settings.json and it still prompted me for a password.

Comparing your OUTPUT tab to mine, your stdout is empty. Mine contains my library list which looks like it means I made a connection and executed a command presumably related to the library list.  Is your user profile restricted in what commands it can execute, for example those related to library lists? 

What password level do you have on your IBM i?  Wondering it that has anything to do with it. There are a lot of system values that start with QPDW* but I suspect these are the most significant.
```
DSPSYSVAL SYSVAL(QPWDLVL)    
DSPSYSVAL SYSVAL(QPWDMAXLEN) 
DSPSYSVAL SYSVAL(QPWDMINLEN) 
 DSPSYSVAL SYSVAL(QPWDRULES)
```
But I'm running out of ideas.  May have to wait until Liam returns from vacation, or someone looks at the connection code.  I'm not familial with the code...

**Comment by SJLennon** [comment]
@andymalo43 I've tried looking at the code, and while I know some javascript, I'm not an expert.  Then I reread some of your comments more carefully.  So...

> I tried the command via ssh on my server and nothing happened 

If you are saying that `echo liblist | /QOpenSys/usr/bin/qsh` does nothing, then this is may be the problem.  For me, in PuTTY, it lists my library list 
![image](https://user-images.githubusercontent.com/67484051/125806257-e7ff44d4-4bda-4ef3-a2e5-aad093510273.png)
The code expect the library list as a string and I suspect if the command fails it doesn't return a string. Though how it bails out of the process I'm not clear on, but it should next have a message "Checking temporary library configuration."
**So, perhaps you don't have QSH installed?**  (You might want to check out this link: https://www.ibm.com/support/pages/basics-qshell, though I'm not confident that I know how PASE and QSH interact.)

You might also try looking on the green screen with `WRKLNK OBJ('/QOpenSys/usr/bin/qsh')`.
Mine shows this:
![image](https://user-images.githubusercontent.com/67484051/125807336-c98fe058-6d5b-4216-9377-29c1f31a9e1b.png)
The taking `12=Work with links` it shows this:
![image](https://user-images.githubusercontent.com/67484051/125807455-f96360d4-5ee6-4f81-843c-cabca3e46379.png)

**Comment by worksofliam** [comment]
> Hello,
> 
> 1. 'xxx' was just to mask my password
> 2. Yep, i use Putty, ssh connexion from my linux computer
> 3. Thank you, here is the OUTPUT TAB :
>    ![image](https://user-images.githubusercontent.com/87163807/125701774-31bb279d-5a8a-438f-9ede-98e78fc14fca.png)
>    I tried the command via ssh on  my server and nothing happened :/

This is likely the issue. A useful start is seeing the exit code is 9 here. Let me do some research.

**Comment by worksofliam** [comment]
Looks like this may be the same issue as #69

**Comment by worksofliam** [comment]
@andymalo43 What is your QCCSID?

**Comment by worksofliam** [comment]
Two days away from stale and close due to inactivity.

**Comment by szsascha** [comment]
@worksofliam For me it also looks like the same like #69 or a network issue. In my opinion this should be closed because we've similar issues and getting no reply from @andymalo43

**Comment by worksofliam** [comment]
@szsascha agreed. I will close.

**Comment by andymalo43** [comment]
Hello,

I resolved my issue by configuring my Bash 

https://ibmi-oss-docs.readthedocs.io/en/latest/troubleshooting/SETTING_BASH.html
