### ISSUE TITLE
Code for IBM i will not function correctly until the temporary library has been corrected in the settings.

### ISSUE THREAD

**Issue by AMDOCA** [halcyon-tech/vscode-ibmi#218]
No matter what I do this error pops up when connecting to IBM i.

**Comment by SJLennon** [comment]
@AMDOCA 
You might want to look at closed issue #214.

Have you added tempLibrary to your settings.json?

It might help to resolve the issue if you posted your settings.json.

**Comment by worksofliam** [comment]
Did not use issue format as requested when creating an issue.

**Comment by AMDOCA** [comment]
"libraryList": [
                "SGFDTAWK",
                "SGFWORK",
                "SGFGLOWK",
                "SGFOBJ",
                "SGFDAT",
                "QGPL",
                "QTEMP",
                "ILEDITOR"
            ],
            "homeDirectory": "/",
            "tempLibrary": "ILEDITOR",
            "buildLibrary": "QTEMP",
            "objectBrowserList": [
                "QGPL",
                "QTEMP"
            ],
            "databaseBrowserList": [
                "QGPL",
                "QTEMP",
                "SGFDTAHR"

**Comment by AMDOCA** [comment]
Hi,

The issue is close related to ILEDITOR library. If I manually remove it the
error does not pop up. The problem arises when at time connection there is
an attempt to create it because it already exists.

**Comment by AMDOCA** [comment]
Hi Mr. Lennon,

I managed to solve the issue. I found that Code For IBM i extension was
failing when trying to find the /home/AMDOCA directory. Once created in IFS
the message stopped popping up.

Thanks for your help!

Abel
