### ISSUE TITLE
Error on CRTBNDRTPG actions - undefined library

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#232]
When a user profile has `CURLIB(*CRTDFT)`, then it sets the connection config prop `currentLibrary` to undefined, causing further issues later.

It needs to default to `QGPL` instead.

### Discussed in https://github.com/halcyon-tech/vscode-ibmi/discussions/231

<div type='discussions-op-text'>

<sup>Originally posted by **robinsg** August  3, 2021</sup>
Hello,

I'm running v0.6.6.

My source file is in the IFS but when I run the CRTBNDRPG I get the following:

**Action Create Bound RPG Program (CRTBNDRPG) for undefined/RPABOTS001 was not successful.**

This is missing the object library name from what I can tell.

If I prompt the CRTBNDRPG action and type in the object library the compile works fine.

In the actions I can see the following for the CRTBDNRPG stream file option:

`CRTBNDRPG PGM(&BUILDLIB/&NAME) SRCSTMF('&FULLPATH') OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT)`

From the documentation &BUILDLIB is meant to reflect the &CURLIB setting.

When I press the  Change Current Library icon on my User Library List pane nothing seems to happen.

Any suggestion how I correct this issue?
</div>

**Comment by szsascha** [comment]
@worksofliam Please keep in mind that setting the QGPL as the default curlib can have side effects. Esp. on a large system running multiple installations of IBM i software.

**Comment by worksofliam** [comment]
@szsascha i am just following what *CRTDFT follows. 

Do you recommend a different default current library?

**Comment by szsascha** [comment]
@worksofliam Ahhh sorry. You're completely right. I had remembered it wrong.

If it had not been correct, I would have recommended to show an error.

**Comment by worksofliam** [comment]
@szsascha no problem! Appreciate the support through all this :)
