### ISSUE TITLE
Improve labeling of ILEDITOR library

### ISSUE THREAD

**Issue by alanseiden** [halcyon-tech/vscode-ibmi#237]
My client asked me:
```
Good Morning Alan,
 
Why is there a new library (ILEDITOR) on our production box this morning?
 
There is nothing in the library, but it does have your name on it.
```

They use MIMIX replication and always want to know about new objects: what they are for, whether they need to be replicated, etc. 

A small but helpful step would be to label the library as something like "Temporary objects for Code for i IDE. May be cleared." or similar.

**Comment by alanseiden** [comment]
Created PR https://github.com/halcyon-tech/vscode-ibmi/pull/238  (not tested)

**Comment by szsascha** [comment]
What happens if the library cannot be created? (Because of missing permissions for example)

Is the creation of the library really necessary?

**Comment by alanseiden** [comment]
> Wouldn't be better to use QTEMP?
@szsascha The documentation (https://github.com/halcyon-tech/vscode-ibmi/blob/master/docs/README.md) states that QTEMP can't be used. (If I had to guess why, perhaps the tool needs a library that can be shared among multiple jobs.)

**Comment by worksofliam** [comment]
@alanseiden is correct.

QTEMP cannot be used. If ILEDITOR doesn't exist, it tries to create it. If it can't be created, it will default to the users current library.
