### ISSUE TITLE
Show object information in object browser

### ISSUE THREAD

**Issue by szsascha** [halcyon-tech/vscode-ibmi#242]
**Is your feature request related to a problem? Please describe.**
A similar feature as already described in #47 but for the object browser could be pretty useful.

**Describe the solution you'd like**
I've already suggest a solution in #47. This could be also done for the object browser.

**Describe alternatives you've considered**
The alternative would be to use an 5250 emulator besides VS Code

**Comment by worksofliam** [comment]
@szsascha I would like to implement this, but I am unsure how I would display the info.

Any ideas?

**Comment by szsascha** [comment]
@worksofliam I would make the object entry expandable. The child entries are used to show the information.

**Comment by worksofliam** [comment]
@szsascha

Do you know any examples of that happening on other apps?

**Comment by szsascha** [comment]
@worksofliam Not exactly. But the database browser works similar for showing the fields. Objects could be like this. Instead of showing field names, you show the attributes of the object.

**Comment by worksofliam** [comment]
So there is a reason I'm against that design.

In the future, I'd actually like to make some objects openable and editable from the Object Browser.

For example, imaging clicking on a binding directory and have a JSON file open up (which is the binding directory contents).

**Comment by szsascha** [comment]
Sounds like a great idea!

But wouldn't it make more sense to open that kind of json file in an editor window where you can edit and save it?

Currently I do not see any point where this interferes with each other.

**Comment by szsascha** [comment]
@worksofliam Any updates on this?

**Comment by worksofliam** [comment]
Likely not going to be done in this extension. 

See some progress on this here: https://github.com/halcyon-tech/vscode-ibmi-fs
