### ISSUE TITLE
'db2util' not installed on system or is disabled in the settings

### ISSUE THREAD

**Issue by bskimball** [halcyon-tech/vscode-ibmi#243]
This plugin looks really nice. I am having an issue with the database browser (everything else is working).

I am getting the message 
```
'db2util' not installed on system or is disabled in the settings
```

I do have db2util installed version 1.0.11-dev. I do have /QOpenSys/pkgs/bin in my PATH variable. Is that an incompatible version?
![image](https://user-images.githubusercontent.com/5348828/129082396-e9b1a7a8-61fa-4136-a915-19e0112959b0.png)

**Comment by worksofliam** [comment]
Likely you need to enable SQL in the extension's additional settings.

After you've connected, see `Settings: <host>` in the bottom left on the status bar.

**Comment by bskimball** [comment]
Yup that worked. I was coming here to close the issue. Thanks so much, you've done a great job on this plugin. 

For anyone else that comes across this

![image](https://user-images.githubusercontent.com/5348828/129084652-3b0369a7-d12f-4dab-80ec-683dbe957263.png)
