### ISSUE TITLE
Can not connect to iSeries

### ISSUE THREAD

**Issue by anson2416** [halcyon-tech/vscode-ibmi#244]
**Describe the bug**
(A clear and concise description of what the bug is. We will not accept your bug and close it if this is not filled out correctly.)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Extension version [e.g. 0.x.x]
 - IBM i OS version [e.g. 7.x]

**Additional context**

**Comment by worksofliam** [comment]
Template not correctly filled out.
