### ISSUE TITLE
Ability to Pull from iASP

### ISSUE THREAD

**Issue by M0rwhsky** [halcyon-tech/vscode-ibmi#245]
We have source files on iASP.  The connections seems to use this just fine for finding the library and objects from the Job Description.  However when trying to open up members the application pull the member from the IFS.  In order to pull this from the IFS you must include the iASP at the beginning of the IFS string.

Either use the parameter from the Job Description like it seems to for the Object listing and Libraries.
Or add a parameter to allow users to specify what iASP they wish to pull from if not default.

cant find:
qsys.lib/"library".lib/qrpglesr.file/"mbr".mbr

Could find:
"iASP"/qsys.lib/"library".lib/qrpglesrc.file/"mbr".mbr

Thank you

**Comment by worksofliam** [comment]
For now, you are able to specify a source ASP in the additional settings for the connection.

![image](https://user-images.githubusercontent.com/3708366/129403989-1f204e23-96bb-41eb-b1bd-9b876f20f7d5.png)

**Comment by M0rwhsky** [comment]
Thank you.... Sorry for this... Murphy law as soon as I posed it I found what I was looking for...

I appreciate the additional information.
