### ISSUE TITLE
Can not connect to iSeries

### ISSUE THREAD

**Issue by anson2416** [halcyon-tech/vscode-ibmi#247]
**Describe the bug**
I newly install the plug-in, by following the guideline, i was not able to connect to iSeries. Any body could share the detail trouble shooting steps for me? (I believe it is not the issue of plug-in, most likely it is the BE security setup).

**To Reproduce**
1. Install the latest plug-in 
2. Click on 'F1' to show the log on screen
3. Input the host detail:  FQDN, port (i try 22 / and 992). 992 is the port i use in PCOM. 
4. See error: No response from host

**Expected behavior**
I can log on iSeries. 

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Extension version: latest
 - IBM i OS version 7.2

**Additional context**
- SSL is required
- I am not sure if SSH demon is up or not.

**Comment by worksofliam** [comment]
Please check the SSH daemon is running and try again.
