### ISSUE TITLE
Cannot reconnect to using 'Connect to Previous IBM i' using ssh key

### ISSUE THREAD

**Issue by sleepy-l0c0** [halcyon-tech/vscode-ibmi#249]
**Describe the bug**
When using password only the 'Connect to Previous IBM i' works great.  I can set up a connection with my id_rsa ssh key generated on my IBMi in a qsh session using  `ssh-keygen -t rsa -N "".` However when I try to use the 'Connect to Previous IBM i feature i get the error message:
`Not connected to mysvr.domain! Error while signing data with privateKey: error:06000066:public key routines:OPENSSL_internal:DECODE_ERROR`

VS code -  Version: 1.59.0 
Code for IBM i ext - v0.6.7
IBM i OS - v7r2

**Comment by SJLennon** [comment]
Can you connect successfully using another client, e.g. PuTTY, or ssh in windows?  This might help clarify where the problem lies.
@sleepy-l0c0

**Comment by sleepy-l0c0** [comment]
Connecting the first time isn't an Issue at all. It the connect to previous
option. Yes I can ssh from (wsl) terminal in vs code using same key.

**Comment by worksofliam** [comment]
Is possibly the same issue as #209

**Comment by worksofliam** [comment]
@sleepy-l0c0 Whats the status here?

**Comment by sleepy-l0c0** [comment]
I haven't figured it out yet. If it's just me feel free to close the issue.

**Comment by worksofliam** [comment]
@sleepy-l0c0 I won't close the issue yet.

I want to make sure we solve any open issues and make sure you have a good experience. Are you able to provide detailed steps for me to recreate this issue?

**Comment by sleepy-l0c0** [comment]
Not currently in front of my computer. I will give it a go and see if I can
recreate my issue detailing my steps a I proceed.

**Comment by sleepy-l0c0** [comment]
Well good news. I have tried a couple of times and was not successful in
recreating the issue. I'm not sure what changed, however I'm glad it works
now.
Here were my steps:
1) remove existing profile (only had one set for password)
2) create a new ssh key on my wsl with ssh-keygen command.
3)scp pub file to the 400 with password auth.
4) cat the pub key to authorized_keys on my profile
5) copy private key to easier to access location for vscode.
6) setup connection profile in code for ibm I
7) connect successfully
(This has been the case always)
8) close vscode reopen
9) used to prompt me a button "reconnect to previous ibmi".
9a) this time I hit a green 'play' triangle and it connected again.

**Comment by worksofliam** [comment]
@sleepy-l0c0 Nice!!

Thanks for sharing your steps. Please feel free to close this issue.
