### ISSUE TITLE
Cannot open the members in /IASPXX/QSYS.LIB/SOURCELIB

### ISSUE THREAD

**Issue by nonicknamelala** [halcyon-tech/vscode-ibmi#256]
The source file can be added into the member browser, and it can list all of the members. but it cannot be opened.

After studying, I found the source members in /QSYS.LIB/XXX.LIB can be opened, but it cannot open the source member in /IASPXX/QSYS.LIB/XXX.LIB which is in another disk mounted in other folders.

**Comment by worksofliam** [comment]
Looking into this futher. @nonicknamelala Do you have db2util installed?

**Comment by nonicknamelala** [comment]
> @nonicknamelala does one of these source files live in an ASP?

Sorry for late reply! I'm green hand to AS400, I don't know what is ASP. But I think it is, the prefix of the path is IASPCN.

Later, I fixed it after finding the param of "sourceASP" in the document.

Thank you very much!
