### ISSUE TITLE
SQL: Unexpected token  in JSON at position 349

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#261]
**Describe the bug**
When I run  `select * from qiws.qcustcdt` I get the error "Unexpected token  in JSON at position 349".
However, `select cusnum, lstnam, zipcod from qiws.qcustcdt` works fine.
It appears to be specific to file qcustcdt.  Another select * that I ran form another file worked fine.

**To Reproduce**
1.Run the statement. And get the error.
2.Look at the Code for IBM i output and see this:

/home/LENNONS: DB2UTIL_JSON_CONTAINER=array /QOpenSys/pkgs/bin/db2util -o json "select * from qiws.qcustcdt"
{
    "code": null,
    "signal": null,
    "stdout": "[\n{\"CUSNUM\":938472,\"LSTNAM\":\"Henning \",\"INIT\":\"G K\",\"STREET\":\"4859 Elm Ave \",\"CITY\":\"Dallas\",\"STATE\":\"TX\",\"ZIPCOD\":75217,\"CDTLMT\":5000,\"CHGCOD\":3,\"BALDUE\":37.00,\"CDTDUE\":0.00},\n{\"CUSNUM\":839283,\"LSTNAM\":\"Jones   \",\"INIT\":\"B D\",\"STREET\":\"21B NW 135 St\",\"CITY\":\"Clay  \",\"STATE\":\"NY\",\"ZIPCOD\":13041,\"CDTLMT\":400,\"CHGCOD\":1,\"BALDUE\":100.00,\"CDTDUE\":0.00\u0000},\n{\"CUSNUM\":392859,\"LSTNAM\":\"Vine    \",\"INIT\":\"S S\",\"STREET\":\"PO Box 79    \",\"CITY\":\"Broton\",\"STATE\":\"VT\",\"ZIPCOD\":5046,\"CDTLMT\":700,\"CHGCOD\":1,\"BALDUE\":439.00,\"CDTDUE\":0.00\u0000},\n{\"CUSNUM\":938485,\"LSTNAM\":\"Johnson \",\"INIT\":\"J A\",\"STREET\":\"3 Alpine Way \",\"CITY\":\"Helen \",\"STATE\":\"GA\",\"ZIPCOD\":30545,\"CDTLMT\":9999,\"CHGCOD\":2,\"BALDUE\":3987.50,\"CDTDUE\":33.50\u0000},\n{\"CUSNUM\":397267,\"LSTNAM\":\"Tyron   \",\"INIT\":\"W E\",\"STREET\":\"13 Myrtle Dr \",\"CITY\":\"Hector\",\"STATE\":\"NY\",\"ZIPCOD\":14841,\"CDTLMT\":1000,\"CHGCOD\":1,\"BALDUE\":0.00,\"CDTDUE\":0.00},\n{\"CUSNUM\":389572,\"LSTNAM\":\"Stevens \",\"INIT\":\"K L\",\"STREET\":\"208 Snow Pass\",\"CITY\":\"Denver\",\"STATE\":\"CO\",\"ZIPCOD\":80226,\"CDTLMT\":400,\"CHGCOD\":1,\"BALDUE\":58.75\u0000,\"CDTDUE\":1.50\u0000},\n{\"CUSNUM\":846283,\"LSTNAM\":\"Alison  \",\"INIT\":\"J S\",\"STREET\":\"787 Lake Dr  \",\"CITY\":\"Isle  \",\"STATE\":\"MN\",\"ZIPCOD\":56342,\"CDTLMT\":5000,\"CHGCOD\":3,\"BALDUE\":10.00,\"CDTDUE\":0.00},\n{\"CUSNUM\":475938,\"LSTNAM\":\"Doe     \",\"INIT\":\"J W\",\"STREET\":\"59 Archer Rd \",\"CITY\":\"Sutter\",\"STATE\":\"CA\",\"ZIPCOD\":95685,\"CDTLMT\":700,\"CHGCOD\":2,\"BALDUE\":250.00,\"CDTDUE\":100.00\u0000},\n{\"CUSNUM\":693829,\"LSTNAM\":\"Thomas  \",\"INIT\":\"A N\",\"STREET\":\"3 Dove Circle\",\"CITY\":\"Casper\",\"STATE\":\"WY\",\"ZIPCOD\":82609,\"CDTLMT\":9999,\"CHGCOD\":2,\"BALDUE\":0.00,\"CDTDUE\":0.00},\n{\"CUSNUM\":593029,\"LSTNAM\":\"Williams\",\"INIT\":\"E D\",\"STREET\":\"485 SE 2 Ave \",\"CITY\":\"Dallas\",\"STATE\":\"TX\",\"ZIPCOD\":75218,\"CDTLMT\":200,\"CHGCOD\":1,\"BALDUE\":25.00\u0000,\"CDTDUE\":0.00\u0000},\n{\"CUSNUM\":192837,\"LSTNAM\":\"Lee     \",\"INIT\":\"F L\",\"STREET\":\"5963 Oak St  \",\"CITY\":\"Hector\",\"STATE\":\"NY\",\"ZIPCOD\":14841,\"CDTLMT\":700,\"CHGCOD\":2,\"BALDUE\":489.50,\"CDTDUE\":0.50\u0000},\n{\"CUSNUM\":583990,\"LSTNAM\":\"Abraham \",\"INIT\":\"M T\",\"STREET\":\"392 Mill St  \",\"CITY\":\"Isle  \",\"STATE\":\"MN\",\"ZIPCOD\":56342,\"CDTLMT\":9999,\"CHGCOD\":3,\"BALDUE\":500.00,\"CDTDUE\":0.00\u0000}\n]",
    "stderr": ""
}

**Environment (please complete the following information):**
 - Extension version [e.g. 0..6.7]
 - IBM i OS version [e.g. 7.4]  (Pub400.com)

**Additional context**
PUB400.COM db2util version is db2util 1.0.11-dev.  I wonder if that might be the issue.  It seems like either of these statements  also cause the error:
```
select  cdtdue from qiws.qcustcdt;
select  baldue from qiws.qcustcdt;
```

**Comment by worksofliam** [comment]
On my test system I have:

```
db2util.ppc64                                      1.0.11-1
```

Let me see if I can recreate it.

**Comment by SJLennon** [comment]
I suspect PUB400 but I haven't managed to get them to load the latest db2Util.
@worksofliam

**Comment by SJLennon** [comment]
I just tried it on PUB400 in QP@TERM with no problem, so green screen handles it ok.
![image](https://user-images.githubusercontent.com/67484051/131547610-bac8e0c9-69c2-4098-b021-9f5ade5f4941.png)
@worksofliam

**Comment by SJLennon** [comment]
@worksofliam I created an issue on  IBM.db2Util.  https://github.com/IBM/ibmi-db2util/issues/17

(This is not urgent for me.)

**Comment by SJLennon** [comment]
@worksofliam Actually, it looks like there is a pull request in to fix this already. Maybe this will move it along.

**Comment by Nope7** [comment]
Same error but similar message...

"SQL:  Unexpected token  in JSON at position 2471"

Same behaviour: it works with specific select like 'SELECT field1, field2 FROM...' but does not work with 'SELECT * FROM ...."

Looks like * it's not correctly managed somewhere...

**Comment by worksofliam** [comment]
@Nope7 Hopefully the PR in the db2util repo will solve the issue.

It's got something to do with one of the types being returned by db2util

**Comment by SJLennon** [comment]
FWIW:  The db2Util folk have updated it to v1.0.12.  
https://github.com/IBM/ibmi-db2util/releases/tag/v1.0.12

This may have fixed the issue, though I don't know how long it takes to get it generally available for installation.

**Comment by SJLennon** [comment]
Holger installed V1.0.12 on PUB400.COM.  I test it and the problem is fixed. Issue Closed.

**Comment by worksofliam** [comment]
Nice!! @SJLennon
