### ISSUE TITLE
Library profiles should instead be connection profiles

### ISSUE THREAD

**Issue by getfoundational** [halcyon-tech/vscode-ibmi#266]
Hello,

Great extension.  I've never been able to get moved over to RDi and this seems a little more intuitive and "up my alley"!

I'd like to give a little background on my situation in hopes you can point me to a way to address this with the extension currently or consider enhancements that might help me and others that might be in a similar situation.

I have 60 or so customers that we do processing for on our system.  Each customer has their own library that houses their database files and source code.  When working on that client's "stuff", I always place their library just under QGPL in my library list to ensure their files are picked up when recompiling programs, etc.

I do see there is the option now to create profiles for the library lists so I think that'll help me to quickly change the library list.

One issue I am seeing is that in the member browsing section, I'll end up with a huge list of CL/RPG/DDS source when I'd add all of those for 60+ libraries.

I am wondering though if there is a better/different way to sort of segregate each customer so I could quickly jump between environments to get the proper library list but also get a smaller source member list?

Thank you again for all your work!

**Comment by worksofliam** [comment]
So to me, it sounds like profiles should cover a lot more than just the library list.

Perhaps connections can have many profiles which include all of their generic configuration like library list, current lib, source lists, object lists, etc.

Is that along the lines of what you'd like?

**Comment by getfoundational** [comment]
Yes, I think that would be perfect!

Then you *could* have numerous source files show up in the window or you could limit it as I was looking for.

It would essentially be different "development environments" when you'd switch profiles.

Thanks for responding so quickly and considering this.

**Comment by worksofliam** [comment]
I have updated the title of this issue to match the enhancement. It's a good idea and I like it a lot. 

Of course, the next issue is when this will get done.

**Comment by getfoundational** [comment]
Thank you for reviewing and considering it!

**Comment by worksofliam** [comment]
@getfoundational Having thought about this some more, I think I'd like more feedback on this before I implement it.

**Comment by getfoundational** [comment]
Makes sense.  Hopefully the wider community sees value in the approach/idea too.

**Comment by worksofliam** [comment]
After some further research, implementing this would likely break any existing profiles the user has.

**Comment by getfoundational** [comment]
Sorry for the added work, but that is great that you think it would be helpful.  I think it would add a great bit of flexibility to the concept of profiles for sure!

**Comment by worksofliam** [comment]
@getfoundational Will be available in the next release.

Will close when available.

**Comment by getfoundational** [comment]
Awesome!  Thanks so much for taking it on.
