### ISSUE TITLE
New IFS Browser restructuring in 0.7.0 and behavior and also removal of shortcut link

### ISSUE THREAD

**Issue by richardschoen** [halcyon-tech/vscode-ibmi#273]
With the new restructured IFS browser functionality it appears that I can add an IFS shortcut with the "+" icon from the IFS Browser or by right-clicking a directory link that's already there and selecting "Add IFS Shortcut".  Is that correct ? Just want to confirm. 

Also my user home directory shows in the IFS browser. I like that as a default shortcut, but just wanted to confirm the intent that home dir should always show in the list.

Overall the functionality seems to work nicely.

**Now for the question/issue:**

If I want to delete an IFS shortcut, there appears to be no option to delete it from the list once added.  I tried "Delete Object' and it deleted my IFS folder and all its contents instead of removing the link. Owwww. There should probably be a Delete IFS Shortcut option. Hope this makes sense.

**Comment by worksofliam** [comment]
> or by right-clicking a directory link that's already there and selecting "Add IFS Shortcut"

You can right-click
 on any directory and use the 'Add IFS Shortcut', include the existing shortcut.

> confirm the intent that home dir should always show in the list.

That is the default one, but you can add and remove shortcuts as you wish.

> If I want to delete an IFS shortcut, there appears to be no option to delete it from the list once added.

Correct. Right now there is no way to right-click on a shortcut to remove it. Instead, there is a minus button you can use in the view which will let you select which shortcut you want to remove.

**Comment by richardschoen** [comment]
Ah got it. Tool tips weren't working last night for some reason. 

Since you do have a right-click Add Shortcut it might be worth having the right-click remove IFS shortcut as well. 

Food for thought.
