### ISSUE TITLE
Search member by source date

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#279]
From @JDubbTX

> Also, how about ability to search based on source date?

Would love to hear from him about how he would like this to work.

**Comment by JDubbTX** [comment]
command that allows entry of a single date, and then options for < > or =.  In other words 'before, after, or on the date entered.  uppon hitting enter, the search could happen a couple of different ways.

you could have each line that meets the date criteria lhighlight get focus as you search forward (or backward if yeeally want to get fancy). 

or

just highlight all rows that meet the criteria somehow

**Comment by worksofliam** [comment]
A cool idea for sure. Could easily be done using VS Code decorations, much like how code coverage highlights lines.

**Comment by worksofliam** [comment]
The plan is to open a command where the user can enter a query which will then highlight all lines that match the query.

**Comment by worksofliam** [comment]
You won't believe it. 

<img width="1442" alt="image" src="https://user-images.githubusercontent.com/3708366/185766705-cbdd0786-68c8-4eae-b87c-c0eecfd8b048.png">

**Comment by JDubbTX** [comment]
> You won't believe it.
> 
> <img alt="image" width="1442" src="https://user-images.githubusercontent.com/3708366/185766705-cbdd0786-68c8-4eae-b87c-c0eecfd8b048.png">

😲😲😲

**Comment by worksofliam** [comment]
@JDubbTX are you able to test this for me? Check the attached PR.

**Comment by JDubbTX** [comment]
should be able to look at it tomorrow some.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by worksofliam** [comment]
Possible now with diff mode.
