### ISSUE TITLE
ILE verify

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#286]
Do we need a verify feature?

E.g. a button that runs the active sources through the `CRTXXXXXX` with `OPTION(*NOGEN *EVENTF)? Maybe it runs automatically?

Maybe after the user stops typing for x seconds, it automatically runs the verify and loads the errors?

Would love some thoughts on this.

Maybe people can help fill this table out as we'd need to determine what type of source it is (MOD vs PGM) in order to compile

| Type | Member Parameter | IFS Parameter | How to determine *MOD vs *PGM in source code |
|---|---|---|---|
| SQLRPGLE / RPGLE | SRCFILE+SRCMBR | SRCSTMF | If NOMAIN is defined, it's a module |
| CL | SRCFILE+SRCMBR | SRCSTMF | ? |
| C / CPP? | SRCFILE+SRCMBR | SRCSTMF | If main is defined, it's a program |
| COBOL | SRCFILE+SRCMBR | SRCSTMF | ? |

**Comment by worksofliam** [comment]
Another option is to let the user select what verify to use. 

* A new status bar item will show whether the file being edited has been configured to verify.
* Clicking on the status bar item for an unconfigured source will prompt a select box for the user to tell the extension if this is a 'Module', 'Program', escape to cancel
   * Based on the table above, we may be able to automatically figure it out when the item has been clicked.
* When the type has been determined, the text changed handler will trigger the verify after X seconds of no typing
* Clicking the button will remove the configuration for this member and also disable the verify feature

**Comment by SJLennon** [comment]
Back in #64 there was similar discussion and my suggestion was a verify button.  

I still like that idea--on request, save to a temporary location and compile.  If there was some way that the action could know that it was verify and not compile, couldn't we let the user pick the action to run? (I say this not knowing how VSCODE or the extension works these things internally.)

**Comment by worksofliam** [comment]
@SJLennon you bring up a good point.. maybe the verify trigger is simply when the user saves the document.

Yeah.. the verify could be a simple as letting the user chose which Action the 'verify' process should run. Another good point!

Liam

**Comment by worksofliam** [comment]
Users can easily add their own verify.
