### ISSUE TITLE
Usage of SEU commands

### ISSUE THREAD

**Issue by szsascha** [halcyon-tech/vscode-ibmi#287]
**Is your feature request related to a problem? Please describe.**
I was just thinking about how cool it would be to have a full featured SEU command line in VSCode. I don't mean the commands on lines but in the input field at the top.
Two main reasons for this:
1. I personally really like to use SEU commands. You're able to achieve pretty much with a very simple syntax.
2. It would open a very good opportunity for veterans to get very fast productive with this plugin 

**Describe the solution you'd like**
As described I would prefer only the command line from the top of SEU. Not the line commands. But that's maybe something for the future.

I could imagine that this can easily be done with VSCode's integrated command line. You use a combination of keys and the command line opens. Then you can type in your SEU command. After pressing enter the command will be executed.

It will be faster to use than in SEU since you press a key combination instead of hitting tabulator 1000 times. So veterans without VSCode experience will also get very fast good productivity results.

**Describe alternatives you've considered**
The alternative is simply to not implementing this feature.

**Additional context**
Information can be found there: https://wiki.midrange.com/index.php/SEU

In particular it's about:
SEU Command Line
FIND or F - find string in source member
SAVE - save current source member
HIDE - hide lines containing a string (i.e. HIDE 'C*' will hide all source lines containing the string C*)
TOP or T - Position to top of source member
BOTTOM or B - Position to bottom of source member

**Comment by szsascha** [comment]
#279 could be use this feature.

I guess there is actually no possibility to use the SEU FIND command to search by date. But we could utilize this and extend this command a bit in VS Code.

**Comment by SJLennon** [comment]
Personally, I'm not sure this is worth the effort.  Better, in my opinion, to move away from SEU and to learn move about VSCODE commands,  which are fairly intuitive anyway.

FIND:  VSCODEs Ctrl +F is a single keystroke and gives more features.
SAVE: VSCODE has Ctrl + s
TOP: VSCODE has Ctrl + home
BOTTOM VSCCODE has Ctrl + end

HIDE: Don't know if there is anything similar in VSCODE, but I Inever used it in my SEU days.  Though I think RDi allows  you to hide comments.

**Comment by worksofliam** [comment]
Haha, the precious SEU commands! While it would be good, I don't believe it belongs in this extension.

It might be simple enough for another extension to add a command that launches an input box for the commands and then executes the command on the active editor.

It could be related to #279, but that actually won't be command-driven (at least right now).
