### ISSUE TITLE
A kind of "RPG doc" like Javadoc

### ISSUE THREAD

**Issue by szsascha** [halcyon-tech/vscode-ibmi#288]
**Is your feature request related to a problem? Please describe.**
I currently don't know if there is already something like this but I could imagine that it could be pretty useful.
With Javadoc you're able to define a structured documentation for method's, classes and so on. That documentation is utilized by the IDE's to prompt all defined information in a structured way when you hover a method for example. You can see immediately what argument is used for what.
This could be nice to use in RPG for Programs (documentation for program parameters), procedures (documentation of arguments and returns) and subroutines.

**Describe the solution you'd like**
There are many ways to solve this pretty easily. Each way has 2 parts.
Part 1: Documentation - Describe the program / procedure
Part 2: Show the documentation (for example on hovering)

For Part 1 is conceivable to use a special kind of comments. For example *? instead of * in fixed ILE RPG
Part 2 can be done by indexing and parsing of the sources.

**Describe alternatives you've considered**
There are many ways to implement this. At the moment I'm not able to decide what alternative would be the best. I also don't know if there is already something like this.

**Additional context**
A bit about Javadoc: https://en.wikipedia.org/wiki/Javadoc

**Comment by worksofliam** [comment]
@szsascha This is a good idea and I have a funny story for this.

The RPGLE tools already built-in already have a way for the user to provide documentation for their RPG code.

As you may know, we already provide content assist. But, it is possible to improve the content assist with your own comments you can write like so:

```
//@ Makes a call to the Geotab Get() API.
//- authinfo = Geotab_Auth('':'':'':'');
//- data = Geotab_Get(authinfo:'Rule');
Dcl-Pr Geotab_Get Pointer ExtProc;
  //@ The token from Geotab_Auth
  pSession     Like(Geotab_Token);
  //@ The Entity type (from Geotab)
  pType    Pointer Value Options(*String);
  //@ The max amount of elements returned
  pLimit   Int(5) Const Options(*NoPass);
  //@ The search object, if any. 
  //@ Object can be created with Geotab_NewObject().
  pSearch  Pointer Options(*NoPass);
End-Pr;
```

* Any line that starts with `//@` will be used for comment in the next procedure or procedure parameter.
* Any line that starts with `//-` will be used as an example for the next procedure.

It also supports variables, contents, and subprocedure I believe.

Copy the above example into an RPGLE source and you will see it provides hover assist.

It is an undocumented feature that I use all the time. See a large example here: https://github.com/SeidenGroup/geotab_rpgle_sdk/blob/master/headers/geotab.rpgle_h

Writing documentation for this would be a good idea, but it was never finalized. I wonder if instead we should just support ILEdoc. You can see an example of that in this PR: https://github.com/sitemule/noxDB/pull/39/files#diff-bb97672fbaff327f88f37cf71b9bab09b3573b7c58a15a60a6da8fc08a075209R81

**Comment by worksofliam** [comment]
See my implementation of the documentation parser here: https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/languages/rpgle/linter.js#L409

* It parses all code for procedures, variables, constants, subroutines, etc
* It also looks for the `//@` comments and `//-` comments
* It returns useful objects with all the definitions and their comments - this is where the docs could be generated from.
* I also built a website to show documentation built using this style: https://iledocshub.herokuapp.com/?docs=https://raw.githubusercontent.com/SeidenGroup/geotab_rpgle_sdk/master/headers/geotab.rpgle_h

Lots of potential for ideas

**Comment by worksofliam** [comment]
For the time being, I am going to create a new issue to generate markdown documentation based on my current implementation.

**Comment by worksofliam** [comment]
@szsascha I would need to add COBOL, but do you think it'd be better to follow the ILEdoc format: https://bitbucket.org/m1hael/iledocs/wiki/ILEDocs_Syntax

**Comment by szsascha** [comment]
@worksofliam 

I really like your documentation format. But I also think that it would make sense to go the most standardized way. In my opinion this is something like Javadoc. Many developers are familiar with this kind of documentation. So I think it would be better to use ILEDoc.

But I'm really like both. It's your decision.

**Comment by worksofliam** [comment]
Okay, I will look into supporting ILEdocs! Though, I still only aim at supporting RPGLE free-format (`**FREE`)

Based on this documentation: https://bitbucket.org/m1hael/iledocs/wiki/ILEDocs_Syntax

Here are some tasks:

* [ ] Remove `//@` support
* [ ] Remove `//-` support
* [ ] Understand the new `@` tags in ILEdocs
* [ ] Translate ILEDocs documentation style and use it in the hover assist
* [ ] Generate documentation based on ILEdocs

**Comment by worksofliam** [comment]
Making some great progress! 

![image](https://user-images.githubusercontent.com/3708366/133939507-a5a749d7-78f5-4d71-936d-bf43c97c0440.png)

**Comment by worksofliam** [comment]
Content assist on the ILEDocs tags

**Comment by worksofliam** [comment]
Will be available in next release.
