### ISSUE TITLE
Why does Code for IBM i depend on the walkthrough extension?

### ISSUE THREAD

**Issue by chrjorgensen** [halcyon-tech/vscode-ibmi#292]
I installed the latest Code for IBM i extension - version 7.3 - manually using "Install from vsix".

But now the extension can't be activated:

![billede](https://user-images.githubusercontent.com/13275072/133100878-415fec00-1c83-4f74-be45-628e25c554e9.png)

Seems it depends on the walkthrough extension (which I haven't installed).
Shouldn't it be the other way around? This does not seem logical to me...

**Comment by worksofliam** [comment]
Interesting. Sorry about this - my focus is the Marketplace.

The walkthroughs are depended on so new users have some tutorials to follow along with if they've never used it before.

I am happy to change this, though.

**Comment by chrjorgensen** [comment]
Fair enough - not an issue, I was just surprised of this new dependency.

I'm not keen on too much dependency between software packages - I prefer to have independent blocks, which can work with but do not require each other.

**Comment by worksofliam** [comment]
@chrjorgensen What's the status of this?

Would you rather us remove the dep or shall we close this for now? :)

**Comment by chrjorgensen** [comment]
@worksofliam Let's keep the dependency - it's better for new users to have tutorials at hand (which this dependency gives them) without having to install any additional extension.

The rest - more experienced - of us can live with having this extra extension... :-)
