### ISSUE TITLE
Character conversion problem

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/vscode-ibmi#293]
Hi,
**Describe the bug**
in one of the last release of code for i it gave me a character conversation problem.
Unfortunately we have some file which contain § character in field name. Recently if I open my program from member section this character is wrong converted:

![image](https://user-images.githubusercontent.com/9719313/133127709-70e6ff6b-7c3d-42d3-860a-8116dd0872a6.png)

**To Reproduce**
I have a source file with ccsid 280 (italian).
From seu i see this:
![image](https://user-images.githubusercontent.com/9719313/133127905-eeccec86-566f-424f-b185-f03c23d407b6.png)
while from member section of vscode I see  
P�NRf 
instead of:
P§NRF

**Environment (please complete the following information):**
 - Extension version v0.7.3
 - IBM i OS version V7R3

**Additional context**
If I try to make a cpytostmf in my /home folder specifying the parameter:
STMFCCSID(1208) 
and opening it from ifs browser the character § is well converted:

![image](https://user-images.githubusercontent.com/9719313/133128421-e7afd8ff-e38e-40b2-861e-abf30ce75e95.png)

Many thanks

**Comment by worksofliam** [comment]
Hi @pabloto 

Do you have source date support enabled? You should disable it and open the member again to see if that solves the problem.

Also see this answer on another issue: https://github.com/halcyon-tech/vscode-ibmi/issues/198#issuecomment-884245064

Does your system have `QCCSID` setup, as well as other env vars mentioned in that answer?

**Comment by pabloto** [comment]
Hi @worksofliam,

Yes I try date support, and disabling it the source have the correct character:

![image](https://user-images.githubusercontent.com/9719313/133143852-7f1d7331-d98f-4eec-b61e-dfd0b0d0ab5f.png)

making env command from shell this is the output:

SHELL=/QOpenSys/pkgs/bin/bash
QIBM_PASE_CCSID=1208
PWD=/home/myuser
LOGNAME=myuser
TZ=<CET>-1<CEST>,M3.5.0,M10.5.0
HOME=/home/myuser
LANG=IT_IT.UTF-8
SSH_CONNECTION=192.168.0.64 59109 192.168.0.11 22
TERM=xterm
USER=myuser
LE_WORKING_DIR=/home/myuser/.acme.sh
LOGIN=myuser
SHLVL=1
PS1=\u@\h@\W$ 
SSH_CLIENT=192.168.0.64 59109 22
PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
MAIL=/var/spool/mail/myuser
SSH_TTY=/dev/pts/0
_=/QOpenSys/pkgs/bin/env

But I'm not sure than QIBM_PASE_CCSID=1208 have effect on V7R3.

Many thanks

**Comment by benetti-smeup** [comment]
@worksofliam 
Hi Liam. I have the same problem with £ in the member name, and I have env variables
PASE_LANG 'IT_IT'
QIBM_PASE_CCSID '1208'
set from my previous issue.

Disabling date support it works again.
Using the source-dates-ibmi-0.0.2.vsix it works, so it seems the issue is related to source-dates porting in the core extension.

**Comment by worksofliam** [comment]
@benetti-smeup Thanks for sharing.

This actually means the issue is with `Rfile`. I may revert it back to the SQL method to resolve this issue.

Liam

**Comment by worksofliam** [comment]
I wonder if me calling `Rfile` thought QSH would make a big difference.

https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/filesystems/qsys/complex/content.js#L37

Something to look into later.

**Comment by worksofliam** [comment]
thanks to Calvin B for looking into this

```
bash-5.1$ echo "/usr/bin/Rfile -sr /QSYS.LIB/BARRY.LIB/GERMAN.FILE/TEST.MBR" | /QOpenSys/usr/bin/qsh
000100200706dfsdfsd
000200200706
000300200706Mit freundlichen Gr??en aus der S?dwestpfalz
000400200706
000500200706testing ? ? ? sdfsdf
000600200706
000700200706
```

Looks like `Rfile` is inheriting from the job CCSID and not the CCSID of the file.

I will be replacing `Rfile` with the original SQL implementation.

**Comment by worksofliam** [comment]
Allotted time to get this fixed and released tonight.

**Comment by worksofliam** [comment]
![image](https://user-images.githubusercontent.com/3708366/133506075-e5b74b12-66b9-4d14-bd53-452314d26c42.png)

Reverted back to the SQL method. Requires SQL to be enabled.

**Comment by worksofliam** [comment]
@pabloto @benetti-smeup 

0.7.4 has been released. Please update and see how it goes.

**Comment by benetti-smeup** [comment]
@worksofliam 
0.7.4 works for me.
Thanks!

**Comment by worksofliam** [comment]
Awesome!!

**Comment by pabloto** [comment]
Hi @worksofliam,

for me it doesn't still work, Could you try to create a pfsrc like this:
CRTSRCPF FILE(yuorlib/QRPG280) CCSID(280)
add this to vscode 
then a create a source member like this:

testchar.rpgle

and I wrote a comment line:


**free

// comment line with strange character
// §àòèì

when it's automatically save I obtain this:

**free

// comment line with strange character
// Â§Ã Ã²Ã¨Ã¬

I have now code for i version: 
v.0.7.4

my qccsid system value is 280

I have db2util, whether it has activated source date that no the result is the same.

Many thanks

**Comment by benetti-smeup** [comment]
@pabloto 
Have you tried setting env variables?
PASE_LANG 'IT_IT'
QIBM_PASE_CCSID '1208'

https://github.com/halcyon-tech/vscode-ibmi/issues/198#issuecomment-871493601

**Comment by pabloto** [comment]
from my mac i made:

% ssh -t myuser@myibmi 'env'

Welcome to myibmi!

SHELL=/QOpenSys/pkgs/bin/bash
QIBM_PASE_CCSID=1208
LANG=IT_IT.UTF-8
TERM=xterm
USER=myuser
LOGIN=myuser
SHLVL=0
SSH_CLIENT=192.168.0.141 55875 22
PATH=/QOpenSys/pkgs/bin:/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
MAIL=/var/spool/mail/paolos
SSH_TTY=/dev/pts/2
_=/QOpenSys/pkgs/bin/env
Connection to myibmi closed.

**Comment by worksofliam** [comment]
@benetti-smeup @pabloto don't you need to set those at a WRKENVVAR level?

**Comment by worksofliam** [comment]
![image](https://user-images.githubusercontent.com/3708366/133624706-78132c08-3d17-4950-a948-a19c5f59c449.png)

I tested it and it works for me.

**Comment by benetti-smeup** [comment]
> @benetti-smeup @pabloto don't you need to set those at a `WRKENVVAR *SYS` level?

Yes.

**Comment by pabloto** [comment]
I had it:

![image](https://user-images.githubusercontent.com/9719313/133627837-c9a45781-77d9-48d0-b18f-09a7d7455501.png)

**Comment by benetti-smeup** [comment]
> I had it:
> 
> ![image](https://user-images.githubusercontent.com/9719313/133627837-c9a45781-77d9-48d0-b18f-09a7d7455501.png)

after setting wrkenvvar I had to restart my IBM i.

**Comment by pabloto** [comment]
I restart, but nothing change...

**Comment by pabloto** [comment]
Hi probably the problem could be this:

![image](https://user-images.githubusercontent.com/9719313/133632017-0bbdde65-1f43-448b-be15-2f71391e46e8.png)

![image](https://user-images.githubusercontent.com/9719313/133632056-937535c2-709f-44e0-90e2-03c4241e0b73.png)

**Comment by worksofliam** [comment]
Huh! That actually might be it. Maybe I need to set the ccsid when the file is created.

**Comment by worksofliam** [comment]
Need to set the CCSID before executing the SQL here: https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/filesystems/qsys/complex/content.js#L105

**Comment by worksofliam** [comment]
@pabloto what happens if you change the CCSID of the file to UTF8 (`CHGATR CCSID(1208)`) and then try and run the statement - does it put the characters in correctly?

**Comment by benetti-smeup** [comment]
My IFS files have CCSID 1208

**Comment by pabloto** [comment]
![image](https://user-images.githubusercontent.com/9719313/133639330-9ae1d8e4-c275-4a73-b35d-08e60a32db0e.png)

![image](https://user-images.githubusercontent.com/9719313/133639417-f32886c6-c8c5-4318-ab20-c3a83126c1d1.png)

**Comment by worksofliam** [comment]
@pabloto THat worked! Ok, I will make another fix this evening and get it out.

@benetti-smeup Yes, on 7.4 the default IFS CCSID for new files is 1208 - but not before that.

**Comment by benetti-smeup** [comment]
@worksofliam yes, but I am on 7.2.

**Comment by worksofliam** [comment]
@benetti-smeup that makes this even more fun! I wonder what env var affects that.

**Comment by pabloto** [comment]
From ssh terminal making env command I have this:

QIBM_PASE_CCSID=1208

but if I try:

touch aaa.txt

the ccsid of this file is 819.

If you know how to set ccsid 1208 by default please let me know.

Many thanks

**Comment by worksofliam** [comment]
```
bash-5.1$ /usr/bin/setccsid -h
setccsid: 001-3047 usage: setccsid [-R [-H | -L | -P]] [-h] ccsid file ...
```

This is what the extension will run before executing the SQL.

**Comment by worksofliam** [comment]
@pabloto the fix is out. Please give it a go and report back here!

**Comment by benetti-smeup** [comment]
@worksofliam
0.7.5 works for me.
Thanks!

**Comment by worksofliam** [comment]
@benetti-smeup Awesome - thank you!!

**Comment by pabloto** [comment]
@worksofliam works for me too, but now it doesn't work the source date. Is it true?

Many thanks

**Comment by worksofliam** [comment]
@pabloto are you saying the source date support does not work in 0.7.5?

**Comment by pabloto** [comment]
Sorry @worksofliam my fault. 

Now the date support works!!! 

many thanks for you help!
