### ISSUE TITLE
Please add Content Assist for Commands (.CMD)

### ISSUE THREAD

**Issue by thebeardedgeek** [halcyon-tech/vscode-ibmi#295]
I am writing some commands and would like to be able to use Content Assist in VS Code.
![image](https://user-images.githubusercontent.com/9466407/133623393-577ab8ad-5824-4543-8bb0-a99c36ec45f0.png)

**Comment by worksofliam** [comment]
Hit a bit of a blocker on making the languages APIs in VS Code support more than one language ID.

https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/languages/clle/clCommands.js#L23

https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/languages/clle/clCommands.js#L103
