### ISSUE TITLE
Generate DDL from object browser

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#297]
Right-clicking on a database object and clicking Generate SQL should be a thing

**Comment by szsascha** [comment]
Do you mean the generation of the CREATE TABLE SQL?

Do you know if there are APIs / tools that can be used for this?

**Comment by worksofliam** [comment]
@szsascha yes, there is!

https://www.ibm.com/docs/en/i/7.4?topic=services-generate-sql-procedure

**Comment by szsascha** [comment]
I've just looked more into it.

My current plan is to open a new, unsafed editor tab with the CREATE TABLE statements after rightclicking a file in the object browser.

Is there already a piece of code in the extension where a new, unsafed editor tab is opened? I already tried the following but it leaves without exception on Uri.parse. https://stackoverflow.com/questions/41068197/vscode-create-unsaved-file-and-add-content

**Comment by worksofliam** [comment]
@szsascha Yes! The search results open up in a brand new tab - check that out!

**Comment by szsascha** [comment]
@worksofliam I just implemented this feature. Would be really nice if you could have a look on it :)

**Comment by worksofliam** [comment]
I'll check it out!

**Comment by worksofliam** [comment]
Part of the Db2 for i extension. It will not be added to the base.
