### ISSUE TITLE
Database Browser not working: Error occurred in SQL Call Level Interface SQLSTATE=HY009 SQLCODE=-99999

### ISSUE THREAD

**Issue by richardschoen** [halcyon-tech/vscode-ibmi#300]
**Describe the bug**
Cannot expand library to list available files. Get error: **Error occurred in SQL Call Level Interface SQLSTATE=HY009 SQLCODE=-99999**

**To Reproduce**
1. Go to database browser
2. Add QIWS or any other library to list and click the arrow to expand the list.
3.  Error from console:

```
/tmp: DB2UTIL_JSON_CONTAINER=array /QOpenSys/pkgs/bin/db2util -o json "select TABLE_NAME, TABLE_TYPE, TABLE_TEXT, BASE_TABLE_SCHEMA, BASE_TABLE_NAME from QSYS2.SYSTABLES where TABLE_SCHEMA = 'QIWS' order by TABLE_NAME asc"
/tmp: DB2UTIL_JSON_CONTAINER=array /QOpenSys/pkgs/bin/db2util -o json "select * from QSYS2.SYSCOLUMNS where TABLE_SCHEMA = 'QIWS' order by ORDINAL_POSITION asc"
{
    "code": null,
    "signal": null,
    "stdout": "[\n{\"TABLE_NAME\":\"QCUSTCDT\",\"TABLE_TYPE\":\"P\",\"TABLE_TEXT\":\"PC Support Customer File\",\"BASE_TABLE_SCHEMA\":\"null\",\"BASE_TABLE_NAME\":\"null\"},\n{\"TABLE_NAME\":\"QCUSTCDTEM\",\"TABLE_TYPE\":\"P\",\"TABLE_TEXT\":\"PC Support Customer File\",\"BASE_TABLE_SCHEMA\":\"null\",\"BASE_TABLE_NAME\":\"null\"},\n{\"TABLE_NAME\":\"QCUSTCDTSV\",\"TABLE_TYPE\":\"P\",\"TABLE_TEXT\":\"PC Support Customer File\",\"BASE_TABLE_SCHEMA\":\"null\",\"BASE_TABLE_NAME\":\"null\"},\n{\"TABLE_NAME\":\"QCUSTCDT3\",\"TABLE_TYPE\":\"T\",\"TABLE_TEXT\":\"\",\"BASE_TABLE_SCHEMA\":\"null\",\"BASE_TABLE_NAME\":\"null\"},\n{\"TABLE_NAME\":\"QCUSTCDT4\",\"TABLE_TYPE\":\"T\",\"TABLE_TEXT\":\"\",\"BASE_TABLE_SCHEMA\":\"null\",\"BASE_TABLE_NAME\":\"null\"},\n{\"TABLE_NAME\":\"QMENUSRC\",\"TABLE_TYPE\":\"P\",\"TABLE_TEXT\":\"PC Organizer Menu Source\",\"BASE_TABLE_SCHEMA\":\"null\",\"BASE_TABLE_NAME\":\"null\"}\n]",
    "stderr": ""
}

{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "Error occurred in SQL Call Level Interface SQLSTATE=HY009 SQLCODE=-99999"
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/9791508/133892332-89519b80-d60c-4f96-bee3-98634b6ed9ac.png)

**Environment (please complete the following information):**
 - Extension version [0.7.7]
 - IBM i OS version [e.g. 7.3]
 - dbutil [1.0.12]

**Comment by SJLennon** [comment]
FWIW:  Latest release of db2Util is 1.0.12.  Could your version of 1.0.2 be the problem?
@richardschoen @worksofliam

**Comment by richardschoen** [comment]
Typo.

**Comment by SJLennon** [comment]
On PUB400.COM.  I added QIWS. Expanded it. Seems to work for me. Did I miss a step?

![image](https://user-images.githubusercontent.com/67484051/133894887-63c13aac-73ea-4941-accb-89fb74231587.png)

@richardschoen @worksofliam

**Comment by worksofliam** [comment]
@SJLennon I think Richard's problem is that when executing SQL statements, it is not inheriting the library list.

Actually, this is because db2util, I believe, only supports SQL naming and therefore does not use the library list. We might have a way to set the current schema to the current library, though.

**Comment by worksofliam** [comment]
Did some research and apparently not.

I made an issue for it, but right now you will have to qualify your SQL objects.

https://github.com/IBM/ibmi-db2util/issues/19

**Comment by richardschoen** [comment]
It is actually getting the list of table from what I pasted above. It's just not rendering in the list when I attempt to expand the library name.  Same error occurs with any library.

**Comment by richardschoen** [comment]
Interestingly I can get the files to show up when I hit pub400.com. 

However when I Control-R the SQL doesn't run.

**Comment by SJLennon** [comment]
Ctlr-R works for me on PUB400.COM.  Remember that your statement needs to be in a .SQL file. 
Even works with a /, but that's something that was added in some (fairly) recent OS400 update.
Something odd about your machine.  CCSID=65535 perhaps?
@richardschoen 
![image](https://user-images.githubusercontent.com/67484051/133909000-cab2cdda-79fc-4111-ae94-73d2297da4ca.png)

**Comment by richardschoen** [comment]
I was testing on pub400 to see if it worked. Something wrong with Control-R key mapping. 

On my system, hard to say.  As mentioned above db2util seems to run based on the JSON results but then an error is thrown.

**Comment by richardschoen** [comment]
I actually don't see any key bindings for Control-R 

![image](https://user-images.githubusercontent.com/9791508/133911224-b6957346-9611-41f8-94fc-ea74cb2c09c2.png)

**Comment by richardschoen** [comment]
OK figured out my key binding issue, so it definitely works with pub400, but not my box even though db2util V1.0.12 works fine and the library queries seem to be returning results.

**Comment by worksofliam** [comment]
@richardschoen what do we need to do to help you get this resolved?

**Comment by richardschoen** [comment]
OK, now that key binding for Control-R is resolved I can run an individual query from a member via Control-R.  I just can't use the database browser. 

Still gets the original error.  

So looks like the issue is related to the database browser and listing contents form a library not working as expected. 

Just tested the SQL queries with db2util and looks like this one does not work on V7R3 perhaps because it causes the actual error:
```/QOpenSys/pkgs/bin/db2util -o json "select * from QSYS2.SYSCOLUMNS where TABLE_SCHEMA = 'QIWS' order by ORDINAL_POSITION asc"```

So I guess that's the culprit for the database browser.

**Comment by richardschoen** [comment]
OK, so the query works in ACS but not with db2util.  Getting closer.

**Comment by richardschoen** [comment]
This is the guy who throws error on V7R3 and no on V7R4. Something related to data type casting perhaps on V7R3 for any unicode fields perhaps ?

I changed my sysval QCCSID to 37 and still got the error. 

/QOpenSys/pkgs/bin/db2util -o json "select * from QSYS2.SYSCOLUMNS where TABLE_SCHEMA = 'QIWS'"

**Comment by worksofliam** [comment]
@richardschoen Worth raising an issue in the Db2util repo?

**Comment by richardschoen** [comment]
Will do. However I probably won't be the only to see this issue with V7R3.  

Must be something brittle in db2util.

**Comment by richardschoen** [comment]
db2util issue created: https://github.com/IBM/ibmi-db2util/issues/20

**Comment by richardschoen** [comment]
@worksofliam  Wasn't there some sort of environment variables you were mentioning the other day that needed to be set for QSH/PASE calls ? Not sure if it's relevant.

**Comment by richardschoen** [comment]
Looks like the COLUMN_EXPRESSION field which is a large clob might be the culprit. Can you tweak to query to only include fields needed for the query. This clob field can probably be ignored.

**Comment by richardschoen** [comment]
Appears to be a TR issues with DB2 on V7R3.
