### ISSUE TITLE
Server browser improvements

### ISSUE THREAD

**Issue by szsascha** [halcyon-tech/vscode-ibmi#303]
**Is your feature request related to a problem? Please describe.**
The new server browser looks pretty nice. But I think we could add a bit more functionality to it.

**Describe the solution you'd like**
I'm missing the inputs to change the connection name, host, username and password. Would expect it in the "Settings" tab, opening on rightclick and "Connection settings".
I also would expect a kind of "after connection serverbrowser" where you can see all connections. The current connection is highlited and can be disconnected by a click on a "stop" button. If you click the "play" button of another connection, while connected, you'll be asked if you're sure and data will be loss during disconnection. Then the current connection closes and a new connection, to another server is started.

**Comment by worksofliam** [comment]
So this sounds like two enhancements:

1. A way to edit the host/IP, username and private key on an existing connection
2. A way to correctly disconnect and reconnect to another server without having to disconnect from the current connection / reload the environment.

**Comment by szsascha** [comment]
@worksofliam 

Yes. You're right. But the first one is more important in my opinion. The second one came to me while writing.

**Comment by worksofliam** [comment]
@szsascha I will assign this to myself and work on point 1.

* [ ] Add ability to edit host name, user name, and private key on a connection.

**Comment by worksofliam** [comment]
@szsascha What do you think?

**Comment by szsascha** [comment]
@worksofliam Great! You're so fast with the implementations :)
