### ISSUE TITLE
Add Copy Option to IFS Browser

### ISSUE THREAD

**Issue by thebeardedgeek** [halcyon-tech/vscode-ibmi#311]
Currently the IFS Browser does not include a Copy stream file option.
![image](https://user-images.githubusercontent.com/9466407/134204026-bc8faa54-eeda-4065-acf6-0995e44df82d.png)

Can we add this option please? It would make working with the IFS easier.

**Comment by priceaj** [comment]
@thebeardedgeek I have added this here https://github.com/priceaj/code-for-ibmi/tree/CopyIFS%23311 if you want to have a go!
