### ISSUE TITLE
Create a "Duplicate Action" capability

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#312]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a convenience when creating new Actions.

**Describe the solution you'd like**
Click on Actions and it shows the list of action.  I'd like to be able to right click on an action and have an option to bring up the "New Action" form, populated with the values from the action I right clicked on.  The Action name could be blank. Or, perhaps better, be populated with the original action name prepended with **(Copy)**, e.g., **(COPY) Call program** if I'd clicked on the Call program action.
I suggest the right click option would be "Duplicate this action".  Right clicking now gives Cut, Copy and Paste.  Copy certainly doesn't seem to do anything.
**Describe alternatives you've considered**
I tried clicking Actions twice to get two forms open, then cutting and pasting. I found it got a bit confusing since both tabs said "Work with Actions".

**Comment by worksofliam** [comment]
New duplicate action button:

![image](https://user-images.githubusercontent.com/3708366/134446107-237babf5-425d-4742-a075-1bc33befb085.png)
