### ISSUE TITLE
Problem in save of source member

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/vscode-ibmi#314]
**Describe the bug**
I have the AutoSave function activated in my vscode setting, working on a source sometimes it gave me this error:

![image](https://user-images.githubusercontent.com/9719313/134324713-c81e6ba7-5ef6-4f5a-bc5b-2fcc8db4e431.png)

If I try to retry it always gave me the same error. the only workaround I found until know is to copy the source locally, close vscode and restart again.

**Environment (please complete the following information):**
 - Extension version v0.7.7
 - IBM i OS version V7R3

**Comment by worksofliam** [comment]
Does this happen specifcally after you create a new member? Or generally all the time?

**Comment by pabloto** [comment]
It happen me in the last 3/4 days, until now in a random manne.
I didn't understand when the issue start, during the day I sometimes left a source open, and sometimes it gave me this error. 
If I can reproduce it I'll tell you how.

Many thanks

**Comment by worksofliam** [comment]
I actually found the issue. It's do with members that have `0.` in them. Will get a fix out ASAP.

**Comment by worksofliam** [comment]
Since this is a bug that is only a problem with source dates enabled, I implemented this fix:

1. Fetch the length of SRCDAT (e.g. the record length) when the member is opened
2. If the member has no rows yet, default to 80 (who the hell uses less than 80?)
3. When saving the member, trim any line longer than the record length.

Fix out in the next 30 mins.

**Comment by worksofliam** [comment]
@pabloto 0.7.8 is out with the fix.

I will close this but please post here if you have further issues.

**Comment by pabloto** [comment]
Hi. the issue seems solved.
Many thanks

**Comment by worksofliam** [comment]
@pabloto Please answer these:

* Db2 enabled?
* What is the source length?
* Can you share with me a snippet of code to recreate it?

**Comment by worksofliam** [comment]
@pabloto I just recreated it with the same record length and the content you provided. It saved with no issue.

Is it at all possible the source is being locked by someone else?

**Comment by worksofliam** [comment]
@pabloto What is your auto save configuration set to?

**Comment by pabloto** [comment]
> @pabloto Do you get the issue if you turn off auto save and just save manually?

I'll try and I'll give you a feedback.

**Comment by worksofliam** [comment]
@pabloto Did you find out if the member is being locked somewhere else?

**Comment by pabloto** [comment]
I @worksofliam I think then something happen when you put the date into the stream file in /tmp, as you can see there are a lot of NaN.
