### ISSUE TITLE
Provide Object Filter in Object Browser

### ISSUE THREAD

**Issue by dlarsencbk** [halcyon-tech/vscode-ibmi#319]
**Is your feature request related to a problem? Please describe.**
In order to Edit Source files in this extension, each  library and file combination must be entered  individually in the member browser. Our Libraries contain a mix of production objects and source files.  Some libraries have over a hundred source files named by project. This process also requires time to individually identify source files for over 30 libraries and manually add all those libraries and source files to the member browser.  Not all files end in SRC and not all file names start with Q. The resulting work  for this extension would take too much time and is not practical.

**Describe the solution you'd like**
In RDI, Remote Systems View, there is an object filter that can automatically identify and produce a list of just source files. This is extremely helpful to have the system do this automatically
A filter in the Object Browser (or where ever it makes sense) would be an extremely valuable addition to this product.

**Describe alternatives you've considered**
Alternatives include manually adding each library/source file combination individually. Too time consuming. 
Another would be to move the source files to their own library. That involves creating hundreds of other libraries and redesigning the applications. Not practical.

**Additional context**
RDI Object Filter
![image](https://user-images.githubusercontent.com/84473787/134552633-fb5c737b-4e92-4ade-a505-472b4e5cda44.png)

**Comment by worksofliam** [comment]
Hey @dlarsencbk 

Thanks for raising this!

While I really like the idea. I am struggling to think how we would implement it or how it would work from the VS Code side. I am going to add the 'help wanted' tag to see if anyone else would like to chime in.

p.s. I understand adding X source files can be slow. You can also manually edit the JSON for that view to add more.. which might be a tad faster.

Liam

**Comment by SJLennon** [comment]
Bearing in mind that I don't understand much about the capabilities/limitations of VSCODE extensions, here's my take on this one request:

I envisage being able to right click on a library in the member browser, and being presented with a list of SRCPF files in the library. 

From this list you could pick one or more source files to be added to the member browser. 

The current setting could then be saved with an appropriate profile name and thus could be easily reloaded.

It wasn't clear whether the request also included a library level browser.  I suppose such an option could also be done if the above approach for SRCPF was feasible, and you would be able to pick only one library and would then be presented with the list of SRCPFs in it.

But I wonder how many other shops have a similar setup?

**Comment by worksofliam** [comment]
I am still wondering how this would work. I'd like a concrete idea before just slapping something together. Any further input would be great.

**Comment by worksofliam** [comment]
I think I understand this requirement a bit better now. Here's my take:

* Member Browser and Object Browser to be completely replaced with a new `Object Browser`, which combines both worlds of the member and object browser.
* Much like the member browser and the object browser, the user will be able to add a filter to the view. The filter can be against these items. All but the library filter will support the `*` wildcard.
   * Library
   * Object
   * Member
   * Object attribute
* The tree view will children in this order: Library, Objects, Members (for srcpf)
* Users will be able to right-click and run actions from Objects and Members

**Comment by worksofliam** [comment]
Work in progress. Will come out as an optional feature, but will eventually replace the Object Browser and Member Browser.

![image](https://user-images.githubusercontent.com/3708366/140621981-30972cf2-4fd7-4a6e-8292-0ec6d86a07ef.png)

**Comment by worksofliam** [comment]
Please help [test this PR](https://github.com/halcyon-tech/vscode-ibmi/pull/377#issuecomment-962509309)
