### ISSUE TITLE
Language tools for RPGLE (outline, content assist, etc)

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#32]
Somethings to consider:

* [ ] When the user saves the member (or streamfile) do we want to run a compiler with `*EVENTF *NOGEN` so we can generate an error listing, which would then populate the diagnostics panel? This is more real-time than having to compile every time you want the diagnostics to update. We can do this without a language server.
* [ ] Do we want to build an outline view for RPGLE? This means looking for structs, variables, and procedures to populate an outline view? Might require an LSP
* [ ] Do we want 'go-to reference'? For this, we may have to make it so the LSP also looks in copy/include header files
* [ ] I personally want to be able to hit F12 on a header copy/include and have it open that source. (I guess this would be part of 'go-to reference')

Am open to ideas and discussion.

**Comment by worksofliam** [comment]
Any way to make use of the existing IBMiLangiages dep we have for an LSP? Maybe @barrettotte can comment on that.

Other inspiring projects:

* https://github.com/andlrc/rpglelint
* https://github.com/andlrc/rpglefmt

**Comment by barrettotte** [comment]
@worksofliam Ah yeah this is something I've been keeping in the back of my mind for awhile. I could be wrong, but unfortunately I don't think the TextMate grammars I made in IBMiLanguages can really be used for anything outside of syntax highlighting. The extent would maybe be reusing some of the regex, but that's just being optimistic lol.

I think a lot of this would definitely involve some kind of an RPGLE parser to get the good stuff in the AST to feed to a language server. Once that thing is fed, you could probably go pretty wild with it based off of some of the extension API stuff I've read.

RPGLE free parsing probably wouldn't be too bad to make from scratch. But I think as soon as the mix of fixed and free come in the difficulty spikes pretty hard. So, porting an existing parser would definitely be ideal

**Comment by worksofliam** [comment]
I kind of assumed that using the TM grammars would be a PITA to port over, which is totally unfortunate.

The mix of free and fixed does make the entire thing totally complicated. I can't imagine what the codebase for the RPGLE compiler is like these days, thinking about all the backwards support it needs to have.

I personally don't see a problem with supporting only free-format for the time being. Some people would likely disagree with that, but 🤷‍♀️

**Comment by worksofliam** [comment]
@barrettotte I don't know what use this is to us, but back when I writing NetRPG I converted the bad lexer from that project to JavaScript.

https://gist.github.com/worksofliam/fe6afa456b1bb7575b441f76c2e4235a

This only covers totally free format, tho.

**Comment by barrettotte** [comment]
@worksofliam If I find time this weekend, I might do a tutorial or something on LSP and see how hard it would be to implement something simple just to get started. I've been looking around a bit at some of the servers on https://microsoft.github.io/language-server-protocol/implementors/servers/ . 

One thing I'm a little worried about is external symbols/references. If source is referencing some external program that hasn't been loaded by the client yet, I'm wondering how the server is going to be able to know about it. But, a lot of this is surrounded in fog for me, so maybe its not actually that bad.

**Comment by barrettotte** [comment]
I should have added to that prior comment that there's no guarantees I'll figure anything out, so if anyone wants to take a swing at this feel free lol.

**Comment by worksofliam** [comment]
@barrettotte Might be useful to know if you watch to fetch members within another extension (the LSP) while you have Code for IBM i installed and connected, you can use our scheme to download/open members.


```
            let uri = vscode.Uri.parse(`LIB/FILE/MBR.mbr`).with({scheme: 'member'});
            try {
              let doc = await vscode.workspace.openTextDocument(uri); // calls back into the provider
              const editor = await vscode.window.showTextDocument(doc, { preview: false });
            } catch (e) {
              console.log(e);
            }
```

**Comment by thebeardedgeek** [comment]
@worksofliam on option 1 in regards to saving and running a compiler with *EVENTF *NOGEN I like this idea but I wonder if someone that saves every few seconds would tax this process. Options I was thinking for this:

1. A shortcut key that could save + run the compiler and get the diagnostic messages without compiling the object
2. A separate shortcut key that would run the compiler and get the diagnostic messages without compiling the object
3. A menu option on the object that would allow you to test compiling without compiling the object

I'm not sure if I am overthinking this but these seemed like good options to me.

**Comment by worksofliam** [comment]
@thebeardedgeek If that's the case, I can take a stab at the NOGEN stuff. What is nice about the NOGEN stuff is that it's a simple implementation and it works for the majority of the ILE compiles (`CRTBNDx` and `CRTxMOD`).

**Comment by mlstoppa** [comment]
@worksofliam Though I recognize the help of being able to know about any errors while saving the source member, I still stick to have an outline view populated with names (procedures, variables, arrays, ...).
As @barrettotte pointed out in a previous discussion LSP might be required.
I know very little if nothing at all about how to build a VSC extension, but I am available to help.

**Comment by worksofliam** [comment]
I thought I would share this here as an interesting project. It's for COBOL and has built-in language tools for that: https://github.com/spgennard/vscode_cobol

**Comment by worksofliam** [comment]
https://stackoverflow.com/a/59132169/4763757

**Comment by worksofliam** [comment]
Got this last night. This is by no means perfect, but it's a nice start. This is **not** using the language server.

![image](https://user-images.githubusercontent.com/3708366/110691350-0badca00-81b3-11eb-802a-a9a4d238448e.png)

**Comment by worksofliam** [comment]
@barrettotte Check out `feature/rpglint` to see some of that progress. I am wondering if we should release it but have the functionality disabled by default.

**Comment by mahoneyl** [comment]
I just want to throw in my .2cents and say that something I've really been missing from RDi is Outline View. I think it would be a really productive addition to CODE for IBM i.

**Comment by worksofliam** [comment]
I am working on branch feature/outline_view which adds a basic outline view for RPGLE. It only includes procedures and subroutines. 
![image](https://user-images.githubusercontent.com/3708366/124393356-1c390180-dcc8-11eb-8266-627e27bb1bd3.png)

**Comment by chrjorgensen** [comment]
Hi Liam.

I see that the content assist requires the source to start with "**FREE" - please be aware that the instruction is case-insensitive, so "*free" is also valid... and what I use...

My preference is to have all RPG language elements in lowercase - all that uppercasing is too much shouting for me... he he

Of course it is a personal preference, but the compiler allows it and so should Code for IBM i.

Keep up the great and impressive work!

**Comment by worksofliam** [comment]
Hey @chrjorgensen 

It does look like the `**FREE` check is requiring uppercase - but all else is case insensitive.

I will get this fixed up tonight or tomorrow.

Thanks!

**Comment by mlstoppa** [comment]
How can I have the outline showing in the pane?
Thanks

**Comment by worksofliam** [comment]
@mlstoppa you can find the outline view in the regular Explorer. 

You are able to move it to another view also.

**Comment by mlstoppa** [comment]
@worksofliam I see all the other 5 sections' titles (user library list, member browser, ifs browser, object browser, database browser) but not the outline, nor it is listed in IBMi short menu. Did I miss some configuration points?
