### ISSUE TITLE
BUILDLIB seperate to Current Library

### ISSUE THREAD

**Issue by ChrisHird** [halcyon-tech/vscode-ibmi#320]
I was looking for a way to have any compiles to be directed to a build library instead of the current library. Reading through the documentation it appears that the default is &OPENLIB and &BUILDLIB is another pointer to &CURLIB( not sure that is the substitute variable). As the variable is already defined could it be unlinked from the  current library?

**Comment by worksofliam** [comment]
Could be part of your other issue, #322, which might allow you to set your own variables.

**Comment by ChrisHird** [comment]
I agree, but if we don't get 322 maybe this is another option?

**Comment by worksofliam** [comment]
@ChrisHird 322 will likely be added in the future. I like that idea a lot.
