### ISSUE TITLE
Ability to set attributes by connection

### ISSUE THREAD

**Issue by ChrisHird** [halcyon-tech/vscode-ibmi#322]
Would like to be able to set globally available attributes when connecting to a system. This would be things such as the TGTRLS for compiles, Binding directory location, Storage model, object replace setting etc.

This would allow each workspace to have its own set of definitions that can be used in the action scripts.

**Comment by worksofliam** [comment]
Okay, so a place to set up variables specific to a connection (and also part of a connection profile).

Cool idea.
