### ISSUE TITLE
Not connected to www.pub400.com!

### ISSUE THREAD

**Issue by Chrisdeparis** [halcyon-tech/vscode-ibmi#326]
**Describe the bug**

I can connect to my pub400 account with ileeditor but also with SEU, but impossible with the extension code for ibm i.

**To Reproduce**
1. Go to 'code for ibmi extension'
2. Click on 'Connect to an IBM i'
Not connected to www.pub400.com! Impossible d’écrire dans les paramètres de l’utilisateur. Veuillez s’il vous plaît ouvrir le fichier des paramètres de l’utilisateur pour y corriger les erreurs/avertissements et essayez à nouveau.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Extension version [e.g. 0.x.x]
 - IBM i OS version [e.g. 7.x]

**Additional context**

**Comment by priceaj** [comment]
Looks like there is a similar issue here: https://github.com/Microsoft/vscode/issues/38731 can you try what they did to resolve the issue?

Also what settings are you using to connect to PUB400?

Host should be PUB400.com
Port needs to be 2222
Then login with username and password

**Comment by Chrisdeparis** [comment]
I had an error in the settings.json file that prevented the connection.
Thanks

**Comment by n4nisha** [comment]
> I had an error in the settings.json file that prevented the connection. Thanks

what was the error?
