### ISSUE TITLE
Pasting Code into CLLE and CMD members adds extra characters

### ISSUE THREAD

**Issue by thebeardedgeek** [halcyon-tech/vscode-ibmi#330]
The last few programs I have tried to write in CLLE or CMD I've pasted some code snippets in from notepad.exe on Windows. When I paste the code into VS Code it adds \r or \\r to the end; causing the member to not save properly or not compile. Is anyone else experiencing this? I have removed extra spaces at the end of each line, if there was any but this still occurs.

![image](https://user-images.githubusercontent.com/9466407/134717932-1a2ddb9c-5d93-4f88-ab6c-21e5eea0c390.png)
![image](https://user-images.githubusercontent.com/9466407/134717962-a167052d-a487-4d88-b927-26ae8e71f334.png)

If I delete the \r or \\r in VS Code after it shows up, it doesn't come back. But I am not sure what is causing it to be there initially.

**Comment by worksofliam** [comment]
So you copy this from notepad:

```
Hello world
How are you
This is a test
```

And it pastes as:

```
Hello world\r
How are you\r
This is a test\r
```

Is that correct?

**Comment by worksofliam** [comment]
Is this only happening with CL?

**Comment by thebeardedgeek** [comment]
It seems to happen anytime time I paste text in from another application but I typically use notepad to remove any "character" formatting that could be present.

I've only been working with CLLE and CMD files and have not tested with others.

**Comment by worksofliam** [comment]
Okay here's another question. Do the `\r` only show up after you've saved it, after it's been pasted in?

**Comment by thebeardedgeek** [comment]
Yes, it's after the first save it looks like. Here is the Code for IBM i output
![image](https://user-images.githubusercontent.com/9466407/134719169-122553da-b0cf-44e2-ac41-7a1b31bc0059.png)

**Comment by worksofliam** [comment]
The fix is making this return value for `\r` blank: 

https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/filesystems/qsys/complex/content.js#L143

**Comment by worksofliam** [comment]
@thebeardedgeek Fix release incoming
