### ISSUE TITLE
Rpgle Content Assist Enable

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/vscode-ibmi#341]
**Describe the bug**
If I enable Rpgle Content Assist Visual studio code don't suggest me variable name, look at this:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/9719313/135523930-76e23bc9-88e6-458f-92a2-125925911ab9.gif)

**Environment (please complete the following information):**
 - Extension version v0.7.10

**Additional context**

**Comment by worksofliam** [comment]
For the future, looks like we just need to add more items to the `items` array here:

https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/languages/rpgle/linter.js#L341

We should continue to look at the `doc` object for more info for variables and structs.

**Comment by mlstoppa** [comment]
Hi Liam,

I am still trying to use content assistant with no success.

Whether "Rpgle content assist" option is enabled or not, I can't see any prototype information neither hovering the procedure call nor pressing ctrl-space.

When pressing ctrl-space all I see is the list of RPGLE snippets from Neils Liisberg.

Code for IBM i is running v0.7.16 and all other estensions are up to date.

Is there something I can do or check to have this feature working?

Thank you

**Comment by worksofliam** [comment]
@mlstoppa 

1. It only works with total free-format code (`**FREE`)
2. Perhaps you could create a piece of code where it doesn't work and I can recreate your issue?

**Comment by worksofliam** [comment]
I have added a commit that will now display more global variables.

![image](https://user-images.githubusercontent.com/3708366/140200429-33249a47-fc17-49cc-aeba-4f84e63d624b.png)

**Comment by mlstoppa** [comment]
Yes, members are total-free format. All I see are BIFs

![image](https://user-images.githubusercontent.com/11289821/140290265-8f2180b7-328c-4b58-bc5f-1730fcf64d4d.png)

I'll try with the last commit then tell you if it works.

**Comment by mlstoppa** [comment]
It's already v0.7.17.

![image](https://user-images.githubusercontent.com/11289821/140293057-ed35bc04-1109-400a-b5fd-415a7e23df14.png)

**Comment by worksofliam** [comment]
@mlstoppa Are you able to share a snippet of code with me so I can recreate it? Please feel free to email it to me if you don't want to share it here.

**Comment by mlstoppa** [comment]
@worksofliam 
I wasn't able to find your email. Can you please provide me one?

**Comment by worksofliam** [comment]
@mlstoppa 

`liam [ @ ] worksofbarry [ dot ] com`

**Comment by mlstoppa** [comment]
@worksofliam 
Sent!

**Comment by worksofliam** [comment]
@mlstoppa Thank you! I got it. I will take a look at it this evening.

**Comment by worksofliam** [comment]
Hey @mlstoppa 

I had a look, but I could see all the global variables from my content assist.

![image](https://user-images.githubusercontent.com/3708366/140354395-02a9d7c5-9173-46dd-bd2a-45bc6ab6f9b9.png)

**Comment by worksofliam** [comment]
I will add this note:

* It will only pick up copybooks if they are in the same library as the base source code. It will not use the library list to find it.

**Comment by mlstoppa** [comment]
@worksofliam 
Liam, the copybooks >are< in the same library, just a different source file to keep things in order.

**Comment by mlstoppa** [comment]
@worksofliam 
Found it! For some reason, the source file language was set to RPG instead of RPGLE. Now, the outline view also lists variables and procedures' names.
It works! Great!

**Comment by worksofliam** [comment]
@pabloto Any feedback here?

**Comment by pabloto** [comment]
Nothing change
