### ISSUE TITLE
Rpgle Indentation Enabled: End-DS

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#342]
**Describe the bug**
A line like this, which is valid, throws off the subsequent indentation:
`dcl-ds InTbl extname('QIWS/QCUSTCDT') template end-ds;`
![image](https://user-images.githubusercontent.com/67484051/135760666-758afb88-b3f1-48de-b101-f7817686363b.png)

Commentng out the line removes indentation errors:
![image](https://user-images.githubusercontent.com/67484051/135760737-9cdc3d1e-f80d-4a57-99a0-5e7b0bba8ed0.png)

Putting the `end-ds` on a separate line largely improves the situation but the `end-ds` is still flagged.
![image](https://user-images.githubusercontent.com/67484051/135760849-cffe5853-1e9d-4839-bd8d-2fa41ee6dfab.png)

Putting a line in the data structure totally resolves the problem:
![image](https://user-images.githubusercontent.com/67484051/135760944-788961cb-1c1f-40d6-9597-24891cba1998.png)

**To Reproduce**
Paste this code into an RPGLE member:
```
**free
ctl-opt debug option(*nodebugio: *srcstmt)
    dftactgrp(*no) actgrp(*caller)
    main(Main);
Dcl-C up         'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
Dcl-C lo         'abcdefghijklmnopqrstuvwxyz';
Dcl-S string       Char(10)   inz('zzz locn');
dcl-ds InTbl extname('QIWS/QCUSTCDT') template end-ds;

dcl-s MyCusnum like(cusnum);
dcl-s MyLstNam like(lstnam);

dcl-proc Main ;
    dcl-pi Main Extpgm('ASTATE');
    end-pi;
    string = %XLATE(lo:up:'rpg dept');
    // string now contains 'RPG DEPT'
    dsply string;

    string = %XLATE(up:lo:'RPG DEPT':6);
    // string now contains 'RPG Dept'
    dsply string;
    return;
end-proc;
```

Since this is experimental this is not urgent.

**Comment by worksofliam** [comment]
Probably needs to be handled here: https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/languages/rpgle/linter.js#L918

**Comment by SJLennon** [comment]
@worksofliam  This is fixed:
![image](https://user-images.githubusercontent.com/67484051/136409976-392b137b-195b-451e-bfdc-8faa176f0e4f.png)

This still has an issue:
![image](https://user-images.githubusercontent.com/67484051/136410100-a71701a4-7219-4960-9e52-20a7f2903caa.png)
It expects to be indented, and IMHO it shouldn't be indented, i.e., the dcl-s and the end-ds should be at the same indent level.
