### ISSUE TITLE
Db2 for i Extension

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#344]
So I think it's worthy to remove the existing Database functionality from the base extension, to then write a 'Db2 for IBM i' extension which would add back that functionality.

1. I think this would remove some bloat from the base
2. Would allow us to add more functionality since we've got space to grown in a separate extension. (It would use the Code for IBM i connection, like the git extension does.)

## Ideas:

* Move the 'execute SQL' functionality to the new extension
* The initial view is a list of schemas, and the user can add remove more
* I want this list of schemas in the view to work exactly as the list of schemas does in the Schemas window in ACS.
   * When you open the schema dropdown, you get a list of database types.
   * Clicking on the database types will then show you all the objects of that type in the chosen schema
   * Instead of showing the list in a new view (tab) like Schemas does, it will just show under the item type in the view.
   * Clicking on the SQL object will maybe render some HTML to show information about the object in a table (like Schemas does)
   * Right-clicking on the object will show:
       * Query - to open a new SQL file with a prefilled statement to `select * from x limit 10`
       * Generate SQL - to open a new SQL file with the SQL to generate the same object

Please make further suggestions, but this is the current plan.

**Comment by worksofliam** [comment]
If anyone knows the SQL that the right click options on tables are, please share them here.

* Locks
* Locked Rows
* Not sure if we want any of the other stuff in that list?
* Other ideas?

![image](https://user-images.githubusercontent.com/3708366/136130911-aa5e50f5-6c66-41e9-8ae3-22be49874284.png)

**Comment by worksofliam** [comment]
I actually have made a start, but nothing to publish yet. It's a lot of work. It might be some time.

**Comment by worksofliam** [comment]
A start has been made in the new extension: https://github.com/halcyon-tech/vscode-db2i/projects/1

**Comment by davidknittle** [comment]
One thing i would love to have is a generator for an sql that is a simple select but has all of the fields, rather than select *. This allows me to strip out some useless fields but still not have to type all of the other fields in, and also to consolidate fields from multiple files into a single select much easier. just a thought. right now i build these using SYSCOLUMNS...
