### ISSUE TITLE
IFS Browser: list directories first, followed by streamfiles

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#353]
In the IFS Browser, list the directories first in alphabetical order, followed by the stream files in alphabetical order.

**Comment by worksofliam** [comment]
https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/views/ifsBrowser.js#L396

Looks like the `objects` list should be sorted by `type` and `name` after it's been retrieved.

**Comment by PerryRaleigh** [comment]
Hey Barry, I'll give it a go.

**Comment by novy400** [comment]
Hello I've just push a pull request about it.
