### ISSUE TITLE
Compile implies Save 

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#365]
**Is your feature request related to a problem? Please describe.**

If I'm editing source, but have not saved it, and I key Ctrl+e to compile then I get "The file must be saved to run Actions" with Save and Cancel buttons.  I then have to _grab my mouse_ and click on Save.  I don't recall ever having clicked on Cancel.

While this isn't a huge inconvenience, it is somewhat inefficient.

**Describe alternatives you've considered**
The alternative is to first key Ctrl+s to save, but I then have to watch until the icon in the tab turns from a circle to an X before keying Ctrl+e.  And if I get ahead of myself (because the save took longer than usual) I'm back to "The file must be saved to run Actions" situation

**Describe the solution you'd like**
Seems to me that in virtually all situations Ctrl+e implies that we want to compile the edited code.  

**I propose that Ctrl+e, if there are changes, will first do a save before initiating the compile.**

If someone who want to override this action, , I suggest a new setting "Compile implies save".  It would default to Yes. 

And I suppose the extension would have to consider the case of a dropped connection.

**Comment by worksofliam** [comment]
A cool idea. Perhaps this should be some connection setting? Perhaps:

> Automatically save before running action is dirty

What do you think?

**Comment by SJLennon** [comment]
I think it should be connection specific.  That way it's easy to toggle it from Settings in the Status bar.  (Though my feeling is that most won't want to turn if off.)

For those newish to VS Code, I wonder about their understanding of "dirty", though it is fairly intuitive I suppose.

Slight modified version of the above:
**Automatically save before running action if editor dirty**
With additional explanatory text like this
**When current editor has unsaved changes, automatically save it before running a requested actions.**

Is it worthwhile having message like "Saving..." while the save is in progress?
@worksofliam

**Comment by worksofliam** [comment]
@SJLennon 

> Slight modified version of the above:
> Automatically save before running action if editor dirty
> With additional explanatory text like this
> When current editor has unsaved changes, automatically save it before running a requested actions.

I like your suggestions a lot. I will use these.

> Is it worthwhile having message like "Saving..." while the save is in progress?

I am not sure about a message since I don't know where it would appear. Perhaps we could add a status bar somewhere at the bottom.

Liam

**Comment by worksofliam** [comment]
@SJLennon 

What do you think of this?

![image](https://user-images.githubusercontent.com/3708366/140553578-40bb1290-44f6-4558-9303-9a766283084b.png)

**Comment by SJLennon** [comment]
So this would turn on the automatic save for this connection and you wouldn't see the message again?
Would there be a way to turn it off (or on) in Settings?
@worksofliam

**Comment by worksofliam** [comment]
@SJLennon Yes! There is the actual setting for it. That button just changes the setting for the user.

![image](https://user-images.githubusercontent.com/3708366/140557098-c2c7a75c-133b-44fd-acf6-d5f1f7ac6394.png)

**Comment by SJLennon** [comment]
@worksofliam  Maybe I'm in a post lunch daze, but I'm not sure what the image is tell me about automatic save.

(Though I do like the Launch Column Assist feature upgrade..)

**Comment by worksofliam** [comment]
@SJLennon I just realised I posted the wrong image... nonetheless it's in the settings too :)
