### ISSUE TITLE
Help traditional RPG coders discover the RPG column assistant feature

### ISSUE THREAD

**Issue by alanseiden** [halcyon-tech/vscode-ibmi#369]
The column assistant feature is great, but people might not find it or know it exists. I didn't till I asked you.

Suggestion: When user is in an RPG source member, add something like this to the right-click menu: 
**Prompt........................Shift+F4** 

That prompt option could trigger the column assistant.

**Comment by worksofliam** [comment]
Yes, very good idea. A nice simple change:

```json
			"editor/context": [
				{
					"command": "code-for-ibmi.rpgleColumnAssistant",
					"group": "1_rpgle",
                                         "when": "editorLangId == rpgle"
				}
```

**Comment by worksofliam** [comment]
@briangarland 

Maybe we should use the same group name so the convert and this menu item are in the same group?

What do you use?

**Comment by BrianGarland** [comment]
I'm currently using "group": "1_rpglefree@1".   

I'm open to changing mine.

**Comment by worksofliam** [comment]
Perhaps `1_rpgle` so then we can group them together?

**Comment by BrianGarland** [comment]
Sounds good.   I've made the change and it will be in 0.0.13 when (already uploading)

**Comment by worksofliam** [comment]
@BrianGarland Looking good!

![image](https://user-images.githubusercontent.com/3708366/140556555-a17c65c8-3f32-48c9-9044-289385fb9328.png)
