### ISSUE TITLE
Add a "Delete Action" button to "Work with Actions" dialog

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#374]
**Is your feature request related to a problem? Please describe.**
Editing Settings.JSON to remove an Action is error prone.

**Describe the solution you'd like**
Add a Delete Action button to Work with Actions Dialog

**Describe alternatives you've considered**
Can't think of any.

**Comment by worksofliam** [comment]
Delete button will be available on an action.

![image](https://user-images.githubusercontent.com/3708366/140558973-7e21c159-0ee8-460f-b9e3-8d1d3f0cb89e.png)
