### ISSUE TITLE
Cannot read member with CCSSID 65535

### ISSUE THREAD

**Issue by gramajola** [halcyon-tech/vscode-ibmi#386]
**Describe the bug**
Cannot read member with CCSSID 65535. I change setting and specify in Code for i plugin settings CCSSID 65535 and member file is open but is empty, even if in reality it is not

**To Reproduce**
1. Go to Member Browser
2. Click on member with CCSSID 65535
3. Scroll down to open a file
4. Look the member of the source file is empty, even if in reality it is not

**Screenshots**
![image](https://user-images.githubusercontent.com/94113484/141288998-6ec5bb28-7499-45a7-a04e-507755b25a08.png)
![image](https://user-images.githubusercontent.com/94113484/141289113-35075c10-f3e8-4d22-9a9f-ff9c1100aeab.png)

**Comment by worksofliam** [comment]
You don't use that setting to specify 65535, you use it to specify what the actual encoding is - it likely means when editing it is inherited from the job. 

In the settings, I would start by disabling SQL, and then entering in a valid CCSID in the 'Source File CCSID' field.

**Comment by gramajola** [comment]
Very thanks Liam! I've resolved with theese settings! Now, if that's not a problem for you, I'll create a blog post on the Faq400 italian community. Very useful!

![image](https://user-images.githubusercontent.com/94113484/141317924-931ed368-f9ec-47e7-92d9-ee5aee37534c.png)

**Comment by worksofliam** [comment]
@gramajola Great! Glad you got it resolved.
