### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by MarkBoyer** [halcyon-tech/vscode-ibmi#389]
I'm trying to connect for the first time using the extension.  I put in system address and credentials.  I get an error "Connection timed out", but it is returned very quickly.  Output tab shows:

null: pwd
{
    "code": null,
    "signal": null,
    "stdout": "/home/wg446mb",
    "stderr": ""
}

/home/wg446mb: echo "liblist" | /QOpenSys/usr/bin/qsh
{
    "code": 9,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

 - Extension version v0.7.19
 - IBM i OS version V7R4M0

If I put the echo command to retrieve the library list into a QP2TERM session, it displays the library list as expected.  However if I SSH to the machine and enter the echo command, nothing is displayed except returning to the "$" prompt.  

Any thoughts on how I can troubleshoot this further or what is going on?  TIA

**Comment by worksofliam** [comment]
@MarkBoyer Are you saying that if you run

```
echo Hello world
```

Nothing shows up in your ssh shell?

**Comment by MarkBoyer** [comment]
@worksofliam I apologize for not being clear.  What I meant to say was from my Mac if I start an ssh session from terminal, log into the i and issue the command ‘echo “liblist”’ piped to “qsh”, it simply returns to the shell prompt ($) without listing the libraries or showing an error.  I assume this is why the extension shows the exit code “9” in the output.

**Comment by worksofliam** [comment]
Hey @MarkBoyer - thanks.. that's much clearer. You're not the first person to have this.

Check out this comment: https://github.com/halcyon-tech/vscode-ibmi/issues/69#issuecomment-790733019

Sounds like the exact same issue, but with no concrete answer.

I will start to ask around again and let you know why that might be happening.

**Comment by worksofliam** [comment]
Possibly some useful information

https://www.ibm.com/support/pages/how-determine-meaning-qshell-exit-status-or-signal

**Comment by worksofliam** [comment]
@MarkBoyer Can you run `env` and `set` and share the results here please?

**Comment by richardschoen** [comment]
Also consider setting your default shell to bash. See this: https://ibmi-oss-docs.readthedocs.io/en/latest/troubleshooting/SETTING_BASH.html

**Comment by richardschoen** [comment]
Interesting thread: https://code400.com/forum/forum/iseries-programming-languages/clp-clle/9070-qsh-system-command-problem

**Comment by richardschoen** [comment]
One of Kevin Adler's blog posts would make me think perhaps the default bash shell setting plus upgrading bash to the latest version may be in order: https://kadler.io/2020/12/23/bash-builtins.html#

**Comment by MarkBoyer** [comment]
@worksofliam Here is the result of ENV:
HOME=/home/WG446MB
LOGIN=wg446mb
LOGNAME=wg446mb
MAIL=/var/spool/mail/wg446mb
PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
SHELL=/QOpenSys/usr/bin/bsh
SSH_CLIENT=10.38.15.3 59709 22
SSH_CONNECTION=10.38.15.3 59709 10.0.9.20 22
SSH_TTY=/dev/pts/0
TERM=xterm-256color
TZ=<PST>8<PDT>,M3.2.0,M11.1.0
USER=wg446mb

Here is the result of SET:
HOME=/home/WG446MB
IFS=

LOGIN=wg446mb
LOGNAME=wg446mb
MAIL=/var/spool/mail/wg446mb
MAILCHECK=600
OPTIND=1
PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
PS1=$
PS2=>
SHELL=/QOpenSys/usr/bin/bsh
SSH_CLIENT=10.38.15.3 59709 22
SSH_CONNECTION=10.38.15.3 59709 10.0.9.20 22
SSH_TTY=/dev/pts/0
TERM=xterm-256color
TZ=<PST>8<PDT>,M3.2.0,M11.1.0
USER=wg446mb

From the article that @richardschoen referenced, if I "type liblist", or "cl" for that matter, I get "liblist not found" and "cl not found".  If it's a matter of upgrading the shell, any advice there would be appreciated.  We do not have the OSS tools installed, so we don't have the /QOpenSys/pkgs directory.  I will work on getting that installed.

Thanks again for the suggestions and any further advice.

**Comment by kadler** [comment]
> One of Kevin Adler's blog posts would make me think perhaps the default bash shell setting plus upgrading bash to the latest version may be in order: https://kadler.io/2020/12/23/bash-builtins.html#

The `qsh` command is provided by PASE. It is completely unaffected by any version of bash.

**Comment by kadler** [comment]
> @worksofliam I apologize for not being clear. What I meant to say was from my Mac if I start an ssh session from terminal, log into the i and issue the command ‘echo “liblist”’ piped to “qsh”, it simply returns to the shell prompt ($) without listing the libraries or showing an error. I assume this is why the extension shows the exit code “9” in the output.

According to the link @worksofliam provided earlier, exit code 9 is

> 9 when descriptor 2 was not available.

File descriptor 2 is stderr, which should *always* be available for PASE processes. Do you have `$QIBM_USE_DESCRIPTOR_STDIO` set? If so, is it set to something other than 'Y' or 'I'?

**Comment by MarkBoyer** [comment]
@kadler this is kind of unfamiliar ground for me.  I posted the results of "env" and "set" above.  Would there be someplace else I need to check for that?  TIA

**Comment by kadler** [comment]
@MarkBoyer sorry, I missed that. Looks like it's unset in your SSH session. Can you check `WRKENVVAR LEVEL(*SYS)` and see if it's set there?

**Comment by MarkBoyer** [comment]
@kadler here are the results of "WRKENVVAR LEVEL(*SYS)"
QIBM_RPG_JAVA_PROPERTIES    '-Djava.version=1.4;'
QYPS_SOCKETTIMEOUT          '30'                 
QYPS_MAX_CONTIMOUT          '180'                
SKIPWASPLUGIN               '1'                  
QIBM_WS_ACCDS               '1'                  
PASE_DEFAULT_UTF8           'N'

**Comment by kadler** [comment]
Hmm. Not sure why things aren't working then. I'd suggest opening a ticket with IBM support since it seems like a possible bug in QSH (or if not, the QSH devs would know more about why this is occurring).

**Comment by MarkBoyer** [comment]
@kadler I'll get a ticket start.  I did find that when I use QP2TERM, use STRSQH or start a remote shell with RDi and run "env" it shows "QIBM_USE_DESCRIPTOR_STDIO=I".  But if I start an SSH session from Mac or Windows, "env" has no trace of that, and several other environment variables.  Could it be a bug or a setup issue with SSHD?

**Comment by kadler** [comment]
This is what I get from my 7.4 system connecting via SSH:

```
-bash-5.1$ echo $QIBM_USE_DESCRIPTOR_STDIO

-bash-5.1$ echo env | qsh | grep QIBM_USE_DESCRIPTOR_STDIO
QIBM_USE_DESCRIPTOR_STDIO=Y
```

My system **doesn't** have it set in WRKENVVAR, nor does it have it set in my PASE shell, but when QSH is called from PASE it's set to `QIBM_USE_DESCRIPTOR_STDIO=Y`. From 5250, starting QSH or QP2TERM shows `QIBM_USE_DESCRIPTOR_STDIO=I`. 

I'd ask for the same output, but we've established that calling qsh won't produce any output for you from SSH.

**Comment by MarkBoyer** [comment]
That is odd.  If I "echo $QIBM_USE_DESCRIPTOR_STDIO" from my Mac ssh session, it's responds "Y", and you are correct the "echo env | qsh | grep QIBM_USE_DESCRIPTOR_STDIO" has no response.

**Comment by richardschoen** [comment]
I got the same results as Kevin did. I'm on V7R3.

**Comment by kadler** [comment]
@MarkBoyer That's odd, since it didn't show up in the `env` output you previously posted.

What happens if you `unset QIBM_USE_DESCRIPTOR_STDIO`, then try to run the qsh command?

**Comment by MarkBoyer** [comment]
@kadler I had exited my SSH session.  Now I start a new one and run "echo $QIBM_USE_DESCRIPTOR_STDIO" it shows no value.  I does display a blank line, it's not just two "$" prompts stacked on top of each other.  Using unset makes no change.

**Comment by MarkBoyer** [comment]
I was finally able to get the admins to install the open source tools including bash shell and am able to connect and use the tool as expected.  This can be closed.

**Comment by MarkBoyer** [comment]
Resolved.
