### ISSUE TITLE
Allow IFS browser user to add/remove multiple directories from list similar to how source files are added/removed

### ISSUE THREAD

**Issue by richardschoen** [halcyon-tech/vscode-ibmi#39]
Also make sure that DOT files. Ex: .bashrc, .profiles, etc show up.

**Comment by worksofliam** [comment]
Did you change the setting as in the answers?

**Comment by richardschoen** [comment]
Not sure what you're asking ?

**Comment by richardschoen** [comment]
Still keep running into this. It would be nice to be able to have multiple shortcuts to IFS folders just like we have with source files. Find myself changing directories a lot. Just adding another note :-)

**Comment by richardschoen** [comment]
Still painful :)

**Comment by szsascha** [comment]
The ifs browser works actually like a "normal" sftp client. I think the possibility of manually adding folders could lead to confusion.

By default you start in the directory configured in your USRPRF. (Maybe there should be a possibility to set it in a servermanager? #152 )
You can change the directory with the first directory button of the ifs browser.

Maybe it would solve your problem when you create some symbolic links with ADDLNK?

**Comment by worksofliam** [comment]
I think I agree with @szsascha on this one. I don't believe we are planning to change the IFS browser to this.

I will close for now.

**Comment by richardschoen** [comment]
OK, but I can do this in RDI.  In my opinion we should make this better than a standard SFTP client. Nothing is more painful than drilling in and out of a huge project structure and then needing to quickly reference files somewhere else.

**Comment by richardschoen** [comment]
A few screen shots for inspiration or perspiration.
![image](https://user-images.githubusercontent.com/9791508/122662460-c9543b80-d158-11eb-9110-86e42069e535.png)
![image](https://user-images.githubusercontent.com/9791508/122662476-dffa9280-d158-11eb-99d9-4c5411a84129.png)
![image](https://user-images.githubusercontent.com/9791508/122662498-03bdd880-d159-11eb-9f99-b6ab99431c79.png)
