### ISSUE TITLE
Use of new function search source file failed

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/vscode-ibmi#398]
Hi All,

Today I tried the new function Search source file, but if failed with this error:

![image](https://user-images.githubusercontent.com/9719313/141780934-8209c8bc-eff1-4da8-b8c5-3a1499d625fa.png)

Could it be because I have an IASP?

For the stream files it works well because I have a symbolic link in sysbas for every directory in iASP.

Many thanks.

**Comment by worksofliam** [comment]
@pabloto - Yes.. iASP related. Let me see what I can do about thart.

**Comment by worksofliam** [comment]
In the next release, it will show the ASP in the search text and use the ASP from the settings to search.
