### ISSUE TITLE
Compile Problems referencing incorrect source lines

### ISSUE THREAD

**Issue by cbuck0222** [halcyon-tech/vscode-ibmi#399]
Has anyone ever had an issue where the compile problems are referencing the incorrect line? I assume it's probably related to some RPG copy books in my program causing this extension to incorrectly interpret the compile listing. I've tried restarting VS Code and reconnecting to the i, but it doesn't seem to fix this issue.

To simulate this issue, I removed a ";" at the end of my If statement below. Error is recognized in Problems console, but selecting the RNF7030 error references the in correct line (referencing my "dcl-pi" line 204 instead of line 242 where the error exists. 

![image](https://user-images.githubusercontent.com/86483883/141801976-0af4df32-d1ce-4acd-9897-b5b8ffb114bb.png)

**Comment by worksofliam** [comment]
Oh yes, absolutely a problem with SQLRPGLE and copybooks. I would love if you were able to recreate this and paste all the code here so I can recreate it.

Liam

**Comment by priceaj** [comment]
I've seen an issue like this in RDi where certain compile commands were causing the line numbers to be incorrect in the EVENTF. I think its worth looking at the compile commands used for this, specifically OPTION, RPGPPOPT and COMPILEOPT.

**Comment by worksofliam** [comment]
Same as #405 so I will close it.
