### ISSUE TITLE
CL Prompting Tool Repeated Installation

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#402]
**Describe the bug**
Keep being ask to install the CL prompting tool on each connection.

![image](https://user-images.githubusercontent.com/67484051/142239393-2cf7c727-702c-437e-80d7-cb123761bc6f.png)

I click Yes and it installs

![image](https://user-images.githubusercontent.com/67484051/142239475-cd37c2e1-0b89-4ab3-8820-f8e1221d6b9d.png)

It works:

![image](https://user-images.githubusercontent.com/67484051/142240216-6b8240ff-bbab-48ae-97b9-8bab868f5a0f.png)

And next time I connect it repeats.  

Possibly due to using PUB400 with a temp library that is not ILEDITOR, or perhap because I seem to have an extremely cluttered up settings.json from lots of experimentation.

**Comment by worksofliam** [comment]
I will double-check, but it's looking in the logic to check if a program exists in the templib. Maybe it is getting cleared out by something?

**Comment by SJLennon** [comment]
It's not getting cleared out. I have narrowed it down a bit.  

I have 2 connections defined.  The first has a templibrary of LENNONS2, the second LENNONS1. 

I manually found and deleted all GENCMDXML and QTOOLS. They were only in LENNONS2.

 I now connected  through both connections which results in copies of GENCMDXML and QTOOLS in _both_ libraries. 

I delete the objects in LENNONS1, leaving the objects in LENNONS2, which is the templibrary for my _first_ connection.

I now connect with my first connections and I am prompted to do the install again.  So I deduce it is finding the templibrary of my second connection, which is LENNONS1 and looking for and not finding the objects there.. However, it does install them into LENNONS2. 

Are you using different code in deciding if the install is needed and to where is should be installed?

(This may be a case peculiar to me.  There is really no valid reason why I have different templibrary settings. other than I was experimenting some time in the past, probably trying to isolate the temporary files that sometimes got left.  Though I don't know if others might have similar separate templibrary setting for a valid reason.)
@worksofliam

**Comment by worksofliam** [comment]
@SJLennon I am not sure where the issue is here.. it almost sounds like expected functionality.

1. Connect to system
2. Check if GENCMLXML exists in tempLibrary
3. If not, ask to build the program

If I delete the object from my tempLibrary and then reconnect, it will ask me to install it again.

Liam

**Comment by mlstoppa** [comment]
Hi,
something similar happens to me.
I just have one connection and I added temp library to the library list also, just to give the extension one more chance to find it. 
Starting VSC after deleting the GENCMDXML program asks for installing CL prompting tools which then works.
Right after, if I close VSC, open it again, and answer no to the installing question, as tools are already installed, then it doesn't work.
Anything else I can check?
Thank you

**Comment by SJLennon** [comment]
@worksofliam 
@mlstoppa 
I've had a first time attempt at debugging the extension.  The issue appears to be when you can't use CRTLIB to create the temporary library, which I can't do on PUB400.

In IBM.JS, at line 215, when you come out of this code:
```
        progress.report({
          message: `Checking installed components on host IBM i.`
        });

        //Next, we see what pase features are available (installed via yum)
        try {
          //This may enable certain features in the future.
          for (const feature of remoteApps) {
            const call = await this.paseCommand(`ls -p ${feature.path}`);
            if (typeof call === `string`) {
              const files = call.split(`\n`);
              for (const name of feature.names)
                if (files.includes(name))
                  this.remoteFeatures[name] = feature.path + name;
            }
          }
          
        } catch (e) {}
```
`remoteFeatures.GENCMDXMLPGM` is undefined.
And I think that is because `remoteApps(2).path` still has "/QSYS.lib/ILEDITOR.lib/" and it should be the tempLibrary value.

I could be totally wrong about this.  And I don't feel confident in trying to make a fix.

**Comment by worksofliam** [comment]
This is the cause. Fix tonight.

https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/api/IBMi.js#L17
