### ISSUE TITLE
Replace SQL execution with RUNSQL

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#403]
db2util is great for getting explicit data, but when we want to run statements that use the Code for IBM i library list.. it's pants.

What I am proposing is this:

1. User executes statement (Control/Command + R)
2. If statement begins with `SELECT` or `WITH`, then we wrap it with `CREATE TABLE TEMPLIB/TEMPTABLE AS ( <STATEMENT> )`
3. Use `RUNSQL` to execute the statement, in which it will use the Code for IBM i library list.
3. We CPYTOIMPF on the resulting table, which we then display to the user.
4. If it is not a select, we do not have a table to display - easy. If it does create a table, we need to delete the resulting .csv and the temporary table to make sure we're reclaiming storage.

The reasons for this:

* Using RUNSQL means we can make the statement run using system name
* It can use the library list defined in Code for IBM i (the goal)
* IBM i output will have log from executed command
* Removes db2util requirement to run statements.

A worry I have is creating huge tables (and csv) by accident, so maybe we need to enforce a limit too?

**Comment by SJLennon** [comment]
"A worry I have is creating huge tables (and csv) by accident, so maybe we need to enforce a limit too?"
You do need to enforce a limit.  Add a fetch first nnn rows only.

"IBM i output will have log from executed command"
Not sure what you mean by that.  RUNSQL OPTION(*LIST) to create a spool file?

Thought for rumination: The RUNSQLSTM command allows you to run multiple SQL statements and Cl commands from a source file. For example, this source works quite nicely with RUNSQLSTM:
```
drop table qtemp.fred;
create  table qtemp.fred as (
select * from qiws.qcustcdt fetch first 5 rows only)
with data;
cl: RUNQRY QRY(*NONE) QRYFILE((QTEMP/FRED)) RCDSLT(*NO)
```
(Not suggesting you use RUNQRY--it was just a handy example.)
@worksofliam

**Comment by worksofliam** [comment]
@SJLennon Some great notes.

In Code for IBM i, we also handle the `cl:` directly in the editor, allowing users to run CL commands from `.sql` with the library set and spool file in the IBM i Output tab - that will continue to work!

There absolutely needs to be a limit, as well as automatic deletion of those created objects after it's been transmitted to the user.

> Not sure what you mean by that. RUNSQL OPTION(*LIST) to create a spool file?

I meant that any command, like `RUNSQL` or `RUNSQLSTM`, will write the spool file to the IBM i Output tab.

**Comment by worksofliam** [comment]
Note: this change is only needed in the databaseBrowser since that's the only area where the user can execute a custom SQL statement.

**Comment by worksofliam** [comment]
Not sure this is a big deal right now, so I am going to close for the time being.
