### ISSUE TITLE
Error saving to source file when statement is too long

### ISSUE THREAD

**Issue by BrianGarland** [halcyon-tech/vscode-ibmi#404]
**Describe the bug**
If a statement is longer than the record length of the source file the source will fail to save but there is no clear explanation as to why. 

**To Reproduce**
Create an RPGLE **FREE source file with multiple statements.  Somewhere in the middle of that source put a comment that is longer than the record length of the source file and attempt to save the source file.    You'll see a popup in the bottom right corner saying "failed to save 'filename': Unable to write file 'full path'".  There is no indication that the reason is the length of the comment.

**Expected behavior**
Some indication that the statement is too long to be saved.  RDi will bring you to that line in the source and highlight it during the save if it is too long. 

**Screenshots**
![image](https://user-images.githubusercontent.com/14948327/142446475-66eb3e6d-c2f5-4d81-9996-6090439f124a.png)
![image](https://user-images.githubusercontent.com/14948327/142446514-8dcede5a-da1a-4836-9a4d-97a89d0e2e3e.png)

**Environment (please complete the following information):**
 - Extension version 0.8.1
 - IBM i OS version 7.3

**Additional context**

**Comment by worksofliam** [comment]
@BrianGarland SQL enabled or disabled? Guessing disabled.. think I solved this for SQL enabled situation.

**Comment by BrianGarland** [comment]
SQL is enabled.  
![image](https://user-images.githubusercontent.com/14948327/142454659-e6b50922-c340-43ba-8eff-ed04d2d83541.png)

**Comment by worksofliam** [comment]
@BrianGarland I am not able to recreate this issue. I have code in the file system handlers which chops off the end if the record length is too long.

I guess some Qs for you:

1. What version of the extension are you on?
2. What record length are you working with?
3. Can you please share the exact steps you took so I can try those also?

Thanks!

**Comment by BrianGarland** [comment]
1) version 0.8.1
2) 112 record length (6 for srcseq, 6 for srcdat, 100 for srcdta)
3a) create a new member 
3b) enter these lines  (there are three lines, the second comment may wrap in github but should be one line in vs code
```
**FREE
// short comment
// long comment ------------------------------------------ xxxxxxxxxxxxxxxxxxxxxx   dddddddddd 555555555555555555555555
```
3c) Ctrl-S to save
3d) Get the error

If you split the long comment into two lines ( between the x's and the d's)  the save will be successful

**Comment by SJLennon** [comment]
I tried this and I got no errors and the line was truncated. Screen shost below are for RPGLE but I get the same result with SQLRPGLE.  0.8.2 on on OS 7.4 (PUB400).
![image](https://user-images.githubusercontent.com/67484051/142644121-7f2627c7-2ea8-4b5f-8a6b-3c69fada79de.png)

Now save  with Ctrl+s
![image](https://user-images.githubusercontent.com/67484051/142644304-03f28ab3-cc50-4027-87a1-bfccade6a7a0.png)

Close and reopen:
![image](https://user-images.githubusercontent.com/67484051/142644475-5356b482-a2d0-45fc-87f6-56c986028b90.png)

**Comment by BrianGarland** [comment]
I get the same error with PUB400 so it must be something with the installation on my laptop.  

I did update to 0.8.2 of the extension and have all the same issues.

**Comment by worksofliam** [comment]
@BrianGarland Absolutely recommend cloning and having a little debug yourself.

These two locations are what I took a look at:

* https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/filesystems/qsys/complex/content.js#L42
* https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/filesystems/qsys/complex/content.js#L106

**Comment by BrianGarland** [comment]
Hmm.  With SQL enabled I cannot get it to stop at either of those lines.  I even went upstream of them and tried a couple of other spots.  If I disable SQL I can get it to stop in that save routine and it doesn't fail, it just truncates the line.

This is a clean fork and clone to my laptop.  

I'll keep trying but if you have any other suggestions let me know.

**Comment by worksofliam** [comment]
@BrianGarland Debug higher up.

Try starting here, where the file system for QSYS is registered.

https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/Instance.js#L180

**Comment by worksofliam** [comment]
@BrianGarland Any update for us at all?

**Comment by worksofliam** [comment]
@BrianGarland I am going to close this. Please feel free to open it again.

**Comment by BrianGarland** [comment]
@worksofliam I think this issue was tied to another extension.  I had the old "source dates" extension installed still and after uninstalling that I no longer get the error, just the truncated statement.

**Comment by worksofliam** [comment]
@BrianGarland that makes sense! Yup, the old source dates extension is totally useless now as all that functionality exists in the base.

Thanks!
