### ISSUE TITLE
rpgleIndentationEnabled Gone?

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#407]
Where did "code-for-ibmi.rpgleIndentationEnabled": true go?  I know it was experimental, but I liked the feature !  And it worked fairly recently, now it is "unknown Configuration setting".  In fact, per #387, it looked like it would be handy to totally fix indention.

**Comment by worksofliam** [comment]
Check out vscode-rpgle in our GitHub org!

**Comment by SJLennon** [comment]
I have.  But can't see any references. Only this:

Enable these options in VS Code settings.

    vscode-rpgle.rpgleColumnAssistEnabled - column assist for RPGLE fixed-format.
        vscode-rpgle.rpgleColumnAssistant / Shift+F4 to launch it when on fixed-format line
    vscode-rpgle.rpgleContentAssistEnabled - shows content assist and enables the following commands
        vscode-rpgle.rpgleOpenInclude / Shift+F12 when on copy or include statement
    vscode-rpgle.rpgleLinterSupportEnabled - enables linter
        vscode-rpgle.openLintConfig to open or create linter file. Creates / opens relative to source that is currently open. Read more below on linting.

Though do get some (inconsistent) messages and squiggly line on indentation.

**Comment by worksofliam** [comment]
Perhaps this issue needs to be moved over to vscode-rpgle?

**Comment by SJLennon** [comment]
Moved.

________________________________
