### ISSUE TITLE
Hover over tool-tip definition details for variables, constants, files, etc. 

### ISSUE THREAD

**Issue by cbuck0222** [halcyon-tech/vscode-ibmi#408]
I didn't realize how much I relied on this feature in RDi until I started working recently in VS Code, but it would be nice to replicate the feature that allows you to hover over a variable, constant, file or some other element in your RPG/CL code to display a tool-tip like box that details the definition (data type, library/file defined in, etc.) of the item you're hovering. This is especially helpful when trying to follow existing programs you were not the author of. 

Example of RDi's hover over box for a work field:
![image](https://user-images.githubusercontent.com/86483883/143900790-79b59550-08fa-4726-bc6b-4350641629fd.png)

**Comment by cbuck0222** [comment]
@worksofliam Perhaps I'm missing it, but in the vscode-rpgle extension, is this not just an as-you-type assistant that displays the definition details? I was thinking more of box that appears when you hover your cursor over the element after it's already been typed, or more specifically a program that you are browsing and not necessarily writing/editing.

**Comment by worksofliam** [comment]
@cbuck0222 nope!

It is content assist, hover assist, outline view, and many other things.

**Comment by cbuck0222** [comment]
@worksofliam sorry, just want to make sure I'm understanding you. So you're saying I should be seeing some sort of definition detail for this variable when I hover over it? I see the other content assist and column assist features after installing the extension, but I'm not seeing this specific behavior. 

![image](https://user-images.githubusercontent.com/86483883/143938635-03049c40-cf16-49be-8576-287ccfe6bf64.png)

**Comment by worksofliam** [comment]
@cbuck0222 This is likely something to raise over on the correct repo, but as far as I am aware, the hover assist may only work for procedures. This is feature request you should absolutely raise.

Liam

**Comment by cbuck0222** [comment]
@worksofliam Gotcha. Just wanted to make sure I wasn't missing it or using it incorrectly before I did so. Thanks for your help and clarification!
