### ISSUE TITLE
Enable source dates in RPGLE-sources in VS-code  

### ISSUE THREAD

**Issue by wartsepp73** [halcyon-tech/vscode-ibmi#414]
Hi, does anybody know how I can enabled source dates in RPGLE-sources in VS-code ? I followed the instructions installed the extented IBM-pro addon, enabled SQL, enabled show source dates, but no unfortunately no success yet. Any help much appreciated :-) best regards, Wart Sepp

**Comment by wartsepp73** [comment]
Hi, does anybody know how I can enabled source dates in RPGLE-sources in VS-code ? I followed the instructions installed the extented IBM-pro addon, enabled SQL, enabled show source dates, but no unfortunately no success yet. Any help much appreciated :-) best regards, Wart Sepp

**Comment by worksofliam** [comment]
Hi @wartsepp73

What is the 'IBM pro' addon? Could you share a list of extensions you have installed? Thanks!

Also, what version of Code for IBM i do you have?

**Comment by wartsepp73** [comment]
Thanks for replying :-)
![image](https://user-images.githubusercontent.com/94969842/144246995-9792290c-27e4-45ae-8440-cf507eba08a4.png)
Version code for ibm i 0.8.3
Extension which I installed: HalcyonTechLtd.code-for-ibmi-0.8.2.vsix

**Comment by worksofliam** [comment]
@wartsepp73 Great! You have the right one installed.

Will you also share a screenshot of your connection settings? (or the JSON of it.)

Liam

**Comment by wartsepp73** [comment]
Ofcourse, appreciate your help !
![image](https://user-images.githubusercontent.com/94969842/144248384-e4605c5b-063d-4608-bf16-a436f8117719.png)

**Comment by worksofliam** [comment]
I didn't see this in the original screenshot, but it looks like SQL is not actually enabled.

![image](https://user-images.githubusercontent.com/3708366/144248723-ce24bebf-2c86-4d2d-aef1-9ba37dea4232.png)

You need to have `db2util` installed on your IBM i with yum.

Liam

**Comment by wartsepp73** [comment]
thanks Liam :-), I will try that right away, Wart

**Comment by worksofliam** [comment]
@wartsepp73 Great - thank you. Please post back when you have done that!

**Comment by wartsepp73** [comment]
Great Liam :-), that did the trick installing open source package db2util, the most important for me is that now the source-dates are not being set to 000000 (checked it in RDI and SEU) when changing the source in VScode.  The sourcedates are  shown now on the same line, it could be great when all the sourcedates are shown and it would be even more great to able to search on source-dates, but I understand that's not a easy fix. THANKS !

**Comment by worksofliam** [comment]
@wartsepp73 I am afraid there is no plans to show all source dates on every line, but there is a plan to make search dates searchable. The issue for that is #279. 

Thanks and enjoy!

**Comment by NextPage66** [comment]
I know this is closed but hoping someone will respond.
I am not sure how to install db2util on IBM i with yum. 
can someone help me out?
