### ISSUE TITLE
Add "Open Member" tool for exact Library/File/Member specification

### ISSUE THREAD

**Issue by cwbuck** [halcyon-tech/vscode-ibmi#416]
I find it takes a little extra time to navigate to the exact source member you're looking for by just scrolling through the current Object Browser, especially in larger source files. The filter options are helpful, but often I know exactly what source I'd like to open but have to expand the entire source file and scroll to find it. 

It would be nice to add something like RDi's "Open Member" tool where you can input the exact library, file and member you wish to open. This is accessed in RDi by a shortcut of Ctrl + Alt + Q. By pressing OK, if found, the member is then opened directly in the editor.

Input fields include:
Connection
Library
File
Member

![image](https://user-images.githubusercontent.com/68613130/144621714-cfa774fb-68e4-4942-9773-856768549b07.png)

**Comment by worksofliam** [comment]
A great idea. I am not sure we'd add the UI for it, but we do already have something like this, but doesn't have a default keybinding.

If you open the command palette (F1 or Control/Command + Shift + P) and search for 'open file', you'll see the option show up for IBM i: 

![image](https://user-images.githubusercontent.com/3708366/144623561-4dd029ef-98eb-407b-bc34-e4bcd676bc10.png)

Before selecting the option, you can press the cog icon on the item and give it a keybinding.

Then you can enter in a path:

![image](https://user-images.githubusercontent.com/3708366/144623700-39adb3b2-0e22-4bae-885f-567ad7ddd27d.png)

Right now, we don't ship with a default key binding. If you could suggest one, then maybe we could add it. I personally do not like Control/Command + Alt + Q. I do like Control/Command + Alt + O.

**Comment by cwbuck** [comment]
Nice! I didn't know about this. This is certainly faster than the browser list. I don't mind having to setup my own key binding. Just didn't know this existed. I've setup for Ctrl + Alt + O for now to try it out.

The RDi UI piece is helpful on some fronts. But I can certainly adapt to this. Only thing that is a little tedious is having to know the extension. My organization has tons of old code out there and it's not always even ILE code. So that's a little tough to remember at times.

**Comment by worksofliam** [comment]
@cwbuck Glad to show you!

Yes, I can see where the UI would come in place, but building that type of UI is not one of Code's strong points since it wants to be minimalistic (which I like).

I think for now we'll close this, but I may raise another issue for the default key binding.
