### ISSUE TITLE
outline not working. 

### ISSUE THREAD

**Issue by AjaykulkarniIBMi** [halcyon-tech/vscode-ibmi#418]
Hello, i am not seeing the outline populated. 
Is there something i need to turn on?

**Comment by worksofliam** [comment]
Outline for RPG is not part of this extension. See https://github.com/halcyon-tech/vscode-rpgle

**Comment by AjaykulkarniIBMi** [comment]
Sorry to not mention, I do have the new vs-code rpgle extension as well.
even the lint is not working.
i installed, closed vscode , opened it and the content assist, linter , outline is not wokring.
I have enabled it in the setting as well.

**Comment by AjaykulkarniIBMi** [comment]
@worksofliam  do you want me to open a new request? Let me know.
as it is not working yet, please help

**Comment by worksofliam** [comment]
@AjaykulkarniIBMi Please open the issue in the other repository.
