### ISSUE TITLE
Add terminal type support to the tn5250 terminal

### ISSUE THREAD

**Issue by Hadkins2** [halcyon-tech/vscode-ibmi#425]
Would be handy to have the ability to set the terminal type and possibly other configuration options to the tn5250 terminal window. 

env.TERM= is the configuration option for terminal type.

Possible values are: 
IBM-3179-2 | 24x80 monochrome (default)
IBM-3180-2 | 27x132 monochrome
IBM-3196-A1 | 24x80 monochrome
IBM-3477-FC | 27x132 color
IBM-3477-FG | 27x132 monochrome
IBM-5251-11 | 24x80 monochrome
IBM-5291-1 | 24x80 monochrome
IBM-5292-2 | 24x80 color

Also, not important to my shop, but could be important for some would be device name.
env.DEVNAME=NAME

Thanks!

Howard Adkins

**Comment by worksofliam** [comment]
Oh, this was released! Forgot to close this :)
