### ISSUE TITLE
How to turn off the lines supporting IF

### ISSUE THREAD

**Issue by AjaykulkarniIBMi** [halcyon-tech/vscode-ibmi#427]
How can this be turned off?
![CleanShot 2021-12-06 at 15 09 45](https://user-images.githubusercontent.com/37787504/144923529-f85943d5-c747-4f74-b272-50658c74ad67.png)

**Comment by worksofliam** [comment]
This is a VS Code feature, and not a feature specific to Code for IBM i.

See this possible answer. https://stackoverflow.com/a/54488167/4763757
