### ISSUE TITLE
Ability to call an initial program per connection 

### ISSUE THREAD

**Issue by fathert** [halcyon-tech/vscode-ibmi#430]
In RDi it's possible to call an initial program at connection time, per connection. I use this to set my job's library list (which is somewhat dynamic) as well as to set the system library to English (as I work on a German machine) and to do some other set-up work for my development environment. Such a feature would be really useful in VSCode for i too.

**Comment by worksofliam** [comment]
Interesting idea, but likely not possible. Compiles are run in a stateless fashion in their own job, and uses the user library list as set in the extension:

![image](https://user-images.githubusercontent.com/3708366/145234987-8b07309c-6b37-4d2d-b766-30bc3de208bf.png)

> set the system library to English

What command do you use to do this? Perhaps we could add some support to set the 'system library'?

I would recommend you check out connection profiles if you need to switch between environments/projects on a single connection: https://halcyon-tech.github.io/vscode-ibmi/#/?id=connection-profiles

**Comment by fathert** [comment]
Thanks for the reply Liam

```
CHGSYSLIBL LIB(QSYS2924) OPTION(*ADD)
```
...is used to change the system library.

How about the ability to define more than one command per action? We use Turnover which creates development libraries for each task, my initial program adds any task libraries to my library list automatically for my active tasks, so I always have them in the library list. I could manually maintain the current library list, but it's just nicer not to have to think about it. The connection profiles don't seem to work for me, I set one up but switching to it has no impact on the library that's used to compile, I will try to replicate and submit a bug report it if necessary. In any case, they're not quite what I'm after.

I also use...
```
 ADDENVVAR  ENVVAR(RPGINCDIR) VALUE('/home/tim/Source')
```
.. in the initial program to set a list of include paths that are sometimes needed.

If all else fails, I can probably get around it by wrappering the compile commands.

Thanks,

Tim.

**Comment by worksofliam** [comment]
@fathert I see you're appending to the system library list! Not something anyone has asked for before. Up until now, we've only allowed the user to manage the user library list.

I am open to the idea of adding the ability to manage the system library list, but I'd love to hear ideas on how you'd expect the user (you) to do that in VS Code.

> How about the ability to define more than one command per action?

I do like this idea. Perhaps we could make it so the command box in the Actions is a multi-line and each line is a separate command. Likely needs a separate issue as this is a large change.

About environment variables for Actions: another good idea. There is actually a way to set connection variables (which can be used in Actions as variables), but maybe those connection variables should have a setting on there so they are also created as environment variables when the action is run. What do you think of that?

**Comment by fathert** [comment]
I guess relatively few people work on a machine where the primary language isn't the one in which they wish to work 😄 but it's the way you have to do it if you want to use a secondary installed language. In terms of a solution, I think multiple commands per action would solve all of them, I could just call my CL first to set-up the environment and then that would manage everything, or add multiple commands to set the system library, env vars, etc.. I'm not convinced that it really warrants a special place in VS Code to set it.

**Comment by worksofliam** [comment]
Okay, that makes sense to me too.

Do you want to close this issue and raise another for the multiple commands in an Action?

**Comment by fathert** [comment]
Yeah sure! Thanks again.
