### ISSUE TITLE
Multi commands in an action

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#432]
As suggested by @fathert - I am going to make it so actions can run multiple commands in one action.

I did check, and they do all still run in their own job, so environment variables cannot be shared across them. The library list is inherited from VS Code user library list for each command.

```
ADDENVVAR ENVVAR(VSCODE) VALUE('Hello from vscode') LEVEL(*JOB)
CRTBNDRPG PGM(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*EVENTF) DBGVIEW(*SOURCE) TGTRLS(*CURRENT)
DSPJOB OUTPUT(*PRINT)
```

The last `DSPJOB` would be missing `VSCODE` from the env vars, because they are all stateless.

**Comment by worksofliam** [comment]
@fathert would you be interested in testing the feature? If you check the linked PR, there is a build you can install there.

**Comment by fathert** [comment]
> @fathert would you be interested in testing the feature? If you check the linked PR, there is a build you can install there.

Yeah, sure! I'm travelling ATM but on Monday I'll have a look, thanks.

**Comment by fathert** [comment]
Yeah, sure. Sorry, I've been travelling so only just caught up, I'll try it today. Thanks!

**Comment by fathert** [comment]
Hi Liam,

Reading this...

_Command to run
Below are available variables based on the Type you have select below. You can specify different commands on each line. **Each command run is stateless and run in their own job.**_

...and your comment above RE: envvars, I don't think this solves my original issue because neither the library list, system library nor the ENVVAR changes would have any effect on the compile command - or have I missed something?

Ta. Tim.

**Comment by worksofliam** [comment]
@fathert I am afraid that's true. It does kind of suck, I think that's just the nature of using SSH are our architecture - it just doesn't work like a normal ILE job.

**Comment by fathert** [comment]
No worries, thanks for trying. I've got round it for now by creating a wrapper command which first sets my environment and then executes the supplied build command:
![image](https://user-images.githubusercontent.com/8808151/145824659-7f017d47-2300-4421-b064-75f66820ac95.png)

**Comment by worksofliam** [comment]
@fathert Excellent! Sorry for the trouble.
