### ISSUE TITLE
Upload workspace to directory

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#438]
I was using the Azure App Services extension in VS Code today, and they have the ability to deploy your workspace right to an App Service. While not the same, I'd like the ability to right-click on a remote directory and have 'Deploy Workspace', which will upload the contents of your workspace into the chosen folder.

It needs different modes:

* Upload all (raw) - uploads each file in the workspace individually to the chosen folder
* Upload all (zip) - creates a zip of the workspace, uploads it to `/tmp` and then extracts it to the chosen folder
* Changes (raw) - only uploads changed files (perhaps using the local git client to determine what has changed?)
    * git API example: https://stackoverflow.com/a/60238771/4763757

**Comment by worksofliam** [comment]
* Perhaps we also need 'local' actions too? 
   * Commands would still only run on the server
* If the file is local, an option to run the workspace upload before the action is run?
* If the file is local, and the command includes *EVENTF, convert the errors to point to local files?

**Comment by worksofliam** [comment]
Example:

* Am developing ILE app locally
* Want to upload and build
* Run action
    1. Triggers workspace upload (changes only, thanks git)
    2. Runs action command
    3. Bring errors down and points them to local files?

**Comment by worksofliam** [comment]
New potential file idea?

`.vscode/actions.json`

When the user connections and this file exists in the workspace, it will prompt them to import those missing actions. That way, actions can also be tied to the project. Awesome.

**Comment by edmundreinhardt** [comment]
This is cool, I imagine you are supporting both Windows and Mac.  For Mac, rsync does a brilliant job of this. For Windows, you could prereq cygwin and have a path to it in your preferences (clunky) or write your own.  

With the build actions, they will need substitution parameters for things like the current file name (in case you want to just build the object for that source file and its prereqs)   - so your stored action becomes something like 'makei {filename}'  and you would have another action for 'makei all' that would build the whole project.
Not that by passing the name of the edited file to makei, makei will map that to the associated target object internally and make that object.  There is no magic here.  It uses https://github.com/IBM/ibmi-bob/blob/master/mk/filetypeTargetMap.inc to do the mapping.

So to invoke these actions your shell script will do
1. Synchronize workspace dir to IFS dir
2. Invoke build command  which contains
  - ensure Bob in path i.e. 'export PATH=/QOpenSys/pkgs/bin:$PATH'
  - for any variables in the project definition do 'export <var>=<value>'  
  - makei command with any replacements done
3. bring back contents of .logs directory which has joblog.json for IBM i job log and output.log for makei output

For explanation of project definition variables see https://github.com/IBM/ibmi-bob/wiki/project-metadata
```
Variables (can be used to name libraries for the object library or library list, or directories for the include path). This allows the same project definition to target a different build library from one developer to another. It would also allow Bob to be used in CI/CD pipelines. Before invoke a Bob build, an environment variable should be set with the same name as the Bob variable and with the desired value for that build. So if the iproj.json said to use &objlib1 for the OBJLIB for compiles within a directory and the PASE command export objlib1=PROJ_QA1 is run, then the environment variable objlib1 would be set to “PROJ_QA” before invoking the build command. Within the build shell script the value could be referenced via &objlib1. Similarly the CI/CD mechanisms can set up directories and object libraries using the exact same environment variable names.
```

**Comment by worksofliam** [comment]
> bring back contents of .logs directory which has joblog.json for IBM i job log and output.log for makei output

@edmundreinhardt do you not write this information to standard out or standard error in the makei command?

**Comment by worksofliam** [comment]
@edmundreinhardt 

> This is cool, I imagine you are supporting both Windows and Mac. For Mac, rsync does a brilliant job of this. For Windows, you could prereq cygwin and have a path to it in your preferences (clunky) or write your own.

It'll likely be the latter, though I won't be writing the upload. The library I am using for the connection (ssh2) has all the APIs I need to upload/download files, so I may as well just use that so it is then cross-platform with no extra deps.
