### ISSUE TITLE
Add &OPENMBRTXT as a parameter in Actions

### ISSUE THREAD

**Issue by Hadkins2** [halcyon-tech/vscode-ibmi#446]
Would be handy for some iSeries commands such as CRTSRVPGM to pick up text of the source member you created the *MODULE from to create the *SRVPGM with since the default for the CRTSRVPGM command is *BLANK.

![image](https://user-images.githubusercontent.com/95584606/146606862-0f43cacb-108d-4689-85dc-540e41c32cb3.png)

![image](https://user-images.githubusercontent.com/95584606/146607064-c1bdbf36-bf6d-4474-a443-42a9f33f7b0e.png)

Thanks,

Howard Adkins

**Comment by worksofliam** [comment]
A neat idea for sure. I will see what I can do.

In the mean time, are you passing in `TEXT(*MODULE)` into `CRTSRVPGM`?

**Comment by Hadkins2** [comment]
I am not seeing *MODULE as a valid value for the TEXT parm on CRTSRVPGM.  I am on V7R3 TR5.  Unsure if they added that in later releases.

![image](https://user-images.githubusercontent.com/95584606/146613446-a6bb513c-7daf-41db-859b-744770e585a6.png)

**Comment by worksofliam** [comment]
@Hadkins2 That's unfortunate. I did only check the 7.4 docs and it is there. I will still see about adding it.

https://www.ibm.com/docs/en/i/7.4?topic=ssw_ibm_i_74/cl/crtsrvpgm.htm#CRTSRVPGM.TEXT

**Comment by Hadkins2** [comment]
No need to expend energy on a feature that is coming from IBM.  My penalty for not having the system more current.
