### ISSUE TITLE
Unable to open member with "color codes"

### ISSUE THREAD

**Issue by MarkBoyer** [halcyon-tech/vscode-ibmi#450]
It's a fairly standard practice to use "color codes" to highlight comments in source.  It's seems the editor in VSC has an issue if the code for yellow with column separators is used.

![Screen Shot 2021-12-20 at 2 01 21 PM](https://user-images.githubusercontent.com/3966735/146839130-22061e48-60c2-47dc-aa77-85c343443825.png)

The data gets retrieved according to the Output panel:

/home/wg446mb: DB2UTIL_JSON_CONTAINER=array /QOpenSys/pkgs/bin/db2util -o json "select srcdat, REPLACE(rtrim(srcdta), ' ', '.+') as srcdta from ILEDITOR.RM12P446B_SRCFILE_WOCRTT_MB"
{
    "code": null,
    "signal": null,
    "stdout": "[\n{\"SRCDAT\":211220,\"SRCDTA\":\".+.+.+.+.+--.+Before.+--\"},\n{\"SRCDAT\":170418,\"SRCDTA\":\".+.+.+.+.+\u0016*.+Outside.+Labor\"},\n{\"SRCDAT\":211220,\"SRCDTA\":\".+.+.+.+.+--.+After.+--\"}\n]",
    "stderr": ""
}

using space to remove the color code, which causes the "\u0016" to be removed allows the member to be opened:

/home/wg446mb: DB2UTIL_JSON_CONTAINER=array /QOpenSys/pkgs/bin/db2util -o json "select srcdat, REPLACE(rtrim(srcdta), ' ', '.+') as srcdta from ILEDITOR.RM12P446B_SRCFILE_WOCRTT_MB"
{
    "code": null,
    "signal": null,
    "stdout": "[\n{\"SRCDAT\":211220,\"SRCDTA\":\".+.+.+.+.+--.+Before.+--\"},\n{\"SRCDAT\":211220,\"SRCDTA\":\".+.+.+.+.+.+*.+Outside.+Labor\"},\n{\"SRCDAT\":211220,\"SRCDTA\":\".+.+.+.+.+--.+After.+--\"}\n]",
    "stderr": ""
}

Any thoughts?

**Comment by worksofliam** [comment]
Fun! I will have to look into it - good find.

**Comment by worksofliam** [comment]
@MarkBoyer are you getting a specific error or does it just not open?

**Comment by MarkBoyer** [comment]
@worksofliam no, there is no error message, the editor is just never displayed.

**Comment by worksofliam** [comment]
@MarkBoyer Silly question, but how can I type this character into SEU? I can just copy it from the website and save the member?

https://www.cogsci.ed.ac.uk/~richard/utf-8.cgi?input=0016&mode=hex

**Comment by MarkBoyer** [comment]
@worksofliam I'm not sure if that will do it.  I've use keybinds in Client Access before and had a tool once upon a time to use SEU line commands, but usually just copy from an existing comment.  I've saved some sample source, here is the savf.  Let me know if this doesn't work for you.
[vsc450.savf.zip](https://github.com/halcyon-tech/vscode-ibmi/files/7757461/vsc450.savf.zip)

**Comment by worksofliam** [comment]
@MarkBoyer Any chance you can just share the EBCDIC hex of the character? I will hardcode it in SEU that way

**Comment by onewheelonly** [comment]
Probably 0x32:

http://www.classanova.com/view?id=1382&p=5

**Comment by MarkBoyer** [comment]
@worksofliam sorry, I misunderstood your question.  If you are using the IBM i Access Client emulator (java), you can go to Edit->Preferences->Keyboard, and scroll until you see the QSN_SA_* characters that let you map to the colors.  Yes, @onewheelonly is correct and the yellow is X'32'.  I have not tested all of the other options.  I can tell you that blue (3A), green(20), red(28) and pink(38) seem to not give any issues.
![Screen Shot 2021-12-21 at 1 29 46 PM](https://user-images.githubusercontent.com/3966735/147000545-6bbc7b8c-7295-4113-ad8d-5e796c57dbeb.png)

**Comment by worksofliam** [comment]
Here's the JSON response for future reference.

```json
[
  {
    "SRCDAT": 0,
    "SRCDTA": "**FREE"
  },
  {
    "SRCDAT": 0,
    "SRCDTA": ""
  },
  {
    "SRCDAT": 0,
    "SRCDTA": "ctl-opt.+dftactgrp(*no);"
  },
  {
    "SRCDAT": 0,
    "SRCDTA": ""
  },
  {
    "SRCDAT": 0,
    "SRCDTA": "dcl-s.+testc.+char(52);"
  },
  {
    "SRCDAT": 0,
    "SRCDTA": ""
  },
  {
    "SRCDAT": 211103,
    "SRCDTA": "dsply.+testc;.+//Hello.+world"
  },
  {
    "SRCDAT": 0,
    "SRCDTA": ""
  },
  {
    "SRCDAT": 0,
    "SRCDTA": "//Yes.+this.+is.+aqesomeddddasddadsdasdd.+Hello.+world!!!"
  },
  {
    "SRCDAT": 211221,
    "SRCDTA": "//.+\u0016hello"
  },
  {
    "SRCDAT": 0,
    "SRCDTA": "return;"
  },
  {
    "SRCDAT": 0,
    "SRCDTA": ""
  },
  {
    "SRCDAT": 0,
    "SRCDTA": "dcl-proc.+testp;"
  },
  {
    "SRCDAT": 0,
    "SRCDTA": ".+.+dcl-pi.+*n.+char(1).+end-pi;"
  },
  {
    "SRCDAT": 0,
    "SRCDTA": ""
  },
  {
    "SRCDAT": 0,
    "SRCDTA": ".+.+//Awesome.+test.+yo"
  },
  {
    "SRCDAT": 0,
    "SRCDTA": ""
  },
  {
    "SRCDAT": 0,
    "SRCDTA": ".+.+return.+'a';.+//Super.+nice"
  },
  {
    "SRCDAT": 0,
    "SRCDTA": "end-proc;"
  }
]
```

**Comment by worksofliam** [comment]
Future change: show a message to the user. Turns out it's a parsing error, likely due to that character. Fun.. will see what I can do about that.

![image](https://user-images.githubusercontent.com/3708366/147019041-04efb4fe-b7e6-4ab7-b2c8-079946d28ea9.png)

**Comment by worksofliam** [comment]
VS Code shows the invalid character nicely. Now to figure out what to do with it.

![image](https://user-images.githubusercontent.com/3708366/147019552-b1c3cf9b-b8cb-4b1f-9878-5984b8b7d2bc.png)

**Comment by worksofliam** [comment]
Dare I? https://stackoverflow.com/a/51602415/4763757

**Comment by worksofliam** [comment]
I got it to work, but this fix would remove the character completely. Control characters aren't valid in JSON strings.

**Comment by worksofliam** [comment]
@MarkBoyer I am torn. If I release this fix, it will solve the issue, but remove the characters entirely. Would love your thoughts on that.

**Comment by MarkBoyer** [comment]
@worksofliam I ran more of a test.  I tried several of the more common colors:
![Screen Shot 2021-12-21 at 1 44 02 PM](https://user-images.githubusercontent.com/3966735/147024069-e13839ab-30db-4a15-aa17-8bb97cee8a66.png)
I had to comment out the yellow that is the source of this ticket, however the rest came through fine:
![Screen Shot 2021-12-21 at 6 19 30 PM](https://user-images.githubusercontent.com/3966735/147024114-909e622f-927e-4815-91ee-fea5784c3271.png)
As you can see , the code for green converts to a printable character.

So to answer your question, I have two thoughts:
1) Use some character, or character set the way that ".+" is used for spaces, and replace when after retrieving and before writing back to the i.
2)  If you don't like 1, maybe at least a dialog that explains codes will be stripped and gives the user a chance to proceed or cancel?

If there weren't so many that still used SEU and use the colors codes, it wouldn't be necessary, buuuuut.  :)  In my case, if it's just the color code for yellow that is ever the issue, it's not a deal breaker, but it would flag that as a changed line of code, maybe not through the editor, but when it runs through the rest of the merge process in my environment.

**Comment by worksofliam** [comment]
@MarkBoyer If yellow is the only issue, then perhaps we could just make it replace that character when read, and then fix it on the way back up.. not a bad idea. Let me have a whirl.

Thanks so much for testing other colors. It does seem yellow is the only issue.

**Comment by worksofliam** [comment]
@MarkBoyer 

> Use some character, or character set the way that ".+" is used for spaces, and replace when after retrieving and before writing back to the i.

I do like this idea but I am not sure what character we should display when a control character is there. Now bare in mind, control characters are fine, it's just the JSON parsing that it doesn't like - putting it back into the database might be an issue too. I guess I will have to play around with it and let you know.

> If you don't like 1, maybe at least a dialog that explains codes will be stripped and gives the user a chance to proceed or cancel?

If I can't find a way, it'll likely be this.

The good news is that I actually show an error when the file fails to open now.

Liam

**Comment by worksofliam** [comment]
@MarkBoyer I think I will get this merged in sooner than later. The plan is to warn people about it in the connection settings and automatically remove them.

**Comment by worksofliam** [comment]
Hey @MarkBoyer 

Can you see how this behaves in 0.9.x? We actually changed how we fetch members with source dates in recent changes.

Thanks!

**Comment by worksofliam** [comment]
I just checked, and it looks like the files are now openable even with the color codes, but add the invalid character symbol (in red) as part of the editor.

![image](https://user-images.githubusercontent.com/3708366/154851515-7b781f97-7318-42be-b42e-5b2f87c99cd3.png)

**Comment by worksofliam** [comment]
@LGSDEVS There is an option in the Code for IBM i settings to enable colours in the source.
