### ISSUE TITLE
Error message "Cannot read property 'trim' of undefined" when opening filter.

### ISSUE THREAD

**Issue by makins11** [halcyon-tech/vscode-ibmi#456]
I just installed vscode and code for IBMI.   I was able to connect and added some filters.   I get the message "Cannot read property 'trim' of undefined" when I try to browse the filter.  The ifs browser function works.

**Comment by worksofliam** [comment]
@makins11 Please share you JSON configuration here. That will let me recreate it, hopefully!

Thanks,
Liam

**Comment by makins11** [comment]
Here you go.  Thanks. 


{
    "code-for-ibmi.connectionSettings": [
        {
            "name": "hanna.hannasteel.com",
            "objectFilters": [
                {
                    "name": "New Filter",
                    "library": "HSCPLIB",
                    "object": "QRPGLESRC",
                    "types": [
                        "*SRCPF"
                    ],
                    "member": "*",
                    "undefined": "New Filter",
                    "New Filter": "New Filter"
                },
                {
                    "name": "New Filter",
                    "library": "M_AKINS",
                    "object": "Q*",
                    "types": [
                        "*SRCPF"
                    ],
                    "member": "*",
                    "undefined": "New Filter"
                },
                {
                    "name": "test",
                    "library": "M_AKINS",
                    "object": "*",
                    "types": [
                        "*ALL"
                    ],
                    "member": "*",
                    "undefined": "test"
                }
            ],
            "databaseBrowserList": [
                "QTEMP",
                "QGPL"
            ],
            "libraryList": [
                "QTEMP",
                "QGPL",
                "HSCPLIB"
            ],
            "customVariables": [],
            "connectionProfiles": [],
            "ifsShortcuts": [
                "/home/makins"
            ],
            "homeDirectory": "/home/makins",
            "tempLibrary": "ILEDITOR",
            "currentLibrary": "QGPL",
            "sourceFileCCSID": "*FILE",
            "enableSQL": false,
            "hideCompileErrors": [],
            "enableSourceDates": false,
            "sourceDateLocation": "none",
            "clContentAssistEnabled": false,
            "encodingFor5250": "default",
            "terminalFor5250": "default",
            "setDeviceNameFor5250": false,
            "autoSaveBeforeAction": false,
            "sourceASP": null
        }
    ],
    "code-for-ibmi.connections": [
        {
            "name": "hanna.hannasteel.com",
            "host": "hanna.hannasteel.com",
            "port": 22,
            "username": "m_akins",
            "privateKey": null
        }
    ],
    "security.workspace.trust.untrustedFiles": "open"
}






From:   "barry" ***@***.***>
To:     "halcyon-tech/vscode-ibmi" ***@***.***>
Cc:     "makins11" ***@***.***>, "Mention" 
***@***.***>
Date:   01/03/2022 01:31 PM
Subject:        Re: [halcyon-tech/vscode-ibmi] Error message "Cannot read 
property 'trim' of undefined" when opening filter. (Issue #456)



@makins11 Please share your JSON configuration here. That will let me 
recreate it, hopefully!
Thanks,
Liam
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you were mentioned.Message ID: 
***@***.***>

**Comment by worksofliam** [comment]
@makins11 Would you also mind sharing a screenshot of the error that appears?

Thanks!

**Comment by makins11** [comment]
This message when opening the first filter. 



This message when opening filter "test" - Cannot read property 
'startsWith' of undefined

**Comment by worksofliam** [comment]
@makins11 What version of Code for IBM i are you using and what version of IBM i are you connecting to?

Liam

**Comment by worksofliam** [comment]
@makins11 Just seems `type` is not coming back from the outfile? Weird.

Are you able to do the following?

1. `DSPOBJD OBJ(M_AKINS/*ALL) OBJTYPE(*ALL) OUTPUT(*OUTFILE) OUTFILE(QTEMP/OBJECTLIST)`
2. Convert that to CSV with `CPYTOIMPF`
3. Either upload the CSV here or email to `liam[@]worksofbarry.com`

Liam

**Comment by makins11** [comment]
From:   "barry" ***@***.***>
To:     "halcyon-tech/vscode-ibmi" ***@***.***>
Cc:     "makins11" ***@***.***>, "Mention" 
***@***.***>
Date:   01/03/2022 02:27 PM
Subject:        Re: [halcyon-tech/vscode-ibmi] Error message "Cannot read 
property 'trim' of undefined" when opening filter. (Issue #456)



@makins11 Just seems type is not coming back from the outfile? Weird.
Are you able to do the following?
DSPOBJD OBJ(M_AKINS/*ALL) OBJTYPE(*ALL) OUTPUT(*OUTFILE) 
OUTFILE(QTEMP/OBJECTLIST)
Convert that to CSV with CPYTOIMPF
Either upload the CSV here or email to liam[@]worksofbarry.com
Liam
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you were mentioned.Message ID: 
***@***.***>

**Comment by worksofliam** [comment]
@makins11 Looks like your reply didn't have anything in it.

**Comment by makins11** [comment]
Where do I find the code for IBM i version?   I just did the install about 
a week or so ago so it should be pretty current.   Version 7.2 with 
current ptfs. 





From:   "barry" ***@***.***>
To:     "halcyon-tech/vscode-ibmi" ***@***.***>
Cc:     "makins11" ***@***.***>, "Mention" 
***@***.***>
Date:   01/03/2022 02:15 PM
Subject:        Re: [halcyon-tech/vscode-ibmi] Error message "Cannot read 
property 'trim' of undefined" when opening filter. (Issue #456)



@makins11 What version of Code for IBM i are you using and what version of 
IBM i are you connecting to?
Liam
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you were mentioned.Message ID: 
***@***.***>

**Comment by worksofliam** [comment]
@makins11 You can find it in the extensions panel by clicking on the Code for IBM i extension.

Would you still be able to run the command to get the object list?

**Comment by makins11** [comment]
Code for IBM i v0.8.18




From:   "barry" ***@***.***>
To:     "halcyon-tech/vscode-ibmi" ***@***.***>
Cc:     "makins11" ***@***.***>, "Mention" 
***@***.***>
Date:   01/03/2022 03:01 PM
Subject:        Re: [halcyon-tech/vscode-ibmi] Error message "Cannot read 
property 'trim' of undefined" when opening filter. (Issue #456)



@makins11 You can find it in the extensions panel by clicking on the Code 
for IBM i extension.
Would you still be able to run the command to get the object list?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you were mentioned.Message ID: 
***@***.***>

**Comment by worksofliam** [comment]
@makins11 Great - thanks! I will wait for you to share the CSV with me.

**Comment by makins11** [comment]
This should be the object list





From:   "barry" ***@***.***>
To:     "halcyon-tech/vscode-ibmi" ***@***.***>
Cc:     "makins11" ***@***.***>, "Mention" 
***@***.***>
Date:   01/03/2022 03:14 PM
Subject:        Re: [halcyon-tech/vscode-ibmi] Error message "Cannot read 
property 'trim' of undefined" when opening filter. (Issue #456)



@makins11 Great - thanks! I will wait for you to share the CSV with me.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you were mentioned.Message ID: 
***@***.***>

**Comment by worksofliam** [comment]
@makins11 You cannot reply to GitHub with attachments. 

Either paste it into the issue or send it to my email (`liam[@]worksofbarry.com`)

**Comment by makins11** [comment]
Got it.   Sorry.    I created a new empty source file and I'm getting the 
same error message when I try to browse it. 





From:   "barry" ***@***.***>
To:     "halcyon-tech/vscode-ibmi" ***@***.***>
Cc:     "makins11" ***@***.***>, "Mention" 
***@***.***>
Date:   01/03/2022 03:17 PM
Subject:        Re: [halcyon-tech/vscode-ibmi] Error message "Cannot read 
property 'trim' of undefined" when opening filter. (Issue #456)



@makins11 You cannot reply to GitHub with attachments.
Either paste it into the issue or send it to my email (
liam[@]worksofbarry.com)
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you were mentioned.Message ID: 
***@***.***>

**Comment by worksofliam** [comment]
@makins11 No problem!

Yes, it seems like the OUTFILE is missing some columns. I can confirm this with the CSV :)

Liam

**Comment by worksofliam** [comment]
Hey @makins11 

Just so you are aware, there isn't much more I can do without that data. I will keep it open for now, but please get that over to me whenever you are able to.

Thanks!

**Comment by makins11** [comment]
Should be on its way.




From:   "barry" ***@***.***>
To:     "halcyon-tech/vscode-ibmi" ***@***.***>
Cc:     "makins11" ***@***.***>, "Mention" 
***@***.***>
Date:   01/03/2022 03:47 PM
Subject:        Re: [halcyon-tech/vscode-ibmi] Error message "Cannot read 
property 'trim' of undefined" when opening filter. (Issue #456)



Hey @makins11
Just so you are aware, there isn't much more I can do without that data. I 
will keep it open for now, but please get that over to me whenever you are 
able to.
Thanks!
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you were mentioned.Message ID: 
***@***.***>

**Comment by makins11** [comment]
I found this 

https://archive.midrange.com/midrange-l/201903/msg00679.html

CRTDTAARA DTAARA(QTEMP/QCPTOIMPF) TYPE(*CHAR) LEN(6) VALUE('NO')


https://www.ibm.com/support/pages/cpyfrmimpf-and-cpytoimpf-data-areas

**Comment by worksofliam** [comment]
So after some chat with @makins11, it looks like his CPYTOIMPF command is not adding headings at all.

> Used a different program 
> 
> SNDFEXCEL SNDF((QTEMP/OBJECTLIST '*FILE.*TRNEXT' *FIRST *ALL *MBR *NONE)) 
>  COLHDG(*ALIAS) TRANSFORM(*CSVUTF8)                                       
> 
> I tried the CPYTOIMPF wtih ADDCOLNAM(*SYS) and ADDCOLNAM(*SQL) and neither one produced column headings.  

This means there might be a PTF issue on the system. I am not sure this is related to Code for IBM i.

The IBM link you provided where it suggested creating the data area looks like a good fix. You should create it, try the command again and then try Code for IBM i, then post back here.

**Comment by makins11** [comment]
That data area existed.   I deleted it and Code for IBM i works now. 
Thanks. 





From:   "barry" ***@***.***>
To:     "halcyon-tech/vscode-ibmi" ***@***.***>
Cc:     "makins11" ***@***.***>, "Mention" 
***@***.***>
Date:   01/03/2022 04:33 PM
Subject:        Re: [halcyon-tech/vscode-ibmi] Error message "Cannot read 
property 'trim' of undefined" when opening filter. (Issue #456)



So after some chat with @makins11, it looks like his CPYTOIMPF command is 
not adding headings at all.
Used a different program
SNDFEXCEL SNDF((QTEMP/OBJECTLIST '*FILE.*TRNEXT' *FIRST *ALL *MBR *NONE))
COLHDG(*ALIAS) TRANSFORM(*CSVUTF8)
I tried the CPYTOIMPF wtih ADDCOLNAM(*SYS) and ADDCOLNAM(*SQL) and neither 
one produced column headings.
This means there might be a PTF issue on the system. I am not sure this is 
related to Code for IBM i.
The IBM link you provided where it suggested creating the data area looks 
like a good fix. You should create it, try the command again and then try 
Code for IBM i, then post back here.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you were mentioned.Message ID: 
***@***.***>
