### ISSUE TITLE
Where's the server browser?

### ISSUE THREAD

**Issue by fathert** [halcyon-tech/vscode-ibmi#461]
Hello, maybe I'm blind, but I can't seem to find the server browser again once I am connected and the connection is interrupted. When my network connection is unstable and I'm disconnected I can find no way to reconnect. Attempting a "reconnect to previous" gives me the following message:
![image](https://user-images.githubusercontent.com/8808151/148365860-f2773bbe-0dc3-4f34-ab79-a31968b6f663.png)

How to I get back to the list of servers again that's displayed initially:
![image](https://user-images.githubusercontent.com/8808151/148366299-481c2a22-ea48-46bb-84c3-4bc5b593d77a.png)

I only see these browsers:
![image](https://user-images.githubusercontent.com/8808151/148367207-ba7b28f3-b8df-4fa9-a19f-eb51f0e3ff52.png)

TIA

Tim.

**Comment by worksofliam** [comment]
@fathert You have to be fully disconnected. Sometimes, when you lose connection the extension can ask if you want to connect again in a popup window.

Otherwise, try opening the command palette and searching for `Disconnect`. Or restarting VS Code.

**Comment by fathert** [comment]
The problem is that you cannot disconnect without saving your code and you cannot save your code with being connected and so you end up in a catch-22 situation. At the moment I'm having to copy my changes into another editor, restart VS-code and paste it back, which when you have to do it many time a day is a bit of a pain to say the least. 

Do you reckon there's a way to allow us to get back to the server browser to reconnect again or to at least allow a forced disconnect with unsaved code?

Thanks!

Tim.

**Comment by worksofliam** [comment]
@fathert Why are you being disconnected so often?

Usually, when you get disconnected, a little window shows (in the bottom right) up asking if you want to reconnect. This only shows up if the connection knows it has been disconnected.

Sounds like I will need to come up with some ideas about forcing a reconnect

**Comment by fathert** [comment]
From time to time my internet connection is unstable (as today) because my ISP here in Lisbon is flaky, other times I code on the road with a mobile connection, which can be similarly flaky. ZScaler sometimes seems to play up, which my company use in lieu of a VPN, and we're also forcibly disconnected after a timeout or a few hours for security reasons. Today it's particularly bad and is going to be a showstopper for me for the time being unfortunately. 

It would be great if it could be forcibly reconnected somehow.

As always, thanks!

**Comment by worksofliam** [comment]
I will think of a way to let the user force reconnect to the remote server so the files don't have to close.

Thanks!

**Comment by worksofliam** [comment]
A brand new configuration has been added, which when enabled will add a new button to the action bar at the bottom.

![image](https://user-images.githubusercontent.com/3708366/148456605-dabf9281-d40e-459c-a879-50f651b5d591.png)

Clicking the button will force reconnect to the IBM i you're connected to.

![image](https://user-images.githubusercontent.com/3708366/148456898-e3c2e968-c8b2-4e0d-bbea-17d175649a77.png)

**Comment by worksofliam** [comment]
Will be out in the next release.

**Comment by fathert** [comment]
Great, thanks, I'll check it out.
