### ISSUE TITLE
Structure subroutine Program

### ISSUE THREAD

**Issue by XCcl** [halcyon-tech/vscode-ibmi#466]
Hi,

Is there options, a way to display the subroutine program structure as on RDI (Rational Developer for i) ? 

in attach, a capture.

Thanks

![Capture](https://user-images.githubusercontent.com/54525854/148573858-3dd7958f-11a3-400f-b71b-ba1ade686e46.PNG)

**Comment by worksofliam** [comment]
You might be looking for RPGLE language tools.

Thought note, it only supports total free format.

* https://marketplace.visualstudio.com/items?itemName=HalcyonTechLtd.vscode-rpgle
* https://github.com/halcyon-tech/vscode-rpgle
