### ISSUE TITLE
How to setup larger timeout?

### ISSUE THREAD

**Issue by ssamayoa** [halcyon-tech/vscode-ibmi#469]
My IBM-I server is small / very resource limited and seems that because of that when is retrieving file lists I always get "Connection to XXXX has timed out".

How can I setup a larger timeout?

**Comment by worksofliam** [comment]
Right now it is hardcoded to 35000ms, but perhaps it is your iBM i system timing out your SSH connection?

* Verify the TCP keepalive on the iSeries (`CHGTCPA`). - TCP keep alive 
* Any timeout settings in the `sshd_config`

**Comment by ssamayoa** [comment]
Hi @worksofliam 

I just found out that the problem is when "liblist" runs qsh is returning exit code 9 but "timeout", "end" and "error" events  are mapped to "disconnected" function - I will look deeper into why my IBM-I is returning exit code other than 0 (FWIW is OS 7.1), also get deeper into how to work with VS plugins and add a different function for error.

**Comment by worksofliam** [comment]
This is likely the same issue as https://github.com/halcyon-tech/vscode-ibmi/issues/389.

Also, for the record, we do not formally support 7.1. I will help where I can though.

**Comment by ssamayoa** [comment]
@worksofliam 
Thanks - next time I will extend my search to closed issues.
Seems that the open utilities aren't well configured, looks like I will have to continue using PDM/SEU on that host.
I'm closing the issue.
