### ISSUE TITLE
Right-click to Show File Info on IFS files from IFS Browser

### ISSUE THREAD

**Issue by richardschoen** [halcyon-tech/vscode-ibmi#47]
Just to be able to see all the standard IFS attributes. 

Could even trigger one of the CL commands to show the output of DSPATR or whatever Cl command shows file attributes.

**Comment by worksofliam** [comment]
Our new UI tools might be able to do this.

**Comment by worksofliam** [comment]
I am not sure there is an easy way to get information about a streamfile from an outfile or somewhere in the database.

Any ideas @richardschoen? I personally don't want to parse the output of `DSPATR`.

**Comment by richardschoen** [comment]
The magic of SQL: https://www.ibm.com/support/pages/retrieving-information-about-objects-ifs

**Comment by szsascha** [comment]
@worksofliam You mentioned that the new UI tools are able to do this. What's the progress on this? Can this issue be solve by community?

**Comment by worksofliam** [comment]
@szsascha Of course.

I personally don't know the answer to this issue. VS Code doesn't even have a way to view information about files, so I'm open to ideas on how this should work.

**Comment by szsascha** [comment]
@worksofliam 
I could imagine that it is possible to display file attributes like the fields are listed in the database browser. So each object (ifs or i) could be an "expandable" entry. This would also open a possibility to change object attributes.

**Comment by worksofliam** [comment]
Not possible with the regular explorer, and therefore will not try to add something for IBM i. Not sure what the UI would look like.

**Comment by richardschoen** [comment]
Here’s something could use as a template.

All my other IFS explorer tools support it.

https://marketplace.visualstudio.com/items?itemName=brunnerh.file-properties-viewer

Regards
Richard Schoen
________________________________

**Comment by richardschoen** [comment]
Also it seems the stat command will provide what you need for file properties.
