### ISSUE TITLE
Ability to read/write IFS files in other CCSIDs

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#481]
E.g. if a file is in 37, be able to read/write in it

**Comment by worksofliam** [comment]
Can use `/usr/bin/attr` to find the CCSID.

**Comment by worksofliam** [comment]
Next step is to try and determine the easiest way to convert one CCSID to another. Likely iconv.

**Comment by worksofliam** [comment]
`iconv -f xx -t 1208 /path/to/myfile.txt > /path/to/yourfile.txt `

**Comment by priceaj** [comment]
> Next step is to try and determine the easiest way to convert one CCSID to another. Likely iconv.

I normally use dd 

`dd if=input_filename of=output_filename conv=ascii`

**Comment by worksofliam** [comment]
Fun. I wasn't aware of `dd`.. let's see how it goes with `iconv`, then I might try that if there are any issues.

Feel free to give the test PR a go.
