### ISSUE TITLE
When opening a source "object" filter i get error message now.

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#494]
I get this error now.
![image](https://user-images.githubusercontent.com/1353665/152050595-1dc8dc8e-ee82-431d-8d35-22e8c07ef41e.png)

I have been playing around with the settings.  I added a filter for QSYSOPR *MSGQ and tried to expand it.  After this when I started getting the error message.  I have removed all object filters and re-created the one for source and I still get this error. 

What did I do wrong?

Thanks, Matt

**Comment by worksofliam** [comment]
@m-tyler Can you share the Code for IBM i result in the Output panel after you try to open it?

![image](https://user-images.githubusercontent.com/3708366/152051510-7d3453e1-e37e-4135-a09e-05d7d372f05a.png)

**Comment by m-tyler** [comment]
.: pwd
{
    "code": null,
    "signal": null,
    "stdout": "/home/PGMT",
    "stderr": ""
}

/home/PGMT: pwd
{
    "code": null,
    "signal": null,
    "stdout": "/home/PGMT",
    "stderr": ""
}

/home/PGMT: echo "liblist" | /QOpenSys/usr/bin/qsh
{
    "code": null,
    "signal": null,
    "stdout": "RBTSYSLIB   SYS\nWFIQSYS     SYS\nQSYS        SYS\nQSYS2       SYS\nQHLPSYS     SYS\nQUSRSYS     SYS\nQSHELL      PRD\nPGMT        CUR\nWIASPUSR    USR\nWSBUSR      USR\nWSBINTG     USR\nWSBQUAL     USR\nWSBDTA      USR\nWSBOBJ      USR\nWSBSRC      USR\nDEVQUAL     USR\nDEVDTA      USR\nDEVOBJ      USR\nDTSINTG92   USR\nDTSINTG     USR\nDTSQUAL92   USR\nDTSQUAL     USR\nDTSUSER     USR\nDTSCNTRL    USR\nDTSDCDTA    USR\nDTSINFORM   USR\nWFIINTG     USR\nWFIQUAL     USR\nWFIDTA      USR\nWFINEP      USR\nWFIHST      USR\nWFIOBJ      USR\nTAATOOL     USR\nSPLTOOL     USR\nAFPTOOL     USR\nACMSLIB     USR\nWAEDTA      USR\nWAEOBJ      USR\nWFISRC      USR\nHAWKEYE     USR\nQGPL        USR\nQTEMP       USR",
    "stderr": ""
}

/home/PGMT: system "CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF2111: Library ILEDITOR already exists."
}

/home/PGMT: system "CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)"
{
    "code": null,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/PGMT: system "CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)"
{
    "code": null,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/PGMT: ls -p /QOpenSys/pkgs/bin/
{
    "code": null,
    "signal": null,
    "stdout": "2to3\n2to3-3.6\nR\nRscript\n[\naddbuiltin\nalternatives\nansible\nansible-config\nansible-connection\nansible-console\nansible-doc\nansible-galaxy\nansible-inventory\nansible-playbook\nansible-pull\nansible-test\nansible-vault\natob\nawk\nbaddbdir\nbase32\nbase64\nbasename\nbash\nbashbug\nbltest\nbtoa\nbunzip2\nbzcat\nbzcmp\nbzdiff\nbzegrep\nbzfgrep\nbzgrep\nbzip2\nbzip2recover\nbzless\nbzmore\nc2ph\ncat\ncertcgi\ncertutil\nchcon\nchgrp\nchktest\nchmod\nchown\nchroot\nchroot_setup\ncksum\ncmsutil\ncomm\nconflict\ncorelist\ncp\ncpan\ncpp-6\ncpp-6.bin\ncrlutil\ncrmftest\ncsplit\ncurl\ncurl-config\ncut\ncwbmedic\ncwbping\ncwbtrc\ndate\ndb2util\ndb_archive\ndb_checkpoint\ndb_deadlock\ndb_dump\ndb_hotbackup\ndb_load\ndb_printlog\ndb_recover\ndb_sql\ndb_stat\ndb_upgrade\ndb_verify\ndbtest\ndd\nderdump\ndertimetest\ndf\ndigest\ndir\ndircolors\ndirname\ndltest\ndu\neasy_install-3.6\necho\necperf\negrep\nenc2xs\nencguess\nencodeinttest\nenv\nex\nexample\nexpand\nexpr\nfactor\nfalse\nfbectest\nfgrep\nfind\nfipstest\nflask\nfmt\nfold\nfunzip\ngawk\ngcc-6\ngcc-6.bin\ngcc-ar-6\ngcc-ar-6.bin\ngcc-nm-6\ngcc-nm-6.bin\ngcc-ranlib-6\ngcc-ranlib-6.bin\ngcov-6\ngit\ngit-cvsserver\ngit-receive-pack\ngit-shell\ngit-upload-archive\ngit-upload-pack\ngmake\ngrep\ngroups\ngunzip\ngzexe\ngzip\nh2ph\nh2xs\nhead\nhostid\nhttpserv\nid\nidle3\nidle3.6\nigawk\ninstall\ninstmodsh\nisql\niusql\njoin\njson_pp\nkill\nless\nlessecho\nlesskey\nlibnetcfg\nlibtool\nlibtoolize\nlink\nlistsuites\nln\nlocate\nlogname\nls\nmake\nmakepqg\nmangle\nmd5sum\nminigzip\nmkdir\nmkfifo\nmknod\nmktemp\nmodutil\nmultinit\nmv\nnice\nnl\nnode\nnodever\nnohup\nnonspr10\nnpm\nnproc\nnpx\nnumfmt\nocspclnt\nocspresp\nod\nodbc_config\nodbcinst\noidcalc\np7content\np7env\np7sign\np7verify\npaste\npathchk\nperl\nperl5.24.1\nperlbug\nperldoc\nperlivp\nperlthanks\npiconv\npinky\npip3\npip3.6\npk11ectest\npk11gcmtest\npk11mode\npk12util\npk1sign\npkix-errcodes\npl2pm\npod2html\npod2man\npod2text\npod2usage\npodchecker\npodselect\npp\npr\nprintenv\nprintf\nprove\npstruct\nptar\nptardiff\nptargrep\nptx\npwd\npwdecrypt\npydoc\npydoc3\npydoc3.6\npython\npython2\npython2.7\npython3\npython3.6\npython3.6m\npyvenv\npyvenv-3.6\nreadlink\nrealpath\nremtest\nrm\nrmdir\nrpm\nrpm2archive\nrpm2cpio\nrpmdb\nrpmgraph\nrpmkeys\nrpmquery\nrpmsign\nrpmverify\nrsaperf\nruncon\nrview\nrvim\nsdrtest\nsecmodtest\nselfserv\nseq\nsha1sum\nsha224sum\nsha256sum\nsha384sum\nsha512sum\nshasum\nshlibsign\nshred\nshuf\nsigntool\nsignver\nsleep\nslencheck\nsmtpd.py\nsort\nsplain\nsplit\nssltap\nstat\nstdbuf\nstrsclnt\nstty\nsum\nsymkeyutil\nsync\ntac\ntail\ntar\ntee\ntest\ntimeout\ntouch\ntr\ntrue\ntruncate\ntsort\ntstclnt\ntty\nuname\nuncompress\nunexpand\nuniq\nunlink\nunzip\nunzipsfx\nupdate-alternatives\nupdatedb\nuptime\nurlgrabber\nusers\nvdir\nvfychain\nvfyserv\nview\nvim\nvimdiff\nvimtutor\nwc\nwget\nwheel\nwho\nwhoami\nxargs\nxmlservice-cli\nxsubpp\nxxd\nyes\nyum\nzcat\nzcmp\nzdiff\nzegrep\nzfgrep\nzforce\nzgrep\nzip\nzipcloak\nzipdetails\nzipgrep\nzipinfo\nzipnote\nzipsplit\nzless\nzmore\nznew",
    "stderr": ""
}

/home/PGMT: ls -p /usr/bin/
{
    "code": null,
    "signal": null,
    "stdout": "Rfile\najar\najar.prv\nappletviewer\napt\narmsrv\narmsrvconv\nattr\nbasename\nbash\nbash2\nbash2bug\nbashbug\nbunzip2\nbzcat\nbzcmp\nbzdiff\nbzegrep\nbzfgrep\nbzgrep\nbzip2\nbzip2recover\nbzless\nbzmore\nc++\ncat\ncatsplf\nchgrp\nchmod\nchown\nclrtmp\ncmp\ncompress\ncp\ncpp\ncurl\ncut\ndataq\ndatarea\ndate\ndb2\ndb2profc\ndb2profc_trace\ndb2profp\nddns-confgen\ndelv\ndfmadmin\ndhcpd\ndhcrelay\ndig\ndirname\ndnssec-dsfromkey\ndnssec-importkey\ndnssec-keyfromlabel\ndnssec-keygen\ndnssec-revoke\ndnssec-settime\ndnssec-signzone\ndnssec-verify\ndspmsg\necho\negrep\nenv\nenvsubst\nexpr\nextcheck\nfc-cache\nfc-cache_64\nfc-cat\nfc-cat_64\nfc-list\nfc-list_64\nfc-match\nfc-match_64\nfc-query\nfc-query_64\nfc-scan\nfc-scan_64\nfgrep\nfile\nfind\nfunzip\ng++\ngcc\ngcov\ngencat\ngetjobid\ngettext\ngettext.sh\ngettextize\ngfortran\ngit\ngit-receive-pack\ngit-shell\ngit-upload-archive\ngit-upload-pack\ngitk\ngrep\ngrunt\ngrunt-init\ngtar\ngunzip\ngzexe\ngzip\nhead\nhost\nhostname\nhttpapi\nhwkeytool\niconv\nid\nidlj\nidn\nikeyman\ninfo\ninfokey\nipcrm\nipcs\nixlc\nixlci\njar\njarsigner\njava\njavac\njavadoc\njavah\njavap\njconsole\njdb\njdmpview\njextract\njshint\njson5\nkdestroy\nkeytab\nkeytool\nkinit\nklist\nkpasswd\nksetup\nldapadd\nldapchangepwd\nldapcompare\nldapdelete\nldapdiff\nldapexop\nldapmodify\nldapmodrdn\nldapsearch\nless\nlessecho\nlesskey\nlesspipe.sh\nln\nlocale\nlogger\nlogname\nls\nmakeinfo\nmawk\nmkdir\nmkfifo\nmsgattrib\nmsgcat\nmsgcmp\nmsgcomm\nmsgconv\nmsgen\nmsgexec\nmsgfilter\nmsgfmt\nmsggrep\nmsginit\nmsgmerge\nmsgunfmt\nmsguniq\nmv\nnamed\nnamed-checkconf\nnamed-checkzone\nnamed-compilezone\nnamed-journalprint\nnamed-rrchecker\nnative2ascii\nngettext\nnode\nnohup\nnpm\nnslookup\nnsupdate\nod\norbd\npack200\npax\npcregrep\npcretest\npdftexi2dvi\npkg-config\npkg-config_64\npolicytool\npowerpc-ibm-aix5.1.0.0-pkg-config\npowerpc-ibm-aix6.1.0.0-c++\npowerpc-ibm-aix6.1.0.0-g++\npowerpc-ibm-aix6.1.0.0-gcc\npowerpc-ibm-aix6.1.0.0-gcc-4.7.2\npowerpc-ibm-aix6.1.0.0-gcc-ar\npowerpc-ibm-aix6.1.0.0-gcc-nm\npowerpc-ibm-aix6.1.0.0-gcc-ranlib\npowerpc-ibm-aix6.1.0.0-gfortran\npr\nprintenv\nprofconv\nprofdb\nprofp\nps\npwd\npwdx\npydoc\npydoc_64\npython\npython-config\npython2.6\npython2.6-config\npython2.6_64\npython2.6_64-config\npython_64\npython_64-config\nqsh\nr.js\nrecode-sr-latin\nrexec\nrexx\nrm\nrmdir\nrmic\nrmid\nrmiregistry\nrndc\nrndc-confgen\nrpm\nrsync\nschemagen\nscreen\nscreen-4.0.3\nsed\nserialver\nservertool\nsetccsid\nsh\nshar\nshjs\nsort\nsplit\nsqlite3\nsqlj\nstrEKM\nsudo\nsudoedit\nsudoreplay\nsvn\nsvnadmin\nsvndumpfilter\nsvnlook\nsvnrdump\nsvnserve\nsvnsync\nsvnversion\nsystem\nsysval\ntail\ntar\ntclsh\ntclsh8.5\ntclsh8.5_64\ntclsh_64\ntcsh\ntee\ntest\ntexi2dvi\ntexi2pdf\ntexindex\ntnameserv\ntouch\ntr\ntsig-keygen\nuname\nuncompress\nuniq\nunpack200\nunshar\nunzip\nunzipsfx\nwc\nwget\nwish\nwish8.5\nwish8.5_64\nwish_64\nwsgen\nwsimport\nxargs\nxgettext\nxjc\nxmlwf\nzcat\nzcmp\nzdiff\nzegrep\nzfgrep\nzforce\nzgrep\nzip\nzipcloak\nzipgrep\nzipinfo\nzipnote\nzipsplit\nzless\nzmore\nznew\nzsh",
    "stderr": ""
}

/home/PGMT: ls -p /QSYS.lib/ILEDITOR.lib/
{
    "code": null,
    "signal": null,
    "stdout": "GENCMDXML.PGM\nO81GVMDCZX.FILE/\nO8GGILUDNW.FILE/\nOBZV6K84CW.FILE/\nODGKJ2B8WT.FILE/\nODHTVCPNV9.FILE/\nOEJOXY1CIN.FILE/\nOFKI7XJTCQ.FILE/\nOHSX9IQVTW.FILE/\nOIDKNR5LBS.FILE/\nOL6IZVOWKP.FILE/\nOLPF6YXI0H.FILE/\nOM7QO8LRYB.FILE/\nOMXKLXLDVB.FILE/\nORUEO3HFNJ.FILE/\nOTTSEMYJXV.FILE/\nOWAKYPMVK3.FILE/\nOWSYIA8MCY.FILE/\nOX6BLIHQY7.FILE/\nPGMT_00001.FILE\nPGMT_00002.FILE\nPGMT_00003.FILE\nPGMT_00004.FILE\nPGMT_00005.FILE\nPGMT_00006.FILE\nPGMT_00007.FILE\nPGMT_00008.FILE\nQTOOLS.FILE/",
    "stderr": ""
}

/home/PGMT: DB2UTIL_JSON_CONTAINER=array /QOpenSys/pkgs/bin/db2util -o json "SELECT * FROM QSYS2.ASP_INFO"
{
    "code": null,
    "signal": null,
    "stdout": "[\n{\"DEVICE_DESCRIPTION_NAME\":\"null\",\"ASP_NUMBER\":1,\"ASP_STATE\":\"NONE\",\"ASP_TYPE\":\"SYSTEM\",\"RDB_NAME\":\"BOISE03\",\"NUMBER_OF_DISK_UNITS\":39,\"DISK_UNITS_PRESENT\":\"ALL\",\"TOTAL_CAPACITY\":2977844,\"TOTAL_CAPACITY_AVAILABLE\":1563558,\"PROTECTED_CAPACITY\":0,\"PROTECTED_CAPACITY_AVAILABLE\":0,\"UNPROTECTED_CAPACITY\":2977844,\"UNPROTECTED_CAPACITY_AVAILABLE\":1563558,\"SYSTEM_STORAGE\":508,\"OVERFLOW_STORAGE\":0,\"STORAGE_THRESHOLD_PERCENTAGE\":90,\"OVERFLOW_RECOVERY_RESULT\":\"SUCCESS\",\"ERROR_LOG_SPACE\":36,\"MACHINE_LOG_SPACE\":189,\"MACHINE_TRACE_SPACE\":1,\"MAIN_STORAGE_DUMP_SPACE\":1078,\"MICROCODE_SPACE\":6205,\"END_IMMEDIATE\":\"NO\",\"COMPRESSION_RECOVERY_POLICY\":\"OVERFLOW DELAY\",\"COMPRESSED_DISK_UNITS\":\"NONE\",\"CHANGES_WRITTEN_TO_DISK\":\"YES\",\"MULTIPLE_CONNECTION_DISK_UNITS\":\"NO\",\"BALANCE_STATUS\":\"COMPLETE\",\"BALANCE_TYPE\":\"NONE\",\"BALANCE_DATA_MOVED\":null,\"BALANCE_DATA_REMAINING\":null,\"BALANCE_TIMESTAMP\":\"null\",\"TRACE_STATUS\":\"NONE\",\"TRACE_DURATION\":null,\"TRACE_TIMESTAMP\":\"null\",\"RESOURCE_NAME\":\"null\",\"PRIMARY_ASP_RESOURCE_NAME\":\"null\"},\n{\"DEVICE_DESCRIPTION_NAME\":\"WIASP\",\"ASP_NUMBER\":33,\"ASP_STATE\":\"AVAILABLE\",\"ASP_TYPE\":\"PRIMARY\",\"RDB_NAME\":\"WIASP\",\"NUMBER_OF_DISK_UNITS\":120,\"DISK_UNITS_PRESENT\":\"ALL\",\"TOTAL_CAPACITY\":9372574,\"TOTAL_CAPACITY_AVAILABLE\":1870815,\"PROTECTED_CAPACITY\":0,\"PROTECTED_CAPACITY_AVAILABLE\":0,\"UNPROTECTED_CAPACITY\":9372574,\"UNPROTECTED_CAPACITY_AVAILABLE\":1870815,\"SYSTEM_STORAGE\":593,\"OVERFLOW_STORAGE\":null,\"STORAGE_THRESHOLD_PERCENTAGE\":90,\"OVERFLOW_RECOVERY_RESULT\":\"null\",\"ERROR_LOG_SPACE\":null,\"MACHINE_LOG_SPACE\":null,\"MACHINE_TRACE_SPACE\":null,\"MAIN_STORAGE_DUMP_SPACE\":null,\"MICROCODE_SPACE\":126,\"END_IMMEDIATE\":\"null\",\"COMPRESSION_RECOVERY_POLICY\":\"OVERFLOW IMMEDIATE\",\"COMPRESSED_DISK_UNITS\":\"NONE\",\"CHANGES_WRITTEN_TO_DISK\":\"YES\",\"MULTIPLE_CONNECTION_DISK_UNITS\":\"NO\",\"BALANCE_STATUS\":\"COMPLETE\",\"BALANCE_TYPE\":\"CAPACITY BALANCING\",\"BALANCE_DATA_MOVED\":null,\"BALANCE_DATA_REMAINING\":null,\"BALANCE_TIMESTAMP\":\"2022-02-01-13.00.00\",\"TRACE_STATUS\":\"NONE\",\"TRACE_DURATION\":null,\"TRACE_TIMESTAMP\":\"null\",\"RESOURCE_NAME\":\"WIASP\",\"PRIMARY_ASP_RESOURCE_NAME\":\"null\"}\n]",
    "stderr": ""
}

/home/PGMT: system "DSPOBJD OBJ(PGMT/Q*) OBJTYPE(*ALL) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/o0JkVo9Pga)"
{
    "code": null,
    "signal": null,
    "stdout": "CPF9861: Output file O0JKVO9PGA created in library ILEDITOR.\nCPF9862: Member O0JKVO9PGA added to output file O0JKVO9PGA in library ILEDITOR.",
    "stderr": ""
}

/home/PGMT: system "QSYS/CPYTOIMPF FROMFILE(ILEDITOR/o0JkVo9Pga o0JkVo9Pga) TOSTMF('/tmp/vscodetemp-onx43Xioma') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD) "
{
    "code": null,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/PGMT: /usr/bin/attr "/tmp/vscodetemp-onx43Xioma" CCSID
{
    "code": null,
    "signal": null,
    "stdout": "37",
    "stderr": ""
}

/home/PGMT: /usr/bin/iconv -f IBM-037 -t UTF-8 "/tmp/vscodetemp-onx43Xioma" > /tmp/vscodetemp-oSJlKeIPXT
{
    "code": null,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

.: rm -f /tmp/vscodetemp-onx43Xioma
{
    "code": null,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

**Comment by worksofliam** [comment]
@m-tyler Can you also share your VS Code `settings.json` with me?

![image](https://user-images.githubusercontent.com/3708366/152052466-bda80042-4e8e-4271-9847-a936785cc5ae.png)

**Comment by worksofliam** [comment]
Notes: I can see the `CPYTOIMPF` file is copying to 37 instead of 1208. This is due to that bad data area. The user has already opened #493 to try and let them get around this issue. We can see that from these log entries.

```
/home/PGMT: system "QSYS/CPYTOIMPF FROMFILE(ILEDITOR/o0JkVo9Pga o0JkVo9Pga) TOSTMF('/tmp/vscodetemp-onx43Xioma') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD) "
{
"code": null,
"signal": null,
"stdout": "",
"stderr": ""
}

/home/PGMT: /usr/bin/attr "/tmp/vscodetemp-onx43Xioma" CCSID
{
"code": null,
"signal": null,
"stdout": "37",
"stderr": ""
}

/home/PGMT: /usr/bin/iconv -f IBM-037 -t UTF-8 "/tmp/vscodetemp-onx43Xioma" > /tmp/vscodetemp-oSJlKeIPXT
{
"code": null,
"signal": null,
"stdout": "",
"stderr": ""
}
```

**Comment by m-tyler** [comment]
[settings.json.txt](https://github.com/halcyon-tech/vscode-ibmi/files/7981994/settings.json.txt)

**Comment by m-tyler** [comment]
Seems odd that I was able to open source.  
![image](https://user-images.githubusercontent.com/1353665/152053869-85a04f42-4690-49af-bb64-646c68eeca09.png)

**Comment by worksofliam** [comment]
@m-tyler This potentially has something to do with the other issue you raised.

I see `sqlExecutor` is also none. I would be happy to get on a Zoom with you to look into this issue as that seems like the next best step.

Feel free to reach out to me on LinkedIn and we can set it up.

https://www.linkedin.com/in/worksofbarry/

**Comment by m-tyler** [comment]
I did have `sqlExecutor` set to db2 before based on another thread about not being able to run SQL statements against the IBM database.   I turned it to none later. 

Let me try a few more things.  I have just started using this extension and exploring into VSC as an alternative to RDi.   I can just "clean up" my installation and start over. 

If I end up with the same results I will contact you back. 

Thanks, Matt

**Comment by worksofliam** [comment]
@m-tyler That makes sense actually. Setting it to `none` will try and use `CPYTOIMPF`, and based on #493 that likely will be an issue for you - using SQL to fetch the members should work like it did before.

**Comment by m-tyler** [comment]
Okay, I have reverted back to using DB2 for `sqlExecutor` setting. Case closed!

Thanks, Matt

**Comment by worksofliam** [comment]
@m-tyler awesome - thanks bud!
