### ISSUE TITLE
Tool does not take into account IFS file names with blanks imbedded. 

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#496]
**Describe the bug**
I got error "Action Set CCSID to 1252 for [file name] was not successful. 

**To Reproduce**
I opened my IFS home folder in the IFS filter, Right clicked on a .SQL file with a space in the name, choose Run Actions (Ctrl+E).  

**Screenshots**
![image](https://user-images.githubusercontent.com/1353665/152056474-87c412c8-21e0-44a7-bfb3-57134cfa1923.png)
![image](https://user-images.githubusercontent.com/1353665/152056446-a057705f-389d-494c-8be6-2e6765416e7b.png)
![image](https://user-images.githubusercontent.com/1353665/152056564-05a162d7-37e5-4904-9a31-e3c30759f180.png)

**OUTPUT** 
/home/PGMT: setccsid 1252 /home/PGMT/SQL_Scripts/Analyze PCR.sql
{
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "setccsid: 001-2113 Error found getting information for object /home/PGMT/SQL_Scripts/Analyze. No such path or directory.\nsetccsid: 001-2113 Error found getting information for object PCR.sql. No such path or directory."
}

/home/PGMT: /usr/bin/attr "/home/PGMT/SQL_Scripts/Analyze PCR.sql" CCSID
{
    "code": null,
    "signal": null,
    "stdout": "1208",
    "stderr": ""
}

/home/PGMT: /usr/bin/attr "/home/PGMT/SQL_Scripts/Analyze PCR.sql" CCSID
{
    "code": null,
    "signal": null,
    "stdout": "1208",
    "stderr": ""
}

/home/PGMT: /usr/bin/attr "/home/PGMT/SQL_Scripts/Analyze PCR.sql" CCSID
{
    "code": null,
    "signal": null,
    "stdout": "1208",
    "stderr": ""
}

/home/PGMT: /usr/bin/attr "/home/PGMT/SQL_Scripts/Analyze PCR.sql" CCSID
{
    "code": null,
    "signal": null,
    "stdout": "1208",
    "stderr": ""
}

**Environment (please complete the following information):**
 - Extension version [e.g. 0.8.27]
 - IBM i OS version 7.3

**Comment by worksofliam** [comment]
@m-tyler Not a bug per se.. you can change the action and add the double quotes around the path. PR is welcome too
