### ISSUE TITLE
Ctrl  + Shift + Escape on Windows 10

### ISSUE THREAD

**Issue by SJLennon** [halcyon-tech/vscode-ibmi#499]
Used F1 to disconnected today and noticed there is a shortcut that I don't recall seeing before:
![image](https://user-images.githubusercontent.com/67484051/152183467-bedfa8af-11f9-4e3a-88d6-b37703ee6a0e.png)
However, on Windows 10 instead of disconnecting the shortcut always brings up the Task Manager.  

Question: Is this working as intended in the extension?

Opening Task Manager is standard operation across all recent versions of Windows.
https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec#WindowsVersion=Windows_10.  See the first section.

**Comment by worksofliam** [comment]
Oh fun! I likely didn't know this because I don't use Windows. We should probably change the shortcut.

Any suggestions @SJLennon?

**Comment by SJLennon** [comment]
Let me troll around.  I personally don't use that many shortcuts--can't remember them.

**Comment by SJLennon** [comment]
Ctrl + Alt combinations don't seem to be used a lot in VS Code or Windows.  **So perhaps Ctrl + Alt + D?** 
 But how would this play on the Mac or Linux?

(Actually, I have mapped Ctrl + Alt + U and Ctrl + Alt +L) to upper and lowercase the selection in VS Code, so I do use a few odd shortcut keys.)

**Comment by SJLennon** [comment]
Uh Oh!  On Ubuntu `CTRL + Alt + D` is taken.  It minimizes all windows. (Running in in a VMWare VM in my case.)

Maybe instead either:
```
    Ctrl + Alt + X   (eXit connection)
    Ctrl + Alt + Q   (Quit connection)
```
Honestly not a major issue for me.
@worksofliam

**Comment by worksofliam** [comment]
@SJLennon Good spot! I will see if they have any meaning on my mac.. also, we could always remove the default shortcut and just let the user figure it out like as did you.

**Comment by SJLennon** [comment]
> @SJLennon Good spot! I will see if they have any meaning on my mac.. also, we could always remove the default shortcut and just let the user figure it out like as did you.

Works for me.  I don't disconnect very often and probably most people don't.
And you can change the key binding for IBM i Disconnect. I just changed disconnect to Ctrl + Alt + D and it works nicely.
![image](https://user-images.githubusercontent.com/67484051/152434212-db3032e4-3f06-41fa-8674-a5912aa2f1a8.png)
@worksofliam
