### ISSUE TITLE
control block matching seems to find wrong block head or tail.

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#502]
Notice the IF and ENDIF lines outlined.  The IF that is highlighted is not the if for the ENDIF highlighted. 
![image](https://user-images.githubusercontent.com/1353665/152406687-d89fb2bf-91d4-4919-ac2b-e80753c289b6.png)

**Comment by worksofliam** [comment]
I believe this is part of ibmi-languages, not vscode-ibmi.

**Comment by m-tyler** [comment]
Ctrl+Shift+\ matches the wrong ENDIF.

Ctrl+Shift+[ folds the correct control block. 

If I comment out the `exe sql` code the block marking works
