### ISSUE TITLE
Ability to open sources as read only

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#503]
**Is your feature request related to a problem? Please describe.**
> I need to browse source from a master branch (production source library) and I need to ensure I don't accidentally modify this source and push these changes back. 

**Describe the solution you'd like**
> I don't see a way to make a certain member source open in VS CODE as read-only.   Some programmers have limited authority to production source but I have full authority to source.    

**Describe alternatives you've considered**
> I have looked at the autosave option and turned them off but I think there is still a real issue.

**Comment by worksofliam** [comment]
I've wanted this for a while, but there is a blocker.

https://github.com/microsoft/vscode/issues/4873

**Comment by n0pinion** [comment]
Hi,

Our product is managed via ARCAD source control, so only the *current* version library is writable in seu.
To achieve this security in vscode I added this piece of code in writeFile (complex.js)

current_lib **is an alias, not the real name**
user_lib **idem**

```diff
writeFile(uri, content, options) {
    const path = uri.path.split(`/`);
    let asp, lib, file, fullName;

    if (path.length === 4) {
      lib = path[1];
      file = path[2];
      fullName = path[3];
    } else {
      asp = path[1];
      lib = path[2];
      file = path[3];
      fullName = path[4];
    }
+    if (lib !== `current_lib` && lib !== `user_lib`){
+     throw new Error(lib + ` is write protected.\nCurrent version actuelle: current_lib`);
   }
```

It's candid but does the job of preserving source from unwanted modification.

Adding a *settings.json hosted* list of write enabled libraries would be a plus.

Have a nice day.

**Comment by m-tyler** [comment]
This has turned into a _**LOW PTY**_ issue for me as our company has finally wised up and removed *ALLOBJ from my user so I will not be able to modify source outside of our change management tool.

**Comment by SJLennon** [comment]
FWIW: In my last job we set up developers with two ids.  The one for development was the one that we routinely used 99% of the time.  It had read only authority to production objects, so we could look at production source and data for research or support issues.  The one with authority to production data was essentially *ALLOBJ, but if we used it then the usage was logged, data changes were reported from the journals and the IT manager and Programming Manager had to sign off on it next morning.  This was an auditor requirement.  

Essentially, the developers were trusted and allowed to fix production issues, but were prevented from making malicious or accidental changes.  We used Aldon for source control and deployment.  It worked pretty well.  Though it could also work without a commercial source control system, by not routinely giving developers update ability to production data or source. 

Yes, unfortunately there will be some diehards who insist that developers need *ALLOBJ and thus need protection against them selves, but I don't see it.  Use the provided OS facilities.

**Comment by m-tyler** [comment]
Luckily, we don't have those diehards in-house.  I like the idea of a dual profile, the main profile without *ALLOBJ and one that has *ALLOBJ but is always disabled, even if it meant I had to ask for it to be activated by the helpdesk.  I doubt the dual profile set will take traction because it means someone has to manage.

**Comment by m-tyler** [comment]
What do you tihnk about using **workbench.editor.decorations.badges** [https://code.visualstudio.com/updates/v1_53#_tab-decorations](url) and view OBJECT_PRIVLEGES or UDTF OBJECT_PRIVLEGES(), to add a decoration indicating edit capable mode or read-only mode?
