### ISSUE TITLE
Library list and database schema list editable as a string

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#504]
**Is your feature request related to a problem? Please describe.**
> When I want to add new connection profiles and have different library lists maintaining the list is cumbersome via the current UI.  

**Describe the solution you'd like**
> Add a right-click option to open an inline input or an action to open the settings .JSON document.  I would like to be able to just apply a *JOBD to the connection to get the *LIBL, etc. applied but I don't know how complicated this would be to develop.  

**Describe alternatives you've considered**
> I like the ability to quickly create JDBC config settings with new libraries in ACS RunSQL Scripts plugin.  It gives you an input form that has an open area for typing in libraries.  
> 
> ![image](https://user-images.githubusercontent.com/1353665/152567565-ff40bca9-af33-4105-963f-3a21d5b08647.png)

**Comment by worksofliam** [comment]
After looking into this some more, my proposed way is the way I am going to do it!

**Comment by worksofliam** [comment]
Library list is now editable as a string.
