### ISSUE TITLE
Database Browser to use the *LIBL of the connection

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#505]
**Is your feature request related to a problem? Please describe.**
> I see that the *LIBL defaults at creation to the connection information but it remains static from that point on.   If I want to add libraries to a new connection to develop for a different setup, I have to add the libraries to both locations.  Not really that big of a deal for the first couple but gets tedious if you have to create several connections.

**Describe the solution you'd like**
> Consider an option to have it link to the *LIBL of the connection until the user adds a library to the Database Browser list that is not in the connection *LIBL.

**Comment by worksofliam** [comment]
A cool idea. I will look into it and if it's simple enough I will make the change.

I am avoiding large changes to the database browser and I'd rather spend more time on the future db2i extension which will replace this extension.

https://github.com/halcyon-tech/vscode-db2i

**Comment by m-tyler** [comment]
I am fine with this direction.

**Comment by worksofliam** [comment]
Decided against this change as I am hoping to move the database browser out of the extension sooner than later.
