### ISSUE TITLE
Line is truncated when it is not modified

### ISSUE THREAD

**Issue by mattlavinder** [halcyon-tech/vscode-ibmi#512]
**Describe the bug**
Having an issue with a line of code getting truncated when saving. The setting to maintain source date is enabled.

**To Reproduce**
Here is the code I am saving:

```
               if TskOpnDs.MEMBER <> gMbrName;
                   wrtJobDbg(*ON);
                   wrtDebug(pgmname+': Opened member ' + TskOpnDs.MEMBER + '.+
                             Expected member ' + gMbrName + '.':*ON);
                   dump;
                   *inlr = *on;
                   return;
               endif;
```
- When I save and I have NOT modified the wrtDebug line, it seems to truncate the `.+` off the end of the line
- When I save and I HAVE modified the wrtDebug line (to put them back), it does NOT truncate the line

**Expected behavior**
I would expect these two lines to left, regardless of whether the line was modified or not.

**Environment (please complete the following information):**
 - Extension version v0.8.30
 - IBM i OS version 7.4

**Comment by worksofliam** [comment]
@mattlavinder What is the record length of the source file you're working with?

Thanks!

**Comment by worksofliam** [comment]
I will be looking into this today.

**Comment by worksofliam** [comment]
@mattlavinder Think I've tracked it down. Fix will be coming out this evening.

**Comment by worksofliam** [comment]
@mattlavinder 0.8.31 just released. Will you give that release a whirl and try it out? Thanks!

**Comment by mattlavinder** [comment]
@worksofliam Looks good to me.  Thanks!
