### ISSUE TITLE
Error when I tried to use SQL

### ISSUE THREAD

**Issue by hn000246** [halcyon-tech/vscode-ibmi#513]
Hello guys I'm trying to read a table but I got this error message: "There's no way to run SQL statmentson this system. Set SQL executor.
I was reading finding that i need to intall db2util but I don´t know how.
There's a way to learn how to doit to make possible the SQL ?

Best Regards,
![sql](https://user-images.githubusercontent.com/50391179/152878613-ff01536c-e1cf-40ea-a73a-f48d2e59dcae.jpg)

**Comment by worksofliam** [comment]
Db2util can be installed through yum. 

https://ibmi-oss-docs.readthedocs.io/en/latest/yum/README.html

**Comment by hn000246** [comment]
I really appreciate your help @worksofliam Thanks!!
