### ISSUE TITLE
Source member list no longer working

### ISSUE THREAD

**Issue by fathert** [halcyon-tech/vscode-ibmi#515]
**Issue**
No source members appear in the object browser window when a source file is expanded:
![image](https://user-images.githubusercontent.com/8808151/152961180-cd113aae-b0ff-4087-be33-8b3a7bc21380.png)

The following error appears in the log "Conversion between CCSID 1200 and CCSID 65535 invalid" (translated from the German below)
```
/home/PGMR85: echo "/usr/bin/db2 \"
        SELECT
          (b.avgrowsize - 12) as MBMXRL,
          a.iasp_number as MBASP,
          a.table_name AS MBFILE,
          b.system_table_member as MBNAME,
          b.source_type as MBSEU2,
          b.partition_text as MBMTXT
        FROM qsys2.systables AS a
          JOIN qsys2.syspartitionstat AS b
            ON b.table_schema = a.table_schema AND
              b.table_name = a.table_name
        WHERE
          a.table_schema = 'GENSRCQ' 
          AND a.table_name = 'QSPLSRC'
          
        ORDER BY
          b.system_table_member
      \"" | /QOpenSys/usr/bin/qsh
{
    "code": null,
    "signal": null,
    "stdout": "MBMXRL               MBASP  MBFILE                                                                                                                           MBNAME     MBSEU2     MBMTXT                                            \n-------------------- ------ -------------------------------------------------------------------------------------------------------------------------------- ---------- ---------- --------------------------------------------------\n\n **** CLI ERROR *****\n         SQLSTATE: 57017\nNATIVE ERROR CODE: -332\nZeichenumsetzung zwischen CCSID 1200 und CCSID 65535 ung�ltig. \n\n  0 RECORD(S) SELECTED.",
    "stderr": ""
}
```

**To Reproduce**
Steps to reproduce the behaviour:
I assume this happens on machines where the default CCSID is 65535 but I'm not able to test this as I have no control over the default or user profile CCSID I have.

**Expected behavior**
The list of source members should be displayed under the source file.

**Screenshots**

**Environment (please complete the following information):**
 - Extension version 0.8.31
 - IBM i OS version 7.2

**Additional context**
Possible related to this change?
https://github.com/halcyon-tech/vscode-ibmi/compare/0.8.28...0.8.29#diff-c2fa9480f688a296d5a8238369275d0f87fd8933eccbc1450eeedf42bd2b18b1

**Comment by worksofliam** [comment]
@fathert what is your SQL executor set to in the connection settings? I've never seen this error from the member list before!

**Comment by rustyperry1962** [comment]
I was having the same issue. Changing the SQL executor to None fixed it. Thanks for the suggestion worksofliam!

And thanks for the work on this extension. 30+ year IBMi developer and I love it.

**Comment by worksofliam** [comment]
@rustyperry1962 Do you also have QCCSID 65535? Maybe I should set it to none by default if that's the case.

**Comment by fathert** [comment]
Ah yes, that fixes it!

**Comment by worksofliam** [comment]
Cool - we can close this for now. Next step is to automate turned it to 'None' if the CCSID is 65535.
