### ISSUE TITLE
Features Request for Search Source File

### ISSUE THREAD

**Issue by thebeardedgeek** [halcyon-tech/vscode-ibmi#524]
When I go to search a source file I would like the ability to search for these two items; similar to PDM search.

1. Case sensitivity

2. Position of the text

Also, I would like the ability to:

- Open a member from results of the search

**Comment by worksofliam** [comment]
The other two might be possible with regex, but

> Open a member from results of the search

already exists.

**Comment by worksofliam** [comment]
Related to #165

**Comment by SJLennon** [comment]
> 
> already exists.

Follow the link:
![image](https://user-images.githubusercontent.com/67484051/153302199-9beee2dc-3bc9-4f29-8ec5-d0772bb68435.png)
@thebeardedgeek

**Comment by worksofliam** [comment]
@SJLennon I think an incoming change might be to make it link right to the line number.

**Comment by worksofliam** [comment]
Okay so this is the plan:

* I need to get the regex search working, which supports case-sensitive search.
* I am not going to work on searching by column.

**Comment by worksofliam** [comment]
Closing in place of #165 - @thebeardedgeek I will be working on _this_ this week
