### ISSUE TITLE
QRPGLESRC

### ISSUE THREAD

**Issue by mattsheawave** [halcyon-tech/vscode-ibmi#532]
I can see my source physical files in the libraries.  I can open source from all the other source physicals but QRPGLESRC.  I click or double click and nothing happens.  
Thoughts,
Matt

**Comment by worksofliam** [comment]
@mattsheawave What if you disable SQL in the connection settings, reconnect, and try again?

**Comment by worksofliam** [comment]
Did you get this error?

![image](https://user-images.githubusercontent.com/3708366/153508312-1f4b80a5-977c-4f85-96e3-24ddcb708904.png)

**Comment by paolos69** [comment]
I have disabled SQL
gives me this error: "Source date support is disabled. SQL must be enabled."

**Comment by paolos69** [comment]
I have disabled SQL,
gives me this error: "Source date support is disabled. SQL must be enabled."

**Comment by paolos69** [comment]
I have disabled SQL
gives me this error: "Source date support is disabled. SQL must be enabled."

**Comment by paolos69** [comment]
![image](https://user-images.githubusercontent.com/34394401/153600060-ab57e99b-b1f2-4d99-8404-1d2457458b77.png)

**Comment by worksofliam** [comment]
For source dates to work, your QCCSID must not be 65535.

**Comment by paolos69** [comment]
can i change it?

**Comment by paolos69** [comment]
280?

**Comment by mattsheawave** [comment]
Upon VS Code startup I receive a message "QCCSID is set to 65535. Disabling SQL Support."  So it appears, SQL is already disabled.
I can successfully edit CL and DDS source, just not RPGLE.

**Comment by worksofliam** [comment]
@mattsheawave what is stopping you from editing RPGLE?

**Comment by mattsheawave** [comment]
@worksofliam When I click on an RPGLE member, nothing happens.  It doesn't open in the editor window.  Single click, double click.  When I single click on CL or DDS members, they open fine in the editor window.

**Comment by worksofliam** [comment]
@mattsheawave can you go to the Code for IBM i output tab and paste me the content after you try to open the member?

**Comment by worksofliam** [comment]
@mattsheawave You have a different issue.

> Database file CCSID is 65535

This is because your source file is in CCSID 65535. You can override this by changing the 'source file CCSID' connection setting.

**Comment by worksofliam** [comment]
@mattsheawave Source date support will be enable-able without SQL support as of tomorrow.

**Comment by worksofliam** [comment]
Possible dupe of #534
