### ISSUE TITLE
QCCSID

### ISSUE THREAD

**Issue by paolos69** [halcyon-tech/vscode-ibmi#534]
I need advice, I can't find precise information, if I change the QCCSID FROM 65535 TO 280,
What problems can I encounter?
Thank you

**Comment by paolos69** [comment]
However with version "8.30" and "Sql executor" = 'None' it works
![image](https://user-images.githubusercontent.com/34394401/153704441-6cd2918f-bc2b-4230-8170-0c8af9ab6bce.png)

**Comment by worksofliam** [comment]
I will have to see about enabling source dates even with QCCSID 65535.

**Comment by worksofliam** [comment]
Change incoming

**Comment by paolos69** [comment]
thank you
