### ISSUE TITLE
Color coding incorrect when *N used for field name in DS

### ISSUE THREAD

**Issue by JonFP** [halcyon-tech/vscode-ibmi#537]
Subject says it all.  Graphic showing issue supplied.

<img width="344" alt="image" src="https://user-images.githubusercontent.com/13474625/153775419-a17664b1-e5f1-443b-a27e-383abf27adec.png">

**Comment by worksofliam** [comment]
This is not a Code for IBM i issue. You should raise this issue with the languages extension. 

https://github.com/barrettotte/vscode-ibmi-languages

**Comment by JonFP** [comment]
OK - sorry pardon
