### ISSUE TITLE
I still see connection settings after deleting the connection.

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#538]
I expected the settings file to be cleaned up after deleting my connection but all the filters and library lists for the various profiles are still in the settings.json file. 

I don't know if this is desired but it's not for me. 

I wanted to "clean up" by deleting my connection but that did not work.  I still have to scroll through the settings.json file to perform the additional clean-up.

Is this a bug or a feature request?

**Comment by worksofliam** [comment]
A feature request. 

I guess it's deleting it from the `connections` but not `connectionSettings`?

Liam

**Comment by m-tyler** [comment]
Yes. I spent a small amount of time cleaning up my connections settings so that I could restart with the newest release.
