### ISSUE TITLE
CCSID = 65535

### ISSUE THREAD

**Issue by paolos69** [halcyon-tech/vscode-ibmi#541]
Hello
Always talking about CCSID = 65535 and source update date, this happens:
 I have two systems to manage, on the first I get this message (Img1) on the second equal to the first (img2)
![img1](https://user-images.githubusercontent.com/34394401/154099076-3d1dd1c8-7852-4352-97ac-eb9b17a78f6c.PNG)
![img2](https://user-images.githubusercontent.com/34394401/154099106-39d9de0b-49a8-4e01-9fdb-bce135ad9b4e.PNG)

**Comment by paolos69** [comment]
You're right, I get it

**Comment by paolos69** [comment]
Last problem
![image](https://user-images.githubusercontent.com/34394401/154130574-0198e2d0-7dfe-4a76-bee1-d27af4ec2c19.png)
![image](https://user-images.githubusercontent.com/34394401/154130765-f51e4724-c99d-4a9a-be4c-51b931c7fbc0.png)

**Comment by worksofliam** [comment]
@paolos69 Sorry - you need to give more context to your issues. I will close this for now. Please provide more information when raising issues.

**Comment by worksofliam** [comment]
@paolos69 Hablas espanol? Esta bien si plantea los problemas en espanol.

**Comment by paolos69** [comment]
I'm sorry
