### ISSUE TITLE
Conversion of special characters on source file (es. § )

### ISSUE THREAD

**Issue by paolos69** [halcyon-tech/vscode-ibmi#555]
I changed QCCSID from 65535 to 1144
I'm using version 0.9.1, when I open a source file if there is a character like "§" it doesn't translate it, like with QCCSID 65535.
![SEU](https://user-images.githubusercontent.com/34394401/154984083-434e7d5f-d970-4086-aca6-7768c24e7f0b.png)
![VsCode_0_9_1](https://user-images.githubusercontent.com/34394401/154984132-b44fc7b4-b4c5-4145-8ab9-34364a065795.PNG)
I am also attaching the configuration
![Config1](https://user-images.githubusercontent.com/34394401/154984259-3305db04-9a28-4f2b-94c1-bfc3d4ec4c66.PNG)
![Config2](https://user-images.githubusercontent.com/34394401/154984278-71d52430-dc8f-4d52-8cb5-60a4f2870829.PNG)
Thank you

**Comment by worksofliam** [comment]
@paolos69 is this the only character that is not converting? I wonder if it's because that character is not know to the CCSID of the encoding you're using.

**Comment by paolos69** [comment]
I checked:
CCSID01144, ebcdic-it-280+euro (€)
I hope I'm not wrong.
![ccsid_1144](https://user-images.githubusercontent.com/34394401/154996718-2cd2b743-2df8-4778-8aa7-b17834f1fe98.png)

**Comment by worksofliam** [comment]
@paolos69 What CCSID is the source file? I am going to try and recreate it.

**Comment by worksofliam** [comment]
Also, does it convert properly when source dates are disabled?

**Comment by paolos69** [comment]
Convert correctly when source dates are disabled
The CCSID of creation: 65535
Also happens with creation CCSID: 1144

**Comment by worksofliam** [comment]
@paolos69 Is it happening with any other special characters in that CCSID? Or is just `§`?

**Comment by worksofliam** [comment]
It looks like just that character.

![Uploading image.png…]()

**Comment by worksofliam** [comment]
The fact that it's only not translating this character correctly makes me think there is a deeper issue here with some IBM-supplied programs. Will have to look into it more deeply.

I am glad it's just this character, though.

**Comment by worksofliam** [comment]
@paolos69 May I ask what editor you used to get that character in there? SEU?

**Comment by worksofliam** [comment]
Also happening with ACS.

<img width="991" alt="image" src="https://user-images.githubusercontent.com/3708366/155027907-fb2b8de4-2510-45e9-9f1b-31f6416e5714.png">

**Comment by worksofliam** [comment]
Had some discussions with other people. Here are some notes and quotes.

---

![image](https://user-images.githubusercontent.com/3708366/155032019-729a9abf-f4e1-415a-bbfb-639918b50e00.png)

```
E2969485 40A68589 9984407C 40838881 998183A3   Some weird § charact
```

`7C` is `§` in 280/1144, is `@` in 37.

---

So this works:

* QCCSID is 65536
* File is 1144/280
* Character comes as expected

This doesn't:

* QCCSID is 37
* File is 1144/280
* Bad character comes

---

![image](https://user-images.githubusercontent.com/3708366/155032385-d2f5c880-3014-4fae-b4c2-62c7ef16b33f.png)

> I took an ODBC trace. The column is described as 280, so that's right. The data I get back is wrong, though:

```
F1F2F340407C7C40   should be F1F2F340B5B540
F4F5F64040B5B540   should be F4F5F6407C7C40
```

> So basically, something is converting the data as it's read (to 37, presumably) but then we're trying to interpret it as 280
> Sounds like a bug to me. I'd open an issue with IBM support.
> The weird thing is even the select hex() output is wrong...

> I think it's pretty easy to recreate too. Runsql code snippet creating a cssid 280 file, add a member, then insert a hex literal and query it.

**Comment by worksofliam** [comment]
@paolos69 Are you able to run a select over the view created over member you're trying to create to see if you're having the same issue?

1. `CREATE OR REPLACE VIEW SESSION.MEMBER FOR YOURLIB.YOURSPF(YOURMBR)`
2. `SELECT * FROM SESSION.MEMBER`

Share a screenshot of the results here of the same lines.

**Comment by paolos69** [comment]
![image](https://user-images.githubusercontent.com/34394401/155139852-d036cefa-ca39-4572-b8a8-9db2174e6005.png)

**Comment by paolos69** [comment]
![image](https://user-images.githubusercontent.com/34394401/155140201-dd336a65-28c9-4435-a06e-7c8646da54ad.png)

**Comment by paolos69** [comment]
I think the problem is limited to this character.

**Comment by worksofliam** [comment]
> I think the problem is limited to this character.

I agree. I think we're going to close this we've got the CCSID issues mostly nailed down at this point.
