### ISSUE TITLE
Let administrator see which users are connected via SSH

### ISSUE THREAD

**Issue by alanseiden** [halcyon-tech/vscode-ibmi#563]
**Is your feature request related to a problem? Please describe.**
Security administrators want to track who is connecting to IBM i via SSH (and, ideally what they do on the system).

**Describe the solution you'd like**
An extension that reports usernames and perhaps jobs or other information. 

If there were a basic reporting tool, the security officer might become confident enough to consider SSH (and VS Code, which the developers want).

**Comment by worksofliam** [comment]
@alanseiden I like the idea and I am wondering what the UI could provide in this case? A simple list of users and then below them a list of jobs?

**Comment by alanseiden** [comment]
@worksofliam I think so. How would you do it? All I could find was OpenSSH logging:

https://en.wikibooks.org/wiki/OpenSSH/Logging_and_Troubleshooting#Client_Logging 
https://www.ibm.com/support/pages/sshd-can-use-unix-syslog-facilities-logging
If done right, we get a log that looks like this:
```
Feb 23 22:50:50 Seiden auth|security:info sshd[3409111]: Close session: user alan from [IP Address] port 51876 id 0
Feb 23 22:50:50 Seiden auth|security:info sshd[3409111]: Received disconnect from [IP Address] port 51876:11: disconnected by user
Feb 23 22:50:50 Seiden auth|security:info sshd[3409111]: Disconnected from user ALAN [IP Address] port 51876
Feb 23 22:50:56 Seiden auth|security:info sshd[3409161]: Accepted publickey for ALAN from [IP Address] port 51953 ssh2: RSA SHA256:5NSncUTxwiis/U1lTjiUKU2Et7b1iN/n9G/qBrCqoDmU
```

**Comment by worksofliam** [comment]
@alanseiden Perhaps we could a shortcut to open that log up automatically? And maybe we need to add how to enable it to our docs.

**Comment by alanseiden** [comment]
@worksofliam I've documented the process in our internal KB. I'll send you the link privately and see what you think.

**Comment by worksofliam** [comment]
@alanseiden What is the plan with the issue? What can the extension do to make it easier for you/admins?

**Comment by alanseiden** [comment]
@worksofliam I am not sure, but I plan to meet with a real, live security administrator on Thursday and share my SSH security notes. I have a feeling that VS Code won't be the place to implement this, because VS Code is more for developers than admins.

**Comment by priceaj** [comment]
> VS Code is more for developers than admins.

Just saw this issue and coming along to comment the same thing!
