### ISSUE TITLE
Not able to connect to IBM i

### ISSUE THREAD

**Issue by procton** [halcyon-tech/vscode-ibmi#570]
When connecting to my IBM i server I get the following error "Not connected to 10.200.100.122! connect ECONNREFUSED 10.200.100.122:22.
Which services need to be activated on the server side ? 
Thank you

**Comment by worksofliam** [comment]
@procton make sure the SSH daemon has been started.

**Comment by procton** [comment]
Thank you everybody, closing the issue.
