### ISSUE TITLE
It always tells me that the compilation has failed and it is false.

### ISSUE THREAD

**Issue by viruslogic** [halcyon-tech/vscode-ibmi#580]
Hi, good morning

I just installed the latest version. v1.2.2 and now, every time I launch the compilation of a source, be it RPGLE, free or CL, I always get the log that the compilation has failed. When it is not true. 

The object is created in the AS400 without problems. Even so, it tells me that the compilation has failed.

I attach images and the compilation log for your review.

There are a suspicious error: TypeError: Cannot read property 'groups' of null

![Captura](https://user-images.githubusercontent.com/10233590/157232511-041029a8-894b-40e0-8841-b2d7822bcadf.png)
[error.txt](https://github.com/halcyon-tech/vscode-ibmi/files/8205808/error.txt)

**Comment by worksofliam** [comment]
Fix incoming!

**Comment by worksofliam** [comment]
Release in 1.2.3.

**Comment by viruslogic** [comment]
Awesome!!!

Thank you very much @worksofliam!!!

It's working.
