### ISSUE TITLE
Can't add object browser filters for libraries with '#' in the name since v1.1.0 onwards

### ISSUE THREAD

**Issue by ben-mulhern** [halcyon-tech/vscode-ibmi#582]
In v1.0.3 and previous versions, I have been able to create filters in the object browser for libraries that contain '#' in the library name. From v1.1.0 onwards I receive an error when trying to expand the filter to see the files contained within:

CPD0018: String 'O\#0627743' contains a character that is not valid.
CPF0006: Errors occurred in command.

By rolling back the extension to v1.0.3, the same filter works fine. 

This is low priority because there is a workaround, which is to specify the library name wrapped in double quotes.

**To Reproduce**
1. Existing library called O#06277434 and an active connection to the iSeries.
2.  In object browser -> create new filter with properties:
 Filter name = "Test filter"
 Library = O#06277434
 Object = *
 Object type filter = *SRCPF
 Member = *
3. Attempt to expand the filter in the object browser, which triggers the error message and does not expand the filter.

**Environment:**
 - Extension version = 1.1.0 onwards
 - IBM i OS version = 7.4

**Comment by worksofliam** [comment]
Fix out in 1.2.3
