### ISSUE TITLE
No results in notebook cell

### ISSUE THREAD

**Issue by davidknittle** [halcyon-tech/vscode-ibmi#583]
I LOVE THE NEW NOTEBOOK FEATURE!
When i enter an SQL, it runs the sql but does not display the results. i assume, like usual, i am missing a setting, but i cant figure out which one. 
Also, is there a way to set a default maximum number of returned rows? ACS only brings back a subset of rows, which makes a gneric select much faster

**Comment by worksofliam** [comment]
Hey 👋 

* Do you have SQL enabled in the connection settings?
* after the statement is run, check the Code for IBM i output and perhaps share it here. That might give us a reason why.
* are you getting any errors?

**Comment by davidknittle** [comment]
it seems to be working now. Not sure what changed. I think i just needed to restart VS Code.

**Comment by worksofliam** [comment]
@davidknittle Great!!

If you have a moment, would you mind replying to this thread if you haven't already? Thanks!

**Comment by worksofliam** [comment]
https://github.com/halcyon-tech/vscode-ibmi/discussions/350
