### ISSUE TITLE
Can't log on to server using integrated 5250 terminal.

### ISSUE THREAD

**Issue by cleeverz** [halcyon-tech/vscode-ibmi#585]
I'm using the pub400 server to learn about working and coding in the IBMi environment. Using the vscode-ibmi plugin, I am able to SSH into the server successfully, browse through Libraries and directories, and make changes to code files, but entering my credentials on the login screen in the integrated 5250 terminal always results in a "Password not correct for user profile" error. I can log in successfully with the same credentials using a different 5350 client. 

**To Reproduce**
1. Connect to the pub400.com server in VSC.
2. Click on "Terminals" in the VSC instance. 
3. Select "5250".
4. Enter a valid username and password.

**Expected behavior**
The user should be logged in to the server and able to navigate the OS successfully.

**Actual behavior**
The user always receives the "Password not correct for user profile" error.

**Environment (please complete the following information):**
 - Extension version: v1.2.3
 - IBM i OS version 7.4

**Additional context**
I'm running VSC 1.65.1 on windows 10 12H1.

I'll mention this also in case it might be related: I also noticed that the cursor in the terminal is sometimes out of place at first, appearing below the line it should have, as if it was offset by an extra row. This clears up by maximizing the VSC window.

**Comment by worksofliam** [comment]
@cleeverz suggestions:

* Change your password to use standard a-z characters and numbers. 
* change the terminal CCSID in the connection settings to what you usually use

**Comment by cleeverz** [comment]
@worksofliam , thank you! That first suggestion was the ticket. For educational purposes, may I ask why that mattered? If the server in question accepted special characters in passwords, do we know why they wouldn't work in the 5250 emulator in VSC?

**Comment by worksofliam** [comment]
@cleeverz my initial feeling is that it either has something to do with your pase setup or the terminal encoding! 

Glad you got it working!
