### ISSUE TITLE
Member Fails to Save and Clears Member on System

### ISSUE THREAD

**Issue by mattlavinder** [halcyon-tech/vscode-ibmi#591]
**Describe the bug**
I am having a pretty serious issue with saving a source member. I had a member fail to save and this resulted in the target member being empty. I had enableSourceDates set to true at the time. I disabled enableSourceDates, restored the member, re-applied my changes, and I was able to save successfully.

The issue here is this is a pretty sensitive program, so I cannot post the entire source on a public forum.  I will tell you there are 14,452 lines of code in this member and it is an RPGLE program.  The source file is 132 positions wide. 

Maybe we start by seeing if this can be reproduced by saving a very large source member with enableSourceDates set to true, and then we go from there.

**To Reproduce**
1. Make sure enableSourceDates is set to TRUE
2. Open a large source member
3. Make a modification
4. Save it
5. Error message appears saying member cannot be saved
6. Member on system is now empty

**Expected behavior**
Save the member

**Environment (please complete the following information):**
 - Extension version v1.2.4
 - IBM i OS version 7.4

**Comment by worksofliam** [comment]
> SQL statement too long or complex.

IBM i issue. Will look into it.

**Comment by worksofliam** [comment]
Work around is to break up the inserts. Perhaps group into 7000 rows each.

**Comment by worksofliam** [comment]
Fixed and will deploy tonight. Will save in rows of 5000.

![image](https://user-images.githubusercontent.com/3708366/158698024-6267c51e-1643-4a8e-b8a7-23942e9e8bf0.png)
