### ISSUE TITLE
Search Member

### ISSUE THREAD

**Issue by acerbis** [halcyon-tech/vscode-ibmi#598]
**Describe the bug**
Apparently the search in source file function (i.e. to search a string in all members) is not automatically ASP aware.
Other functions, like create a new source etc. appear to work.
When the grep command is built, the ASP name must be prefixed.

/QSYS.LIB/MYLIB.LIB/SRCPGM.FILE/*.         (this string is built despite the SRCPGM is in a mounted ASP, so it fails.

Should be i.e.

/MYASP01/QSYS.LIB/MYLIB.LIB/SRCPGM.FILE/*.

**To Reproduce**
![immagine](https://user-images.githubusercontent.com/74674075/159960685-499c57d4-b25c-487e-9172-5f211e75091b.png)

thanks

**Comment by worksofliam** [comment]
Quick workaround: hard code the ASP in the connection settings.

Future code enhancement: get the ASP number for the library/source file and use `this.ibmi.aspInfo` to get the ASP name.

Liam
