### ISSUE TITLE
Search Source File functionality ignores Filter criteria

### ISSUE THREAD

**Issue by p-behr** [halcyon-tech/vscode-ibmi#601]
When using the Search Source File in the object browser it will search all source members in the file, ignoring the filter criteria.

**To Reproduce**
1. Create a filter:  Library=QSYSINC, Object=QRPGLESRC, ObjectType=*SRCPF, Member=IFS*
2. Expand the filter to ensure that only member IFS.RPGLE is present.
3. Right-click on the qrpglesrc folder in the newly created filter and choose "Search Source File"
4. Search for "Header File Name: PTHREAD"
5. The search results are from PTHREAD.RPGLE

**Expected behavior**
I would expect that the search would include only members that are present in the filter.

**Screenshots**
![image](https://user-images.githubusercontent.com/17951550/160137556-97821754-b073-4cc7-8242-4a59dbe9ace4.png)

![image](https://user-images.githubusercontent.com/17951550/160137677-d10f3913-9ef2-4f56-a4d6-6faa69dfd8e7.png)

**Environment (please complete the following information):**
 - Extension version v1.2.6
 - IBM i OS version 7.4

**Comment by worksofliam** [comment]
This is a neat idea - not something I ever considered!

**Comment by worksofliam** [comment]
@p-behr Please try the test build in the PR attached to this issue. When you're happy with it, I will merge it and get it released.

Liam
