### ISSUE TITLE
Double-click a source member in object browser keeps tab open

### ISSUE THREAD

**Issue by p-behr** [halcyon-tech/vscode-ibmi#604]
The preview mode is handy, but sometimes you really do want to open multiple members in new tab(s).
It would be nice if the Object Browser worked more like the Explorer: 
* a single-click opens in preview
* a double-click opens in a new tab

**Describe alternatives you've considered**
Make a change in the source, or right-click on the tab and select Keep Open (Ctrl+K Enter).
Maybe I'm missing something obvious?

**Comment by worksofliam** [comment]
Single click vs double click isn't something extensions can determine. There is a configuration change to the default for preview mode!

![image](https://user-images.githubusercontent.com/3708366/160159816-959c04e7-5bd6-4c15-9b03-5270a390e61c.png)

**Comment by p-behr** [comment]
Roger that; Ctl+K Enter it is then!
:-)
