### ISSUE TITLE
Missing Member Browser Option

### ISSUE THREAD

**Issue by sprdave** [halcyon-tech/vscode-ibmi#607]
I am not seeing "Member Browser"  in my IBM i list on the left hand side of Visual Studio Code.  I see tutorials that speak of this option but I do not have "Member Browser"  in my list of options for RPG ILE programming in Visual Studio Code.

* QCCSID: 273
* Features enabled:
   * git: true
   * grep: true
   * tn5250: true
   * setccsid: true
   * GENCMDXML.PGM: false
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: false

**Comment by worksofliam** [comment]
Member browser was replaced with object browser.
