### ISSUE TITLE
Why does the CL extension have to be installed over and over again?

### ISSUE THREAD

**Issue by merhovon** [halcyon-tech/vscode-ibmi#608]
Hello all,

as soon as I connect to the server, I keep getting a message (Would you like to install the CL prompting tools onto your system?) asking if the CL extension should be installed.
This I have to do again and again because otherwise the extension is not available, how can I work around the problem?

**Comment by worksofliam** [comment]
Perhaps the program is being deleted in your temp library - or maybe the extension is doing something bad.

I will look into it tonight.

**Comment by merhovon** [comment]
I checked it in parallel, the library is not cleared.

**Comment by worksofliam** [comment]
Fix made. Due release in 1.3.0.
