### ISSUE TITLE
Not connected to ACE8.TRIPPLITE.COM! Max identification string size exceeded

### ISSUE THREAD

**Issue by cunninghammike1125** [halcyon-tech/vscode-ibmi#610]
I am attempting to create a new connection to ACE8.TRIPPLITE.COM and recieve the error message: Not connected to ACE8.TRIPPLITE.COM! Max identification string size exceeded.  Please advise.

**Comment by worksofliam** [comment]
@cunninghammike1125 Usually this has something to do with the port number being used.

* Are you using the correct SSH port?
* Is SSH enabled on your system?

**Comment by worksofliam** [comment]
Closing as stale.
