### ISSUE TITLE
Import actions from QAUOOPT?

### ISSUE THREAD

**Issue by merhovon** [halcyon-tech/vscode-ibmi#611]
Hello all,

on the AS400 I have some custom actions stored in a custom QAUOOPT, can this be automatically imported into the action list?

Like this:
   Selection . . . . . . . . :   UI                                               
                                                                                
   Command  . . . . . . . . :   CVTRPGSRC FROMFILE(&l/&f) FROMMBR(&n) TOFILE(&l/Q
RPGLESRC) LOGFILE(*NONE)                                                        

It is a whole list, that's why would enter it manually, that's why the question if it is possible automatically.

**Comment by worksofliam** [comment]
Yeah, for sure it's possible and I always wanted to do something like this.

**Comment by worksofliam** [comment]
@merhovon @SJLennon Is this still a nice-to-have? I personally don't think much of it, but I might as well do it sooner than later.

**Comment by worksofliam** [comment]
I am going to close. I don't think there is much ask of it.
