### ISSUE TITLE
Action to quick open member

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#615]
**Is your feature request related to a problem? Please describe.**
In our environment, we do not load a full copy of all sources to each developer.  We only get copies of sources that we work on. I often need to open a member from production code, either to recall how the program was coded before my changes or to duplicate something I have seen in another program. 

**Describe the solution you'd like**
It would be nice to have a simple dialog or something that we type to quickly open a member from the IBM i server without the need to create a filter every time.  It does not need to have a short cut but that would be very nice. 

**Describe alternatives you've considered**
Creating a filter that I constantly modify to find the member I want to open or creating a filter over all production sources to get to the one I want (this last item is slow to download a list of all production members).  

Thanks, Matt

**Comment by worksofliam** [comment]
There are two ways to open files:

1. Open File: allows you to enter in the entire path to source member or streamfile.

<img width="633" alt="image" src="https://user-images.githubusercontent.com/3708366/162812402-16c4a0d7-53d5-4661-8604-41866063fdbc.png">

2. Go to file: lets you quickly filter files you've browsed before to open them again.

<img width="651" alt="image" src="https://user-images.githubusercontent.com/3708366/162812581-90c7ed15-3757-4b66-848e-509ffd20d570.png">

@m-tyler I am going to close this for the time being, but do let me know if you need something more specific.

**Comment by m-tyler** [comment]
Thanks for the info.

I cannot seem to get Ctrl+Alt+O (IBM i: Open File) to work for me.  It tells me each time its unable to open that member.

The Go to file (Ctrl+Alt+P) option works great if I have opened the filter containing that member once.

**Comment by worksofliam** [comment]
@m-tyler Please let me know what you're trying and I will check the format is correct (or fix a bug!)

**Comment by m-tyler** [comment]
I tried all of these patterns, FYI we use an IASP but I have yet to be required to add that to anything so far.
/wfisrc/qrpgsrc/prp10vrg.sqlrpgle
/wfisrc.lib/qrpgsrc.file/prp10vrg.sqlrpgle
/wiasp/wfisrc.lib/qrpgsrc.file/prp10vrg.sqlrpgle

/WFISRC/QRPGSRC/PRP10VRG.SQLRPGLE
/WFISRC.LIB/QRPGSRC.FILE/PRP10VRG.SQLRPGLE
/WIASP/WFISRC.LIB/QRPGSRC.FILE/PRP10VRG.SQLRPGLE


Also, I could not find a log entry for the attempt to see if I was messing up the open string.   Is there such a thing for this?

Thanks, Matt

**Comment by worksofliam** [comment]
For source members, remove the leading `/` you have.

* Instead of: `/wfisrc/qrpgsrc/prp10vrg.sqlrpgle`
* try: `wfisrc/qrpgsrc/prp10vrg.sqlrpgle`

Leading `/` is used for the IFS.

**Comment by m-tyler** [comment]
Sorry about that.  I know I had that pattern typed in one time but I did not have it saved in that list I sent along.  I must have used the wrong extension.  

Any way to keep that little dialog open if it fails to find the member to open it, for instance, I mistyped the source file name, QRPGSRC as QPRGSRC?

**Comment by worksofliam** [comment]
@m-tyler No way to keep it open, but perhaps I could make the value retain for the next time you try to open it. Likely another issue required for that.

**Comment by m-tyler** [comment]
Anything would help to prevent having to retype even though it's not a long string I would imagine IFS strings could be an issue.

**Comment by m-tyler** [comment]
No hurry on this one its a low PTY for me.  Since I know the string pattern, I'll watch out for my poor typing.

**Comment by m-tyler** [comment]
So I would like to have an addition for the quick open, I don't think the member type (extension) needs to be specified.  The IBM i will not allow you to have the same-named member of different types exist in the same source file.   Allowing me to forgo supplying the member type, would mean that your tool would need to figure that part out for me to set the VS Code language. 

Thanks, Matt
