### ISSUE TITLE
Object filter member entries show number of sub items

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#616]
**Is your feature request related to a problem? Please describe.**
If I create a filter that covers all source member files, like Q*, *SRCPF, and then specify a member filter, I will get a list of source files in the library I created the filter for even though there are no members that match my member filter.    I have to open the source file item to see that there is nothing in there for me.  

**Describe the solution you'd like**
Can the number of members found for the source file be shown as part of the display name?

Something like this. 
> QMNUSRC (0)
> QRPGSRC (12)
>QSQLSRC (2)
> QSRVSRC (1)

Thank, Matt

**Comment by worksofliam** [comment]
Yeah, I like this a lot!

<img width="480" alt="image" src="https://user-images.githubusercontent.com/3708366/162818509-39c25c3f-f2f5-4680-8996-7609965c8733.png">

**Comment by m-tyler** [comment]
I hope you would consider reopening this item.  I seem you added the counts to 1.3.0 but I feel its not accurate based on the member filter.  I created a filter with a specific member and I am seeing a count of all members in the source file but what I had intended in the initial ask was to count the number of members matching the filter.

**Comment by worksofliam** [comment]
@m-tyler Interesting. Gotta figure out how to account for the filter!

**Comment by m-tyler** [comment]
when you load the member sub-tree can you count then, like with a for each type of operation?  Otherwise, you should take the query from SYSPARTITIONSTAT and replace the column list with just a COUNT(*).  You run it twice but you get an accurate count.  

An alternative is to write that query with OLAP functions.   A couple of OLAP features could be used, ROW_NUMBER() or group by grouping sets((...),(...)).    Grouping sets would be my preferred solution. 

I can spend a little time writing a query for member lists that do both of the OLAP features and let you decide which direction to head if you want.

**Comment by m-tyler** [comment]
I wrote two queries based on your initial query in the extension for the member list. 

They both use REGEXP_LIKE() to perform filtering on all three key elements of member filtering.  I found no difference in time to produce results between the two (9 to 10 seconds on my system).  I suspect it's the REGEXP_LIKE() function causing the basic COUNT(*) version from performing faster.  I would like you to consider the benefits of allowing the user to supply specific, simple generic, or a REGEXP string to get a list of data for the filter elements on all three member filter elements. 

Specific named filtering for a single selection: `REGEPR_LIKE( COL ,'^{filter}')`
Simple generic filter: `REGEXP_LIKE( COL,'^{genfilter}')`
REGEXP filter: `REGEXP_LIKE( COL,'{regexpfilter}')`

Where 
- ^{filter} = 'QRPGSRC' or the like for the library or member
- ^{genfilter} = 'Q*' or 'LIB*' or 'SRV*'
- {regexpfilter} = any regular expression string, user responsible for correct format, no input validation by extension. 


The OLAP version is in a CTE so that filtering on the `**MBR COUNT` lines could be filtered but it does not need to be in a CTE for basic result set processing. 

Basic COUNT(*) version: 
```
    select A.IASP_NUMBER as MBASP
           ,A.TABLE_NAME as MBFILE
           ,A.TABLE_SCHEMA as MBLIB
           ,LL.ORDINAL_POSITION MBLIBPOS
           ,count(B.SYSTEM_TABLE_MEMBER) as MBCOUNT
      from QSYS2.SYSTABLES as A
           join QSYS2.SYSPARTITIONSTAT as B
             on B.TABLE_SCHEMA = A.TABLE_SCHEMA
               and B.TABLE_NAME = A.TABLE_NAME
           inner join QSYS2.LIBRARY_LIST_INFO LL
             on LL.SCHEMA_NAME = A.TABLE_SCHEMA
               and LL."TYPE" = 'USER'
      where 1 = 1
        and regexp_like ( A.TABLE_SCHEMA ,'(D1WFIQUAL|D1WFIINTG|^PGMT|^WFISRC)' )
--         and regexp_like ( A.TABLE_SCHEMA ,'(^D1WFIQUAL)' )
        and regexp_like ( A.TABLE_NAME ,'Q.{2,3}SRC' ) 
        and A.TABLE_NAME not in ('QSQDSRC')
--         and regexp_like ( B.SYSTEM_TABLE_MEMBER ,'^HRM66JRG' )
--         and regexp_like ( B.SYSTEM_TABLE_MEMBER , '^HRM66XRG|^KRN00A(RG|FM|PR|SP|BL)|^KRN00D|^KRN00R|^KRN01A|^KRN03A|^PRP00AFN2[0123]|^PRP00ABL|^PRP00APR|^PRP00ARG|^PRP00ASP|^PRP00ASPU|^PRP00D|^PRP60C|^PRP60E|^UTL000FN05' )
        and regexp_like ( B.SYSTEM_TABLE_MEMBER , '^HRM66XRG|^KRN00A(RG|FM|PR|SP|BL)|^KRN00D|^KRN00R|^KRN01A|^KRN03A|^PRP00AFN2[0123]|^PRP00ABL|^PRP00APR|^PRP00ARG|^PRP00ASP|^PRP00ASPU|^PRP00D|^PRP60C|^PRP60E|^UTL000FN05' )
group by A.IASP_NUMBER ,A.TABLE_NAME ,A.TABLE_SCHEMA ,LL.ORDINAL_POSITION
```
OLAP count() version: 
```
with T1 as (
    select (B.AVGROWSIZE - 12) as MBMXRL
           ,A.IASP_NUMBER as MBASP
           ,A.TABLE_NAME as MBFILE
           ,A.TABLE_SCHEMA as MBLIB
           ,ifnull( B.SYSTEM_TABLE_MEMBER , '**MBR COUNT') as MBNAME
           ,B.SOURCE_TYPE as MBSEU2
           ,B.PARTITION_TEXT as MBMTXT
           ,LL.ORDINAL_POSITION MBLIBPOS
           ,count(B.SYSTEM_TABLE_MEMBER) as MBCOUNT
      from QSYS2.SYSTABLES as A
           join QSYS2.SYSPARTITIONSTAT as B
             on B.TABLE_SCHEMA = A.TABLE_SCHEMA
               and B.TABLE_NAME = A.TABLE_NAME
           inner join QSYS2.LIBRARY_LIST_INFO LL
             on LL.SCHEMA_NAME = A.TABLE_SCHEMA
               and LL."TYPE" = 'USER'
      where 1 = 1
        and regexp_like ( A.TABLE_SCHEMA ,'(D1WFIQUAL|D1WFIINTG|^PGMT|^WFISRC)' )
--         and regexp_like ( A.TABLE_SCHEMA ,'(^D1WFIQUAL)' )
        and regexp_like ( A.TABLE_NAME ,'Q.{2,3}SRC' ) 
        and A.TABLE_NAME not in ('QSQDSRC')
--         and regexp_like ( B.SYSTEM_TABLE_MEMBER ,'^HRM66JRG' )
--         and regexp_like ( B.SYSTEM_TABLE_MEMBER , '^HRM66XRG|^KRN00A(RG|FM|PR|SP|BL)|^KRN00D|^KRN00R|^KRN01A|^KRN03A|^PRP00AFN2[0123]|^PRP00ABL|^PRP00APR|^PRP00ARG|^PRP00ASP|^PRP00ASPU|^PRP00D|^PRP60C|^PRP60E|^UTL000FN05' )
        and regexp_like ( B.SYSTEM_TABLE_MEMBER , '^HRM66XRG|^KRN00A(RG|FM|PR|SP|BL)|^KRN00D|^KRN00R|^KRN01A|^KRN03A|^PRP00AFN2[0123]|^PRP00ABL|^PRP00APR|^PRP00ARG|^PRP00ASP|^PRP00ASPU|^PRP00D|^PRP60C|^PRP60E|^UTL000FN05' )
        
      group by GROUPING SETS (
            (
              B.AVGROWSIZE
              ,A.IASP_NUMBER
              ,A.TABLE_NAME
              ,A.TABLE_SCHEMA
              ,LL.ORDINAL_POSITION
            )
            ,(
              B.AVGROWSIZE
              ,A.IASP_NUMBER
              ,A.TABLE_NAME
              ,A.TABLE_SCHEMA
              ,B.SYSTEM_TABLE_MEMBER
              ,B.SOURCE_TYPE
              ,B.PARTITION_TEXT
              ,LL.ORDINAL_POSITION
            )
          )
  )
  select MBASP
         ,MBFILE
         ,MBLIB
         ,MBNAME
         ,MBSEU2
         ,MBMTXT
         ,MBLIBPOS
         ,MBCOUNT
    from T1
--     where 1=1 and MBNAME = '**MBR COUNT'
    order by MBASP
             ,MBLIBPOS
             ,MBLIB
             ,MBFILE
             ,MBNAME
             ,MBSEU2
             ,MBMTXT
;select * from QSYS2.LIBRARY_LIST_INFO ll where       
```

**Comment by worksofliam** [comment]
Yeah, this is actually a lot trickier than I thought. Using SQL isn't a bad option, but for those with thousands of members, this could be pretty slow (which I want to avoid).

For the time being, I am going to remove the functionality I added because a total count, even with a filter, is wrong. This is something I can come back to in the future.

**Comment by m-tyler** [comment]
I do understand the part of reducing others being affected by a slow process.    My sample queries are my design for what _I_ can do with the product not necessarily what others need, so if the REGPEX_LIKE() over the library, on the queries above, are turned back into a specific selection, this reduces the work.   Then the use of LIBRARY_LIST_INFO is not needed in the query also.  

We have source in our archive library that has 25749, 8252, and 24350 members.  The current design it takes about  the same amount of time to expand the list of those members.   One of the main difference between what you are providing people and my solution is that I use REGEXP_LIKE() to assist filtering with complex lists of members.  The above examples use the REGEPX_LIKE() on all three key element of a filter.  Removing the REGEXP_LIKE() over library and is should perform fairly well.

This query on my system runs under 10 seconds. 
```
create table qtemp.filter_testing as( 
with T1 as (
    select (B.AVGROWSIZE - 12) as MBMXRL
           ,A.IASP_NUMBER as MBASP
           ,A.TABLE_NAME as MBFILE
           ,A.TABLE_SCHEMA as MBLIB
           ,ifnull( B.SYSTEM_TABLE_MEMBER , '**MBR COUNT') as MBNAME
           ,B.SOURCE_TYPE as MBSEU2
           ,A.FILE_TYPE as MBPFSRC
           ,B.PARTITION_TEXT as MBMTXT
           ,count(B.SYSTEM_TABLE_MEMBER) as MBCOUNT
      from QSYS2.SYSTABLES as A
           join QSYS2.SYSPARTITIONSTAT as B
             on B.TABLE_SCHEMA = A.TABLE_SCHEMA
               and B.TABLE_NAME = A.TABLE_NAME
      where 1 = 1
        and A.TABLE_SCHEMA = 'WFIARCHIVE'
        and regexp_like ( A.TABLE_NAME ,'\$\$ARCSRC' )        
      group by GROUPING SETS (
            (
              B.AVGROWSIZE
              ,A.IASP_NUMBER
              ,A.TABLE_NAME
              ,A.TABLE_SCHEMA
            )
            ,(
              B.AVGROWSIZE
              ,A.IASP_NUMBER
              ,A.TABLE_NAME
              ,A.TABLE_SCHEMA
              ,B.SYSTEM_TABLE_MEMBER
              ,B.SOURCE_TYPE
              ,A.FILE_TYPE
              ,B.PARTITION_TEXT
            )
          )
  )
  select
          MBASP
         ,MBFILE
         ,MBLIB
         ,MBNAME
         ,MBSEU2
         ,MBPFSRC
         ,MBMTXT
         ,MBCOUNT
    from T1
--     where 1=1 and MBNAME = '**MBR COUNT'
    order by MBASP
             ,MBLIB
             ,MBFILE
             ,MBNAME
             ,MBSEU2
             ,MBPFSRC
             ,MBMTXT
) with data
;select count(*) from qtemp.filter_testing
```

I don't absolutely need the counts, it just seemed like a good idea.   If there was a good way to provide the information to most with the simple selection style and also allow for a more complex style like I have demonstrated, I think it would provide that nice extra for those like me.  

Anyway, thanks for putting in the time to consider this.

**Comment by m-tyler** [comment]
I added the enableSQL condition to `getObjectList`.  When this condition is true, I clear the results of DSPFD command, insert the results of an `SYSTABLES inner join SYSPPARTITIONSTAT` query that matches the used columns from the DSPFD command then let the result of `getObjectList` work as originally designed. 

When the member quantity is large, its does take some time, but knowing that I am using SQL to build this list I accept that delay.  

This is what my source file list looks like now.   This list took about 60 seconds to build.  But only about 3 seconds the second time. 

![image](https://user-images.githubusercontent.com/1353665/194084481-8abcd045-bfef-4685-a069-243a11aeb813.png)

Side note, I create two SQL table functions to produce the results of the source file list and the source member list.  The table function for the source file list also inserts the dots and the number of members in the file text.

**Comment by worksofliam** [comment]
@m-tyler You should make a PR for this. I am open to optional features like this. It's not something I would use, but if others find it useful we can put it in.
