### ISSUE TITLE
results.csv from DB query attempts to save to local root with no permissions 

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#620]
**Describe the bug**
If I run my query with CSV: prefix I get a CSV tab opened and it looks like I can save the results but I get this error instead, when I press Ctrl+S to save.  Also, VSC opens a duplicate empty tab. 
![image](https://user-images.githubusercontent.com/1353665/162830985-e8595bf7-595b-4bda-9d24-f1e33a0e67ca.png)
![image](https://user-images.githubusercontent.com/1353665/162831345-80a37a2d-0c31-4862-aa3a-7d199476f694.png)

**To Reproduce**
1. Open SQL workspace 
2. Type a query with the prefix of CSV: 
3. Once the results tab appears, press Ctrl+S to save.
4. Error appears in the notifications area.

**Expected behavior**
I would have assumed the default location would be the user home folder and no second tab opened.  

**Environment (please complete the following information):**
 - Extension version v1.2.6
 - IBM i OS version 7.3

**Additional context**
If I click to close the tab, I get asked to save the tab.  When I select save nothing seems to happen sometimes I receive the error above but mostly I see nothing happen.

If I choose File | Save as, I still get the duplicate empty tab but I also get to save the results.csv tab.  It's not very intuitive.  I have to close the duplicate and then the results tab I want appears different. 

I have rainbow CSV installed and I cannot rule it out as the culprit.   However, I have turned off the tool and still see the issue. 

Thanks, Matt

**Comment by worksofliam** [comment]
Interesting... maybe this is a Windows thing as I don't think I get the same result on my mac. I will look into it when I get home to my Windows machine.

**Comment by m-tyler** [comment]
No worries.  This is a low PTY issue for me. 

Thanks, Matt

**Comment by worksofliam** [comment]
Same issue on Mac.

**Comment by worksofliam** [comment]
Ok, this is an issue with 'Save', but if you 'File->Save As', then it lets you save as you'd expect. I have asked some VS Code devs if there is a way around the issue with 'Save' but it doesn't like there is for now.
