### ISSUE TITLE
query results show different number of columns than RUN SQL Scripts 

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#621]
**Describe the bug**
I just noticed a join query is returning a smaller set of columns to the result tab than its supposed to.  I compared it to the results from the exact same query running in ACS RSS.  I also looked at the Code for IBM I log and I can see the results returning all the columns properly.   

I noticed this issue with all forms of output supported. 

**To Reproduce**
My example query is a single join statement.  I have yet to determine if it is also a problem with multiple joins.   I don't notice this with single table queries.  

**Expected behavior**
All columns returned that were specified in the query.

**Screenshots**
![image](https://user-images.githubusercontent.com/1353665/162837816-34c6b3ad-f3ec-4752-8694-75bd394553af.png)
![image](https://user-images.githubusercontent.com/1353665/162837841-18dda77f-5f78-473d-bc79-5ac440a192c7.png)
![image](https://user-images.githubusercontent.com/1353665/162837953-c8827ea8-09d0-4976-bcf3-18a4aa97559d.png)

**Environment (please complete the following information):**
 - Extension version 1.2.6
 - IBM i OS version  7.3

Thanks, Matt

**Comment by worksofliam** [comment]
@m-tyler by any chance are you able to recreate this with the sample database that you can create in the system?

**Comment by m-tyler** [comment]
I will attempt it with the system catalogs as many of the table/column informational items are views like my query is formed as.  If the issue does not appear I will look to the sample database.   At least on 7.3 its seems to be a bit messed up, missing some data.  I don't have it installed right now.

**Comment by m-tyler** [comment]
from ACS RSS.
![image](https://user-images.githubusercontent.com/1353665/162842427-6d44f5a4-230e-47aa-9f13-a3fefe071c17.png)

From VS Code JSON results.
![image](https://user-images.githubusercontent.com/1353665/162842474-1a4f149b-8e26-429f-8d19-fcfd4e98d67b.png)

I am going to assume there is a missing couple columns but I have not determined
[result.csv](https://github.com/halcyon-tech/vscode-ibmi/files/8468112/result.csv)
 which one yet. 
[VSCODE_IBM_I_Ext_issue_621.log](https://github.com/halcyon-tech/vscode-ibmi/files/8468111/VSCODE_IBM_I_Ext_issue_621.log)

**Comment by m-tyler** [comment]
Okay, It may be where both result sets in the join have the same column name.   In the last query i sent TABLE_NAME is missing from the second join result set column list.

**Comment by m-tyler** [comment]
Its also missing SC.TABLE_SCHEMA from the results.

**Comment by m-tyler** [comment]
in the above query SC.TABLE_NAME and SC.TABLE_SCHEMA are missing but also the like columns, named SYSTEM_*.

**Comment by worksofliam** [comment]
@m-tyler Totally weird. I will have a look into this as soon as possible. Maybe earlier next week as it's an anniversary this weekend.

**Comment by m-tyler** [comment]
No worry this is a low PTY issue for me. 

THanks, Matt

**Comment by worksofliam** [comment]
@m-tyler When you run the query with the missing columns again, would you mind sharing the Code for IBM i output? Likely a parsing issue but I am not able to recreate at this time.

**Comment by m-tyler** [comment]
Last test that produced CSV tab.
![image](https://user-images.githubusercontent.com/1353665/164546400-f3abbfcf-35bf-40eb-a9bf-7cd7d4cf395b.png)
Output from the Code for IBM i log.
[Issue #621.txt](https://github.com/halcyon-tech/vscode-ibmi/files/8534841/Issue.621.txt)

**Comment by m-tyler** [comment]
I took the output from the log and parsed the column headings into a string that was one heading column per line with a comma.  I then ran the query in ACS RSS tool (1.1.9.0 version), right-clicked choose Details... then the details window appear (see the image earlier), select all (Ctrl+A), right-click choose Copy > Column Name.    This sequence puts the column headings into the clip board.  I pasted into a new tab then compared the log to this new tab and I found no differences in the number of columns returned from the system.

The first thing that popped into my mind was that the underlying query is joining with the keyword `using` which causes the named columns to be the leading columns and never repeat in the results again.

**Comment by worksofliam** [comment]
Here are the four differences.

![image](https://user-images.githubusercontent.com/3708366/165204021-3221d7d0-f3ac-4e04-88d3-50964497845e.png)

And the answer is that the same key is used already and that is the nature of JSON. When the same key is used, it will overwrite the previous.

@m-tyler Not sure how to fix this one unless we rename the key if it's found in the object already. Otherwise this isn't something that I can solve.

**Comment by m-tyler** [comment]
Renaming the columns does work but the next question is who is responsible for renaming duplicate columns.  At first, I would put the responsibility on the user but there needs to be something to inform them they need to rename these duplicate columns.

The other option is to have the code rename the columns.  Outside of forcing a table nick name (like SC for SYSCOLUMNS) I am not certain what you can do, easily. 

You could write code to parse the statement out and find the tables then give them nicknames (if they don't have one), but that seems like a lot of effort.

**Comment by worksofliam** [comment]
I could rename the columns, but it'd become more like `TABLE_SCHEMA`, `TABLE_SCHEMA_2`, etc.

**Comment by m-tyler** [comment]
That would be perfectly fine with me.  Would you also be able to know to send a little note to the user letting them know you had to rename some columns because of duplication?

**Comment by worksofliam** [comment]
@m-tyler That's a nice idea also. I will have to see what I can do
