### ISSUE TITLE
A way to run one action when focus is in source tab

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#625]
I have a couple of actions I can use on general members, WBUILD is one that I would use while I have the source open in a tab.  Another action is ACMSCHKOUT command built by Rocket Aldon.  I only want this action to appear when I selected it from the member list of the object browser.

I would want WBUILD to be selectable when I choose to run an action when the selection focus is in the member list of the object browser as well as ACMSCHKOUT.  

Is there a piece of information about where the focus is at so that a setting can be used to control when actions appear for selection?

Thanks, Matt

This is Low PTY for me.

**Comment by m-tyler** [comment]
Correct. I don't want my check-out command to appear when I initiate the actions within the source tab but I do want the WBUILD command to be active.

**Comment by worksofliam** [comment]
Had a look into this, and it will actually take a lot of work:

* Separate commands needed when opening from source view or tree view.
   * It used to be this way about a year ago but was removed
* New configuration options on actions.
* New UI on Action editor to support this new configuration 
* Documentation updated to explain the use case.

I will leave this open, but before I work on I'd need to hear from others to make sure it's worth the time.

**Comment by m-tyler** [comment]
Yep, not a problem.  If its costs too much then I say it can be left alone.  I understand that others might not want the same ask as I have.
