### ISSUE TITLE
GENCMDXML halts with error with invalid objects for CL parsing

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#626]
**Describe the bug**
I open CL source and everything looks fine but there are many errors reported to QSYSOPR, `CPF9801 received by procedure GENCMDXML. (C D I R)`.  I reply to them with a C.  

Tracking the problem down to the way GENCMDXML is coded.  If you specify no error DS x'00000000' then any errors within QCDRCMDD will percolate to the next level, GENCMDXML, which this error is sent to QSYSOPR.  

**To Reproduce**
1. Open Output to Code for IBM i
2. Clear output pane
3. Open CL member 
4. Move the cursor over an item that is not a command.
5. Watch the output, you will see the error appear.
`/home/PGMT: system "CALL PGM(ILEDITOR/GENCMDXML) PARM('BCAT      ' 'BCAT      *LIBL     ')"
/home/PGMT: system "CALL PGM(ILEDITOR/GENCMDXML) PARM('QTEMP     ' 'QTEMP     *LIBL     ')"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CEE9901: Application error.  CPF9801 unmonitored by GENCMDXML at statement 0000002200, instruction X'0000'."
}`

**Expected behavior**
I understand that its harder to know for sure if a token is supposed to be a command object but at least the cal to the API should be silenced for errors. 

**Screenshots**

**Environment (please complete the following information):**
 - Extension version 1.2.6
 - IBM i OS version 7.3

**Additional context**
While working over the steps to document the issue as i see it. I noticed that this tool constantly pulls down the source for the open member.  Is this a setting to turn off?   While documenting this issue the tool pulled the source at least 7 times after opening.

**Comment by m-tyler** [comment]
I think defaulting the length of the Error ds to 16 or x'10' for the first two hex characters would prevent halts from percolating upwards.

**Comment by worksofliam** [comment]
@m-tyler 

I have pushed a change to the CL source. You can see it here:

https://github.com/halcyon-tech/vscode-ibmi/commit/ca7cf4af920fd0783c54b7d1f9e874beaca2b993#diff-351b3445a9fb9df083ba7bf3df464bb7725071210793b1db86f496c04e5e0aa6R9

By tomorrow morning a new release will be out with this fix. Test it and let me know.

> I noticed that this tool constantly pulls down the source for the open member. Is this a setting to turn off? While documenting this issue the tool pulled the source at least 7 times after opening.

When you open a file and do not change it, VS Code will keep polling the file to detect any changes. This is standard VS Code behaviour and there is no way to turn it off I believe.

**Comment by worksofliam** [comment]
New change coming tonight.

**Comment by worksofliam** [comment]
@m-tyler Please review the commit I made to make sure the new hex value is valid.

**Comment by m-tyler** [comment]
Its correct.
