### ISSUE TITLE
Connection Settings need a *DEFAULT profile section 

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#628]
**Is your feature request related to a problem? Please describe.**
Connection Settings need a *DEFAULT profile section instead of injecting the save profile values in the middle of the *DEFAULT profile. Duplicated settings are currentLibrary,homeDirectory, libraryList ,objectFilters ,databaseBrowserList.

When I save the current and initial connection settings into a connection profile, the save injects this connection profile in the middle of the actual default object. 

**Describe the solution you'd like**
Just create a connectionProfiles[{"name": "*DEFAULT"}] for initial connections.  this way when I want to save the current connection profile to a named one it would simply just copy that whole profile object to a new one. 

I am trying to build a work environment that allows me to develop with asymmetry to the Rocket Aldon LM(i) tool.   I would need to be able to create profiles quite often. 

**Describe alternatives you've considered**
I have not tried anything else.  It would be nice to have a copy action through the VS Code interface so I can build profiles quickly.  Copying through the settings .json document is clumsy. 

![image](https://user-images.githubusercontent.com/1353665/163593187-d3a4e9bb-521a-4c54-834e-e8eb7d591194.png)

This is a medium PTY for me. 

Thanks, Matt

**Comment by m-tyler** [comment]
So if you don't provide a *DEFAULT connection profile object then can you provide a maintenance panel for a connection profile?

**Comment by worksofliam** [comment]
I could create one automatically, but there is nothing from stopping the user from creating a default one. I am not sure this is something I will work on, but for sure am open to PRs.

**Comment by m-tyler** [comment]
When I go to create variables for each connection profile, the system only saves them to the base (*DEFAULT) connection in the section.  

"...there is nothing from stopping the user from creating a default one"  I am not that clear on what you mean by this.  Does this mean I can alter the base connectionSettings into a connection profile named *DEFAULT?

**Comment by m-tyler** [comment]
So what I thought was an insertion of the default connection profile ends up being a replacement of the connection settings from a profile.  Sorry, for misunderstanding that part.   

I am conflicted in asking for a *DEFAULT profile, now that I understand what you are accomplishing, but I am still on the side of just having it created.   

But with that said the other part where the custom variables are not being locked to a connection profile is still an issue.  

For instance, I created a few profiles, added variables, swapped to one of the profiles, added a new variable, (no save existing profile option exists), swapped to another profile, and variables are gone. 

When I remove a filter from a profile, (since there is no option to save an existing profile), if I swap to another profile and then back to the one I removed the filter from, the filter is back. 

Variables and filter modification happen only in the global connection settings and will not be pushed to the profile that sets up the connection environment, so maybe all that is really needed is to have the "Save current settings into Profile" have the ability to select a profile to save to.

**Comment by m-tyler** [comment]
I just read in the Code for IBM i about saving to an existing profile if you use the same name (I missed that part the first time).  For me, I was envisioning being able to name the profiles after a project ID and summary text, this makes it hard(er) to replace a profile.  I think some option to allow for picking the profile to replace is beneficial.

**Comment by m-tyler** [comment]
I am going to write up anther feature request to ask for what I would truly want and close this one to reduce any confusion.
