### ISSUE TITLE
Copy member fails with "Extension must be provided when creating a member."

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#630]
**Describe the bug**
Copy member fails with "Extension must be provided when creating a member."

We have an IASP, so I don't know what effect that has on the action.

No Code for IBM i log entry is made so the action never makes it to the IBM server. 

**To Reproduce**
1. In a filter that you can add members to, expand and find any member.
2. Right-click and select the action "Copy Member"
3. Fill out the popup dialog line to make the member unique to the source file copying to.
4. Press Enter.
5. See the error notification appear.

**Expected behavior**
New member is created.

**Environment (please complete the following information):**
 - Extension version 1.2.6
 - IBM i OS version 7.3

**Comment by worksofliam** [comment]
@m-tyler Need some more info from you:

1. What format is the new path you're copying to?
2. Please share a screenshot of the error
3. Any output in the Code for IBM i output channel?

**Comment by m-tyler** [comment]
Prompt open from selection
![image](https://user-images.githubusercontent.com/1353665/164479202-cdbc4081-ba18-4736-9807-1b05794c266a.png)

My string before Enter
![image](https://user-images.githubusercontent.com/1353665/164479652-044a1d51-93a3-41f7-8283-b20baea19400.png)

Error after Enter
![image](https://user-images.githubusercontent.com/1353665/164479821-ee6dda4c-281b-43c7-bff1-f51abdca3b17.png)

**Comment by worksofliam** [comment]
@m-tyler Try it without the ASP and the leading `/` and see if that works.

**Comment by m-tyler** [comment]
Removed `WIASP/`.
![image](https://user-images.githubusercontent.com/1353665/164487290-8ec9dc44-3358-4bf7-a165-f443817ea648.png)
Error in log.
![image](https://user-images.githubusercontent.com/1353665/164487550-1893a792-c551-4aae-9fb3-434626c4d7a0.png)

**Comment by worksofliam** [comment]
Cool. I will look into it!
