### ISSUE TITLE
Database table/PF objects are not recognized by actions feature.

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#631]
**Is your feature request related to a problem? Please describe.**
I was trying to implement a pseudo PDM options feature using the actions.  My action I want to implement is a CPYF command to copy data from the selected table object and be prompted for the target table to copy to.   I have my action built but the object browser sees my table as a file and thinks it need to be operated on like a PF-SRC object and not another object. 

**Describe the solution you'd like**
Since database SQL tables (FILES) (PF-DTA attributes) (SYSTABLES -> FILE_TYPE <> 'S') cannot have more than one member and search thing can be problematic the right-click options my table objects are limited to are useless.   It save you time developing any right-click options I ask that FILE_TYPE <> 'D'  be treated like other object types and have the Run Actions option on their right-click menu. 

**Describe alternatives you've considered**
Since there isn't a command line available to me (i don't have the 5250 terminal installed) I have to return to the ACS 5250 tool to run my PDM options there. 

**Additional context**
You may need to augment the query of SYSTABLEs to return the FILE_TYPE so that other processing knowledge maybe possible. 

Thanks, Matt

**Comment by worksofliam** [comment]
So I think what you're asking for is: **can an action be created for specific object attributes as well as types?**

Because a `PF-SRC`, `PF`/table, `LF`, etc, are all types of `*FILE`. We do actually return the attribute, but Actions do not take it into account. It gets tricky here because the type is already kind of specific, but I can see how checking the attribute would be useful also.

Got to think about how it would work for a UI perspective.

**Comment by worksofliam** [comment]
Let's start by adding the attribute to the item description in the object browser.

![image](https://user-images.githubusercontent.com/3708366/165198768-8bca4c64-d6c4-406a-9bd4-a56d0089b75a.png)

**Comment by worksofliam** [comment]
I ended up figuring it out and it was tons easier than I was expecting. Will release it tonight! 
![image](https://user-images.githubusercontent.com/3708366/165201491-fea35a83-3ae9-485c-b19a-16374d0b998c.png)

**Comment by m-tyler** [comment]
Great!  Works like a charm!
