### ISSUE TITLE
Provide a save or save as option for connection profiles

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#633]
**Is your feature request related to a problem? Please describe.**
Currently, connection profiles replace the active connection properties.  If I want to make modifications and save them its easy, I just select the "Save current settings into profile" action.  What was not clear at first (until you read through [Code for IBM i : Settings: Connection](https://halcyon-tech.github.io/vscode-ibmi/#/?id=settings-connection) is that you have to use the exact same profile name to perform a Save action.  

For me, I was wanting to use a pattern like `project ID - project summary`.  These can be long enough to be problematic when retyping the name, in order to replace an existing profile.

**Describe the solution you'd like**
When I choose to save the current settings, please present a list of connection profiles like is done when I select to set on active.  The extension would the proceed to replace that profile with the values from the active settings. 

**Describe alternatives you've considered**
My only alternative is to just name the profiles after the project ID.  Some I recall what they are for others I will not.   

**Additional context**
Along with creating connection profiles there is/will be a need to delete them.  Can this be considered for addition also?

My best practices goal would be to set a profile up so that it sets the library list and each of my filters are a just collection of change objects for my project.  What I would need the system to be able to do before I could use the system this way is to allow for me to list libraries, source files and members that are involved in my project.  We have three basic development paths, base and two deltas used for Sprint and Epic changes.  Each of these paths involves multiple libraries.  The libraries basically represent a developer space, code integration space, QA/UT space, and production space.  We store sources in the standard member types source files, eg, QRPGSRC, QDDSSRC, etc.   Code changes can be for different named source members so a simple generic pattern is not possible at times.

**Comment by worksofliam** [comment]
I think this is possible now.

**Comment by m-tyler** [comment]
What you provided is wonderful! Sorry for not getting back a response on this one sooner.
