### ISSUE TITLE
Ad-Hoc compare action

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#637]
**Is your feature request related to a problem? Please describe.**
Is it possible to provide a panel to allow me to type in the source member(s) for comparison?

**Describe the solution you'd like**
There are times when I want to compare a modified version of source to the production copy of source.  A general action/command that does not need to be linked to a short-cut, that presents a entry form with a from source and to source.  The initial iteration could be two quick popups similar to the popup that appears for Ctrl+Alt+O.   But I would ask for a full panel that lets me individually specify the from / to library / source file / member.

**Describe alternatives you've considered**
The only way to really achieve this with my company's source management design is to open both sources (using Ctrl+Alt+O or from a filter), navigate to the open files list, select each source to compare, and then choose to compare.

**Comment by worksofliam** [comment]
@m-tyler This is what I've come up with. There isn't an easy to get a prompt to show two input boxes right now without a bunch of work. Here is a video for it. It basically allows you to use the `Compare with selected` without having to find the second member.

**Comment by worksofliam** [comment]
https://user-images.githubusercontent.com/3708366/165203047-55ca727b-e53c-4e4d-99e6-24427541932d.mov

**Comment by m-tyler** [comment]
NICE!  I ask for a lot and really only expect you to do what is available and I think this addition is truly a lot.   I cant wait to work with this addition!

**Comment by worksofliam** [comment]
@m-tyler Excited for your continued feedback :)

**Comment by m-tyler** [comment]
Well it does not work for me.  I keep getting `Unable to open 'PRP40A.RPGLE ↔ PRP40A.RPGLE': PRP40A in *N type *MEM not found. (42704).`

1. I set my development member with `Select for Compare` (library PGMT)
2. I press F1, search for `IBM I:Compare with Selected`
3. Replace the library with the one I want to compare to
   
![image](https://user-images.githubusercontent.com/1353665/165633918-ad0ac76a-9119-49e4-97d0-3c062750d165.png)
![image](https://user-images.githubusercontent.com/1353665/165633961-eeea7d7c-1856-4377-905a-67bff69a9b7f.png)

5. Press Enter and I receive the above error

In the Code for IBM i log I can see the alias' get created for the members but I then see `select srcdat, rtrim(srcdta) as srcdta from ILEDITOR.WFISRC_QRPGSRC_PRP40A` and then I get `SQLSTATE: 42704\nNATIVE ERROR CODE: -204\nPRP40A in *N type *MEM not found.",`

The log then produces the whole member details for the WFISRC member. 

I have removed the /WIASP part with no luck. 

From the log:
```
/home/PGMT: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
CREATE OR REPLACE ALIAS ILEDITOR.PGMT_QRPGSRC_PRP40A for PGMT.QRPGSRC("PRP40A")
/home/PGMT: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
CREATE OR REPLACE ALIAS ILEDITOR.WFISRC_QRPGSRC_PRP40A for WFISRC.QRPGSRC("PRP40A")
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n  ?>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.",
    "stderr": ""
}

/home/PGMT: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
SELECT LENGTH(srcdta) as LENGTH FROM ILEDITOR.PGMT_QRPGSRC_PRP40A limit 1
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n  ?>\nDB20000I  THE SQL COMMAND COMPLETED SUCCESSFULLY.",
    "stderr": ""
}

/home/PGMT: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
select srcdat, rtrim(srcdta) as srcdta from ILEDITOR.WFISRC_QRPGSRC_PRP40A
{
    "code": 4,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\n **** CLI ERROR *****\n         SQLSTATE: 42704\nNATIVE ERROR CODE: -204\nPRP40A in *N type *MEM not found.",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\nSRCDAT   SRCDTA                                                                                              \n-------- ----------------------------------------------------------------------------------------------------\n 220408        *========================================================================*                    \n  41013        * PROGRAM NAME...: PRP40A                                                                     \n  41013        * AUTHOR.........:                                                                            \n  41013        * DATE...........:                                                                            \n  41013        * PCR #..........:                                                                            \n  41013        * FUNCTION/DESC..: PRINT PAYROLL CHECKS - FROM HOLDOVER FILE                                  \n  41013        *------------------------------------------------------------------------                     \n  70110        *    NOTE -
```

**Comment by m-tyler** [comment]
So it works for another member, CLLE. 

![image](https://user-images.githubusercontent.com/1353665/165635543-ce339352-b8dd-410c-94fd-8a80002e42c2.png)

And it seems to work with the same member in a different library.

![image](https://user-images.githubusercontent.com/1353665/165635741-5cb79012-ac8b-4b10-bb6e-4c7638d1f0b6.png)

It just does not like to compare from within my programmer library. 
![image](https://user-images.githubusercontent.com/1353665/165635856-15bdb542-db2b-4dbb-830d-e59ba2de0ebf.png)

**Comment by m-tyler** [comment]
This is working for me!  It work wonderfully. Great addition.
