### ISSUE TITLE
Keep a local copy of source for error recovery

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#648]
**Is your feature request related to a problem? Please describe.**
I received a few errors trying to save a member.  One time it was able to retry and save the member but another time it was not.  I decided that I would just quit VS Code and start over.  However, when I went to open the member from the server it was empty.  

Luckily for me, the changes were minor and easily re-creatable but I would have been a little mad if they were more than this. 

**Describe the solution you'd like**
I can get back my member because I journal my source but I really shouldn't need to if you could keep a local copy that is saved to first and then shipped to the server. 

**Describe alternatives you've considered**
None.

**Additional context**
If a local copy is not viable, consider a TEMP member on the server then remove the to be replace member and rename the temp member.

**Comment by worksofliam** [comment]
Sounds like we need an additional option so the user can configure where to make a copy of the source before we make changes to the member. Sounds like a cool idea.

**Comment by m-tyler** [comment]
Its a LOW pty for me.

**Comment by worksofliam** [comment]
Not something we plan on adding.
