### ISSUE TITLE
DATABASE BROWSER

### ISSUE THREAD

**Issue by robycatta** [halcyon-tech/vscode-ibmi#657]
I have installed the extension and everything works except that nothing appears in the BROWSER DATABASE. Thanks for your help

* QCCSID: 65535
* Features enabled:
   * git: false
   * grep: true
   * tn5250: true
   * setccsid: true
   * GENCMDXML.PGM: false
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: false
* Source dates enabled: false

**Comment by worksofliam** [comment]
The database browser was removed a few versions ago. Seems I forgot to remove the view for it also.

**Comment by robycatta** [comment]
Ah ok thank you!
