### ISSUE TITLE
Source line numbering options

### ISSUE THREAD

**Issue by kgrover3** [halcyon-tech/vscode-ibmi#659]
**Is your feature request related to a problem? Please describe.**
Not all legacy devs are accustomed to the shifted line numbers after saving the source in VS Code with Code for IBM i

**Describe the solution you'd like**
Offer "preferred" numbering settings that are stored in settings.json, but it shouldn't force the user to intervene if those settings don't work for the given source they are trying to save. I think it should just silently use the stepped (size-based) default scheme.

**Describe alternatives you've considered**
Currently I just re-save the source in SEU with the needed numbering settings.

**Additional context**
By default, it chooses based on the number of lines, though the default start is always 1.00 and the increment is the largest of (1.00, 0.10, 0.01) that it can get away with.

**Comment by worksofliam** [comment]
It will change to use decimals if the file is more than 10000 lines long.

![image](https://user-images.githubusercontent.com/3708366/165999410-91ff95d6-44de-424f-810b-0d7df2d04d23.png)
![image](https://user-images.githubusercontent.com/3708366/165999525-9371e030-f572-4fab-8499-eb2f474ca029.png)

**Comment by jkyeung** [comment]
> **Additional context** By default, it chooses based on the number of lines, though the default start is always 1.00 and the increment is the largest of (1.00, 0.10, 0.01) that it can get away with.

Because SEU is limited to 32764 lines in a single member, it never has to increment by 0.01 when renumbering.

I commented on the commit too.
