### ISSUE TITLE
Cursor keys not working on 5250 terminal.

### ISSUE THREAD

**Issue by robinsg** [halcyon-tech/vscode-ibmi#662]
When I open a 5250 terminal from Code for i I am unable to use the up, down, left and right cursor keys. They just seem to print escape character instead of moving the cursor.

I have the 5250 session type set as default except for the language which is set to 285. The matches my user profile language settings . . . the way I have set them for the last 4 decades 🤣.

I'm running VSC on Windows 11.

Any suggestions how I fix the cursor key mappings?

Thanks.

**Comment by worksofliam** [comment]
@robinsg Did you play around with the tn5250 settings in the Connection settings of your connection? I am not sure what might solve it but that might be a good place to start!

**Comment by worksofliam** [comment]
@robinsg Does the same happen if you ssh into the system using another client and then launching tn5250?

**Comment by robinsg** [comment]
No, it works fine.

I use MobaXterm to SSH in to my LPARs. If I then run TS5250 from the SSH
session it works as expected.


Glenn Robinson

IBM Storage and Power Systems Specialist
RSI Consulting Limited
Tel: + 44 7930 946274
Email: ***@***.***

**Comment by richardschoen** [comment]
Must be something about the way the 5250 session starts up from within VS Code. Terminal type possibly ?  I have the same issue if I start a 5250 session directly.  If I open the PASE terminal and then start a 5250 session it works.

**Comment by robinsg** [comment]
I'm wondering if this has anything to do with the shell program when TN5250 is first started. Does VSC run ksh or bash as the shell?

I'm clutching at straws but I'll try your method and report back.

**Comment by worksofliam** [comment]
@robinsg Perhaps it's got something do with the fact I am forcing the users `TERM` to be `xterm`.

Try the following:

* `TERM=xterm /QOpenSys/pkgs/bin/tn5250 ...` to see if you get the same issue
* `/QOpenSys/pkgs/bin/tn5250` to see if the issue goes away.

Maybe I need to remove the hard coded `TERM`.

**Comment by richardschoen** [comment]
Might be worth a try. However see my previous comment. If you exit with Control-Q and run the same sequence with XTERM it works fine the second time when run manually from the same PASE session you started.  Interesting....

**Comment by richardschoen** [comment]
For m personally I just start a PASE session and do this in a start5250.sh script:
`
#!/QopenSys/pkgs/bin/bash
export term=xterm
tn5250 ssl:localhost:992
`

**Comment by worksofliam** [comment]
Hey @robinsg - any update on this? How is it going?

**Comment by robinsg** [comment]
No further progress I'm afraid. I was hoping that putting export TERM=xterm at the top of my .profile file might fix this but no luck.

When I first set up the OSS environments on these LPARs a few years back I used QSYS2.SET_PASE_SHELL_INFO() to set my shell to bash and then set up my .profile and .bashrc files. Any thoughts on that method for setting up the bash environment using that method?

**Comment by BallonLac** [comment]
Exact same problem here, PUB400 untouched profile.

Exiting then launching with `XTERM=xterm ...` thing works fine.
Exiting then launching without any XTERM gives a black-and-white 5250, cursor keys working but no function keys ...

**Comment by worksofliam** [comment]
I believe this issue to be fixed. @robinsg i am going to close the issue, but please feel free to open again if you feel otherwise.
