### ISSUE TITLE
vscode-ibmi not picking up HOMEDIR when connecting to IBM i

### ISSUE THREAD

**Issue by robinsg** [halcyon-tech/vscode-ibmi#668]
When I connect to and of my IBM i LPARs Code for i dispalys a message:

Code for IBM i may not function correctly until your user has a home directory. Please set a home directory using CHGUSRPRF USRPRF(GROBINSO) HOMEDIR('/home/grobinso')

My HOMEDIR is set correctly on all my LPARs.

```
                         Display User Profile - Basic        
                                                             
User profile . . . . . . . . . . . . . . . :   GROBINSO      
                                                             
Home directory . . . . . . . . . . . . . . :   /home/grobinso
```

When I log in via SSH, my session is automatically started in the HOMEDIR so I know it's right.

Any ideas why Code for i is not correctly picking up my HOMEDIRE?

**Comment by worksofliam** [comment]
@robinsg Try sshing into the system yourself and running `pwd`. Paste the result here!

It looks like when `pwd` is called, something is also being written to standard error.

**Comment by robinsg** [comment]
I can't see anything obvious:

```
[grobinso@jedc1-aaa-mgt01 ~]$ ssh kbciast1
grobinso@kbciast1:/home/grobinso $ pwd
/home/grobinso
grobinso@kbciast1:/home/grobinso 
```

**Comment by robinsg** [comment]
Ah, my apologies.

My .bashrc file has a tput command in the PS1 variable. I'd put the export TERM=xterm after the PS1 variable definition which caused the issue.

Simply moved the export TERM before the PS1 definition.

**Comment by worksofliam** [comment]
@robinsg Great job! Thanks for sharing how you solved it.
