### ISSUE TITLE
Add disconnect button to status bar

### ISSUE THREAD

**Issue by merhovon** [halcyon-tech/vscode-ibmi#674]
**Is your feature request related to a problem? Please describe.**
1. To end a current active connection, there is only a shourtcut, better would be a button like " Show Reconnect Button".
2. It would be good if two or more connections could be opened at the same time, so it is easy to copy from one source to another or even comparing two sources would be so much easier.

**Describe the solution you'd like**
1. A button like " Disconnect current active connection".
2. Can open new connection when I use ctrl + ^ so I can compare and copy sources. (Best with function keys not manual)

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by worksofliam** [comment]
A disconnect button would be neat. Perhaps we could add it to the action bar.

We will likely not be adding the ability to have more than one concurrent connection. But, you can open a new VS Code window and have many of those.

**Comment by sebCIL** [comment]
I create the PR #832 for this issue.

**Comment by chrjorgensen** [comment]
Issue has been solved by PR #832 and will be closed.
