### ISSUE TITLE
Cannot connect to V7R5

### ISSUE THREAD

**Issue by samuelexyz** [halcyon-tech/vscode-ibmi#678]
When i try to connect i receive an "Error during setup for ASCII/EBCDIC conversion" 

I try to enable/disable SQL & EBCDIC but i obtain the same error

CCSID is 273

This is the connection log:

.: pwd
{
    "code": 0,
    "signal": null,
    "stdout": "/home/MYPROFILE1",
    "stderr": ""
}

/home/MYPROFILE1: pwd
{
    "code": 0,
    "signal": null,
    "stdout": "/home/MYPROFILE1",
    "stderr": ""
}

/home/MYPROFILE1: /QOpenSys/usr/bin/qsh
liblist
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "Error during setup for ASCII/EBCDIC conversion"
}

/home/MYPROFILE1: system "CRTLIB LIB(MYPROFILE11) TEXT('Code for i temporary objects. May be cleared.')"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "Error during setup for ASCII/EBCDIC conversion"
}

/home/MYPROFILE1: [ -d "/tmp" ]
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/MYPROFILE1: system "CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "Error during setup for ASCII/EBCDIC conversion"
}

/home/MYPROFILE1: system "CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "Error during setup for ASCII/EBCDIC conversion"
}

/home/MYPROFILE1: ls -p /QOpenSys/pkgs/bin/
{
    "code": 0,
    "signal": null,
    "stdout": "2to3\n2to3-3.6\n2to3-3.9\n5250keys\n7z\n7za\n7zr\nR\nRscript\n[\n__pycache__/\naccessdb\naclocal\naclocal-1.15\nacountry\nactivemq\nactivemq-admin\naddftinfo\naddgnupghome\nadig\nadjust-xcoff-header\nafmtodit\nahost\nalternatives\nanacron\nansible\nansible-config\nansible-connection\nansible-console\nansible-doc\nansible-galaxy\nansible-inventory\nansible-playbook\nansible-pull\nansible-test\nansible-vault\nant\nantRun\napplydeltaiso\napplydeltarpm\napplygnupgdefaults\napropos\naria_chk\naria_dump_log\naria_ftdump\naria_pack\naria_read_log\nasn1Coding\nasn1Decoding\nasn1Parser\natob\nautoconf\nautoexpect\nautoheader\nautom4te\nautomake\nautomake-1.15\nautopoint\nautoreconf\nautoscan\nautossh\nautoupdate\nawk\nbase32\nbase64\nbasename\nbash\nbashbug\nbison\nbottle.py\nbrotli\nbsdcat\nbsdcpio\nbsdtar\nbsqldb\nbsqlodbc\nbtoa\nbunzip2\nbzcat\nbzcmp\nbzdiff\nbzegrep\nbzfgrep\nbzgrep\nbzip2\nbzip2recover\nbzless\nbzmore\nc++\nc2ph\nc_rehash\ncal\ncaptoinfo\ncat\ncatman\ncc\nccache\nccmake\ncertutil\nchcon\nchem\nchgrp\nchmod\nchown\nchroot\nchroot_setup\nchsh\ncjpeg\ncksum\nclear\nclusterdb\ncmake\ncmp\ncmsutil\ncol\ncolcrt\ncolrm\ncolumn\ncombinedeltarpm\ncomm\ncorelist\ncp\ncpack\ncpan\ncpio\ncpp\ncpp-6\ncpp-6.bin\ncreatedb\ncreaterepo\ncreateuser\ncrlutil\ncrond\ncronnext\ncrontab\ncsplit\nctest\ncups-config\ncurl\ncurl-config\ncurve_keygen\ncut\ncwebp\ncxpm\ndatacopy\ndate\ndb2util\ndb_archive\ndb_checkpoint\ndb_deadlock\ndb_dump\ndb_hotbackup\ndb_load\ndb_printlog\ndb_recover\ndb_sql\ndb_stat\ndb_upgrade\ndb_verify\ndd\ndebuginfo-install\ndefncopy\nderb\nderdump\ndf\ndiff\ndiff3\ndir\ndircolors\ndirmngr\ndirmngr-client\ndirname\ndislocate\ndjpeg\ndltest\ndos2unix\ndropdb\ndropuser\ndrpmsync\ndu\ndumpsexp\ndvipdf\ndwebp\neasy_install-2.7\necho\necpg\negrep\nenc2xs\nencguess\nenv\nenvsubst\neps2eps\neqn\neqn2graph\nescapesrc\nevent_rpcgen.py\nex\nexpand\nexpect\nexpr\nf2py3.6\nf95\nfactor\nfalse\nfax2ps\nfax2tiff\nfc-cache\nfc-cat\nfc-conflist\nfc-list\nfc-match\nfc-pattern\nfc-query\nfc-scan\nfc-validate\nfgrep\nfile\nfind\nfind-repos-of-install\nfisql\nfix-rpath\nflex\nflex++\nfmt\nfold\nfragiso\nfreebcp\nfunzip\ng++\ng++-6\ng++-6.bin\ngapplication\ngawk\ngcc\ngcc-6\ngcc-6.bin\ngcc-ar\ngcc-ar-6\ngcc-ar-6.bin\ngcc-nm\ngcc-nm-6\ngcc-nm-6.bin\ngcc-ranlib\ngcc-ranlib-6\ngcc-ranlib-6.bin\ngcov\ngcov-6\ngdb\ngdbm_dump\ngdbm_load\ngdbmtool\ngdbus\ngdbus-codegen\ngdiffmk\ngenbrk\ngenccode\ngencfu\ngencmn\ngencnval\ngendict\ngendiff\ngennorm2\ngenrb\ngensprep\ngetopt\ngettext\ngettext.sh\ngettextize\ngfortran\ngfortran-6\ngfortran-6.bin\ngif2rgb\ngifbuild\ngifclrmp\ngifecho\ngiffix\ngifinto\ngiftext\ngiftool\ngio\ngio-querymodules\ngit\ngit-cvsserver\ngit-receive-pack\ngit-shell\ngit-upload-archive\ngit-upload-pack\nglib-compile-resources\nglib-compile-schemas\nglib-genmarshal\nglib-gettextize\nglib-mkenums\nglilypond\ngmake\ngobject-query\ngperf\ngperl\ngpg\ngpg-agent\ngpg-connect-agent\ngpg-error\ngpg-error-config\ngpg-wks-server\ngpgconf\ngpgparsemail\ngpgrt-config\ngpgscm\ngpgsm\ngpgtar\ngpgv\ngpinyin\ngrap2graph\ngrep\ngresource\ngrn\ngrodvi\ngroff\ngroffer\ngrog\ngrolbp\ngrolj4\ngropdf\ngrops\ngrotty\ngroups\ngs\ngsbj\ngsdj\ngsdj500\ngsed\ngsettings\ngslj\ngslp\ngsnd\ngtester\ngtester-report\ngunzip\ngzexe\ngzip\nh2ph\nh2xs\nhardlink\nhb-ot-shape-closure\nhb-shape\nhb-subset\nhb-view\nhead\nhelp2man\nhexdump\nhmac256\nhostid\nhpftodit\niconv\nicu-config\nicuinfo\nicupkg\nid\nidle3\nidle3.6\nidle3.9\nidn2\nifnames\nigawk\nindxbib\ninfo\ninfocmp\ninfotocap\ninitdb\ninnochecksum\ninstall\ninstall-info\ninstmodsh\nipcmk\nisosize\nisql\niusql\njmacs\njoe\njoin\njpegtran\njpico\njq\njson_pp\njstar\nkbxutil\nkill\nksba-config\nless\nlessecho\nlesskey\nlexgrog\nlftp\nlftpget\nlibassuan-config\nlibgcrypt-config\nlibnetcfg\nlibpng-config\nlibpng16-config\nlibtool\nlibtoolize\nlink\nlistsuites\nlkbib\nln\nlocate\nlogname\nlogrotate\nlook\nlookbib\nlp5250d\nlprsetup.sh\nls\nlua\nluac\nlzcat\nlzcmp\nlzdiff\nlzegrep\nlzfgrep\nlzgrep\nlzip\nlzless\nlzma\nlzmadec\nlzmainfo\nlzmore\nm4\nmac2unix\nmake\nmakeconv\nmakedeltaiso\nmakedeltarpm\nmakeinfo\nman\nman-recode\nmandb\nmanpath\nmc\nmcdiff\nmcedit\nmcookie\nmcview\nmd5sum\nmergerepo\nmesg\nminisign\nmkdir\nmkfifo\nmknod\nmktemp\nmmroff\nmodifyrepo\nmodutil\nmpicalc\nmsgattrib\nmsgcat\nmsgcmp\nmsgcomm\nmsgconv\nmsgen\nmsgexec\nmsgfilter\nmsgfmt\nmsggrep\nmsginit\nmsgmerge\nmsgunfmt\nmsguniq\nmsql2mysql\nmv\nmvn\nmvnDebug\nmvnyjp\nmy_print_defaults\nmyisam_ftdump\nmyisamchk\nmyisamlog\nmyisampack\nmysql\nmysql_convert_table_format\nmysql_find_rows\nmysql_fix_extensions\nmysql_install_db\nmysql_plugin\nmysql_secure_installation\nmysql_setpermission\nmysql_tzinfo_to_sql\nmysql_upgrade\nmysql_waitpid\nmysqlaccess\nmysqladmin\nmysqlbinlog\nmysqlcheck\nmysqld\nmysqld_multi\nmysqld_safe\nmysqld_safe_helper\nmysqldump\nmysqldumpslow\nmysqlhotcopy\nmysqlimport\nmysqlshow\nmysqlslap\nmytop\nnamei\nnano\nncdu\nncurses6-config\nncursesw6-config\nneeds-restarting\nneqn\nngettext\nnginx\nnice\nninja\nnl\nnode\nnodever\nnohup\nnologin\nnpm\nnproc\nnpth-config\nnpx\nnroff\nnspr-config\nnss-config\nnss-policy-check\nnumfmt\nocspclnt\nod\nodbc_config\nodbcinst\noid2name\nonig-config\nopenssl\nosql\np11-kit\npackage-cleanup\npal2rgb\npango-view\npaste\npatch\npathchk\npcre-config\npcre2-config\npcre2grep\npcre2test\npcregrep\npcretest\npdf2dsc\npdf2ps\npdfmom\npdfroff\npdftexi2dvi\nperl\nperl5.24.1\nperlbug\nperldoc\nperlivp\nperlthanks\nperror\npf2afm\npfbtopfa\npfbtops\npg_archivecleanup\npg_basebackup\npg_checksums\npg_config\npg_controldata\npg_ctl\npg_dump\npg_dumpall\npg_isready\npg_receivewal\npg_recvlogical\npg_resetwal\npg_restore\npg_standby\npg_test_fsync\npg_test_timing\npg_upgrade\npg_waldump\npgbench\npic\npic2graph\npiconv\npigz\npinentry\npinentry-curses\npinky\npip2\npip2.7\npip3\npip3.6\npip3.9\npk12util\npkg-config\npkgdata\npl2pm\npng-fix-itxt\npngfix\npod2html\npod2man\npod2texi\npod2text\npod2usage\npodchecker\npodselect\npost-grohtml\npostgres\npostmaster\npowerpc-ibm-os400-pkg-config\npp\npphs\nppm2tiff\npr\npre-grohtml\npreconv\nprintafm\nprintenv\nprintf\nprotoc\nprove\nps2ascii\nps2epsi\nps2pdf\nps2pdf12\nps2pdf13\nps2pdf14\nps2pdfwr\nps2ps\nps2ps2\npsql\npstruct\nptar\nptardiff\nptargrep\nptx\npv\npwd\npydoc\npydoc3\npydoc3.6\npydoc3.9\npython\npython2\npython2-config\npython2.7\npython2.7-config\npython3\npython3-config\npython3.6\npython3.6-config\npython3.6m\npython3.6m-config\npython3.9\npython3.9-config\npyvenv-3.6\nraw2tiff\nrdjpgcom\nreadlink\nrealpath\nrecode-sr-latin\nredis-benchmark\nredis-check-aof\nredis-check-rdb\nredis-cli\nredis-sentinel\nredis-server\nrefer\nreindexdb\nrename\nrenice\nreplace\nrepo-graph\nrepo-rss\nrepoclosure\nrepodiff\nrepomanage\nrepoquery\nreposync\nrepotrack\nreset\nresolve_stack_dump\nresolveip\nrev\nrftp\nrjoe\nrm\nrmdir\nrnano\nroff2dvi\nroff2html\nroff2pdf\nroff2ps\nroff2text\nroff2x\nrpm\nrpm2archive\nrpm2cpio\nrpmargs\nrpmbuild\nrpmdb\nrpmdev-bumpspec\nrpmdev-checksig\nrpmdev-cksum\nrpmdev-diff\nrpmdev-extract\nrpmdev-md5\nrpmdev-packager\nrpmdev-rmdevelrpms\nrpmdev-setuptree\nrpmdev-sha1\nrpmdev-sha224\nrpmdev-sha256\nrpmdev-sha384\nrpmdev-sha512\nrpmdev-sort\nrpmdev-sum\nrpmdev-vercmp\nrpmdev-wipetree\nrpmdumpheader\nrpmfile\nrpmgraph\nrpmkeys\nrpmls\nrpmpeek\nrpmquery\nrpmsign\nrpmspec\nrpmverify\nrsync\nrsync-ssl\nrun-parts\nrunant.py\nruncon\nruntest\nrview\nrvim\nsc\nsc_install_defaults\nscedit\nscinit\nscopenports\nscp\nscs2ascii\nscs2pdf\nscs2ps\nsdiff\nsed\nselfserv\nseq\nsetsid\nsftp\nsha1sum\nsha224sum\nsha256sum\nsha384sum\nsha512sum\nshasum\nshow-changed-rco\nshow-installed\nshowrgb\nshred\nshuf\nsigntool\nsignver\nsleep\nslencheck\nslsh\nsmtpd.py\nsoelim\nsort\nspectool\nsplain\nsplit\nsqlite3\nsqlite3_analyzer\nssh\nssh-add\nssh-agent\nssh-copy-id\nssh-keygen\nssh-keyscan\nsshpass\nssltap\nstat\nstatic-to-shared\nstdbuf\nstrsclnt\nstty\nsum\nsvr4-shrlib\nsxpm\nsymkeyutil\nsync\ntabs\ntac\ntail\ntar\ntbl\ntclsh8.6\ntdspool\ntee\ntest\ntexi2any\ntexi2dvi\ntexi2pdf\ntexindex\ntfmtodit\ntic\ntiff2bw\ntiff2pdf\ntiff2ps\ntiff2rgba\ntiffcmp\ntiffcp\ntiffcrop\ntiffdither\ntiffdump\ntiffinfo\ntiffmedian\ntiffset\ntiffsplit\ntimed-read\ntimed-run\ntimeout\ntjbench\ntmux\ntn5250\ntoe\ntouch\ntput\ntr\ntree\ntroff\ntrue\ntruncate\ntrust\ntset\ntsort\ntsql\ntstclnt\ntty\nuconv\nuname\nunbuffer\nuncompress\nunexpand\nuniq\nunix-lpr.sh\nunix2dos\nunix2mac\nunlink\nunlzma\nunpigz\nunxz\nunzip\nunzipsfx\nunzstd\nupdate-alternatives\nupdate-ca-certificates\nupdatedb\nuptime\nurlgrabber\nusers\nuuidgen\nuuidparse\nvacuumdb\nvacuumlo\nvdir\nverifytree\nvfychain\nvfyserv\nview\nvim\nvimdiff\nvimtutor\nwatchgnupg\nwc\nwget\nwhatis\nwheel\nwhereis\nwho\nwhoami\nwish8.6\nwrjpgcom\nxargs\nxgettext\nxml2-config\nxmlcatalog\nxmllint\nxmlservice-cli\nxmlwf\nxslt-config\nxsltproc\nxsubpp\nxt5250\nxxd\nxz\nxzcat\nxzcmp\nxzdec\nxzdiff\nxzegrep\nxzfgrep\nxzgrep\nxzless\nxzmore\nyacc\nyat2m\nyes\nyum\nyum-builddep\nyum-complete-transaction\nyum-config-manager\nyum-debug-dump\nyum-debug-restore\nyum-groups-manager\nyumdb\nyumdownloader\nzcat\nzcmp\nzdiff\nzegrep\nzfgrep\nzforce\nzgrep\nzip\nzipcloak\nzipcmp\nzipdetails\nzipgrep\nzipinfo\nzipmerge\nzipnote\nzipsplit\nziptool\nzless\nzmore\nznew\nzstd\nzstdcat\nzstdgrep\nzstdless\nzstdmt",
    "stderr": ""
}

/home/MYPROFILE1: ls -p /usr/bin/
{
    "code": 0,
    "signal": null,
    "stdout": "Rfile\najar\nappletviewer\napt\narmsrv\narmsrvconv\nattr\nbasename\nbash\ncat\ncatsplf\nchgrp\nchmod\nchown\nclrtmp\ncmp\ncompress\ncp\ncut\ndataq\ndatarea\ndate\ndb2\ndb2profc\ndb2profc_trace\ndb2profp\nddns-confgen\ndelv\ndfmadmin\ndhcpd\ndhcrelay\ndig\ndirname\ndnssec-dsfromkey\ndnssec-importkey\ndnssec-keyfromlabel\ndnssec-keygen\ndnssec-revoke\ndnssec-settime\ndnssec-signzone\ndnssec-verify\ndspmsg\necho\negrep\nenv\nexpr\nextcheck\nfgrep\nfile\nfind\ngencat\ngetjobid\ngrep\nhead\nhost\nhostname\nhttpapi\nhwkeytool\niconv\nid\nidlj\nikeyman\nipcrm\nipcs\nixlc\njar\njarsigner\njava\njavac\njavadoc\njavah\njavap\njconsole\njdb\njdmpview\njextract\nkdestroy\nkeytab\nkeytool\nkinit\nklist\nkpasswd\nksetup\nldapadd\nldapchangepwd\nldapcompare\nldapdelete\nldapdiff\nldapexop\nldapmodify\nldapmodrdn\nldapsearch\nln\nlocale\nlogger\nlogname\nls\nmkdir\nmkfifo\nmv\nnamed\nnamed-checkconf\nnamed-checkzone\nnamed-compilezone\nnamed-journalprint\nnamed-rrchecker\nnative2ascii\nnohup\nnslookup\nnsupdate\nod\norbd\npack200\npax\npolicytool\npr\nprintenv\nprofconv\nprofdb\nprofp\nps\npwd\npwdx\nqsh\nrexec\nrexx\nrm\nrmdir\nrmic\nrmid\nrmiregistry\nrndc\nrndc-confgen\nschemagen\nsed\nserialver\nservertool\nsetccsid\nsh\nsort\nsplit\nsqlj\nstrEKM\nsystem\nsysval\ntail\ntar\ntee\ntest\ntnameserv\ntouch\ntr\ntsig-keygen\nuname\nuncompress\nuniq\nunpack200\nwc\nwsgen\nwsimport\nxargs\nxjc\nzcat",
    "stderr": ""
}

/home/MYPROFILE1: ls -p /QSYS.LIB/QZDFMDB2.PGM
{
    "code": 0,
    "signal": null,
    "stdout": "/QSYS.LIB/QZDFMDB2.PGM",
    "stderr": ""
}

/home/MYPROFILE1: ls -p /QSYS.lib/MYPROFILE11.lib/*.PGM
{
    "code": 0,
    "signal": null,
    "stdout": "/QSYS.lib/MYPROFILE11.lib/EMPPGM.PGM\n/QSYS.lib/MYPROFILE11.lib/HELLO.PGM\n/QSYS.lib/MYPROFILE11.lib/HELLOF.PGM\n/QSYS.lib/MYPROFILE11.lib/HELLOP.PGM\n/QSYS.lib/MYPROFILE11.lib/LIBRIG1.PGM\n/QSYS.lib/MYPROFILE11.lib/LIBRIG2.PGM\n/QSYS.lib/MYPROFILE11.lib/LIBRIP0.PGM\n/QSYS.lib/MYPROFILE11.lib/LIBRIP1.PGM\n/QSYS.lib/MYPROFILE11.lib/TESTCL.PGM\n/QSYS.lib/MYPROFILE11.lib/TESTFIL.PGM",
    "stderr": ""
}

/home/MYPROFILE1: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
SELECT * FROM QSYS2.ASP_INFO
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "Error during setup for ASCII/EBCDIC conversion"
}

/home/MYPROFILE1: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i')"
select SYSTEM_VALUE_NAME, CURRENT_NUMERIC_VALUE from QSYS2.SYSTEM_VALUE_INFO where SYSTEM_VALUE_NAME = 'QCCSID'
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "Error during setup for ASCII/EBCDIC conversion"
}

**Comment by SJLennon** [comment]
@samuelexyz 
I'm seeing a similar issue on PUB400.COM.  It might be a problem with `/QOpenSys/usr/bin/qsh`.  It is a SYMLNK to `../../QIBM/ProdData/OS400/PASE/bin/qsh` . Not sure  what the ../.. is all about.

I tried this in PuTTY and got the same error:

```
(/home/LENNONS)->
(/home/LENNONS)->/QOpenSys/usr/bin/qsh liblist
Error during setup for ASCII/EBCDIC conversion
(/home/LENNONS)->

```

**Comment by SJLennon** [comment]
In my case, I do connect to PUB400.COM, but I get an and error like this:
![image](https://user-images.githubusercontent.com/67484051/169865661-c7148604-f446-4a9d-bae1-9e9a5e8d2232.png)
I'm pretty sure I've had it working since PUB400.COM went to V7.5.
Now I cannot open any of my filters:

```
/home/LENNONS: system "DSPFD FILE(LENNONS1/*ALL) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(LENNONS2/O_RcvnJckn)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "Error during setup for ASCII/EBCDIC conversion"
}

```
Using the WRKLNK path, more PuTTY feedback:
```(/home/LENNONS)->
(/home/LENNONS)->/QIBM/ProdData/OS400/PASE/bin/qsh
Error during setup for ASCII/EBCDIC conversion
(/home/LENNONS)->/QIBM/ProdData/OS400/PASE/bin/qsh liblist
Error during setup for ASCII/EBCDIC conversion
(/home/LENNONS)->
```

**Comment by worksofliam** [comment]
Totally weird. I've never seen this error.

**Comment by worksofliam** [comment]
@SJLennon are you seeing this with 7.5 consistently?

**Comment by SJLennon** [comment]
@worksofliam Yes. I'm getting the error consistently on PUB400.  I think after V7.5 was installed I did a little work successfully, but I'm not sure, because I haven't done much for a few days, until yesterday (for various reasons).
I had hoped that @samuelexyz would mention a bit more about his machine, and wondered if it was PUB400.

I am curious about "/QOpenSys/usr/bin/qsh. It is a SYMLNK to ../../QIBM/ProdData/OS400/PASE/bin/qsh" mentioned above.  Do you know how it looks on a non-v7.5 machine or a non PUB400 machine?

**Comment by worksofliam** [comment]
QSH on my 7.4 box and it looks the same.

```
lrwxrwxrwx  1 qsys  0     76 Mar  9  2016 qsh -> ../../QIBM/ProdData/OS400/PASE/bin/qsh
```

**Comment by worksofliam** [comment]
I also don't think this issue is related to 7.5. It's some misconfiguration somewhere.

**Comment by worksofliam** [comment]
@SJLennon Can you run `set` on fresh pub400 connection and share the resulting environment variables?

**Comment by SJLennon** [comment]
@worksofliam  Possibly something is up with PUB400.

Can you try  WRKENVVAR LEVEL(*JOB) on V7.4

On PUB400 it is this, which seems a little different from what we have in the documentation:
```
Opt  Name                        Value                    
                                                          
     PASE_USRGRP_LIMITED         'N'                      
     QIBM_PASE_USE_PRESTART_J >  'Y'                      
     LANG                        '/QSYS.LIB/EN_US.LOCALE' 
```

**Comment by samuelexyz** [comment]
@SJLennon  @worksofliam  yes i'm trying to PUB400, I think the issue are related to this IBM change

https://www.ibm.com/docs/en/i/7.4?topic=system-default-pase-ccsid-locale-changed-utf-8

but i'm not sure i'm doing some test to find out a workaround

**Comment by ThePrez** [comment]
Hmmm.. 
Howsabout this?
```
/QOpenSys/pkgs/bin/python2.7  -c "import ctypes;print(ctypes.CDLL('libc.a(shr_64.o)', 0x00040000).Qp2jobCCSID())"
```

**Comment by samuelexyz** [comment]
@ThePrez CCSID is 273

**Comment by SJLennon** [comment]
Agreed for PUB400:
```
(/home/LENNONS)->/QOpenSys/pkgs/bin/python2.7  -c "import ctypes;print(ctypes.CDLL('libc.a(shr_64.o)', 0x00040000).Qp2jobCCSID())"
273
(/home/LENNONS)->
```

**Comment by samuelexyz** [comment]
@worksofliam  

I post my test result, i take some peace of code and i get a working example:


`const node_ssh = require(`node-ssh`);


async function sendQsh(client, options) {
    let qshCommand;

    if (Array.isArray(options.command)) {
        qshCommand = options.command.join(`;`);
    } else {
        qshCommand = options.command;
    }

    options.stdin = qshCommand;

    return sendCommand(client, {
        ...options,
        command: `bash`
    });
}

async function sendCommand(client, options) {
    const command = options.command;
    const directory = '<<MYHOMEDIR>>';


    const result = await client.execCommand(command, {
        cwd: directory,
        stdin: options.stdin,
        onStdout: options.onStdout,
        onStderr: options.onStderr,
    });

    // Some simplification
    if (result.code === null) result.code = 0;

    console.dir(JSON.stringify(result, null, 4) + `\n\n`);



    return result;
}

async function testLibList() {

    const connectionObject = {};
    connectionObject.keepaliveInterval = 35000;
    connectionObject.name = 'pub400.com';
    connectionObject.host = 'pub400.com';
    connectionObject.port = 2222;
    connectionObject.username = '<<<MYUSERNAME>>>';
    connectionObject.password = '<<<MYPASSWORD>>>';

    const client = new node_ssh.NodeSSH;

    await client.connect(connectionObject);

    const liblResult = await sendQsh(client, {
        command: `liblist`
    });

}

testLibList().catch((error) => {
    console.error(error);
});`

i replace /QOpenSys/pkgs/bin/sh with bash now it's working

**Comment by ThePrez** [comment]
`liblist` is now [a bash builtin](https://kadler.io/2020/12/23/bash-builtins.html) so using bash should circumvent this singular liblist problem. The underlying conversion issue still remains, unfortunately. 

This might be related to some unconventional ILE environment setup (I'm looking at you, `QIBM_USE_DESCRIPTOR_STDIO`)

Yet another info-gathering step:
```
system "DSPJOB OPTION(*ENVVAR)" | grep QIBM
```

**Comment by samuelexyz** [comment]
@ThePrez i see not working 

from ssh

![image](https://user-images.githubusercontent.com/10728037/170080111-45ae27ff-de44-48ce-aaf4-df2224b99c25.png)


from qsh 5250

![image](https://user-images.githubusercontent.com/10728037/170080315-3bc96c6c-e144-4493-aae4-d9e3807bd080.png)


From printenv on bash

bash-5.1$ printenv    
SHELL=/QOpenSys/usr/bin/bsh
PWD=/home/SRENATI
LOGNAME=srenati
TZ=<UTC>0
HOME=/home/SRENATI
SSH_CONNECTION=213.187.6.248 57681 185.113.5.134 2222
TERM=xterm-256color
USER=srenati
LOGIN=srenati
SHLVL=1
PASE_USRGRP_LIMITED=N
SSH_CLIENT=213.187.6.248 57681 2222
PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
MAIL=/var/spool/mail/srenati
SSH_TTY=/dev/pts/5
_=/QOpenSys/usr/bin/printenv

**Comment by SJLennon** [comment]
FWIW:  

`system `"DSPJOB OPTION(*ENVVAR)" | grep QIBM`

will not work in QSH unless I change my job CCSID from 273 to 37, because the  | has a different code point in 273

**Comment by SJLennon** [comment]
@worksofliam @ThePrez 
Another FWIW, where I start QP2TERM, then start QSH inside it using the SYMLNK. target of /QOpenSys/usr/bin/qsh.

Things work in this situation and  I can issue the liblist and system commands.

```
                                                      /QOpenSys/usr/bin/-sh   
                                                                              
  ----End of .Profile                                                         
  (/home/LENNONS)->                                                           
> /QIBM/ProdData/OS400/PASE/bin/qsh                                           
  $                                                                           
> liblist                                                                     
  PUB400SYS   SYS                                                             
  QSYS        SYS                                                             
  QSYS2       SYS                                                             
  QUSRSYS     SYS                                                             
  QHLPSYS     SYS                                                             
  LENNONS1    CUR                                                             
  LENNONS1    USR                                                             
  LENNONS2    USR                                                             
  QTEMP       USR                                                             
  QGPL        USR                                                             
  $                                                                           
> system dsplibl     
                                                       /QOpenSys/usr/bin/-sh                                                      
                                                                                                                                  
     5770SS1 V7R5M0  220415                    Library List                                          5/24/22 21:23:33        Page 
    1                                                                                                                             
                              ASP                                                                                                 
       Library     Type       Device      Text Description                                                                        
       PUB400SYS   SYS                    $ PUB400.COM global programs                                                            
       QSYS        SYS                    System Library                                                                          
       QSYS2       SYS                    System Library for CPI's                                                                
       QUSRSYS     SYS                    System Library for Users                                                                
       QHLPSYS     SYS                                                                                                            
       LENNONS1    CUR                    LENNONS (*CURLIB)                                                                       
       LENNONS1    USR                    LENNONS (*CURLIB)                                                                       
       LENNONS2    USR                    LENNONS (second)                                                                        
       QTEMP       USR                                                                                                            
       QGPL        USR                    General Purpose Library                                                                 
                              * * * * *  E N D  O F  L I S T I N G  * * * * *                                                     
                                                       -=* http://pub400.com *=-                                                  
   $                                                                                                                              
> exit                 
  (/home/LENNONS)->    
                                                                                                                                                         
 ===>                                                                                                                                                                                      
```
Not sure what this tells us, and what to fix on PUB400 eludes me.

**Comment by SJLennon** [comment]
@worksofliam @ThePrez 

And another FWIW:

In a CCSID 273 job, startingQP2TERM, and runing QSH, these are the env variables:

```
 system "DSPJOB OPTION(*ENVVAR)" ] grep QIBM          
   QIBM_IFS_OPEN_MAX                       '66000'    
   QIBM_PASE_CCSID                         '1208'     
   QIBM_PASE_DESCRIPTOR_STDIO              'T'        
   QIBM_USE_DESCRIPTOR_STDIO               'Y'        
   QIBM_PASE_USE_PRESTART_JOBS             'Y'        
   QIBM_DESCRIPTOR_STDERR                  'CRLN=N'   
   QIBM_DESCRIPTOR_STDOUT                  'CRLN=N'   
   QIBM_DESCRIPTOR_STDIN                   'CRLN=Y'   
   _                                       'QIBM'     
```

**Comment by ThePrez** [comment]
Is the bash version installed (`yum list bash`) at version 5.1-2?

**Comment by ThePrez** [comment]
I was able to get onto pub400 and the good news is that this is easily recreatable. I didn't realize how easy it is to recreate. Any `qsh` invocation, basically, exhibits at least the EBCDIC error

**Comment by ThePrez** [comment]
OK, it looks like the error is not directly related to EBCDIC/ASCII conversion, that's just a side effect. One can verify by running data through `/QOpenSys/usr/bin/iconv` with the needed to/from CCSIDs and observe that it works. 

It looks like the subsystem is running in single-threaded mode and all jobs are therefore contained to single-threaded. The qsh CCSID conversions rely on multiple threads to perform the bidirectional conversions. 

I believe resolution is to change QUSRWRK to run in multi-threaded mode, as indirectly discussed in this doc
https://www.ibm.com/support/pages/subsystem-single-or-multiple-threads

**Comment by ThePrez** [comment]
^^ More likely, a CHGJOBD is required to set `ALWMLTTHD`

**Comment by ThePrez** [comment]
Confirmed... Job description for QDFTSVR is

>  Allow multiple threads  . . . . . . . . . . . . . :   *NO

Fix for the problem is
```
CHGJOBD JOBD(QGPL/QDFTSVR) ALWMLTTHD(*YES)
```

**Comment by ThePrez** [comment]
Thanks to Pub400 admins, should be fixed. Please try now. Thanks!

**Comment by SJLennon** [comment]
@ThePrez 
Yep, it work now for me.
Well, that was a weird one!

**Comment by samuelexyz** [comment]
@ThePrez
it working

Thanks
