### ISSUE TITLE
Error on open object browser

### ISSUE THREAD

**Issue by wserpas** [halcyon-tech/vscode-ibmi#680]
When I try to click on object browser, I receive an error:
**Error during setup for ASCII/EBCDIC conversion**

* QCCSID: 273
* Features enabled:
   * git: true
   * grep: true
   * tn5250: true
   * setccsid: true
   * GENCMDXML.PGM: false
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: false

**Comment by worksofliam** [comment]
Dupe of #678
