### ISSUE TITLE
Error during setup for ASCII/EBCDIC

### ISSUE THREAD

**Issue by christianlarsen** [halcyon-tech/vscode-ibmi#681]
I'm trying to connect to pub400 ...

First thing that I have, is some kind of problem with the "temporary library"...

I receive a message:

![image](https://user-images.githubusercontent.com/504668/170100828-275f653d-3a86-4ee4-97ff-848e6e86fed6.png)

After that, when I'm trying to make a deploy, or open a QRPGLESRC member, I'm receiving a message...

![image](https://user-images.githubusercontent.com/504668/170101141-c936f809-0d15-46ed-a0ee-9cb80c829dc3.png)

Any idea?  

* QCCSID: null
* Features enabled:
   * git: true
   * grep: true
   * tn5250: true
   * setccsid: true
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: true

**Comment by GeorgeJeffcock** [comment]
ditto...

Weird two IBM i  users in a matter of minutes

I saw this also: https://github.com/microsoft/vscode/issues/150200

**Comment by worksofliam** [comment]
Dupe of #678
