### ISSUE TITLE
Color coding text in specific IBM i source member files

### ISSUE THREAD

**Issue by kellycookson** [halcyon-tech/vscode-ibmi#683]
I really like the IBM i extensions for VS code! However, I am experiencing some difficulties with color coding of text when IBM i source members have certain file name extensions:
  *.cblle
  *.sqlcblle
  *.sqlsp
  *.sqlprc
  *.sqltabl
  *.sqlindx
  *.sqltrg
The text of these source member files has no color coding. The text within them is all the same color.

I downloaded a PL/SQL color coding extension for VS Code. I then set the following in my VS Code settings.json file:
    "files.associations": {
        "*.sqlsp": "sql",
        "*.sqlprc": "sql",
        "*.sqltabl": "sql",
        "*.sqlindx": "sql",
        "*.sqltrg": "sql",
        "*.cblle": "cobol",
        "*.sqlcblle": "cobol"
      }
This resulted in the PL/SQL extension adding color coding my SQL source member files. But the language value of “cobol” did not work. The text of *.cblle and *.sqlcblle source member files continues to be all white. What am I missing?

**Comment by SJLennon** [comment]
@kellycookson 
Color highlighting is provided by this separate extension.  It's normally enabled automatically, but you might want to check your extensions.
![image](https://user-images.githubusercontent.com/67484051/170532075-b156881a-8ea1-48e5-9225-a04677c866a0.png)

**Comment by worksofliam** [comment]
COBOL is provided by another extension. Try this: https://marketplace.visualstudio.com/items?itemName=bitlang.cobol

**Comment by worksofliam** [comment]
@kellycookson 

1. Open the source up with the weird extension
2. Press F1 and search 'Change Language Mode'
3. Select 'Configure File Association for ...'

<img width="759" alt="image" src="https://user-images.githubusercontent.com/3708366/170723514-ac45b167-55f1-41bb-a201-59ffbcf9b07e.png">

**Comment by kellycookson** [comment]
Thanks. I asked the owner of the BitLang COBOL extension (vscode_cobol) to add the IBM i extensions to the bitlang cobol extension. They got it added already. The BitLang COBOL extension now recognizes the *.cblle, *sqlcblle, and *.cblcpy file name extensions for IBM i source members.

**Comment by worksofliam** [comment]
@kellycookson Glad to hear that! bitlang.cobol has been very kind to our users by quickly solving little bits like that.

Can we close this issue for the time being?

**Comment by kellycookson** [comment]
Yes. Please close this. Thanks again.
