### ISSUE TITLE
Regression: Unable to open qprglesrc folder in version 1.3.3

### ISSUE THREAD

**Issue by mdgozza** [halcyon-tech/vscode-ibmi#684]
**Describe the bug**
In version 1.3.0 ( when I downgrade ) I am able to correctly open the qprglesrc folder
<img width="426" alt="image" src="https://user-images.githubusercontent.com/9098106/170388128-739735b8-b524-494c-8429-3ddb71712bfe.png">

In version 1.3.3 ( latest ) I am unable to open the qrpglesrc folder.
![image](https://user-images.githubusercontent.com/9098106/170388111-479e8d52-a8ac-43d0-881d-83c672ce6ba0.png)

**To Reproduce**
Understandably reproducing this will be tricky, so instead I will list out all of the things
that I think are unique to my environment and that may be related.
my `sourceASP` setting is custom and
my `sourceFileCCSID` is 37

Beyond those two things I am not really sure if there is anything unique?

**Expected behavior**
It is expected that I can view the source files under the qrpglesrc folder.

**Environment (please complete the following information):**
 - Extension versions listed above
 - IBM i OS version 7.x

**Additional context**
Apologies I do not know much about things in the i world, please let me know what additional information I can provide to help! Thanks! Love the extension!!!

**Comment by worksofliam** [comment]
@mdgozza You need to use `*SRCPF` in the filter to open source now.
