### ISSUE TITLE
Moving IFS Objects

### ISSUE THREAD

**Issue by HenryMiller** [halcyon-tech/vscode-ibmi#685]
Hello,
I am unable to perform moving and copying objects from IFS Browser .
Beste regards,
Giovanni

* QCCSID: 65535
* Features enabled:
   * git: true
   * grep: true
   * tn5250: true
   * setccsid: true
   * GENCMDXML.PGM: false
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: false
* Source dates enabled: false

<img width="274" alt="image" src="https://user-images.githubusercontent.com/1829995/170640865-97f6b555-6a20-4ee1-b589-071f8642de6e.png">

**Comment by worksofliam** [comment]
I wonder if this has something to do with `QNTC`.

**Comment by HenryMiller** [comment]
I think so. It works fine in all other folders

**Comment by worksofliam** [comment]
@HenryMiller So I've been looking into this and I don't think it's a Code for IBM i problem. I get the same result when I do the same thing in pase.
