### ISSUE TITLE
Update text

### ISSUE THREAD

**Issue by HenryMiller** [halcyon-tech/vscode-ibmi#686]
Hi, 

I get "Error changing member text! CPD0071" when updating source member text.

Thank you.

* QCCSID: 65535
* Features enabled:
   * git: true
   * grep: true
   * tn5250: true
   * setccsid: true
   * GENCMDXML.PGM: false
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: false
* Source dates enabled: false

<img width="728" alt="image" src="https://user-images.githubusercontent.com/1829995/170814557-69649527-1a25-4789-b539-bd3f3fd80851.png">

**Comment by worksofliam** [comment]
@HenryMiller what text value are you trying?

**Comment by HenryMiller** [comment]
Source Member  Text.
<img width="267" alt="image" src="https://user-images.githubusercontent.com/1829995/170835878-b09c23d7-3988-489a-810f-1359f9946c76.png">

**Comment by worksofliam** [comment]
@HenryMiller Right, but what value did you try and set it to? Thanks

**Comment by HenryMiller** [comment]
Values is:  "POST:getDocNo".
Any value I try to type gives me the same error.
All members have the same problem, so I open a 5250 session, run STRPDM and update text member from there.
I'm on MAC Monterey.

<img width="144" alt="image" src="https://user-images.githubusercontent.com/1829995/170914730-bf9f7a7a-d7d1-472c-9e75-c51f7c3df7e0.png">

**Comment by worksofliam** [comment]
@HenryMiller After you try and update the text, please send the output in the Code for IBM i Output channel:

As you can see here, it works for me.

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/3708366/171069546-34eb8920-2d8c-48ec-9750-fbeb5afe8308.png">

**Comment by HenryMiller** [comment]
Here is the log I get .

/home/novtechspa/testgit/: system "CHGPFM FILE(IASP01/BMS71L_SRC) MBR() TEXT('POST: skuSearchx')"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPD0071: È necessario il parametro MBR.\nCPF0006: Si sono verificati errori nel comando."
}

.: system "CPYTOSTMF FROMMBR('/IASP01/QSYS.lib/BMS71L_SRC.lib/QSRC.file/PXAPICGICN.mbr') TOSTMF('/tmp/vscodetemp-O_ccl2DbVA') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPFA0A9: L'oggetto non è stato trovato. L'oggetto è /IASP01/QSYS.lib/BMS71L_SRC.lib/QSRC.file/PXAPICGICN.mbr.\nCPFA097: Oggetto non copiato. L'oggetto è /IASP01/QSYS.lib/BMS71L_SRC.lib/QSRC.file/PXAPICGICN.mbr."
}

.: system "CPYTOSTMF FROMMBR('/IASP01/QSYS.lib/BMS71L_SRC.lib/VSCODE.file/RPGLINT.mbr') TOSTMF('/tmp/vscodetemp-O_VUId0ruJ') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPFA0A9: L'oggetto non è stato trovato. L'oggetto è /IASP01/QSYS.lib/BMS71L_SRC.lib/VSCODE.file/RPGLINT.mbr.\nCPFA097: Oggetto non copiato. L'oggetto è /IASP01/QSYS.lib/BMS71L_SRC.lib/VSCODE.file/RPGLINT.mbr."
}

.: system "CPYTOSTMF FROMMBR('/IASP01/QSYS.lib/BMS71L_SRC.lib/VSCODE.file/RPGLINT.mbr') TOSTMF('/tmp/vscodetemp-O_VUId0ruJ') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPFA0A9: L'oggetto non è stato trovato. L'oggetto è /IASP01/QSYS.lib/BMS71L_SRC.lib/VSCODE.file/RPGLINT.mbr.\nCPFA097: Oggetto non copiato. L'oggetto è /IASP01/QSYS.lib/BMS71L_SRC.lib/VSCODE.file/RPGLINT.mbr."
}

**Comment by worksofliam** [comment]
@HenryMiller Thanks! Yes, it was the ASP. I have pushed a fix but it won't be available until I do a release.

**Comment by HenryMiller** [comment]
Thank you for fixing it!
