### ISSUE TITLE
Menu item for running actions

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#694]
* `menus`:
* `      "editor/title": [`

**Comment by openmax** [comment]
Better : "Button Menu for running actions" ?

**Comment by worksofliam** [comment]
@openmax I'd be curious to hear what your ideas are to improve the actions workflow.

**Comment by openmax** [comment]
as starting point i'd like this extension for vscode -> https://marketplace.visualstudio.com/items?itemName=jerrygoyal.shortcut-menu-bar  
and relative github -> https://github.com/GorvGoyl/Shortcut-Menu-Bar-VSCode-Extension

where you can configure fixes button 1 to 9 to  your prefered actions ..
and there are already button for "save" , "undo", "cut" , "copy" etc etc 

as evolution 
where we have multiple choise for ctrl-e , maybe we can have a button that open a submenu 
( or sub-button ) , like in then microsoft ribbon of office ..

here some already asked example on vscode : https://github.com/microsoft/vscode/issues/41309

**Comment by worksofliam** [comment]
Sadly it's not possible to dynamically add to those icons. While it would be neat, there is no pretty way to go about it right now.

**Comment by worksofliam** [comment]
@openmax I think our 'runAction' command needs to let you pass in a parm so you can click the button and it will search for the action.

For example, for that extension:

* `code-for-ibmi.runAction|CRTBNDRPG`
* `code-for-ibmi.runAction|CRTSRVPGM`

then it would search and use the first action to match the type, extension, and name provided in the argument.

What do you think?

**Comment by openmax** [comment]
@worksofliam that is a good idea , so i can put in the button configuration comand parameter to solve particulary compile need , 
like RPGPPOPT(*LVL2) , TGTRLS(V7R2M0) or ALWNULL(*USRCTL) ..., and have more button for the same COMMAND but with the option i want ..

**Comment by worksofliam** [comment]
> Sadly it's not possible to dynamically add to those icons. While it would be neat, there is no pretty way to go about it right now.

Closing because this is still the same problem.
