### ISSUE TITLE
Diagnostic messages don’t line up with the correct source line after the source is modified.

### ISSUE THREAD

**Issue by rob400i** [halcyon-tech/vscode-ibmi#699]
I set the option to create the Event File (OPTION(*EVENTF)) when using the CRTBNDRPG command.  After running the action, the diagnostic messages are correctly lined up with the source lines with the error.
However, if I delete lines above the lines with errors in the editor, the error messages don’t follow the new line positions. The error messages stay on the same line # which no longer corresponds to the correct source line.

Diagnostic messages line up correctly
![image](https://user-images.githubusercontent.com/107089402/172516630-b8989d40-6018-43c0-9f39-7793f5955db7.png)

After two lines at the top of the source were deleted, the diagnostic messages no longer line up with the correct source line.
![image](https://user-images.githubusercontent.com/107089402/172516659-79403603-9c3a-444c-a132-f73d56820072.png)

**Comment by worksofliam** [comment]
I'll see what I can do about this! It's not a bug per se... but it's part of vscode for sure.
