### ISSUE TITLE
Adding Graphical Debugging Through ACS

### ISSUE THREAD

**Issue by dariocs** [halcyon-tech/vscode-ibmi#70]
Hi everyone ,
What do you think if we add a graphical debug through the ACS?
If you already installed IBM Toolbox for Java on your server, both the jt400.jar and the tes.jar files are in the same directory on the server: /QIBM/ProdData/HTTP/Public/jt400/lib/
After copying the jar files to your client, add them to your client CLASSPATH environment variable.
To start Debug Manager from a command prompt on your client, run the following command: java utilities.DebugMgr
reference:
https://www.itjungle.com/2020/06/08/guru-graphical-debugging-through-acs/
https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_74/rzamq/rzamqrunning.htm

**Comment by worksofliam** [comment]
I think it'd be awesome, @dariocs - perhaps a command to launch it would be awesome.

**Comment by dariocs** [comment]
HI SJLennon ,
I used setting break points on grafical debug and It works fine... 
I ussually  run this comand to start the debugger:
java -cp  jt400.jar; tes.jar utilities.DebugMgr
Now I have done a PR that add it to the project .

**Comment by m-tyler** [comment]
If you use the ACS product (at least in the 1.1.8.x versions) there is a PLUGIN for the system debugger.  You can activate it like this, `.\acslaunch_win-32.exe /PLUGIN=sysdbg /SYSTEM=[server_name] /USER=[userid]`.  You will be prompted to log on to the connection created.    You may also specify a job reference to connect to. 

` Syntax: SYSDBG [Options]

 Valid options include:
          /system=<system_name>      Specify a system
          /user=<user>                         User ID to use for debug
          /job=<job_name>                  Job to debug, in 'number/user/name' format

Launches the IBM i System Debugger`

I would image a form to fill that specifies where the `acslaunch.jar` is located.  The product you download from IBM site has Windows, MAC and Linux start programs.
