### ISSUE TITLE
Tools to create a save file

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#709]
1. New right click option to create a save file from objects
2. New quick pick menu to toggle which objects you want to put into the save file
3. Next quick pick input box to enter where the save file will be saved to

**Comment by worksofliam** [comment]
4. Option to download, download and delete, nothing

**Comment by worksofliam** [comment]
<img width="649" alt="image" src="https://user-images.githubusercontent.com/3708366/173201787-eba6d424-6c77-493d-988a-f52feed8d23d.png">

**Comment by dennisnel** [comment]
I've tested on Windows

Selecting all 5 objects from an "Object" filter

![image](https://user-images.githubusercontent.com/69187463/173321666-87175642-caa2-4f04-a4fc-2619399e03a4.png)

![image](https://user-images.githubusercontent.com/69187463/173321831-1d0abf22-24a2-4ed4-bc6d-40d6ce5d84e6.png)

![image](https://user-images.githubusercontent.com/69187463/173321869-95a08548-52d9-4168-a790-e4eca701260f.png)

![image](https://user-images.githubusercontent.com/69187463/173321896-f5c81f70-3bf4-4543-8693-b7f5cff8dc04.png)

and then I copied the IFS savf to an IBM i *SAVF object and compared the results 

![image](https://user-images.githubusercontent.com/69187463/173322063-3d5a50dd-8e11-4fda-9974-291e3aa140bb.png)
