### ISSUE TITLE
vscode-ibmi-fs

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#712]
I'd like to make some objects editable as JSON. Let's say you open one of the objects up, it would load it as JSON in a new tab. Some could start as read-only, but in the future, we could let the user edit the JSON, and then when the file is saved, it would run the required commands.

* JOBD
* BNDDIR
* MSGF
* DTAARA

What else?

Needs to go into a separate extension as it would make vscode-ibmi bigger than it already is.

**Comment by GlennGundermann** [comment]
When you do this, is it possible to do it in such a way that only some data is editable?
For example, if you had a file with multiple members, having the member list and being able to edit the member description would be handy.  Or some settings in a user profile.

**Comment by worksofliam** [comment]
Repo created!
