### ISSUE TITLE
member browser option doesn't show up

### ISSUE THREAD

**Issue by kunalroy25** [halcyon-tech/vscode-ibmi#713]
Issue text goes here.

* QCCSID: 37
* Features enabled:
   * git: false
   * grep: true
   * tn5250: false
   * setccsid: true
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: false

**Comment by worksofliam** [comment]
Use the object browser.
