### ISSUE TITLE
The member browser does not appear in my VSCode left panel

### ISSUE THREAD

**Issue by GLooseJr** [halcyon-tech/vscode-ibmi#715]
After downloading, installing the Code for IBM i, and also checking for any updates, I only see these browsers:
USER LIBRARY LIST
OBJECT BROWSER
IFS BROWSER

I notice that some images of VSCode in your on-line help also do not show the MEMBER BROWSER, but other nearby documentation entries do show that browser at the point where documentation explains its use.

How do I get access to the MEMBER BROWSER?

The OBJECT BROWSER is not capable of opening IBM i source file members.  An error reports that it cannot open members of a file that is assigned CCSID 65535.  (Not surprising, since there is supposed to be a different browser that is designed to work with source file members.)

Thanks,
George Loose
Technical Product Manager - IBM i 
SMA Technologies
www.smatechnologies.com

**Comment by worksofliam** [comment]
@GLooseJr you're on the right track.

You do use the object browser as it replaced the member browser. You need to set the source CCSID in your connection settings.

**Comment by GLooseJr** [comment]
Barry,

I have not been able to find where to set the “source CCSID”.  The VSCode search, within the Settings panel, does not show any matching setting.  I didn’t find the answer to this while searching on line.

Thanks,
George


George Loose
Technical Product Manager
1201 Fannin St., Suite 202
 | Houston, TX 77002
Office: 281.446.5000 | Direct: 281.312.6649
www.SMAtechnologies.com
| ***@***.***
The information contained in this e-mail and any accompanying documents may contain information that is confidential or otherwise protected from disclosure. If you are not the intended recipient of this message, or if this message has been addressed to you in error, please immediately alert the sender by reply e-mail and then delete this message, including any attachments. Any dissemination, distribution or other use of the contents of this message by anyone other than the intended recipient is strictly prohibited.​
​
​
Signature For George Loose

**Comment by GLooseJr** [comment]
I found the correct JSON label after searching for “connections” while VSCode settings was on display.

Thanks for the help!
George


George Loose
Technical Product Manager
1201 Fannin St., Suite 202
 | Houston, TX 77002
Office: 281.446.5000 | Direct: 281.312.6649
www.SMAtechnologies.com
| ***@***.***
The information contained in this e-mail and any accompanying documents may contain information that is confidential or otherwise protected from disclosure. If you are not the intended recipient of this message, or if this message has been addressed to you in error, please immediately alert the sender by reply e-mail and then delete this message, including any attachments. Any dissemination, distribution or other use of the contents of this message by anyone other than the intended recipient is strictly prohibited.​
​
​
Signature For George Loose
From: George Loose
Sent: Friday, June 17, 2022 4:18 PM
To: halcyon-tech/vscode-ibmi ***@***.***>
Subject: RE: [halcyon-tech/vscode-ibmi] The member browser does not appear in my VSCode left panel (Issue #715)

Barry,

I have not been able to find where to set the “source CCSID”.  The VSCode search, within the Settings panel, does not show any matching setting.  I didn’t find the answer to this while searching on line.

Thanks,
George
