### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#717]
* Spanish
* French
* Japanese
* German

requires some work to support multi language

**Comment by natastro** [comment]
Hello! 👋🏼 I would be happy to provide Spanish translation if needed. Thank you!

**Comment by inf1serg** [comment]
Hi! Same as @natastro here! I can provide Spanish translation too.

**Comment by worksofliam** [comment]
This is coming soon. https://github.com/microsoft/vscode-extension-samples/blob/main/i18n-sample/README.md

**Comment by novy400** [comment]
Hi cool, I can help in French translation with Sebastien if needed.
