### ISSUE TITLE
Cannot save my source 

### ISSUE THREAD

**Issue by Papa-Lima-Tango** [halcyon-tech/vscode-ibmi#718]
I could not save my source to the ISeries.
Not sure what combination of keys i may have used or what scenario caused this.... but my source code looks ok from VSCode,  and when i tried looking at it from a green screen "see snip it below" it only has a partial amount of my program prefix/suffixed with Z's. 

I was able to restore my program from backup.  Would like to know maybe how this happened and what I could do to restore it from VSCode..   

Thanks 

Example......

```
\Z************************************************************************      
\Z******* PLEASE READ THIS BEFORE MAKING CHANGES TO THIS PROGRAM  ********      
\Z************************************************************************\Z    
\Z* Following sub-routines have been moved to copybook SAPxxxxx:       *\Z    
\Z* TS2EDTX, EDTITMX, ITMSRCX, ITMDTL,X                                      *\Z    
\Z************************************************************************\Z    
 \Z* Program Modification Log                                                   
 \Z*---------------------------------------------------------------------      
```  

* QCCSID: 37
* Features enabled:
   * git: true
   * grep: false
   * tn5250: true
   * setccsid: true
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: true

**Comment by worksofliam** [comment]
@Papa-Lima-Tango Hi!

Create a new source file and copy the member to it. Then, when you try and save in VS Code again, copy and paste the 'Code for IBM i' output channel contents here (it doesn't contain any sensitive information).

<img width="941" alt="image" src="https://user-images.githubusercontent.com/3708366/174691551-a9b93d66-cdd4-4526-b1cb-f897e0b2bb4f.png">

If you're able to, please share what is after the line it stops saving at. Likely some SQL issue that we can resolve quickly.
