### ISSUE TITLE
Can't open source members with the symbol '§' in the name

### ISSUE THREAD

**Issue by alfax218** [halcyon-tech/vscode-ibmi#719]
Can't open source members with symbol '§' in the name, this issue occurred since release 1.3.4
Same issue as: https://github.com/halcyon-tech/vscode-ibmi/issues/701

* QCCSID: 1144
* Features enabled:
   * git: true
   * grep: false
   * tn5250: false
   * setccsid: true
   * GENCMDXML.PGM: false
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: true

**Comment by worksofliam** [comment]
@alfax218 are you suggesting you were able to open up those members in 1.3.7? You should downgrade for the time being if that's the case.

**Comment by worksofliam** [comment]
@p-behr check this out.

**Comment by worksofliam** [comment]
@alfax218 1.3.9 with this fix is deploying now. Thanks @p-behr !

**Comment by alfax218** [comment]
Problem fixed!
Keep going, you're doing a great job!

**Comment by worksofliam** [comment]
@chrjorgensen Take a look at this issue. I know we're looking at CCSID issues, but isn't it hilarious that member names can have this character in them?

**Comment by chrjorgensen** [comment]
@worksofliam This is indeed also a CCSID issue - the CCSID 37 US characters '#@$' becomes '£§$' in CCSID 280 ITA.
I guess an Italian will maybe not use any of the characters '£§$' in a member name, but if the member is installed or restored from an external (american) party, these characters may get used anyway.

This is exactly the kind of problem, that my PR #714 will fix - no more need for adding special characters to the regexp for system names... 😃
