### ISSUE TITLE
Go to file cannot find newly added source member

### ISSUE THREAD

**Issue by DgitalTrex** [halcyon-tech/vscode-ibmi#722]
Steps:
1. Use CPYF and add member to QRPGLESRC
2. Refresh VSCode object browser
3. Use Go To File (Ctrl+Alt+P)
4. Look for new member ..../QRPGLESRC/NewMember

Expected result:
New member to show
Actual behavior:
Member no show

* QCCSID: 37
* Features enabled:
   * git: true
   * grep: false
   * tn5250: false
   * setccsid: true
   * GENCMDXML.PGM: false
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: false

```json
[
  {
    "command": "system \"CRTLIB LIB(ISEDEV) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ISEDEV already exists.",
    "cwd": "/home/ISE1"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPTOIMPF in library QSYS not found.",
    "cwd": "/home/ISE1"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found.",
    "cwd": "/home/ISE1"
  }
]
```

**Comment by DgitalTrex** [comment]
What's the list? Also how do I do that? I tried the refresh button a couple
of times

**Comment by worksofliam** [comment]
@DgitalTrex sorry, that was more of a note to self!

For the time being, the bottom of the file list should have the ability to clear all the entries, and then when you open the source file again the list to should fix itself.

**Comment by sebCIL** [comment]
I create the PR #833 for this issue.
