### ISSUE TITLE
Set User Library List & custom variables with Actions

### ISSUE THREAD

**Issue by merhovon** [halcyon-tech/vscode-ibmi#723]
**Is your feature request related to a problem? Please describe.**
Longer library lists currently have to be entered manually.

**Describe the solution you'd like**
I work with a very large library list, so I do not have to maintain this again and again manually I have created a CL program. It would be great if such CL applications could be executed as actions.  

**Additional context**
The idea would also fit very well, to set custom variables.

**Comment by worksofliam** [comment]
I am not sure I understand the request.

> It would be great if such CL applications could be executed as actions.

CL programs can be executed in actions? Maybe you are referring to the point that each command runs stateless. You might also want to look into connection profiles, which will allow you to switch between library lists.

**Comment by merhovon** [comment]
The problem is, currently when I have the library list updated using an action, this is not updated in the "User-Library-List". I have included the CL as an action and run it and in the output I see that the libraries have been added to the list, but they are not added to the "User-Library-List". 

![image](https://user-images.githubusercontent.com/26201870/175562340-ac90d4e7-d390-4868-98e1-d0593a717efe.png)


![image](https://user-images.githubusercontent.com/26201870/175562370-5afb4e30-5c7a-4686-9dd0-ac19a9935b0c.png)

**Comment by worksofliam** [comment]
@merhovon That is correct. CL programs cannot update the library list that is used from VS Code. Currently, there is no way around this. There is a button you can use on the User Library List view to enter a list of libraries. It might be faster than doing them one at a time.

<img width="646" alt="image" src="https://user-images.githubusercontent.com/3708366/178056735-2f3b03bf-1996-47e4-9446-94249efa1aa7.png">
