### ISSUE TITLE
List of member doesn't works (when attributes are blank)

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/vscode-ibmi#743]
Hi, 

this problem appear today after I update the extension to 1.4.0.

From object browser expanding a file source it doesn't appear nothing.

<img width="261" alt="image" src="https://user-images.githubusercontent.com/9719313/178474233-0e29bd20-8d9b-43d8-acb2-134c2b080c59.png">

Obiously there are a lot of source, and in code for I output I see this:

[codefori_output.txt](https://github.com/halcyon-tech/vscode-ibmi/files/9092194/codefori_output.txt)

I try to delete the filter and recreate it, but nothing. 

My library stay in an IASP.

Many thanks

**Comment by pabloto** [comment]
Downgrading to 1.3.10 it works.

**Comment by worksofliam** [comment]
@pabloto  can you test and let me know if the IFS browser is also not working?

I think I know the issue.

**Comment by pabloto** [comment]
Hi Liam,

Ifs seems works:

<img width="331" alt="image" src="https://user-images.githubusercontent.com/9719313/178499826-31618142-986e-4c2f-84e7-a86efc8d5356.png">

Obiously I'm again in 1.4.0

<img width="976" alt="image" src="https://user-images.githubusercontent.com/9719313/178499997-cf350c67-74af-4b4f-ab8d-b4bc1496e367.png">

Let me know if I could help.

Many thanks

**Comment by worksofliam** [comment]
@pabloto 

In 1.4.0:

1. Toggle the developer tools (in photo)
2. Try and load the source file list again
3. Paste any error from dev tools you see here

<img width="408" alt="image" src="https://user-images.githubusercontent.com/3708366/178500331-bdd13e10-4f84-4d6d-ae92-d80459cc6b32.png">

**Comment by worksofliam** [comment]
@pabloto Do you have time to meet and look at this together at all?

**Comment by worksofliam** [comment]
@pabloto 1.4.1 is coming out with some additional logging that will be printed to the dev tools console, so please [follow the steps from that comment again](https://github.com/halcyon-tech/vscode-ibmi/issues/743#issuecomment-1181756709) when you have the new version.

**Comment by pabloto** [comment]
Hi hope to understand well your instructions:

[Extension Host] CPF2158: La libreria VSCODE esiste nell'unità ASP DIRECTA1.
CPF2111: La libreria VSCODE esiste già.
console.ts:137 [Extension Host] ls: cannot access '/QSYS.lib/VSCODE.lib/': Un file o una directory nel nome percorso non esiste.
console.ts:137 [Extension Host] TypeError: Cannot read properties of null (reading 'replace')
	at e.exports.sysNameInLocal (/Users/osxtest/.vscode/extensions/halcyontechltd.code-for-ibmi-1.4.1/dist/extension.js:2:658921)
	at /Users/osxtest/.vscode/extensions/halcyontechltd.code-for-ibmi-1.4.1/dist/extension.js:2:665146
	at Array.map (<anonymous>)
	at e.exports.getMemberList (/Users/osxtest/.vscode/extensions/halcyontechltd.code-for-ibmi-1.4.1/dist/extension.js:2:665020)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async e.exports.getChildren (/Users/osxtest/.vscode/extensions/halcyontechltd.code-for-ibmi-1.4.1/dist/extension.js:2:718359)
	at async v.fetchChildrenNodes (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:19736)
	at async v.getChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:15955)

**Comment by worksofliam** [comment]
Looks like we're not taking your ASP into account. I will see what I can do!

**Comment by worksofliam** [comment]
@pabloto Can you confirm:

1. The name of your ASP is `DIRECTA1`
2. You have SQL enabled or disabled

**Comment by pabloto** [comment]
Yes my iasp is directa1, and I have sql enable

**Comment by worksofliam** [comment]
Here's the issue.

Row coming back from the database:

```
MBASP: 33
MBFILE: 'QCLSRC'
MBMTXT: null
MBMXRL: 80
MBNAME: 'UCHKCONT1C'
MBSEU2: null
```

Code being executed:
```js
        file: this.ibmi.sysNameInLocal(result.MBFILE),
        name: this.ibmi.sysNameInLocal(result.MBNAME),
        extension: this.ibmi.sysNameInLocal(result.MBSEU2),
```

So it's the null being passed in that's causing the error.

**Comment by worksofliam** [comment]
I am going to update `sysNameInLocal` and `sysNameInAmerican` so that if null is passed in, then it will return null right away.

**Comment by chrjorgensen** [comment]
Yeah, I see the error on my system as well - a source file member without type stops the generation of the member list.
Hm, not a situation that I tested for, sorry... but great to have this fixed. 👍

**Comment by worksofliam** [comment]
@chrjorgensen it might be an hour or two before I get to making the PR. If you want to, feel free.

**Comment by chrjorgensen** [comment]
@worksofliam PR is coming...!

**Comment by chrjorgensen** [comment]
@worksofliam PR #745 has landed - please review.

The title of this issue mentions ASP not being taken into account - is there also a problem with ASP handling? I haven't changed any ASP handling...

**Comment by worksofliam** [comment]
@chrjorgensen Yes, let's ignore the title. I was wrong. I will fix that!

**Comment by worksofliam** [comment]
@pabloto 1.4.2 has the fix. Thanks!

**Comment by pabloto** [comment]
Thanks to you. Tomorrow I will try

**Comment by pabloto** [comment]
Hi @worksofliam , @chrjorgensen 

it works perfect.

Many thanks
