### ISSUE TITLE
Can't see sources when opening filters in object browser

### ISSUE THREAD

**Issue by alfax218** [halcyon-tech/vscode-ibmi#746]
With last updates i can't see any source member when opening filters in object browser. I've downgraded to 1.3.10 to be able to see again the source members

```
* QCCSID: 1144
* Features enabled:
   * git: true
   * grep: false
   * tn5250: false
   * setccsid: true
   * GENCMDXML.PGM: false
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: true
```

**Comment by pabloto** [comment]
Have you tried the last version 1.4.2? Yesterday I have the same problem and this version works for me.

**Comment by alfax218** [comment]
> Have you tried the last version 1.4.2? Yesterday I have the same problem and this version works for me.

I've started downgrading from 1.4.2 until the 1.3.10, that's the latest version working for me

**Comment by worksofliam** [comment]
In 1.4.2:

1. Toggle the developer tools (in photo)
2. Try and load the source file list again
3. Paste any error from dev tools **console** you see here

<img width="408" alt="image" src="https://user-images.githubusercontent.com/3708366/178500331-bdd13e10-4f84-4d6d-ae92-d80459cc6b32.png">

Please also share the contents of your Code for IBM i output channel after the list doesn't appear.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by alfax218** [comment]
> 

No errors in the dev tool console.

This is the Code for IBM i output:
`/: system "DSPFD FILE(MYLIB123/QSRC) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_md18RJ3s)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Il file di emissione O_MD18RJ3S è stato creato nella libreria ILEDITOR.\nCPF9862: Il membro O_MD18RJ3S è stato aggiunto al file di emissione O_MD18RJ3S nella libreria ILEDITOR.\nCPF3030: 1 record sono stati aggiunti al membro O_MD18RJ3S nel file O_MD18RJ3S in ILEDITOR.",
    "stderr": ""
}

/: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT * FROM ILEDITOR.O_md18RJ3s
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\nPHRCEN  PHRDAT  PHRTIM  PHFILE     PHLIB      PHFTYP  PHFILA  PHMXD  PHFATR  PHSYSN   PHASP  PHRES  PHDTAT  PHWAIT  PHWATR  PHSHAR  PHLVLC  PHTXT                                              PHNOFM  PHFCCN  PHFCDT  PHFCTM  PHFLS  PHICAP  PHRES2    PHACCP  PHSELO  PHCSEQ  PHNOMB  PHRES3  PHSQLT  PHRES4   PHMAXM  PHMANT  PHRECV  PHFKAP  PHSIZ        PHSIZI  PHSIZM  PHRCDC       PHALLO  PHCONT  PHUNIT  PHFRCR  PHDLTP  PHMXKL  PHMXRL  PHJRNL  PHJRNM     PHJRLB     PHJRIM  PHJRSC  PHJRSD  PHJRST  PHJROM  PHNAML  PHRMTN                                             PHRDLT  PHNACM  PHACCM         PHALRD  PHALWT  PHALUP  PHALDT  PHDCTL  PHINID        PHDCTN     PHFILN     PHRUSE  PHCSID  PHMXK2  PHSSEQ     PHSSLB     PHLGID     PHTBSH  PHTBSU  PHNOCS  PHNOTR  PHTBLN  PHLNTB                                                                                                                                                                                                                                                             PHAPSZ  PHDSTF  PHNODG     PHNODL     PHNUMP  PHPRTK                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               PHFLPS  PHPRBY  PHMQMT  PHMQRF  PHMQOE  PHMQCL  PHAPGS  PHVOLT  PHMQRS  PHMQRM  PHMQWN  PHKPIM \n------- ------- ------- ---------- ---------- ------- ------- ------ ------- -------- ------ ------ ------- ------- ------- ------- ------- -------------------------------------------------- ------- ------- ------- ------- ------ ------- --------- ------- ------- ------- ------- ------- ------- -------- ------- ------- ------- ------- ------------ ------- ------- ------------ ------- ------- ------- ------- ------- ------- ------- ------- ---------- ---------- ------- ------- ------- ------- ------- ------- -------------------------------------------------- ------- ------- -------------- ------- ------- ------- ------- ------- ------------- ---------- ---------- ------- ------- ------- ---------- ---------- ---------- ------- ------- ------- ------- ------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ------- ------- ---------- ---------- ------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ------- ------- ------- ------- ------- ------- ------- ------- ------- ------- ------- -------\n1       220713  171559  QSRC       MYLIB123   P       *PHY           PF      E00B174B   33          S       -    1      60          N                                                               1  1       170825  115034  Y      N                 A       N       N         5725          0                     0                                10000    1000     499       509000  N       N          0         0     0       0       132  N                                                                        0                                                                  0                   Y       Y       Y       Y       N                  0                                  1144       0  *HEX                  ITA                             0       0       0                                                                                                                                                                                                                                                                             N                                 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        N       0                                            0  0                               N      \n\n  1 RECORD(S) SELECTED.",
    "stderr": ""
}

/: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"

        SELECT
          (b.avgrowsize - 12) as MBMXRL,
          a.iasp_number as MBASP,
          a.table_name AS MBFILE,
          b.system_table_member as MBNAME,
          coalesce(b.source_type, '') as MBSEU2,
          coalesce(b.partition_text, '') as MBMTXT
        FROM qsys2.systables AS a
          JOIN qsys2.syspartitionstat AS b
            ON b.table_schema = a.table_schema AND
              b.table_name = a.table_name
        WHERE
          a.table_schema = 'MYLIB123' 
          AND a.table_name = 'QSRC'
          AND b.system_table_member like '@MORD%'
      
{
    "code": 1,
    "signal": null,
    "stdout": "DB2>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n\nMBMXRL               MBASP  MBFILE                                                                                                                           MBNAME     MBSEU2     MBMTXT                                            \n-------------------- ------ -------------------------------------------------------------------------------------------------------------------------------- ---------- ---------- --------------------------------------------------\n\n  0 RECORD(S) SELECTED.",
    "stderr": ""
}
`

**Comment by worksofliam** [comment]
@alfax218 Would you mind removing the member name filter you have defined (`@MORD`) and trying again? Thanks!

**Comment by chrjorgensen** [comment]
@alfax218

SYSTEM_TABLE_NAME is in CCSID 37 (US) and will never match '§' - but will match '@'...

There were a major rewrite of retrieving the member list of a source file in version 1.4.x, and it is now the CCSID on your userprofile, alternatively system value QCCSID, that control how the variant characters '#', '@' and '$' (in CCSID 37) are converted to your national characters.

First, check the CCSID of your userprofile - if it is different from the system value. That could produce a member list with un-expected variant characters.

Next, try removing any variant characters from your filter (when you can edit the filter) and see if you see any members - and what variant characters are shown. You should specify the same characters in your filter as is shown in the member list.

Here is a sample with user CCSID 37 `CHGUSRPRF xxx CCSID(37)` and member filter `MEMBER#*`:

![billede](https://user-images.githubusercontent.com/13275072/178782268-39f0f925-7f13-413d-bcef-4498047ec230.png)

And here is the same list, now with user CCSID 1144 `CHGUSRPRF xxx CCSID(1144)` - I did not change the filter, just the user CCSID:

![billede](https://user-images.githubusercontent.com/13275072/178783885-0ccccd35-bece-4df1-b778-1501321ce420.png)

(The filter did not need to be changed because the '#' is not an Italian variant character - you use '£' instead. So the '#' is not converted and is sent to the SQL LIKE operator as is and thus still match the member name in american (CCSID 37))

When applying any member filter, the filter value is converted from national variant characters to american - to match the output from SQL. You may have to mingle your filter to match what CCSID is on your IBM i user profile. If you change your IBM i CCSID you may also have to change the filters in Code for IBM i - if they contain any variant characters.

Hope this helps...

**Comment by alfax218** [comment]
> @alfax218
> 
> SYSTEM_TABLE_NAME is in CCSID 37 (US) and will never match '§' - but will match '@'...
> 
> There were a major rewrite of retrieving the member list of a source file in version 1.4.x, and it is now the CCSID on your userprofile, alternatively system value QCCSID, that control how the variant characters '#', '@' and '$' (in CCSID 37) are converted to your national characters.
> 
> First, check the CCSID of your userprofile - if it is different from the system value. That could produce a member list with un-expected variant characters.
> 
> Next, try removing any variant characters from your filter (when you can edit the filter) and see if you see any members - and what variant characters are shown. You should specify the same characters in your filter as is shown in the member list.
> 
> Here is a sample with user CCSID 37 `CHGUSRPRF xxx CCSID(37)` and member filter `MEMBER#*`:
> 
> ![billede](https://user-images.githubusercontent.com/13275072/178782268-39f0f925-7f13-413d-bcef-4498047ec230.png)
> 
> And here is the same list, now with user CCSID 1144 `CHGUSRPRF xxx CCSID(1144)` - I did not change the filter, just the user CCSID:
> 
> ![billede](https://user-images.githubusercontent.com/13275072/178783885-0ccccd35-bece-4df1-b778-1501321ce420.png)
> 
> (The filter did not need to be changed because the '#' is not an Italian variant character - you use '£' instead. So the '#' is not converted and is sent to the SQL LIKE operator as is and thus still match the member name in american (CCSID 37))
> 
> When applying any member filter, the filter value is converted from national variant characters to american - to match the output from SQL. You may have to mingle your filter to match what CCSID is on your IBM i user profile. If you change your IBM i CCSID you may also have to change the filters in Code for IBM i - if they contain any variant characters.
> 
> Hope this helps...

The CCSID of the userprofile is the same of the system (1144).

I've tried to edit the filter removing the special characters (§ in this case) and i can see the source members with the correct symbol. So if i create a filter with the symbol § i can't see the sources, and if i create a filter without the symbol i see the sources with the symbol §.

**Comment by chrjorgensen** [comment]
> The CCSID of the userprofile is the same of the system (1144).

FYI, it is not a requirement that the userprofile has the same CCSID as the system value - the userprofile takes precedence.

> I've tried to edit the filter removing the special characters (§ in this case) and i can see the source members with the correct symbol. So if i create a filter with the symbol § i can't see the sources, and if i create a filter without the symbol i see the sources with the symbol §.

Can you post some screenshots of your list with and without filter with the symbol § - and a screenshot of your filter setup?
This would make it easier for me to test on my system...

**Comment by chrjorgensen** [comment]
@pabloto 

Your first filter TEST123 selects members with names beginning with '§TEST' - but the member in the file is called 'TEST§'...
So your first filter will not find the member. You must change the member value in the filter to 'TEST§*', then it will work.

**Comment by alfax218** [comment]
@chrjorgensen 

I've edited the reply 1 minute after i've posted for more clarity so maybe you've missed it.
There are 2 members: §test.rpgle and test§.rpgle

**Comment by chrjorgensen** [comment]
@pabloto 

I just recreated your scenario on my server - and I get the expected result - with each filter showing one member:

![billede](https://user-images.githubusercontent.com/13275072/179765836-807efd76-6611-4c7f-bc64-1a0f01a4b66c.png)

I also tested SQL enabled and SQL disabled - same result.

Please confirm you are running version 1.4.2 of the extension:

![billede](https://user-images.githubusercontent.com/13275072/179766216-5495515e-94ee-4c8f-826c-4c8a97f14f2b.png)

Next, try the following:

1. create a new connection - to the same server using the same userprofile and SQL enabled. So we have a fresh configuration with no errors from previous versions of the extension. Not being able to delete a filter indicates you have a corrupt configuration. Verify you see both members in the source file with member filter value '*'.

2. Add a filter like the one called TEST123 above - with member filter value '§TEST*'. Verify you see one member only in the list.

3. Add a filter like TEST321 with member filter value 'TEST*'. Verify you see one member only again. Both filters select only one member as specified.

If at any point you don't get the expected result, please post the output from the Code for IBM i channel.

**Comment by alfax218** [comment]
@chrjorgensen 

So i've created a new connection, same server, same userprofile and SQL enabled, with last version of Code for IBM i (1.4.2).

This is the results:
![image](https://user-images.githubusercontent.com/107923967/179926140-16dd7946-0750-48cc-ac2d-aaaf9478ab35.png)

I still have the same problems and still can't delete the filters.

This is the output when i try to open the faulty filter:

/home/TESTUSER: system "DSPFD FILE(VSCODE/QSRC) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(ILEDITOR/O_5xdIrf1y)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Il file di emissione O_5XDIRF1Y è stato creato nella libreria ILEDITOR.\nCPF9862: Il membro O_5XDIRF1Y è stato aggiunto al file di emissione O_5XDIRF1Y nella libreria ILEDITOR.\nCPF3030: 1 record sono stati aggiunti al membro O_5XDIRF1Y nel file O_5XDIRF1Y in ILEDITOR.",
    "stderr": ""
}

/home/TESTUSER: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT * FROM ILEDITOR.O_5xdIrf1y
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\nPHRCEN  PHRDAT  PHRTIM  PHFILE     PHLIB      PHFTYP  PHFILA  PHMXD  PHFATR  PHSYSN   PHASP  PHRES  PHDTAT  PHWAIT  PHWATR  PHSHAR  PHLVLC  PHTXT                                              PHNOFM  PHFCCN  PHFCDT  PHFCTM  PHFLS  PHICAP  PHRES2    PHACCP  PHSELO  PHCSEQ  PHNOMB  PHRES3  PHSQLT  PHRES4   PHMAXM  PHMANT  PHRECV  PHFKAP  PHSIZ        PHSIZI  PHSIZM  PHRCDC       PHALLO  PHCONT  PHUNIT  PHFRCR  PHDLTP  PHMXKL  PHMXRL  PHJRNL  PHJRNM     PHJRLB     PHJRIM  PHJRSC  PHJRSD  PHJRST  PHJROM  PHNAML  PHRMTN                                             PHRDLT  PHNACM  PHACCM         PHALRD  PHALWT  PHALUP  PHALDT  PHDCTL  PHINID        PHDCTN     PHFILN     PHRUSE  PHCSID  PHMXK2  PHSSEQ     PHSSLB     PHLGID     PHTBSH  PHTBSU  PHNOCS  PHNOTR  PHTBLN  PHLNTB                                                                                                                                                                                                                                                             PHAPSZ  PHDSTF  PHNODG     PHNODL     PHNUMP  PHPRTK                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               PHFLPS  PHPRBY  PHMQMT  PHMQRF  PHMQOE  PHMQCL  PHAPGS  PHVOLT  PHMQRS  PHMQRM  PHMQWN  PHKPIM \n------- ------- ------- ---------- ---------- ------- ------- ------ ------- -------- ------ ------ ------- ------- ------- ------- ------- -------------------------------------------------- ------- ------- ------- ------- ------ ------- --------- ------- ------- ------- ------- ------- ------- -------- ------- ------- ------- ------- ------------ ------- ------- ------------ ------- ------- ------- ------- ------- ------- ------- ------- ---------- ---------- ------- ------- ------- ------- ------- ------- -------------------------------------------------- ------- ------- -------------- ------- ------- ------- ------- ------- ------------- ---------- ---------- ------- ------- ------- ---------- ---------- ---------- ------- ------- ------- ------- ------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ------- ------- ---------- ---------- ------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ------- ------- ------- ------- ------- ------- ------- ------- ------- ------- ------- -------\n1       220720  094752  QSRC       VSCODE     P       *PHY           PF      E00B174B    1          S       -    1      60          N                                                               1  1       220719  145404  Y      N                 A       N       N            2          0                     0                                10000    1000     499       509000  N       N          0         0     0       0        92  N                                                                        0                                                                  0                   Y       Y       Y       Y       N                  0                                  1144       0  *HEX                  ITA                             0       0       0                                                                                                                                                                                                                                                                             N                                 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        N       0                                            0  0                               N      \n\n  1 RECORD(S) SELECTED.",
    "stderr": ""
}

/home/TESTUSER: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"

        SELECT
          (b.avgrowsize - 12) as MBMXRL,
          a.iasp_number as MBASP,
          a.table_name AS MBFILE,
          b.system_table_member as MBNAME,
          coalesce(b.source_type, '') as MBSEU2,
          coalesce(b.partition_text, '') as MBMTXT
        FROM qsys2.systables AS a
          JOIN qsys2.syspartitionstat AS b
            ON b.table_schema = a.table_schema AND
              b.table_name = a.table_name
        WHERE
          a.table_schema = 'VSCODE' 
          AND a.table_name = 'QSRC'
          AND b.system_table_member like '@TEST%'
      
{
    "code": 1,
    "signal": null,
    "stdout": "DB2>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n  ?>\n\nMBMXRL               MBASP  MBFILE                                                                                                                           MBNAME     MBSEU2     MBMTXT                                            \n-------------------- ------ -------------------------------------------------------------------------------------------------------------------------------- ---------- ---------- --------------------------------------------------\n\n  0 RECORD(S) SELECTED.",
    "stderr": ""
}

**Comment by alfax218** [comment]
@chrjorgensen 

![image](https://user-images.githubusercontent.com/107923967/179936485-db55c3cb-5f0f-415b-ad8d-c2bff050701d.png)

**Comment by alfax218** [comment]
@chrjorgensen 

![image](https://user-images.githubusercontent.com/107923967/179942709-3578a969-a804-42c9-a8d9-e29ab00cdcdd.png)

**Comment by alfax218** [comment]
@chrjorgensen 

![image](https://user-images.githubusercontent.com/107923967/179949851-f2176501-7772-43f4-8735-4ff5754cb358.png)

**Comment by chrjorgensen** [comment]
@alfax218 

That's it - your system has a different CCSID 280 (ITA) for SYSTEM_TABLE_NAME than all my systems, which has CCSID 37 (US).
This is the output from my systems:

![billede](https://user-images.githubusercontent.com/13275072/179969962-30ef9dc7-4d90-4764-a7f7-53c2c123e63b.png)

I also tested this on PUB400, which runs under CCSID 273 (GER) - and it is the same, CCSID 37 for the two columns.

Do you have access to more IBM i systems, where you can do the same check?

We have not done anything special to get CCSID 37 on these columns - installed the system and applied PTF's using QSECOFR profile. Have you any idea of why your system is different?

**Comment by alfax218** [comment]
@chrjorgensen 


> Yeah, letting the database column CCSID control the conversion is also on my mind.

That would be great!

> How is your filter doing when you disable SQL in the configuration settings? The extension then uses DSPFD TYPE(*MBR) which returns the member names in CCSID 37 - at least on our systems. _Can you check how it affects your lists?_

Actually, with SQL disabled it works, i can see both sources:
![image](https://user-images.githubusercontent.com/107923967/180015751-ac650cd5-e436-474c-85e5-f8b86a4a7b1a.png)

**Comment by alfax218** [comment]
@chrjorgensen 

> > How is your filter doing when you disable SQL in the configuration settings? The extension then uses DSPFD TYPE(*MBR) which returns the member names in CCSID 37 - at least on our systems. _Can you check how it affects your lists?_
> 
> Actually, with SQL disabled it works, i can see both sources: ![image](https://user-images.githubusercontent.com/107923967/180015751-ac650cd5-e436-474c-85e5-f8b86a4a7b1a.png)

I didn't try to open the sources. I can see them but not open them, i get this output:
```
.: system "CPYTOSTMF FROMMBR('/TESTASP/QSYS.lib/VSCODE.lib/QSRC.file/TEST.mbr') TOSTMF('/tmp/vscodetemp-O_9d8iF44q') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPFA0A9: L'oggetto non è stato trovato. L'oggetto è /TESTASP/QSYS.lib/VSCODE.lib/QSRC.file/TEST.mbr.\nCPFA097: Oggetto non copiato. L'oggetto è /TESTASP/QSYS.lib/VSCODE.lib/QSRC.file/TEST.mbr."
}
```

**Comment by chrjorgensen** [comment]
@alfax218 

I will look into how we can make this work with SQL enabled. But it may take some time, so in the mean time you may disable SQL to avoid the issue. Is that OK?

**Comment by alfax218** [comment]
> @alfax218
> 
> I will look into how we can make this work with SQL enabled. But it may take some time, so in the mean time you may disable SQL to avoid the issue. Is that OK?

Sorry, i made another edit after posted.
Even though i can see the sources i can't open them. In the meantime i think i'm gonna use the version 1.3.10 wich works fine for me (except for deleting filters but i can still delete them in the settings json).

**Comment by chrjorgensen** [comment]
@alfax218 

Your `CPYTOSTMF` command indicates your library is in a user ASP - is that correct? This is not something I have seen before in this case and has not tested against it.

Will the `CPYTOSTMF` command succeed in a regular 5250 session? There are no variant characters in the names, so there is no conversion done in the extension to change the command.

Also you should report the filter delete problem in a new issue - so we can investigate this as well.

**Comment by alfax218** [comment]
@chrjorgensen 

> Your `CPYTOSTMF` command indicates your library is in a user ASP - is that correct? This is not something I have seen before in this case and has not tested against it.

Correct.


> Will the `CPYTOSTMF` command succeed in a regular 5250 session? There are no variant characters in the names, so there is no conversion done in the extension to change the command.

No, it fails, same error message.


> Also you should report the filter delete problem in a new issue - so we can investigate this as well.

Ok, thank you, i will.

**Comment by worksofliam** [comment]
@chrjorgensen Your related PR (#770) has been merged in. What needs to be done for this issue?

**Comment by chrjorgensen** [comment]
@alfax218 

Could you please try the new release 1.5.1 of Code for IBM i? It contains changes to the code for retrieving member list using SQL and hopefully fixes this issue. TIA.

**Comment by alfax218** [comment]
@chrjorgensen 

Thank you, now it works!
