### ISSUE TITLE
 I can't compile, what do I need to configure?

### ISSUE THREAD

**Issue by gtjhem** [halcyon-tech/vscode-ibmi#753]
I have this problem when compiling

![image](https://user-images.githubusercontent.com/32494468/179126235-12bdd351-746a-41e7-a5f7-d8518340ca85.png)

/home/E62480: /QOpenSys/usr/bin/qsh
liblist -d ;liblist -c E62480;liblist -a MONITORPLU BEPTMFILES BEPUSRLIB BEPCYFILES CREDICARD BEPSATEXD E62480;system  "CRTSQLRPGI OBJ(E62480/BEPGMNP001) SRCFILE(E62480/QRPGLESRC) CLOSQLCSR(*ENDMOD) COMMIT(*NONE) OPTION(*EVENTF) DBGVIEW(*SOURCE)"; if [[ $? -ne 0 ]]; then exit 1; fi
{
    "code": 9,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

/home/E62480: system "QSYS/CPYTOIMPF FROMFILE(E62480/EVFEVENT BEPGMNP001) TOSTMF('/home/E62480/tmp/vscodetemp-O_KjT3XuDL') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD) "
{
    "code": 0,
    "signal": null,
    "stdout": "CPC2958: Todos los registros copiados del archivo EVFEVENT en E62480.",
    "stderr": ""
}

.: system "CPYTOSTMF FROMMBR('/IIBSDESA/QSYS.lib/E62480.lib/QRPGLESRC.file/BEPGMNP001.mbr') TOSTMF('/home/E62480/tmp/vscodetemp-O_w4RsE2an') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
.: system "CPYTOSTMF FROMMBR('/IIBSDESA/QSYS.lib/E62480.lib/QRPGLESRC.file/BEPGMNP001.mbr') TOSTMF('/home/E62480/tmp/vscodetemp-O_w4RsE2an') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPCA082: Se ha copiado el objeto.",
    "stderr": ""
}

{
    "code": 0,
    "signal": null,
    "stdout": "CPCA082: Se ha copiado el objeto.",
    "stderr": ""
}

.: system "CPYTOSTMF FROMMBR('/IIBSDESA/QSYS.lib/E62480.lib/QRPGLESRC.file/BEPGMNP001.mbr') TOSTMF('/home/E62480/tmp/vscodetemp-O_w4RsE2an') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPCA082: Se ha copiado el objeto.",
    "stderr": ""
}

.: system "CPYTOSTMF FROMMBR('/IIBSDESA/QSYS.lib/E62480.lib/QRPGLESRC.file/BEPGMNP001.mbr') TOSTMF('/home/E62480/tmp/vscodetemp-O_w4RsE2an') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPCA082: Se ha copiado el objeto.",
    "stderr": ""
}

.: system "CPYTOSTMF FROMMBR('/IIBSDESA/QSYS.lib/E62480.lib/QRPGLESRC.file/BEPGMNP001.mbr') TOSTMF('/home/E62480/tmp/vscodetemp-O_w4RsE2an') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPCA082: Se ha copiado el objeto.",
    "stderr": ""
}

.: system "CPYTOSTMF FROMMBR('/IIBSDESA/QSYS.lib/E62480.lib/QRPGLESRC.file/BEPGMNP001.mbr') TOSTMF('/home/E62480/tmp/vscodetemp-O_w4RsE2an') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPCA082: Se ha copiado el objeto.",
    "stderr": ""
}

.: system "CPYTOSTMF FROMMBR('/IIBSDESA/QSYS.lib/E62480.lib/QRPGLESRC.file/BEPGMNP001.mbr') TOSTMF('/home/E62480/tmp/vscodetemp-O_w4RsE2an') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPCA082: Se ha copiado el objeto.",
    "stderr": ""
}

dont show spool 

![image](https://user-images.githubusercontent.com/32494468/179126453-b9b2d07f-6e75-4bca-9fd8-4291ea99033b.png)

last EVENTF in the EVFEVENT in my lib

EVFEVENT
"TIMESTAMP  0 20220714203125"
"PROCESSOR  0 999 1"
"FILEID     0 999 000000 027 QTEMP/QSQLTEMP1(BEPGMNP001) 20220714203125 0"
"FILEID     0 001 000000 028 E62480/QRPGLESRC(BEPGMNP001) 20220714201459 0"
"EXPANSION  0 001 000000 000000 999 000047 000111"
"EXPANSION  0 001 000088 000088 999 000139 000147"
"EXPANSION  0 001 000088 000088 999 000163 000172"
"EXPANSION  0 001 000119 000119 999 000192 000203"
"EXPANSION  0 001 000119 000119 999 000216 000226"
"FILEEND    0 001 000124"
"FILEEND    0 999 000231"
"PROCESSOR  0 000 1"
"FILEID     0 001 000000 029 E62480/EVFTEMPF01(BEPGMNP001) 20220714203125 1"
"ERROR      0 001 1 000194 000194 009 000194 017 RNF7031 I 00 053 El nombre o indicador SQL_00009 no está referenciado."
"ERROR      0 001 1 000195 000195 009 000195 017 RNF7031 I 00 053 El nombre o indicador SQL_00010 no está referenciado."
"ERROR      0 001 1 000196 000196 009 000196 017 RNF7031 I 00 053 El nombre o indicador SQL_00011 no está referenciado."
"ERROR      0 001 1 000197 000197 009 000197 017 RNF7031 I 00 053 El nombre o indicador SQL_00012 no está referenciado."
"ERROR      0 001 1 000141 000141 009 000141 017 RNF7031 I 00 053 El nombre o indicador SQL_00001 no está referenciado."
"ERROR      0 001 1 000142 000142 009 000142 017 RNF7031 I 00 053 El nombre o indicador SQL_00002 no está referenciado."
"ERROR      0 001 1 000144 000144 009 000144 017 RNF7031 I 00 053 El nombre o indicador SQL_00004 no está referenciado."
"ERROR      0 001 1 000022 000022 020 000022 029 RNF7031 I 00 054 El nombre o indicador BEPGMNP001 no está referenciado."
"ERROR      0 001 1 000111 000111 014 000111 019 RNF7031 I 00 050 El nombre o indicador SQFAPP no está referenciado."
"ERROR      0 001 1 000109 000109 014 000109 019 RNF7031 I 00 050 El nombre o indicador SQFCRT no está referenciado."
"ERROR      0 001 1 000110 000110 014 000110 019 RNF7031 I 00 050 El nombre o indicador SQFOVR no está referenciado."
"ERROR      0 001 1 000108 000108 014 000108 018 RNF7031 I 00 049 El nombre o indicador SQFRD no está referenciado."
"ERROR      0 001 1 000051 000051 011 000051 016 RNF7031 I 00 050 El nombre o indicador SQLAID no está referenciado."
"ERROR      0 001 1 000053 000053 011 000053 016 RNF7031 I 00 050 El nombre o indicador SQLABC no está referenciado."
"ERROR      0 001 1 000055 000055 011 000055 016 RNF7031 I 00 050 El nombre o indicador SQLCOD no está referenciado."
"ERROR      0 001 1 000057 000057 011 000057 016 RNF7031 I 00 050 El nombre o indicador SQLERL no está referenciado."
"ERROR      0 001 1 000059 000059 011 000059 016 RNF7031 I 00 050 El nombre o indicador SQLERM no está referenciado."
"ERROR      0 001 1 000061 000061 011 000061 016 RNF7031 I 00 050 El nombre o indicador SQLERP no está referenciado."
"ERROR      0 001 1 000063 000063 011 000063 016 RNF7031 I 00 050 El nombre o indicador SQLER1 no está referenciado."
"ERROR      0 001 1 000064 000064 011 000064 016 RNF7031 I 00 050 El nombre o indicador SQLER2 no está referenciado."
"ERROR      0 001 1 000065 000065 011 000065 016 RNF7031 I 00 050 El nombre o indicador SQLER3 no está referenciado."
"ERROR      0 001 1 000066 000066 011 000066 016 RNF7031 I 00 050 El nombre o indicador SQLER4 no está referenciado."
"ERROR      0 001 1 000067 000067 011 000067 016 RNF7031 I 00 050 El nombre o indicador SQLER5 no está referenciado."
"ERROR      0 001 1 000069 000069 011 000069 017 RNF7031 I 00 051 El nombre o indicador SQLERRD no está referenciado."
"ERROR      0 001 1 000071 000071 011 000071 016 RNF7031 I 00 050 El nombre o indicador SQLWN0 no está referenciado."
"ERROR      0 001 1 000072 000072 011 000072 016 RNF7031 I 00 050 El nombre o indicador SQLWN1 no está referenciado."
"ERROR      0 001 1 000073 000073 011 000073 016 RNF7031 I 00 050 El nombre o indicador SQLWN2 no está referenciado."
"ERROR      0 001 1 000074 000074 011 000074 016 RNF7031 I 00 050 El nombre o indicador SQLWN3 no está referenciado."
"ERROR      0 001 1 000075 000075 011 000075 016 RNF7031 I 00 050 El nombre o indicador SQLWN4 no está referenciado."
"ERROR      0 001 1 000076 000076 011 000076 016 RNF7031 I 00 050 El nombre o indicador SQLWN5 no está referenciado."
"ERROR      0 001 1 000077 000077 011 000077 016 RNF7031 I 00 050 El nombre o indicador SQLWN6 no está referenciado."
"ERROR      0 001 1 000078 000078 011 000078 016 RNF7031 I 00 050 El nombre o indicador SQLWN7 no está referenciado."
"ERROR      0 001 1 000079 000079 011 000079 016 RNF7031 I 00 050 El nombre o indicador SQLWN8 no está referenciado."
"ERROR      0 001 1 000080 000080 011 000080 016 RNF7031 I 00 050 El nombre o indicador SQLWN9 no está referenciado."
"ERROR      0 001 1 000081 000081 011 000081 016 RNF7031 I 00 050 El nombre o indicador SQLWNA no está referenciado."
"ERROR      0 001 1 000082 000082 011 000082 017 RNF7031 I 00 051 El nombre o indicador SQLWARN no está referenciado."
"ERROR      0 001 1 000084 000084 011 000084 016 RNF7031 I 00 050 El nombre o indicador SQLSTT no está referenciado."
"ERROR      0 001 1 000095 000095 015 000095 026 RNF7031 I 00 054 El nombre o indicador SQLCLSE... no está referenciado."
"ERROR      0 001 1 000099 000099 015 000099 026 RNF7031 I 00 054 El nombre o indicador SQLCMIT... no está referenciado."
"ERROR      0 001 1 000091 000091 015 000091 026 RNF7031 I 00 054 El nombre o indicador SQLOPEN... no está referenciado."
"FILEEND    0 001 000231"

**Comment by worksofliam** [comment]
Looks like the same issue as #562.

I would recommend check out [this comment](https://github.com/halcyon-tech/vscode-ibmi/issues/562#issuecomment-1132559069) and the one below it. It's to do with your system setup.
