### ISSUE TITLE
Rename "Connection Profiles"

### ISSUE THREAD

**Issue by chrjorgensen** [halcyon-tech/vscode-ibmi#766]
**Is your feature request related to a problem? Please describe.**
IMHO the wording `Connection Profiles` may not be the best choice. It makes me think of the IBM i connection, but this is more about environments _inside_ the connection - the library list, object/member filters, IFS filters and custom variables.

**Describe the solution you'd like**
`Connection Profiles` could be reduced to just `Profiles` or changed to `Environments`. Since the settings in the profile are not about the connection to the server but about what is shown from the server, at least `Connection` should be removed from the title.

**Comment by worksofliam** [comment]
You are very right. I think we'll go with 'Profiles' to keep the familiarity for existing users.

This will be part of PR #761.
