### ISSUE TITLE
Deleting a new action deletes the last action in the Actions list

### ISSUE THREAD

**Issue by Wright400** [halcyon-tech/vscode-ibmi#772]
# Issue:
  Deleting a brand new action deletes the last action in your Actions list

# Steps to recreate:

1. Click `Actions` on lower bar
2. Click `New Action` button
3. Scroll down to `Delete` button and click it
4. When prompted to delete click `Yes`
5. The last item on `Actions` should now be gone

# Desired result:
 Nothing. Should just return to Actions list.

---

* QCCSID: 273
* Features enabled:
   * git: true
   * grep: true
   * tn5250: true
   * setccsid: true
   * GENCMDXML.PGM: false
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: false

```json
[
  {
    "command": "system \"CRTLIB LIB(JWRIGHT1) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPD0032: Not authorized to command CRTLIB in library *LIBL.\nCPF0006: Errors occurred in command.",
    "cwd": "/home/JWRIGHT"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPTOIMPF in library QSYS not found.",
    "cwd": "/home/JWRIGHT"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found.",
    "cwd": "/home/JWRIGHT"
  }
]
```

**Comment by chrjorgensen** [comment]
Bug confirmed - will by fixed by PR #774
