### ISSUE TITLE
Run Action shows partial matches on extensions

### ISSUE THREAD

**Issue by Wright400** [halcyon-tech/vscode-ibmi#773]
# Issue:

When action is defined with:
```
"extensions": [
      "RPGLE"
    ]
```

Run action (Ctrl+E) will show this action for .RPGLE and .SQLRPGLE.

# Expected behavior:
"RPGLE" should exact match .RPGLE and not partially match

---

* QCCSID: 37
* Features enabled:
   * git: false
   * grep: false
   * tn5250: true
   * setccsid: true
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: true

```json
[
  {
    "command": "system \"CRTLIB LIB(JWRIGHT) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library JWRIGHT already exists.",
    "cwd": "/home/JWRIGHT"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPTOIMPF in library QSYS not found.",
    "cwd": "/home/JWRIGHT"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found.",
    "cwd": "/home/JWRIGHT"
  }
]
```

**Comment by worksofliam** [comment]
Fixed and released in 1.5.1
