### ISSUE TITLE
Can't find Member in EVFEVENT. Appears to be using different logic than RDi to determine library

### ISSUE THREAD

**Issue by Wright400** [halcyon-tech/vscode-ibmi#779]
### Preface:
We've custom built a source control tool that can be called from RDi by modifying the compile commands much like Code for IBM i's Custom Actions.

It sets the library list, runs a compile command located at the top of each program source (based on Thomas Raddatz's pre-compiler), and compiles and promotes the object to our production server.

This process including sending the EVFEVENT back works in RDi.

**We did first review internally before considering this was a Code for IBM i bug as this is a non-standard way of compiling objects. Only after we had a suspected cause did we feel it was appropriate to submit this issue to you as we believe the goal would be for the extension to have similar logic to the way RDi handles event files. If you disagree we can explore alternatives such as trying to force our event files back to the source library only when compiling from vscode.**

# Issue
We are running a command in one library (PRDSRC) that changes the library list, compiles a program in a specified library, then returns the event file.

This command executes just fine using a custom action, but the event file is not returned.

### Output for Code for IBM i
Truncated the compile listing as it's bloated. Like I mentioned it compiles fine.  Here you can see the error that the CPYTOIMPF failed. This is because it's looking in `PRDSRC` for the member when the member was actually created in `DECONP` and we updated the LDA accordingly.

```json
    * *   E N D   O F   C O M P I L A T I O N   * * * * *",
    "stderr": "RNS9304:  Program DD0248R placed in library DECONP. 00 highest severity. Created on 07/25/22 at 15:09:17.\nCPC0904:  Data area RETURNCODE created in library QTEMP."
}

/home/JWRIGHT: system "QSYS/CPYTOIMPF FROMFILE(PRDSRC/EVFEVENT DD0248R) TOSTMF('/tmp/vscodetemp-O_yInhj7lv') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD) "
{
    "code": 255,
    "signal": null,
    "stdout": "",
    "stderr": "CPF2803: To-file EVFEVENT in PRDSRC not allowed.\nCPF2817: Copy command ended because of error."
}
```

# Run Action Command
`SRCARC MBR(&OPENMBR) OPTION(*EVENTF) LIB(&OPENLIB) FILE(&OPENSPF) TASK(COMPILE)`

Here &OPENLIB is correct as our SRCARC command expects the source library. It is  `PRDSRC` here.

# Custom Pre-compiler script

The SRCARC command will read the top of the RPG program for compile commands. Here it uses the standard &LI replacement variable that would insert in the object library. In our case that would be set to  `DECONP`
```rpgle
  // >>PRE-COMPILER<<
  //
  //   >>TASK 11976<<
  //   >>CMD<<  CHGENV DECON2;
  //
  //   >>CRTCMD<< CRTSQLRPGI   OBJ(&LI/&OB) +
  //                           SRCFILE(&SL/&SF) +
  //                           SRCMBR(&SM) +
  //                           OBJTYPE(*PGM) OPTION(*EVENTF);
  //
  //   >>EXECUTE<<
  //
  // >>END-PRE-COMPILER<<
```

# Suspected Cause
We found for RDi to properly locate our event files the library had to be populated in the LDA:

```rpgle
    // Set *LDA to let RDi know where to find Event File
    sCmd = 'CHGDTAARA DTAARA(*LDA (1 10)) VALUE(' + %trim(sa_Globals.sObjLib) + ')';
    system(sCmd);
    sCmd = 'CHGDTAARA DTAARA(*LDA (11 10)) VALUE(' + %trim(sa_Globals.sSrcMbr) + ')';
    system(sCmd);
```

It appears that the extension is either not using the LDA or incorrectly putting either the Source Library or Library of the Command being executed rather than the Object Library.

## Note
We can get it to work and find the event file if compile into the Source Library. So we know nothing is wrong with the format of our EVFEVENT file.

---

* QCCSID: 37
* Features enabled:
   * git: false
   * grep: false
   * tn5250: true
   * setccsid: true
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: true

```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/JWRIGHT"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPTOIMPF in library QSYS not found.",
    "cwd": "/home/JWRIGHT"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found.",
    "cwd": "/home/JWRIGHT"
  }
]
```

**Comment by worksofliam** [comment]
@Wright400 great issue report. When you run the action, the very last thing should be a note about where it's fetching errors from. Can you find that and share it here as well?

**Comment by Wright400** [comment]
The issue had the Output from the Output view with Code for IBM i selected.

Here's the bottom of the Output from "IBM i Output"

```
   Message Totals:
     Information  (00) . . . . . . . :     2897
     Warning      (10) . . . . . . . :        0
     Error        (20) . . . . . . . :        0
     Severe Error (30+)  . . . . . . :        0
     ---------------------------------  -------
     Total . . . . . . . . . . . . . :     2897
   Source Totals:
     Records . . . . . . . . . . . . :     3560
     Specifications  . . . . . . . . :     2073
     Data records  . . . . . . . . . :        0
     Comments  . . . . . . . . . . . :     1451
          * * * * *   E N D   O F   F I N A L   S U M M A R Y   * * * * *
 Program DD0248R placed in library DECONP. 00 highest severity. Created on 07/25/22 at 16:49:49.
           * * * * *   E N D   O F   C O M P I L A T I O N   * * * * *

Fetching errors from PRDSRC/DD0248R.
```

**Comment by worksofliam** [comment]
> SRCARC MBR(&OPENMBR) OPTION(*EVENTF) LIB(&OPENLIB) FILE(&OPENSPF) TASK(COMPILE)
> 
> Here &OPENLIB is correct as our SRCARC command expects the source library. It is PRDSRC here.

So this is why it doesn't work like RDi: Code for IBM i does not read from the LDA. Each compile command is run in a new job, so we/Code for IBM i has no way to get that value.

This is how we determine what library to get the errors from:

1. We default to the library where the source exists by default
2. In the event that the object path is part of the command, we then use the library from that. For example, if the command has `PGM`, `OBJ`, `MODULE` (and a few others), then we get the full path from that since the errors are created in the same library.

Example:

```
CRTCBLMOD MODULE(DEVOBJ1/PRCORD) SRCFILE(DEVSRC1/QCBBLESRC) OPTION(*SOURCE) DBGVIEW(*SOURCE)
```

From this we know the fetch the errors from `DEVOBJ1`, even though the source code is in `DEVSRC1` because we are looking at the `MODULE` parameter for a qualified path.

Since your command does not provide one of those 'standard' parameters (like all the IBM compilers) and you are overriding the build library with your tool, Code for IBM i is looking in the 'wrong' library.

Right now, I am not sure what the right thing to do is. In theory, we're doing what we can to support the IBM way, though after you read this I'd love to hear if you have any ideas.

**Comment by worksofliam** [comment]
If your build command (`SRCARC`) simply copied the member back to the source build library, that'd probably solve the problem quickly. I am totally open to suggestions on how I can make this better in the extension, though.

**Comment by Wright400** [comment]
@worksofliam thanks a ton for explaining how the library selection logic works without LDA access. We did suspect doing everything over SSH there might be a reason you weren't using the LDA. No access definitely explains that.

As far as solution goes you and I are on the same page. I was just about to write that the easiest solution sounds like writing the member to both Source and Object libraries. I'll be coding that up now. It should keep both the extension and RDi happy.

Just add this to the list of reasons I'm not a fan of the LDA.

**Comment by worksofliam** [comment]
@Wright400 Awesome! Happy to explain it. Maybe it might be worth me adding to the docs how Code for IBM i fetches the errors. Feel free to keep this open and ask more questions, but do close whenever you're comfy.

**Comment by Wright400** [comment]
Happy to close the issue. I've got a solution for our build tool and anyone else who might face the same issues should be able to use this solution.
