### ISSUE TITLE
Ignore 7031 warnings from external sources

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#781]
**Is your feature request related to a problem? Please describe.**
In the settings config, I can tell the extension to ignore compile message ids, like 7031.  However, I don't want to ignore all those. Only those that come from external sources like DCL-F, /COPY, etc.  

**Describe the solution you'd like**
Please consider looking at the sequence value being greater than 6 digits and ending with the letter 'D'.  Example, `42000007D`.    Maybe a separate settings item that makes me check it on to ignore external source 7031 warnings?

**Describe alternatives you've considered**
I have no other alternative I have the capability to achieve at this moment. 

**Additional context**
I want to be able to find code items internally that I no longer use and remove that code.  I cannot remove fields from files that are used or unused items from /COPY members.

**Comment by worksofliam** [comment]
Interesting idea, but a lot harder to implement than it seems.

**Comment by m-tyler** [comment]
Well, no harm in asking.  :-)

**Comment by worksofliam** [comment]
@m-tyler We might be able to hide errors that come from 'external sources', which in my mind means any include/copy file, but not file declarations that you mentioned.

**Comment by worksofliam** [comment]
I'm still not sure what we will do to implement this, so I am going to close now.
