### ISSUE TITLE
Still problems with CCSID

### ISSUE THREAD

**Issue by fheldt** [halcyon-tech/vscode-ibmi#783]
Issue text goes here.

* QCCSID: 1141
* Features:
   * git: false
   * grep: false
   * tn5250: false
   * setccsid: true
   * GENCMDXML.PGM: false
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: false
* Source dates enabled: true

Variants
```json
{
  "american": "%23@$",
  "local": "%23�$"
}
```

Errors:
```json
[
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Objekt QCPTOIMPF in Bibliothek QSYS nicht gefunden.",
    "cwd": "/home/HEL"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Objekt QCPFRMIMPF in Bibliothek QSYS nicht gefunden.",
    "cwd": "/home/HEL"
  },
  {
    "command": "ls -p /QOpenSys/pkgs/bin/",
    "code": 2,
    "stderr": "/QOpenSys/pkgs/bin/ not found",
    "cwd": "/home/HEL"
  }
]
```

The CCSID of QRPGLESRC is 1141.

This is without "source dates":

<img width="526" alt="image" src="https://user-images.githubusercontent.com/1674474/181521483-cfaa3350-1036-4a2c-b25f-3d36d7a6e71d.png">

And after activating "source dates":

<img width="593" alt="image" src="https://user-images.githubusercontent.com/1674474/181521747-39ec6156-d90b-4e1c-a514-5b9dce42a95b.png">

So if I leave the "source date" setting to false, I can edit all RPG files (although the source date will be set to 000000 on saving.

Interestingly at least since the last version it shows the text in the member list correctly:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/1674474/181522810-574f80c6-790d-4942-bf98-b9ea58bb9e7a.png">

**Comment by worksofliam** [comment]
@chrjorgensen Funny I just updated the initial support text to include variants!

**Comment by worksofliam** [comment]
@fheldt 

It sure does have something to do with the SQL program we are using to fetch data. What is your user profile CCSID setup with?

**Comment by worksofliam** [comment]
@fheldt Please also share the source file CCSID.

**Comment by worksofliam** [comment]
I wonder if this has something to do with how your pase environment is set up. Can you launch into a pase shell and execute `echo $LC_ALL` and share the result?

**Comment by fheldt** [comment]
The system is V7.3

The QCCSID is 1141, in my user profile I have *SYSVAL.

The CCSID of the source file (QRPGLESRC is also 1141):
<img width="617" alt="image" src="https://user-images.githubusercontent.com/1674474/181691827-9b52cf0e-7e70-4f61-a13b-e3f5e43b5f5b.png">

In WRKENVVAR LEVEL(*SYS) I have set PASE_LANG = 'DE_DE'

When i login via ssh/shell or qsh there is no LC_ALL set. Can this be the issue?

**Comment by worksofliam** [comment]
@fheldt ignore my comment about LC_ALL. But you could try setting `QIBM_PASE_CCSID` to 1208 in `WRKENVVAR *SYS` and restarting the SSHD.

Give that a go and let us know!

Side note: I think these extra steps are required because you're on 7.3.

https://www.ibm.com/docs/en/i/7.4?topic=system-default-pase-ccsid-locale-changed-utf-8

**Comment by fheldt** [comment]
Bingo! After setting QIBM_PASE_CCSID to 1208 and restarting sshd is is showing everything correctly now.

Thank you so much for your help!

PS: It might make sense to add this to the documentation.

**Comment by worksofliam** [comment]
@fheldt absolutely adding it to the docs! Awesome.

**Comment by worksofliam** [comment]
Docs updated. Thank you @fheldt!

**Comment by worksofliam** [comment]
https://halcyon-tech.github.io/vscode-ibmi/#/pages/tips/ccsid
