### ISSUE TITLE
Source Not Showing

### ISSUE THREAD

**Issue by jimjepson** [halcyon-tech/vscode-ibmi#791]
Issue Type: <b>Bug</b>

I cannot view/edit source members anymore on one of my systems?   I can see the source files but when open one, I get a blank page.  This just started in the last month or so.

SQL is not enabled in the settings and the QCCSID is 66535.

Looking at the Code for IBM i output, seems the DB2 command is not returning anything?

/home/NUJKJ: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
CREATE OR REPLACE ALIAS ILEDITOR.QGPL_QCLSRC_A_CHGUSR_C for QGPL.QCLSRC("A_CHGUSR_C")
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

/home/NUJKJ: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
select srcdat, rtrim(srcdta) as srcdta from ILEDITOR.QGPL_QCLSRC_A_CHGUSR_C
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

Extension version: 1.5.2
VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (3.86GB free)|
|Process Argv|--crash-reporter-id 3753743e-64a9-46d2-8a37-ce0176bfb9ca|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
pylanb8912:30529769
vsclangdf:30486550
c4g48928:30535728

```

</details>

**Comment by worksofliam** [comment]
@jimjepson Let's try and find the root cause. 

1. First off, launch into a pase shell (you can do this in VS Code using the Terminals button in the status bar when connected to a system)
2. Run this and share the output: `echo "select * from sysibm.sysdummy1" | LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"`

When I run it on pub400, this is what I get and you should get something similar.

```
$ echo "select * from sysibm.sysdummy1" | LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
DB2>
  ?>

IBMREQD 
--------
Y       

  1 RECORD(S) SELECTED.
```

**Comment by jimjepson** [comment]
Here is what I get:

echo "select * from sysibm.sysdummy1" | LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
DB2>
$

**Comment by worksofliam** [comment]
@jimjepson i also need you to do this through a pase shell that is not QP2TERM. You can SSH into IBM i through any client (like putty), but also through VS Code like I mentioned before.

**Comment by jimjepson** [comment]
Here are the results from putty:

$ echo "select * from sysibm.sysdummy1" | LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
DB2>
$

**Comment by worksofliam** [comment]
@jimjepson this is likely an issue with some SSHD setup. I've seen this before and can share more details on or before Monday.

**Comment by worksofliam** [comment]
@jimjepson Check out this comment and the one after it. It's the exact problem you were having.

https://github.com/halcyon-tech/vscode-ibmi/issues/562#issuecomment-1132559069

**Comment by jimjepson** [comment]
I stoped and restarted the SSHD server with ENDTCPSVR SERVER(*SSHD) followed by a STRTCPSVR SERVER(*SSHD).   It is working again!

Thank you!
