### ISSUE TITLE
New command API to easily get/set custom variables

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#809]
Command should probably be defined [here](https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/webviews/variables/index.js#L13) or in CompileTools.

**Comment by merhovon** [comment]
It would be great if the action variables could be accessed under custom variables and if regular expressions were supported.

**Comment by worksofliam** [comment]
Can be done through the exposed configuration API now.
