### ISSUE TITLE
Testing for IBM i Extension

### ISSUE THREAD

**Issue by n8bush** [halcyon-tech/vscode-ibmi#816]
Was trying out the IBM i Tests example and get: 
Error running command testing-ibmi.runSelectedTest: e.split is not a function. This is likely caused by the extension that contributes testing-ibmi.runSelectedTest.

Output of Log(Extension Host) is:
[2022-08-17 08:50:27.163] [exthost] [error] TypeError: e.split is not a function
	at /Users/nbush/.vscode/extensions/halcyontechltd.testing-ibmi-0.0.5/extension.js:80:29
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async a._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:63914)
	at async /Users/nbush/.vscode/extensions/halcyontechltd.testing-ibmi-0.0.5/src/views/testView.js:21:9
	at async a._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:63914) testing-ibmi.runSelectedTest {"value":"halcyontechltd.testing-ibmi","_lower":"halcyontechltd.testing-ibmi"}

* QCCSID: 37
* Features:
   * git: true
   * grep: true
   * tn5250: true
   * setccsid: true
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: true

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Errors:
```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/NBUSH/Development/dmsapi/"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPTOIMPF in library QSYS not found.",
    "cwd": "/home/NBUSH/Development/dmsapi/"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found.",
    "cwd": "/home/NBUSH/Development/dmsapi/"
  }
]
```

**Comment by worksofliam** [comment]
@n8bush No idea how you got hold of the extension! It's been deprecated a while back and shouldn't be available on the marketplace any longer.

Sorry!

**Comment by n8bush** [comment]
@worksofliam No prob, installed awhile back. Just got to trying it out. 

Thanks.
