### ISSUE TITLE
I lost the ability to see my connections after upgrading to 1.5.6

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#822]
The VS Code extension reporting features don't work unless you are connected. 

**Describe the bug**
Upgraded to 1.5.6 from 1.5.5 and I no longer see my connection in the list

Before:
![image](https://user-images.githubusercontent.com/1353665/185650182-de26bfbc-4bd0-4523-a1c9-4106125be93c.png)

After:
![image](https://user-images.githubusercontent.com/1353665/185650135-9f4266c8-5350-4c94-8399-2fbfaa69b43c.png)

Looking in the settings.json document all my connections and filters are still there. 

I have reverted back to 1.5.5 and they appear again.

**Comment by worksofliam** [comment]
Weird. No issue here on 1.5.6: 

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/3708366/185651914-c7801981-997c-4bef-9ba9-a25eb45e93e5.png">

**Comment by m-tyler** [comment]
Any way to turn on a start-up logger?  Maybe see a message if there is another extension interfering?  By the way, I am at VSC 1.70.2.

**Comment by m-tyler** [comment]
Okay, new stuff.  I tried to recreate my connection to see what happens.
![image](https://user-images.githubusercontent.com/1353665/185652962-0d29db2d-611e-4fa8-a9d2-b5b177830ba4.png)

**Comment by worksofliam** [comment]
Oh, that is weird. Have you tried uninstalling the extension and reinstalling the extension at all?

**Comment by m-tyler** [comment]
It works when I downgrade to 1.5.5 but I have not tried to completely remove the extension. 

Extension not installed.
![image](https://user-images.githubusercontent.com/1353665/185654399-7116d555-3ec6-4139-846a-13ae9ad39a37.png)

Extension installed via `IBM i Development Pack v0.0.8`
![image](https://user-images.githubusercontent.com/1353665/185655160-06ddcf7d-01ae-47f3-8e94-f0ede8effe58.png)

Whoo! Hoo!  Back to working!  

Is there an easier way to uninstall using the Development pack?

**Comment by worksofliam** [comment]
@m-tyler weird. It's entirely possible that something went wrong with the installation. 1.5.6 didn't really touch anything to do with connections.

**Comment by m-tyler** [comment]
Well at least I know a way to attempt to resolve this issue if it appears again.
