### ISSUE TITLE
Object context options

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#826]
There are no co text options for objects in the object browser.

**Comment by worksofliam** [comment]
One was added, but more would still be nice :)

**Comment by Wright4i** [comment]
Agreed, we need at least 2

**Comment by Wright4i** [comment]
@worksofliam this can be closed (handled in PR #882) unless you have additional ideas for context options?

**Comment by worksofliam** [comment]
@Wright4i Nope, you're spot on. Closing!
