### ISSUE TITLE
Compile error markers no longer appear

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#849]
After updating to 1.5.9 or 1.5.10 I no longer get embedded compile errors markers in the source.  I have to search through the `IBM I Output` view to see what the issue is.   The main issue I have with doing this is the tool will reload information for the open member into that output view and cause the view to scroll.  If I don't clear the view before compiling and I don't open the source listing right away I have to clear and recompile.

Is there a new setting I'm not seeing?

* QCCSID: 37
* Features:
   * git: true
   * grep: true
   * tn5250: false
   * setccsid: true
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: true

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Notice the red outlined source quick view does not show the red marker.
![image](https://user-images.githubusercontent.com/1353665/187772588-e4868d84-e850-48bd-bc42-996e86c36493.png)

**Comment by worksofliam** [comment]
After you run an Action, scroll to the bottom of IBM i Output below the spool file. You should see a message about `*EVENTF`. What does it say?

**Comment by m-tyler** [comment]
![image](https://user-images.githubusercontent.com/1353665/187774217-0b23f94d-3a1f-416d-af3a-aac5e303988d.png)

**Comment by worksofliam** [comment]
Ok. After trying a compile, please paste the output from the Code for IBM i output channel here.

**Comment by m-tyler** [comment]
[Code for IBMi - output channel.txt](https://github.com/halcyon-tech/vscode-ibmi/files/9464805/Code.for.IBMi.-.output.channel.txt)

**Comment by worksofliam** [comment]
Ok. I can see the command being executed to grab the file.

```
QSYS/CPYTOIMPF FROMFILE(PGXX/EVFEVENT TESTPRPSP5) TOSTMF('/home/PGXX/tmp/vscodetemp-O_BS3aQhJd') MBROPT(*REPLACE) STMFCCSID(1208) RCDDLM(*CRLF) DTAFMT(*DLM) RMVBLANK(*TRAILING) ADDCOLNAM(*SQL) FLDDLM(',') DECPNT(*PERIOD)
```

Any chance you can grab this member for me? You should run that command yourself to a different streamfile and upload it here.

**Comment by worksofliam** [comment]
Also, can you confirm that `PGXX` from `FROMFILE(PGXX/EVFEVENT TESTPRPSP5)` is the same library you're compiling the object in?

**Comment by m-tyler** [comment]
Okay, I'm sorry for wasting your time. I did not notice that the tool was using the default CPYTOIMPF command instead of the one my company has me use (as we have not migrated off the old 5.1 version of the command yet).   The default command you supply causes the data in the tmp/folder to be code page 37 instead of 1208.  

This is the reason I asked for a change in #493.  

Thanks for the assist showing me I forgot to make a change to the tool.
