### ISSUE TITLE
If SSH connection disconnects/times out, cannot re-connect unless I close all open files. 

### ISSUE THREAD

**Issue by richardschoen** [halcyon-tech/vscode-ibmi#85]
I cannot use the connect options if the SSH connection times out because I get an error that files are already open, so I am in a catch 22 situation.  Can't reconnect. And can't exit without losing changes to my open IFS files or members.

It would be nice to simply re-connect and then be able to save my open file members without having to copy/paste my in flight changes to another editor so I don't lose them. 

I seem to recall you put this check in based on someone else's request, but at minimum allow me to disable this check with a setting perhaps.

In my scenario my remote SSH connection from the IBMi was disconnecting over a VPN so essentially the IBMi was closing the connection and the editor didn't know about it until I tried to save a file. 

Hope this makes sense. Doesn't happen too often but I lose some changes because of this issue until I know that I needed to copy my changes somewhere else  so as not to lose data.

**Comment by worksofliam** [comment]
We need to add some basic event handler to close all the open documents from the connection when it disconnects from an error.

**Comment by richardschoen** [comment]
If you close all documents the dev will lose in flight edits. 

They need to be able to reconnect without losing where they are at if possible.

**Comment by worksofliam** [comment]
We need to add a keepalive. The SSH timeout doesn't achieve this.

**Comment by onewheelonly** [comment]
The "ServerAliveInterval" SSH option may do what you want, here.

**Comment by richardschoen** [comment]
I'm not sure how the VS Code SSHFS plugin does it, but if I lose a connection and then close and re-open VS Code it somehow knows what I had open and opens everything back to where it was. Not sure if it maintains temporary files or something similar.

**Comment by worksofliam** [comment]
@onewheelonly I just realised while I was looking into this issue that we already set the keep alive that node-ssh/ssh2 uses. 

https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/api/IBMi.js#L45

I wonder if there is an underlying bug in one of those libraries.

**Comment by worksofliam** [comment]
Okay, so for the time being I've added a message when the timeout event happens. When this happens, you can select `Yes` and have Code for IBM i reconnect to the connection.

I am about to release this. Please post back your results here.
