### ISSUE TITLE
Unable to open member with "color codes" and german characters

### ISSUE THREAD

**Issue by LGSDEVS** [halcyon-tech/vscode-ibmi#860]
**Describe the bug**
I use color codes to mark the source code, unfortunately the VSC can't handle it. Also, special characters from the German language such as the "ß" are not recognized and output correctly.

**Screenshots**
color codes:
![bugvsc](https://user-images.githubusercontent.com/105491016/189126304-171db451-bcf4-4a98-ae36-1a671d4c42b5.png)

german characters
![grafik](https://user-images.githubusercontent.com/105491016/189126882-672a1b12-0a27-41ce-8cf7-1fbf9026abc3.png)

**Comment by worksofliam** [comment]
@LGSDEVS Did you also fix your env vars?

**Comment by worksofliam** [comment]
@LGSDEVS can you give it a try anyway, and let us know what you find?

**Comment by worksofliam** [comment]
Also, is SQL enabled and what CCSID is the source file?

**Comment by worksofliam** [comment]
@LGSDEVS Are you able to do a hex dump of that source member so I can do some further investigation? It likely has something to do with the conversion from EBCDIC to 1208 that is causing the colours to not work.

**Comment by worksofliam** [comment]
@LGSDEVS Do you get the same result if you enable SQL and try to open the member again?

**Comment by DannyRidgway** [comment]
I have the same issue with the special colour characters too.
![image](https://user-images.githubusercontent.com/37447074/192527375-fe2f7c34-ce15-40d9-a521-139b9d8f1a41.png)
![image](https://user-images.githubusercontent.com/37447074/192527500-d16cd972-25b8-4972-a66d-5b6b95f5de0a.png)

**Comment by worksofliam** [comment]
@DannyRidgway what is the source file CCSID and do you have source dates enabled or disabled?

**Comment by worksofliam** [comment]
@LGSDEVS @DannyRidgway Any chance you can recreate this on pub400 and give me access to your libraries? My user profile is `BARRY` on there.
