### ISSUE TITLE
compiling command (action) does not respect library list

### ISSUE THREAD

**Issue by andigoering** [halcyon-tech/vscode-ibmi#873]
Hi!
I am struggling with my own compiling command and found that the library list is obviously not used when the command run.
First it did not find the command.
Then i qualified the command with the library, which results in pgm behind not found.
Then i added prodlib to the command that results in compile is missing copy and file references.

In the output it looks good...
Current library: QGPL
Library list: QGPL QTEMP $ISDSO $ISDSD $ISDSS $IS $ISTOOLS
Commands:
		$IS/CRTSKYPGM DEBUG('*YES')  SRCLIB($ISDSS) PGM(R1SB6000R) TYPE(SQLRPGLE) LANG('EN') OPTION(*EVENTF)

* QCCSID: 273
* Features:
   * git: false
   * grep: false
   * tn5250: false
   * setccsid: true
   * GENCMDXML.PGM: false
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: false
* Source dates enabled: true

Variants
```json
{
  "american": "%23@$",
  "local": "%23§$"
}
```

Errors:
```json
[
  {
    "command": "system \"CRTLIB LIB(CODE4IAG) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Bibliothek CODE4IAG bereits vorhanden.",
    "cwd": "/home/ag"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Objekt QCPTOIMPF in Bibliothek QSYS nicht gefunden.",
    "cwd": "/home/ag"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Objekt QCPFRMIMPF in Bibliothek QSYS nicht gefunden.",
    "cwd": "/home/ag"
  }
]
```

**Comment by worksofliam** [comment]
Likely something to do with the dollar signs.

Please share the contents of your Code for IBM i output channel after attempting your issue.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by andigoering** [comment]
hi! thx for the prompt response.
Which part you need?
It is a lot in the output....

**Comment by worksofliam** [comment]
@andigoering If you send it all I can easily find what I am looking for!

**Comment by andigoering** [comment]
[neu 55.txt](https://github.com/halcyon-tech/vscode-ibmi/files/9595076/neu.55.txt)

**Comment by andigoering** [comment]
the outline view also not works for me, maybe same reasons?

**Comment by worksofliam** [comment]
@andigoering This has something to do with the dollar signs in the name. I will need to push a fix for this. Thanks!

**Comment by andigoering** [comment]
Liam, thank you for the quick investigation. I will try a workaround to include something into my command and reset the library list myself. Is this also the reason for the outline not working?

**Comment by worksofliam** [comment]
It might well be, yes.

**Comment by andigoering** [comment]
strange....
so is there any way, i mean anything i can do. like to run a (remote) command that makes sure the library list is that in right way?
I really would like to go ahead with this tool and want to introduce to my team as well, but the current issue is a show stopper unfurtunatly.
Andi

**Comment by worksofliam** [comment]
@andigoering I am going to fix it today - I will post back when it is done :)

**Comment by worksofliam** [comment]
@andigoering It is not done yet. I have created the fix for some testing in a new branch. I need to work with it a bit more and then it will be out tomorrow.

**Comment by andigoering** [comment]
thank you so much

**Comment by andigoering** [comment]
Liam, thank you for the instant fix.
what do i need to do to get the fix?

**Comment by worksofliam** [comment]
@andigoering The release will be going out in the next hour. I will reply back here when it is available.

**Comment by worksofliam** [comment]
@andigoering a new update is out (1.5.12) and VS Code should update automatically or show you that there is an update available.

Give it a go and let me know.

**Comment by andigoering** [comment]
Terrific! It is working fine!! Thank you so much!

**Comment by worksofliam** [comment]
@andigoering So glad to hear that! You might be the first person to have raised this issue, which leads me to believe that using `$` in library/object names is not that common!
