### ISSUE TITLE
Detect record length, even for source files with no existing data

### ISSUE THREAD

**Issue by bdietz400** [halcyon-tech/vscode-ibmi#883]
With an existing source file with record length of 112.

right click to create a new member and paste some code that extends past column 80.
i see "error" that 'content past record lenght of 80'

Extension version: 1.5.15
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by worksofliam** [comment]
@bdietz400 Do you have source dates enabled or disabled?

**Comment by worksofliam** [comment]
Guessing enabled.

Please share the contents of your Code for IBM i output channel after restarting VS Code and recreating the issue.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by bdietz400** [comment]
Enable source dates is checked.
re create progressing....

**Comment by bdietz400** [comment]
![past80](https://user-images.githubusercontent.com/7241553/192364711-e661ecb2-7446-4996-b21f-951339c3139f.jpg)
[past80.txt](https://github.com/halcyon-tech/vscode-ibmi/files/9649232/past80.txt)

**Comment by worksofliam** [comment]
So I can see it's running this:

```
SELECT LENGTH(srcdta) as LENGTH FROM ILEDITtmp.VSCODE_SOURCE112_CODEPAST80 limit 1
```

And returning

`LENGTH: 0`.

This might be because it's a brand new source file with no existing members in! Does this error also appear on new members in existing source files with members in them?

**Comment by bdietz400** [comment]
it happens when there are existing member and a new one is created.
once the member exists there are no problems

**Comment by worksofliam** [comment]
@Wright4i I forget.. did we release this yet?

**Comment by Wright4i** [comment]
@worksofliam we in fact have not released this yet. Actually, that reminds me.. we also need to release the ibm-i-development-pack after [PR#5](https://github.com/halcyon-tech/ibm-i-development-pack/pull/5). I watched you demo then have to separately add in the Display Renderer extension!

**Comment by worksofliam** [comment]
@Wright4i i can do that soon!
