### ISSUE TITLE
Detect variables in `iproj.json` and `.ibmi.json`

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#897]
1. When the project is opened and the extension is connected, scan the local workspace to find the `iproj.json` and the many possible `.ibmi.json` files.
2. Find all the possible variables used inside of those files. Usually a variable starts with `&`.
3. If no `.env` exists, automatically create a `.env` with those variables found so the user can provide values. Set the initial value to `*CURLIB` for each variable

**Comment by beckhamrryyaann** [comment]
excited about this functionality.

**Comment by worksofliam** [comment]
Will be part of the Project Mode extension being developed by IBM.
