### ISSUE TITLE
Unable to Install Code for IBM i - Getting - 'Couldn't find a compatible version of Code for IBM i with this version of Code'  errorr. 

### ISSUE THREAD

**Issue by digvijay2k2** [halcyon-tech/vscode-ibmi#904]
Hi , 

Trying to install 'Code for IBM i' extension version 1.5.16 for VS Code version 1.7.1 and running into compatibility issues. 
Getting error 'Couldn't find a compatible version of Code for IBM i with this version of Code'  error.

Looking for help on how to resolve this error.

**Comment by digvijay2k2** [comment]
Initial Question

**Comment by worksofliam** [comment]
@digvijay2k2 

* What OS are you on?
* Have you tried restarting VS Code?
* What about if you start VS Code and reload? (Command Palette -> Reload Window)

**Comment by digvijay2k2** [comment]
Hi Liam, 

I am on windows 10.
Based on your suggestion I did try restarting VS code as well as doing a reload but still running into same issue.  

I did try installing some other extension (Eg RPG for IBM i) and was able to install but facing compatible version issue with both Code for IBM i as well as IBM i development pack.  
 
![image](https://user-images.githubusercontent.com/108098862/195185687-10284add-3d48-4f3c-83bf-2434bbe52e36.png)

**Comment by worksofliam** [comment]
I am going to need some more information about your VS Code setup.

I am on the latest version and we are not getting the same issue. Can you share the File -> About Visual Studio Code? It should show something like this:

<img width="1094" alt="Screenshot 2022-10-11 at 9 19 18 PM" src="https://user-images.githubusercontent.com/3708366/195227009-a3864517-d25b-4f9f-a7bb-07aaeb453e2e.png">

**Comment by digvijay2k2** [comment]
Sure.

![image](https://user-images.githubusercontent.com/108098862/195231888-45ef723a-13b8-4bfc-a68f-1995648e8cbf.png)

**Comment by worksofliam** [comment]
@digvijay2k2 You are on a seriously old version of Visual Studio Code. Please update :)

**Comment by digvijay2k2** [comment]
Thank you Liam , sorry my bad I miss-read 1.7.1 as 1.71 and did not realize that I am on a very old version. Will get this updated and try again.  Thanks again !!
