### ISSUE TITLE
library List issues

### ISSUE THREAD

**Issue by bigbearjeff63** [halcyon-tech/vscode-ibmi#909]
I am just getting things setup and was adding libraries to my User Library List. It seemed to be going well, but there are a few libraries that I attempt to add that it tells me, "**The following libraries were removed from the updated library list as they are invalid:**'  These are libraries with source that I use often back in the green screen world. Any idea what may be causing this?

**Comment by bigbearjeff63** [comment]
User Error. Ignore my post

**Comment by worksofliam** [comment]
@bigbearjeff63 glad to hear you solved it! Would love to hear what we can do to make sure this doesn't happen for others in the future.
