### ISSUE TITLE
Opening source from a filter with a lib name with a dot (e.g. LIB.MORE) produces *FILE not found (42704) error.

### ISSUE THREAD

**Issue by ptkelly13** [halcyon-tech/vscode-ibmi#912]
Opening source from a filter with a lib name with a dot (e.g. LIB.MORE) produces *FILE not found (42704) error in editor screen.  "Try Again" produces Window dialogue with the same error.  (I removed the errors under Errors section as they were unrelated and contained PI.
![image](https://user-images.githubusercontent.com/29577026/196961891-858db253-64cb-4e34-b440-641f6bdb116e.png)
![image](https://user-images.githubusercontent.com/29577026/196961986-4ddcebff-9509-4a53-a019-b059db6a1074.png)
![image](https://user-images.githubusercontent.com/29577026/196962001-c24a7d4d-9fd2-4f63-a1cf-addf4384afc4.png)

* QCCSID: 37
* Features:
   * git: true
   * grep: true
   * tn5250: false
   * setccsid: true
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: true

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Errors:
```json
[

]
```

**Comment by worksofliam** [comment]
@ptkelly13 This is good info! Thanks! I am going to look into this right away. I will need some more info, though.

Please share the contents of your Code for IBM i output channel after the list doesn't appear. Please remove any PII.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3708366/178739532-03c8ad30-84de-4698-9904-65938f2ef651.png">

**Comment by ptkelly13** [comment]
No rush AT ALL.  Here is the info if I got it right.  I cleared the output and recreated the error:
/home/MSPTK: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
CREATE OR REPLACE ALIAS RCHASA43.V411.SMUS_QCLSRC_CTR0011 for V411.SMUS.QCLSRC("CTR0011")
{
    "code": 4,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\n **** CLI ERROR *****\n         SQLSTATE: 42704\nNATIVE ERROR CODE: -204\nV411 in QSYS type *LIB not found.",
    "stderr": ""
}

/home/MSPTK: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT LENGTH(srcdta) as LENGTH FROM RCHASA43.V411.SMUS_QCLSRC_CTR0011 limit 1
{
    "code": 4,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\n **** CLI ERROR *****\n         SQLSTATE: 42704\nNATIVE ERROR CODE: -204\nSMUS_QCLSRC_CTR0011 in V411 type *FILE not found.",
    "stderr": ""
}

/home/MSPTK: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
CREATE OR REPLACE ALIAS RCHASA43.V411.SMUS_QCLSRC_CTR0011 for V411.SMUS.QCLSRC("CTR0011")
{
    "code": 4,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\n **** CLI ERROR *****\n         SQLSTATE: 42704\nNATIVE ERROR CODE: -204\nV411 in QSYS type *LIB not found.",
    "stderr": ""
}

/home/MSPTK: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT LENGTH(srcdta) as LENGTH FROM RCHASA43.V411.SMUS_QCLSRC_CTR0011 limit 1
{
    "code": 4,
    "signal": null,
    "stdout": "DB2>\n  ?>\n\n **** CLI ERROR *****\n         SQLSTATE: 42704\nNATIVE ERROR CODE: -204\nSMUS_QCLSRC_CTR0011 in V411 type *FILE not found.",
    "stderr": ""
}

**Comment by worksofliam** [comment]
@ptkelly13 Good news. The PR is done and we're just waiting for it to be tested by someone else before it can be merged. This will likely happen tomorrow.

Thanks!

**Comment by worksofliam** [comment]
@ptkelly13 The release, 1.5.19, is just about to come out and you should have the update in 15 minutes or so.

Give it a try and let us know how it goes.

**Comment by ptkelly13** [comment]
> @ptkelly13 The release, 1.5.19, is just about to come out and you should have the update in 15 minutes or so.
> 
> Give it a try and let us know how it goes.

Works great for me!  Thanks much.
