### ISSUE TITLE
Member search without needing filter opened.

### ISSUE THREAD

**Issue by m-tyler** [halcyon-tech/vscode-ibmi#927]
**Is your feature request related to a problem? Please describe.**
  When wanting to search for members for a value, I don't often know where I need to look or if I need to look in the production code (which as have many thousands of members).  Opening a filter over production RPG source takes a bit of time and feels like a waste just to search. 

**Describe the solution you'd like**
Some menu item or action that brings ups a prompt that requires me to fill out the search items and then trigger the search function.  

**Describe alternatives you've considered**
I do like the quick prompt popup but for this, I think it would fit best like an action prompt form.   If its an action-style form please have the Enter key trigger the functionality. 

**Additional context**
I am not concerned about the length of time it might take to perform the search, I would like to just get it to start and then go back to something else which the search is cooking. 

Thanks, Matt

**Comment by worksofliam** [comment]
@m-tyler Just to be clear, you're talking about a member name search and not member content search - right?

**Comment by m-tyler** [comment]
I mean a member content search just like done with the right-click option on a source file.  I just want to be able to specify the (IASP?) library and file without needing open a filter to do it.

**Comment by worksofliam** [comment]
@m-tyler Now I am following along. The reason you can't do that right now is because out search function `grep` does not return the source type in the result (it returns everything as `.mbr` instead). If we can get around that limitation (e.g. finding the source type/attribute) with a fast performing system call, then we can easily do it.

**Comment by m-tyler** [comment]
ah yea, I never noticed the return results list from grep before.   

Well, thanks for entertaining the idea.

**Comment by worksofliam** [comment]
There isn't much we can do about this due to the reasons I specified above. I will close for now.

**Comment by chrjorgensen** [comment]
@m-tyler Hello, just wanted to let you know that with the new [release 1.7.4](https://github.com/halcyon-tech/vscode-ibmi/releases/tag/1.7.4https://github.com/halcyon-tech/vscode-ibmi/releases/tag/1.7.4) of the extension, it is now possible to search members and streamfiles without using any filter.

Now we just need to fix your problem #1082 so you can open the members from the search result...! 😄 

HTH.
