### ISSUE TITLE
Spurious warning in **free: Protoypes can only be defined with either `EXTPGM` or `EXTPROC`

### ISSUE THREAD

**Issue by jwoehr** [halcyon-tech/vscode-ibmi#955]
Attached streamfiles (from Redbook example 4-1) compile without warning but the editor issues a warning against the copyfile `cpym02.rpgle` that "Protoypes can only be defined with either \`EXTPGM\` or \`EXTPROC\`"

![image](https://user-images.githubusercontent.com/4604036/201261720-d22b1a45-b51d-4547-ac5a-ce6f80d1efe6.png)

* QCCSID: 37
* Features:
   * git: true
   * grep: true
   * tn5250: true
   * setccsid: true
   * GENCMDXML.PGM: false
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: false

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Errors:
```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: Library ILEDITOR already exists.",
    "cwd": "/home/JWOEHR"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPTOIMPF in library QSYS not found.",
    "cwd": "/home/JWOEHR"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found.",
    "cwd": "/home/JWOEHR"
  }
]
```
[Redbook_example_4_1.zip](https://github.com/halcyon-tech/vscode-ibmi/files/9986436/Redbook_example_4_1.zip)

**Comment by worksofliam** [comment]
It’s a lint rule. It may be valid code, but the rule specifically says that any PR must explicitly use EXTPROC or EXTPGM. This is not a bug.

**Comment by jwoehr** [comment]
Thanks @worksofliam `Dcl-Pr NonDigit ind extproc;` works for me.
