### ISSUE TITLE
Member names that include the # symbol show incorrect name in problems view

### ISSUE THREAD

**Issue by richardm90** [halcyon-tech/vscode-ibmi#964]
If I have a member name that includes the # symbol then I find this isn't referenced correctly in the problems view. It appears to treat the # symbol as a separator such that a member name of A#PGM01 is shown and hyper linked with a member name of A.

For example:

Member name = A#PGM01.rpgle

```
**FREE

dcl-s msg char(52);

msg = 'Hello ' + MY_NAME;

dsply msg;
return;
```

When I compile this member I then get the following appear in the problems view. Notice the member name is shown as A in library RICHARD, source file QSOURCE.

![image](https://user-images.githubusercontent.com/7809440/203085698-2fe4651d-5b7c-410b-83b9-7bdf45b7b868.png)

If I then click on one of the problem view rows it attempts to show member A.

![image](https://user-images.githubusercontent.com/7809440/203086286-7a1358d6-2ae4-43e2-99a9-4c09d67733d2.png)

The same is also true if a error is detected in a /include member that includes the # symbol.

* QCCSID: 1146
* Features:
   * git: true
   * grep: true
   * tn5250: false
   * setccsid: true
   * GENCMDXML.PGM: false
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: true

Variants
```json
{
  "american": "%23@$",
  "local": "%23@£"
}
```

Errors:
```json
[
  {
    "command": "system \"DLTOBJ OBJ(RICHARD/O_*) OBJTYPE(*FILE)\"",
    "code": 255,
    "stderr": "CPF2125: No objects deleted.",
    "cwd": "/home/richardm"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPTOIMPF in library QSYS not found.",
    "cwd": "/home/richardm"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found.",
    "cwd": "/home/richardm"
  }
]
```

**Comment by worksofliam** [comment]
Fixed in a90ffbe12063837a01d3b158f530fd70790b6016. Will make a release today.

**Comment by richardm90** [comment]
@worksofliam, crikey, that was nearly fixed before I even finished raising the issue!

**Comment by worksofliam** [comment]
Release going out now
