### ISSUE TITLE
Local development, deployment of changes fails after adding a new source directory.

### ISSUE THREAD

**Issue by JDubbTX** [halcyon-tech/vscode-ibmi#965]
**Describe the bug**
I am set up to develop locally and build with Bob.  I needed to add a new source file to the project, QBNDSRC in this case, and then some binding directory pseudo source for a binding directory inside.  After doing so, I attempted to 'build current' and 'deploy changes'.  The deploy fails because somehow an empty file with the same name as the directory is added to the IFS before the directory is created.

**To Reproduce**
Start with no files or directory on the IFS named 'QBNDSRC'
![image](https://user-images.githubusercontent.com/56802156/203477775-a6d2fee7-1c67-4963-a78b-c978770a5202.png)
Add the QBNDDIR directory and a source file locally, then selected 'Build current'
![image](https://user-images.githubusercontent.com/56802156/203478026-a3d0dafa-8c90-4741-a72b-17fe33dda9e5.png)
Chose to deploy only changed files
![image](https://user-images.githubusercontent.com/56802156/203478155-e49d4301-990f-4fbb-bb87-ce1ae75d78a3.png)
notification of failed deployment
![image](https://user-images.githubusercontent.com/56802156/203478259-cabe4da9-08fb-4c74-96cb-593a15ad7aca.png)
Empty file now exists with same name as the directory.  Output shows why the deployment failed
![image](https://user-images.githubusercontent.com/56802156/203478438-6fa831a2-55e4-4779-b0b4-fdc2a3d5e934.png)

**Expected behavior**
The new directory should have been added and new file deployed to the new directory

**Screenshots**
see above

**Environment (please complete the following information):**
 - Extension version [e.g. 1.5.26]
 - IBM i OS version [e.g. 7.4]

**Additional context**
This is part of an exercise to move older ROCKET ALDON LMi managed source to a new project using git / gitlab with Bob.

**Comment by worksofliam** [comment]
Issue was it was counting directories as 'new files', and then was trying to create a text file with the same name instead of a directory.

Solved in https://github.com/halcyon-tech/vscode-ibmi/commit/80589b46387a997cbabdc0b97c4948e6b706828f.

Release will be today.

**Comment by worksofliam** [comment]
1.5.27 on the way!
