### ISSUE TITLE
unable to display source members in object browser

### ISSUE THREAD

**Issue by masmithrpg** [halcyon-tech/vscode-ibmi#970]
CCSID = 37
i've tried changing 'Enable Sql' on and off
i've tried changing  show source dates on and off
i am using  
TSTMIS/QRPG*/*.*(*SRCPF)

Log below 

/home/SMITHMI: system "DSPFD FILE(TSTMIS/QRPG*) TYPE(*ATR) FILEATR(*PF) OUTPUT(*OUTFILE) OUTFILE(VSCODE/O_iHoSCHsD)"
{
    "code": 0,
    "signal": null,
    "stdout": "CPF9861: Output file O_IHOSCHSD created in library VSCODE.\nCPF9862: Member O_IHOSCHSD added to output file O_IHOSCHSD in library VSCODE.\nCPF3030: 3 records added to member O_IHOSCHSD in file O_IHOSCHSD in VSCODE.",
    "stderr": ""
}

/home/SMITHMI: LC_ALL=EN_US.UTF-8 system "call QSYS/QZDFMDB2 PARM('-d' '-i' '-t')"
SELECT * FROM VSCODE.O_iHoSCHsD
{
    "code": 0,
    "signal": null,
    "stdout": "DB2>",
    "stderr": ""
}

.: system "DLTOBJ OBJ(VSCODE/O_iHoSCHsD) OBJTYPE(*FILE)"
{
    "code": 0,
    "signal": null,
    "stdout": "",
    "stderr": ""
}

* QCCSID: %3F
* Features:
   * git: true
   * grep: true
   * tn5250: false
   * setccsid: true
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: false

Variants
```json
{
  "american": "%23@$",
  "local": "%23@$"
}
```

Errors:
```json
[
  {
    "command": "system \"DLTOBJ OBJ(VSCODE/O_*) OBJTYPE(*FILE)\"",
    "code": 255,
    "stderr": "CPF2125: No objects deleted.",
    "cwd": "/home/SMITHMI"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPTOIMPF in library QSYS not found.",
    "cwd": "/home/SMITHMI"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found.",
    "cwd": "/home/SMITHMI"
  }
]
```

**Comment by worksofliam** [comment]
Looks like this is your issue: https://halcyon-tech.github.io/docs/#/pages/tips/setup?id=no-results-from-sql-execution

**Comment by masmithrpg** [comment]
Thanks Liam
That seems to have cleared up this issue.
