### ISSUE TITLE
Safer way to confirm directory deletion

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#973]
We need a new config: 

* Safer directory deletion (boolean, false default)

* If it's false, then it will delete regular (current behaviour)
* It it's true, then it will prompt the user to confirm the directory name they're deleting, similar to how GItHub wants to the user to confirm the repo name before it gets deleted.

This came from K3S

**Comment by steph-beneschan-256** [comment]
Hello, I'll start working on this if noone else has done so yet
