### ISSUE TITLE
Rename `./src/Instance.ts`

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/vscode-ibmi#977]
We have two files named `Instance.ts`

* `./src/Instance.ts`
* `./src/api/Instance.ts`

`./src/api/Instance.ts` is the 'true' _Instance_, because the class itself is named `Instance`. `./src/Instance.ts` is just a class of exported functions used to setup the extension and hold the true _Instance_.

I propose we rename `./src/Instance.ts` to something else like `context.ts` or `setup.ts`.

@halcyon-tech/core Any ideas on this?

**Comment by Wright4i** [comment]
@worksofliam how do you feel about `instantiate.ts` since it creates the instance?

**Comment by worksofliam** [comment]
@Wright4i I very much like that name.

p.s. welcome back, hope you had a nice trip

**Comment by Wright4i** [comment]
@worksofliam thanks! South Korea was amazing and a week off work was even more amazing :)
