### ISSUE TITLE
Compilation error gravity 20

### ISSUE THREAD

**Issue by pabloto** [halcyon-tech/vscode-ibmi#984]
Hi,

why RPGLE compilation error gravity 20 are only warning and not red error?

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/9719313/207577000-91f4f737-25b1-4de2-8a20-9edb2f7d67b3.png">

Bye

**Comment by worksofliam** [comment]
Severity 20 is just a Warning inside of VS Code. 

https://github.com/halcyon-tech/vscode-ibmi/blob/master/src/api/CompileTools.js#L16
