### ISSUE TITLE
Library List Used for Actions

### ISSUE THREAD

**Issue by MarkBoyer** [halcyon-tech/vscode-ibmi#985]
I am trying to create custom actions that use a custom create command.  When I perform the action, the output indicates the library list.  I'm curious how this is determined.  It is not the library list associated with my user profile.  If I SSH to the box and display the library list, you can see they are different.  TIA.
![SCR-20221214-ljg](https://user-images.githubusercontent.com/3966735/207738256-3ac53abc-f768-4b90-ba7e-14bb34f3161f.png)
![SCR-20221214-lkv](https://user-images.githubusercontent.com/3966735/207738280-cee1aea1-f877-47ca-a5fa-ea26f615b50f.png)

**Comment by worksofliam** [comment]
The user library list is determined in the User Library List view. I'm not sure if that's the answer you're looking for!

**Comment by MarkBoyer** [comment]
@worksofliam well sure, if you want to put it right in someone's face.  UGH.  I've had that view minimized since the day I installed the plugin wondering why I needed it.  That's perfect and saving them as profile is brilliant.  Thank you!
