### ISSUE TITLE
server disconnect and no any option to reconnect

### ISSUE THREAD

**Issue by shriramji1008** [halcyon-tech/vscode-ibmi#987]
Issue text goes here.

* QCCSID: 273
* Features:
   * git: true
   * grep: true
   * tn5250: true
   * setccsid: true
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: false

Variants
```json
{
  "american": "%23@$",
  "local": "%23§$"
}
```

Errors:
```json
[
  {
    "command": "system \"CRTLIB LIB(RAM10081) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPD0032: Not authorized to command CRTLIB in library *LIBL.\nCPF0006: Errors occurred in command.",
    "cwd": "/home/RAM1008"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPTOIMPF in library QSYS not found.",
    "cwd": "/home/RAM1008"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Object QCPFRMIMPF in library QSYS not found.",
    "cwd": "/home/RAM1008"
  }
]
```

**Comment by worksofliam** [comment]
See the docs page. You can enable buttons to reconnect: https://halcyon-tech.github.io/docs/#/pages/login?id=unstable-connections-reconnect

**Comment by shriramji1008** [comment]
How to debug the sqlrpgle program in vscode
And please show me the program display output while we call the program on
the vscode
