### ISSUE TITLE
Since Version 1.6.1 the connection to Git Client for IBM i does not work anymore

### ISSUE THREAD

**Issue by nedi-dev** [halcyon-tech/vscode-ibmi#991]
**Describe the bug**
Up to Version 1.6.0 the extension "Git Client for IBM i" worked well.
After installing Version 1.6.1 of "Code for IBM i" we receive the message "the directory is no git repository" while using VSCODE git view.

**To Reproduce**
see above

**Expected behavior**
Using the "git-view" in VSC you should see the git informations of the project located on IBM i.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/64408777/208414864-16776c37-eb5e-4a20-98d5-73abcb43fa8a.png)

**Environment (please complete the following information):**
 - Extension version: 1.6.0 > 1.6.1
 - IBM i OS version: 7.3

**Additional context**
The extension "Git Client for IBM i" is not listed in the VSCODE Marketplace anymore - why?

**Comment by worksofliam** [comment]
The git client extension is no longer maintained and is not available to install from the Marketplace.

You are able to build it and fix your issues manually from here: https://github.com/halcyon-tech/git-client-ibmi

**Comment by nedi-dev** [comment]
is there any preferred alternative?
maybe: using command-line git in pase-terminal
or
mapping a drive in Windows with SSHFS-Win
or ??
