### ISSUE TITLE
5250 terminal - Keyboard unlock

### ISSUE THREAD

**Issue by HenryMiller** [halcyon-tech/vscode-ibmi#998]
Hello,
When  keyboard is locked (i.e. typing alpha characters into a numeri field) , I cannot unlock it.
I tried many combinations on my Mac Book Pro  without success.
5250 Terminal Type is  3477-FG , but I tried almost all of them.
Keyboard:  I tried US/English and Italian.
Is there any keyboard configuration file to adjust.
 
<img width="385" alt="Screenshot at Dec 23 10-01-52" src="https://user-images.githubusercontent.com/1829995/209306093-0df5859b-6c1e-454c-a9f5-eaa3562876c9.png">

* QCCSID: 1144
* Features:
   * git: true
   * grep: true
   * tn5250: true
   * setccsid: true
   * GENCMDXML.PGM: true
   * QZDFMDB2.PGM: true
   * iconv: true
   * attr: true
* SQL enabled: true
* Source dates enabled: true

Variants
```json
{
  "american": "%23@$",
  "local": "£§$"
}
```

Errors:
```json
[
  {
    "command": "system \"CRTLIB LIB(ILEDITOR) TEXT('Code for i temporary objects. May be cleared.')\"",
    "code": 255,
    "stderr": "CPF2111: La libreria ILEDITOR esiste già.",
    "cwd": "/home/ADMIN/m11_bob/"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPTOIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Non trovato l'oggetto QCPTOIMPF nella libreria QSYS.",
    "cwd": "/home/ADMIN/m11_bob/"
  },
  {
    "command": "system \"CHKOBJ OBJ(QSYS/QCPFRMIMPF) OBJTYPE(*DTAARA)\"",
    "code": 255,
    "stderr": "CPF9801: Non trovato l'oggetto QCPFRMIMPF nella libreria QSYS.",
    "cwd": "/home/ADMIN/m11_bob/"
  }
]
```

**Comment by worksofliam** [comment]
You want to use control A to grab attention and then F12 to go back.

**Comment by HenryMiller** [comment]
Hi,
It works !
Thank you.
